### ISSUE TITLE
Sort by date column in mod list

### ISSUE THREAD

**Issue by tfriberg** [KSP-CKAN/CKAN#1046]
A date column in the mod list would be usefull so that I could sort by date. Both mod update date and install date would be nice but the former I believe is most usefull.

**Comment by slikts** [comment]
This would be nice, and the columns wouldn't necessarily need to be visible by default; it could just be a context menu on the column header letting the user choose what to show.

**Comment by 7ranceaddic7** [comment]
I'm going to bump this.  A 'Install Date/Time' would be EXTREMELY helpful when trouble shooting.

**Comment by kp0llux** [comment]
why hasn't this been implemented yet?  being able to sort by date/time installed would prove reeeeally helpful when trying to narrow down what's causing the game to fail after installing a handful of mods at a time.

**Comment by 7ranceaddic7** [comment]
Anything on the status of this and #1773?

**Comment by HebaruSan** [comment]
#2514 will close this by adding the install date. The last update date column will continue to be tracked in #1155.
