### ISSUE TITLE
Scraping from KerbalStuff should give us all authors

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1048]
https://github.com/KSP-CKAN/NetKAN/pull/1452 has a `$kref` pointing to https://kerbalstuff.com/mod/855/Antares%20%26%20Cygnus which lists 2 mod authors. However the generated .ckan file in the [log output](http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20NetKAN%20metadata/1827/console) from Jenkins looks like this
```
{
    ...
    "author": "RaiderNick",
    ...
}
```
While one would expect it to be
```
{
    ...
    "author": [ "RaiderNick", "Kartoffelkuchen" ],
    ...
}
```

**Comment by RichardLake** [comment]
Looking at https://kerbalstuff.com/api/mod/855 the kerbalstuff API is not sending both authors. While netkan may need changes if it did it would need to be fixed on KS's side as well.

**Comment by Dazpoet** [comment]
That would indeed nullify my proposal until such a time that the KS API lists all authors, I'll go open an issue over there to see what can be done.

**Comment by Dazpoet** [comment]
Seeing as KS no longer exists this is now a null subject and henceforth I'm closing it.

**Comment by plague006** [comment]
In before "Scraping from SpaceDock should give us all authors" :)

**Comment by Dazpoet** [comment]
:smiling_imp:
