### ISSUE TITLE
wrong client version in console help

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1063]
just done a "ckan.exe --help" on a 1.6.20 ckan.
Second line shows 0.0.0.0 as version.
last line correctly 1.6.20

![ss 2015-06-03 at 06 23 12](https://cloud.githubusercontent.com/assets/1223135/7965423/ac02c2bc-0a1d-11e5-82a8-bae6b1ec674e.png)

**Comment by RichardLake** [comment]
Repeat of #362. Closing in favour of the older report.
