### ISSUE TITLE
gui-with-console isn't working

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1064]
hey,

just wanted to start the gui with the parameter "gui-with-console".
The help lists it as a valid option.
when I try to run "ckan.exe -gui-with-console", it just shows the help, and does nothing else.

I'm running ckan 1.6.20 on windows 8.1.

grettings
postremus

**Comment by RichardLake** [comment]
gui --show-console works while the  "gui-with-console" doesn't.

**Comment by RichardLake** [comment]
And looking at the code has never worked.

**Comment by RichardLake** [comment]
I'm going to remove the command as even if it did work it is a duplication of existing functionality.
