### ISSUE TITLE
Tarsier Space Technology not updating

### ISSUE THREAD

**Issue by PR0ficiency** [KSP-CKAN/CKAN#1066]
Hi team,

Thanks for your awesome project. Two things: CKAN doesn't seem to be getting the latest version of this mod: http://forum.kerbalspaceprogram.com/threads/111157-0-90-Tarsier-Space-Technology-with-Galaxies-(caretaker-release-v4-5d-FIXED-for-0-90!) / https://github.com/JPLRepo/TarsierSpaceTechnology/releases

Also, I am getting a Trojan warning from my antivirus when I run CKAN. Is this something you've heard from other users and is it a known issue? 

2015-06-03 16:17:49	Detected Trojan: HEUR/QVM03.0.Malware.Gen	[Ignored]
Details: 
Trojan name: HEUR/QVM03.0.Malware.Gen
Path: C:\Users\Craig\Downloads\KSP\ckan.exe
2015-06-03 16:17:38	Process Creation	[Auto-blocked]
Details: 
Process: C:\Windows\explorer.exe
Action: Process creation
Path: C:\Users\Craig\Downloads\KSP\ckan.exe
2015-06-03 16:17:33	Detected Trojan: HEUR/QVM03.0.Malware.Gen	[Ignored]
Details: 
Trojan name: HEUR/QVM03.0.Malware.Gen
Path: C:\Users\Craig\Downloads\KSP\ckan.exe
2015-05-30 22:41:13	Modify key settings	[Auto-allowed]

Thanks,

PR0ficiency

**Comment by RichardLake** [comment]
Looking at 
https://www.virustotal.com/en/file/55f4d9b60ccdf96d2e9b8c55b0c05df074653a123b43d72d87addca5e2043c4e/analysis/ seems to suggest it is a false positive.

**Comment by Dazpoet** [comment]
Newest version of Tarsier is now in CKAN :)
