### ISSUE TITLE
The 'compare' command thinks 1.5.01 is both smaller and larger than 1.5.1

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1076]
Problem initially located in https://github.com/KSP-CKAN/NetKAN/pull/1516

When comparing 2 strings on the form `x.0y` and `x.y` the result is always `-1` when run through the `ckan compare` commmand.

**Comment by dbent** [comment]
To clarify, the bug is that even when the arguments are transposed the result is always `-1`:

```
> ckan compare 1.01 1.1
-1
> ckan compare 1.1 1.01
-1
```

**Comment by RichardLake** [comment]
> Then the initial part of the remainder of each string which consists entirely of
digit characters is determined. The numerical values of these two parts are
compared, and any difference found is returned as the result of the
comparison. 

My reading of the "correct" behaviour in this case is too have them return 0.

**Comment by pjf** [comment]
Oh dang. And thank you.
