### ISSUE TITLE
Enhancement: Add the ability to navigate to a mod from the "Relationships" tab in the gui client

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1082]
Saw this on the [KSP forums](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-21-5-Jun-2015?p=2001947&viewfull=1#post2001947) posted by deeperman and thought it was a good idea:

"please add the ability to navigate to the desired modification"
http://imgur.com/h7olv5e

Essentially, when a user double clicks on a mod in the relationship viewer it changes the selected mod (or changes the filtering) to that mod.

**Comment by Postremus** [comment]
Would like that Feature too

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎07.‎06.‎2015 13:03
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] Enhancement: Add the ability to navigate to a mod from the"Relationships" tab in the gui client (#1082)

Saw this on the KSP forums posted by deeperman and thought it was a good idea:
"please add the ability to navigate to the desired modification"
http://imgur.com/h7olv5e
Essentially, when a user double clicks on a mod in the relationship viewer it changes the selected mod (or changes the filtering) to that mod.
