### ISSUE TITLE
Inline End-of-Line Comments

### ISSUE THREAD

**Issue by Murdabenne** [KSP-CKAN/CKAN#1084]
Not quite sure if this is the correct venue, but this is a feature request.

Please add in the ability to have comments in an inline fashion.  Basically, get the "//" (or whatever else is accepted) and ignore the bit after that, until end-of-line.  This allows manually generated netkan and ckan files to be a bit more self explanatory to newbie folks, like myself.  Otherwise whoever is trying to follow on with what I am doing, or else myself in about 3 months, will have no clue why or what a setting was done a particular way (unless they are an expert in CKAN).

**Comment by dbent** [comment]
`.ckan` and `.netkan` files are strictly valid [JSON](http://json.org/) documents, which don't allow javascript-style comments. Instead, a [comment](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#comment) field can be used instead, and is used in [several](https://github.com/KSP-CKAN/CKAN-meta/search?utf8=%E2%9C%93&q=comment) where there is special need to mention why something was done.

**Comment by Dazpoet** [comment]
As specified above, use the comment field instead :+1: 

Closing this since I don't see us changing away from strict JSON anytime soon.

**Comment by birdspider** [comment]
it's about the .ckan .netkan files  (mod-packages, mod-definitions) ?

if they are "manually" created I recommend putting them into some sorts of vcs, there you can comment in the commit-msgs or keep a README/CHANGELOG of some sorts

**Comment by dbent** [comment]
`.ckan` files are under version control in the [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta) repository and `.netkan` files are under version control in the [NetKAN](https://github.com/KSP-CKAN/NetKAN) repository.
