### ISSUE TITLE
Exporting all installed mods as a human-readable list from within the gui

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1094]
Seen this request a few times now so though I'd put it here for tracking.

From what I gather users want a way to export a complete list of mods they can post in e.g. the forums (so not a metapackage).

I normally generate something like this with the command `ckan list --porcelain > list.txt` but that one also has the CKAN specific symbols at the start to show if it's upgradeable, unknown, AD etc so it might not be ideal.

If the reason for wanting these lists are showing what mods are needed for something or for helping in tracking down bugs it would seem to me that the versions of mods might also be pertinent to include. Not sure all users agree though.

**Comment by dbent** [comment]
*Musings:* The save file dialog that appears when you go to `File | Export installed mods...` could have another couple of file types:

- `Plain text (*.txt)` that would export a "pretty" list of mods with their name, CKAN identifier, and version.
- `Comma-separated values (*.csv)` that would export as much "top-level" data as possible. Relational data like, uh, *relationships* would be omitted as there's no common way to express that in a CSV. Users who are at least semi-competent with a text editor or spreadsheet can then hack at this to produce whatever kind of output they want.

The command line client  `list` command could also take a `--export` flag that would take one of the file types and dump the output to stdout. Users could then do a redirect to whatever file they want.

**Comment by dbent** [comment]
Other useful formats functionally equivalent to the "pretty" plain text format:

- `Markdown (*.md)`
- `BBCode (*.bb.txt)` (I know of no common file extensions for text files containing BBCode)

**Comment by Dazpoet** [comment]
I totally agree with the above :+1:
