### ISSUE TITLE
Relationships window is not refreshed after instance change

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1096]
Steps to reproduce:
1) Chose a mod, and go to it's relationships window
2) Change your ksp install
3) The Relationship windows is still present, showing the relations off the suggested mod in grey.

Tested using ckan 1.6.22, on windows 8.1

**Comment by Postremus** [comment]
further testing showed, that this only occurs with an empty registry.

**Comment by HebaruSan** [comment]
I tried this just now and the relationships tab showed the relationships of the newly selected mod in the new instance.
