### ISSUE TITLE
gui does not mark mod with missing dependency red

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1105]
Once "Kerbal Construction Time RP-0 Config" is selected, the gui says that Module RP-0 has not been found. RP-0 (Realistic Progression) is a dependency of that config.
The Gui should mark this config red, like it does with conflicting mods.

**Comment by HebaruSan** [comment]
This is like a poor man's version of #2231. If we were going to attack this use case, I would think that the desired outcome would be that the checkbox isn't even there.
