### ISSUE TITLE
OSX can't locate installations

### ISSUE THREAD

**Issue by beldougie** [KSP-CKAN/CKAN#1109]
I have all of my KSP installs (and all of my Steam games to be fair) on an external drive that is accessed via `/Volumes/{drivename}/STEAM_LIBRARY/steamapps/common/`. I can run CKAN using mono, no problem, but when I click the 'add new' button, the path tree is wrong. It seems to think it's on Windows or something, but it starts at Desktop and then won't let me traverse higher in the tree (my desktop is some 4 or 5 nodes below the root of the drive.

This makes it unusable because I can't access the installations I have. Would love to try this out at some point though if you can address this. Cheers,

**Comment by beldougie** [comment]
However, I have just installed with homebrew and with the command line I'm able to access the correct installations ok - it's just running from `mono ckan.exe` seems to nerf the path detection.

Hope that helps

**Comment by craigmaslowski** [comment]
I'm having a similar problem. My Steam games are installed on a second internal hard drive. I cannot see that volume regardless of whether I run `mono ckan.exe` or install the homebrew version and run it. I had to use Terminal and the command line options to get my install recognized.

`ckan ksp add Main /volumes/data/SteamLibrary/SteamApps/common/Kerbal\ Space\ Program`

**Comment by pjf** [comment]
Adding @McJones to this issue, who's also reported this.

`KSPPathUtils.cs` contains the Steam detection code. I'd love a patch that *does* find KSP under OSX. :)

**Comment by pjf** [comment]
Closing this with the application of #1480; our next release (today) should show some relief. :)
