### ISSUE TITLE
Json database corruption when Update of Repositories is interrupted.

### ISSUE THREAD

**Issue by LdpA** [KSP-CKAN/CKAN#1114]
I was updating my installed mods from a wireless access point on my laptop, when the connection was suddenly dropped halfway through updating/refreshing the list.

Ckan suddenly reverted to a blank screen (no mods listed) and when I opened it again all references to my installed mods had been lost. Checking the files I noticed that my registry.json had been reverted to 0 bytes. Luckily I had a backup of the previous night so I simply restored the original file and everything was back to normal.

Don't know why exactly this happened, but it would teach me not to use public wifi spots to update my mods :)

**Comment by Postremus** [comment]
Was able to reproduce it.
