### ISSUE TITLE
Ermergerd @pjf is actually working for a client this week

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1115]
Ahoy everyone,

Just a quick note to say that I'm *actually working* for my honest-to-goodness-day-job for this week (ending 19th June), and I'm writing to you all from my our beautiful capital city, Canberra. During this time getting hold of me will be a little more tricky than usual (although late last week had me preparing to work, with me also being away).

My next sprint is on Sunday 21st, and I hope to be catching up with a backlog of everything (especially PRs) when that happens. If there's something that needs my attention, please do mention me with @pjf, and if something urgently needs my attention then a private message on the forums works well, and both @techman83 and @NathanKell have more direct details for me.

Due to the wonders of our bots, this message will auto-close in a week (but I hope to close it before then when I'm back).

Keep being awesome,

~ Paul

**Comment by pjf** [comment]
And I'm back!

**Comment by techman83** [comment]
Yay!
