### ISSUE TITLE
Add Webhook support

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1118]
Instead of having netkan query repositories for changes at least for Bitbucket-hosted repositories an alternative would be to use webhooks as documented on https://confluence.atlassian.com/display/BITBUCKET/Manage+Webhooks
A request to create an entry for a new version could be as simple as "creating ckan-version" somewhere in the commit-message

**Comment by janbrohl** [comment]
this could be a way to address issue #865

**Comment by plague006** [comment]
We now have self-published metadata (issue #865) and nobody has replied to this in over 8 months. If someone thinks this should be implemented feel free to re-label as appropriate. Auto-closing in 1 week.
