### ISSUE TITLE
Heat Control

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1121]
Heat Control and Heat control core conflict.  and on top of this it seems I can't install heat control at all even if the core is not installed.

**Comment by Bit-Fiddler** [comment]
actually my mistake...  heat control no longer updates as it says it is not compatible with deadly reentry not the core as I originally thought

**Comment by damerell** [comment]
Fixed in  KSP-CKAN/NetKAN#1619.

**Comment by dbent** [comment]
Closing as the conflict has been removed.
