### ISSUE TITLE
Configuration file management

### ISSUE THREAD

**Issue by damerell** [KSP-CKAN/CKAN#1122]
This stems from an IRC discussion (http://pastebin.com/U9DRiCJw).

It would be nice if CKAN handled configuration files more gracefully. I suggest a dpkg-like behaviour, as follows:

Package metadata includes a statement of which files are configuration files. (If metadata says nothing, guess that all .cfg files are configuration files? Maybe?)

When updating a package, if a configuration file has been edited from the last package-supplied version, alert the user and permit them to select the old or new version. Squirrel away the unselected version for user's later reference.

When removing a package, distinguish "remove" and "purge". "Remove" squirrels away the configuration files and replaces them if the package is later reinstalled. dpkg leaves them in-situ, but in a KSP world it is probably better to hide them in CKAN's directory so that GameData is not full of ghost directories for uninstalled packages.

**Comment by pjf** [comment]
Super-relevant ticket: #949.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN/issues/949 by its virtue will address this and change the way we can install configs. Closing in favour of https://github.com/KSP-CKAN/CKAN/issues/949
