### ISSUE TITLE
Failed to connect to repository - CKAN v1.6.23-0-gd76e0ba (beta) Ubuntu 14.04

### ISSUE THREAD

**Issue by Macel** [KSP-CKAN/CKAN#1125]
CKAN v1.6.23-0-gd76e0ba (beta) on ubuntu 14.04 shows the following errors after opening it up and attempting to refresh the repository:

```
\2343 [1] WARN CKAN.URLHandlers (null) - Skipping URL handler: Parsing Error: Could not parse file ~/.local/share/applications/mimeapps.list
11563 [1] ERROR CKAN.ErrorDialog (null) - Failed to connect to repository. Exception: An error occurred performing a WebClient request.
```

Note that the autoupdate portion works fine at startup, and that I have run the mozroots --import command.. 

The repository URL is what was default at install: https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip

**Comment by pjf** [comment]
That's odd. Can you confirm this is still an issue? This could just be a temporary network error...
