### ISSUE TITLE
Refreshing should not wipe list of selected mods

### ISSUE THREAD

**Issue by joflashstudios** [KSP-CKAN/CKAN#1129]
The refresh button is quite close to the filter by mod name box. If someone is working on a large changeset and accidentally clicks the refresh button when trying to search, it wipes out their changeset. This can be quite frustrating on large installs, when the user has to go back and re-select 100+ mods again.

And no, of course this didn't happen to me... I'm not that clumsy... :)

**Comment by pjf** [comment]
This is an absolutely solid feature request. Putting it on our list of things to do. Thank you very much!

**Comment by HebaruSan** [comment]
I believe this was done in #2552 (or earlier).
