### ISSUE TITLE
Spec should say that installing to Ships subfolders is fine, but creating Ships subfolders is not.

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1134]
Currently we're not allowed to install to subfolders of the Ships folder in accordance with the spec. It would be pretty nice if we could do this since a lot of mods package .craft files directly into their .zips or just smacked into a single folder named CRAFT or Ships or something else we cannot handle.

I'm not sure why this restriction was put in from the start but I think it should be removed now.

**Comment by pjf** [comment]
Wait, we can't install into SPH/VAB? Are you sure?

**Comment by pjf** [comment]
We don't let mods *create* folders in `Ships`, but we should allow installing to existing folders.

(It might be sensible re-create VAB/SPH/@thumbs if they're otherwise lost or removed by the user, though...)

**Comment by Dazpoet** [comment]
I guess I've misinterpreted
```
(v1.2) For GameData only one may specify the path to a specific subfolder; for example: GameData/MyMod/Plugins. The client must check this path and abort the install if any attempts to traverse up directories are found (eg: GameData/../Example).
```
then because I thought the spec meant we're not allowed to install to a subfolder (like SPH/VAB) anywhere but the `GameData` folder?

The above snippet was fetched from [here](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#install)

**Comment by pjf** [comment]
D'oh, we should update that.

In GameData we create directories as needed. At the moment we don't create directories in `Ships`, but we absolutely allow the destination to be specified.

Decorating this ticket with tags appropriately.

**Comment by plague006** [comment]
I tried this out because I needed this feature to resolve #1736 cleanly. I tried a [.netkan](http://pastebin.com/PQqNEVT0) with netkan.exe and [it failed](http://imgur.com/va1sbtw). I also tried a [.ckan](http://pastebin.com/9DT6sMnC) with ckan install and [it failed](http://imgur.com/0lKg900) as well. In both cases, they would let me install the .craft files directly into the `Ships` folder but not the `Ships/SPH` folder.
