### ISSUE TITLE
Cancelling update of mods throws an CKAN.CancelledActionKraken: 

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1138]
hey,

I am using ckan 1.8.0 on windows 8.1, ksp 1.0.2.

just cancelled the download of mod updates. It was at the "Spacey" pack, and got this error:

``` 
CKAN.CancelledActionKraken: Download cancelled by user
   bei CKAN.NetAsyncDownloader.DownloadModules(NetFileCache cache, IEnumerable`1 modules)
   bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, NetAsyncDownloader netAsyncDownloader)
   bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

The gui should catch this, and just "fail" silently. The user knows, when he pressed the cancell button. :)

**Comment by pjf** [comment]
You're right, this shouldn't be visible to the user.

Does this still occur with CKAN v1.8.3?

**Comment by Postremus** [comment]
Tested in 1.8.4, does not occure anymore.
