### ISSUE TITLE
Mods conflict with themselves on upgrade

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1139]
hey,

wanted to update OPM from 1.7_Beta_2.repackaged0 to 1:1.7. It has thrown the following exception during the update:

```
The following inconsistencies were found:
OuterPlanetsMod 1:1.7 conflicts with OuterPlanetsMod 1.7_Beta_2.repackaged0, can't install both.   bei CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, NetAsyncDownloader netAsyncDownloader)
   bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

I am using ksp 1.0.2 on window 8.1, with ckan 1.8.
The gui should probably handle inconsistencies in a better way, for example marking the mod red when you want to update it.

**Comment by pjf** [comment]
Gosh dang, is this different to #930 ? Mods shouldn't be able to conflict with themselves.

Doing moar testing now!

**Comment by pjf** [comment]
Good news is that upgrades of things which aren't OPM seem to be working for me, so that's good.

@Postremus : Do you get the same issue if you try to do the upgrade on the command-line?

**Comment by Postremus** [comment]
yup, the issues are mostly the same. But OPM should be repackaged at least. I still want to update it.

Exception on the command line:
```
Unbehandelte Ausnahme: CKAN.InconsistentKraken: Eine Ausnahme vom Typ "CKAN.Inco
nsistentKraken" wurde ausgelöst.
   bei CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, NetAsyncDownloade
r netAsyncDownloader)
   bei CKAN.CmdLine.Upgrade.RunCommand(KSP ksp, Object raw_options)
   bei CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by pjf** [comment]
I got an upgrade error with RP-0. Drat. Investigating harder.

**Comment by pjf** [comment]
Traced to 782363fb3778d93c5f3df26060413e3461203b7e via git bisect and discovering RP-0 can conflict with itself on upgrade via the cmdline.

29e0ece03076873710aa44bcfc6ab1e3ab689cdb claims to fix this, but doesn't seem to contain any non-whitespace changes. Working on a patch now.
