### ISSUE TITLE
Automatic uninstall of required mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1145]
Some mods require other mods to be installed.  If you are installing a single mod with a number of dependencies, it can then be confusing to figure out which ones should be uninstalled.

My suggestion is to do the following:

1.  If there are dependencies, check all the other installed mods to see if any of those have the same dependency.
2.  If no other mod has that dependency, offer it to the user as an option to uninstall it, similiarly to the way that suggested mods are offered when installing

**Comment by pjf** [comment]
Hooray! This is #978, so I'm copying the discussion over there to keep everything in one place.

**Comment by pjf** [comment]
Or not copying the discussion, because #978 has a pretty good implementation strategy, and I think it defaults to what we have here if the user takes no action to explicitly protect mods that were installed as part of relationship resolution. :)

And yes, this is something we'd love. :)
