### ISSUE TITLE
Curse support

### ISSUE THREAD

**Issue by BobPalmer** [KSP-CKAN/CKAN#115]
I didn't see it floating around, but given the request for folks to use repos *other* than the official one, you should really consider Curse support if you wish for this project to achieve a more universal adoption rate.

**Comment by pjf** [comment]
Curse don't have an API that we can use, so we can't really do this in terms of automatic indexing. Marking this as closed for now; we can (and do) manually index curse-only mods, but that requires a volunteer or the mod author making sure their info is being kept up to date.
