### ISSUE TITLE
Amsterdam mirror is down

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1151]
Hey,

The Amsterdam metadata mirror (http://amsterdam.ksp-ckan.org/master.zip) is down.
It just gives an 404.
The problem is, that it is linked in the ckan-gui in the repositories.
It should either be a mirror again, or at least redirect to the default one.

**Comment by plague006** [comment]
Considering ksp-ckan.org is kinda dead, I'm closing this.
