### ISSUE TITLE
Is "depends" required in metapackages?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1172]
I am generating metapackages (in my [web-view](http://forum.kerbalspaceprogram.com/threads/125487-CKAN-Web-View) and I am not sure if "depends" is needed even if empty or if there just has to be any relationship or they are optional.
The spec does not say anything about that yet but the [example in the wiki](https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29) has the field "depends".

This issue intersects with #1152

**Comment by Dazpoet** [comment]
I am 98 % sure depends is not required but recommend you TIAS :)

**Comment by janbrohl** [comment]
What is TIAS?

**Comment by Dazpoet** [comment]
Try It And See :)

**Comment by Postremus** [comment]
Recommends also workss for metapackages.
