### ISSUE TITLE
Spec is stricter about mod versions than extant ckan releases

### ISSUE THREAD

**Issue by toadicus** [KSP-CKAN/CKAN#1174]
The spec says:

>The mod_version may contain only alphanumerics and the characters . + (full stop, plus) and should start with a digit.

However, this is not enforced when importing from KerbalStuff.  This results in occasionally-unwanted behavior wherein older versions sort ahead of newer versions because of non-comforming elements, e.g.

`v0.15.3_Froude`

sorts as newer than

`v0.15.3.1`

Since "\_" is not in the spec, perhaps everything after the "\_" should be ignored when sorting?

**Comment by pjf** [comment]
D'oh. This is one of the cases where I think we should change the spec; we can't really stop mod authors releasing with all sorts of funny names, and I suspect ignoring part of the version string *will* break already indexed files which utilise strange version systems.

Having said that, #834 is relevant here for "well-behaved" mods.

In any case, I'll go bump the epoch for FAR if it's sorting incorrectly, which should fix this issue.
