### ISSUE TITLE
Tell us what works with KSP 1.0.4

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1184]
All these KSP releases mean a lot of mods haven't been updated to be listed as KSP 1.0.4 compatible. Ideally, they get updated on kerbalstuff or with new `.version` files, but if we have to then we can fix these by hand.

This ticket is designed to be a landing zone for 'mod X works on KSP 1.0.4'. Please include the following information:

* Mod name
* Mod CKAN identifier (if known)
* A link to the mod author/maintainer stating that it's working as intended under KSP 1.0.4

This *may* be obsoleted by whatever comes out of #1173, which seems pretty relevant now, and may result in the implementation of #1160 so it can be sensibly carried out.

I'll be editing comments made on this issue to include additional information and mark-up where appropriate.

See [this forum post](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-\(CKAN\)-Package-Manager-v1-8-4-26-Jun-2015?p=2041017&viewfull=1#post2041017) for context.

**Comment by SkyMarshal** [comment]
One thing that may need addressed, actually, is some really stinking out of date versions are reported as compatible due to the lack of a corresponding max for "version_min" tags in some .ckan files.  For example, Editor Extensions is reporting v2.3 as compatible (released 2014/12/24 for version .90).

**Comment by pjf** [comment]
@SkyMarshal: D'oh! We caught a *lot* of these in #1156 and friends, which ironically caused much unhappiness because now the CKAN wouldn't install old and broken versions of mods when newer but incompatible ones existed.

Putting in a fix for Editor Extensions v2.3 now, but if you have any more examples we'd *love* to know about them. As we're indexing about ~800 mods now (and *thousands* of releases) it really helps to have human feedback for where things have gone wrong.

**Comment by SkyMarshal** [comment]
PlanetShine is showing an old version, but I bet it is compatible.  CrowdSourceScience is definitely compatible, but there is a 3.0.1 version out whereas CKAN shows v3.0.

**Comment by SkyMarshal** [comment]
I'd also wager the planet-adding mods (Kopernicus, Outer Planets, etc.) are compatible.  On a semi-related note, it'd be nice to allow incompatible mods to be installed.  A big red button on the UI would feel appropriate.

**Comment by pjf** [comment]
@SkyMarshal : You may be looking for the discussion at #1173. :)

**Comment by SkyMarshal** [comment]
That's precisely it, although I would not have thought to search for that title xD

**Comment by pjf** [comment]
- [ ] TACLS is reported to work fine under 1.0.4 (Reported by @SkyMarshal in #1190)

**Comment by SkyMarshal** [comment]
[The SETI-Contracts mod is acknowledged by the author to work with v1.0.4.](http://forum.kerbalspaceprogram.com/threads/106130)

**Comment by SkyMarshal** [comment]
[KIS has also been reported functional in v1.0.3](http://forum.kerbalspaceprogram.com/threads/113111?p=2035088&viewfull=1#post2035088)

**Comment by SkyMarshal** [comment]
[Outer Planets mod seems to work in 1.0.3 and .4](http://forum.kerbalspaceprogram.com/threads/104280?p=2036057&viewfull=1#post2036057)

**Comment by pjf** [comment]
With #1197 we should be able to do some pretty awesome overrides on a per-release basis (ie: "for the current release, change the metadata like X, but trust future releases"). :)

**Comment by pjf** [comment]
We found a bug in the `.version` file packaged with SETI-Contracts, which Yemo fixed within *minutes* of me reporting it. TACLS fixes are awaiting review. Working on the others now. :)

**Comment by SkyMarshal** [comment]
I am pleased to hear that.  Seems the sudden transition from 1.0.2 to 1.0.4 kicked off a serious round of bug stomping for the CKAN.  Also, I was highly amused as, when I went in to work Friday, I was searching for some way to wipe parts of memory which contained sensitive information in Perl (right now I'm supporting a set of legacy scripts that handle plaintext usernames and passwords) and I found your post on the topic.  It just seemed ironic as hell, interacting with someone for the first time bug fixing something for a game and stumbling across something of theirs the day afterwards at work.

P.s. yes yes, I know, plaintext passwords are evil.  I've gotten it to the point where they no longer get printed in stack traces (wtf, right?) and am looking into something like OAuth tokens to replace that system.

**Comment by valuial** [comment]
I have BDAnimationModule and Toolbar from BahamutoD and blizzy78 respectly running in 1.0.4, no problems so far.

**Comment by valuial** [comment]
- [x] [The SETI-CommunityTechTree mod is acknowledged by the author to work with v1.0.4.] (http://forum.kerbalspaceprogram.com/threads/106130)

**Comment by plague006** [comment]
I think we're good on the 1.0.4 catchup at this point.
