### ISSUE TITLE
CKAN fails to download TACLS

### ISSUE THREAD

**Issue by SkyMarshal** [KSP-CKAN/CKAN#1190]
![ksp5](https://cloud.githubusercontent.com/assets/1243563/8370213/83c44bd2-1b79-11e5-9bb4-cde6cafc8e26.png)

**Steps to reproduce**: Check TACLS and try to install.

**Detailed Errors**:
```
Failed to download "https://kerbalstuff.com/mod/733/TAC Life Support/download/0.11.1.20" - error: The remote server returned an error: (404) Not Found.
```
(Note that the actual link stopped after "TAC")

```
About to remove:

Done!

About to install...

 * TACLS 0.11.1.20
 * ModuleManager 2.6.6 (cached)
 * TACLS-Config-Stock v0.11.1 (cached)

Downloading "https://kerbalstuff.com/mod/733/TAC Life Support/download/0.11.1.20"



Error!
```

**Comment by SkyMarshal** [comment]
Figured it out.  I really do not like the kerbal stuff website.  Something caused a hiccup (possibly @taraniselsu uploaded a version then pulled it down?  I don't know how the system works there) and [a bad .ckan file](https://github.com/KSP-CKAN/CKAN-meta/blob/master/TACLS/TACLS-0.11.1.20.ckan) was generated... with a bad version and URL... that is also marked as versioned for KSP 1.0... which is interpreted by CKAN as being valid for any KSP version with that prefix.  Kinda a perfect storm here to screw up the system.  IMO, we should point it back at the github repository.

**Comment by SkyMarshal** [comment]
Additionally, forumgoers report TACLS seemed to work on v1.0.3 (despite KSP-AVC giving them an earful) which prooobably means it works fine with v1.0.4.

**Comment by pjf** [comment]
@SkyMarshal : You're my new favourite person.

Fixing now. :)

**Comment by NathanKell** [comment]
For the record, I have a hard time imagining anything that changed in 1.0.3 affecting TACLS.
