### ISSUE TITLE
CKAN should not remove ship folders if empty on uninstall

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1191]
As reported by @SkyMarhsal in #1189, the CKAN will *remove* subdirectories
(VAB, SPH, etc) if a mod that includes craft files (eg: FAR) is uninstalled
and the directory is then empty.

The CKAN should never be deleting these directories, and realistically we
should probably be *creating* the system Ships subdirectories if they
don't exist.

Hopefully this is a simple patch to `ModuleInstaller`. :)

**Comment by RichardLake** [comment]
Just to be clear is it removing ships/VAB or ships/@thumbs/ and subdirectories? The former should be impossible - the code only calls directory.delete in one place and that has a guard for the directories. However it was never updated with 1.0.0 to include @thumbs and its subdirectories ...

**Comment by martinnj** [comment]
The addition is based on pjf comment "The CKAN should never be deleting these directories, and realistically we should probably be creating the system Ships subdirectories if they don't exist." which I took to mean if the directories are missing for whatever reason, just recreate them, even if they we're manually deleted. If I'm wrong I can close the RP.

**Comment by RichardLake** [comment]
Just spent some time checking - I can get ckan to remove @thumbs/VAB, @thumbs/SPH and @thumbs but not VAB or SPH. If I am correct the "proper" fix is to add the three directories to the guard on line 773 of ModuleInstaller.cs 

Even with a fix it will still be worthwhile recreating them but doing so in uninstall seems a odd location. Having them missing will cause issues when installing modules, or while playing KSP, not while uninstalling.

**Comment by martinnj** [comment]
Right, I'll take another gander at it. Should I let the PR stay open or just close it and create another one once it's fixed?

**Comment by RichardLake** [comment]
As far as I know either way would be fine - it isn't like there is discussion on the PR which would be lost if you made a new one.
