### ISSUE TITLE
Usage of filter_regexp vs include/exclude with wildcards

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1192]
When analyzing the CKAN repository to find out which regexes are actually in use i saw that there are only 22 distinct regexes.

`["PluginData/TacLifeSupport/LifeSupport\\.cfg$", "CrossFeedEnabler.dll", "\\.ddsified$", "Rework_License.txt", "Agencies", "Kosmos_Readme.txt", "KerboKatzUtilities.version", "^(?!CustomBiomes/PluginData/)|config.xml", "ModuleManager.*dll$", "KKInterfaces.dll", "(?<!Basic Asteroids\\.cfg)$", "SmokeScreen_", "Flags", "(?<!img_buttonAdvancedFlyByWire.png)$", "ModuleManager.+\\.dll", "Readme_CFE.txt", "^(?!GameData/ThunderAerospace/TacLifeSupport/PluginData/TacLifeSupport/LifeSupport.cfg)", "(?<!Trans-Jool\\.cfg)$", "^(?!FinePrint/FinePrint.cfg)", "LazTekDragonDock", "Rework_TweakScale.cfg", "KerboKatzUtilities.dll"]`

To me it looks like simpler (case-insensitive) include/exclude directives using only `*` and `?` could be a better solution for most of them. (filter would then just be a special case of exclude)

**Comment by plague006** [comment]
No response in 7 months. Adding a support tag to this to give people a week to see if this goes anywhere or if it's a non-issue.
