### ISSUE TITLE
"Delete" a KSP install could be interpreted as deleting it on disk

### ISSUE THREAD

**Issue by BebopKerman** [KSP-CKAN/CKAN#1194]
Minor UI issue in this screen...
![image](https://cloud.githubusercontent.com/assets/12983857/8387881/ed4acf56-1c21-11e5-8053-ae4957b60056.png)

I hesitated before removing an install I had renamed. (Not for long, because 1. it was a backup and 2. CKAN was cautious about deleting stuff elsewhere.) But I think it could confuse other users.

Proposed solution: add a tooltip to the Delete button reassuring the user that their install won't be deleted on disk.

**Comment by dbent** [comment]
"Forget" is probably a suitable replacement.

**Comment by BebopKerman** [comment]
Oh that's good. Better than my idea of "remove" and easier to change than a
tooltip!

**Comment by pjf** [comment]
Forget is what the command-line uses, too. :)

Merging @Postremus' awesome PR. There'll be a new release tomorrow after my sprint, if not sooner. :)
