### ISSUE TITLE
NetKAN should warn, not fail, on KSP-AVC errors (when version info already exists)

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1199]
KSP-AVC `.version` files are notorious for containing errors. When we first added the functionality to `netkan.exe` I thought it was bugged, because the first six mods I tested it on failed. It turned out humans just aren't very good at writing JSON unless there's a bot reminding them about when they've made mistakes.

At the moment, if a `.version` file fails to parse, we abort indexing. Unfortunately, that means we miss out on new releases until someone spots what's going on, which can take a while.

I'd like to propose that if a `.version` file fails to parse, but we _do_ have version data from another source (eg: KerbalStuff), then we produce a warning, and continue as if there was no `.version` file present.

If we don't have version info from another source, then we continue to bail, to avoid writing a clearly errorneous "universal" release of the mod.

**Comment by pjf** [comment]
What's more, we should do the check to see if we bail *after* override sections have processed. That means we can pop in an `x_netkan_override` for something that would normally rely upon a working `.version` file to supply all the version information.

**Comment by HebaruSan** [comment]
Not sure what the state of the art was when this was written, but nowadays if there's a problem parsing a .version file:

1. The error shows up on http://status.ksp-ckan.space
2. We notice it relatively quickly
3. I submit a pull request to fix it, or post on the mod's forum thread if there's no repo
4. Mod authors generally fix and re-release in a timely fashion (only one such error exists right now)

This is a pretty good situation, and I'm not sure it would be better to be generating semi-invalid metadata. Do we still want this suggestion?

**Comment by pjf** [comment]
@HebaruSan : This is absolutely representing things when CKAN/NetKAN were in their infancy, and certainly sounds like it's no longer needed. Closing with great joy and immense gratitude for all the tremendous work that you do!
