### ISSUE TITLE
Linux Error

### ISSUE THREAD

**Issue by Kosti1** [KSP-CKAN/CKAN#1214]
Log:
Unhandled Exception:
System.TypeInitializationException: An exception was thrown by the type initializer for CKAN.Net ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: An exception was thrown by the type initializer for CKAN.Net ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  --- End of inner exception stack trace ---

**Comment by RichardLake** [comment]
Could you please give the output of "mono --version" and which linux distro you are using?

**Comment by Kosti1** [comment]
ok

**Comment by Kosti1** [comment]
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by Kosti1** [comment]
I fixed it.

**Comment by RichardLake** [comment]
Was it apt-get install mono-complete or other mono packages?
