### ISSUE TITLE
Cannot uninstall incompatible mods via GUI

### ISSUE THREAD

**Issue by squizzeak** [KSP-CKAN/CKAN#1221]
When viewing the incompatible filter, unchecking the 'install' box on mods that were installed prior to the KSP update leaves the 'go to changes' button greyed out, preventing one from uninstalling those mods.

Removing via the CLI (ckan remove) functions without issue.

**Comment by attisan** [comment]
confirming bug: some here

**Comment by Postremus** [comment]
Was not able to reproduce this. I installed "Advanced flyby Wire", which latest version is for 0.90.0. I then was able to uninstall it in 1.0.4.

**Comment by squizzeak** [comment]
Reproduction steps would likely include installing a max-1.0.2 mod while 1.0.2 is the installed KSP version, then upgrading KSP to 1.0.4, and attempting to uninstall the 1.0.2 mods from the incompatible list (that was my experience, anyways).

It's possible this has been remediated by some other recent changes, so next time KSP updates are pushed down by steam I'll report back whether it's still occurring under the later versions.

**Comment by Postremus** [comment]
I retested it. I installed "0.35m SSR MicroSat and Airlaunch Vehicle" in 1.0.2. It is a max 1.0.2 mod.
I then "upgraded" (edited the Version manually) to 1.0.4. I  am able to uninstall the mod.

**Comment by squizzeak** [comment]
Have you tried installing under 1.0.2, closing CKAN, upgrading KSP, starting CKAN, and then attempting to uninstall?

I am still able to reproduce under a recent dev build (with 1.0.4 installed) by attempting to uncheck ExceptionDetector (which was installed during the 1.0.2 era).  Apply changes remains greyed out and the uninstall is unable to be executed.

**Comment by Postremus** [comment]
Yes, exact same steps. Would you please export your modlist, and paste the link to it in here?

**Comment by squizzeak** [comment]
Modlist exported to https://dl.dropboxusercontent.com/u/591783/1221.ckan

**Comment by squizzeak** [comment]
Let me know if a screencast would work, I'll record the behavior and post it to youtube or something.

**Comment by Postremus** [comment]
How did you install the "HotRockets EmissivePatch"? CKAN just crashes when i want to install it.

**Comment by Postremus** [comment]
Anyway, got a dev build. Would you please test it? https://dl.dropboxusercontent.com/u/46071056/CKAN/ckan.exe

**Comment by squizzeak** [comment]
Here's the applicable piece from registry.json for HotRockets Emissive Patch: http://pastebin.com/RER0GkKB

Will proceed with testing the dev build.

**Comment by squizzeak** [comment]
Same behavior; unchecking 'ExceptionDetector' while viewing the Incompatible filter still leaves 'Apply Changes' greyed out.

Here is the entry in registry.json for this mod: http://pastebin.com/wzmEkZJS

**Comment by Postremus** [comment]
Still not able to reproduce it. :(

**Comment by squizzeak** [comment]
I suppose go ahead and close this out as can't reproduce (as I said, CLI works fine, so there's a known workaround) and I'll reopen if I can find reliable repro steps.
