### ISSUE TITLE
What happened to Daz?

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1224]
Bug: Daz is no longer around

Reproduction steps: 1) assign Daz to a job which include long days and 2 hours of travel each day. 2) have said job primarily be about indexing of metadata for a GIS and poking about in an issuesystem, making Daz very tired of computerwork

Solution: wait until the last of july when current workload ends.

I guess one could say I am living the dream since my hobby is all of a sudden my work :p Unfortunately this make me less inclined to do the same thing once I have a few minutes to spare at home and ergo I haven't really been around lately. Just thought I would let you know. Keep being awesome!

**Comment by techman83** [comment]
@Dazpoet :+1:

**Comment by pjf** [comment]
@Dazpoet: You are *amazing*. Thank you *so* much for all your help and contributions. Really, having you around has been really, really wonderful.

I hope that your new job is going really well, and if you do find yourself back in CKAN land I'm sure we'll be really happy to see you! <3

**Comment by plague006** [comment]
I agree with @pjf's label and offer my support to @Dazpoet. =)
