### ISSUE TITLE
CKAN shouldn't start two KSP instances on double-click

### ISSUE THREAD

**Issue by Icemanau** [KSP-CKAN/CKAN#1232]
I've been using CKAN for a short while and one thing I have noticed is that it is possible to have two instance of KSP start if you double click on the Launch KSP button.

Ideally, CKAN should check for an instance of KSP before starting a new one.
If one is found, it could ask if they want to close it or switch to it.
When one is not found, it just starts it.

Otherwise it's a good program to keep track of KSP mods and add ons.
Regards Brad

**Comment by plague006** [comment]
In CKAN, go into the Settings menu and select KSP command-line. Add `-single-instance` as an argument.

#1255 should address the issue for new installs, and maybe down the road someone will write some code that actually has CKAN itself detect if KSP running (which in itself could be useful to stop people trying to delete mods as the game is using them).

**Comment by Dazpoet** [comment]
Issue has been resolved so I'm closing this.
