### ISSUE TITLE
A provided mod can't satisfy a suggestion

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1234]
Steps to reproduce:
1) Install ProceduralFairing. It suggest PFTextures.
2) "ProceduralFairings-ForEverything" should be suggested, but it isn't. It provides PFTextures.

Tested on ckan 1.10.0, ksp 1.0.4. Only tested the gui so far.

Reported by Felger on IRC

**Comment by plague006** [comment]
Same behaviour in Win7-64bit command-line.

**Comment by Postremus** [comment]
Further investigation showed, that the gui calls registry.LatestAvailable(..) instead of registry.LatestAvailableWithProvides(..)

**Comment by HebaruSan** [comment]
This is included in the text UI in #2177. Just need to catch ModuleNotFoundKraken here and call LatestAvailableWithProvides:

https://github.com/KSP-CKAN/CKAN/blob/6aac4882af4cfd089d03ef4f3eb4143d14036efa/GUI/MainInstall.cs#L183-L199

**Comment by politas** [comment]
I don't think that commit made it into #2177

**Comment by HebaruSan** [comment]
Sorry, what I meant was that ConsoleUI allows "provides" mods to satisfy suggestions. #2177 indeed did not modify GUI.

**Comment by politas** [comment]
I can't find that commit "Satisfy suggestions w/ provides as per #1234" in the master tree, and the code as it is doesn't include that change. I think you maybe added it to your branch after it was merged, or didn't push the commit through to GitHub in time?

**Comment by HebaruSan** [comment]
This is the code that does it. If `LatestAvailable` doesn't find anything, ConsoleUI falls back to `LatestAvailableWithProvides`.

https://github.com/KSP-CKAN/CKAN/blob/2692e033697aeca739117490b8e16219998399c8/ConsoleUI/DependencyScreen.cs#L156-L171

**Comment by politas** [comment]
Ah, now I understand! Thanks for persisting in clearing up my confusion.

**Comment by HebaruSan** [comment]
Heh, thanks for persisting in asking; I was just as confused until I remembered the story with that commit.
