### ISSUE TITLE
When upgrading mods, list the old version number as well as the new version number in the install tab.

### ISSUE THREAD

**Issue by jakkarth** [KSP-CKAN/CKAN#1239]
This would be a stopgap until such time as a full log of CKAN's activities is implemented. Use case happened to me this morning:

- See OPT Space Plane Parts has a new version available
- Check its box, apply changes
- Install tab says it's downloading and install V1.7, great!
- Start game, ship won't load due to missing parts
- I care more about my ship than having mod up to date (so I can recover kerbals on board), look at install tab to see what old version was
- It's not there??
- Track down by other means that last release was V1.6
- Use undocumented command line options to install V1.6 of the mod
- Start game, ship still won't load due to other missing parts

Now I have no idea what version of the mod I had before I upgraded. It could have been 2 or 3 versions old. Since CKAN doesn't log all of its activity I can't go check what I did a week ago. My options now are to guess at older versions until I find one that works.

Desired behavior:

- Check its box, apply changes
- Install tab lists it downloading, removing V1.5 (or whatever it was), installing V1.7.
- It doesn't work, I refer back to the install tab and see old version, use undocumented command line arguments to install V1.5.

This seems like a lighter weight request than adding full logging of every CKAN install/remove/upgrade option, though that would be the actual ideal solution. I thought I remembered full logging being an open issue but I can't find it now.

**Comment by plague006** [comment]
We do this now!
![Really, we do!](http://puu.sh/l0t4d/fdbf08490e.png)

**Comment by Postremus** [comment]
Woooooooohoooooo

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎28.‎10.‎2015 08:23
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] When upgrading mods, list the old version number as wellas the new version number in the install tab. (#1239)

Closed #1239.
