### ISSUE TITLE
Allow find directives to pick files

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN#1241]
Came up in KSP-CKAN/NetKAN#1821 and KSP-CKAN/NetKAN#1822. Any particular reason it only matches on directories?

**Comment by pjf** [comment]
"Historical reasons".

The `find` directive was essentially exposing the function that did the "default" install when no install stanza was specified. It always searched for a directory name, and hence the `find` directive did the same.

**Comment by dbent** [comment]
Cool, should be fairly straight forward to allow files as well.

**Comment by plague006** [comment]
As #1512 is merged I think this can safely be closed.
