### ISSUE TITLE
Unable to retrieve metadata repositories master list

### ISSUE THREAD

**Issue by glek** [KSP-CKAN/CKAN#1242]
All other functions are working normally including updating repositories, checking for updates, downloading updates, downloading mods, etc.

**Comment by plague006** [comment]
The server that hosts the metadata repositories master list is down. No ETA on it coming back up.

**Comment by pjf** [comment]
Oh! I always wondered where the list came from; I actually thought it was compiled in. In any case, we should either provide a default list with the client or otherwise restore functionality, and preferably something the user can change if they wish.

**Comment by glek** [comment]
Perhaps keep a local copy in the event that the master list can't be fetched from the server, similar to how repository information is stored locally with the option to refresh?

**Comment by hakan42** [comment]
We could add the file (I should have a copy somewhere ) to the CKAN-meta repo and fetch it  (in raw forkat) from there. Then, the chance of that file not being available is the same as the full metadata zip not being available. Which is near enough zero for my taste :)

**Comment by glek** [comment]
It also consolidates everything in the same place.

**Comment by bstpierr** [comment]
Does anyone happen to have the MechJeb2 repo URL information? That's all I'm trying to add, but it seems to be very difficult to find.

**Comment by hakan42** [comment]
I have added my old copy of the repositories.json to the CKAN-meta repo. The URL to the raw file is https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/repositories.json , this URL should be put into the CKAN client. I might come up with a pull request to that effect later on.

@bstpierr , the URL to the MechJeb2 dev repo is in the repository file mentioned above, it would be https://github.com/KSP-CKAN/CKAN-meta-dev/archive/MechJeb2-ci.zip

**Comment by hakan42** [comment]
The PR for the CKAN client is at https://github.com/KSP-CKAN/CKAN/pull/1264

**Comment by plague006** [comment]
PR was merged and is part of the current release.
