### ISSUE TITLE
@pjf is out of action for a few days

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1250]
Hey lovely people,

Some personal life circumstances have knocked me out of action for the last few days. You might occasionally see me on IRC or github, but you shouldn't consider my presence to be reliable for the time being.

I'm hoping to squeeze out a sprint before my flights to the USA in a week, and I anticipate doing my second sprint while in Portland, Oregon, later this month.

Thank you all so much for your understanding,

~ Paul

**Comment by techman83** [comment]
@pjf *waves*

**Comment by pjf** [comment]
Just a quick status update on this:

* I'm catching an international flight in a few hours, and will be off the net during that time.
* My next sprint is scheduled for Wednesday, Pacific time.

**Comment by pjf** [comment]
I'm back. :)
