### ISSUE TITLE
kwrocketry + dmagic orbital science either not there or not able to install

### ISSUE THREAD

**Issue by trifox** [KSP-CKAN/CKAN#1253]
kwrocketry does not appear in the list of installable mods, for ksp1.0.4 although compatible ....

installing dmagic v1.0.6 createtes a 404 error, on kerbalstuff it has version 1.0.7 and v1.0.6 is plain not existant

**Comment by plague006** [comment]
It seems dmagic had 1.0.5 and 1.0.6 available long enough for the bot to index them, but the bot hasn't grabbed 1.0.7 yet.

**Comment by plague006** [comment]
As to KW.. I looked at the thread and this was the most recent post:

>Installed the latest KW release due to the claims that it will work with 1.0.4. First ship I made and took to orbit exploded due to the KW decouplers. So I'd advise people to be cautious with KW rocketry and 1.0.4

**Comment by trifox** [comment]
thank you for checking, i see, i dont use the decouplers and had kwrocketry manually installed, but i remember an issue with the decoupler as well ...

**Comment by trifox** [comment]
arrgh, cant send mails here, installing using ckan installs many mods, since 64 bit version has been declined, i end up with 3,3 gigs used by mods, so the game crashes instantly due to no memory :/ is there a way to figure out how much a mod consumes, or display the size of a mod in the ckan list !?

**Comment by plague006** [comment]
The install size/size on disk of a mod isn't the same as the ram they take when the game starts. When I added "-force-d3d11" to my steam launch options I saw a night-and-day difference in ram usage. (Some people prefer -force-opengl)

**Comment by trifox** [comment]
yea, i forgot that the old module manager had an option to run in opengl mode, whereas ckan does run in default dxmode, will use my starter shortcut to run the game instead of the ckan build in one ;)

**Comment by Postremus** [comment]
You can change the commandline options CKAN passes to KSP by klicking in the gui on "Settings", then on "KSP Commandd-Line".

**Comment by trifox** [comment]
thx

**Comment by trifox** [comment]
awesome, thx for quick support people, using ckan makes installing the mods more robust and stable, somehow i was always wondering why ksp was even starting due to soo many errors that occured using the old package manager, using the opengl switch i come down with a comfortable 2.1 gigs used, even with EVE and outerplanets active :D
