### ISSUE TITLE
Metapackage tries to install updated version of a mod

### ISSUE THREAD

**Issue by Toskin** [KSP-CKAN/CKAN#1256]
I tried to distribute .ckan file as a way to provide modpack. Trying to reload from file went good at first, but after reloading repositories, which found about 4 updates, CKAN was unable to load settings from .ckan file, writing report about new version of mods. Further meddling caused unhandled exceptions.

**Comment by Postremus** [comment]
Mind sharing your .ckan, so we can test this?

**Comment by Toskin** [comment]
Gimme mail, I'll send it to you. If it helps, I tried to duplicate Quill18 pack for his newest youtube series, for other players. About 2-3 mods had to be added manually. Here is list.
![redirect](https://cloud.githubusercontent.com/assets/8083413/8532700/61eb9ae6-2430-11e5-9ec4-0e20b17b625d.jpg)

**Comment by Postremus** [comment]
Please upload the .ckan somehwere, and post the link here. :)

**Comment by Toskin** [comment]
Here is link for ZIP file with .ckan file and readme, which I posted yesterday on youtube.
https://www.dropbox.com/s/goz8180ecmzp7lo/RemotePack.zip?dl=0

**Comment by Postremus** [comment]
What ckan and what ksp version do you use?

**Comment by plague006** [comment]
@Toskin I had a look at your readme:

Distant objects enhancement isn't abandoned, and it *is* in the CKAN repo. There are versions for 1.0.0 and 1.0.4 but none for 1.0.2. http://forum.kerbalspaceprogram.com/threads/98943

Thanks for the info about RemoteTech not being updated in CKAN, we'll have to look into it.

Not addressing your primary issue because you're in @Postremus's very capable (yet surprisingly soft) hands.

**Comment by squarism** [comment]
I gisted it here, for some useless future reason.  :telescope:

https://gist.github.com/squarism/c8d66ac5b762728ec532

**Comment by Toskin** [comment]
CKAN Version is 1.10.0.0-gb447380, KSP was 1.0.2 (I am forgetting to update, now I have 1.0.4)

**Comment by Toskin** [comment]
Ok. Got another part of error, while trying to install into clear KSP 1.0.4.
![ckan error](https://cloud.githubusercontent.com/assets/8083413/8538712/00fe764a-2471-11e5-90d7-22ebf6432798.png)
This doesn't make sense to me, because I am not using Astronomer pack nor RSS.
(And yes, sorry, I have Czech localization of Windows.)

**Comment by Postremus** [comment]
Your last problem seems to be something like #1097.

**Comment by HebaruSan** [comment]
The test case can no longer be run because it depends on KerbalStuff.

```
$ ckan.exe install -c toskin_pack.ckan 
installed-default 2015.07.05.09.19.28 requires ContractsWindowPlus 5.1 but it is not listed in the index, or not available for your version of KSP.
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
Or `ckan install --allow-incompatible` to ignore module compatibility.
```

![image](https://user-images.githubusercontent.com/1559108/82129832-6f31bb80-978b-11ea-869d-582dd8429e5f.png)
