### ISSUE TITLE
[GUI] Refresh button can cause issues with the registry if another process installs a mod

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1259]
It's possible to have CKAN install a module and have it become "orphaned" if an unrelated GUI was launched before the installation and the refresh button is pressed.

2 repro methods:

Have a GUI instance open, install a mod via CLI, refresh GUI. The entries in the registry created by CLI will be lost and the installed mod(s) will be "orphaned".

Have 2 GUI instances open: `A` and `B`. Install a mod in instance `A`, once install is complete refresh instance `B`. The entries in the registry created by `A` will be lost and the installed mod(s) will be "orphaned".

**Comment by Postremus** [comment]
#706

**Comment by plague006** [comment]
Closing this due to / in favour of the referred PR/issue/commit.
