### ISSUE TITLE
CKAN home page is displaying internal server error 500

### ISSUE THREAD

**Issue by rintomathew** [KSP-CKAN/CKAN#1263]
My linux box is rhel 6.5. i have installed ckan 2.3 and solr 1.4 on the same machine. i have followed the ducumentation.
http://docs.ckan.org/en/ckan-1.8.1/installing.html
I am getting error in my ckan home page "Internal Error" 500
so i have followed steps 
9,10,11,12 
in the document 
https://github.com/ckan/ckan/wiki/How-to-install-CKAN-2.0-on-CentOS-6.3-%28new%29
as a work around . but couldnt see any differences. 
Could anybody help me.

**Comment by techman83** [comment]
@rintomathew are you trying to use the 'Comprehensive Knowledge Archive Network' or the Kerbal Space Program mod manager 'Comprehensive Kerbal Archive Network'.

If it's the former you're in the wrong place, if it's the latter -> https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Fedora might help.
