### ISSUE TITLE
Where to report outdated mods?

### ISSUE THREAD

**Issue by friederschueler** [KSP-CKAN/CKAN#1267]
I gues this issue tracker is only for direct CKAN problems, but where to report outdated mods?

The mod Modular Fuel Tanks is release with v5.6.0. (since more than 3 weeks) But CKAN says 5.5.2 is latest release. I ask the mod author about this and he said he can not do anything it is CKAN problem :)

I found this:
https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ModularFuelTankExpansion.netkan

But it seems to be an extension to MFT, not MFT itself, as it only depends on MM according to the author:

http://forum.kerbalspaceprogram.com/threads/64117-1-0-4-Modular-Fuel-Tanks-v5-6-0/page51

**Comment by Postremus** [comment]
https://github.com/KSP-CKAN/CKAN-meta Should be the right place to report outdated mods.

**Comment by plague006** [comment]
Thanks for the heads up @friederschueler, MFT 5.6 will be available soon.
