### ISSUE TITLE
Changeset page: Repurpose the  Description Column 

### ISSUE THREAD

**Issue by Murdabenne** [KSP-CKAN/CKAN#1268]
The changeset "Description" column is currently unused.

Propose the following

1) on adds, the mods the the mod-to-be-added depends on are listed (forward dependencies).  This accomplishes the task of informing the end use just which mod is causing the install of the additional mods listed.  Also, changeset line for added dependencies would list the reverse dependency as the reason why it was installed ex: "[modname] added because [mod you are adding] depends on it" (CKAN #589).  Per CKAN #978, also the things that were installed by user request  (not via dependency) get tagged as being independently installed, and flagged against optional removal.

2) on removes, the mods that depend on the mod-to-be-removed are listed (reverse dependencies).  This accomplishes the task of informing the user a list of the mods that this will cause to be removed with it.  Also automatically removed mods listed would have in their description "[modname being autoremoved] removed because it depends on [modname you are removing]". Also, per CKAN #978, the user should be offered an option to uninstall any mods that were installed a a dependency that have no other mods depending on them - but not ones that are flagged as being deliberately installed by the user (those would have to be deliberately removed by the usual way of the user unchecking the box on the main screen).

In the case of something with >5 mods depending on it (modulemanager, firespitter, FAR, etc), the "these mods depend on this" would be too much data to put on a single line of text, so instead the text would say "removing this mod will cause XX other mods to be removed". 

Relationships: 

A depends on B.  This means A has a dependency (needs) on B, and B has a reverse dependency (is needed by) on A.

Examples to clarify (All these are on the changeset screen)
Mods A, B C, and X are as follows:
A depends on B and C
B is independent
C is independent
X depends on B

The user installs X, B is noted as dependency and installed along with it as well as being on the notification line 

The user then installs mod A, which causes mod C to be installed as a dependency, and mod B is updated to have mod A as a reverse dependency. 

Now the user removes mod A - which causes Mod C to be offered for uninstall since the only mod it has as a reverse dependency is Mod A.  B is not offered because removing the reverse for B to A still leaves reverse dependency of B to X

Next the user removes mod X, which causes Mod B to be offered for uninstall since the only remaining reverse dependency is mod X.

reset, have both X and A installed, meaning A B C X are all there.

First, remove X - nothing is offered since A and C are uninvolved, and B still has a reverse dependency B to A after eliminating B to X.

next remove A - both B and C are offered for removal since neither have any reverse dependencies other than the B to A and C to A that are being cut. 

There is the nasty case of A depends on B, B depends on C, and C depends on A, a cycle. 

Removing any of these should trigger automatic removal of the others.  By keeping a stack of removed mods, the potential cycle can be terminated like a tail recursion (yay lisp code a long time ago), and unwound in that manner.

Remove B. B is not on the remove list, add B (B).  B triggers reverse depends A, Remove A, (B) 
Remove A. A is not on the remove list, add A (B,A). A triggers reverse depends C. Remove C (B,A).
Remove C. C is not on the remove list, add C (B,A,C).  C triggers reverse depends B. Remove B (B,A,C). 
Remove B. B is on the list so pop. (and pop and pop finally yielding a list B A C to be removed)

There are other variations, but this may already exist in some for of registry checking in the current system. 

Original discussion in ckan irc http://pastebin.com/xqg8Z9Ks
Note this also includes parts of CKAN #978 
This may include CKAN #589 as well.

**Comment by Murdabenne** [comment]
This may include ckan #589 as well.

**Comment by Murdabenne** [comment]
Corrected type in title

**Comment by plague006** [comment]
Throwing this up as an example for this PR and #1311.
![Picture of a dog flying a train to Pluto](http://i.imgur.com/I8aWPJG.jpg)

**Comment by pjf** [comment]
Having just scanned over the description and looked at plague006's mock-up, I just came here to say hells yeah.

**Comment by HebaruSan** [comment]
I think this was done in #1412 and #2753; the changeset has no Description column, but instead Reason for action, and it explains why each entry is in the list, including mods that are no longer needed to satisfy dependencies:

![image](https://user-images.githubusercontent.com/1559108/185797382-ad015518-fd2a-492a-b420-fdd7eb4018ab.png)
