### ISSUE TITLE
On first load, refresh and prompt for autorefresh

### ISSUE THREAD

**Issue by abarbe-** [KSP-CKAN/CKAN#1275]
On first install, once the install directory / version is selected, automatically refresh the modlist/selection pane/repository.

Ideally, once the modlist is refreshed, spin up a dialog with:
Title: Auto-refresh
Body: Would you like CKAN to refresh the [modlist/repository] every time it is loaded?  (You can always manually refresh using the button up top.)
Buttons: Yes; No
... and set a setting accordingly that is checked on run.

(Ties into #1020. Suggested labels: enhancement, gui, install)

**Comment by FireFaced** [comment]
This is a VERY good idea. I hate when I open CKAN and expect to see a mod, but I haven't refreshed, so I can't find it

**Comment by plague006** [comment]
This feature is added with #1285 and you should expect it in the next CKAN release.
