### ISSUE TITLE
CKAN command line 'show' command not finding manually installed mods?

### ISSUE THREAD

**Issue by aallan** [KSP-CKAN/CKAN#1280]
When asked to 'show' information about a manually installed mod, CKAN can't find it...

    dastardly{aa}: mono ckan.exe list
    
    KSP found at /Applications/KSP_osx
    
    KSP Version: 1.0.4
    
    Installed Modules:
    
    - KSPSerialIO autodetected dll
    - Mono autodetected dll
    - PsimaxSerial autodetected dll
    - Servers autodetected dll
    - Telemachus autodetected dll
    
    Legend: -: Up to date. X: Incompatible. ^: Upgradable. ?: Unknown 
    dastardly{aa}: mono ckan.exe show KSPSerialIO
    KSPSerialIO not found or installed.
    Looking for close matches in available mods for KSP 1.0.4.
    No close matches found.
    dastardly{aa}:

**Comment by plague006** [comment]
Autodetection doesn't actually dtect mods themselves, it detects .dll files and assumes that they represent mods. That's why you have KSPSerialIO, Mono, and Servers. None of those are the names of mods as far as CKAN knows. If you want info about the mod that provides KSPSerialIO, then you want `mono ckan.exe show SerialIO`

**Comment by pjf** [comment]
Although our metadata for `SerialIO` has it marked as being for 1.0.2 only, because [that's what KerbalStuff says](https://kerbalstuff.com/mod/385/KSP%20Serial%20IO).

@aallan : I'm guessing it also works fine under 1.0.4? If so, we should probably put in a version override for it.

**Comment by aallan** [comment]
@pjf Yup, it works under 1.0.4. See https://twitter.com/aallan/status/619884669941751808

**Comment by pjf** [comment]
@aallan : Awesome, thank you! KSP-CKAN/NetKAN#1903 should let our indexer know that the mod is 1.0.4 compatible, so you should find it CKAN installable in a few hours (human review + bot indexing).

~ Paul (hopping on a plane in a couple of hours to Oregon)
