### ISSUE TITLE
Mac Mono difficulties

### ISSUE THREAD

**Issue by Quantum-Incident** [KSP-CKAN/CKAN#1281]
Have the most recent versions of Mono and Ckan (installed and on HDD respectively)  
However, when I try to run Ckan.exe it runs but is not responding and opens no windows (see picture) and is unslelectable (e.g cannot command tab to it)
![screen shot 2015-07-12 at 19 27 38](https://cloud.githubusercontent.com/assets/10763686/8639254/ce7234f0-28cb-11e5-831c-e06f0a2eba48.png)
EDIT: My apologies aallan, I am running in OXS 10.10.1 Yosemite

**Comment by aallan** [comment]
Which version of OSX is this running on?

**Comment by MidnightLightning** [comment]
Mine hung like that for a long time on OSX 10.6.8, but eventually bombed out with the error I reported in #1284 (and now it errors out with that exception immediately).

**Comment by alampros** [comment]
I've been seeing this also, however, I can't seem to replicate the problem. Sometimes it starts, sometimes it hangs on `mono-sgen`. After killing the process and trying again several times (from the mac CKAN.app executable), it seems to finally fire up.

**Comment by Quantum-Incident** [comment]
Many thanks alampros, Midnight-lightning and aallan It is now working!
(with the multiple Minute boot times associated with an ungodly amount of Mods (even with TM!))

**Comment by MidnightLightning** [comment]
So the solution to your problem was to just let it spin for several minutes and it eventually shows up?

**Comment by Quantum-Incident** [comment]
Pretty much yep
