### ISSUE TITLE
QUESTION: Converting AD install

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#1288]
Is there a way to convert a complete AD install to a CKAN controlled install?

**Comment by plague006** [comment]
No, not yet.See #949 for discussion and related issues. Closing this as it's a duplicate. (If you wish to share your view/insight, feel free to add it to #949)

**Comment by UndiFineD** [comment]
on linux with mono, i have AD modules, #949 has been closed, and still no solution for upgrading them ?

**Comment by dbent** [comment]
@UndiFineD #949 has not been closed.
