### ISSUE TITLE
CKAN doesnt install mods

### ISSUE THREAD

**Issue by steak1986** [KSP-CKAN/CKAN#1292]
I am using Ubuntu x64, i have gotten ckan and it opens no problem, its pointed to my game directory.  It sees mods i have installed manually.  When i select a mod and press Apply Changes, it goes to installation screen, but then just chugs away for hours.  I originally tried with a big mod, Astronomers visual pack, so i tried just with a simple small mod, collisionfx, and its still just spinning.  It does not start downloading the files, it does not install them.  Anyone had this issue?  I have deleted ckan and downloaded a new copy but same thing.  I dont want to rebuild this box, but i am close to trying that just to try and fix it.

**Comment by plague006** [comment]
Can you try using it via commandline just to see if that makes a difference?

**Comment by Postremus** [comment]
What CKAN version do you use? what mono version are you running on (mono --version)?

**Comment by steak1986** [comment]
I have tried the refresh button, nothing.  CKAN version v1.10.0-gb447380 (beta).  For mono 3.10.0.

**Comment by pjf** [comment]
Hmm. Try `mono ckan.exe install DogeCoinFlag --verbose`? That'll give us some idea where it's getting to (or `--debug` instead of `--verbose` if you want *oodles* of information). The `DogeCoinnFlag` mod is just a single flag file, so it's about the simplest thing we can get for debugging purposes.

**Comment by steak1986** [comment]
I will say i am no linux expert i ran the line, and here is what i got.  Dont know what to do next


$ mono ckan.exe install DogeCoinFlag --verbose
73 [1] INFO CKAN.CmdLine.MainClass (null) - Verbose logging enabled
92 [1] INFO CKAN.CmdLine.MainClass (null) - Using KSP install at /home/phillip/Desktop/SteamLibrary/steamapps/common/Kerbal Space Program
714 [1] INFO CKAN.Registry (null) - Registering ModuleManager from GameData/ModuleManager.2.6.6.dll
715 [1] INFO CKAN.Registry (null) - Registering FilterExtensions from GameData/000_FilterExtensions/FilterExtensions.dll
726 [1] INFO CKAN.Registry (null) - Registering Toolbar from GameData/000_Toolbar/Toolbar.dll
726 [1] INFO CKAN.Registry (null) - Registering AJE from GameData/AJE/Plugins/AJE.dll
727 [1] INFO CKAN.Registry (null) - Registering B9_Aerospace_WingStuff from GameData/B9_Aerospace/Plugins/B9_Aerospace_WingStuff.dll
727 [1] INFO CKAN.Registry (null) - Registering MiniAVC from GameData/B9_Aerospace/Plugins/MiniAVC.dll
727 [1] INFO CKAN.Registry (null) - Registering BetterBuoyancy from GameData/BetterBuoyancy/Plugins/BetterBuoyancy.dll
728 [1] INFO CKAN.Registry (null) - Registering CrossFeedEnabler from GameData/CrossFeedEnabler/Plugins/CrossFeedEnabler.dll
728 [1] INFO CKAN.Registry (null) - Registering CityLights from GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll
728 [1] INFO CKAN.Registry (null) - Registering Clouds from GameData/EnvironmentalVisualEnhancements/Plugins/Clouds.dll
728 [1] INFO CKAN.Registry (null) - Registering Geometry from GameData/EnvironmentalVisualEnhancements/Plugins/Geometry.dll
728 [1] INFO CKAN.Registry (null) - Registering OverlayMgr from GameData/EnvironmentalVisualEnhancements/Plugins/OverlayMgr.dll
728 [1] INFO CKAN.Registry (null) - Registering Terrain from GameData/EnvironmentalVisualEnhancements/Plugins/Terrain.dll
729 [1] INFO CKAN.Registry (null) - Registering FerramAerospaceResearch from GameData/FerramAerospaceResearch/Plugins/FerramAerospaceResearch.dll
729 [1] INFO CKAN.Registry (null) - Registering Scale_Redist from GameData/FerramAerospaceResearch/Plugins/Scale_Redist.dll
729 [1] INFO CKAN.Registry (null) - Registering ferramGraph from GameData/FerramAerospaceResearch/Plugins/ferramGraph.dll
729 [1] INFO CKAN.Registry (null) - Registering Firespitter from GameData/Firespitter/Plugins/Firespitter.dll
729 [1] INFO CKAN.Registry (null) - Registering KerbalJointReinforcement from GameData/KerbalJointReinforcement/Plugin/KerbalJointReinforcement.dll
730 [1] INFO CKAN.Registry (null) - Registering Kopernicus from GameData/Kopernicus/Plugins/Kopernicus.dll
730 [1] INFO CKAN.Registry (null) - Registering MechJeb2 from GameData/MechJeb2/Plugins/MechJeb2.dll
730 [1] INFO CKAN.Registry (null) - Registering ModularFlightIntegrator from GameData/ModularFlightIntegrator/ModularFlightIntegrator.dll
731 [1] INFO CKAN.Registry (null) - Registering ModuleRCSFX from GameData/ModuleRCSFX/Plugins/ModuleRCSFX.dll
731 [1] INFO CKAN.Registry (null) - Registering KSPAPIExtensions from GameData/ProceduralFairings/KSPAPIExtensions.dll
731 [1] INFO CKAN.Registry (null) - Registering ProceduralFairings from GameData/ProceduralFairings/ProceduralFairings.dll
732 [1] INFO CKAN.Registry (null) - Registering RCSBuildAid from GameData/RCSBuildAid/Plugins/RCSBuildAid.dll
732 [1] INFO CKAN.Registry (null) - Registering RCSBuildAidToolbar from GameData/RCSBuildAid/Plugins/RCSBuildAidToolbar.dll
733 [1] INFO CKAN.Registry (null) - Registering RealChute from GameData/RealChute/Plugins/RealChute.dll
734 [1] INFO CKAN.Registry (null) - Registering KSPAPIExtensions from GameData/RealFuels/Plugins/KSPAPIExtensions.dll
734 [1] INFO CKAN.Registry (null) - Registering RealFuels from GameData/RealFuels/Plugins/RealFuels.dll
734 [1] INFO CKAN.Registry (null) - Registering Scale_Redist from GameData/RealFuels/Plugins/Scale_Redist.dll
734 [1] INFO CKAN.Registry (null) - Registering TweakScale_RealFuels from GameData/RealFuels/Plugins/TweakScale_RealFuels.dll
736 [1] INFO CKAN.Registry (null) - Registering RealSolarSystem from GameData/RealSolarSystem/Plugins/RealSolarSystem.dll
737 [1] INFO CKAN.Registry (null) - Registering SmokeScreen from GameData/SmokeScreen/SmokeScreen.dll
737 [1] INFO CKAN.Registry (null) - Registering ModuleAnimateEmissive from GameData/SolverEngines/Plugins/ModuleAnimateEmissive.dll
737 [1] INFO CKAN.Registry (null) - Registering SolverEngines from GameData/SolverEngines/Plugins/SolverEngines.dll
894 [1] INFO CKAN.RelationshipResolver (null) - Resolving relationships for DogeCoinFlag
895 [1] INFO CKAN.RelationshipResolver (null) - Resolving relationships for DogeCoinFlag
About to install...

 * DogeCoinFlag v1.02

Continue? [Y/n] y


Unhandled Exception:
System.DllNotFoundException: libcurl
  at (wrapper managed-to-native) CurlSharp.NativeMethods:curl_global_init (int)
  at CurlSharp.Curl.GlobalInit (CurlInitFlag flags) [0x00000] in <filename unknown>:0 
  at CKAN.Curl.Init () [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.DownloadCurl () [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.Download (ICollection`1 urls) [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.DownloadModules (CKAN.NetFileCache cache, IEnumerable`1 modules) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (ICollection`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.DllNotFoundException: libcurl
  at (wrapper managed-to-native) CurlSharp.NativeMethods:curl_global_init (int)
  at CurlSharp.Curl.GlobalInit (CurlInitFlag flags) [0x00000] in <filename unknown>:0 
  at CKAN.Curl.Init () [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.DownloadCurl () [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.Download (ICollection`1 urls) [0x00000] in <filename unknown>:0 
  at CKAN.NetAsyncDownloader.DownloadModules (CKAN.NetFileCache cache, IEnumerable`1 modules) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (ICollection`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.ModuleInstaller.InstallList (System.Collections.Generic.List`1 modules, CKAN.RelationshipResolverOptions options, IDownloader downloader) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.Install.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0 
phillip@PMLINUX:~/Desktop$

**Comment by pjf** [comment]
Hooray! There's our problem `libcurl` is missing! Try `apt-get install libcurl4-openssl-dev` and try again. :)  (This is also mentioned at the bottom of [all the releases](https://github.com/KSP-CKAN/CKAN/releases).)

**Comment by steak1986** [comment]
haha, success.  Thanks so much for your help and quick responses

**Comment by pjf** [comment]
@steak1986 : I'm so glad!

I've also opened #1293 to see if we can get the client itself to detect when the library is missing and suggest an appropriate installation.

May you go to space today. :)

~ pjf

**Comment by steak1986** [comment]
Now that i got my linux system to work i can do it, WITHOUT SLOW DOWNS!
