### ISSUE TITLE
`Latest Version` column empty in 1.10.1

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1296]
Totally my fault. @pjf and I both had a look, but I had the final go-ahead and merged #1295 without adequately inspecting the GUI.

![Image of my shame](http://4.bp.blogspot.com/-PrTJBAcpZTE/UYQlOcatgwI/AAAAAAAACyc/5RHChd5T5LE/s1600/ConeofShame.gif)

**Comment by pjf** [comment]
Wait what?

**Comment by pjf** [comment]
You're right. :) Bisecting now to see if this is from my changes.

**Comment by pjf** [comment]
Sweet, totally my fault. c33fd784a7dbe78f7fd2dac3c7c36d31cec87be3 must be the culprit. :)

**Comment by plague006** [comment]
If you push out a hotfix: think Charon.

**Comment by pjf** [comment]
@plague006: That was my thoughts for the next larger release (especially if we can find an appropriate pic). :)
