### ISSUE TITLE
NetKAN + CKAN strip trailing space on folder names

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1300]
If you try out https://gist.github.com/plague006/8b8225d4e816756fef1b you expect it to take the folder "BetterIonEngine " and install it. Instead, netkan returns `No files to install`. The same is true if you use `find` instead of `find_regexp`. Somewhere along the line, the space is being stripped.

Related: KSP-CKAN/NetKAN#1907

**Comment by plague006** [comment]
Originally I thought this was a netkan-only issue but CKAN displays the same behaviour. 
With `"find": "ionEngineBetter"` CKAN returns:

`Installing mod "BetterIonDrives v0.1"Bad metadata detected for module BetterIonDrives v0.1
No files found in BetterIonEngine/ionEngineBetter to install!`

Trailing whitespaces suck.

**Comment by HebaruSan** [comment]
Looks like this got fixed at some point; the old metadata installs a folder with a trailing space:

```
$ ckan.exe install betteriondrives
About to install...

 * BetterIonDrives v0.1 (s3-us-west-2.amazonaws.com, 85.0 KiB)

Continue? [Y/n] 

Downloading "https://s3-us-west-2.amazonaws.com/ksp-ckan/D35E434D.zip"
0 B/sec - downloading - 0 B left - 100%               
Installing mod "BetterIonDrives v0.1"
Updating registry
Committing filesystem changes
Rescanning GameData
Done!

$ ls ~/.ksp/GameData/
 Astrogator          CustomAsteroids   Kopernicus                OPM     SquadExpansion
'BetterIonEngine '   KittopiaSpace     ModuleManager.4.1.3.dll   Squad   TextureReplacer
```
