### ISSUE TITLE
Mod shows up as autodetected dll, even when the mod has been manually deleted

### ISSUE THREAD

**Issue by nimobeeren** [KSP-CKAN/CKAN#1302]
When I manually install a mod by copying its folder to KSP's GameData folder, it shows up as autodetected dll (AD). After removing the all of the mod's files, it still shows up as AD, which prevents the user from checking the mod to install it through CKAN. Double-clicking it actually throws an exception, see my [other issue](https://github.com/KSP-CKAN/CKAN/issues/1301).
Restarting CKAN does not help.

I would like to see the autodetected status to be removed when the mod files are manually removed.

**Comment by nimobeeren** [comment]
Sorry, I'm an idiot. Refreshing the mod list does of course remove the autodetected status and allows for the mod to be installed through CKAN.

**Comment by plague006** [comment]
Glad it worked out =)
