### ISSUE TITLE
Strange behaviour from netkan.exe when given a .ckan file to process

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1307]
So I accidentally had a .ckan run through the most current netkan and netkan didn't reject it. It processed it, downloaded the file to cache* and spat out a perfectly viable .ckan of its own.

I expected it to throw up an error, but under the assumption it's intentional: the cache file it downloaded had an unexpected name `F68501B5-netkan-KerBalloons` (no extension).

.ckan used in test:
```
{
    "spec_version": 1,
    "identifier"  : "KerBalloons",
    "name"        : "KerBalloons",
    "abstract"    : "Adds balloons to KSP.",
    "author"      : "JoePatrick1",
    "version"     : "1.1",
    "ksp_version" : "1.0.2",
    "license"     : "restricted",
    "resources": {
        "homepage": "http://forum.kerbalspaceprogram.com/threads/119297"
    },
    "install": [
        {
            "file"       : "KerBalloons",
            "install_to" : "GameData"
        }
    ],
    "download": "http://addons-origin.cursecdn.com/files/2238/252/KerBalloons%20.zip"
}
```

NetKAN XML data from amazonaws (is it built after every commit to master? I have no idea):
```
<Contents><Key>netkan.exe</Key><LastModified>2015-07-16T21:43:18.000Z</LastModified><ETag>"31983db60b9946fe1a4efa11bc3034ca"</ETag><Size>1734144</Size><StorageClass>STANDARD</StorageClass></Contents>
```

Pinging @dbent since netkan is your baby, and I'm assuming no outstanding PRs cover this.

**Comment by dbent** [comment]
That's fine, `.netkan` files are a strict superset of `.ckan` files, i.e. all `.ckan` files are also valid `.netkan` files.

- Logging a warning when the input file does not end in `.netkan` is probably appropriate though.
- I'll fix the filename to include the `.zip` extension.

**Comment by plague006** [comment]
:+1:
Feel free to close this at your leisure.
