### ISSUE TITLE
I want to compile CKAN from the repo.

### ISSUE THREAD

**Issue by FireFaced** [KSP-CKAN/CKAN#1315]
So, I'm getting tired of waiting for releases, so I would like instructions to compile CKAN from the files that the repository provides.

**Comment by plague006** [comment]
We have a wiki page for that: https://github.com/KSP-CKAN/CKAN/wiki/Build-Environment

**Comment by FireFaced** [comment]
Oh

**Comment by pjf** [comment]
We also have a bot that builds the latest copy of what's on master and places it [here](https://ckan-travis.s3.amazonaws.com/ckan.exe). The git commit id is included in the version number that displays in the title bar (or in `ckan.exe version`). :)

**Comment by pjf** [comment]
There's also a guide specifically for Linux:

https://github.com/KSP-CKAN/CKAN/wiki/Building-CKAN-on-Linux

:)
