### ISSUE TITLE
KAS and KIS have released a new version for ksp 1.0.4

### ISSUE THREAD

**Issue by jrmysprks** [KSP-CKAN/CKAN#1316]
ckan installs KAS v0.5.2 (current version is 0.5.3) to ksp 1.0.4.
ckan installs KIS v1.1.5 (current version is 1.2.0) to ksp 1.0.4.

**Comment by plague006** [comment]
Have you hit refresh before installing? I've been unable to replicate this and checked the .version files for each to ensure we're installing the version we think we're installing.

**Comment by jrmysprks** [comment]
Thank you Plague006, ckan is working just fine and I did not realize I had to tell ckan to check for updates. My bad. I am new at using the program.
