### ISSUE TITLE
Error while updating repo / SSL-Cert?

### ISSUE THREAD

**Issue by SgtWolle** [KSP-CKAN/CKAN#1317]
Hi everybody!
I would like to use this really helpful tool, but I can't.

When I try to update the repository, I get this error message:
![error](https://cloud.githubusercontent.com/assets/13392297/8761213/6b8c7e40-2d44-11e5-9684-53188f4402df.jpg)

So I tried updating via cmd. Here is the error message I got: ckan.exe update
![error2](https://cloud.githubusercontent.com/assets/13392297/8761231/665039c0-2d45-11e5-8169-7c7683dd72ec.jpg)

CKAN-Version: v1.10.0-0-gb447380 (beta)
Windows 7 64bit
KSP 1.0.4

When you need any further information, plz ask.

Any help is very appreciated! Thank you guys!

**Comment by Postremus** [comment]
Can you reproduce the error using the latest release (1.10.3)?

**Comment by SgtWolle** [comment]
Yes, I can! (v1.10.3)

**Comment by Dazpoet** [comment]
If this was on linux/os x I'd ask for a mozroots to hopefully resolve it, what's the equivalent on windows though?

**Comment by SgtWolle** [comment]
I get the error while using Windows 7 64bit. Do you need any further information?

**Comment by Dazpoet** [comment]
Some googling didn't yield me much to be honest but looking at your error and applying my non-existant german skills I'd say you need to refresh your certifacts somehow. Are you running .NET 4.5?

**Comment by ayan4m1** [comment]
Hi, I'm trying to work on the backlog of issues in the CKAN project. Would you mind retesting your scenario - specifically, providing an English (or non-screenshot) version of the exception log would be useful.
