### ISSUE TITLE
Installing RealismOverhaul throws a exception

### ISSUE THREAD

**Issue by frustaci** [KSP-CKAN/CKAN#1319]
CKAN.ModuleNotFoundKraken: Cannot install AeroArrows, module not available
   em CKAN.CkanModule.FromIDandVersion(IRegistryQuerier registry, String mod, KSPVersion ksp_version)
   em CKAN.RelationshipResolver.<RelationshipResolver>c__AnonStorey0.<>m__0(String name)
   em System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   em System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   em System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   em CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KSPVersion kspversion)
   em CKAN.MainModList.ComputeConflictsFromModList(IRegistryQuerier registry, IEnumerable`1 change_set, KSPVersion ksp_version)
   em CKAN.Main.<UpdateChangeSetAndConflicts>c__async1.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em CKAN.Main.<ModList_CellValueChanged>c__async0.MoveNext()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.CompilerServices.AsyncMethodBuilderCore.<ThrowAsync>b__4(Object state)

**Comment by Postremus** [comment]
What CKAN version and what ksp version are you using?

2015-07-18 15:26 GMT+02:00 frustaci <notifications@github.com>:

**Comment by frustaci** [comment]
Latest. CKAN v1.10.3-0 / KSP 1.0.4

**Comment by frustaci** [comment]
Strange enough I do have aero arrows installed but it's market as incompatible.

**Comment by frustaci** [comment]
It seems this problem happens for every mod installed in a previous version and is currently marked as incompatible. For instance I removed AeroArrows manually from CKAN registry but now it gives the same error for VesselView which was also installed in a previous version and is now marked as incompatible.

**Comment by frustaci** [comment]
Also for some reason you cannot remove these conflicting mods using the CKAN UI.

**Comment by frustaci** [comment]
Actually it seems my CKAN registry was borked ever since the first error came up I cannot install or remove anything, the button "Go to changes" is always disabled, so im going to dump the whole thing and start fresh.

**Comment by Bendak** [comment]
Hi i just had a similar error with another mod.

Seems like you realism Overhaul will replace an existing mod Setting, and then it throws this error. Recomend chacking if any mod you have installed has a setting for realism overhaul. Remove the mod and reinstall after the Realism overhaul (if it dont install automatically as dependancy from Realism overhaul).

**Comment by frustaci** [comment]
That's indeed another problem. Conflicting mods also throw another call stack error. Like having HotRockets and trying to install RO because real plume conflicts with HotRockets.
So it seems the only possible solution is to uninstall all incompatible and conflicting mods before ticking RO.
Still would be nice to have these corner crash cases fixed, but thanks anyway, finally got it installed.
