### ISSUE TITLE
CKAN shouldn't replace symlink with directory

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1330]
I've not done any investigation as to why. But my poor internets are making testing challenging.

Before

```
leon@beast /tmp/NetKAN $ ls -lah dummy_ksp/CKAN/
total 4.7M
drwxr-xr-x 2 leon leon 4.0K Jul 21 21:26 .
drwxr-xr-x 5 leon leon 4.0K Jul 21 21:23 ..
lrwxrwxrwx 1 leon leon   22 Jul 21 21:26 downloads -> ../../downloads_cache/
-rw-r--r-- 1 leon leon  264 Jul 21 21:23 installed-default.ckan
-rw-r--r-- 1 leon leon 4.7M Jul 21 21:23 registry.json
```

After, it actually moves the symlink inside it O.o

```
leon@beast /tmp/NetKAN $ ls -lah dummy_ksp/CKAN/downloads
total 8.0K
drwxr-xr-x 2 leon leon 4.0K Jul 21 21:27 .
drwxr-xr-x 3 leon leon 4.0K Jul 21 21:27 ..
lrwxrwxrwx 1 leon leon   22 Jul 21 21:27 downloads_cache -> ../../downloads_cache/
```

Unsure if this affects Windows.

**Comment by mgsdk** [comment]
Are you using the new build script from https://github.com/KSP-CKAN/NetKAN/pull/1948 when you get this behavior? I think [L117](https://github.com/techman83/NetKAN/blob/build_script_mgsdk/build.sh#L117) forces it to create the synlink and folder.

**Comment by techman83** [comment]
Testing that script is actually how I noticed it. I was a little flummoxed as I was certain I had the downloads cached and wondered why they were downloading again (my internet isn't the greatest).

I actually need to pop a fix into my PR to make that symlink path relative.

**Comment by politas** [comment]
This has been fixed, hasn't it? It certainly never replaces my symlinked downloads directory under Ubuntu.

**Comment by HebaruSan** [comment]
Same here, all 13 of my instances have a sym link for the download folder, and it's still there despite a year of running various commands and tests, including with my own compiled binaries. I think this is fixed.

**Comment by techman83** [comment]
Depends, possibly an issue with relative links? I'd have to remember what I was doing to end up in that situation :stuck_out_tongue: 

It doesn't seem to have cropped up for anyone else, so worth closing out as stale.

**Comment by politas** [comment]
Ok, can be re-opened if it re-occurs, then.
