### ISSUE TITLE
vesselviewer mod

### ISSUE THREAD

**Issue by CommanderJohnKoenig** [KSP-CKAN/CKAN#1331]
I did a quick check of vesselviewer mod.  It's current release is for ksp version 1.0.2 but, I can confirm that it does function with version 1.0.4.  I have not tested every function but I can say that it works and you can control functions of your ships with the vesselviewer part selector functions. Again this was a quick check so I did not check every possible function and do not have screen shots for it.  A little more time will tell.  I will continue testing  and report back but, as for now know that it does work.

**Comment by plague006** [comment]
PR https://github.com/KSP-CKAN/NetKAN/pull/1973 is merged.

Thanks for letting us know about this.
