### ISSUE TITLE
Fork request for LPIP

### ISSUE THREAD

**Issue by Gustavo6046** [KSP-CKAN/CKAN#1335]
LPIP is done, and if you give permission, I will fork CKAN to put LPIP inside. Either way I will make a setup that installs LPIP given CKAN and KSP 1.0 is installed. And yes, I did indeed sat in KSP 1.0 since April because MechJeb is bugged in newer versions.

**Comment by Postremus** [comment]
You Can always fork ckan, 

----- Ursprüngliche Nachricht -----
Von: "Gustavo6046" <notifications@github.com>
Gesendet: ‎25.‎07.‎2015 23:23
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] Fork request for LPIP (#1335)

LPIP is done, and if you give permission, I will fork CKAN to put LPIP inside.

**Comment by pjf** [comment]
> You can always fork ckan, ans do a pull request. You dont need to ask for permissions for this.

+1 on this. With the code being MIT licensed, and the metadata CC-0, there shouldn't be anything stopping you from using and modifying the CKAN in any way.

Although I'd love to know more about LPIP, do you have a link? I've been at a conference the last week talking about machine ethics and KSP, and so I'm out of the loop a little as a result.

**Comment by plague006** [comment]
Shutting this down. See #1314 for more details why.

**Comment by pjf** [comment]
@plague006 : D'oh, I missed the discussions in #1314. Thank you so much!
