### ISSUE TITLE
CKAN Steals Window Focus

### ISSUE THREAD

**Issue by ghost** [KSP-CKAN/CKAN#1336]
Error messages as well as a successful installation of mods steals window focus, which is extremely annoying when I'm programming and then suddenly typing commands to CKAN because it has popped up in front of what I was working on. Please fix this if it's possible.

**Comment by pjf** [comment]
@Guard13007 : I don't suppose you can let us know your operating system and CKAN version? That would help us in being able to reproduce and fix this bug!

**Comment by Guard13007** [comment]
Sorry for the slow response.

Windows 7 and version 1.10.3-0-gafb8f0
