### ISSUE TITLE
NetKAN/CKAN-meta Build Scripts

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1339]
After spending a lot of time working on our current build scripts ( KSP-CKAN/NetKAN#1948 & KSP-CKAN/CKAN-meta#711 ), I've noted there is quite a lot of crossover between the two.

Essentially the big difference is that NetKAN inflates ckan files before testing them in the same manner that CKAN-meta does.

The biggest hassles I've had so far
- bash is pretty powerful, but when you start trying to get fancy it gets tricky fast
- the above trickyness makes it hard to maintain
- code duplication
- no easy test cases
- no tests
- many yaks

![ALL THE YAKS](http://i.imgur.com/t0XHtgJ.gif)

I've been otherwise occupied, but have been thinking about it and some of the work I've been doing over in KSP-CKAN/NetKAN-bot#19 could be quite easily extended into NetKAN + CKAN-meta. So rather than a complex bash script, a couple of well laid out prove scripts that leverage existing tested code to do the heavy lifting.

**Comment by HebaruSan** [comment]
Fixed in KSP-CKAN/xKAN-meta_testing#61; it's one big Python GitHub Action now.

**Comment by techman83** [comment]
This fills me with so much joy!!
