### ISSUE TITLE
Auto-update Install action should show progress of download

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1347]
When I get an auto-update notice on starting CKAN, I click "Install" and... nothing. No indication that it's downloading or that there may be a problem; the interface basically locks up. Has it crashed? is it working away in the background? I just have no clue, until eventually it finishes the download (when it's working). Please add a download progress dialog for the auto-update, or some indication that the mouse click has been accepted at least. In general, when a user clicks on an action, they should see some indication that the application has registered the click and is doing something.

**Comment by plague006** [comment]
:+1:

**Comment by politas** [comment]
Just clicked "install" for the 1.14.1 to 1.14.2 update, and I'm still not seeing any UI change to indicate that anything is happening until its finished. Not sure what was done, but the issue has not been adequately addressed yet.
