### ISSUE TITLE
GUI: Provides and hasupdate interact in a way that mods have a checkbox

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1348]
GUI: Provides and hasupdate interact in a way that mods have a checkbox to update but CKAN can't actually install anything.

Easy steps to duplicate: Add https://github.com/KSP-CKAN/CKAN-meta/archive/BDArmoryTest.zip as a repo and install `BahamutoD's Armory-DarkMultiPlayer addon`. `BahamutoD's Armory-common` `provides` `BahamutoD's Armory` but an update checkbox appears. http://imgur.com/CaYpQWP

![Image of a French man eating cheese](http://i.imgur.com/CaYpQWP.png)

**Comment by Postremus** [comment]
Should be #895.

**Comment by plague006** [comment]
Ah yeah, I thought we had an issue already but couldn't find it.
