### ISSUE TITLE
"Mark All Updated" is really bad wording.

### ISSUE THREAD

**Issue by WazWaz** [KSP-CKAN/CKAN#1349]
I only recently discovered that this button is actually "Mark All TO BE UPDATED". I assumed it was to forcefully ignore the files and mark them as being already updated outside CKAN (so I didn't dare touch it!); only when I hit it accidentally did I notice it just checked all the updatable mods - a great feature.

I suggest removing this button and just adding a checkbox in the "Update" menu title which has the same effect, and is familiar to people from other programs.

At the very least, just change it to "Update All" (the user will immediately discover this just checks the mods and they still need to "Go to Changes" (which really should be "Apply Changes" as that is the normal wording of such an operation).

**Comment by Postremus** [comment]
+1
I like the idea.

----- Ursprüngliche Nachricht -----
Von: "WazWaz" <notifications@github.com>
Gesendet: ‎05.‎08.‎2015 09:07
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] "Mark All Updated" is really bad wording. (#1349)

I only recently discovered that this button is actually "Mark All TO BE UPDATED". I assumed it was to forcefully ignore the files and mark them as being already updated outside CKAN (so I didn't dare touch it!); only when I hit it accidentally did I notice it just checked all the updatable mods - a great feature.
I suggest removing this button and just adding a checkbox in the "Update" menu title which has the same effect, and is familiar to people from other programs.
At the very least, just change it to "Update All" (the user will immediately discover this just checks the mods and they still need to "Go to Changes" (which really should be "Apply Changes" as that is the normal wording of such an operation).

**Comment by plague006** [comment]
How about "Select all updates" for the "Mark all updated" button? And "Apply changes" makes much more sense. "Go to changes" actually had me so confused when I started using CKAN that I had to read the instructions. I was completely stuck after ticking the mods I wanted to install.

**Comment by Wetmelon** [comment]
I also agree it's poorly worded.  "Update all available" or "Select all for update" or something similar would be much clearer.

**Comment by plague006** [comment]
So in #1352 I opted for "Add available updates" and "Apply changes". I also changed the color of the checkmark next to "Apply changes".
