### ISSUE TITLE
Cannot seem to download anything, stuck a updating or simply at 0 kbps

### ISSUE THREAD

**Issue by ElCthuluIncognito** [KSP-CKAN/CKAN#1351]
Anytime CKAN begins downloading it will usually stay at (Updating Selected Mods). Occasionally it'll 'begin download' but remain at 0 kbps. In both cases I eventually get an error. This happens even with just a single file. 

I have tried downloading RasterPropMonitor, KW Rocketry, and some others to no avail, and have noticed that its usually when downloading from kerbalstuff, however it fails with others too. 

I have successfully downloaded Astronomer's VP and ModuleManager, but this was before I began experiencing this issue. 

I have re-downloaded CKAN and even used the previous version and had the same results. 

Forgive me if its a lack of information on my end, any help is appreciated.

![ckan](https://cloud.githubusercontent.com/assets/13698844/9143790/080953aa-3d0e-11e5-80b3-8a0e7b5e661c.PNG)

**Comment by ElCthuluIncognito** [comment]
It began working now that I tried it a few hours later.

**Comment by Thesola10** [comment]
I am getting the same kind of problem on Linux (libcurl). Could you at least add an option that specifies which mod is currently being downloaded?

**Comment by politas** [comment]
The next release will do away with libcurl in favour of native C# file operations, which should make downloads more reliable. As for saying which file is being downloaded, no, I'm afraid we can't, because they are all downloaded simultaneously in separate threads. You can pre-download files on the contents tab, which can be very useful if you are installing multiple mods simultaneously, as for Realism Overhaul.

**Comment by Thesola10** [comment]
Then how does the command line version reliably show files download one by one?

**Comment by politas** [comment]
The CLI lists all the files being downloaded, then gives you a combined status for all active downloads, then lists each mod as it installs them, just like the GUI.  It's the same code generating the text for both interfaces.

**Comment by Thesola10** [comment]
Ok I noticed that soon after I sent my last message so okay

---- On ven., 26 mai 2017 00:46:35 +0200 notifications@github.com wrote ----

The CLI lists all the files being downloaded, then gives you a combined status for all active downloads, then lists each mod as it installs them, just like the GUI. It's the same code generating the text for both interfaces.
