### ISSUE TITLE
Releases should be signed

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1354]
Right now, releases aren't signed, and users get a "yo, this is a file you downloaded from the internet" message on Windows.

Mono comes with the `signcode` utility which can do this, and while we'll need to create (and possibly pay a CA to sign) a certificate, that shouldn't be insurmountable.

We'll still want travis to do the signing and release, but luckily we can encrypt things so that only travis can read them.

**Comment by techman83** [comment]
StartSSL HowTo
https://forum.startcom.org/viewtopic.php?f=15&t=1654

**Comment by phmayo** [comment]
Piggybacking on this:

[SpaceDock/SpaceDock-Project#2](https://github.com/KSP-SpaceDock/SpaceDock-Project/issues/2) will require some sort of verification infrastructure (see [SpaceDock/SpaceDock-Project#22](https://github.com/KSP-SpaceDock/SpaceDock-Project/issues/22) for a discussion of implementation ideas), and we were hoping to jump on hte CKAN metadata train, but the spec has no provisions for a `"signed"` field (to reduce the chances of somebody tempering with packages), or at least a `"hash"` to provide download integrity verification.

**Comment by politas** [comment]
Ok, we can get a signed certificate from Certum for only €14.00, which I'm willing to pay for. I'm not sure if that's an annual fee or a once-off, but I'm ok with it either way. It looks to me like their [Open Source Code Signing](https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml) is what we would need to use.

@ayan4m1, do you have any relevant experience in this field?

**Comment by politas** [comment]
Bringing this issue back to life may be worthwhile. We should actually move to release signing, or close this issue.
@HebaruSan , you are quite certainly hte primary coder at this point. Can you make head or tails out of how to actually implement this?

**Comment by techman83** [comment]
And this long standing annoyance can be called done! Thanks for the suggestion @pjf !

![image-1](https://github.com/user-attachments/assets/43e7b293-741f-4788-866c-c38ee423d644)
