### ISSUE TITLE
Write -- verbose log into a file

### ISSUE THREAD

**Issue by BiZZKeryear** [KSP-CKAN/CKAN#1366]
Write ` -- verbose` log into a file so that you can use this switch while using the UI.

Mostly because I dunno how to use the command line effectively, though. 

Have some trouble I can only replicate while using the UI, but ` -- verbose` or  `-- debug` doesn't fire up the UI.

So, ... I either can collect information about the problem or have the problem

**Comment by mgsdk** [comment]
You can run the gui by specifying the `gui` switch on the commandline. For instance:
```
mono ckan.exe gui --debug
```

If you want to dump all the messages that gets written in the console to a text file instead, you can use `>`.
```
mono ckan.exe gui --debug > log.txt
```
