### ISSUE TITLE
CKAN marks all uninstalled mods as "New in repository" on auto refresh on startup

### ISSUE THREAD

**Issue by zanzammar** [KSP-CKAN/CKAN#1368]
This is new behaviour in 1.12.0.

Whenever I refresh my repositories to check for updates, if an update is found CKAN will then mark all uninstalled mods as being new in the repo.

Here is an image of the bug in action.
![ckanbug](https://cloud.githubusercontent.com/assets/13736516/9181625/f5f159c0-3f73-11e5-8b99-71a8381d292a.png)

If there is some extended debug info that would be useful, please specify what you need.  I can't seem to find a log file anywhere for CKAN.

**Comment by Postremus** [comment]
I'am currently unable to reproduce it.
When had you last refreshed before your last refresh?

**Comment by zanzammar** [comment]
I usually refresh once or twice a week.  This happens every time there is
an upgradable mod.  I've noticed it about half a dozen times now and it
definitely started with the last CKAN update.

On Mon, Aug 10, 2015 at 4:11 PM, Martin Panzer <notifications@github.com>
wrote:

> I'am currently unable to reproduce it.
> When had you last refreshed before your last refresh?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN/issues/1368#issuecomment-129591211>.
>



-- 
Douglas Smith

289-201-1284 : Main Phone
705-220-9836 : Mobile Phone

**Comment by zanzammar** [comment]
I have some more information.  I did a little checking and it seems it happens even if their is no upgradable mod.  I guess I was assuming since I usually have updates.

![ckanbug2](https://cloud.githubusercontent.com/assets/13736516/9188710/3e404496-3fad-11e5-8d0c-7769b11a9874.png)

I opened CKAN up, it updated the mod lists, and the bug appeared.  I closed and re-opened 3 times to confirm.  I then tried unchecking the "Refresh mod list on launch" setting, then closed and re-launched CKAN.  After updating the mods manually with the GUI button, the bug does not appear.

![ckanbug3](https://cloud.githubusercontent.com/assets/13736516/9188734/7c2f44b4-3fad-11e5-89ea-e523e7d70f96.png)

It seems to be linked to the auto refresh repository on launch setting.  If you can confirm, perhaps the issue title should be changed.

**Comment by Postremus** [comment]
Able to reproduce it now. The autorefressh is the cause as you said. Thank you.
