### ISSUE TITLE
Version reverts on mod download failure

### ISSUE THREAD

**Issue by TomatoCo** [KSP-CKAN/CKAN#1370]
I've had this happen on several mods, but I'm just going to give my steps to recreate for one of them.

First, I go for the Mk2 Expansion mod. This has a prerequisite of the KM_Gimbal mod. I already have that installed but it's not auto-detected.
![screenshot](http://i.imgur.com/0TJdaIi.png)

This attempt to install failed, as you'd expect it to. 
![screenshot](http://i.imgur.com/c8RrdRt.png)

However! Next time you try to install, the Mk2 Expansion mod has gone from version 1.5 to 1.4.6.
![screenshot](http://i.imgur.com/NUenEVr.png)

Even with the manually installed copy of KM_Gimbal removed, attempts to download the Mk2 mod now fail because it tries to download a version that does not exist. 
![screenshot](http://i.imgur.com/mWH8K1k.png)

A workaround is to hit refresh, which brings the version of Mk2 back to 1.5.

EDIT: I just noticed that the other Mk2 mod visible in that list, Mk2 cockpit expansion, also had its version reverted.

**Comment by Postremus** [comment]
Maybe the registry removes the MK2 version 1.5 after the failed Installation from the availablemodules. This is a bad thing!

**Comment by Postremus** [comment]
I was able to reproduce it this way:
1) click on refresh
2) Close ckan

**Comment by HebaruSan** [comment]
I've tested a lot of mod download failures recently as part of #3635, and I never saw this. Guessing it was fixed at some point.
