### ISSUE TITLE
Dragable Metadata

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/CKAN#1372]
I would like to suggest a drag bar in the metadata page for the description so you can expand it down and read all of it.  Pushing version and all that down lower so you can see more of the description part at once.
https://dl.dropbox.com/u/30270697/tempimages/ckan1.png

**Comment by Postremus** [comment]
+1

**Comment by FireFaced** [comment]
YES! This would be SO useful

**Comment by Postremus** [comment]
closed by #1378
