### ISSUE TITLE
Separate Page for mod management.

### ISSUE THREAD

**Issue by VasVadum** [KSP-CKAN/CKAN#1376]
A separate page for installed mods, easier to manage your installed list from there.  :P I know that you have a filter to see only installed however, it might be nice using that separate page to see all installed with being able to set the priority of how important that mod is in your pack and being able to toggle one temporarily off without removing it from the list so you can later toggle it back on.  Kinda like the favorite list.  As there is one mod in the list I only want if I am diagnosing something, and would like to toggle it on and off every so often.

**Comment by Postremus** [comment]
#1375 should be implemented first. It is a requirement for this.

**Comment by HebaruSan** [comment]
I think this was satisfied by #2971...

- "in your pack" indicates that this is about making modpacks
- "set the priority of how important that mod is" can be done by clicking the Depends, Recommends, and Suggests buttons while editing a modpack
- "toggle one temporarily off" can be done by clicking the Ignore button while editing a modpack.
