### ISSUE TITLE
Make the mod filter the gui is starting with configurable

### ISSUE THREAD

**Issue by Postremus** [KSP-CKAN/CKAN#1377]
From Tekener, on the ckan [Thread](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-12-0-30-Jul-2015?p=2131583&viewfull=1#post2131583)
"Is there a way to set the default filter on startup or maybe add a setting for this?
 CKAN is always starting with "Compatible" while I prefer to have "Installed" in order to see which of my used mods need an update."

And a part of another [post](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-12-0-30-Jul-2015?p=2132922&viewfull=1#post2132922) from him for clarification:
"[....]. If some of them are upgradeable I can see it easily as they all fit on one one page. That why I suggested to have the user decide which filter should be the default one after starting."

**Comment by plague006** [comment]
:+1: It would be nice to either set a default or have it remember the last filter applied.
