### ISSUE TITLE
Recommended mods not showing in Windows 10

### ISSUE THREAD

**Issue by martinnj** [KSP-CKAN/CKAN#1380]
I'm not sure if Windows 10 is even on the roadmap, but since history should be the record of everything, as it happened, here is an issue on it.

Steps to reproduce:
 - Open CKAN.
 - Select a mod the "recommendeds another mod".
 - Click "Go to changes"
 - Click "Apply"
 - The recommended mod list is empty, even though there should be at least one mod. [Example](https://db.tt/tOVvSaJv).

The suggested mods table works fine though.

**Comment by Postremus** [comment]
not a win 10 bug, I can confirm recommends work on it.
I guess it is "just" #1346.

**Comment by martinnj** [comment]
It is indeed. I just verified on my Linux machine, it worked last time I tried, so maybe I've been gone for too long.
