### ISSUE TITLE
CKAN crashes on refresh

### ISSUE THREAD

**Issue by Dargon606** [KSP-CKAN/CKAN#1381]
Ok so i havent played ksp or used CKAN in ages and now every time i start ckan it gives me an error and closes or gives me the option to continue. So i closed it and reinstalled CKAN to the new update (it didnt update for some reason) and tried to start it with the same result. This time i chose to continue and it opened CKAN but every time you click something in CKAN it comes up with the same error which if you click the details tab on it gives the informaton following this report.

My next step will to reinstall CKAN and KSP  and see if it gets fixed but honestly i have no idea.

EDIT: I forgot to mention it said error 401 on it and also i just uninstalled ksp reinstalled both that and CKAN and came up with the same error

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main.UpdateRepo()
   at System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   at System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   at System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ToolStrip.WndProc(Message& m)
   at System.Windows.Forms.MenuStrip.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by Postremus** [comment]
Hi,
sorry for the late rsponse.
What ckan version and what ksp version are you using?
Does this error occur when you click in the toolbar on "Refresh"? Does it occur when you update using the auto-refresh on Launch function?

Greetings
Postremuss

**Comment by Dargon606** [comment]
KSP is likely the latest version as steam chooses to update no matter what
i say but CKAN identified it as 1.0.4 i believe. As for CKAN i just
downloaded 1.12.0. Yes this error occurs when i click refresh as for the
last question i dont exactly know because it doesnt auto-refresh in fact
when CKAN opens there is NOTHING in the mods list and hitting refresh
brings up the error so i cant bring up the mods

**Comment by Postremus** [comment]
I was suddenly able to reproduce it.
I added a repository to ckan, deleted master, uninstalled some mods, then pressed refresh

**Comment by Postremus** [comment]
Most likely cause are empty .ckan files.
Got this stacktrace with my test repository, which inlcudes on empty ckan.

```
   bei CKAN.Repo.ProcessRegistryMetadataFromJSON(String metadata, Registry registry, String filename) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 69.
   bei CKAN.Repo.UpdateRegistryFromZip(String path, Registry registry) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 383.
   bei CKAN.Repo.UpdateRegistry(Uri repo, Registry registry, KSP ksp, IUser user, Boolean clear) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 161.
   bei CKAN.Repo.UpdateAllRepositories(RegistryManager registry_manager, KSP ksp, IUser user) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\Core\Net\Repo.cs:Zeile 89.
   bei CKAN.Main.UpdateRepo(Object sender, DoWorkEventArgs e) in C:\Users\Martin\Documents\Visual Studio 2015\Projects\CKAN\GUI\MainRepo.cs:Zeile 62.
```

**Comment by Dargon606** [comment]
sorry i couldnt respond for a while but if that is the cause then what
would be the solution (im no coder i understood little to none of that.)
