### ISSUE TITLE
Installing CKAN on Ubuntu 14.04

### ISSUE THREAD

**Issue by mtcairneyleeming** [KSP-CKAN/CKAN#1382]
When I installed CKAN following the wiki [tutorial](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu-14.04), mono was installed to ` /usr/bin/mono `, not ` /usr/local/bin/mono `  on Kubuntu 15.04.

**Comment by Postremus** [comment]
Can you actually start ckan using "mono ckan.exe" as command?

**Comment by mtcairneyleeming** [comment]
I wasn't aware I could do that, I have had issues with the Path variable before, and it often required me to add the program manually, but it does work that way, though I do get the ` Could not set X locale modifiers ` error.

**Comment by Dazpoet** [comment]
try running `mono LC_ALL=en_US.UTF-8 mono ckan.exe` and that warning should go away.
