### ISSUE TITLE
"Mark all updated" button is active even if there aren't any to update

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1387]
It used to be that when I did an update and there weren't any mods which needed updating, that this button would be disabled.

Now it is always enabled, even if there is nothing to update

**Comment by plague006** [comment]
I can't replicate this behaviour on the current release (1.12) nor the current dev version. I suspect one of the mods you have installed is tricking CKAN into thinking there's an update. Can you provide your `installed-default.ckan` please? (Located in the `CKAN` folder in your KSP install directory)

**Comment by linuxgurugamer** [comment]
Sure.

You can find it here:

https://drive.google.com/file/d/0Bzid7e3pW1k7dTE5NXNDNERBNmM/view?usp=sharing

There are two modules are are listed as AD, Module Manager and WernherChecker

**Comment by plague006** [comment]
The AD MM is the key here. The button seems to remain highlighted if there's an AD .dll that has a version number in its filename.

As a test I created a test file `HyperEdit.v7.1.4.dll` and placed it inside `GameData` and it triggers the same effect.

**Comment by Postremus** [comment]
I can reproduce it using plague006's.
