### ISSUE TITLE
ksp-ckan.org not available

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1388]
The Help->About brings up a small dialog.  On it there is a link to the homepage, but clicking on it goes to ksp-ckan.org, which doesn't seem to be around anymore.

All the other links in that dialog work

**Comment by techman83** [comment]
I'll take a look at setting up a redirect to the wiki.

**Comment by Dazpoet** [comment]
Seems to be working now after @techman83 worked some magic

**Comment by techman83** [comment]
w00t! Thanks @Dazpoet
