### ISSUE TITLE
Allow mods not installed by CKAN to be registered and managed.

### ISSUE THREAD

**Issue by Marsfan** [KSP-CKAN/CKAN#1411]
I would like it if CKAN could detect what mods I already have downloaded from online and automatically make them part of CKAN so it is easy to update them, this would make it much easier than having to manually uninstall and then install with CKAN.

**Comment by Olympic1** [comment]
CKAN does this already. If it detects a mod that is already in your `GameData` folder it marks the mod with `AD`.

**Comment by Marsfan** [comment]
Thanks for the fast reply, I understand this, but I cannot do anything besides view them. I would like to be able to use CKAN to update these mods, but I cannot.

**Comment by plague006** [comment]
On mobile so I can't search the issues list extensively. This is absolutely a duplicate. The easiest issue that addresses this is #949.

**Comment by pjf** [comment]
> Thanks for the fast reply, I understand this, but I cannot do anything besides view them. I would like to be able to use CKAN to update these mods, but I cannot.

Aye, #949 is the most relevant ticket here, and it's something we *very* much want as well. Most of [the file overwriting milestone](https://github.com/KSP-CKAN/CKAN/milestones/File%20Overwrites) is centred around this very issue.
