### ISSUE TITLE
In the recommended mods part of installation the (De)-select mods checkbox should default to checked

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1416]
It's awkward to have users click the button twice. I used it for the first time today and didn't realize I had to double click until the mod was installing.

**Comment by Postremus** [comment]
+1

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎24.‎08.‎2015 14:03
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] In the recommended mods part of installation the (De)-selectmods checkbox should default to checked (#1416)

It's awkward to have users click the button twice. I used it for the first time today and didn't realize I had to double click until the mod was installing.
