### ISSUE TITLE
GUI: Download sizes should be sorted as numbers, not strings.

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1419]
Steps to reproduce:

1. Open the GUI
1. Sort by download size.

**Comment by Postremus** [comment]
That is The default sorting, done in mainmodlist.cs

----- Ursprüngliche Nachricht -----
Von: "Paul Fenwick" <notifications@github.com>
Gesendet: ‎25.‎08.‎2015 08:36
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] GUI: Download sizes should be sorted as numbers, not strings.(#1419)

Steps to reproduce:
Open the GUI 
Sort by download size.

**Comment by jenyaza01** [comment]
Thaks.
And what about completely disable sorting by Installed version and Latest version - it makes no sense?

**Comment by Postremus** [comment]
What exactly do you mean?

**Comment by jenyaza01** [comment]
Disable sorting in these columns
![2](https://cloud.githubusercontent.com/assets/13692655/9563273/e73c0da4-4e86-11e5-9f8c-57b2581a2a8d.PNG)

**Comment by Postremus** [comment]
Please create a new issue for this. :)

**Comment by jenyaza01** [comment]
Really? Okay, that does not stop anyone.
And it is not enough for the whole issue, IMHO.

**Comment by Keith-UCT** [comment]
I recently noticed this same problem. When trying to sort by download size it, instead of sorting the number like 5, 12, 47, 104, 3004 and so on, it sorts them like 104, 12, 3004, 47, 5. not sure why but it sorts it as though it was alphabetically sorting words, not sorting numbers by value.
This was irritating for me because I wanted to see what mods were the largest and which were the smallest.

**Comment by Postremus** [comment]
@jenyaza01 yup, one issue for every request is normal.


----- Ursprüngliche Nachricht -----
Von: "jenyaza01" <notifications@github.com>
Gesendet: ‎29.‎08.‎2015 18:54
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [CKAN] GUI: Download sizes should be sorted as numbers, notstrings. (#1419)

Really? Okay, that does not stop anyone.
And it is not enough for the whole issue, IMHO.
