### ISSUE TITLE
Sort type missing? 

### ISSUE THREAD

**Issue by jenyaza01** [KSP-CKAN/CKAN#1428]
![1](https://cloud.githubusercontent.com/assets/13692655/9563046/9a101e38-4e83-11e5-8394-935832c81a99.PNG)
I decided to (completely random decision) sort modification by their size, but ran into a problem: the numbers are sorted in alphabetical (?) order.
Perhaps no one before me will notice ... but it would be better if you do the sorting algorithm by the value.

**Comment by Postremus** [comment]
Thanks for the report.
It was already noticed in #1419.
Closing this as duplicate.
