### ISSUE TITLE
"Install from .ckan" should prompt users to accept changes before it starts installing

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1435]
Currently when we "Install from .ckan" from the gui's file menu the install starts immediately and once complete returns to the modlist. Unless you've read the contents of the .ckan file it's very hard to tell what was installed.

This applied only to mods that don't have `recommends` or `suggests`. In the cases of mods that have those the process is paused while waiting for useer input, but there's still no way to see `depends` and no changelist before installing.

**Comment by Postremus** [comment]
Should really make it more clear for The user what's going on.
+1

----- Ursprüngliche Nachricht -----
Von: "Matthew" <notifications@github.com>
Gesendet: ‎31.‎08.‎2015 13:28
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: [CKAN] "Install from .ckan" should prompt users to accept changesbefore it starts installing (#1435)

Currently when we "Install from .ckan" from the gui's file menu the install starts immediately and once complete returns to the modlist. Unless you've read the contents of the .ckan file it's very hard to tell what was installed.
This applied only to mods that don't have recommends or suggests. In the cases of mods that have those the process is paused while waiting for useer input, but there's still no way to see depends and no changelist before installing.
