### ISSUE TITLE
Autodetected AdvancedJetEngine is marked as AJE by CKAN

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1439]
@blowfishpro pointed this out on irc and I can reproduce it on my end.

Reproduction steps:

1) grab a clean 1.0.4 install of KSP
2) download a version of AdvancedJetEngine and manuall install it to gamedata
3) in commandline do a `ckan scan(optional)` followed by a `ckan list`
4) note that AdvancedJetEngine is ADed as [AJE](https://github.com/KSP-CKAN/CKAN-meta/blob/master/AJE) rather than the much newer [AdvancedJetEngine](https://github.com/KSP-CKAN/CKAN-meta/tree/master/AdvancedJetEngine)

I propose that we simply rid ourselves of AJE from CKAN-meta. It's been very obviously deprecated for [months](https://github.com/KSP-CKAN/CKAN-meta/commit/32c0e7710b65c476fa9c72885b271e75ecb849d1) now and hopefully noone uses it. Iirc we now handle AD mods better even if they're not in the upstream? While we're deprecating things we might also handle the old headache of @hakan42 and remove https://github.com/KSP-CKAN/CKAN-meta/tree/master/ContractConfigurator-SCANsat

**Comment by plague006** [comment]
:+1

**Comment by Dazpoet** [comment]
At the inquiry of @Postremus I changed the AJE.dll filename to AdvancedJetEngine.dll and CKAN picked it up correctly after a scan/refresh. It would appear that simply removing AJE from CKAN-meta might not resolve the issue at hand (AJE.dll not being properly ADed as AdvancedJetEngine). Iirc our autodetection basically check .dll file names against identifiers?

I will assume that AJE.dll is named that way for a reason (whatever it might be) so it seems this might be unsolvable from our end since juggling around identifiers is a bad idea in the best of times and a horrible idea when it comes to anything that's connected to the RO suite with all its crosslinked dependencies.

However I still maintain that we should clear out the old deprecated AJE files for good measure :smiling_imp:

**Comment by Postremus** [comment]
```
Iirc our autodetection basically check .dll file names against identifiers?
```
correct
