### ISSUE TITLE
NetKAN generates Curl Warning

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1441]
I'm not sure when this started occurring, as I generated relevant errors for the error parsing and now they don't work!

```
791 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
```

**Comment by techman83** [comment]
Ok, so I did a bisect and found when it started happening -> f32919bfb85f75d73c38b03b945519141bdb595c

**Comment by HebaruSan** [comment]
Guess what still happens almost 5 years later.

![image](https://user-images.githubusercontent.com/1559108/87002947-512b7a80-c180-11ea-99c8-db65a98b5b90.png)

It's not clear why we need this. Did the user do something wrong? Is this action actually unsafe?

**Comment by techman83** [comment]
I think it's a relatively benign warning in so far as how we use it. It's probably how CurlSharp inits the underlying curl library, the [doco covers this a little](https://curl.haxx.se/libcurl/c/threadsafe.html#:~:text=libcurl%20is%20thread%20safe%20but,same%20handle%20in%20multiple%20threads.).
