### ISSUE TITLE
Error while updating a mod

### ISSUE THREAD

**Issue by mrmodji** [KSP-CKAN/CKAN#1450]
File           : GameData/REPOSoftTech/Agencies/Agents.cfg
Installing Mod : REPOSoftTech-Agencies V1.0.2.0
Owning Mod     : DeepFreeze
CKAN Version   : v1.14.1-0-g0b06492 (beta)

**Comment by Postremus** [comment]
What Version of DeepFreeze have you currently installed?

**Comment by plague006** [comment]
Uninstall then re-install deepfreeze, the issue will (should) go away.
