### ISSUE TITLE
Ferram Aerospace install is dabroken

### ISSUE THREAD

**Issue by Ricochetv1** [KSP-CKAN/CKAN#1455]
I was trying to install Rallism Overhaul and RP-0, and got this with Ferram. I busted the installation down to original state, even doing the Steam file integrity check to put EVERYTHING back to stock, and tried to install Ferram by itself, and get the following:

About to install...

 * Ferram Aerospace Research 3:0.15.5.1
 * Module Manager 2.6.8
 * ModularFlightIntegrator 1.1.1

Downloading "https://kerbalstuff.com/mod/52/Ferram Aerospace Research/download/v0.15.5.1_Hayes"
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/95/artifact/ModuleManager-2.6.8.zip"
Downloading "https://ksp.sarbian.com/jenkins/job/ModularFlightIntegrator/9/artifact/ModularFlightIntegrator-1.1.1.0.zip"

Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearch 3:0.15.5.1 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/FAR Blitzableiter.png

and try again.

Your GameData has been returned to its original state.

-----------------
My theory is that Ferram has an older version of module manager packaged with it, and ckan is freaking out about the difference in versions.

**Comment by plague006** [comment]
For some reason present in your `Ships/@thumbs` directory. Delete the `Ships/@thumbs` directory and that should clear the issue.
