### ISSUE TITLE
CKAN v1.14.1 unable to install any mods on Ubuntu

### ISSUE THREAD

**Issue by cdavidson0522** [KSP-CKAN/CKAN#1457]
When I select a mod from the list and click the Contents -> Download button it brings me to the "Updating repositories" tab and the progress bar spins forever. It never actually does anything. I've let it go several hours. No errors are displayed or output to the command line.

When I select a mod from the list and click Changeset tab -> Apply it brings me to the "Installing mods" tab and the progress bar spins forever. It never actually does anything. No errors are displayed or output to the command line.

I've updated Mono to the latest version. I've updated CKAN to the latest version. I've tried running as sudo. Nothing works.

I'm running Ubuntu 14.04 LTS.

```
/usr/bin/mono -V
Mono JIT compiler version 3.2.8 (Debian 3.2.8+dfsg-4ubuntu1.1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen
```

CKAN v1.14.1-0-g0b06492 (beta).

KSP 1.0.4.

<script>
#!/bin/bash
sudo /usr/bin/mono ckan.exe
</script>

**Comment by birdspider** [comment]
`I've tried running as sudo` you should never do that, unless you know what you are doing or the app in question explicitly needs elevated rights.

have you tried `mozroots --import --ask-remove` (non-root) prior to launching ckan ?

**Comment by cdavidson0522** [comment]
Yes, I've tried that command several times. It doesn't have any effect on this issue.

mozroots --import --ask-remove
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Importing certificates into user store...
Import process completed.

**Comment by pjf** [comment]
@cdavidson0522 : If you can check two things for me:

- `sudo apt-get install libcurl4-openssl-dev` to make sure you've got the SSL libraries we need under linux.
- Try `mono ckan.exe update` and `mono ckan.exe install DogeCoinFlag` on the command-line. Those will try fetching a known good (and very small) mod, without starting the GUI (which means we can check to see if it's a problem in our network layer or not).

**Comment by cdavidson0522** [comment]
Hello. That worked successfully. The GUI now appears to be working as well; I was able to install Kerbal Attachment System and Kerbal Inventory System. Thank you your help and for creating this great tool.

/usr/bin/mono ckan.exe install DogeCoinFlag
About to install...

 * Dogecoin Flag v1.02

Continue? [Y/n] Y

Downloading "https://github.com/pjf/DogeCoinFlag/releases/download/v1.02/DogeCoinFlag-1.02.zip" (libcurl)
0 kbps - downloading - 0 MiB left - 100%           
Installing mod "DogeCoinFlag v1.02"
Updating registry
Commiting filesystem changes
Rescanning GameData
Done!

**Comment by plague006** [comment]
Closing this as the solution is already in the wiki.
