### ISSUE TITLE
AVG flags CKAN for a virus

### ISSUE THREAD

**Issue by daspuh** [KSP-CKAN/CKAN#1461]
I opened my CKAN at about 12:30 pm PST 9/16/2015.  I was prompted that there was an update so I accepted it.  As the update began AVG immediately stopped the process due to virus definition.

idp.ares.generic was found in CKAN
Trojan
Medium Threat.

To remove the threat AVG removed CKAN.

This idp.ares.generic seems to be affecting multiple game installers not just CKAN.  Help would be greatly appreciated, I love my CKAN!

**Comment by plague006** [comment]
I was curious what other AVs might detect CKAN as a false positive. Apparently an AV called "Rising" doesn't like it. (https://www.virustotal.com/en/file/8a9ff893be074ec1c574072701a19fef3dadf9104888666bcdf2b71723e9c199/analysis/1442444074/)

At any rate, I think [this link](https://support.avg.com/SupportArticleView?l=en_US&urlname=How-to-exclude-file-folder-or-website-from-AVG-scanning) will give you the info you need. I don't use AVG so I can't be sure.

**Comment by daspuh** [comment]
I was able to install CKAN without it setting off AVG.  Thanks for the response.
