### ISSUE TITLE
invalid url for mod

### ISSUE THREAD

**Issue by Pesoen** [KSP-CKAN/CKAN#1463]
so far i have only found the one, but its a mod i would like to have, so reporting it here.

CKan version 1.14.2-0-g7c34a8a (beta)

the mod is Mk2 Stock-a-like Expansion

error is Failed to download "https://kerbalstuff.com/mod/790/Mk2 Stock-a-like Expansion/download/1.4.6" - error: The remote server returned an error: (404) Not Found.

the space after Mk2 and before Stock is the problem.

**Comment by Pesoen** [comment]
also a newer version is available, not sure how your database works, but i'm guessing it fetches the mod list from online somewhere.(what i might have done) so updating this should be relatively easy.

**Comment by techman83** [comment]
You can check the indexing status here -> http://status.ksp-ckan.org/

Do you have the exact identifier for the mod?

**Comment by Pesoen** [comment]
i have no clue what the identifier is, but if its the name, its written on the third line of my report.

also, it has been fixed now, i can now download it.

**Comment by techman83** [comment]
Ok it was 'Mk2Expansion' we have an Issue + PR for adding Identifier information to the GUI. Looks like the issue may have been transient and now resolved. Feel free to re-open if it continues to be an issue.

**Comment by baldamundo** [comment]
I'm getting the same error on the same file. If I manually download it from the same link via Firefox it works fine.
