### ISSUE TITLE
Exceptions when importing a .CKAN file

### ISSUE THREAD

**Issue by OzoneGrif** [KSP-CKAN/CKAN#1465]
Consultez la fin de ce message pour plus de détails sur l'appel du débogage
juste-à-temps (JIT) à la place de cette boîte de dialogue.

************** Texte de l'exception **************
System.NullReferenceException: La référence d'objet n'est pas définie à une instance d'un objet.
   à CKAN.NetFileCache.CreateURLHash(Uri url)
   à CKAN.NetFileCache.GetCachedFilename(Uri url)
   à CKAN.NetFileCache.IsMaybeCachedZip(Uri url)
   à CKAN.GUIMod..ctor(Module mod, IRegistryQuerier registry, KSPVersion current_ksp_version)
   à CKAN.Main.installFromckanToolStripMenuItem_Click(Object sender, EventArgs e)
   à System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   à System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   à System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   à System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   à System.Windows.Forms.Control.WndProc(Message& m)
   à System.Windows.Forms.ToolStrip.WndProc(Message& m)
   à System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   à System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Assemblys chargés **************
mscorlib
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Version de l'assembly : 0.0.0.0
    Version Win32 : 0.0.0.0
    CodeBase : file:///G:/_GAMES/Steam/steamapps/common/Kerbal%20Space%20Program/ckan.exe
----------------------------------------
System.Core
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34238 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Windows.Forms
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34251 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    Version de l'assembly : 1.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Version de l'assembly : 0.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_fr_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
System.Transactions
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Runtime.Serialization
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34234 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.EnterpriseServices
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.resources
    Version de l'assembly : 4.0.0.0
    Version Win32 : 4.0.30319.34209 built by: FX452RTMGDR
    CodeBase : file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_fr_b77a5c561934e089/System.resources.dll
----------------------------------------

************** Débogage JIT **************
Pour activer le débogage juste-à-temps (JIT), le fichier de configuration pour cette
application ou cet ordinateur (machine.config) doit avoir la valeur
jitDebugging définie dans la section system.windows.forms.
L'application doit également être compilée avec le débogage
activé.

Par exemple :

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Lorsque le débogage juste-à-temps est activé, les exceptions non gérées
seront envoyées au débogueur JIT inscrit sur l'ordinateur
plutôt que d'être gérées par cette boîte de dialogue.

----------------

{
	"kind": "metapackage",
	"abstract": "A list of modules installed on the default KSP instance",
	"name": "installed-default",
	"license": "unknown",
	"version": "2015.09.19.06.21.35",
	"identifier": "installed-default",
	"spec_version": "v1.6",
	"depends": [
		{
			"name": "ContractConfigurator-AnomalySurveyor",
			"version": "1.4.2"
		},
		{
			"name": "MechJeb2",
			"version": "2.5.3"
		},
		{
			"name": "surfacelights",
			"version": "1.0"
		},
		{
			"name": "Toolbar",
			"version": "1.7.9"
		},
		{
			"name": "CollisionFX",
			"version": "3.2"
		},
		{
			"name": "ModularFlightIntegrator",
			"version": "1.1.1"
		},
		{
			"name": "ActsEW",
			"version": "1.5"
		},
		{
			"name": "ContractConfigurator-InitialContracts",
			"version": "1.0.4"
		},
		{
			"name": "FingerboxesCore",
			"version": "2:1.0.4_r1"
		},
		{
			"name": "WaypointManager",
			"version": "2.4.2"
		},
		{
			"name": "AlternateResourcePanel",
			"version": "2.7.3.0"
		},
		{
			"name": "KWRocketry",
			"version": "2.7.0-community"
		},
		{
			"name": "KerboKatzSmallUtilities-AutoBalancingLandingLeg",
			"version": "1.1.1"
		},
		{
			"name": "KerbalEngineerRedux",
			"version": "1.0.18.0"
		},
		{
			"name": "ToadicusTools",
			"version": "15"
		},
		{
			"name": "RCSBuildAid",
			"version": "0.7.2"
		},
		{
			"name": "ProceduralFairings",
			"version": "v3.15"
		},
		{
			"name": "TacFuelBalancer",
			"version": "v2.5.1"
		},
		{
			"name": "G-Effects",
			"version": "0.2.2"
		},
		{
			"name": "USI-LS",
			"version": "0.1.5"
		},
		{
			"name": "SmartStage",
			"version": "v2.7.0"
		},
		{
			"name": "RCSSounds",
			"version": "4.3a"
		},
		{
			"name": "KWRocketry-CommunityFixes",
			"version": "0.2.0"
		},
		{
			"name": "InfernalRobotics",
			"version": "v0.21.3"
		},
		{
			"name": "RoverWheelSounds",
			"version": "1.2"
		},
		{
			"name": "SAVE",
			"version": "1.0.1-672"
		},
		{
			"name": "PreciseNode",
			"version": "1.1.3"
		},
		{
			"name": "MenuStabilizer",
			"version": "1"
		},
		{
			"name": "SeriousKerbalBusiness",
			"version": "1.6"
		},
		{
			"name": "PersistentRotation",
			"version": "1.0.0"
		},
		{
			"name": "WiderContractsApp",
			"version": "1.2.0"
		},
		{
			"name": "KIS",
			"version": "1.2.2"
		},
		{
			"name": "KerboKatzSmallUtilities-DisableTempGagues",
			"version": "1.0.0"
		},
		{
			"name": "StockPlus",
			"version": "v1.0.4c.1"
		},
		{
			"name": "StockBugFixModules",
			"version": "v1.0.4c.2"
		},
		{
			"name": "QuickBrake",
			"version": "v1.01"
		},
		{
			"name": "kOS",
			"version": "0.17.3"
		},
		{
			"name": "ContractConfigurator",
			"version": "1.7.4"
		},
		{
			"name": "KAS",
			"version": "0.5.4"
		},
		{
			"name": "ImprovedChaseCamera",
			"version": "v1.5.1"
		},
		{
			"name": "ContractConfigurator-RemoteTech",
			"version": "2.0.0"
		},
		{
			"name": "ContractConfigurator-ScanSatLite",
			"version": "1.3"
		},
		{
			"name": "TransferWindowPlanner",
			"version": "v1.3.1.0"
		},
		{
			"name": "HyperEdit",
			"version": "1.4.1.0"
		},
		{
			"name": "SelectRoot",
			"version": "2015-05-17"
		},
		{
			"name": "StripSymmetry",
			"version": "v1.6"
		},
		{
			"name": "StageRecovery",
			"version": "1.5.7"
		},
		{
			"name": "ContractConfigurator-Tourism",
			"version": "1.2.0"
		},
		{
			"name": "EnvironmentalVisualEnhancements",
			"version": "7-4"
		},
		{
			"name": "AstronomersPack-Sandstorms",
			"version": "Interstellar.V2"
		},
		{
			"name": "AstronomersPack-Clouds-Medium",
			"version": "Interstellar.V2"
		},
		{
			"name": "SimpleOrbitCalculator",
			"version": "v1.4.0"
		},
		{
			"name": "RemoteTech",
			"version": "v1.6.8"
		},
		{
			"name": "Chatterer",
			"version": "0.9.6"
		},
		{
			"name": "WaterSounds",
			"version": "1.1"
		},
		{
			"name": "KerboKatzUtilities",
			"version": "1.2.11"
		},
		{
			"name": "NavballUpDefault",
			"version": "V0.1"
		},
		{
			"name": "KerbalAlarmClock",
			"version": "v3.4.0.0"
		},
		{
			"name": "ActiveTextureManagement-x86-Basic",
			"version": "5-0"
		},
		{
			"name": "AstronomersPack-AtmosphericScattering",
			"version": "Interstellar.V2"
		},
		{
			"name": "ElectricCost",
			"version": "1.0.1"
		},
		{
			"name": "AstronomersPack-Eve-Jool-Clouds-4K",
			"version": "Interstellar.V2"
		},
		{
			"name": "AstronomersPack-Snow",
			"version": "Interstellar.V2"
		},
		{
			"name": "ContractConfigurator-RemoteTechLite",
			"version": "1.1"
		},
		{
			"name": "ContractConfigurator-AdvancedProgression",
			"version": "4.5"
		},
		{
			"name": "CrewQueue",
			"version": "1:ksp1.0_r2"
		},
		{
			"name": "DockingSounds",
			"version": "1.2"
		},
		{
			"name": "TankLock",
			"version": "0.1"
		},
		{
			"name": "ScienceAlert",
			"version": "1.8.9"
		},
		{
			"name": "StockClamshellFairings",
			"version": "1.0"
		},
		{
			"name": "notes",
			"version": "0.11"
		},
		{
			"name": "SCANsat",
			"version": "v14.2"
		},
		{
			"name": "ModuleManager",
			"version": "2.6.8"
		},
		{
			"name": "SafeChute",
			"version": "v1.7.1"
		},
		{
			"name": "VOID",
			"version": "0.18.3a"
		},
		{
			"name": "DockingPortAlignmentIndicator",
			"version": "6.2.0"
		},
		{
			"name": "KWRocketry-CommunityFixes-interstage",
			"version": "0.2.0"
		},
		{
			"name": "EngineResponseTime",
			"version": "1.0.1"
		},
		{
			"name": "EVAEnhancements",
			"version": "1.0.0"
		},
		{
			"name": "EvaFuel",
			"version": "0.0.2"
		},
		{
			"name": "PlanetShine",
			"version": "0.2.3.1"
		},
		{
			"name": "ShipEffects",
			"version": "1.0.2"
		},
		{
			"name": "ModuleAnimateEmissive",
			"version": "v1.11"
		},
		{
			"name": "PlanetShine-Config-Default",
			"version": "0.2.3.1"
		},
		{
			"name": "Trajectories",
			"version": "v1.4.3"
		},
		{
			"name": "KerboKatzSmallUtilities-FPSViewer",
			"version": "1.0.4"
		},
		{
			"name": "SemiSaturatableRW",
			"version": "1.10.2"
		}
	]
}

**Comment by Tarenola** [comment]
Can confirm the error.

**Comment by zman97211** [comment]
I've authored a pull request that resolves (or at least works around) this issue.

**Comment by Solestis** [comment]
Is there a way to temporarily work around this? Like adding a dummy url to existing .ckan files? I tried but without enough knowledge of how this program expects the file I couldnt make it work.

**Comment by Postremus** [comment]
download_url should ne what you Need


----- Ursprüngliche Nachricht -----
Von: "Solestis" <notifications@github.com>
Gesendet: ‎25.‎09.‎2015 10:52
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Cc: "Martin Panzer" <postremus1996@googlemail.com>
Betreff: Re: [CKAN] Exceptions when importing a .CKAN file (#1465)

Is there a way to temporarily work around this? Like adding a dummy url to existing .ckan files? I tried but without enough knowledge of how this program expects the file I couldnt make it work.
