### ISSUE TITLE
could not establish trust relationship for the ssl/tls secure channel error

### ISSUE THREAD

**Issue by firerobe** [KSP-CKAN/CKAN#1466]
I'm probably doing something stupid but I get this error "Failed to download "https://kerbalstuff.com/mod/777/Firespitter - Plugin Only/download/7.1.4" - error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel." when trying to install several mods

**Comment by techman83** [comment]
@firerobe Can you provide what version of CKAN, along with what OS you are running?

**Comment by firerobe** [comment]
windows 7 64-bit operating system and I just downloaded CKAN a few days ago so I should have the most recent version

**Comment by techman83** [comment]
That's a little strange then, usually most SSL errors I've seen relate to the Mono certificate library on Linux. Have you got .NET 4.5 or greater installed?

**Comment by firerobe** [comment]
as far as I know I should but it is the only thing that I have not tried to re-download so I will try that now see if it works

**Comment by techman83** [comment]
Curious. Are you able to browse https://kerbalstuff.com/mod/777 in internet explorer (It uses the same certificate store as .NET from memory).

**Comment by firerobe** [comment]
yes

**Comment by techman83** [comment]
I don't have a windows machine near me to try it myself unfortunately. Are you able to duplicate the issue repeatedly?

**Comment by firerobe** [comment]
yes and it happens with more then just the firespitter mod it will work for a few mods then it wont for others
