### ISSUE TITLE
ModuleManager cannot be installed

### ISSUE THREAD

**Issue by Wizarth** [KSP-CKAN/CKAN#1467]
Trying to install Module Manager 2.6.8 , and getting:

Failed to download "https://ksp.sarbian.com/jenkins/job/ModuleManager/95/artifact/ModuleManager-2.6.8.zip" - error: The underlying connection was closed: An unexpected error occurred on a send.

it looks like ksp.sarbian.com (the domain the download hosted from) is timing out (tested using my web browser).

**Comment by plague006** [comment]
Not having that issue. Just an issue with his server I imagine?

**Comment by Wizarth** [comment]
I confirm, working now. Just wanted to report it in case it was more.

**Comment by pjf** [comment]
Huh. I've seen this as well, but suspect it's only temporary. (I was *very* worried fora moment it might not be)
