### ISSUE TITLE
GUI: Show mod identifiers in the metadata panel

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1468]
When viewing mods in the GUI, I can't find anywhere that we display the mod's identifier (as would be used in a `.ckan`/`.netkan` relationship field). It would be lovely if this was displayed in the side panel along with author, license, and everything else.

Hopefully a simple matter of code. :)

**Comment by techman83** [comment]
:+1: yes, I encountered this hurdle the other day and it looks like @Postremus is being awesome again :-)
