### ISSUE TITLE
Aiiiiee! pjf is at Burning Seed

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1483]
Hello lovely people! This is a short note to say that I'm at Burning Seed for the next week, and won't have internet access. I'll be back Wednesday-ish.

As always, continue to use your best judgement when doing things. If you're a collaborator, you have the ability to make releases (literally just make a release using the github web interface, and the bots do the rest... you do need to write the release notes, though), merge PRs, manipulate issues, and everything else. :)

Looking forward to seeing you all when I get back!

~ Paul

(This ticket will auto-close after 7 days of inactivity.)

**Comment by techman83** [comment]
:+1:
