### ISSUE TITLE
Apply changes not active if an update is available but not checked

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1485]
I was trying to remove some mods.  One of the mods had an available update.

I unchecked the mods I wanted to remove, the "Apply Changes" did not go active.

I had to select the available update in order for the button to become active

**Comment by Postremus** [comment]
Is this issue still present? On what mod happened it?

**Comment by linuxgurugamer** [comment]
I think it was resolved, but not sure.

I'll keep an eye out and let you know if it happens again.


LGG
