### ISSUE TITLE
Not sure if this is a support issue - how to test a generated ckan

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1486]
I was looking for a way to test a generated ckan (I ran the netkan.exe locally), but didn't see any obvious way to do so.

This one had both requires and excludes in it, and I wanted to be sure it was working properly.  Since I couldn't, I ended up having to update the netkan when I realized it wasn't correct.

If there is no way, then can you raise this as an issue?

**Comment by plague006** [comment]
To test a .ckan (on windows) use `ckan.exe install -c example.ckan`

**Comment by linuxgurugamer** [comment]
OH.

thank you

**Comment by linuxgurugamer** [comment]
Another question, I don't see this in the list of ckan.exe commands:

If I know the path to an install, and I have a new .ckan, is it 
possible, and if so what is the syntax to do the following:

    Test to see if any of the mods in the .ckan specified need to be 
installed.  I don't really need to get a list of what needs to be 
installed, I just need to know whether or not something does need to be 
installed.

also:

Is it correct that when I run the ckan.exe install command, that it will 
install to the current directory/install?

I think the syntax I need would be something like:

ckan.exe install  kspdir  <kspInstallDir>   -c  my.ckan


Thanks


JBB

**Comment by plague006** [comment]
I use `ckan ksp default <install_name> & ckan install -c example.ckan` to specify which installation I want to install to.

As for seeing which mods you're missing I think the GUI can show you that, but I'm not certain. If it doesn't hopefully someone else can answer that for you.

**Comment by linuxgurugamer** [comment]
I need to run this as a cmd line, I want to detect inside the game if 
the user needs to exit and install or not.

Thanks for the first part of the answer.

JBB
