### ISSUE TITLE
 ERROR CKAN.ErrorDialog (null) - Unhandled exception

### ISSUE THREAD

**Issue by Bendak** [KSP-CKAN/CKAN#1487]
```
190 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.UnauthorizedAccessException: O acesso à chave do Registro 'HKEY_CURRENT_USER\Software\CKAN' foi negado.
   em Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   em Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   em Microsoft.Win32.RegistryKey.CreateSubKey(String subkey, RegistryKeyPermissionCheck permissionCheck)
   em Microsoft.Win32.Registry.SetValue(String keyName, String valueName, Object value, RegistryValueKind valueKind)
   em CKAN.Win32Registry.SetRegistryValue[T](String key, T value)
   em CKAN.KSPManager.LoadInstancesFromRegistry()
   em CKAN.Main..ctor(String[] cmdlineArgs, GUIUser User, Boolean showConsole)
   em CKAN.GUI.Main_(String[] args, Boolean showConsole)
   em CKAN.CmdLine.MainClass.Gui(GuiOptions options, String[] args)
   em CKAN.CmdLine.MainClass.Main(String[] args)
```

My user is Admin of my machine, and ckan gives me this error. I already granted full access to everyone in this registry key, it still don't work. It was working fine with previous CKAN and is now trowing this at startup.
If i run as administrator it works, however i loose url integration.

![image](https://cloud.githubusercontent.com/assets/13473098/10266441/4b6c475e-6a38-11e5-9212-c0b1b687eaea.png)

Once i click dismiss it crashes.
![image](https://cloud.githubusercontent.com/assets/13473098/10266445/6f7c4978-6a38-11e5-82c2-ab7ed4b2321a.png)

Running as Admin as work around until a fix is released. Thanks.

Acess denied error on 'HKEY_CURRENT_USER\Software\CKAN'

**Comment by HebaruSan** [comment]
As of #2820 we no longer store settings in the Windows registry, so this is obsolete.
