### ISSUE TITLE
Fails to connect to repository, windows 7

### ISSUE THREAD

**Issue by promethues5500** [KSP-CKAN/CKAN#1489]
CKAN keeps telling me the following when I try to refresh the mod list:

Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Repository successfully updated

I've googled my heart out and have tried everything within my limited technical know how.

I could really use some help getting this working, as I want to play RSS! Thanks ahead of time.

**Comment by plague006** [comment]
Sometimes errors such as this pop up when github has network difficulties. Is the error still present at this time?

**Comment by promethues5500** [comment]
This issue has persisted for weeks. I have tried other repositories as well
(can't recall the exact addresses, but it's something I found online).
Nothing has worked for me. However, I think it may be related to my
inability to update windows at this time. This issue (ckan) led me to find
the windows updater issue, which I'm yet to be able to resolve.

**Comment by plague006** [comment]
At this point it seems like a general connectivity issue and not particularly related to CKAN. Any firewall software or in your router/modem?

**Comment by promethues5500** [comment]
I shouldn't have any connectivity issues on my end, being that I don't have
any issues with my firewall and any other gaming. Mostly, I think I need to
start with getting windows to update correctly (which is turning into a
whole big ordeal). Once that issue is resolved, I'll check CKAN again. If
the issue persists, I'll hop back on here for more help.

Thanks for the help so far.

**Comment by MarsMullo** [comment]
I had this problem just recently and have fixed by undertaking a WINSOCK reset. look it up on YouTube. It worked for me. I also had connection issues with Windows 10 email at the same time ans windows updates and windows defender virus scan databases would not update too. But internet page connection worked fine. Try this.

**Comment by promethues5500** [comment]
So many hours of updates and restarts. Thank you so much! WINSOCK reset did
it for me. CKAN is working now as well!

Really appreciate it. Now on to KSP RSS!!!! Cheers!

**Comment by promethues5500** [comment]
Well I thought everything was working. Got any idea how I can get .net
framework 4.5.2 to install? It keeps failing, and googling around, once
again, has not led me to a solution. CKAN is giving me an unhandled
exception error when I try to check a mod in the list. I'm betting this is
due to my .net framework issue...

Technology sure can be frustrating sometimes. Thanks for the help.
