### ISSUE TITLE
cmd line options need better documentation, both in the program and on the wiki

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1490]
The help page for ckan (when you do a "ckan.exe help") shows options, but doesn't show that you need dashes for some of the options;  for example, --ksp "<install>"   and --kspdir <installpath>.

The wiki also lacks any information on this

**Comment by tjanke42** [comment]
I'll second this.  The command line help and documentation leave much to be desired.

**Comment by politas** [comment]
Supported. I'm still not sure whether there's a way to specify which KSP install you want to install a mod into, rather than constantly switching the default install.

**Comment by politas** [comment]
Fixed by #2197
