### ISSUE TITLE
Help cant update repositories 

### ISSUE THREAD

**Issue by Haxov** [KSP-CKAN/CKAN#1491]
hello i really want to use this for ksp because i think i broke mine trying to use mods. anyway i try updating the mod list it is says this Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Repository successfully updated
every time  plz help

**Comment by MarsMullo** [comment]
Hello, I am having the same issue. Tried turning off all fire wallsand even installed and ran spyware, malware and antivirus stuff.
I get this message: 
"Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Repository successfully updated"

The repository has 0 content
This is from any attempt to update or get meta data.
I can however copy that address and navigate to it in Firefox.
I had trouble with windows 10 mail recently too at the same time... I have no idea whats going on. All these new systems are just so alien to me now.
![ckan problem](https://cloud.githubusercontent.com/assets/10490435/10391700/2296401a-6edd-11e5-94d8-fbc061afedac.jpg)

**Comment by Postremus** [comment]
Is your System time set correctly?

----- Ursprüngliche Nachricht -----
Von: "MarsMullo" <notifications@github.com>
Gesendet: ‎09.‎10.‎2015 12:27
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] Help cant update repositories  (#1491)

Hello, I am having the same issue. Tried turning off all fire wallsand even installed and ran spyware, malware and antivirus stuff.
I get this message: 
"Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Repository successfully updated"
The repository has 0 content
This is from any attempt to update or get meta data.
I can however copy that address and navigate to it in Firefox.
I had trouble with windows 10 mail recently too at the same time... I have no idea whats going on. All these new systems are just so alien to me now.

**Comment by MarsMullo** [comment]
Yes. It is set to Daylight savings time some weeks ago automatically by
Windows 10.
However I will double check

On 9 October 2015 at 23:43, Martin Panzer <notifications@github.com> wrote:

> Is your System time set correctly?
>
> ----- Ursprüngliche Nachricht -----
> Von: "MarsMullo" <notifications@github.com>
> Gesendet: ‎09.‎10.‎2015 12:27
> An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
> Betreff: Re: [CKAN] Help cant update repositories (#1491)
>
> Hello, I am having the same issue. Tried turning off all fire wallsand
> even installed and ran spyware, malware and antivirus stuff.
> I get this message:
> "Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz
> could not be established.
> Repository successfully updated"
> The repository has 0 content
> This is from any attempt to update or get meta data.
> I can however copy that address and navigate to it in Firefox.
> I had trouble with windows 10 mail recently too at the same time... I have
> no idea whats going on. All these new systems are just so alien to me now.
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN/issues/1491#issuecomment-146831227>.
>



-- 
Regards

Martin Ellis

039268713

**Comment by MarsMullo** [comment]
Have changed it Automatic .. was set to manual setting of time.

On 9 October 2015 at 23:43, Martin Panzer <notifications@github.com> wrote:

> Is your System time set correctly?
>
> ----- Ursprüngliche Nachricht -----
> Von: "MarsMullo" <notifications@github.com>
> Gesendet: ‎09.‎10.‎2015 12:27
> An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
> Betreff: Re: [CKAN] Help cant update repositories (#1491)
>
> Hello, I am having the same issue. Tried turning off all fire wallsand
> even installed and ran spyware, malware and antivirus stuff.
> I get this message:
> "Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz
> could not be established.
> Repository successfully updated"
> The repository has 0 content
> This is from any attempt to update or get meta data.
> I can however copy that address and navigate to it in Firefox.
> I had trouble with windows 10 mail recently too at the same time... I have
> no idea whats going on. All these new systems are just so alien to me now.
>
> —
> Reply to this email directly or view it on GitHub.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KSP-CKAN/CKAN/issues/1491#issuecomment-146831227>.
>



-- 
Regards

Martin Ellis

039268713

**Comment by MarsMullo** [comment]
I have found a solution to the problem.
I undertook a WINSOCK reset. Look it up on youtube if you want to try it.
Other issues at the same time were .. WINDOWS 10 mail not syncing, windows defender and windows updates not connecting.
Try this first before undertaking any virus scans and malware software things.. I have no idea how it got all screwed up but a reset worked.

**Comment by Poofey** [comment]
i had this problem, the winsock reset worked like a charm. ty.

**Comment by MarsMullo** [comment]
No worries Poofey ... it takes ages to sort these things for me.. I'm no expert.. feels good to know it helped someone else...  without the old... reinstall and the like thing you hear every now and then.

**Comment by plague006** [comment]
Is anyone still experiencing this issue? Speak up or it shall be closed in 1 week's time.

**Comment by Delwin9999** [comment]
I just came back after being out a while.  I downloaded the newest version of CKAN and I'm getting this error.  I tried resetting as noted above but I'm still getting it.

**Comment by politas** [comment]
So, is your system time correct?

**Comment by Delwin9999** [comment]
Yes.  I'm US Central time and the clocked is sync'd via NTP.  Likewise if I just download the master file directly I can do that with no problem so it's not a connectivity issue on my end or Github's.

**Comment by Delwin9999** [comment]
Also the auto update doesn't work either so that means that there's some connectivity either within CKAN or the layers beneath it.

**Comment by politas** [comment]
Which operating system are you on?

**Comment by Delwin9999** [comment]
Windows 10 build 14931

Interestingly I have CFAN too (for Factorio) and I just ran it.  It auto-updated properly but then the updated version was unable to connect as well.  When I get home tonight I'll go back to old versions and see if I can't track down what version of CKAN broke this.

**Comment by Delwin9999** [comment]
OK, solved this.  It turns out COMODO security tools intercepted the KSP install and put it on a virtual drive.  Permissions are wonky when dealing wit the pass-through virtual drives that COMODO creates and I gave up on it and uninstalled COMODO.

**Comment by politas** [comment]
Thanks for letting us know
