### ISSUE TITLE
CKAN can't launch KSP on Linux

### ISSUE THREAD

**Issue by SilverWingedSeraph** [KSP-CKAN/CKAN#1492]
CKAN no longer launches KSP under Linux. When I press "Launch KSP" nothing happens, and no new processes are spawned by CKAN. This happens on all my KSP installs.

**Comment by Postremus** [comment]
Go to Settings -> "KSP command line".
See if the name of executable is correct. On linux, it should be "KSP.x86" or "KSP.x86_64"

**Comment by SilverWingedSeraph** [comment]
It is "KSP.x86_64 --single-instance". I have tried creating shell scripts that launch the game and pointing it to that; changing the permissions of the executable to 0777; and deleting and reinstalling KSP. None of these worked. However, downloading CKAN again did fix the issue, so I'm not sure what was going on there; perhaps I just had a bad download before (in flight error or on disk error?).
