### ISSUE TITLE
@techman83 MIA

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#1493]
Hi All,

We're performing some large tasks at work at the moment (our primary datacentre decided to kick out all it's customers by Christmas and decided to move the schedule ahead and only give everyone 8 weeks notice), so It's left me with not a lot of spare cycles!

Hopefully after I get back from PAX Aus at the end of the month I'll be a little less sporadic.

I'll keep an eye on my email, so tag me if anything needs addressing. But it all seems pretty stable.

@techman83

**Comment by pjf** [comment]
I keep spotting you on IRC! You're not really gone! :P

**Comment by techman83** [comment]
<ghostly presence>I'm a figment of your imagination :P</ghostly presence>

**Comment by techman83** [comment]
Ok, I'm more or less back on deck now :)
