### ISSUE TITLE
Search on Relationships

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1494]
Since the netkan/ckan spec has comments, why not add the comments to the Metadata window, and allow searching inside the comments.  For example, PlanetPacks

**Comment by plague006** [comment]
Comments are generally used internally within the metadata team to indicate things like who to ask questions to about a specific mod, or changes that can be made at specific milestones to metadata. It is not an inclusive tagging system where mods have comments that specify their category. I think what you want is more along the lines of #1021.

Some non-categorical examples of comments which would only serve to confuse some users:

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/AdvancedJetEngine.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BahamutoDynamicsPartsPack.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BurnTogether.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CactEye2.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Canadarm.netkan

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CustomAsteroids-Pops-Stock-Inner.netkan

:-1: from me. We shouldn't be surfacing internal comments to end users and we shouldn't try to co-opt comments to server a purpose other than their intended one.

**Comment by linuxgurugamer** [comment]
Got it.

I got started on this when i saw the message about putting "PlanetPack" 
into a comment.

After reading your reply (which makes total sense), how about changing 
this from a comment search, to a relationship search;  for example, if I 
want to see all the available planetpacks, I could search on 
"Kopernicus" in the "Depends" relationship.  Right now, I have to 
download the CKAN repo and grep for that.  Doable, but not everyone 
knows or wants to know/install Linux/unix based commands.



JBB

**Comment by ayan4m1** [comment]
Reverse dependency lookup in the Relationships tab would support that use case? That way we wouldn't have to spec out as much related to filter/search changes, just a new element in the dropdown on the Relationships tab.

**Comment by politas** [comment]
It would certainly be useful for one-way conflicts relationships.

**Comment by HebaruSan** [comment]
#2736 would be a good time to add more searches.
