### ISSUE TITLE
Buffalo missing from the CKAN

### ISSUE THREAD

**Issue by birdog357** [KSP-CKAN/CKAN#1495]
I can't see the CKAN icon on my PC but on my higher res tablet I can just make out the end of the gray icon in the title. I can't find it in CKAN.

https://kerbalstuff.com/mod/1199/Buffalo:%20NASA%20Inspired%20MSEV%20-%20Explore%20In%20Style?noedit=True

**Comment by pjf** [comment]
As of a couple of hours ago it's there! The CKAN icon indicates it's been submitted for indexing, it can sometimes take a little while after that before a human's able to finangle a `.netkan` file that our indexer likes. :)
