### ISSUE TITLE
CKAN and KDE are having problems around mimeapps.list

### ISSUE THREAD

**Issue by kolAflash** [KSP-CKAN/CKAN#1498]
Looks like CKAN writes ~/.local/share/applications/mimeapps.list in a certain format (using spaces before and after the equals signs " = "). But KDE doesn't likes that. Please have a look at this KDE bug report.

https://bugs.kde.org/show_bug.cgi?id=354092

Maybe related:
https://github.com/KSP-CKAN/CKAN/issues/723
https://github.com/KSP-CKAN/CKAN/pull/1434

**Comment by pjf** [comment]
Oh gosh dang it.

Is KDE cool *without* the spaces?

**Comment by pjf** [comment]
(Labelling as GUI as I believe the cmdline and core don't touch the mimeapps file)

**Comment by Postremus** [comment]
You are right, pjf, only the gui uses the file.

----- Ursprüngliche Nachricht -----
Von: "Paul Fenwick" <notifications@github.com>
Gesendet: ‎20.‎10.‎2015 09:07
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] CKAN and KDE are having problems around mimeapps.list(#1498)

(Labelling as GUI as I believe the cmdline and core don't touch the mimeapps file)

**Comment by kolAflash** [comment]
Thank you for the quick response!

Yes, after removing the spaces around the equals signs everything is OK.
" = " -> "="

OK example:
```text/plain=kde4-kwrite.desktop;kde4-kate.desktop;kde4-calligrawords_ascii.desktop; ```

Broken example:
```text/plain = kde4-kwrite.desktop;kde4-kate.desktop;kde4-calligrawords_ascii.desktop; ```

I guess the spaces are problematic because of this example of a valid line:
```application/MySQL Workbench=mysql workbench.desktop; ```
This contains spaces in the term before and behind the =. So spaces are clearly to be handled as part of those terms and additional spaces would change the meaning of those.


By the way:

CKAN shouldn't rewrite mimeapps.list every time it starts. It does this, also if absolutely nothing is changed! Even not inserting spaces.

Additionally I'd suggest to modify only the lines which CKAN cares about. And leaving all other lines as they are (including the way spaces are used there).

**Comment by politas** [comment]
Unity (The Ubuntu desktop rather than the game engine) doesn't like those spaces, either.

**Comment by politas** [comment]
Should make it clear that the ~/.local/share/applications/ckan-handler.desktop file has the same problem. There should be no spaces around the "=" signs.

**Comment by politas** [comment]
I would also say that this .desktop file creation and editing of the mimeapps  should probably only happen once per CKAN version at most. Blasting mimeapps over and over again just makes any problem vastly worse.

**Comment by politas** [comment]
By the way, what does the CKAN GUI do if launched referencing a .ckan file? I'm afraid to try it.

**Comment by danielrschmidt** [comment]
I traced down the issue: The mime / desktop file is written in GUI/URLHandlers.cs using [a library called ini-parser](https://github.com/rickyah/ini-parser) that provides a class 'FileIniDataParser'. Said class has a configuration option "AssigmentSpacer", [see here](https://github.com/rickyah/ini-parser/wiki/Configuring-parser-behavior). That option should default to the empty string, but it instead defaults to " ", as can be seen in line 53 [over here](https://github.com/rickyah/ini-parser/blob/development/src/IniFileParser/Model/Configuration/IniParserConfiguration.cs). 

That being said, it should be sufficient to add the following line to GUI/URLHandlers.cs:

parser.Parser.Configuration.AssignmentSpacer = "";

after line 118. 

See also [this example](https://github.com/rickyah/ini-parser/blob/development/src/INIFileParser.Example/Program.cs), line 23.

I don't have a mono build environment, so I can't try right now.

**Comment by politas** [comment]
AH, excellent! Can we also work in a way to only call that process on a CKAN upgrade?

**Comment by pjf** [comment]
Github has closed this with the merge of #1536. Given that change will repair files that previously had a booched separator, I think we're covered for fixing existing systems as well as new installs. I'll be pushing out a new release including those changes this afternoon.

Having said that, you should all feel free to re-open this if you feel appropriate.

**Comment by politas** [comment]
I'll see how the new version works. Is it escaping spaces in exec file paths, too?

**Comment by kolAflash** [comment]
Looks like there are no more spaces inserted. Nevertheless, the whole file is still being rewritten on application start.

I guess the following would be the best:
Just rewrite IF something changed.
Don't touch lines which are not about CKAN.
E.g. if there's currently a line saying
```
text/plain= myprogram.desktop;
```
and there's a space in from of " myprogram" because that's the way the desktop file is named, CKAN will change this line to
```
text/plain=myprogram.desktop;
```

**Comment by politas** [comment]
If the file was for some weird reason named with a space at the start (which is pretty darn unlikely in the Linux world), the line would actually have to be 
text/plain=" myprogram.desktop";

**Comment by danielrschmidt** [comment]
The spacing issue was fixable without much knowledge of CKAN or C#, re-writing the file only when it is needed is a different matter: Where to put the if-something-has-changed-statement is the easy part, but how to figure out if something has changed? 

And yes, just re-writing the CKAN-lines in the files would probably be a better solution, but then you need to rewrite the entire URLHandlers class: Manually read the file into some container, figure out if the CKAN line is already there, modify that line if present (otherwise, add it) and manually write back the file... the way it is done now is much easier.
