### ISSUE TITLE
Add a "Report Issue" button

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/CKAN#1502]
This was requested by @Lyneira on the ckan irc:
> You guys should really have a think on how to discourage users from dropping by modders' threads first when there's an install issue with CKAN. Maybe a "report issue with this mod" button in the UI that leads to a CKAN issue tracker or forum thread or something.

**Comment by Postremus** [comment]
:+1:

**Comment by nobodyhasthis** [comment]
This a good idea. I think it is fair to say that in some modding threads. Reporting CKAN problems can cause significant resentment on the part of mod authors. The CKAN issue tracker link in the forum is not immediately obvious either. I imagine most users would not think to go there for help first. A button in the UI that leads to a CKAN issue tracker or forum thread would help users and mod authors.

**Comment by nobodyhasthis** [comment]
As it currently stands in the GUI there is one obvious link to the forums within the metadata listing. That takes us straight to the mod author. Who will either bite our heads off for asking a CKAN question or direct us to the CKAN forum. Remember after a while it gets frustrating to for mod authors to deal CKAN questions when they don't publish the metadata. 

I have even had a case where a mod author has sent me a PM asking "what is this CKAN that everyone complains about ?". After being asked repeatedly to fix it in his own thread. Poor guy had no idea it even existed till the hate mail rolled in. 

The other link in the GUI is less obvious. It is under Help > About. That does link to the CKAN forum. However the actual issue tracker is buried in a wall of text. However at least it does take the users to the right place on the forums. 

Can we have a NetKan issue link on the GUI please?
