### ISSUE TITLE
Feature Request:  Directory delete option on uninstall

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1507]
Every once in a while, removing a mod leaves files behind which weren't installed, but which can cause problems.  for example, leaving a cfg file behind, etc.

I think it would make sense to add an option in the Netkan file which would specify that the entire directory should be deleted upon uninstall (and possibly deleted BEFORE install), regardless of whatever files are already in there.

This would be very specific, and I don't think a lot of mods would use it, but it can solve some problems for problematical mods such as FAR

**Comment by plague006** [comment]
IMO your idea for implementation is off the mark. A metadata option is not safe as one mod could easily break another by deleting their files.

On the other hand, CKAN knows what files it has installed at any given time, so if a mod is removed maybe CKAN could check that no other mod has a file currently installed to that folder, and if no mod has a file there could present the option to delete that folder.

**Comment by nobodyhasthis** [comment]
I agree on the proposal but the issue has been around for a long time without any viable solution. When trying to explore just a basic policy decision to support this in issue #1610. Which in turn references every other passed issue report that mentions mod folder deletion or _gamedata_ health checking. We listed some good arguments against doing it along side any benefits.

**Comment by mathuin** [comment]
Wouldn't it be better for a mod's metadata to include a reference to files and/or directories that it creates?  That would allow for the deletion of said content at the time the mod is removed via CKAN.

**Comment by plague006** [comment]
@nobodyhasthis it's true, a lot of issues are stuck in limbo and with 252 open issues it's really hard to keep track. I'm trying to work through the backlog that have had no attention in over half a year. With that said #1610 definitely has a more productive discussion so I'll be closing this in favour of it.

@mathuin at time of install CKAN creates entries in registry.json for every single file installed and what mod it is tied to.

Closing for #1610
