### ISSUE TITLE
Request to override max KSP version

### ISSUE THREAD

**Issue by dronkit** [KSP-CKAN/CKAN#1513]
I would like to suggest some kind of option to override the max KSP version for mods. A scenario is, I installed KSP 1.0.5 which came out yesterday, and most of the mods I use aren't updated yet, and are invisible to CKAN, though many are reported to work well or relatively well in 1.0.5.
Maybe it could be enabled via settings menu, and mods with a max KSP version<current KSP version be able to be selected, installed, and managed but be displayed in red, and/or with a warning on installation.
Thanks!

**Comment by pacbard** [comment]
I'm not a CKAN contributor, but a solution to your problem is already in the works for a future CKAN update. See pull #1499 for a discussion between the developers.

**Comment by plague006** [comment]
As a workaround/hack just open your readme.txt in the KSP install folder and change 1.0.5 to 1.0.4.

**Comment by dronkit** [comment]
Thanks guys!
