### ISSUE TITLE
Cannot uninstall installed mods from the incompatible filter list

### ISSUE THREAD

**Issue by cgc007** [KSP-CKAN/CKAN#1515]
Subject pretty much says it all, I can uncheck installed incompatible mods and the "apply changes" button doesn't activate. I have to uncheck the incompatiible ones, then switch filters to installed and recheck and reuncheck all the mods in question there to get it to work properly.

Should be a relatively simple fix I'd think, searched a bit on here but didn't find that listed as an issue, sorry if it's a duplicate!

**Comment by HebaruSan** [comment]
Ironically this wasn't a duplicate when it was created, but it is now; closing in favor of #1842 because there's more discussion of the cause and solutions in that one. Thanks for the report!
