### ISSUE TITLE
EVE update still not in the list

### ISSUE THREAD

**Issue by BiZZKeryear** [KSP-CKAN/CKAN#1517]
I know that EVE (formerly EVE Overhaul now became EVE) got an update shortly after 1.0.5 came out (for 1.0.5) and the author even said that he pushed it to CKAN. Seems it is still waiting.... or stuck somewhere.

**Comment by Olympic1** [comment]
It is still waiting on a merge. We had to fix the LowRes netkan, because EVE only provides a HighRes for the moment.

https://github.com/KSP-CKAN/NetKAN/pull/2553

**Comment by BiZZKeryear** [comment]
Honestly.... it is like  someone told to me once (actually he said it all the time)... people do not care why it isn't working. The just care that it isn't working.
I admit I am the same. I know that the mod exists. I know it can be put in CKAN. I don't care that there is or is not a low res version I probably  will never use (either in high res or not at all)

**Comment by Olympic1** [comment]
EVE can now be found in CKAN
