### ISSUE TITLE
Command line CKAN both does and does not know where KSP is located

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN#1522]
I have three KSP installs (two for testing, etc.).  When I type

```
ckan ksp list
```

the response is:

```
Listing all known KSP installations:

1) "KSP" - g:/steam/SteamApps/common/Kerbal Space Program
2) "KSP Parts" - G:/Steam/steamapps/common/KSP Parts
3) "KSP The Martian" - G:/steam/steamapps/common/KSP The Martian
```

So CKAN clearly know where my KSP installs are.  However, if I type any other command, e.g.:

```
ckan clean
```

the response is:

```
I don't know where KSP is installed.
Use 'ckan ksp help' for assistance on setting this.
```

CKAN is confused, and I don't know how to un-confuse it.  Thanks in advance for any help you can provide for this.  What do you need from me to help you investigate this?  Log files?  Other?

**Comment by politas** [comment]
I think you need to set a default install to use the command line for anything other than listing and adding installs. That's been my experience.
