### ISSUE TITLE
Reupload of a zip file on GitHub

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/CKAN#1523]
SolverEngines v1.13 was added yesterday on GitHub with a `.zip` file but this file got changed later because of a bad packaging. I tried to fix this in [`897ffd3`](https://github.com/KSP-CKAN/CKAN-meta/commit/897ffd39b955b723d81abd27b4f2dd42916527c3), but our bot changed this back to the old zip file in [`5430923`](https://github.com/KSP-CKAN/CKAN-meta/commit/5430923aeba2d89a7734ec6ee6797befabc137c3).

Is this solvable?

**Comment by plague006** [comment]
Try a forced epoch.

**Comment by Olympic1** [comment]
https://github.com/KSP-RO/SolverEngines/releases/tag/v1.13

When Nathan released v1.13 of SolverEngines, he included a zip file of 526 kB. Later he removed the zip and added a new, smaller one of 37 kB. CKAN keeps using the first zip file because that is the one that was cached on release.

**Comment by plague006** [comment]
The only end-user effect this will have is an inaccurate download size in the CKAN client. The correct file will be downloaded. So if @techman83 has a chance it'd be nice to delete the cached version but if that never gets done, it's not really an issue IMO.

**Comment by Olympic1** [comment]
ok, good to know

**Comment by techman83** [comment]
If you know the filename it might help me, as I don't see it.

**Comment by Olympic1** [comment]
SolverEngines_v1.13.zip

**Comment by Olympic1** [comment]
Poking @techman83 to see if this is fixed. Also, is there a way I can delete the cached `zip` file from my computer?

**Comment by plague006** [comment]
> Also, is there a way I can delete the cached `zip` file from my computer?

Missed this or would have replied sooner: you can delete your local cache by opening the CKAN gui then opening `Settings` then `CKAN Settings` then clicking the `Clear Cache` button.

**Comment by Olympic1** [comment]
I found that out, that's why I closed this
