### ISSUE TITLE
Forum migration broke all the old links

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/CKAN#1527]
The KSP forums are migrated from `vBulletin` to `IPS`, unfortunaly this migration broke all the old forum links. I asked KasperVld if he could make a redirection script so that the old links redirect the user to the new links, but looks like that isn't possible.

> Olympic1: I noticed that the old links doesn't work anymore, I thought you would redirect them to the respective thread.

> KasperVld: Turns out it's not possible, sorry to brake CKAN and all other posts. I did look into it though.

EDIT: Turns out that the new forum links also need to have to be changed because some threads were removed so almost every thread has a different ID.

Old forum link (CKAN)
http://forum.kerbalspaceprogram.com/threads/100067

New Link (CKAN)
http://forum.kerbalspaceprogram.com/index.php?/topic/90246-/

**Comment by Olympic1** [comment]
Comment by @damerell

> As you'll see at http://forum.kerbalspaceprogram.com/index.php?/topic/126583-welcome-to-the-new-forums/ all existing forum links have broken (sigh) but there is a tool to find the new thread given the old thread's URL. I suggest a bulk conversion of all homepage links in CKAN metadata which are old-forum links into links of the form http://forum.kerbalspaceprogram.com/showthread.php?t=nnnnnn would save a lot of hassle down the line.

So changing `nnnnnn` with the old forum ID `100067` will give http://forum.kerbalspaceprogram.com/showthread.php?t=100067 and will redirect automatically to the new thread.

**Comment by valerian** [comment]
I'm pretty sure that by the end of the day the old URLs will work again, thanks to a redirect rule.

**Comment by Olympic1** [comment]
Closing this as Kasper has made a redirection script so that old links work again
