### ISSUE TITLE
"Compatible" mods with incompatible dependencies aren't listed in any filters.

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1529]
For example, QuizTechAeroPack is marked as compatible with 1.0.5, but its dependency ModuleRCSFX is not. As a result, QuizTechAeroPack is apparently ruled out of all filters, even "All".

Confirmed that this is the specific situation by recent correction of ModuleRCSFX compatibilty, which took it out of compatibility with 1.0.5, prior to which, QuizTechAeroPack was listed in "Compatible" filter and others.

**Comment by plague006** [comment]
Closing for https://github.com/KSP-CKAN/CKAN/issues/1695
