### ISSUE TITLE
Provide a way to trigger a "ckan repair" operation in the GUI

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1530]
I believe this is the only function that regular users would need to do  occasionally that isn't available in the GUI

**Comment by plague006** [comment]
Oh, I didn't realize what CKAN clean was. Clearing the cache via the GUI has been around since da8b46f9c5318c1dc1d4963b8aa43808616bc01c or earlier.

**Comment by politas** [comment]
Ok, there's another command line option which I think is what I meant. Scan or repair?

**Comment by plague006** [comment]
Some of the work for this:

https://github.com/KSP-CKAN/CKAN/compare/master...plague006:feature/repair_registry_button?expand=1

Pretty sure the button I have would do as much for a broken registry as having a functional button. :S

**Comment by politas** [comment]
That's a good start for the UI. I think it would be good to add a statement explaining the level of risk. I am always annoyed when I find a black box option where I have no idea exactly what it is doing and whether it has a chance of breaking my setup.

**Comment by plague006** [comment]
There's no risk. It reads the installed_modules and rewrites them.

**Comment by politas** [comment]
Ok, so it is worthwhile saying that it is a safe operation, in order to allay users' fears.

**Comment by plague006** [comment]
Did more digging. the repair function was a time-and-place thing. It's for problems that happened when they changed the registry format to include an installed files manifest (they didn't always).

If someone is installing a version of CKAN < v1.0 then they can use the CLI to run the repair. If "ckan repair" gains more functionality in the future this should definitely be revisited though.

**Comment by HebaruSan** [comment]
Closing as not needed for now.
