### ISSUE TITLE
EVAManager version is wrong in registry

### ISSUE THREAD

**Issue by tivec** [KSP-CKAN/CKAN#1534]
This was originally part a comment on #1532 but I figured I'd move it up to a new issue instead.

EVAManager is updated for 1.0.5 on Kerbalstuff as version 6, but the required version has KSP version 1.0.4 in the registry.

**Comment by damerell** [comment]
I encouraged Tivec to do this since they could not re-open #1532, it being opened by someone else.

**Comment by Olympic1** [comment]
Updated in https://github.com/KSP-CKAN/CKAN-meta/commit/6503e8dd0032f3b0bdc1ae2cd72bf6be068214f7
