### ISSUE TITLE
Kerbal Engineer Redux 1.0.5

### ISSUE THREAD

**Issue by evictedSaint** [KSP-CKAN/CKAN#1541]
I noticed Kerbal Engineer Redux has been updated to 1.0.5 for a little over a month now (11/09/15) but is still listed as 1.0.4 on CKAN.

Please forgive me if I've made a mistake or am over-stepping, I'm very new to this.

**Comment by Olympic1** [comment]
The latest version was released on 15 July. All the download pages, GitHub and Curse, say that is for 1.0.4. Even on the forums it says 1.0.4.

Where did you read this that is was released for 1.0.5?

**Comment by linuxgurugamer** [comment]
The dev version is 1.0.5, but they don't reference dev versions in CKAN

**Comment by evictedSaint** [comment]
I am mistaken, yes. I'm sorry, thank you.
