### ISSUE TITLE
Slow download speed in the Windows GUI 

### ISSUE THREAD

**Issue by mkalte666** [KSP-CKAN/CKAN#1543]
Im using Windows10.

Since some time i often experience Downloading issues - the program shows really low download rates (some 100kbps at max) - sometimes. Sometimes means that in my last install with 5 mods updated that happend once. With the command line tool i dont run into this and if i download the .zips manually (i.e. from github) i also do not run ito the issue.

Am i filing a duplicate or is this new / my systems fault?

**Comment by birdspider** [comment]
there was a related issue #840 (mac osx though) - does mouse movement improve speeds ?

**Comment by mkalte666** [comment]
No, moving the mouse does not help at all.

Other thing i noticed while paying around (installing a bit random mods..) is that the problem occures in the last megabytes of the download. 

Also i made a screenshot. 
![moremeh](https://cloud.githubusercontent.com/assets/3924804/11846953/5a7d6ad0-a41b-11e5-9616-43af7f90c493.png)

**Comment by plague006** [comment]
Has this issue persisted?
