### ISSUE TITLE
SSL error with certificate from letsencrypt

### ISSUE THREAD

**Issue by Schnobs** [KSP-CKAN/CKAN#1544]
The problem:
ERROR CKAN.ErrorDialog (null) - Failed to download "http://blizzy.de/toolbar/Toolbar-1.7.10.zip" - error: SslCaCert

Try as I might, I can't get mono/ckan to accept the certificate. I tried:
- certmgr -ssl https://blizzy.de
- mozroots --import --sync
to no avail.

More generally, why does CKAN try SSL on a plain http:// URL?
(update: because blizzy redirects everything to https)
So the problem seems to be my inability to get the CA cert, not a ckan issue as such.
I apologize for the inconvenience.

**Comment by Olympic1** [comment]
We noticed this issue as well. I tried https for the download but it also fails then.

**Comment by Schnobs** [comment]
Funny enough, it works in the browser; but wget and curl (and probably other CLI clients) balk at the URL.

I could "solve" this issue by manually fetching the letsencrypt root certificates from https://letsencrypt.org/certificates/

On Debian/Ubuntu:
- D/L them into /usr/local/share/ca-certificates/<subdirectory> 
- run "update-ca-certificates"

**Comment by plague006** [comment]
Dunno if this will help the issue with Jenkins, but I'll tag @techman83 to bring his attention to it.

**Comment by techman83** [comment]
It should, but I grabbed all 4 certs off the lets encrypt site, successfully imported them and bizarrely got the same result. CKAN/NetKAN use libcurl, so getting the right certs in the store will totally resolve this issue.

**Comment by politas** [comment]
Which files from lets encrypt are supposed to go in /usr/local/share/ca-certificates/? The update-ca-certificates man page says it will load files with a .crt extension, but none of the files in https://letsencrypt.org/certificates/ have that extension.

**Comment by Schnobs** [comment]
politas: you need the root cert and either intermediate (both won't hurt). I fetched the text files and renamed them to crt.
