### ISSUE TITLE
Request: Verify KSP version via BuildID.txt

### ISSUE THREAD

**Issue by NathanKell** [KSP-CKAN/CKAN#1545]
It would be very, very helpful if CKAN would make sure that players on KSP 1.0.5 are in fact on build 1028 or above, since many mods built for "KSP 1.0.5" will only work on build 1028+ (i.e. the "silent patch").
Players on steam, of course, are forced to get the update. But no one else is, and we're fielding a lot of support requests about it, and it'd be real nice if CKAN checked. :)

**Comment by plague006** [comment]
You would want CKAN to check the build ID and surface an error message for certain builds indicating to a user that they should upgrade?

**Comment by NathanKell** [comment]
Yep, that would be awesome! We're not going to do a silent patch again (in theory), but you never know. And people *still* haven't gone to 1028+ for 1.0.5, I still get 'bug reports'.

**Comment by Dazpoet** [comment]
Seeing as this is a modbreaking (aka we install mods incorrectly) problem should it not warrant a bug marking and more stars than one?

**Comment by plague006** [comment]
@Dazpoet By all means, I'm just trying to get *any* kind of label onto issues. :)

**Comment by nobodyhasthis** [comment]
@politas Has this bug report be be resolved by merging #1645 Support of reading build IDs.
I am just looking through for stuff that could possibly be clean off the 'to do list'.

**Comment by politas** [comment]
Yes, indeed.
