### ISSUE TITLE
Default KSP install not saved

### ISSUE THREAD

**Issue by eiktyrner** [KSP-CKAN/CKAN#1546]
After setting a KSP installation as default it doesn't save on restarting CKAN.
I've tried removing the Steam default so I only have my proper one in C:/Games but it still defaults to the one from Steam. No error messages or anything.

Here is a gif on what happens.
http://imgur.com/KuLzydc

Windows 10
CKAN v1.16.0 Ringshine

**Comment by ayan4m1** [comment]
In the registry under `HKEY_CURRENT_USER\Software\CKAN` there are a few keys set to control which directory is used. My guess is there is a subtle bug or migration issue and yours are, to use the technical term, "out of whack."

Mind posting those keys and their values? Thanks for your report!

**Comment by politas** [comment]
You could also run `ckan ksp list --debug` on a command line and pastebin the results of that, which might tell us something.

**Comment by eiktyrner** [comment]
Did you guys check the date on this? I'm not able to do any further investigation this much later...

**Comment by politas** [comment]
Yeah, it's as much cleaning up old issues as anything. It's rude to close off without offering something, and I don't know how this didn't get a response earlier. Sorry about that. If you're not having any issues with later releases, we'll close this off.
