### ISSUE TITLE
Scrolling the mod list with the mouse wheel doesn't work initially

### ISSUE THREAD

**Issue by madadam** [KSP-CKAN/CKAN#1548]
When I start CKAN and move the mouse cursor over the mod list, then turn the mouse wheel, the modlist doesn't scroll. Not even when I first click on it. However, when I click outside the CKAN window, then click back on it, the mouse wheel scrolling starts working as expected.

I'm using CKAN v1.16.0-0-g7206ce5. I'm on Ubuntu 15.10.

**Comment by politas** [comment]
I find the same thing on Ubuntu 14.04, and always have. You can also usually get the scroll wheel to work by selecting and then deselecting a mod. I thought there was an existing issue for this, but I can't find it.
