### ISSUE TITLE
Updated Mods since November

### ISSUE THREAD

**Issue by 5k1n1** [KSP-CKAN/CKAN#1550]
KAS Last updated 11 November 2015 - v0.5.5 for KSP 1.0.5
http://forum.kerbalspaceprogram.com/index.php?/topic/83468-105-kerbal-attachment-system-kas-055/

KIS Last updated 11 November 2015 - v1.2.3 for KSP 1.0.5
http://forum.kerbalspaceprogram.com/index.php?/topic/101928-105-kerbal-inventory-system-kis-123/

Universal Storage 
https://kerbalstuff.com/mod/250/Universal%20Storage

mfg Timon :)

**Comment by Olympic1** [comment]
All the latest releases of these mods are available on CKAN, I can't see what the problem is.

**Comment by politas** [comment]
Note that all three of these updates are for KSP 1.0.5 only. CKAN will not show them for KSP 1.0.4 installs.
