### ISSUE TITLE
Add a way for find_regexp with find_matches_files true to allow installation of multiple files

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1552]
As noted in KSP-CKAN/NetKAN#2863, a find_regexp directive with find_matches_files set to true only matches and installs one file, even if there are several that match the pattern. (It also doesn't seem to match either the first or last file alphabetically) If it matched and installed all files that match the regexp pattern, we could do things like install a set of example craft files into the Ships/SPH folder based on wildcard matching. 

Also, strangely, when attempting to match a set of files like this:
/KAX/Example Craft/KAX Bungalow.craft
/KAX/Example Craft/KAX Choppah.craft
/KAX/Example Craft/KAX ESpirit.craft
/KAX/Example Craft/KAX Horizon.craft
/KAX/Example Craft/KAX Predator.craft
/KAX/Example Craft/KAX Sparrow.craft

This is the results I got with different strings:

"find_regexp" : "Example.Craft.*craft"
"find_matches_files" : true
"install_to" : "Ships/SPH"

installed KAX Choppah.craft into Ships/SPH

"find_regexp" : "KAX.*craft"
"find_matches_files" : true
"install_to" : "Ships/SPH"

tried to install KAX Choppah.craft into Ships/SPH/Example Craft/ (which failed due to non-existent directory)

It's not clear why it tries to use the directory name in the second example but not the first. Nor is it clear why it ignored the /KAX directory level in both.

**Comment by plague006** [comment]
:-1: for changing the way existing functions act.

If you want to propose an entirely new function that allows selecting multiple files that's a whole other story. In that case I would much prefer to see an `install_as` function as @dbent has mentioned (basically select a folder and install it under a different name, so that we can `find: Example Craft` and `install_as: SPH`.

**Comment by politas** [comment]
Then the flag is misnamed, because it matches _a_ file, not files.

**Comment by politas** [comment]
Covered by #2170
