### ISSUE TITLE
ckan.exe remove --all/ckan remove --re tries and fails to uninstall an autodetected DLL 

### ISSUE THREAD

**Issue by ProjectGemini** [KSP-CKAN/CKAN#1553]
Specifically, (using command line), I get the error "I can't do that, KSPSteamCtrlr isn't installed." As you might imagine, this is a little bit of an issue. "KSPSteamCtrlr" is an autodetected DLL inside the SQUAD folder. 

Using version v1.16.0-0-g7206ce5

**Comment by HebaruSan** [comment]
`Cmdline/Remove.cs` loops over `Registry.Installed(false)`, which includes auto detected mods that can't be removed. It should be using `Registry.InstalledModules` instead, which should only include things that can be removed.
