### ISSUE TITLE
Retry change set if error occurs 

### ISSUE THREAD

**Issue by jbw** [KSP-CKAN/CKAN#1556]
Currently when I select a bunch of mods into install and an error occurs downloading one of them I have no way of retrying the change set/or individual mods (it disappears) and I have to go through and reselect again.

**Comment by nobodyhasthis** [comment]
Possibly related to issue #1572. Where there is a suggestion to storing a temporary .ckan export to allow user to retry, abort or wait for bad gateway error to resolve. This would at least remember the selection and save some frustration.
