### ISSUE TITLE
zombie KSP installs listed with `ckan ksp list`

### ISSUE THREAD

**Issue by davidhyman** [KSP-CKAN/CKAN#1558]
steps:
- create a second KSP 'install'
- use CKAN to manage mods with that install (select install)
- delete that install

actual: `<dir>  is not a vaild install` when using `list` or `forget` commands

expected: missing install is not listed OR missing install is actually forgotten when using the `forget` command

It would also seem the zombie install has a 'name' of `null` so cannot be referenced by the forget command

(in example below, drive 'G' was the second KSP, now deleted)

``` posh
 X:\Steam-Games\Kerbal Space Program>ckan ksp list

101 [1] WARN CKAN.KSPManager (null) - Kerbal Space Program at G:/Steam-Games/Kerbal Space Program is not a vaild install
Listing all known KSP installations:

1) "auto" - c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program

X:\Steam-Games\Kerbal Space Program>ckan ksp forget "G:/Steam-Games/Kerbal Space Program"
107 [1] WARN CKAN.KSPManager (null) - Kerbal Space Program at G:/Steam-Games/Kerbal Space Program is not a vaild install
Couldn't find install with name "G:/Steam-Games/Kerbal Space Program", aborting..
```

p.s. 'vaild' -> 'valid' ;)

**Comment by Dazpoet** [comment]
I guess... better late than never? This issue haunted me for a long LONG time and I solved it [here](https://github.com/KSP-CKAN/CKAN/issues/1836#issuecomment-254557598)

**Comment by politas** [comment]
There's another way to get rid of them: add a new instance of ksp (see #1859). There is work being done on a fix for both issues.
