### ISSUE TITLE
CKAN/KSP Demo Functionality

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN#1559]
So after seeing http://forum.kerbalspaceprogram.com/index.php?/topic/129320-modding-the-demo-current-demo-version-10/ on the official forum, I went ahead and downloaded the demo, and pointed CKAN at it, and CKAN merrily fetched a list of plugins that would work for the demo.

This is actually something that (IMO) should not work, as CKAN should be smart enough to figure out that the KSP client is the demo client, then give the player a nag message that CKAN is only intended to be used with the full version and direct the player to https://kerbalspaceprogram.com/kspstore/index.php?p=22 .

I haven't looked that much into this issue to see if there's an easy way to stop this from occurring, but I don't think this is desired behavior regardless.

**Comment by techman83** [comment]
I don't think we really should be policing this. If Squad allow the demo to load mods, then why not let them experience how awesome KSP is with mods and how easy CKAN is to use. It might just motivate them to buy it.

**Comment by plague006** [comment]
I definitely agree with @techman83. CKAN doesn't change a config setting to enable mods or anything of the sort, it simply downloads mods and installs them to the correct location. No more or less than a user can perform with ease.

**Comment by Almagnus1** [comment]
Actually from http://forum.kerbalspaceprogram.com/index.php?/topic/91479-ksp-demo-mods/&do=findComment&comment=1551982 :

The demo is designed to not support addons at all, the most you can do is a one-for-one replacement of an existing part, and there's no plugin support.
-sal_vager


The concern is someone with less than noble intent creating a "mod" that CKAN deploys on the demo that can cracks the demo into the full version, taking advantage of the automation that CKAN provides with mod installation and combining that with a script the user runs to bypass the CKAN restrictions on what a mod can/can't do.

We haven't seen this yet, but CKAN should not work with the demo, as that's going against the intent of the demo.

**Comment by TeddyDD** [comment]
> The concern is someone with less than noble intent creating a "mod" that CKAN deploys on the demo that can cracks the demo into the full version, taking advantage of the automation that CKAN provides with mod installation and combining that with a script the user runs to bypass the CKAN restrictions on what a mod can/can't do.

Nah. It's way easier to just download game from torrents. Also that kind of "mod" would be banned on forum.

**Comment by plague006** [comment]
> The concern is someone with less than noble intent creating a "mod" that CKAN deploys on the demo that can cracks the demo into the full version, taking advantage of the automation that CKAN provides with mod installation and combining that with a script the user runs to bypass the CKAN restrictions on what a mod can/can't do.

Someone writing a script to bypass CKAN restrictions? In your hypothetical why wouldn't the script also bypass the demo restrictions you want CKAN to impose? It's all very convoluted.

Ultimately, while CKAN does try to hold true to its name and be comprehensive, there have been and will be mods that are excluded from the index because they require processes that CKAN doesn't permit (like running external scripts or executables). While CKAN doesn't condone or support anyone contravening the EULA or ToS that Squad has imposed on the demo, I don't think we're comfortable taking a proactive approach and devoting time and resources to a problem that hasn't been shown to actually exist, and considering KSP's age will likely never exist.

**Comment by plague006** [comment]
Closing this as the consensus seems to be: we should do nothing unless the current situation changes.
