### ISSUE TITLE
Have our docs somewhere other than a github wiki

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#156]
The wiki is great for quick things, but it's extremely limited in scope.

- There are no hooks, triggers, or pull requests; so limiting our workflow.
- There's no table of contents documentation for each document (there would be, if github upgraded their version of gollum)
- We're limited in styling
- It's not at all obvious there are docs there.

Github will freely host a `ksp-ckan.github.io` domain for us, and is likely to give us a better landing page for users, and better processes for our docs.

**Comment by Dazpoet** [comment]
This is now up for discussion in https://github.com/KSP-CKAN/CKAN/issues/807 instead and as such I'll close this unused topic in favour of the new and more alive one.
