### ISSUE TITLE
Add ‘subsection’ options for `show` in CLI

### ISSUE THREAD

**Issue by meyerweb** [KSP-CKAN/CKAN#1560]
At present, `ckan show ModName` spits out everything CKAN knows about a mod.  Sometimes, all you want is one piece of that; say, if you’re writing a script that collects all the resources for all the mods currently installed.

So it would be handy to be able to say something like `ckan show resources ModName` and have CKAN return just the Resources section.  Or `ckan show installed ModName` to get just the files the mod installed.

**Comment by plague006** [comment]
I like the idea, but realistically it'll likely take a while to be implemented unless one of the coders takes it on as a pet project.

In the interim I can offer a suggestion: if you're writing a script to collect the resources of installed mods, parse the `registry.json` in the CKAN folder. Under `installed_modules` section you can extract the information you're looking for.

**Comment by meyerweb** [comment]
Oh, that’s a _great_ idea.  Thank you!
