### ISSUE TITLE
Can't find Kerbal Engineer Redux

### ISSUE THREAD

**Issue by ghost** [KSP-CKAN/CKAN#1562]
Hey. Trying to install KER, but cannot for the life of me find it in CKAN. It's in the latest.tar.gz archive, though. Any ideas?

**Comment by Almagnus1** [comment]
Check the incompatible section of CKAN.  It's still there, but it hasn't been updated for 1.0.5.

The only thing that's really broken with KER is that KER doesn't acknowledge the existence of the new jet engines, so don't expect those to work.

**Comment by MarkSkilbeck** [comment]
How does one do that?

**Comment by Almagnus1** [comment]
I did a manual install to get it working again, but that's probably going to cause issues down the line.

**Comment by politas** [comment]
When KER finally releases an updated version, you'll need to manually uninstall it so you can re-install with CKAN.

**Comment by Olympic1** [comment]
KER is ow on CKAN ([`09a1a3c`](https://github.com/KSP-CKAN/CKAN-meta/commit/09a1a3c7fa171eec087986e9bc11c55c6498bef3))
