### ISSUE TITLE
Toolbar and menu widgets squashed when running CKAN with libgdiplus-4.2 on Linux

### ISSUE THREAD

**Issue by LuciusMartius** [KSP-CKAN/CKAN#1565]
When I run CKAN with mono using libgdiplus-4.2 the toolbar and menu widgets are squashed and show only one or two characters shown of each string.

I verified this by downgrading libgdiplus to 3.12 (and giflib to 4.2.3 because libgdiplus-3.12 wont compile with giflibs-5.1.2) after which it worked perfectly. After upgrading everything again to the latest version the issue reoccurs.

Some additional information:
Distribution: Gentoo Linux
Mono version: 4.2.2.10

The next version of Ubuntu will already ship with libgdiplus-4.2 so this might be worth checking out.

![snapshot1](https://cloud.githubusercontent.com/assets/10165955/12532916/dcea9f70-c21f-11e5-94f4-6003749b6077.png)
-Screenshot of main window

![snapshot2](https://cloud.githubusercontent.com/assets/10165955/12532915/dce9c492-c21f-11e5-808c-6cdb8d497dc6.png)
-Screenshot of the filter menu

**Comment by CRHough** [comment]
This is exactly the problem I had (see #1044).

Try rebuilding libgdiplus-4.2 with the cairo use flag. It seems to fix things for me.

**Comment by politas** [comment]
This is a Mono issue, not a CKAN issue. Please raise it with mono-project.com
