### ISSUE TITLE
Gather Opt-In Statistics on Currently Installed Mods on CKAN Startup to Provide List of Most Popular Mods by Retention (not by Downloads)

### ISSUE THREAD

**Issue by inigmatus** [KSP-CKAN/CKAN#1566]
To provide the community with quality statistics on the most popular mods retained by the active CKAN player base, I recommend CKAN allow users to opt-in to share with CKAN the mods they have installed currently when CKAN runs through its normal mod check/update process on CKAN startup.

This will give CKAN a good indication of which mods have staying power since mods that exist in the user's installed mod base on CKAN startup are usually mods the player has chosen to remain installed at game shut down - indicating stable or balanced mods.

A number of advantages could be done with the data gathered:
1. Current mod popularly is determined by number of downloads, which as we all know, not all downloaded mods are kept in player installs. You could have a popularly downloaded mod that is just as popularly uninstalled.
2. CKAN could publish on a website or in conjunction with kerbalstuff, the most popular mods retained on player installs.
3. CKAN could publish on a website or in conjunction with kerbalstuff, the most popular sets of mods retained on player installs.
4. CKAN could provide CKAN users a list of "other players with this mod have also installed..." recommendation set.

Essentially my desire is to be able to pick a mod, and see what the most popularly retained mods other players have installed in conjunction with the mod I picked. That way if I install Kerbal Aircraft Expansion, for example, I can see a list of popularly retained mods that other players have installed in their game and are keeping after shutting down their games and opening CKAN again, at this very moment in time. Such a list would significantly decrease the risk of installing conflicting mods, or mods that are not stable, and make deciding which complimentary mods to initially install or explore, much easier.

**Comment by HebaruSan** [comment]
Replaced by #3242.
