### ISSUE TITLE
Stock Visual Enhancements

### ISSUE THREAD

**Issue by Nhawks1717** [KSP-CKAN/CKAN#1567]
Hiya. So currently my Stock Visual Enhancements mod is being put on CKAN through Kerbal Stuff(and I believe through Github as well) and for whatever reason the version on CKAN is the 1.0.0R version which is a very old version. I switched up my versioning system after the next release so I don't know if that messed up whatever does the automatic stuff when its on Kerbal Stuff. The latest release however is version 0.5.6 and that isn't showing on CKAN. Another issue that I can see happening is that my mod comes bundled with a development version of EVE and not the release version that is currently on CKAN. Is there anyway to tell CKAN to use the version that is in my download instead of the one that is on CKAN as the current SVE configs will not work with the release version.

**Comment by politas** [comment]
Switching up the versioning system as you describe will have locked CKAN into presenting the old 1.0.0R as the latest version, but that's easy to fix. The development EVE is a bit trickier. CKAN policy is to only offer users released versions of mods unless the user has selected a development repository.

**Comment by politas** [comment]
Version fix: KSP-CKAN/NetKAN#3038

**Comment by Olympic1** [comment]
Bumping up the epoch won't fix this as all the releases that were released after 1.0.0R are pre-releases and we chose not to pick up those as some pre-releases are not stable. However, we can add them manually to CKAN or @Nhawks1717 has to release a stable release.

**Comment by Nhawks1717** [comment]
Hmmm... okay... that's troublesome. Well if I'm reading this correctly, once I put out another release version CKAN will update that? That's perfectly fine with me, hopefully rbray will get a new EVE release version out by the time I have it ready. Thanks for the help guys!

**Comment by Olympic1** [comment]
CKAN will update it if its not a pre-release

**Comment by Nhawks1717** [comment]
Sweet! Thanks for the info!
