### ISSUE TITLE
Need to handle download problems better where CKAN crashes by Timeout / Unhandled Exception 

### ISSUE THREAD

**Issue by nobodyhasthis** [KSP-CKAN/CKAN#1572]
When installing a mod with a lot of dependencies/recommends there is a timeout error that will cause a crash. Plus the all selected mods will be forgotten. Mods have downloaded will be present in the CKAN folder but nothing will install. If working from .CKAN it must be used again. If not then all selections are lost.

Suggest catching the error and asking user to try again, skip, abort or save selections. Or some other suitable and user friendly feedback.  

At present the following error and lost of information can be disconcerting. Can we have have something more graceful in reporting of download / installation problems ? 

************** Exception Text **************
System.TimeoutException: Transaction Timeout

**Comment by politas** [comment]
I'm frankly staggered this hasn't already been raised.

**Comment by nobodyhasthis** [comment]
This requires a empty mods folder and the initial selection of one of the bigger mods. Like SETI or Realism Overhaul. Which have a large list of associated mods. It seems to trigger after theses mods are downloaded. 

In a case where a mod simply fails to download (due to server / connection issue) the error code would be ------The remote server returned an error: (504) Gateway Timeout. Which is understandable. However this timeout appears after download. 

As a suggestion just prior to initiating such a large install. A temporary mod selection list is exported. If the process fails then this list could be used the existing import functionality and start again. This gives the solution to remember user selection, whilst providing a possible route to recovery.

Also in the event a persistence Timeout. The importing of the temporary fall back file could help the user overcome it whether caused by Gateway Timeout or System.TimeoutException: Transaction Timeout

**Comment by nobodyhasthis** [comment]
I do not know if the following helps of hinders further diagnosis. This based observation of steps need to reproduce error and included here in the hop that it helps someone.  

I suspect this is an error in the check of source version number prior to loading a pre-cache mod. CKAN would always have to check it has the it has the latest version from the source, to ensure integrity. However this is unnecessary if mods have just be downloaded. If a lot of mods are downloaded this check prior to actual install may be the problem here.

**Comment by nobodyhasthis** [comment]
Here is another crash when faced with a common download issue. This one was actually caused by trying to download from Kerbal Stuff. Instead of reporting a connection error there is a crash. A better option would ask to skip the affected mod, try again or abort the current operation.  

CKAN DownloadErrorsKraken on 404 error. 

************** Exception Text **************
Uh oh, the following things went wrong when downloading...

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///F:/Kerbal%20Filesw/used/ckan.exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1068.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.96.0 built by: NETFXREL2STAGE
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.81.0 built by: NETFXREL2
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------

**Comment by Olympic1** [comment]
@nobodyhasthis We are aware of the KerbalStuff errors. It isn't possible to download any KS mod because KS stopped.

**Comment by Dazpoet** [comment]
I opened a suggestion on a possible fix here #1395

**Comment by nobodyhasthis** [comment]
@Dazpoet thank you for heads up. That is a great description of the problem and how to catch the selections the user has made. Awesome thinking. If we follow #1395 it will provide it a method to restore things.

1) select mods
2) run selections based on TMP/virtual packages
3) create a metapackage over all the mods in the current list we want to install
4) run installation
5) end transactions
6) remove the metapackage created in 3)

The one question that remains is all of the above errors not closely related enough to be handled by a single procedure that prevents a crash?

If we could work in fail safe that says "sorry things got messed up do you want to try again?" for all of the above. Then use the back up to automatically restart from step 1.

An additional fail safe would be "Sorry mod X is giving me problems. Can I skip that?". On a yes from the user drop mod X from the back up selection and restart step 1. 

With two important things to consider. Did mod X have a dependency? If so we need to flag that up. The second important thing is we must be all error free before committing to step 4. The run installation 

Sorry if the above is clear as mud. Best I can do pre coffee. I just hope it helps more that hinders.

**Comment by politas** [comment]
Is there any way for the progress string to indicate which particular file is being downloaded?

**Comment by nobodyhasthis** [comment]
Issue title change as I have not seen a  _System.TimeoutException: Transaction Timeout _error for a while. However leaving issue open for review as I have recently seen another type of crash related to download problems. Unhandled Exception:CKAN.FileNotFoundKraken:  

The root cause is again is nothing to do with CKAN. It was caused by Space Dock forgetting to turn on SSL support after doing an update. However there should be a better response instead of an Unhandled Exception crash. Possibly a better way to deal with this is to stop the download attempt and go through the steps above. Also see #1395 to preserve user choices during these crashes.

**Comment by nobodyhasthis** [comment]
I have not personally seen a recent recurrence of the reported problem. Just a regular 404 error dialog which works fine. As expected and covered in user guide. Initial collection of unhandled exceptions listed in this issue dates back to fall of Kerbal Stuff and the start up of Space Dock. With nothing significant since then. So closing my own issue to clean up the backlog if no one objects. I think this is fixed for now.
