### ISSUE TITLE
Error on Startup Makes CKAN Unusable

### ISSUE THREAD

**Issue by Sahadara** [KSP-CKAN/CKAN#1575]
Upon launching CKAN, I am given the error shown in this [image.](http://imgur.com/rI4DqUP)
The log given beneath is [here.](http://pastebin.com/QxvEfSPz)

This started happening out of nowhere a few days ago after I removed some mods. If I click continue it opens up the CKAN window but shows none of the mods. It's unusable. No amount of reinstalling fixes it and I have no idea what to do to resolve this. Help is much appreciated.

**Comment by plague006** [comment]
Can you upload your registry.json somewhere (you can locate this file in the CKAN folder inside your ksp install folder)? It seems something got corrupted inside it and if I have a poke around I can probably repair it.

**Comment by Sahadara** [comment]
That made me realize I was stupid enough to not delete the CKAN folder and try reinstalling after that (smh). Doing that fixed the issue. Thank you for making me realize the issue.

**Comment by plague006** [comment]
:+1:
