### ISSUE TITLE
Installing previously uninstalled mod USI-UKS-Shared attempts to overwrite

### ISSUE THREAD

**Issue by JustaSimpleUser** [KSP-CKAN/CKAN#1576]
I thought I had an earlier version of all of the USI mods properly installed and I'm attempting to update via CKAN (despite RoverDude's direction to avoid CKAN and install manually).  CKAN's Changeset looks like:
![changeset](https://cloud.githubusercontent.com/assets/13194658/12954145/3b150d50-cfd2-11e5-8928-9e4ddf35d72a.JPG)

When I apply the changes I get:

> Installing previously uninstalled mod USI-UKS-Shared
> 
> Oh no! We tried to overwrite a file owned by another mod!
> Please try a `ckan update` and try again.
> 
> If this problem re-occurs, then it maybe a packaging bug.
> Please report it at: https://github.com/KSP-CKAN/CKAN-meta/issues/new
> 
> Please including the following information in your report:
> 
> File           : GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt
> Installing Mod : USI-UKS-Shared 0.1.7.0
> Owning Mod     : USI-Kolonization
> CKAN Version   : v1.16.0-0-g7206ce5 (beta)
> 
> Your GameData has been returned to its original state.
> 
> 
> Error!

I'm not entirely sure what a "ckan update" is but I have checked for a new CKAN version and refreshed the cache.

Reporting as instructed :-)

**Comment by Olympic1** [comment]
Check if you have any `USI Kolonization` smaller then 0.1.7.0 and uninstall it, I renamed any version prior to 0.1.7.0 because it was causing this issue.

Try that and comment back if it worked or not.

**Comment by politas** [comment]
Check your GameData folder for the specified file. If you find it, delete it, then try installing again. But seriously, it is probably worth heeding the advice from RoverDude to install manually. The current metadata is apparently not correct.

**Comment by JustaSimpleUser** [comment]
Thanks for the advice.  I took the easiest road...I manually re-installed all of RoverDude's mods.  Although everything appears to be working correctly, my new suspicion is that I should have uninstalled via CKAN first.
