### ISSUE TITLE
Can't install USI Kolonization due to conflicting file registration?

### ISSUE THREAD

**Issue by Koverpih** [KSP-CKAN/CKAN#1585]
> About to install...
> 
>  * USI Kolonization Systems (MKS/OKS) 1:0.33.7.0
>  * USI Kolonization Core 0.1.8.0
> 
> Downloading "https://github.com/BobPalmer/MKS/releases/download/0.33.7.0/UKS_0.33.7.0.zip"
> Downloading "https://github.com/BobPalmer/Kolonization/releases/download/0.1.8.0/Kolonization_0.1.8.0.zip"
> Module "USI Kolonization Systems (MKS/OKS)" successfully installed
> The following inconsistencies were found:
> USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/CHANGELOG.txt, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/EL_Parts.cfg, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/EL_USI.cfg, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Kolonization.version, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Kolony.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/KolonyTools.dll, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/OrbitalLogistics.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/PlanLog.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Settings.cfg, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/StationManager.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Flags/USI1.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Flags/USI2.png, but this file is registered to USI-Kolonization
>  * USI-UKS-Shared wishes to install GameData/UmbraSpaceIndustries/Kolonization/Flags/USI3.png, but this file is registered to USI-Kolonization
> 
> 
> 
> Error!
> 

Appears after USI Kolonization Core is on CKAN. Installed them manually now. I assume this must be a CKAN-side problem?

**Comment by Olympic1** [comment]
We had some problems with USI Kolonization. You can solve the conflict by uninstalling and re-installing USI Kolonization.

**Comment by Koverpih** [comment]
THAT'S WHY! I forgot to uninstall USI Kolonization! I thought they refer to UKS... 
@Olympic1 Thanks.
