### ISSUE TITLE
CKAN on NuGet?

### ISSUE THREAD

**Issue by jkoritzinsky** [KSP-CKAN/CKAN#1588]
Hey guys!  I'm working on making a Visual Studio addin for KSP modding support (you can see the progress at [the repo](/jkoritzinsky/Kerbal-Space-Program-for-Visual-Studio)).  I want to eventually add in CKAN integration above just CKAN/NetKAN files.  My goal is to make it act like a package manager in VS for mod development (which would then be able to generate a CKAN file with all of the dependencies specified).

I could just include the CKAN dll in my repo, but I would have to manually update it whenever I happen to see a CKAN update.  If it were on NuGet, it would make support a little easier (especially for integrating CKAN into the build process, not just editor support).

I'd be willing to help out with getting this going if needed.

**Comment by dbent** [comment]
It's possible, but I'd like to cleanup and reorganize our build process (first steps in #1589) over the next few weeks first, it would make things a lot easier.

**Comment by jkoritzinsky** [comment]
Awesome! Let me know if there's anything I can do to help!

**Comment by HebaruSan** [comment]
We started creating an org on Nuget, but it's not fully set up yet. I think a confirmation email was sent to `nuget@ksp-ckan.space` and not responded to. This was for [KSPMMCfgParser](https://github.com/KSP-CKAN/KSPMMCfgParser), which I think is still listed as my personal package until the org is finalized.

- https://www.nuget.org/packages/KSPMMCfgParser
- https://www.nuget.org/organization/KSP-CKAN
