### ISSUE TITLE
"Error 404 Download failed" This is happening for 90% of the mods I try to download KSP V.1.0.5

### ISSUE THREAD

**Issue by waffleoblue** [KSP-CKAN/CKAN#1590]
So i have downloaded and installed CKAN. followed all the instructions for picking KSP directory. Tried even putting CKAN into the KSP directory. Any mod i try to download It throws a 404 error. I even tried mods I already have and I know that work. Still nothing I have been scouring the forums and cant find anything that will help describe or solve the issue. PLEASE HELP!!!

**Comment by ILM126** [comment]
I would just presume that the mods you are trying to download are from Kerbal Stuff, which has shut down yesterday.
But you can access the mods from the site [here](https://i.52k.de/kspmods/storage/) in this temporary location.

**Comment by waffleoblue** [comment]
Oh wonderful, just my luck. Is there a way to get CKAN to pull from other websites like for example Curse?

**Comment by ILM126** [comment]
Well, yes. But that will have to be done via CKAN's meta repo. If you want more info, join the irc chat and find out more.
[https://kiwiirc.com/client/irc.esper.net](https://kiwiirc.com/client/irc.esper.net) You'll have to join #ckan to chat.

**Comment by nobodyhasthis** [comment]
@waffleoblue you probably already know the story this week. However I pass on some news in case you are still left in the dark. Thanks to hard work of some amazing people there is a replacement for Kerbal Stuff up. [http://spacedock.info/](url). So things are improving. There still a lot of mod authors that need to react to the loss of Kerbal Stuff but good news is there is a replacement if need to rehost their mods. You still see errors this week but hopefully less of them.

**Comment by websterhamster** [comment]
So, it looks like CKAN is more or less non-functional for downloading mods until the database is fixed to point to other download locations.

**Comment by pjf** [comment]
Ta da!!!!!

https://github.com/KSP-CKAN/CKAN-meta/pull/969

**Comment by waffleoblue** [comment]
Gotcha thanks for the info I'll give that alternate site a look.

**Comment by Olympic1** [comment]
Fixed in KSP-CKAN/CKAN-meta/pull/969, I will leave this issue open for a week, should there occur problems.

**Comment by pjf** [comment]
Even with that change, non-free mods that were previously hosted on KS are still in limbo. But that means that perhaps 10% of mods will be breaking now, rather than most. :)

**Comment by nobodyhasthis** [comment]
The following does not solve the issue but it does help users find
temporary workarounds for the 10% of mods with more restrictive
licenses. Or at least to understand that CKAN is waiting for mod authors to
find a new host and amend metadata. Could we do a temporary fix to catch
the 404 error and handle it a bit better. To just say the mod is currently
unavailable?

By directing the user to seek help with the forum link there a chance that
these mods have mirrors already. A number of mods are available on mirror
sites but the authors have not volunteered to amend metadata or even passed
on the information directly the CKAN team. Not for any malicious reasons I
hope. It is just stuff in real live getting the way.

I know that does not fix the problem. However that forum link in the
metadata is very handy and has allowed me to carry on regardless. To
quickly find a mirror site for manual download. I just wish the 404 error
messages was not so abrupt and unhelpful.

**Comment by plague006** [comment]
If you have alternate download locations for mods, please share. Running down individual mods for mirrors is a time consuming process and by sharing you can reduce that workload significantly.

**Comment by websterhamster** [comment]
Is there an official/central place we can recommend alternate download URLs?

**Comment by plague006** [comment]
Officially, https://github.com/KSP-CKAN/CKAN-meta if it's related to .ckans and https://github.com/KSP-CKAN/NetKAN if it's related to netkans. If you're not sure what the difference is, either is fine: we see issues on all the repos.

**Comment by nobodyhasthis** [comment]
@plague006 have raised an issue to Netkan to change a kerbal stuff mod download link to a mirror download github official release. If the feedback says it helps with the workload. I can start hunting down the rest.

**Comment by plague006** [comment]
:+1: 'twas helpful indeed. Any further contributions you're willing to make would be greatly appreciated.

**Comment by nobodyhasthis** [comment]
Couple of other notes on current my 404 hit list.

2 fixed already because @Olympic1 is awesome.  I have seen further by standing on the shoulders of giants. I am just checking the small print on another mod which might help another one get reported in the next hour. Then I will pass on the information to an adult =D

- Dr Jets chop shop is hosted on curse but always used be mirrored to Kerbal Stuff. Have asked author if this mirror will move to Spacedock as it easier to deal with. If not then somebody is going to have to point to the main curse download. Which is a bit of a pain to maintain pending the API shenanigans. 

- Universal Storage is in limbo but there is the authors personal One Drive link on the mod forum to help users that are really stuck. Lets not kick his bandwidth to death please. Have asked author to host on the space dock as better solution and still waiting to hear back. Due to real life considerations he might just be unaware of the recent Spacedock news.

**Comment by nobodyhasthis** [comment]
Latest 404 errors on my watch list. Not worth an issue report pending author actions. However writing them down here so we know to come back and check up later.

- Field Experience  - Author is aware and will host soon. Temporary site for users that a really stuck on forum. May see this up over weekend.
 
 - Mkerb Science Instruments - Currently no alternative host found. Several people have posted this to forum. Nothing we can do right now.  

- Universal Storage - Not available with exception of one drive link. All rights reserved license. All we can do is leave a message.

- Dr Jets chop shop still waiting to see if there is another alternative Spacedock upload. Currently only available on curse.

**Comment by politas** [comment]
Just moved Field Experience to the Author hosted DLs in KSP-CKAN/CKAN-meta#994
