### ISSUE TITLE
Kerbal Stuff

### ISSUE THREAD

**Issue by Ricochetv1** [KSP-CKAN/CKAN#1595]
Ummm.... you been to Kerbalstuff lately? It's gone. He left a torrent link behind for all the mods on there, but it needs 62GB... We should probably find a way someone else can host those files and redirect ckan to that store for now...

**Comment by plague006** [comment]
Being addressed in https://github.com/KSP-CKAN/CKAN/issues/1586.

**Comment by Shuudoushi** [comment]
Do people even look in IRC before posting this stuff?

**Comment by Ricochetv1** [comment]
People still use IRC?

**Comment by politas** [comment]
Yeah, expecting people to check IRC (when they quite possibly have never heard of it) is a bit unreasonable. Checking existing issues, on the other hand, is a perfectly reasonable expectation.
