### ISSUE TITLE
Scraping from SpaceDock should give us all authors

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#1600]
I've opened https://github.com/KSP-SpaceDock/SpaceDock/issues/76 to make the circle complete. See the original issue at #1048 

And yes I'm doing it this way rather than editing the old one, because I can :p

**Comment by Dazpoet** [comment]
So this has now been fixed on SpaceDocks end in https://github.com/KSP-SpaceDock/SpaceDock/pull/78 so I'm guessing that somewhere, somehow, a mod with multiple authors will now break in the future, unless ofcourse NetKAN will just handle this without issue? @dbent ?

**Comment by dbent** [comment]
It won't break, it's just an additional field in the metadata that NetKAN will ignore until it's told not to.

**Comment by Dazpoet** [comment]
Nice so this should/could be closed then or should I keep it around as a reminder to sometime in the future add this to NetKAN?

**Comment by dbent** [comment]
Keep it around, I'll add it whenever the change is live on SpaceDock.

An example mod for my own reference: http://spacedock.info/api/mod/60
