### ISSUE TITLE
ckan stuck at downloading on ubuntu 15.10

### ISSUE THREAD

**Issue by akosmaroy** [KSP-CKAN/CKAN#1603]
Hi,

I just installed CKAN on my ubuntu 15.10 box. I followed this wiki page for the installation steps: https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu-14.04

I installed the latest version of CKAN, it reports as 1.16.0

after I select a plugin in the GUI, I try to install it, but it's stuck when trying to download:

```
About to install...

 * Distant Object Enhancement v1.6.4
 * Distant Object Enhancement default config v1.6.4

Downloading "https://kerbalstuff.com/mod/403/Distant Object Enhancement bis/download/v1.6.4" (libcurl)
```

and it remains permanently at 0%.

is this a possible SSL cert issue? but I did run "mozroots --import --ask-remove" as described in the documentation...

what am I doing wrong?

Akos

**Comment by ChucklesTheBeard** [comment]
That mod downloads from kerbalstuff, which shut down last week. I'm sure someone will switch the metadata around so it points at the github instead, shortly.

**Comment by plague006** [comment]
Closing as https://github.com/KSP-CKAN/NetKAN/pull/3234 is merged.
