### ISSUE TITLE
Long opening time on Ubuntu 15.10

### ISSUE THREAD

**Issue by qm3ster** [KSP-CKAN/CKAN#1616]
**CKAN Version:**
Ringshine
v1.16.0-0-g7206ce5 (beta)
**Operating System:** 
Ubuntu 15.10, Mono 3.2.8 (Debian 3.2.8+dfsg-4ubuntu4)

**The issue you are experiencing:** 
console spammed with `exception inside UnhandledException handler: Cannot call Invoke or BeginInvoke on a control until the window handle is created` until window opens (which takes a long time, some seconds, for some reason)
The issue is not fatal, but it's combined with an inordinately long time until the window opens.
Perhaps there are other logs I could obtain to see why it takes so long?

**How to recreate this issue:**
Do a clean install as per [Ubuntu **14.04**(!) instructions](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu-14.04)

**Comment by birdspider** [comment]
first of all you have `Ubuntu 15.10` so the 14.04 instruction do not necessary apply,

Further the CKAN wiki states:

> If you are on an OS X or Linux system first of all make sure that you have the latest version of Mono which is available [here](http://www.mono-project.com/download/)

whareas your `Mono 3.2.8` is definitly _not_ the latest (The latest Mono release is: 4.2 SR1 (4.2.2.30))

**Comment by ChucklesTheBeard** [comment]
>Go to the Mono project and add their repository, as per the instructions on http://www.mono-project.com/docs/getting-started/install/linux/ for more recent versions.

**Comment by Olympic1** [comment]
OS X and Linux systems require at least Mono 4.0 and higher
Windows systems require .NET4.5 and higher

**Comment by qm3ster** [comment]
Derp-derp. Thanks. No more error message, but it doesn't seem any faster.
Surprising how everything actually worked on the old version then.

**Comment by qm3ster** [comment]
Deep in the shadows, the error continues to be spammed, when closing CKAN window using the window decorator button :v:

**Comment by ayan4m1** [comment]
Mono 3.2.8 is just about two years old - any chance you could retest with Mono 4.x?

**Comment by qm3ster** [comment]
@ayan4m1 I did install according to instructions and got a much newer Mono, hence the comment when I closed the issue. (The version was over 4)
I am not actively using CKAN nowadays but I will report if on speed and console error later today.

**Comment by qm3ster** [comment]
Yup, neither issue present with current versions of both.
