### ISSUE TITLE
KSP Serial IO not updated

### ISSUE THREAD

**Issue by alextorre98** [KSP-CKAN/CKAN#1617]
The mod KSP Serial IO is not indexed in it's lastest version, which is compatible with ksp 1.0.5. The version in CKAN is for 1.0.4

**Comment by ChucklesTheBeard** [comment]
That is correct! KerbalStuff, the file host used by many mods, shut down. Updates to things that were hosted there will require manual intervention.

@zitron-git can either upload it to spacedock and hit the "add to CKAN" button there, or follow [our guide on adding mods to CKAN](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) to update it.

**Comment by plague006** [comment]
Looking at http://forum.kerbalspaceprogram.com/index.php?/topic/60281-hardware-plugin-arduino-based-physical-display-serial-port-io-tutorial-06-jun/&page=1 the latest version seems to be 17.3, which is the most recent version CKAN has indexed. Are you saying this version is 1.0.5 compatible, or is there a more recent release indicated somewhere else?

**Comment by alextorre98** [comment]
I downloaded the lastest version and it's working with ksp 1.0.5 on windows 10

Matthew <notifications@github.com>wrote:

Looking at http://forum.kerbalspaceprogram.com/index.php?/topic/60281-hardware-plugin-arduino-based-physical-display-serial-port-io-tutorial-06-jun/&page=1 the latest version seems to be 17.3, which is the most recent version CKAN has indexed. Are you saying this version is 1.0.5 compatible, or is there a more recent release indicated somewhere else?

---

**Comment by plague006** [comment]
> I downloaded the lastest version

Great. What is the latest version?

**Comment by alextorre98** [comment]
The one you said, 17.3.
The file name is KSPSerialIO_017_3.zip

Matthew <notifications@github.com>wrote:

> I downloaded the lastest version

Great. What is the latest version?

---

**Comment by zitron-git** [comment]
Hey there, what do modders like me need to do to keep things up to date on CKAN since the whole kerbal stuff drama?

**Comment by Olympic1** [comment]
@zitron-git You can reupload your mod/plugin on [SpaceDock](http://spacedock.info/) or GitHub so we can make a `.netkan` file that can automatically update your mod on CKAN when you release a new update.

**Comment by zitron-git** [comment]
Alright thanks. SpaceDock seems the easiest. Didn't think a replacement would be up so soon!
