### ISSUE TITLE
New Download Sites Needed

### ISSUE THREAD

**Issue by WDayneHS** [KSP-CKAN/CKAN#1619]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** Latest

**Operating System:** Windows 10

**The issue you are experiencing:** Cannot download mods from Kerbalstuff.com

**How to recreate this issue:** Select a mod from kerbalstuff.com and apply changes

**CKAN error codes (if applicable):**

**Comment by plague006** [comment]
Closing in favour of https://github.com/KSP-CKAN/CKAN/issues/1586

KerbalStuff has been closed, we know. We're working on finding alternate download sources for mods. If you have a particular mod that interests you and you have an alternate link to it, please let us know and we'll get it working as quickly as we can.
