### ISSUE TITLE
Is $kref asset_match branch specific?

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-CKAN/CKAN#1626]
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ckangithubuserrepoasset_matchfilter_regexp

I currently use this in my plugin:
"$kref" : "#/ckan/github/KSP-RO/TestFlight/asset_match/TestFlightCore*"

I want to release **test** builds on a different branch from master, and **don't** want those showing up in CKAN for normal users.

Does the asset_match system search all branches or only master? If it searches all branches is there any way to control it?

**Comment by dbent** [comment]
GitHub releases are tied to a tag not a branch. If you don't want CKAN to pick up the release you can just flag it as a pre-release, which would seem to make sense here, as it also signal to anyone downloading manually that those are non-stable builds.

**Comment by jwvanderbeck** [comment]
Yeah flagging it is as pre-release is what I am currently doing and does make semantic sense.  The problem is like CKAN, if a release is tagged as "pre-release" then Travis will also not build a release, which is a bit of a pain.  It means I need to manually build and upload the release which is not preferred.

I'd much rather have it as a normal release tagged and titles as a beta, and have it handled by Travis, but ignored by CKAN.

**Comment by dbent** [comment]
Then your best bet is to give your test/stable releases distinguishing filenames and use the `asset_match` regex to only match on the stable filenames. Caveats:

- NetKAN only considers the most recent non-prerelease release. If you do a "stable" release followed by a "test" release within the bot's poll period then it won't pick up the "stable" release.
- NetKAN will spit out a warning and error for the releases that don't have the matching asset.

But I'm confused why your Travis setup cares about releases, usually a release is the end product of a CI build not the trigger for one.

**Comment by jwvanderbeck** [comment]
Travis does CI but also can do the build and attach the artifacts to a tagged release.  Which means I don't have to do it manually and upload the resulting files, i just create the release and Travis does it for me.
