### ISSUE TITLE
"Apply Changes" disabled

### ISSUE THREAD

**Issue by joflashstudios** [KSP-CKAN/CKAN#1630]
**CKAN Version:** 
1.16.1-0-g2e91715 (beta)

**Operating System:** 
Windows 7

**The issue you are experiencing:** 
After installing the latest update, I'm getting some strange behavior.

Adding and removing mods does not cause the change list to appear, nor the "Apply Changes" button to enable.

![image](https://cloud.githubusercontent.com/assets/7459309/13736550/69e0cb7c-e983-11e5-9aa1-fe70cd6f536d.png)

**How to recreate this issue:** 
Unfortunately, I don't know what has caused the issue. It arose suddenly with an existing install.

**CKAN error codes (if applicable):** 
No exceptions.

**Comment by politas** [comment]
Have you tried different combinations of mods? There is the possibility that a metadata change has generated an incompatibility or dependency lack in your installed mods. if you can post your full modlist, I'll look through them.

**Comment by joflashstudios** [comment]
I think you're right, @politas. It's fixed now.

It might be helpful if such issues had some sort of notification, instead of just mysteriously not working.
