### ISSUE TITLE
Add Filter by description to GUI

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1631]
Steven Mading on the forums [spake thusly](http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1161-13-mar-2016/&do=findComment&comment=2456148):

> CKAN is great if you already know about the available mods and what they do, but it's not so great for browsing mods because you can only really search based on the mod's name.

> Are there any plans to improve the ability to *find* a mod you like, either by adding 'tags' fields that authors can populate, or by just making a sort of 'dumb grep' on the mods' description fields?  I would actually prefer a dumb grep, with the expectation that authors can add a keyword list to the end of their description to help searching, than searching ONLY on keywords the author picked and not on their description text.

This seems like a reasonable suggestion to me, and most of the required code is presumably basically already there, it just needs to be adapted to a different field.

**Comment by Dunbaratu** [comment]
Hey, thanks.  This will be useful.  I'll try to remember once it exists to make sure to edit the kOS description in CKAN accordingly.
