### ISSUE TITLE
CKAN incorrectly marking KSP version

### ISSUE THREAD

**Issue by Marsfan** [KSP-CKAN/CKAN#1633]
Hi,

So I was going though CKAN, downloading some new mods, and I found out that there was a mod I could not install due to it being for a newer version of KSP. This surprised me because I have the newest version (1.0.5).
It seems CKAN has marked me as having 1.0.4 and I cannot change it, any suggestions.

**Comment by politas** [comment]
CKAN (currently) looks at the settings.cfg file in your base ksp directory to know what version of KSP you have. The start of that file for KSP 1.0.5 should be:

    // KSP Game Settings
    
    SETTINGS_FILE_VERSION = 1.0.5

**Comment by Marsfan** [comment]
@politas Good to know. Thing is, I don't think that value gets update when you update the KSP version. Maybe a better bet would be to check the readme file, as that has a pretty comprehensive changlog.

**Comment by politas** [comment]
Ah, maybe that's where we get it from. A Squad employee has requested we use the BuilID.txt file, instead, but that change hasn't been implemented, yet.

**Comment by nobodyhasthis** [comment]
@Marsfan Just to clarify things now and in the future in regard to version control. CKAN will currently detect your KSP version using the readme.txt file. If you want to force an install a mod built for another version of KSP simple change the readme.txt. At your own risk of course.

However @politas is also correct to say CKAN should eventually start checking BuildID.txt. The release of a different build for 1.0.5 has complicated things. The so called silent patch. This covered in #1545 and is something to be aware of when forcing earlier mods. 

In the future a better answer will come from the removal strict version controls. Through fuzzy version choices covered under #1173. For now the best answer is to use the readme.txt version number to determine what can be installed. The answer will eventually change.
