### ISSUE TITLE
Kerbalstuff

### ISSUE THREAD

**Issue by Marsfan** [KSP-CKAN/CKAN#1634]
So kerbalstuff has shut down :cry:.

Unfortuantly, this means that quite a few mods on CKAN are now not able to download. I am pretty sure you guys are aware of this, but I though I should bring it up.
Hopefully this can get fixed. But I know editing tons of data files is a pain in the ass.

**Comment by politas** [comment]
A majority of mods have been redirected to new homes or (where we are allowed to do so by licenses) to mirrored copies. If you are aware of available sources for particular mods, please report them so we can change the metadata. Unfortunately, many pre-1.0.5 mods with restricted licenses are probably lost forever. Few mod authors are interested in supporting obsolete versions.

In short, yes, we are aware; what we can do, we are doing; and we appreciate any assistance anyone can provide.

**Comment by Marsfan** [comment]
@politas so the one I was trying to get was the buffalo rover. It's pretty new

**Comment by politas** [comment]
The NASA inspired MSEV? I was just looking at KSP-CKAN/NetKAN#3409 and fixing that one.
