### ISSUE TITLE
Using download button on contents tab causes System.Net.WebException on 404 error

### ISSUE THREAD

**Issue by solarsootysmudge** [KSP-CKAN/CKAN#1636]
**CKAN Version:** 
 v1.16.1
**Operating System:** 
Windows 8.1
**The issue you are experiencing:** 
When downloads fail after pressing button in contents tab. There is a bug in the 404 error handling leading to a crash. System.Net.WebException: The remote server returned an error: (404) Not Found. There is nothing we can do if host breaks down but an external remote server error should not be crashing CKAN.
**How to recreate this issue:** 
Select a mod with a known broken download link that produces the standard 404 dialogue box. Like one we know is still hosed on Kerbal Stuff for example. In the mod description section we have three tabs. Metadata, Relationships and Contents.

On the contents tab there is a download button to for mods not cached. When this is pressed the download naturally fails to happen. We get the standard 404 error message and dismiss button which is ok. On closing this we then get a crash  

**CKAN error codes (if applicable):** 
*************\* Exception Text **************
Uh oh, the following things went wrong when downloading...

System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

**Comment by plague006** [comment]
Had a quick look, didn't know we had that tab or button. Another issue (which I'll need to open a ticket about) is that when you download a mod via that button it doesn't grey out, you can download it over and over again. Tested on multiple mods.

**Comment by nobodyhasthis** [comment]
@plague006 Try downloading Mkerb Inc. Science Instruments to recreate the crash. It has not moved from Kerbal Stuff yet so produce a reliable test.

Sorry just testing the new version as an end user again. To be honest I have no idea why that button exists. As the window below it greys out and the scroll bars don't work after it is pushed. I may have stumbled on to a bigger problem with the GUI here.

**Comment by politas** [comment]
Actually, the button not greying out might be a good thing. It's an answer for what to do if you have a corrupted/incomplete download in your cache..

**Comment by plague006** [comment]
> Actually, the button not greying out might be a good thing. It's an answer for what to do if you have a corrupted/incomplete download in your cache..

Not really, it's greyed out once you close and re-open CKAN.

**Comment by politas** [comment]
Maybe we should add a "remove from cache" button, then?
