### ISSUE TITLE
Netkan should use the same filenames for caching mods as CKAN

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1637]
CKAN/NetKAN v1.16.1-0-g2e91715

Ubuntu

When using the --cachedir <filepath> switch on netkan, downloaded mod files are stored in `<filepath>`. If that `<filepath>` is the same location as the CKAN/downloads directory in a KSP install, it would be expected that CKAN would use that cached download, rather than downloading a fresh copy, if the source file is the same. Unfortunately, netkan adds the string "netkan-" to the filename and leaves off the version number, so CKAN doesn't recognise the cached file, eg

```
89BC12EC-netkan-NKRs_DEM.zip
```

versus

```
89BC12EC-NKRs_DEM-0.1.zip
```

Presumably, this is because netkan is downloading whatever file it is pointed at, without yet knowing what the version number is.

There should be an option flag to make Netkan change the cached file's name to what CKAN would expect once it has written out the .ckan file. This would speed up testing metadata changes, particularly for large mods.

**Comment by dbent** [comment]
CKAN *should* recognize the cached file, only the first 8 characters are significant for caching purposes, everything after that is basically a comment to make it easier for humans. Specifically the code is in [`CKAN.NetFileCache.GetCachedFilename(Uri)`](https://github.com/KSP-CKAN/CKAN/blob/master/Core/Net/NetFileCache.cs#L138). Notice it only cares that the filename *starts with* the hash, it doesn't even take a mod name or version.

Are you sure that's not working correctly?

**Comment by politas** [comment]
Yep. I shouldn't even have those two example filenames. It's pretty consistent. But here's another. I just ran netkan over AsphaltTiles.netkan, then asked CKAN to install Asphalt Tiles. Here's my shared downloads folder:

    $ ls -l downloads/
    -rw------- 1 x:x 332813 Apr  1 03:53 21CFF5D8-AsphaltTiles-1.1.zip
    -rw-r--r-- 1 x:x 332813 Apr  1 03:50 21CFF5D8-netkan-AsphaltTiles.zip

**Comment by politas** [comment]
Ok, maybe it's the watcher that's failing? I've added an extra debug output in the loop that looks for files, have CKAN running and run Netkan. Netkan gives me this: http://pastebin.com/ag2vb8h0
I would expect if CKAN is watching that directory to find the same file, It should include it in the mods it searches when selecting the same mod (or any other mod for that matter), yet I get this in its output: http://pastebin.com/9pbyWdhB

**Comment by politas** [comment]
Yep looks like FileSystemWatcher is not cross-platform.
https://social.msdn.microsoft.com/Forums/vstudio/en-US/6498433b-d350-4b29-b965-e6b177375c01/using-filesystemwatcher-in-linux?forum=csharpgeneral

**Comment by dbent** [comment]
Well in that case I'd just ditch the watcher as premature optimization; enumerating the list of files in the directory each time it's needed shouldn't take that long. As someone that uses CKAN exclusively from the CLI it wouldn't even do anything for me and I've never found CKAN particularly slow.

**Comment by HebaruSan** [comment]
> CKAN doesn't recognise the cached file

This is not correct. CKAN and NetKAN do recognize each other's cache entries as long as they start with the same 8 hash characters (which they do).

> This would speed up testing metadata changes, particularly for large mods.

We have been in that world for a long time now; a NetKAN pull request downloads the mod when it runs netkan.exe, and when installing via ckan.exe, the mod list shows "(cached)" for that mod.
