### ISSUE TITLE
CKAN does not correctly detect KSP 1.1 pre-release

### ISSUE THREAD

**Issue by RNeilsen** [KSP-CKAN/CKAN#1644]
**CKAN Version:** 
Plasma Window v1.16.1-0-g2e91715 (beta)

**Operating System:** 
Windows 10

**The issue you are experiencing:** 
I'm not sure if this is expected behaviour or not, but thought it worth flagging just in case. In the situation where KSP has just updated to the 1.1 pre-release, but CKAN has not been updated yet, CKAN does not appear to detect the new version of KSP. The top right corner of the CKAN screen shows "Kerbal Space Program 1.0.5" but KSP is definitely on 1.1 pre-release. This might cause problems with CKAN not realising that mods are outdated or similar issues!

**How to recreate this issue:** 
Opt-in to the KSP 1.1 pre-release on Steam, install CKAN Plasma Window, open CKAN, check KSP version display.

**CKAN error codes (if applicable):** 
None

**Comment by politas** [comment]
Looks like the pre-release does not change the readme.txt file. This whole prerelease is going to be a pain for us. We need CKAN to be correctly marking updated mods as 1.1 to stop users who haven't gone to the prerelease accidentally upgrading to them.

**Comment by politas** [comment]
Looks like #1545 needs a solution.

**Comment by Bit-Fiddler** [comment]
related problem...  my CKAN does report KSP 1.1.0 however the "compatible" filter shows some mods with their max version less than this.  and one for sure (Auto Action by Diazo) breaks your KSP install.

**Comment by pjf** [comment]
@RNeilsen : A new KSP beta was pushed a few hours ago, along with an updated readme file. Does it bring joy?

@Bit-Fiddler : D'oh, there's an old AutoAction version that's marked itself as "universally compatible". It's not. I'll fix that in metadata now.

**Comment by pjf** [comment]
@Bit-Fiddler : Fixed in KSP-cKAN/CKAN-meta#1033 .

**Comment by sundhaug92** [comment]
@pjf Mark as fixed?

**Comment by RJPercival** [comment]
On the topic of mods that have marked themselves as universally compatible, "RemoteTech - DEV RELEASE" is marked as such but isn't actually compatible with KSP 1.1.0. In fact, KCAN is also showing the latest version as v1.6.3 when it's v1.6.9.

**Comment by politas** [comment]
@RJPercival - Go into CKAN Settings and delete RemoteTech-pre from the list of repositories. It is not being maintained and is completely useless at this time.

**Comment by politas** [comment]
But this has been fixed. Squad have kindly updated the readme.txt so even with the current CKAN, KSP1.1 is correctly identified.
