### ISSUE TITLE
Improved Availability Status

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN#1646]
See KSP-CKAN/NetKAN#3511

Even though `USI-Core` is compatiable with KSP 1.1.0 it is marked _unavailable_ because one of its dependencies, `FirespitterCore` is not compatible with KSP 1.1.0. To be consistent this should mean that all mods that are compatible with KSP 1.1.0 but depend on `USI-Core` should also be marked _unavailable_ because one of their 2nd degree dependencies is unavailable. In other words, availability status should be determined by traversing the entire dependency tree, not just direct dependencies.

On a related note, we should have some mechanism by which users can see _why_ a mod is unavailable. So for instance you could do something like:

```
> ckan unavailable
Mods unavailable for KSP 1.1.0

* FirespiterCore (v7.1.5) - Firespitter Core
  Incompatible KSP version: 1.0.5
* USI-Core (0.2.0.0) - USI Core
  Unavailable dependency: FirespitterCore
* USI-NuclearRockets (0.2.0.0) - 'Project Orion' Nuclear Pulse Engine
  Unavailable dependency: USI-Core
```

To keep the list managable the `unavailable` command should only consider the _latest_ version of any unavailable mod (No one really cares why a mod released 2 years ago is unavailable with the latest KSP).

**Comment by ToxicFrog** [comment]
I was just coming here to post this bug after spending ten minutes tracking down why most of the USI mods aren't showing up despite having been indexed by NetKAN. Having mods that are compatible, but uninstallable due to unresolved dependencies, show up as such in the list rather than being hidden completely would have helped.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN/issues/1695
