### ISSUE TITLE
Throttle Controlled Avionics is Broken

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1650]
When trying to install; it reports the download link is broken.

Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Which version of KSP are you on?

**Comment by politas** [comment]
If you're after the KSP1.1 version, the mod author has deleted it from Spacedock, so it's not a CKAN issue.

**Comment by plague006** [comment]
As OP is unwilling to fill in the answers the template provides, I see no reason to keep this issue open.
