### ISSUE TITLE
Missing USI mod - AMT

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1651]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
The only release of that mod was 28 Aug 2014. Are you running KSP 0.25 or such?

**Comment by plague006** [comment]
As OP is unwilling to fill in the answers the template provides, I see no reason to keep this issue open.
