### ISSUE TITLE
TCA upgradability not correctly detected when switching from 1.0.5 to 1.1-prerelease

### ISSUE THREAD

**Issue by mathuin** [KSP-CKAN/CKAN#1660]
**CKAN Version:** 
development (beta) -- HEAD of master

**Operating System:** 
Ubuntu 14.04.4 LTS with CKAN running within Docker as per my dockerize-2 branch

**The issue you are experiencing:** 
TCA has a version for 1.1-prerelease on CKAN but CKAN can't tell that it's an upgrade for me.

**How to recreate this issue:**

1. Install KSP 1.0.5.

2. Install CKAN pointing at that installation of KSP.
  - Run it any way you like, Docker not required.

3. Install the TCA mod with CKAN.
  - Note that the mod should be version v3.0.1.

4. Tell Steam you want to switch to 1.1-prerelease.

5. Use CKAN to list mods.
  - Note that TCA has a bullet of '*' which is not part of the legend.

**CKAN error codes (if applicable):** 
None displayed.

When I ran `ckan list --debug`, I got the following output:

```
2066 [1] DEBUG CKAN.Registry (null) - Finding latest available for ThrottleControlledAvionics
2066 [1] DEBUG CKAN.AvailableModule (null) - Our dictionary has 13 keys
2066 [1] DEBUG CKAN.AvailableModule (null) - Choosing between 13 available versions
2066 [1] DEBUG CKAN.CkanModule (null) - Testing if ThrottleControlledAvionics v3.0.1 is compatible with KSP 1.1.0
2066 [1] DEBUG CKAN.CkanModule (null) - Testing if ThrottleControlledAvionics 3.0.1-KSP-1.1-BETA is compatible with KSP 1.1.0
2066 [1] INFO CKAN.CmdLine.List (null) - Latest ThrottleControlledAvionics is ThrottleControlledAvionics 3.0.1-KSP-1.1-BETA
* ThrottleControlledAvionics v3.0.1
```

That bullet is not listed in the legend.

From `CmdLine/Action/List.cs`, lines 52-103:

```
                var installed = new SortedDictionary<string, Version>(registry.Installed());

                foreach (KeyValuePair<string, Version> mod in installed)
                {
                    Version current_version = mod.Value;

                    string bullet = "*";

                    if (current_version is ProvidesVersion)
                    {
                        // Skip virtuals for now.
                        continue;
                    }
                    else if (current_version is DllVersion)
                    {
                        // Autodetected dll
                        bullet = "-";
                    }
                    else
                    {
                        try
                        {
                            // Check if upgrades are available, and show appropriately.
                            CkanModule latest = registry.LatestAvailable(mod.Key, ksp.Version());

                            log.InfoFormat("Latest {0} is {1}", mod.Key, latest);

                            if (latest == null)
                            {
                                // Not compatible!
                                bullet = "X";
                            }
                            else if (latest.version.IsEqualTo(current_version))
                            {
                                // Up to date
                                bullet = "-";
                            }
                            else if (latest.version.IsGreaterThan(mod.Value))
                            {
                                // Upgradable
                                bullet = "^";
                            }
                        }
                        catch (ModuleNotFoundKraken)
                        {
                            log.InfoFormat("{0} is installed, but no longer in the registry", mod.Key);
                            bullet = "?";
                        }
                    }

                    user.RaiseMessage("{0} {1} {2}", bullet, mod.Key, mod.Value);
                }

```

Note that the bullet is given an initial value of "*", and that the bullet never changes.  This is because `3.0.1-KSP-1.1-BETA` is neither equal to nor greater than `3.0.1`.

I have two suggestions:
#. Somewhere after line 93, an `else` block should handle the case where the latest version is known, not equal to the current version, and not detected as being greater than the current version.  This could legitimately occur if someone has upgraded their mods to a newer version from another source before CKAN becomes aware of that newer version.
#. Either modify the logic for `IsGreaterThan` in `Core/Types/Version.cs` to consider `3.0.1-KSP-1.1-BETA` greater than  `3.0.1`, or fail to accept any new version of a mod if its version string is different from the current version and not greater than that version.

Thanks for making a great tool!

**Comment by plague006** [comment]
I'm a metadata guy not a coder, so if I'm being honest I'm not fully grasping the entirety of your post. But basically you're not being allowed to upgrade because `v3.0.1` > `3.0.1`. The ref'ed PR will solve this issue, however I'll leave this issue open in case one of the coders wants to pursue this further.

**Comment by mathuin** [comment]
That PR should handle the specific concern with TCA.  That doesn't solve the general case, though.  

In my opinion, the general case can be solved in one of two ways:  
* fixing the code which defines 'what is newer' (perhaps using dates instead of version string), or
* documenting `*` as representing a mod that is newer (or at least not older) than currently available on CKAN and thus unable to be upgraded at this time.  

@politas and I have chatted a little in the IRC channel, and I think either of those solutions will address this issue nicely.

**Comment by politas** [comment]
I think there are probably other cases where a mod will end up showing a "*", and the legend really needs to list it, even if it's "Unknown state, manual intervention required"

**Comment by mathuin** [comment]
The issue in question is addressed by the aforementioned open pull request, so I'll close this issue.
