### ISSUE TITLE
Mods downloaded and cached but not installed

### ISSUE THREAD

**Issue by khiasa** [KSP-CKAN/CKAN#1661]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 
mods not installing they just stay cached
**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Are you clicking the "Apply" button in the lower right?

**Comment by khiasa** [comment]
yes i finally figured it out. 

im having a problem with the game taking forever to load is there anyway to decrease this

**Comment by politas** [comment]
If you install a bunch of mods, that's what you get.
