### ISSUE TITLE
KSP AVC - Missing Latest Update

### ISSUE THREAD

**Issue by zschmeez** [KSP-CKAN/CKAN#1666]
**CKAN Version:** 
1.16.1
**Operating System:** 
Windows 10
**The issue you are experiencing:** 
The latest version of KSP AVC, 1.1.6, is completely absent from CKAN
**How to recreate this issue:** 
Attempt to download KSP AVC
**CKAN error codes (if applicable):** 
None

**Comment by plague006** [comment]
Per the [github page](https://github.com/CYBUTEK/KSPAddonVersionChecker/releases) 1.1.6 is a pre-release. In addition, the [ksp forum thread' OP](http://forum.kerbalspaceprogram.com/index.php?/topic/72169-1110-ksp-avc-add-on-version-checker-plugin-116115-miniavc-ksp-avc-online-2016-03-30) doesn't actually mention 1.1.6. Given its pre-release tag on github and absence from the OP it seems the author wants end-users to use the stable 1.1.5 until a stable KSP 1.1 is released. Pinging @CYBUTEK to see if they'd like to contribute in favour or against listing 1.1.6 as the version CKAN installs.
