### ISSUE TITLE
All mods fail to download.

### ISSUE THREAD

**Issue by ajventer** [KSP-CKAN/CKAN#1668]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
v1.16.1-0-g2e91715 (beta)

**Operating System:** 
Linux Mint 17.3

**The issue you are experiencing:** 
I am unable to install any mods whatsoever, all install attempts in either the GUI or the console fails instantly with "couldntconnect" - I can however easily open the URLs with a browser and they work fine. 

**How to recreate this issue:** 
I have no idea, it was working for me a week ago.

**CKAN error codes (if applicable):** 
I ran a commandline install attempt with --debug and --verbose - hopefully this is helpful:

Continue? [Y/n] y

6532 [1] DEBUG CKAN.NetAsyncDownloader (null) - Curlsharp async downloader engaged
6538 [1] DEBUG CKAN.NetAsyncDownloader (null) - Downloading https://spacedock.info/mod/520/RemoteTech/download/1.6.11
Downloading "https://spacedock.info/mod/520/RemoteTech/download/1.6.11" (libcurl)
6543 [1] INFO CKAN.Curl (null) - Using curl-ca bundle: (none)
6544 [1] DEBUG CKAN.NetAsyncDownloader (null) - Downloading https://ksp.sarbian.com/jenkins/job/ModuleManager/110/artifact/ModuleManager-2.6.21.zip
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/110/artifact/ModuleManager-2.6.21.zip" (libcurl)
6545 [8] DEBUG CKAN.NetAsyncDownloader (null) - Curlsharp download thread started
6545 [1] INFO CKAN.Curl (null) - Using curl-ca bundle: (none)
6546 [1] DEBUG CKAN.NetAsyncDownloader (null) - Waiting for downloads to finish...
6546 [9] DEBUG CKAN.NetAsyncDownloader (null) - Curlsharp download thread started
6546 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6547 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6546 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6547 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6547 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6547 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6547 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6547 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6551 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6551 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6551 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6551 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6559 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6559 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6559 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6560 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6576 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6576 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6576 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6576 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6608 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6608 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6608 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6608 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6672 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6672 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6672 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6673 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6801 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6801 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
6801 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
6801 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7057 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
7057 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7058 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
7058 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7057 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
7058 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7257 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
7257 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7258 [9] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
7258 [9] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
7259 [9] DEBUG CKAN.NetAsyncDownloader (null) - Curlsharp download complete
7261 [9] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://ksp.sarbian.com/jenkins/job/ModuleManager/110/artifact/ModuleManager-2.6.21.zip: CKAN.Kraken: CouldntConnect
8059 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
8059 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
8059 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
8059 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
8259 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
8259 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
8260 [8] DEBUG CKAN.NetAsyncDownloader (null) - Progress function called... 0/0
8260 [8] DEBUG CKAN.NetAsyncDownloader (null) - Unknown download size, skipping progress..
8261 [8] DEBUG CKAN.NetAsyncDownloader (null) - Curlsharp download complete
8261 [8] INFO CKAN.NetAsyncDownloader (null) - Error downloading https://spacedock.info/mod/520/RemoteTech/download/1.6.11: CKAN.Kraken: CouldntConnect
8261 [8] INFO CKAN.NetAsyncDownloader (null) - All files finished downloading
8262 [8] DEBUG CKAN.NetAsyncDownloader (null) - Signalling completion via callback
Failed to download "https://spacedock.info/mod/520/RemoteTech/download/1.6.11" - error: CouldntConnect
Failed to download "https://ksp.sarbian.com/jenkins/job/ModuleManager/110/artifact/ModuleManager-2.6.21.zip" - error: CouldntConnect
8263 [8] DEBUG CKAN.NetAsyncDownloader (null) - Cleaning up /tmp/tmp6365c334.tmp
8263 [8] DEBUG CKAN.NetAsyncDownloader (null) - Cleaning up /tmp/tmp6ee117e2.tmp
One or more files failed to download, stopped.

**Comment by plague006** [comment]
Any updates to this?

**Comment by jstirk** [comment]
I was having the same issue. After a few hours of reinstalling mono, updating certs and whatnot I realised it was because libcurl was trying to connect to stardock's IPv6 address rather than the IPv4 one. My network isn't set up for IPv6, so it was failing and not falling back to the IPv4 address.

Once I [disabled IPv6 using this guide](https://www.namhuy.net/1419/disable-ipv6-ubuntu-linux-mint.html) everything now downloads fine.
