### ISSUE TITLE
Interstellar Fuel Switch not found

### ISSUE THREAD

**Issue by NoodlesSE** [KSP-CKAN/CKAN#1669]
**Issue:**
Attempting to download Interstellar Fuel Switch or any of the numerous mods that depend on it results in the following error:

> Failed to download "https://spacedock.info/mod/175/Interstellar Fuel Switch/download/1.19" - error: The remote server returned an error: (404) Not Found."

**Repro:**
Run CKAN with clean KSP 1.1 install
Select Interstellar Fuel Switch or any mod that depends on it
Click 'Apply Changes'
Click 'Apply' to download
**Error described above appears**

**Platform:**
CKAN Version: 1.16.1-0-g2e91715 (beta)
Operating System: Win10
KSP 1.1

**Comment by plague006** [comment]
That download link is indeed 404.. but why is CKAN trying to install 1.19 instead of 1.20 or 1.21...? Please hit "refresh" in CKAN and try again.

**Comment by plague006** [comment]
I also pushed https://github.com/KSP-CKAN/CKAN-meta/commit/6ce26cd9e45265b9e42b7cea9fcf6f0c03deac01 which will make trying to install 1.19 impossible (again as long as you hit refresh).

**Comment by NoodlesSE** [comment]
Have tried again, CKAN now downloads version 1.21 successfully. Thanks for the quick response!
