### ISSUE TITLE
Jenkins using 1.0.5 environment for 1.1 mods

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1670]
Watching the Jenkins output, I saw that it said it is building a 1.0.5 environment.  I don't think it's a problem, it seemed to work ok for the KW files I uploaded this morning

**Comment by plague006** [comment]
Can you link a/the related PR please?

**Comment by linuxgurugamer** [comment]
I saw it in the output for this:  https://github.com/KSP-CKAN/NetKAN/pull/3618
