### ISSUE TITLE
Download of mod content can not be canceled

### ISSUE THREAD

**Issue by mullinger** [KSP-CKAN/CKAN#1671]
**CKAN Version:** 
1.16.1

**Operating System:** 
Window 10

**The issue you are experiencing:** 
CKAN crash

**How to recreate this issue:** 
- download mod content that is not available or times out (maybe metadata not in sync with real files?)
- try to install a mod (which starts a second download?)
- bang

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
I think this would have been addressed by some of the fixes in #3635.
