### ISSUE TITLE
Graphical Glitches Under Mono on OSX

### ISSUE THREAD

**Issue by mdfntr** [KSP-CKAN/CKAN#1673]
**CKAN Version:**
```bash
$ mono ckan.exe version
v1.16.1-0-g2e91715 (beta)
```

**Operating System:** OS X 10.11.4 with Mono 4.4.0 (not Homebrew)
```bash
$ uname -rsvp
Darwin 15.4.0 Darwin Kernel Version 15.4.0: Fri Feb 26 22:08:05 PST 2016; root:xnu-3248.40.184~3/RELEASE_X86_64 i386
$ mono --version
Mono JIT compiler version 4.4.0 (mono-4.4.0-branch/a3fabf1 Fri Apr  8 13:48:29 EDT 2016)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           normal
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  x86
	Disabled:      none
	Misc:          softdebug 
	LLVM:          yes(3.6.0svn-mono-master/a173357)
	GC:            sgen
```

**The issue you are experiencing:** Graphical glitches, including misplaced scrollbars and broken tabs.
(Side note: Interestingly, these issues aren't present when running under WINE, but I get certificate errors with WINE right now) See image below.

![screen shot 2016-04-21 at 22 44 12](https://cloud.githubusercontent.com/assets/9371833/14733051/c75da7ca-0814-11e6-8775-93e33970f853.png)

**How to recreate this issue:** Run `mono ckan.exe` and observe.

**CKAN error codes (if applicable):** None

EDIT:
Running under WINE after using winetricks to install `dotnet45` alleviates both the graphical glitches and the certificate errors! Still, though, I would like to know what went wrong with just using plain Mono...

**Comment by politas** [comment]
Can you try rolling back to the Stable Mono release? I'm on Linux rather than MacOSX and have this working fine.

    $ mono --version
    Mono JIT compiler version 4.2.3 (Stable 4.2.3.4/832de4b Wed Mar 16 13:19:08 UTC 2016) 
    Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
    	TLS:           __thread
    	SIGSEGV:       altstack
    	Notifications: epoll
    	Architecture:  amd64
    	Disabled:      none
    	Misc:          softdebug 
    	LLVM:          supported, not enabled.
    	GC:            sgen

**Comment by politas** [comment]
I think that may mean running CKAN as 32-bit, which is unlikely to be a problem.  You could also try 4.3.2 universal from the archive. I would advise taking this incompatibility up with mono-project.com.

**Comment by mdfntr** [comment]
Unfortunately, after downgrading to the stable Mono release (I didn't realize I downloaded the preview version!), the issue persists with no differences, both with 4.2.3 and 4.3.2 universal. Are there any logs or other steps for me to try that might help you? If not, I would be happy to take it up with the Mono people.

**Comment by politas** [comment]
Damn. I was hoping that would fix it. I'm not aware of other Mac users having the same problem, but Mac is a minority platform. I don't think any CKAN developers run MacOSX, unfortunately.

Could I ask you to (at least temporarily) uninstall WINE and see if there's some conflict there?

**Comment by jammi** [comment]
I've been having these issues as well for quite a while. Resizing the window usually re-renders the window and works as some kind of a temporary glitch work-around until you click on the next thing that renders something in another tab.

**Comment by mdfntr** [comment]
Sorry I didn't get back about this sooner.

@jammi's solution does work as he describes. Forcing a re-draw gets the scroll bars back in the right place.

Running without WINE installed didn't cause any change, unfortunately.

Is there anything else I could try that could help diagnose this? I'm happy to run a debug build or something if necessary.

**Comment by rsparkyc** [comment]
Yes, I have the exact same problems, and resizing the window as @jammi suggested does sometimes help alleviate the issues. I do not have WINE installed.

**Comment by politas** [comment]
This really does sound like a problem with the Mono implementation on MacOSX to me. The same code is supposed to run on Windows with .Net as on MacOSX/Linux with Mono, and it's not. The fact that it runs fine under Wine + .Net 4.5, and it runs fine under Linux, would be indicative. CKAN would be a good example of the problem for Mono developers, since it is open source and thus freely available for them to run for testing purposes. Can you try raising the issue with Mono support?

Seriously, this is exactly the sort of problem that CKAN shouldn't have to worry about. That's why we use Mono in the first place. There's no Mac-specific layout or display code in CKAN, as far as I'm aware.

**Comment by jammi** [comment]
@politas At some point (a year ago or more) CKAN had a release that fixed these graphical glitches and it worked for a while with those until someone patched away those. I think it's simply Mono revealing a CKAN bug that is hidden on Windows maybe due to some Windows layout engine limitations, because other Mono apps I've used don't have this bug.

On OS X Mono has to use a double-buffered [compositing window manager](https://en.wikipedia.org/wiki/Compositing_window_manager), since that's what it always had. On Windows and maybe some Linux setups as well, it's likely Mono still uses the XP-and-older era [stacked window manager](https://en.wikipedia.org/wiki/Stacking_window_manager) API's on Windows rather than the double-buffered compositing GUI stuff that's supported in newer API's on Vista, 7 and so forth.

Since the layout gets messed up when CKAN draws into inactive tabs, which are drawn on top of the  active tab on OS X and apparently not on Windows, my guess is that the GUI component definitions have some overlapping/conflicting properties, like same Z-index, inactive tabs not really hidden or something like that, and that also explains why forcing a repaint by resizing the window fixes the issue temporarily until something is drawn into a background tab again by selecting a new mod to install or remove, for instance.

**Comment by politas** [comment]
@mdfntr , @jammi , @rsparkyc 
Can you try out this build to see if it resolves the graphical glitches? It's not the primary purpose of the build, but I have a suspicion that it might help. 
https://dl.dropboxusercontent.com/u/10499401/ckan.exe
Or if you're not comfortable downloading a program from dropbox, you could download the codebase from #1776 and build it yourself.

**Comment by jammi** [comment]
@politas Not all of them and it's just stuck "updating repositories", so I can't test it further.

**Comment by jammi** [comment]
@politas Here's a set of screenshots of what happens with your build: http://imgur.com/a/f2SGL

There are also plenty of new malloc errors:
    
    5078 [1] WARN CKAN.PluginController (null) - Successfully instantiated type "MigrationToolPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null" from MigrationToolPlugin, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null.dll
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10604544) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10604544) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10399744) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10399744) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=9940992) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=9940992) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:24  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10604544) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:25  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10604544) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:25  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10399744) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:25  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory
    mono(17596,0xa3f34000) malloc: *** mach_vm_map(size=10399744) failed (error code=3)
    *** error: can't allocate region
    *** set a breakpoint in malloc_error_break to debug
    Jun  7 05:13:25  mono[17596] <Error>: CGSImageDataLock: Cannot allocate memory

**Comment by jammi** [comment]
@politas Here's another screenshot of after loading, then chicking "Updating repositories" tab, then coming back to "Manage mods" tab -> no resize needed to get the table visible, but scrollbars are in the wrong place.

**Comment by politas** [comment]
Can you delete MigrationToolPlugin.dll from your CKAN/Plugins folder? That thing is completely broken. I doubt it will get rid of much more than that first warning, though.

**Comment by jammi** [comment]
@politas Sorry about that, removed it and it's behaving better now. The initial position of the scrollbars is wrong though and it's a 50/50 chance of the table of mods not rendering bigger than the scroll bars; http://i.imgur.com/dLVTnwp.png but it settles after a resize. Also while removing a mod, the changeset tab draws on top of the manage tab, like this: http://i.imgur.com/sv4RO30.png

**Comment by politas** [comment]
Can you post the set of malloc errors you get now, sans MigrationTool? They may be useful for more serious coders. 

Thanks a lot for the detailed feedback, I'm sure it will be useful.

**Comment by jammi** [comment]
@politas no malloc errors anymore, seemed to be related to the combination of migrationtoolplugin and your build.

**Comment by politas** [comment]
Were you getting them with the release build and MigrationToolPlugin?

**Comment by jammi** [comment]
@politas I didn't pay attention to that. I don't have a need for the MigrationToolPlugin anymore, but could try that combination if you want to.

**Comment by politas** [comment]
If you can spare the time; it's no big deal. I'm almost certain the mallocs are from MigrationToolPlugin.

**Comment by jammi** [comment]
@politas So am I, since they went away by uninstalling it.

**Comment by politas** [comment]
Ref #1840
