### ISSUE TITLE
NetKAN doesn't override install field if $vref defined

### ISSUE THREAD

**Issue by Starstrider42** [KSP-CKAN/CKAN#1674]
**CKAN Version:** CKAN 1.16.1-0-g2e91715 (beta), NetKAN 1.0.5950.1397
**Operating System:** Windows 10 64-bit

**The issue you are experiencing:** 
I am updating my mod's NetKAN config to prepare for a breaking change in the format of the install zip. The new `install` directive is being placed in the main NetKAN file; the old one is in `x_netkan_override` with version "< [next version]". When I run NetKAN on the file, however, I get the following error:
> 578 [1] FATAL CKAN.NetKAN.Program (null) - No files found in [new directory] to install!

Temporarily replacing the new install directive with the old one confirms that other fields, like `depends`, are correctly overridden in the output .ckan file.

In trying to create a minimum working example, I discovered that this issue only shows up if `$vref` is defined. If I remove it, NetKAN runs without error, and the resulting .ckan file has `install` correctly overridden for the old file format.

**How to recreate this issue:** 
Download [demo.netkan.txt](https://github.com/KSP-CKAN/CKAN/files/232344/demo.netkan.txt) and run it using NetKAN. NetKAN will refuse to create a file for v1.2.0 unless the `$vref` line is removed.

**CKAN error codes (if applicable):** 578 [1] FATAL CKAN.NetKAN.Program (null)

**Comment by Dazpoet** [comment]
This sounds very much like the domain of @dbent

**Comment by dbent** [comment]
I see what the issue is, I'll have to think of the best way to fix it.
