### ISSUE TITLE
Ven's Procedural parts texture & Hazard Textures conflict as both of them try to install PPVensTankEnds.dds.

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1675]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Bizarrely, HazardTanks includes PPVensTankEnds.dds, so yeah, they actually are conflicting. Jump into your Gamedata and delete that file after installing one of the mods if you want to get both installed.

**Comment by plague006** [comment]
Saw this closed but no ref'ed fix. Tried to replicate and was able to. Re-opening.

**Comment by Bit-Fiddler** [comment]
Any resolution for this other than uninstalling both in CKAN and then manually installing these 2 mods?  I know this is possible, but I have had so much trouble with manually installed mods breaking CKAN that I have decided to try and never manually install anything.  basically if CKAN does not list it, I do not use it.

**Comment by politas** [comment]
Jump into your Gamedata and delete the conflicting file after installing one of the mods in CKAN, then install the other mod in CKAN.

**Comment by Bit-Fiddler** [comment]
This does not work as it still thinks the file is registered to the other mod.  I have just uninstalled both of them from CKAN and installed them manually.  But it would be nice if somehow this issue could be fixed.

**Comment by politas** [comment]
Ah. Yes I can see how that would happen, now that I've sent you on a red herring quest. Sorry about that.   I suppose a dependency is called for.
