### ISSUE TITLE
Contares Arrow, and antenna also fight over who owns a file

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1676]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Can you include the details about which file? It's hard to fix it, otherwise?

**Comment by politas** [comment]
Hopefullly, /GameData/Contares/Patches/CONTARES_TweakScale.cfg is the file they're complaining about.

**Comment by Bit-Fiddler** [comment]
i think it was tweak scale .cfg yes
