### ISSUE TITLE
Add a "favourite" column.

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1677]
Several users have requested a way of keeping track of selected mods in CKAN without necessarily installing them, for whatever reason.

We would need to add a "favourited_modules" list in registry.json, and have a sortable checkbox column populated from and populating that list.

Possibly a separate command and listing from the cmdline.

**Comment by krissi** [comment]
It would also be great to have 2 kinds of favourite modules

One could be KSP-install local (as described I guess) and one systemwide. As an alternative the favourite-symbol, for example a yellow star could be orange or the checkbox could be "half-checked") when any other known KSP-install lists it as favourite. 

The usecases I have in mind are the following. The local favourites may be unupdated mods I want to install when they are available or other reasons from linked requests.

The global favourites are to specify a set of "my mods". It is very likely that I miss a mod I use in any installation, but rarely (for example some docking port hud) and want to install it quickly to continue.

**Comment by Guard13007** [comment]
How about instead of favorites, just allow the tagging idea suggested in #1022 to handle it?

**Comment by Erquint** [comment]
Cast my vote for favorites list with automatic checks for and notifications when a non-installed mod from the list gets updated to a version compatible with your game.

**Comment by Olympic1** [comment]
Do we need to add the favourites list to the filter or does it need a new button.
