### ISSUE TITLE
Allow hiding mods

### ISSUE THREAD

**Issue by Guard13007** [KSP-CKAN/CKAN#1678]
There are plenty of mods I have no interest in and won't have an interest in the future, I'd like to be able to hide them so that they aren't cluttering the list of mods I may be interested in.

**Comment by plague006** [comment]
Closing as an extension/duplicate of https://github.com/KSP-CKAN/CKAN/issues/1022 and/or https://github.com/KSP-CKAN/CKAN/issues/1677.

**Comment by Guard13007** [comment]
Neither of those is what I'm asking for. That said, assuming I can create a tag and hide it, then #1022 would be appropriate.
