### ISSUE TITLE
Netkan should handle two-part KSP versions

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#1687]
The [KSP-AVC spec](http://ksp.cybutek.net/kspavc/Documents/README.htm) is unclear on how KSP versions should be specified. Some mods (like RealSolarSystem) contain `.version` files which contain a `KSP_VERSION` section with only `MAJOR` and `MINOR` elements, but no `PATCH` level. Netkan will process these, but outputs a KSP version target of "1.1." (with a trailing dot) which causes validation to fail and generally causes sadness.

We should be lenient in what we accept. Mods with `.version` files that don't specify a KSP patch-level should generate a correct version like "1.1" (without the trailing dot).

Related to KSP-CKAN/NetKAN#3791.

**Comment by plague006** [comment]
We should also catch `BUILD` level for `KSP_VERSION` while we're at it.
