### ISSUE TITLE
Force Installation of incompatible mods

### ISSUE THREAD

**Issue by fat-lobyte** [KSP-CKAN/CKAN#1689]
Hi!

While the compatibility check of the mods highest KSP version vs the KSP version is generally a good idea, I believe there should be a way to force the installation of mods, on responsibility of the user.

This has been demonstrated very well with the 1.1.1 patch to KSP, where suddenly most mods were uninstallable, even if they are perfectly compatible in reality.

I suggest either a check box in the settings: "Disable KSP version check" or a right-click menu option for each mod "Force installation". Maybe a warning message or so should pop up, but I do think such a thing is necessary.

**Comment by plague006** [comment]
Closing this due to / in favour of the referred PR/issue/commit.

https://github.com/KSP-CKAN/CKAN/issues/1173
