### ISSUE TITLE
Feature request: Need a way to allow overwriting of files

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1697]
Ever since I released KWRocketryRedux, with the multiple configs, I'm getting hammered with support requests because people who do manual installs aren't following the instructions properly.

This is happening because there are two different sets of .cfg files to choose from, and if not properly installed bad things happen.

CKAN won't allow me to have a default set of cfgs in the main file, and then to overwrite those cfgs with another set if selected.

Please add the ability to specify either directories, or individual files, which CKAN would be allowed to overwrite.  This would let me (and others) have default configs in place which can be replaced with a different set.

I would also suggest that you add a flag which would tell CKAN to delete an entire directory (up to and including the mod directory itself) when updating a mod.

Without getting into the reasons, it is well known that quite a number of people don't use CKAN.   This issue is merely creating lots of headaches for me, and possibly others.

**Comment by plague006** [comment]
Closing for https://github.com/KSP-CKAN/CKAN/issues/1311
