### ISSUE TITLE
"Missing" mod from CKAN modlist

### ISSUE THREAD

**Issue by PiggyWhiskey** [KSP-CKAN/CKAN#1698]
CKAN: 1.16.1-0-g2e91715 (beta)
Windows 10 x64

Attempting to "force" mods to install that are compatible with 1.1.0/1.1.1 but haven't updated to 1.1.2 yet, and CKAN can't handle that easily.
Universal Storage is visible with 1.1.1 and earlier
Latest Version: 1.1.0.11
Max KSP version: 1.1.2
But it isn't available to be installed. Last compatible release was 1.0.5

After changing the ReadMe back to 1.1.2 to get updates, I noticed Universal Storage was missing from the mod list.

Workaround:
1. Force version 1.0.5 and install mod (and dependency)
2. Change version to 1.1.2 and update as needed.

**Comment by jakkarth** [comment]
This appears to be a duplicate of #1695.

**Comment by PiggyWhiskey** [comment]
Yup. Just saw that as well.
I searched, I swear I did.
