### ISSUE TITLE
CKAN fails to recognize updated version

### ISSUE THREAD

**Issue by JacktoseIntolerant** [KSP-CKAN/CKAN#1708]
##### CKAN Version:
v1.16.1-0-g2e91715 (beta)

##### Operating System:
Windows 10, version 1511, build 14295.1005

##### The issue you are experiencing:
I had Kerbal Engineer Redux 1.1.0.2 installed (via CKAN). Version 1.1.1.0 is currently the latest. After updating repositories, CKAN shows the newer version number, but does not show checkbox in the update column:
![screenshot 2016-05-03 12 24 47](https://cloud.githubusercontent.com/assets/12414794/14995726/1d9b8e8a-112b-11e6-95d3-003aac6b8352.png)

Uninstalling and reinstalling the mod (via CKAN) fixed the issue—it installed the current version.

##### How to recreate this issue:
I'm not sure, as I can't install the older version to try. Presumably, have KER 1.1.0.2 installed and refresh repositories, notice lack of update checkbox.

##### CKAN error codes (if applicable):
[none]

**Comment by plague006** [comment]
22 hours ago (14 hours before this issue was opened) https://github.com/KSP-CKAN/CKAN-meta/commit/9961009c4096e959453974cdfcdcd8ea04abcc80#diff-694331329551438a00afb404e1f3ff7f changed the max ksp_version from 1.1.1 to 1.1.2.

Step 1. Hit "refresh"
Step 2. ???
Step 3. Profit

If refreshing doesn't solve the issue feel free to re-open.

**Comment by JacktoseIntolerant** [comment]
I had the problem about 20 minutes before I opened this, so the newer version should have been available.
Hitting Refresh is what I meant by “updating repositories.” I did that several times.
I guess there's an additional/related issue then, that CKAN didn't get (or didn't display) the newer version?

**Comment by plague006** [comment]
I'm not sure if it represents a bug. Have you been able to reproduce it?

**Comment by JacktoseIntolerant** [comment]
I don't know how. Is there a way for CKAN to install the old version again?
