### ISSUE TITLE
#ckan-notices IRC channel

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1709]
I created the #ckan-notices IRC chat channel to split the github notice spam and the actual chat. For a few days the notices will be sent to both #ckan and #ckan-notices in case anyone is relying on seeing the IRC log.

In addition only commits to the master branch will generate notices (no more commit spam when I'm working on metadata branches).

**Comment by dbent** [comment]
Thoughts on +m (moderating) the channel so that people don't inadvertently start up conversations in there?

**Comment by politas** [comment]
:+1:  for +m, and the whole concept.

**Comment by dbent** [comment]
Well I've gone ahead and +m'd it. There shall be silence!

**Comment by politas** [comment]
Ok, so this has been implemented, and it is certainly making #ckan a more pleasant place. Can we call this a success and close it?

**Comment by techman83** [comment]
![Great Success](http://cdn.quotesgram.com/small/99/59/249977053-borat-quote-great-success.jpg)

**Comment by plague006** [comment]
Currently I have ckan-meta, and netkan posting to the notices channel only and ckan posting to both since it's sort of "in the public's interest". I'll probably leave that configuration unless someone cares enough to suggest otherwise.

**Comment by techman83** [comment]
That makes sense, ckan is much lower traffic and will more often have support things pop up in it.
