### ISSUE TITLE
the CONTARES mod is not working

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#1727]
When selecting CONTARES in the list of compatible mods, the background turns red.  What does this mean?

I assume this is something to do with issues posted here where a mod does not check to see if all of the dependencies are compatible or something?

Sorry KSP v 1.1.2
CONTARES 1.7.0

I guess this may help

**Comment by politas** [comment]
Try uninstalling Contares and Contares-Common, then reinstalling.

**Comment by plague006** [comment]
A red background means that a mod is conflicting with a currently installed or another mod selected to be installed. Do you have HotRockets installed? If you do that's the issue, if you don't upload the contents of your installed-default.ckan somewhere. It's in the CKAN folder in your KSP folder.

**Comment by plague006** [comment]
Closing due to lack of reply.
