### ISSUE TITLE
Kilobytes displayed as kilobits

### ISSUE THREAD

**Issue by terrabite3** [KSP-CKAN/CKAN#1732]
CKAN v1.16.1-0-g2e91715 (beta)
Windows 10 64-bit

The download speed given by CKAN does not match Task Manager. It appears that it is displaying kiloBytes per second but the unit say kilobits per second.

![image](https://cloud.githubusercontent.com/assets/6559276/15272242/250689ba-1a25-11e6-96de-3bfe0abd7093.png)

**Comment by plague006** [comment]
Username checks out. :)
