### ISSUE TITLE
Refreshing doesn't update changes to existing mods

### ISSUE THREAD

**Issue by HiddenKn** [KSP-CKAN/CKAN#1738]
**CKAN Version:** v1.16.1-0g2e91715 (beta)

**Operating System:** Windows 10

**The issue you are experiencing:** If a .ckan file is changed on the repo for an existing mod, the mod doesn't get changed when you refresh. 

Note: When restarting CKAN the data IS correctly updated.

**How to recreate this issue:**
1. Install any mod
2. Change the .ckan file on the repo
3. Refresh
4. Notice that the mod doesn't change

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
I have certainly noticed this issue appearing personally and from multiple reports on the CKAN forum thread. I think there are a few cases where CKAN is building a structure and not replacing it when it should. The listing of what's in the cache, for instance, where we are using a Windows-only filesystem watcher. I think there should be a full rebuild of the metadata relationship structure when CKAN refreshes, at the very least.

**Comment by ayan4m1** [comment]
Does this explain the current behavior any better? https://github.com/KSP-CKAN/CKAN/blob/master/GUI/MainModList.cs#L505

There are plenty of places where one cached list of something _might_ be desynced from another between the registry, modules list and GUI module cache. It's just a question of how many root causes there are, and it may not be worth hunting them all down (i.e. better to replace the entire module).

**Comment by politas** [comment]
That looks like it would explain it.
