### ISSUE TITLE
Running "ckan available" using SSH from another computer throws an exception

### ISSUE THREAD

**Issue by HobbesNovakoff** [KSP-CKAN/CKAN#1743]
**CKAN Version:** v1.16.1-0-g2e91715 (beta)

**Operating System:** OSX and Windows (it's complicated)

**The issue you are experiencing:** I set up an SSH server on my home Windows desktop using OpenSSH so that I can control my computer more easily while I'm away. I'm using my Macbook Pro's command line to access CKAN (installed on the Windows desktop), but when I try to list mods using `ckan available`, this happens:
```
C:\Program Files\OpenSSH\home\####\Documents>ckan available
Mods available for KSP 1.1.2


Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at CKAN.CmdLine.ConsoleUser.get_WindowWidth()
   at CKAN.CmdLine.MainClass.Available(KSP current_instance, IUser user)
   at CKAN.CmdLine.MainClass.Main(String[] args)

C:\Program Files\OpenSSH\home\####\Documents>
```
Other commands like `ckan help` and `ckan list` work fine.

**How to recreate this issue:** 1. Access CKAN (on windows) from the command line using SSH (from OS X). 2. Run `ckan available`.

**Comment by techman83** [comment]
I guess it's trying to open the display. On linux/mac you could run `export DISPLAY=":0"` and it'd probably work. No idea how to make that happen on windows though.

**Comment by HobbesNovakoff** [comment]
I thought it was because it wanted to do some kind of formatting with the window size, but freaked out because it asked the system for the size of a window that doesn't exist. (If I try to do anything that opens a GUI through the SSH connection, it throws an entirely different error...)

**Comment by HobbesNovakoff** [comment]
Wait, where do I run this? And do I tack it onto CKAN in the command line, or what?

**Comment by techman83** [comment]
@HobbesNovakoff - I don't think it'd work on windows. `export` is a command in itself, a good explanation [here](http://stackoverflow.com/a/7328289). I don't have a windows machine with ssh installed to try it.

**Comment by politas** [comment]
Just so I can understand this, you're wanting to see whether there are mods available for a given KSP install, when you are unable to access the physically-attached interface of the computer where it is installed? So, is there any way you can actually _play_ KSP on that computer remotely? I'm just not seeing any real requirement for this capability, so I'm tempted to to say won't-fix on this.

**Comment by politas** [comment]
I've just tested, and `ckan available` works fine under ssh on Linux, with no need to export the display. It's just using the CLI, after all, so there's no reason for it not to work. Unless for some reason it's trying to pop open a dialog box to say "I don't know where KSP is installed".

**Comment by HobbesNovakoff** [comment]
@politas: The reason is that I'm using SSH to access my desktop from school. Basically, if I find a new mod, I want to be able to remotely access CKAN and install it before I get home.

**Comment by mathuin** [comment]
@HobbesNovakoff if you're comfortable with Docker on Windows, you're welcome to use my container for CLI access to CKAN.  Pull the container `mathuin/ckan` and run it however that is done on Windows. :-)

**Comment by HobbesNovakoff** [comment]
Um... What?

**Comment by mathuin** [comment]
https://docs.docker.com/windows/

Docker is awesome, but if you're not already comfortable with it, I would not start using it just to update mods at home while at school.  I use it daily for software development and deployment, so it's not much trouble for me to work with it for maintaining video game mods.

**Comment by HobbesNovakoff** [comment]
I'm certainly not experienced with it. I'm not really a coder.

**Comment by politas** [comment]
Just a quick question, if you run `ckan available` from that folder using a normal command line (not ssh), does it work?

**Comment by phardy** [comment]
For what it's worth, I opened a related issue (with the same exception) in #359. It looks like it got fixed for one particular class of weird ptty handling, but not this one. :(

**Comment by politas** [comment]
Can't reproduce ssh-ing into a Linux host. This would seem to be a problem with the SSH implementation.
