### ISSUE TITLE
Work through our documentation and remove the mod author focus

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1745]
Example from paragraph 3 of [Adding a mod to the CKAN](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN/21828db7553fe76da00c8741bebb0d28c793f400)

>Adding a mod to the CKAN is simply a matter of writing a small JSON file to describe the mod, its relationship with other mods, and the installation process. If you're releasing on SpaceDock, or if the mod is packaged in the usual fashion, then the process is even easier!

We need to get better with our messaging in a consolidated way. See https://github.com/KSP-CKAN/CKAN/issues/1741#issuecomment-220748229 for more.

Phase 1 will be collating which documents exist.
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Workflow
- [X] https://github.com/KSP-CKAN/CKAN/wiki
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Basic-troubleshooting
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Build-Environment
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Building-CKAN-on-Linux
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Code-of-Conduct
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Configuring-Jenkins
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Developers'-Guide
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Guide-to-developing-CKAN-GUI-plugins
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Debian-Jessie-or-Debian-Stretch
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Fedora
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Windows
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu-14.04
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Windows-XP-%28Unsupported%29
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Issues-workflow
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Metadata-labeling-guide
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Logging-and-user-interaction
- [X] https://github.com/KSP-CKAN/CKAN/wiki/New-Developers'-Guide
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Qboid
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Releasing-a-new-CKAN-client
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29
- [X] https://github.com/KSP-CKAN/CKAN/wiki/User-guide
- [X] https://github.com/KSP-CKAN/CKAN/blob/master/CONTRIBUTING.md
- [X] https://github.com/KSP-CKAN/CKAN/blob/master/LICENSE.md
- [X] https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md
- [X] https://github.com/KSP-CKAN/CKAN/blob/master/README.md
- [X] https://github.com/KSP-CKAN/CKAN/wiki/FAQ
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN
- [X] https://github.com/KSP-CKAN/CKAN/wiki/About

Phase 2 identifying which need to be edited.

- [ ] https://github.com/KSP-CKAN/CKAN/blob/master/README.md
- [X] https://github.com/KSP-CKAN/CKAN/wiki/FAQ
- [X] https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN
- [X] https://github.com/KSP-CKAN/CKAN/wiki/About

Phase 3 editing.

**Comment by ferram4** [comment]
I'll start this by noting that while a lot of these might seem like a stretch, remember that there is the user assumption that only mod authors handle CKAN-related things and should go to them; therefore, anything that mentions mod authors doing anything related to CKAN but not mentioning or implying that mods may be indexed or metadata maintained by someone else should be changed.

So to start, the [About](https://github.com/KSP-CKAN/CKAN/wiki/About) page has at the bottom:
>modders can support CKAN without having to change their workflow and distribution method: in fact, you will only need to write a file once and most likely you'll never have to update it again; it doesn't even need to be included in your package!
This should either mention that CKAN contributors will handle this for them or that last section of the page should be reworked

The [FAQ](https://github.com/KSP-CKAN/CKAN/wiki/FAQ) page has:
> I've indexed my mod on the CKAN. Is there a graphic I can use to show this?

and 
> I've just hit the 'submit to CKAN' button on KerbalStuff. Now what?

which are both clearly mod-author focused, entirely related to putting mods on CKAN.  It's only several questions later down the page that this:
> How do mods become available via the CKAN?

appears.  A simple fix would be moving that further up and adding a new question after it: "Who creates and maintains the metadata?  Who should I go to if there is an issue?"  I'd say that there should also be some question or answer that makes it glaringly obvious that mods can be listed on CKAN without their author's knowledge just to be sure.

That's all I've found so far.  There should also be some explicitly stated messaging somewhere that mod authors are not necessarily responsible for creating or maintaining metadata to keep that focus.

**Comment by plague006** [comment]
I gave the documentation a once-over and then read your comment. Upon your recommendation I further tweaked the FAQ wiki page around: https://github.com/KSP-CKAN/CKAN/wiki/FAQ/_compare/75ced5444348f4fc35b4ffaee78460fdda9591ae...4f5f24c1b1504ab514f7fb8feefcb396cbd1c1d2

With the already-completed wiki changes, https://github.com/KSP-CKAN/CKAN/issues/1748 will resolve this issue to my personal satisfaction but if there are instances I missed I'll be happy to have a look at them.
