### ISSUE TITLE
Too many public-domain entries

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1749]
There are 85 (with duplicates) entries in the index stating the referenced mods are ind the public domain, it does not look like they actually are - see the public domain section in https://www.debian.org/doc/packaging-manuals/copyright-format/1.0/#license-specification 

The ids are:
```
TemperatureGaugeKiller
NavBallTextureExport
ScienceFunding
VNG-Parachute-EVALoading
PatentPurchase
ContractConfigurator-SCANsat
StockRT
ReflectionPlugin
Kerbalism
TCShipInfo
rt-config-by-ippo
ExceptionDetector
NavBallsToYou
HarderSolarSystem-4x
FacilityReset
NoMoreGrindRedux
CoolRockets
HoldTheMonoprop
DangerAlerts
StockPlugins
KScale2
StockSCANsat
StockNoContracts
KSPCalendar
LayeredAnimations
ControlLock
HarderSolarSystem-2x
HarderSolarSystem-1x
Kerbalism-Profile-Default
HarderSolarSystem-3x
HarderSolarSystem-generic
```

**Comment by politas** [comment]
On what are you basing the assertion that they are not in the public domain?

**Comment by plague006** [comment]
TemperatureGaugeKiller - to MIT per http://forum.kerbalspaceprogram.com/threads/120731

ContractConfigurator-SCANsat - to WTFPL per https://github.com/SimonTheSourcerer/CCSCANsatMissionPack

VNG-Parachute-EVALoading - to unknown per http://forum.kerbalspaceprogram.com/threads/25305?p=442982&viewfull=1#post442982

NavBallTextureExport - no change per https://bitbucket.org/xEvilReeperx/ksp_navballtexturechanger/src/13d1e0736cd9d67c4ab4dff9e47db2f2f3f9c318/NavBallTextureExport/NBTexExport.cs?at=master&fileviewer=file-view-default

ScienceFunding - no change per https://spacedock.info/mod/554/Science%20Funding

PatentPurchase - no change per https://spacedock.info/mod/692/Patent%20Purchase

StockRT - no change per https://spacedock.info/mod/113/StockRT

ReflectionPlugin - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/63612-105-reflection-plugin-continued-20/

Kerbalism - no change per https://github.com/ShotgunNinja/Kerbalism/blob/master/LICENSE

TCShipInfo - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/59724-112-v04-resource-details-in-tracking-center/

rt-config-by-ippo - no change as author of mod was metadata author

ExceptionDetector - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/98658-exceptiondetector-11-ksp-any-version/

NavBallsToYou - no change per https://spacedock.info/mod/458/NavBallsToYou

HarderSolarSystem-4x - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/124069-105-harder-solar-system-kopernicus-v120-112015-axial-tilt-and-more/

FacilityReset - no change per https://spacedock.info/mod/44/Facility%20Reset%20for%2064bit%20KSP

NoMoreGrindRedux - no change per https://spacedock.info/mod/523/No%20More%20Grind%20Redux

CoolRockets - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/61925-10x-coolrockets-cryo-and-launch-particle-fx-may-24/

HoldTheMonoprop - no change per https://spacedock.info/mod/691/Command%20Module,%20Hold%20The%20Monoprop

DangerAlerts - no change per https://github.com/SpaceIsBig42/DangerAlerts/blob/master/LICENSE.txt

StockPlugins - no change per https://spacedock.info/mod/112/StockPlugins

KScale2 - no change per https://spacedock.info/mod/349/Kscale2%20-%20a%20KSP%20system%20resize%20mod

StockSCANsat - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/90061-11x-malahs-stock-configs-updated-stockplugins-20160501/

StockNoContracts - no change per https://spacedock.info/mod/111/StockNoContracts

KSPCalendar - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/61996-11x-kerbin-date-calendar-redux-version-15/

LayeredAnimations - no change per https://github.com/Starwaster/LayeredAnimations/blob/master/license

ControlLock - no change per http://forum.kerbalspaceprogram.com/index.php?/topic/97829-11apr2416-control-lock-input-text-into-text-fields-without-issuing-commands-to-your-vessel/

HarderSolarSystem-2x - see HarderSolarSystem-4x 

HarderSolarSystem-1x - see HarderSolarSystem-4x 

Kerbalism-Profile-Default - see kerbalism

HarderSolarSystem-3x - see HarderSolarSystem-4x 

HarderSolarSystem-generic - see HarderSolarSystem-4x

**Comment by janbrohl** [comment]
While the mod's author might want to release his work into the public domain in some legislations this is not possible and works can only become public domain under special circumstances. See https://en.wikipedia.org/wiki/Public_domain

**Comment by politas** [comment]
Which clearly states that works can become public domain by relinquishing of rights, as per Graber, Christoph B.; Nenova, Mira B. (2008). Intellectual Property and Traditional Cultural Expressions in a Digital Environment. Edward Elgar Publishing. p. 173. ISBN 978-1-84720-921-4.

**Comment by politas** [comment]
If an author says their work is in the public domain, it's in the public domain. Some jusrisdictions place more things in the public domain, regardless of author intent, but no jurisdictions force licensing of material that the author wants to be in the public domain.

**Comment by plague006** [comment]
While public domain certainly does mean different things in different regions we're conveying authorial intent, not legal status per se. Anyone taking CKAN as a definitive source of legal advice is in error.

**Comment by janbrohl** [comment]
So the spec hast to be changed to reflect that diffence to the debian license specification.

**Comment by plague006** [comment]
We accept PRs.
