### ISSUE TITLE
Spec should list required fields for metanetkans

### ISSUE THREAD

**Issue by plague006** [KSP-CKAN/CKAN#1751]
The spec doesn't specify which fields are required for metanetkans and it'd be nice if it did.

@dbent poking you since you probably have the answer at hand without having to look anything up.

**Comment by dbent** [comment]
Required? Not much... `spec_version`, `identifier`, and obviously `$kref` to make it a metanetkan in the first place.

**Comment by plague006** [comment]
Perfect, thanks.
