### ISSUE TITLE
Mods with "x_" fields that maybe should be mapped to non-"x_" fields

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1756]
Some index entries have x-prefixed fields that correspond to fields allowed by the spec:

x_conflicts:
- UniversalStorage 1.1.0.10
- UniversalStorage 1.1.0.11
- UniversalStorage 1.1.0.12
- UniversalStorage 1.1.0.8
- UniversalStorage 1.1.0.9

x_supports:
- AGExt 1.20
- AGExt 1.21a
- AGExt 1.22
- AGExt 1.22a
- AGExt 1.22b
- AGExt 1.23
- AGExt 1.23a
- AGExt 1.23c
- AGExt 1.24
- AGExt 1.24a
- AGExt 1.25
- AGExt 1.25a
- AGExt 1.25d
- AGExt 1.26
- AGExt 1.28
- AGExt 1.28a
- AGExt 1.28b
- AGExt 1.29c
- AGExt 1.29d
- AGExt 1.30
- AGExt 1.30a
- AGExt 1.30c
- AGExt 1.31
- AGExt 1.31a
- AGExt 1.31b
- AGExt 1.31c
- AGExt 1.31d
- AGExt 1.31e
- AGExt 1.31f
- AGExt 1.31g
- AGExt 1.31h
- AGExt 1.32
- AGExt 1.32a
- AGExt 1.32b
- AGExt 1.32d
- AGExt 1.33
- AGExt 1.33a
- AGExt 1.34
- AGExt 1.34a
- Firespitter v7.1.1

x_comment:
- AdjustableLandingGear 1.0.4

**Comment by plague006** [comment]
I looked into these cases and it seems like `x_` was added as a sort of "freeze" on particular parts of the metadata. Regardless, there's no rationale given in any of the PRs or commits so I'm not inclined to make any changes to older metadata.

PR by mod author to add `x_support` https://github.com/KSP-CKAN/NetKAN/pull/412
Direct commit changing `conflicts` to `x_conflicts` https://github.com/KSP-CKAN/NetKAN/commit/57ac02e2459f04d2d7caab88119215c46e89524f

**Comment by SirDiazo** [comment]
Looking back, that is from when the support keyword was still in the proposed stages and still not implemented.

Quoting pjf from https://github.com/KSP-CKAN/NetKAN/commit/b0c8752f2d2e98611a794d3b189492e46ef14fa5#diff-ff76120d98cc79a0aecc9e2ffca98cfd in November 2014:

You're right that x_support will be ignored. There's a proposal for the CKAN spec to be extended in the future with a "supports" field (KSP-CKAN/CKAN#11), and this is an easy way to get that data in now, so if the spec does get expanded we can easily enable it.

(End quote)
