### ISSUE TITLE
CKAN failing to download or update some mods

### ISSUE THREAD

**Issue by Fuzznut** [KSP-CKAN/CKAN#1758]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

THIS LOOKS A BIT LIKE #1755 AND #1756 TO ME BUT I HAVE NO CLUE WHAT I'M DOING SO SORRY IF THIS IS REPOSTING THAT ISSUE BUT I DON'T KNOW IF THEY'RE THE SAME.

**CKAN Version:** 

v1.16.1-0-g2e91715 (beta)

**Operating System:** 

Windows 10

**The issue you are experiencing:** 

Can't update or download  [x] Science, Near Future Construction, Near Future Electrical, KSP Interstellar extended.

**How to recreate this issue:** 

Try to download or update [x] Science, Near Future Construction, Near Future Electrical, KSP Interstellar extended.

**CKAN error codes (if applicable):** 

Failed to download "https://spacedock.info/mod/234/[x] Science!/download/4.18" - error: The remote server returned an error: (404) Not Found.

Failed to download "https://spacedock.info/mod/563/Near Future Construction/download/0.6.3" - error: The remote server returned an error: (404) Not Found.

Failed to download "https://spacedock.info/mod/558/Near Future Electrical/download/0.7.4" - error: The remote server returned an error: (404) Not Found.

Downloading "https://spacedock.info/mod/234/[x] Science!/download/4.18"
Downloading "https://spacedock.info/mod/563/Near Future Construction/download/0.6.3"
Downloading "https://spacedock.info/mod/558/Near Future Electrical/download/0.7.4"
Downloading "https://spacedock.info/mod/172/KSP Interstellar Extended/download/1.8.21"

Error!

**Comment by plague006** [comment]
This issue and the ones you listed are unrelated. You're getting 404 pages from links that *do* work which makes me suspect this is a transient issue.

Are you currently able to replicate the issue? If you plug the full address (https://spacedock.info/mod/558/Near%20Future%20Electrical/download/0.7.4) into a browser are you able to download the file?

**Comment by politas** [comment]
Of those mods, the two that I have installed updated fine. This certainly appears to be a local issue.

**Comment by jcarabetta** [comment]
I have the same problem. I found the URL with https doesn't work:
https://spacedock.info/ 404 or TIMEOUT
http://spacedock.info/ OK

**Comment by janbrohl** [comment]
Although I have to wait for https longer it works for me.

See #1760 for an idea on how to work around such issues in the future

**Comment by Fuzznut** [comment]
Hi there, yes the link works fine for me manually although when I went to reddit with this issue some people there found that the link was broken. So it was working for some things (me and some friends manually) but not others (my CKAN and some other people)

I read #1760 but I'm afraid I don't understand what its saying, can I change the download location of mods for CKAN somehow?

**Comment by dbent** [comment]
This is likely a [SpaceDock issue](http://forum.kerbalspaceprogram.com/index.php?/topic/132186-spacedockinfo-mod-hosting-site/&page=38#comment-2606586) and there's not much we can do about it besides having possibly redundant sources in future versions.

**Comment by Fuzznut** [comment]
FIXED! Transient was indeed the correct word, just had another go tonight and all of them have successfully downloaded, must have just been a temporary problem over the last few days. Should have been more patient I guess, sorry to bother you guys!

Thanks everyone for your exceedingly quick responses and help! You're awesome!

**Comment by politas** [comment]
Thanks for the update, @Fuzznut
