### ISSUE TITLE
Support online validation for CKAN entries?

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1761]
On www.jsonschemavalidator.net there is a free online schema-validator that can be used to validate CKAN entries (against [CKAN.schema](https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema)).

While it is totally possible to copy the schema into the form by hand, this tool and several others (including Visual Studio) could greatly profit if the schema would be added on www.schemastore.org/json/

This seems to be only one pull request (to https://github.com/schemastore/schemastore/ ) away

**Comment by politas** [comment]
How could we best use the results of the validation to improve our processes?

**Comment by janbrohl** [comment]
Validation results are useful for people editing CKAN-files by hand or working with/on tools that work with them - like those suggested in #1762 for example.

Validating files before sharing/uploading them could help lessen support load on the CKAN team because ckan-files in the wild (not in CKAN-meta as they are validated on addition) would be more valid as the editors get more direct feedback on their errors.

For CKAN-meta no direct additions are allowed anymore but I read that there are other CKAN repositories for which this could be directly useful and for user-made modlists it seems they will not be added to CKAN so they will not run through the netkan-toolchain.

The effect may be small adding the schema to the store should be 5 minutes work maximum - I could do that if you want.

**Comment by politas** [comment]
No reason I can see not to. perhaps some relevant changes to the help/wiki pages with links would be good, too.

**Comment by janbrohl** [comment]
Which name and description should I set in the PR? File extension ".ckan" only, right?

**Comment by politas** [comment]
Yes; that schema is for ckan files, not netkans.

**Comment by janbrohl** [comment]
Sorry - I was wrong.
I have to upload the file. Should I append a version? If yes, which one? 1.18?

File extension is ".ckan" only - not ".json", too?

Actually it is better if a project member makes the PR as discussing would take more time than that.

**Comment by plague006** [comment]
https://github.com/KSP-CKAN/CKAN/blob/v1.16.1/CKAN.schema would be v1.16. Might be best not to touch v1.18 until it's released.

**Comment by janbrohl** [comment]
PR created as  SchemaStore/schemastore/pull/174

**Comment by janbrohl** [comment]
PR was merged :)

**Comment by janbrohl** [comment]
KSP-CKAN 1.16 is last in the list at http://www.jsonschemavalidator.net/ (for me) now - you can use it there

**Comment by janbrohl** [comment]
Should I add older versions, too?

**Comment by HebaruSan** [comment]
Pull requests for NetKAN and CKAN-meta are validated pretty comprehensively nowadays. Syntax errors are caught, schema problems are caught, dependencies are checked, mods are downloaded and installed. It's pretty thorough.

Does that satisfy this?

**Comment by politas** [comment]
Between that and @linuxgurugamer 's script, I think we're probably fine to close this.
