### ISSUE TITLE
Link to web-forms for making CKAN-files by hand

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1762]
While the [Webtool](https://github.com/KSP-CKAN/metadata-webtool) is not done yet there are alternatives for making CKAN files. Two of them are http://jeremydorn.com/json-editor/ and https://jsonary-js.github.io/jsonary/try.html

To use them you have to copy https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema into these forms but sources are available ([jsonary](https://github.com/jsonary-js/jsonary) and [json-editor](https://github.com/jdorn/json-editor)) and at least for jsonary you can link with the spec in URL string.

This would be interesting for the manual part of https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29

**Comment by janbrohl** [comment]
Created a really simple CKAN-editor (almost only copy-paste) - uploaded on https://gist.github.com/janbrohl/0c9aa1c8d026b7b5e4e4cd3c869e42f5

**Comment by politas** [comment]
See http://forum.kerbalspaceprogram.com/index.php?/topic/143239-ckan-metadata-webtool
This is looking pretty solid now, we should definitely include it on the [Adding a mod to the CKAN](https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN) page

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/Adding-a-mod-to-the-CKAN#intermediate
