### ISSUE TITLE
Unhandled exception, Object reference not set to instance of object

### ISSUE THREAD

**Issue by GoldenPhysics** [KSP-CKAN/CKAN#1763]
The error window pops up when launching CKAN, and the title of the window is Microsoft .Net Framework. Looking at other issues posted, I saw it was probably a .Net issue, so I downloaded the web installer from Microsoft (https://www.microsoft.com/en-us/download/details.aspx?id=49981) and it told me I had version 4.6.1 or later. Does CKAN work on that version, or will I have to download an earlier version? Is there anything else I can tell you guys that will help solve this (I can post the debug details)?

**CKAN Version:** 
1.16.1-0-g2e91715(beta) aka plasma window

**Operating System:** 
Windows 10

**The issue you are experiencing:** 
When launching CKAN, it gives the error in the title

**How to recreate this issue:** 
Launch CKAN

EDIT: Thought I should add this, if I click continue on the error window, CKAN will load but the list of mods will be empty.

**Comment by politas** [comment]
This is your first time loading CKAN? The mod list will always be empty initially. Clicking "Refresh" should populate it.

**Comment by GoldenPhysics** [comment]
No, it loaded a few months ago, I think it was the same release. When I click refresh, it gives the same error.

**Comment by politas** [comment]
1. Are you working with a clean KSP installation? 

2. Is the folder where KSP is installed writable by your user account?

**Comment by GoldenPhysics** [comment]
1. I'm not entirely sure what you mean by clean. There are still mods in the GameData folder, but I think all of them were installed through CKAN, so I don't see why that would cause a problem.

2. It seems that it is not. I've tried disabling read-only on a few folders (Kerbal Space Program, Steam, steamapps, common), and only the Kerbal Space Program and steamapps folder actually disabled read-only when I checked the properties tab again. Even after trying all of that, CKAN has the exact same error. (Although I didn't compare the details part of the error window.)

**Comment by politas** [comment]
Check the various files and folders in Kerbal Space Program\CKAN for read only status?

**Comment by GoldenPhysics** [comment]
Both folders are read only. I'll try to change that and edit this when that finishes.

**Comment by politas** [comment]
I suspect this is the source of the error, and it is likely something that has come in with Windows 10.

**Comment by GoldenPhysics** [comment]
I've tried disabling read-only from an administrator account, I've tried making sure my account has full permissions from the security tab of the properties window, the share button is grayed out so the solutions I've googled and found that say to share don't work, going into some "advanced" tabs and windows, I reached a "View effective access" which said my account had full acces, and nothing I've tried has fixed it. Any suggestions?

**Comment by janbrohl** [comment]
I have no problems on 10 should i have a look via teamviewer or something?

**Comment by GoldenPhysics** [comment]
I have no idea what that means.

**Comment by janbrohl** [comment]
I was talking about remoting into your computer with a software like that from https://www.teamviewer.com/ but when thinking about it, it doesn't not seem like a good idea to let a total stranger (like me) remote-control your computer

**Comment by GoldenPhysics** [comment]
That's what I though, too.

**Comment by janbrohl** [comment]
Try to install Net 4.5 again from https://www.microsoft.com/en-au/download/details.aspx?id=30653

Redownload CKAN and unpack the zip to a folder on your desktop. Start from there.

**Comment by dbent** [comment]
Does the error you see look like [this](http://www.jososoft.dk/yamaha/articles/exception2.gif)? If so we need the contents of details field.

**Comment by GoldenPhysics** [comment]
"Microsoft .NET Framework 4.5 is already a part of this operating system.  You do not need to install the .NET Framework 4.5 redistributable.

Same or higher version of .NET Framework 4.5 has already been installed on this computer."

That's exactly what it told me when I tried to download it. I think I have 4.6.1.
I downloaded the zip of the CKAN master branch, but, being as inexperienced as I am, have no idea where do go from there.
The details field:

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.Main._UpdateModsList(Boolean repo_updated)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.CurrentInstanceUpdated()
   at CKAN.Main.OnLoad(EventArgs e)
   at System.Windows.Forms.Form.OnCreateControl()
   at System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   at System.Windows.Forms.Control.CreateControl()
   at System.Windows.Forms.Control.WmShowWindow(Message& m)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.Form.WmShowWindow(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Sam_2/Downloads/ckan(1).exe
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1081.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1078.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
Microsoft.GeneratedCode
    Assembly Version: 1.0.0.0
    Win32 Version: 4.6.1064.2 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1080.0 built by: NETFXREL3STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.6.1038.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

**Comment by dbent** [comment]
What's the output of the `ckan ksp list` command from the command line?

**Comment by GoldenPhysics** [comment]
Only one listing. \otherstuff\steam\steamapps\common\Kerbal Space Program

**Comment by dbent** [comment]
Make sure it's set as the default: `ckan ksp default` (Enter `1` then press enter). Then do: `ckan list --debug > ckan-debug.txt` to dump the debug output to a file. Then place the contents of the file in a [gist](https://gist.github.com/) or something.

**Comment by GoldenPhysics** [comment]
I set the default, then tried the other stuff. I know I've said it before, but I'm not very experienced with the command line, so more detail is better with instructions. A link to somewhere with some basic instructions would be very helpful. By the way, thank you all for helping so far, before I forget.

CKAN crashes when I do this, so I don't think I can put the debug log in a file.

The debug throws the same object reference error, then says (**first attempt from downloads**):

C:\otherstuff\Downloads>ckan list --debug > ckan-debug.txt

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.CmdLine.List.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.Main(String[] args)

C:\otherstuff\Downloads>ckan list --debug

145 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
192 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
201 [1] DEBUG CKAN.KSPManager (null) - Loading auto from c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program
210 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
214 [1] DEBUG CKAN.KSP (null) - c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program looks like a GameDir
219 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
220 [1] DEBUG CKAN.KSP (null) - c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program looks like a GameDir
225 [1] DEBUG CKAN.KSP (null) - Initialising c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
229 [1] DEBUG CKAN.KSP (null) - Initialised c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
236 [1] DEBUG CKAN.KSPManager (null) - Added auto at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program
248 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: C:\Users\Sam_2\Downloads
252 [1] DEBUG CKAN.KSP (null) - Cannot find GameData in C:\Users\Sam_2\Downloads
255 [1] INFO CKAN.CmdLine.MainClass (null) - Using KSP install at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program
276 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
510 [1] DEBUG CKAN.RegistryManager (null) - Loaded CKAN registry at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN\registry.json

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.CmdLine.List.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.Main(String[] args)


**Second attempt from a copy of ckan in the KSP folder**:

C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program>ckan list --debug
121 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
161 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
168 [1] DEBUG CKAN.KSPManager (null) - Loading auto from c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program
178 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
181 [1] DEBUG CKAN.KSP (null) - c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program looks like a GameDir
186 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
188 [1] DEBUG CKAN.KSP (null) - c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program looks like a GameDir
193 [1] DEBUG CKAN.KSP (null) - Initialising c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
197 [1] DEBUG CKAN.KSP (null) - Initialised c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN
201 [1] DEBUG CKAN.KSPManager (null) - Added auto at c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program
207 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program
212 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
212 [1] DEBUG CKAN.KSP (null) - C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program looks like a GameDir
218 [1] INFO CKAN.KSP (null) - KSP found at C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program
223 [1] DEBUG CKAN.KSP (null) - Found version 1.1.2
225 [1] DEBUG CKAN.KSP (null) - C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program looks like a GameDir
228 [1] DEBUG CKAN.KSP (null) - Initialising C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
232 [1] DEBUG CKAN.KSP (null) - Initialised C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
236 [1] INFO CKAN.CmdLine.MainClass (null) - Using KSP install at C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program
254 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
435 [1] DEBUG CKAN.RegistryManager (null) - Loaded CKAN registry at C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN\registry.json

Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.RegistryManager.AscertainDefaultRepo()
   at CKAN.RegistryManager..ctor(String path, KSP ksp)
   at CKAN.RegistryManager.Instance(KSP ksp)
   at CKAN.CmdLine.List.RunCommand(KSP ksp, Object raw_options)
   at CKAN.CmdLine.MainClass.Main(String[] args)

C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program>

**Comment by dbent** [comment]
Well, we're done with command line for now.

Place the contents of the file `C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN\registry.json` in a [gist](https://gist.github.com/), that file is going to be fairly large and long comments are unwieldly.

**Comment by GoldenPhysics** [comment]
Well, never having done that before, I searched for an answer, then found one and tried opening it with notepad, however all it seemed to contain was a bunch of blank lines. Is that supposed to happen or am I being an idiot?

**Comment by dbent** [comment]
Totally and completely empty? Believe it or not that's the result I was expecting. The only possible way for you to get the error you were getting was if that file existed and was totally empty.

How it got that way, I couldn't say, possibly corruption from CKAN itself from some other error or crash. Unfortunately that file is what CKAN uses to keep track of what's installed, so that installation is pretty hosed as far as CKAN is concerned. If you happen to have a backup of that directory from an earlier state you can try restoring it, otherwise my recommendation is:

- In that same folder copy the `installed-default.ckan` file somewhere safe. Hopefully that isn't hosed as well. It should contain the packages that were installed, just not which exact files were installed (which was contained in `registry.json`).
- Delete the `registry.json` file, it's useless now.
- **Backup** the `GameData` directory somewhere safe.
- In the `GameData` directory, delete every file and folder that is **not** the Squad folder.
- Execute CKAN again, it should find your relatively virgin installation and set things back up again.

Now for restoring the mods you had installed:

- Open the CKAN GUI, go to *File > Install from .ckan...* and select the `installed-default.ckan` you previously saved.

If you last used CKAN in the current release, it should install all the mods. If however, you last used it with a previous KSP release, some of those exact mod versions probably aren't for the current release. Easiest thing to do in that case is just go through the list and install the latest versions manually.

**Comment by GoldenPhysics** [comment]
Ok, I followed all the instructions and it worked, except for the mods restoring. That's not too big of an issue, though, I can manually select new ones, and it was probably time update what I wanted anyways. 

Here's the error for installed-default.ckan stuff, if you're interested:

JSON deserialization error: Unexpected initial token 'None' when populating object. Expected JSON object or array. Path '', line 1, position 3276.

Other than that, all I have to say is a huge thanks to all of you.
