### ISSUE TITLE
Add "Updated" filter type

### ISSUE THREAD

**Issue by oldlost** [KSP-CKAN/CKAN#1766]
We all know that for installed mods that get updated we can filter to this and even update those mods with a couple clicks. Great.

It would be nice to have a new filter that show a list of mods that are not installed that have been updated since the last CKAN run. This may allow us to see which mods are now compatible with the current version that were not before, or ones that were recently changed we may want to consider installing.

Thanks for listening and thanks for all the work you do on making this program better.

**Comment by HebaruSan** [comment]
#2494 covers "which mods are now compatible with the current version that were not before."

"recently changed we may want to consider installing" would be more involved. Either the client would have to compare every property from the old and new metadata for every mod (slow!), or we would need to track a last updated timestamp a la #1155.
