### ISSUE TITLE
I do not see clouds on Real Solar System after downloading EVE... Do I need to change something in the config file for the clouds to appear?

### ISSUE THREAD

**Issue by smckamey19** [KSP-CKAN/CKAN#1767]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
There is a port of EVE for Real Solar Systems called [RSS Visual Enhancements](http://forum.kerbalspaceprogram.com/index.php?/topic/75157-). 

RSS Visual Enhancements has not been brought up to KSP 1.1, unfortunately, and it isn't on CKAN yet.

I'm not sure that EVE would work on RSS at all - All the planets are different, after all. I gather that there is some RSS compatibility in EVE, but [rbray89 recommends different configs in the changelog](http://forum.kerbalspaceprogram.com/index.php?/topic/51142-). You will need to do some research and tweaking for that. CKAN installs EVE using the standard config, expecting a stock system

**Comment by smckamey19** [comment]
Thank you!

Sent from my iPhone

On Jun 1, 2016, at 10:09 PM, Myk <notifications@github.com<mailto:notifications@github.com>> wrote:


There is a port of EVE for Real Solar Systems called RSS Visual Enhancements<http://forum.kerbalspaceprogram.com/index.php?/topic/75157->.

RSS Visual Enhancements has not been brought up to KSP 1.1, unfortunately, and it isn't on CKAN yet.

I'm not sure that EVE would work on RSS at all - All the planets are different, after all. I gather that there is some RSS compatibility in EVE, but rbray89 recommends different configs in the changelog<http://forum.kerbalspaceprogram.com/index.php?/topic/51142->. You will need to do some research and tweaking for that. CKAN installs EVE using the standard config, expecting a stock system

-
