### ISSUE TITLE
Please clarify install_to in the Spec

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#1770]
At least i did not understand what paths are OK to put in install_to correctly. I thought it would only be these

> Valid values for this entry are GameData, Ships, Ships/SPH(v1.12), Ships/VAB(v1.12), Ships/@thumbs/VAB(v1.16), Ships/@thumbs/SPH(v1.16), Tutorial, Scenarios (v1.14) and GameRoot (which should be used sparingly, if at all)

but i am told some subdirectories are OK, too.  

Please clarify the install_to section because maybe it is  not just me being stupid.

**Comment by politas** [comment]
> (v1.2) For GameData only one may specify the path to a specific subfolder; for example: GameData/MyMod/Plugins. The client must check this path and abort the install if any attempts to traverse up directories are found (eg: GameData/../Example).

Is that sufficient clarification (the next paragraph)?

**Comment by janbrohl** [comment]
Not for me - in the only other paragraph subfolders are not in the valid list and it is not stated if subfolders are allowed for other places than GameData. 

This paragraph says that there may be at most one install directive with install_to set to a subdirectory of GameData?

**Comment by politas** [comment]
Ok, would it make more sense if it was turned around like this?

> under spec_ver v1.2 and higher, you can specify the path to a specific subfolder, but only within the GameData folder.

**Comment by politas** [comment]
The parsing is (for GameData only) (one may specify the path to a specific subfolder)

**Comment by janbrohl** [comment]
I'd like 

> with spec_ver v1.2 and higher, it is _also_ valid to specify the path to a specific subfolder, but only within the GameData folder. (eg: GameData/MyMod/Plugins)

better but my english is not so good.

But thanks now it is clear to me. :)

**Comment by politas** [comment]
Sounds like you were thrown by the pronoun "one", which is less common English. Might be better to avoid that in our doco.

**Comment by janbrohl** [comment]
It me it was clearly meant like "for gamedata: only one may..." but it was meant like "for gamedata only: one may..."

**Comment by politas** [comment]
Does that read better?

**Comment by janbrohl** [comment]
Much better!
