### ISSUE TITLE
Running `ckan.exe gui` fails if no default ksp install is selected

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1785]
This may be specific to Linux, or it may not. My ckan.exe is not located in a KSP install

    $ mono ./ckan.exe list
    I don't know where KSP is installed.
    Use 'ckan ksp help' for assistance on setting this.
    $ mono ./ckan.exe gui
    I don't know where KSP is installed.
    Use 'ckan ksp help' for assistance on setting this.

But if I run

    $ mono ./ckan.exe

It will go straight to the "Select KSP install" dialogue.

If I have a ksp install default set, `ckan.exe gui` works

**Comment by Postremus** [comment]
able to reproduce.
