### ISSUE TITLE
Virus detected in freshly downloaded ckan.exe

### ISSUE THREAD

**Issue by marauder13** [KSP-CKAN/CKAN#1786]
CKAN Version: 1.18.0

Operating System: Windows 10

The issue you are experiencing: AVG Free detected a virus in ckan.exe - IDP.ARES.Generic

How to recreate this issue: Executing the ckan.exe application

CKAN error codes (if applicable): None applicable

Other notes : AVG Free was checked for updates prior to last attempt to run the executable, and everything is up to date. I went to https://github.com/KSP-CKAN/CKAN/releases/tag/v1.18.0 and selected the ckan.exe to download. I copied the application to the target directory, then executed the application. The virus was immediately detected, and dealt with by AVG.

This was not an issue 24 ~ 48 hours ago when I last ran the application. No other software in my computer has not had any virus detected. This is also the first time I have had an issue of this nature with the ckan application.

Thanking you in advance for your time,

Craig.

**Comment by pjf** [comment]
Looking at the release assets github shows they were uploaded using the expected build key which is used by our build/test server (travis), and we haven't updated any of the libraries we depend upon since the last release, so there's an overwhelming chance this is a false alarm. 

However even if it is a false alarm, I'd love to know what we've done to trigger it. If you grab the [v1.16.1 release](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.16.1) does AVG also claim for there to be an infection?

Many thanks!

~ Paul

**Comment by marauder13** [comment]
Hi Paul.

I grabbed the v1.16.1 release and dropped it into the normal place I run it from, and it told me of the later version, which I declined to install, and proceed to let it run, and it worked just fine. AVG did not trigger any alerts when that version started to run.

I have not done any updates to the AVG since this error commenced, neither have I done anything  else to change/alter the system. I have no viruses on the computer, as I did a complete scan approximately five(5) hours ago, and got one threat elsewhere which was removed, but it was not the same as the type that comes up when ckan triggers AVG.

My version of AVG Free is up to date, so whatever the virus identifier is must have come through with the latest data update.

For clarity, I am not blaming you, nor your team/contributors for what is happening, neither am I saying that there definitely is a virus in your application, but I do believe that there is a something with the code that may be causing the trigger. I have been using ckan for quite a while, and apart from one small, easily corrected issue, I have had no problems with it at all. I think this is a great application, and all involved have done a great job with it. But when this problem came up, I wanted to bring it to your attention, in case it was possibly something serious, and only after I tried a few different things myself to make sure that I was not doing anything wrong.

Once more, thank you again for your time, and understanding, with dealing with this problem. In the meantime, I shall use v1.16.1 until this problem is somehow resolved.

Craig.

**Comment by politas** [comment]
This isn't the first time AVG has flagged a CKAN release as a potential virus. Personally, I think AVG is like some of the dodgier naturopaths, who'll give you a "test" that lists a bunch of conditions you never suspected you had, and then will provide you with "cures" for these "conditions".

**Comment by politas** [comment]
http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1180-19-june-2016/&page=41#comment-1847199

http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1180-19-june-2016/&page=86#comment-2295131

http://forum.kerbalspaceprogram.com/index.php?/topic/90246-the-comprehensive-kerbal-archive-network-ckan-package-manager-v1180-19-june-2016/&page=76#comment-2183557

AVG Free is exactly worth what it costs.

**Comment by Quartz101** [comment]
A V G  
N I  A  
T R R  
I  U B  
   S A  
      G  
      E   
  
**A**nti**v**irus **G**arbage

**Comment by Cphoenix** [comment]
> Personally, I think AVG is like some of the dodgier naturopaths, who'll give you a "test" that lists a bunch of conditions you never suspected you had, and then will provide you with "cures" for these "conditions". 

This. AVG causes all manner of problems and it's way, way too trigger-happy with its heuristics. Personally I recommend Sophos Home. It's free, and it's more-or-less built on the same stuff Sophos sells to industry. Honestly it's the only free AV software I've ever used that was actually worth a damn.

Also that gave me a good laugh. I live in a city where there are **piles** of those people everywhere. And more than enough affluent idiots to spend thousands on their "remedies".

**Comment by fedoracoreuser** [comment]
I've just experienced this issue for the first time.
I'm using Windows 10 with Windows Defender, updated to this morning.
I've never had an issue with CKAN being detected as malware, and I ran this exact version of the program several times over the past few days. This morning I log in and Defender immediately reports malware. The threat type is Trojan:Win32/Fethar.B!cl. I am using CKAN version 1.18.1.

I tried redownloading it, but it gets blocked by Windows Defender.
Now, I submitted a copy of this file as a sample to Microsoft, asking for clarifications about why it's getting detected as malware. If and when they reply, I'll post what they have to say.

**Comment by shanaman** [comment]
I have the same issue a Fedoracoreuser with windows defender flagging ckan.exe version 1.18.1 as a virus with Trojan:Win32/Fethar.B!cl.  Previous version of ckan works fine.

**Comment by politas** [comment]
This has been reported to Microsoft, and will hopefully be sorted out soon.

**Comment by shanaman** [comment]
Defender Update today fixed it for me.

**Comment by politas** [comment]
Microsoft have replied and said this is fixed.
