### ISSUE TITLE
mozroots - Couldn't retrieve the file using the supplied information.

### ISSUE THREAD

**Issue by kitingChris** [KSP-CKAN/CKAN#1787]
**CKAN Version:** 
latest
**Operating System:** 
ubuntu
**The issue you are experiencing:** 
```
$ mozroots --import --ask-remove 
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.
```

**Comment by emmanuelmathot** [comment]
same issue with 3.2.10

```
# mozroots --import --sync
Mozilla Roots Importer - version 3.12.0.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
Couldn't retrieve the file using the supplied information.
```

**Comment by politas** [comment]
Mozilla have removed this functionality. You'll need to use Mono's built-in certmgr instead. I haven't been able to reproduce the symptoms to work out exactly what's needed in terms of instructions, though

**Comment by bdouxx** [comment]
hi 
watch my post on an gentoo bug : 
**https://bugs.gentoo.org/show_bug.cgi?id=585548#c4**

use this command instead:
mozroots --import --sync --machine --url "http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt"

or better( if ca-certificates.crt are here):
cert-sync /etc/ssl/certs/ca-certificates.crt

**Comment by kitingChris** [comment]
@bdouxx does not work for me :( 
```
# mozroots --import --sync --machine --url "http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt"
Mozilla Roots Importer - version 3.2.8.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

Downloading from 'http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...
Importing certificates into machine store...
Error: System.ArgumentException: Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.
  at System.Buffer.BlockCopy (System.Array src, Int32 srcOffset, System.Array dst, Int32 dstOffset, Int32 count) [0x00000] in <filename unknown>:0 
  at Mono.Security.ASN1..ctor (System.Byte[] data) [0x00000] in <filename unknown>:0 
  at Mono.Security.X509.X509Certificate.get_RSA () [0x00000] in <filename unknown>:0 
  at Mono.Security.X509.X509Store.ImportPrivateKey (Mono.Security.X509.X509Certificate certificate, System.Security.Cryptography.CspParameters cspParams) [0x00000] in <filename unknown>:0 
  at Mono.Security.X509.X509Store.Import (Mono.Security.X509.X509Certificate certificate) [0x00000] in <filename unknown>:0 
  at Mono.Tools.MozRoots.Process () [0x00000] in <filename unknown>:0 
  at Mono.Tools.MozRoots.Main (System.String[] args) [0x00000] in <filename unknown>:0 
```

**Comment by bdouxx** [comment]
@kitingChris

can you try the other method?
[www.mono-project.com/docs/about-mono/releases/3.12.0/](url)

Mono users on Linux no longer need to run mozroots to get SSL working. A new command, cert-sync, has been added to this release, which synchronizes the Mono SSL certificate store against your OS certificate store – and this tool has been integrated into the packaging system for all mono-project.com packages, so it is automatically used when you install Mono via our packages. Just make sure the ca-certificates-mono package is installed on Debian/Ubuntu (it’s always bundled on RPM-based distros) to take advantage! It should be installed on fresh installs by default.

If you want to invoke the tool manually (e.g. you installed via make install, not packages) use
cert-sync /path/to/ca-bundle.crt

On Debian systems, that’s
cert-sync /etc/ssl/certs/ca-certificates.crt

and on Red Hat derivatives it’s
cert-sync /etc/pki/tls/certs/ca-bundle.crt

Your distribution might use a different path, if it’s not derived from one of those.

**Comment by kitingChris** [comment]
```
$ uname -a
Linux CENTAURI 4.2.0-42-generic #49-Ubuntu SMP Tue Jun 28 21:26:26 UTC 2016 x86_64 x86_64 x86_64 GNU/Linux

$ cat /etc/os-release 
NAME="Ubuntu"
VERSION="15.10 (Wily Werewolf)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 15.10"
VERSION_ID="15.10"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"

$ cert-sync
cert-sync: command not found
```

**Comment by ayan4m1** [comment]
http://packages.ubuntu.com/search?searchon=contents&keywords=cert-sync&mode=&suite=xenial&arch=any

> Just make sure the ca-certificates-mono package is installed on Debian/Ubuntu

**Comment by politas** [comment]
Blame Ubuntu for staying with an old Mono release long past its release. 15.04 should have been given Mono 3.8, and Mono 4.0 was out in plenty of time to be included in 15.10. Staying with 3.2.8 for two years is absurd for anyone other than those staying on the LTS release, who know that sometimes they need to upgrade specific packages.

**Comment by zz0rk** [comment]
This works for me:

cd /
sudo mozroots --import --sync --machine --url "http://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt"

**Comment by politas** [comment]
The CKAN will not be supporting Mono 3.2.8 forever. Please upgrade.

**Comment by zz0rk** [comment]
Sure will... once a stable Debian package becomes available in the repository.

**Comment by politas** [comment]
Debian still doesn't have a Mono later than 3.2.8? At least Ubuntu finally has an upgrade in 16.04! If I were you, I'd be complaining to the Debian package maintainers about this.

**Comment by techman83** [comment]
Mono Project build their own packages.

http://www.mono-project.com/docs/getting-started/install/linux/

**Comment by politas** [comment]
Yeah, that's what I use.

**Comment by ayan4m1** [comment]
Apologies, but the discussion has strayed pretty far from the original issue. Please open specific issues for specific problems - once the problems with 3.2.8 start piling up it will give us even more incentive to stop supporting it. I am locking the conversation on this issue to prevent it from becoming the place where everyone throws their "Mono 3.2" comments and issues.

The original issue was that mozroots has been deprecated. It no longer fixes our cert issues, but a new Mono tool does. However, to get the new Mono tool, you have to upgrade Mono to the version offered by Mono's official Debian/Ubuntu repository. [This](https://bugzilla.xamarin.com/show_bug.cgi?id=41988) is the upstream bug report that you are running into. We cannot fix Mono project issues, and their response is to upgrade to Mono 4.x.
