### ISSUE TITLE
CKAN gui refuses to appear

### ISSUE THREAD

**Issue by N70** [KSP-CKAN/CKAN#1789]
**CKAN Version:** Startram  

**Operating System:** Windows 10  

**The issue you are experiencing:** CKAN gui refuses to show up at all, and instead ckan.exe stalls in the background, and it even takes a long time to close when using "End Task" or "End Process Tree" in task manager, and "TASKKILL /F /IM  ckan.exe" doesn't work, either. NET 4.5 is pre-installed in windows 10, according to the NET installer. I've also tried opening it using "ckan gui" in the command line. The "enable auto-updates" window pops up, too.

**How to recreate this issue:** ?*

**CKAN error codes (if applicable):**

**Comment by Quartz101** [comment]
Wait nevermind, all the guis EVENTUALLY appeared... after 10 minutes.

**Comment by Quartz101** [comment]
GUI eventually appears, but gets stuck on the updating repository thing...

**Comment by ayan4m1** [comment]
Are you using any internet "security" or firewall software? I cannot reproduce your issue on multiple different Windows 10 machines. How many KSP installs do you have? Are any Steam installs? Do you have any GPOs in effect / is the machine bound to an AD server?

**Comment by politas** [comment]
You could also try manually updating to the [latest release](https://github.com/KSP-CKAN/CKAN/releases/latest)
