### ISSUE TITLE
CKAN crash after I uninstall all mods and delete all mods manually from KSP gamedata

### ISSUE THREAD

**Issue by minecraft2048** [KSP-CKAN/CKAN#1790]
**CKAN Version:** StarTram with KSP 1.1.3

**Operating System:** Xubuntu 16.04

**The issue you are experiencing:** Because I have some mod instability after upgrading to KSP 1.1.3, I've decided to clean everything by uninstalling all mods through CKAN installed mods and then delete everything in GameData except Squad. Then, when I starts CKAN through the start menu, it doesn't starts. When I starts it in terminal, this happens:

```
feanor@silmaril ~/Downloads $ mono ./ckan.exe
The following inconsistencies were found:
B9PartSwitch requires ModuleManager but nothing provides it
 * RasterPropMonitor-Core requires ModuleManager but nothing provides it
 * RasterPropMonitor requires ModuleManager but nothing provides it
 * TweakScale requires ModuleManager but nothing provides it
 * CommunityTechTree requires ModuleManager but nothing provides it
 * ProceduralParts requires ModuleManager but nothing provides it  at CKAN.SanityChecker.EnforceConsistency (IEnumerable`1 modules, IEnumerable`1 dlls) <0x415b3f50 + 0x00077> in <filename unknown>:0 
  at CKAN.Registry.CheckSanity () <0x415b3a90 + 0x000b7> in <filename unknown>:0 
  at CKAN.RegistryManager.Save (Boolean enforce_consistency, Boolean recommmends, Boolean with_versions) <0x415db000 + 0x0005f> in <filename unknown>:0 
  at CKAN.KSP.ScanGameData () <0x415cc180 + 0x0026f> in <filename unknown>:0 
  at CKAN.Main.UpdateRepo () <0x415cbbf0 + 0x0014b> in <filename unknown>:0 
  at CKAN.Main.OnLoad (System.EventArgs e) <0x41474710 + 0x00c37> in <filename unknown>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) <0x414744b0 + 0x0007f> in <filename unknown>:0 
feanor@silmaril ~/Downloads $ 
```
Of course there is no ModuleManager because I have deleted it, but I think that CKAN should launch but display this no MM found in the GUI and try to correct it instead of crashing silently

**How to recreate this issue:** 

1.  Uninstall all mods through CKAN
2. Delete everything in KSP GameData except Squad
3. Relaunch CKAN

**Comment by politas** [comment]
If you delete CKAN/registry.json as well, it ought to be ok

**Comment by minecraft2048** [comment]
Yep, deleted the entire CKAN folder( yes I know that its only registry.json, but the cache is useless anyway for 1.1.3) and it works. It will be nice however if CKAN doesn't just silently crash without any error message on screen
