### ISSUE TITLE
CKAN crash after mod install

### ISSUE THREAD

**Issue by muppet9876** [KSP-CKAN/CKAN#1792]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:**  v1.1.18.0-0-geeb9127(beta)

**Operating System:** win10 (64bit)

**The issue you are experiencing:** Crash after upgrading KAC  to v3.7.1.0 from previous version.

**How to recreate this issue:**  Happens very frequently, but not every time, one or more mods are updated/installed

**CKAN error codes (if applicable):**  Details window: http://pastebin.com/EJaBFXJz

**Comment by muppet9876** [comment]
CKAN Version: v1.1.18.0-0-geeb9127(beta)

Operating System: win10 (64bit)

The issue you are experiencing: Crash after installing  MechJeb embedded universal (career mode)

How to recreate this issue: Happens very frequently, but not every time, one or more mods are updated/installed

CKAN error codes (if applicable): Details window: http://pastebin.com/9rKNjjkD

**Comment by muppet9876** [comment]
Aha, it's not crashing on installing. I typed trans in the filter by mod name field and installed transfer window planner w/o crash. When I deleted the text in the filter field got http://pastebin.com/h29CdzU9 crash.

**Comment by politas** [comment]
There is a known bug where CKAN will crash if you try to install new mods and upgrade existing mods at the same time. Does that describe your experience?

**Comment by muppet9876** [comment]
The crash is not from installing, it's when the application tries to refresh the list of mods. It installs mods just fine, then crashes.
