### ISSUE TITLE
Unusably slow on arch with cinamon

### ISSUE THREAD

**Issue by IGBC** [KSP-CKAN/CKAN#1794]
This application is unsably slow on arch linux with the cinamon desktop environment.

**CKAN Version:** 
1.18.0-1

**Operating System:** 
Linux 4.4.13-1-MANJARO #1 SMP PREEMPT Wed Jun 8 09:21:59 UTC 2016 x86_64 GNU/Linux

**The issue you are experiencing:** 
Slow
Unstable
Crashed my desktop environment

**How to recreate this issue:** 
use it in this operating system (installed version packaged in AUR)

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Have you sourced the latest Mono from the Mono project website? Arch seems to have serious issues with Mono.
