### ISSUE TITLE
Can't install DockinPortAlignmentIndicator

### ISSUE THREAD

**Issue by mscg82** [KSP-CKAN/CKAN#1796]
I started with a fresh install of KSP and CKAN and tried to install DockinPortAlignmentIndicator but CKAN doesn't list it under any filter. I checked the registry.json file and the entries for this mod are listed correctly.
Then I checked on another installation of KSP/CKAN where DockinPortAlignmentIndicator is already installed (through CKAN) and in this case the mod is listed only under the "All" and "Installed" filters (with the check mark in the "installed" coloumn) but it doesn't show neiter in the "Compatible" nor in the "Incompatible" filter.

KSP is version 1.1.3 and CKAN is v1.18.0

**CKAN Version:** v1.18.0 

**Operating System:** Windows 7 

**The issue you are experiencing:** Unable to list and install DockinPortAlignmentIndicator 

**How to recreate this issue:** Try to search this mod in the list 

**CKAN error codes (if applicable):**

**Comment by TeddyDD** [comment]
DockinPortAlignmentIndicator depens on ModuleManager witch was remover from CKAN on @sarbian request. Read this: https://github.com/KSP-CKAN/CKAN/issues/1793

For now, your only option is to download ModuleManager.frozen and generate .ckan using netkan.exe and then install ModuleManager using generated .ckan (or install your mods manually like an animal :wink: ) This can be closed I think.

**Comment by mscg82** [comment]
Ok, I got it. Thanks for your help!

**Comment by bolandrm** [comment]
@TeddyDD  I followed your steps and I am still unable to install mods which depend on module manager (despite the fact that module manager is now shown as installed.  Do I need to do something else?

**Comment by mscg82** [comment]
@bolandrm, You can manually modify the registry.json file by adding the module manager entry. To do this, follow this steps:

1. open CKAN and refresh the mod list to get the latest metadata
2. close CKAN, locate the registry.json file and open it in a text editor (if you're on Windows, notepad will be fine but I suggest to use Notepad++)
3. after the line with this text `"available_modules": {` (line 11) paste the following snippet:
`"ModuleManager": {
			"module_version": {
				"2.6.25": {
					"abstract": "Modify KSP configs without conflict",
					"description": null,
					"kind": null,
					"author": [
						"ialdabaoth",
						"Sarbian"
					],
					"comment": null,
					"conflicts": null,
					"depends": null,
					"download": "https://ksp.sarbian.com/jenkins/job/ModuleManager/114/artifact/ModuleManager-2.6.25.zip",
					"download_size": 29232,
					"download_hash": {
						"sha1": "DD7396018AC0BD35D4E3D8483D46B20D02D49129",
						"sha256": "F8373073E5E2277E74D3B6CA63293634CBE347F952433847B361EC2682EA729A"
					},
					"identifier": "ModuleManager",
					"ksp_version": null,
					"ksp_version_max": "1.1.99",
					"ksp_version_min": "1.1.2",
					"ksp_version_strict": false,
					"license": [
						"CC-BY-SA"
					],
					"name": "Module Manager",
					"provides": null,
					"recommends": null,
					"release_status": null,
					"resources": {
						"repository": "https://github.com/sarbian/ModuleManager",
						"homepage": "http://forum.kerbalspaceprogram.com/threads/55219",
						"bugtracker": null,
						"spacedock": null
					},
					"suggests": null,
					"version": "2.6.25",
					"supports": null,
					"install": [
						{
							"file": null,
							"find": null,
							"find_regexp": "ModuleManager.*\\.dll$",
							"find_matches_files": true,
							"install_to": "GameData",
							"as": null,
							"filter": null,
							"filter_regexp": null
						}
					],
					"spec_version": "v1.16"
				}
			}
		},`
4. restart CKAN.

Remember that every time you refresh the mod list the ModuleManager entry will be removed!

**Comment by politas** [comment]
ModuleManager has been marked as 1.1.3 compatible now.
