### ISSUE TITLE
PersistentRotation update not being displayed.

### ISSUE THREAD

**Issue by MarkusA380** [KSP-CKAN/CKAN#1807]
I submitted the same issue on the NETKAN repository, nobody answered. It is urgent!

My mod - PersistentRotation - has been updated on Spaceport some days ago. CKAN still displays a very old version, wich isn't even compatible with 1.1.3! Please help me with this!

**Comment by Blu3wolf** [comment]
https://github.com/KSP-CKAN/NetKAN/issues/4295 - link to the correct issue

**Comment by politas** [comment]
See Issue in NetKAN
