### ISSUE TITLE
JsonSerializationException

### ISSUE THREAD

**Issue by paperclip** [KSP-CKAN/CKAN#1808]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version: v1.18.0-0-geeb9127 (beta)

**Operating System: Windows 10

**The issue you are experiencing:
Unhandled exception when opening CKAN, after selecting install.

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
Newtonsoft.Json.JsonSerializationException: Error converting value "https://s3-us-west-2.ama

**How to recreate this issue:
Open CKAN, select KSP 1.1.3 install

**CKAN error codes (if applicable):
Newtonsoft.Json.JsonSerializationException: Error converting value "https://s3-us-west-2.ama

**Comment by politas** [comment]
Sounds like your registry.json is corrupted. Try a "CKAN repair" on the command line. 
If that doesn't work, clearing your GameData directory, deleting registry.json, and reinstalling everything is the only remaining solution.
