### ISSUE TITLE
Installing specific mods causes them to revert to Autodetected status

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1810]
The tech specs:
CKAN: v1.18.0-0-geeb9127 (beta)
Platform: Windows 7 SP1 x64

Installing specific mods causes them to revert to Autodetected status

How to recreate this issue:
ckan.exe install TextureReplacer=v2.4.13

ckan.exe 

On the GUI refreshing the mod list, Texture replacer is listed as being autodetected.

**Comment by Blu3wolf** [comment]
This seems to apply to any mods installed via the CLI, for which a current version does not exist. Installing FinalFrontier ribbon packs has the same effect, as the ribbon packs are not available for 1.1.3 (which suggests an error in the metadata for them).

**Comment by Blu3wolf** [comment]
So, it seems as though installing old versions of mods through the command line results in them not being added to the list of installed mods through CKAN?

**Comment by politas** [comment]
Only plugins are Autodetected. No dll to find in ribbon packs.

**Comment by Blu3wolf** [comment]
The autodetection is not the issue, the issue is the fact that installing old mods through CKAN, caused CKAN to not recognise them as being installed by CKAN.

**Comment by Blu3wolf** [comment]
Determined to only occur with the GUI open, when using the CLI. Seems like the GUI being open prevents the CLI from updating the registry.json correctly.

**Comment by politas** [comment]
Covered by #706
