### ISSUE TITLE
Sort by Installed tab does not sort AD mods

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1813]
**CKAN Version:** 
v1.18.0-0-geeb9127 (beta)

**Operating System:** 
Windows 7 SP1 x64

**The issue you are experiencing:** 
On clicking the Installed tab in the CKAN GUI, mods are sorted by whether; they are installed, they are not installed but can be, or they are not installed. AD mods are sprinkled throughout without being sorted. 

**How to recreate this issue:** 
Install some mods, some manually, some through CKAN, or install Texture Replacer and then restart the GUI, as well as installing other mods (due to bug with Texture Replacer losing installed status #1810 ). Click the Installed tab in the list of mods.

**Comment by politas** [comment]
I could not reproduce this. AD mods were sorted separately.

**Comment by Blu3wolf** [comment]
That is also the case for me on 18.1. now. Cheers!
