### ISSUE TITLE
Invalid Mono Certificate?

### ISSUE THREAD

**Issue by mbottini** [KSP-CKAN/CKAN#1814]
**CKAN Version:** v1.18.0-15-g1ce214f

**Operating System:** Ubuntu 15.10

**The issue you are experiencing:** When executing `mono ckan.exe`, an error window pops up that says 

    Error in autoupdate: 
    Error getting response stream (Write: The authentication or decryption has failed.): SendFailure

As shown by previous issues, the usual solution to this is to execute `mozroots --import --ask-remove`, which always returns the following output for me:

    Downloading from 'http://mxr.mozilla.org/seamonkey/source/security/nss/lib/ckfw/builtins/certdata.txt?raw=1'...
    Importing certificates into user store...
    5 new root certificates were added to your trust store.
    Import process completed.

This does nothing to solve the problem.

So, I tried the following command: `certmgr -ssl https://api.github.com/repos/KSP-CKAN/CKAN/releases/latest/`, as it is the address that the command line complains about. This adds the following certificates:

    X.509 Certificate v3
        Issued from: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert High Assurance EV Root CA
        Issued to:   C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA
        Valid from:  10/22/2013 12:00:00 PM
        Valid until: 10/22/2028 12:00:00 PM
        *** WARNING: Certificate signature is INVALID ***

and

    X.509 Certificate v3
        Issued from: C=US, O=DigiCert Inc, OU=www.digicert.com, CN=DigiCert SHA2 High Assurance Server CA
        Issued to:   C=US, S=California, L=San Francisco, O="GitHub, Inc.", CN=*.github.com
        Valid from:  4/8/2014 12:00:00 AM
         Valid until: 4/12/2017 12:00:00 PM

**How to recreate this issue:** Delete `~/.config/.mono/certs/` and try running CKAN. I'm still not sure whether this is a CKAN bug, a Mono bug, or just my own machine being stupid.

**Comment by allista** [comment]
I have the same issue with netkan.exe; but adding these two certificates (which are not repository-specific, just GitHub certs) doesn't fix things.

**Comment by techman83** [comment]
Oh gosh, Ubuntu/Debian being on 3.2.8 for so long is going to cause a lot of issues Kwoth/NadekoBot#354

We might have to suggest people upgrade mono. On ubuntu and derivatives it's pretty trivial using the official mono project PPAs.

**Comment by mbottini** [comment]
> We might have to suggest people upgrade mono.

Thanks, that did it. The wiki even says that you have to get Mono from the Mono folks and not from the default repository. Chalk one up to "can't follow basic instructions."
