### ISSUE TITLE
Linux build help

### ISSUE THREAD

**Issue by RedstoneGeek223** [KSP-CKAN/CKAN#1815]
I want to use this wonderful tool but no info was ever provided for building on linux

**CKAN Version:** 1.18.0

**Operating System:** Linux: Kubuntu

**The issue you are experiencing:** Inability to build

**How to recreate this issue:** Unknown

**CKAN error codes (if applicable):** N/A

**Comment by politas** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/Building-CKAN-on-Linux

**Comment by RedstoneGeek223** [comment]
got this
`XBuild Engine Version 12.0`
`Mono, Version 4.2.1.0`
`Copyright (C) 2005-2013 Various Mono authors`
`                Configuration: Debug Platform: AnyCPU`
`/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved`
`Configuration: Debug Platform: AnyCPU`
`/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved`
`Checking if nunit-console is available...`
`Found nunit-console with CLR version 4.`
`Checking if nunit-console4 is available...`
`NUnit-Console version 2.6.4.0`
`Copyright (C) 2002-2012 Charlie Poole.`
`Copyright (C) 2002-2004 James W. Newkirk, Michael C. Two, Alexei A. Vorontsov.`
`Copyright (C) 2000-2002 Philip Craig.`
`All Rights Reserved.`
``
`Runtime Environment - `
`   OS Version: Unix 4.4.0.28`
`  CLR Version: 4.0.30319.17020 ( Mono 4.0 ( 4.2.1 (Debian 4.2.1.102+dfsg2-7ubuntu4) ) )`
``
`ProcessModel: Default    DomainUsage: Single`
`Execution Runtime: mono-4.0`
`Unhandled Exception:`
`System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/plasma-blast/CKAN/Tests/bin/Debug/CKAN.Tests.dll".`
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0xb555c550 + 0x0021e> in` `<filename unknown>:0 `
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share, Int32 bufferSize, Boolean isAsync, Boolean anonymous) <0xb555c4e0 + 0x0005c> in` `<filename unknown>:0 `
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access)` `<0xb555c090 + 0x0005c> in <filename unknown>:0 `
`  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor` `(string,System.IO.FileMode,System.IO.FileAccess)`
`  at NUnit.Core.AssemblyReader.CalcHeaderOffsets () <0xb526d1e8 + 0x00043> in <filename` `unknown>:0 `
`  at NUnit.Core.AssemblyReader..ctor (System.String assemblyPath) <0xb526d160 + 0x0006b> in` `<filename unknown>:0` 
`  at NUnit.Util.RuntimeFrameworkSelector.SelectRuntimeFramework (NUnit.Core.TestPackage` `package) <0xb526c7d0 + 0x00263> in <filename unknown>:0 `
`  at NUnit.Util.DefaultTestRunnerFactory.GetTargetProcessModel (NUnit.Core.TestPackage` `package) <0xb526c6e0 + 0x00027> in <filename unknown>:0 `
`  at NUnit.Util.DefaultTestRunnerFactory.MakeTestRunner (NUnit.Core.TestPackage package)` `<0xb526c5d0 + 0x0001b> in <filename unknown>:0 `
`  at NUnit.ConsoleRunner.ConsoleUi.Execute (NUnit.ConsoleRunner.ConsoleOptions options)` `<0xb526abd0 + 0x00491> in <filename unknown>:0  `
`  at NUnit.ConsoleRunner.Runner.Main (System.String[] args) <0xb729c460 + 0x00757> in` `<filename unknown>:0                              `
`WARNING: The runtime version supported by this application is` `unavailable.                                                              `
`Using default runtime: v4.0.30319                                `                                                                       
`ERROR: Failed to load assembly Cmdline/bin/Debug`
`/CmdLine.exe                                                                            `
`System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/plasma-blast/CKAN/Cmdline/bin/Debug/CmdLine.exe".        `
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0xb555c550 + 0x0021e> in` `<filename unknown>:0`                                                                
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share) <0xb555c100 + 0x00051> in <filename unknown>:0` 
`  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor` `(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)`
`  at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, FileMode mode,` `FileAccess access, FileShare share) <0xb701d5f8 + 0x0007b> in <filename unknown>:0` 
`  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName,` `Mono.Cecil.ReaderParameters parameters) <0xb701d550 + 0x00033> in <filename unknown>:0` 
`  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName,` `Mono.Cecil.ReaderParameters parameters) <0xb701d510 + 0x00017> in <filename unknown>:0` 
`  at ILRepacking.ILRepack.ReadInputAssemblies () <0xb701afc8 + 0x0036f> in <filename` `unknown>:0` 
`WARNING: The runtime version supported by this application is unavailable.`
`Using default runtime: v4.0.30319`
`ERROR: Failed to load assembly Netkan/bin/Debug/NetKAN.exe`
`System.IO.DirectoryNotFoundException: Could not find a part of the path "/home/plasma-blast/CKAN/Netkan/bin/Debug/NetKAN.exe".`
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0xb555c550 + 0x0021e> in` `<filename unknown>:0 `
`  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare` `share) <0xb555c100 + 0x00051> in <filename unknown>:0 `
`  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor` `(string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare)`
`  at Mono.Cecil.ModuleDefinition.GetFileStream (System.String fileName, FileMode mode,` `FileAccess access, FileShare share) <0xb7075548 + 0x0007b> in <filename unknown>:0` 
`  at Mono.Cecil.ModuleDefinition.ReadModule (System.String fileName,` `Mono.Cecil.ReaderParameters parameters) <0xb70754a0 + 0x00033> in <filename unknown>:0` 
`  at Mono.Cecil.AssemblyDefinition.ReadAssembly (System.String fileName,` `Mono.Cecil.ReaderParameters parameters) <0xb7075460 + 0x00017> in <filename unknown>:0` 
`  at ILRepacking.ILRepack.ReadInputAssemblies () <0xb7072f18 + 0x0036f> in <filename` `unknown>:0 `

**Comment by RedstoneGeek223** [comment]
got this error
`bin/build`
`XBuild Engine Version 12.0`
`Mono, Version 4.2.1.0`
`Copyright (C) 2005-2013 Various Mono authors`
`                Configuration: Debug Platform: AnyCPU`
`/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved`
`Configuration: Debug Platform: AnyCPU`
`/usr/lib/mono/4.5/Microsoft.Common.targets:  warning : Reference 'Microsoft.CSharp' not resolved`
`"xbuild" unexpectedly returned exit value 1 at (eval 8) line 12.`
` at bin/build line 2177`
`Makefile:8: recipe for target 'build' failed`
`make: *** [build] Error 1`

**Comment by mgsdk** [comment]
I am not running Ubuntu or a derivative thereof, but on Arch I am able to build the current git repo with both Mono 4.2.1.0 and Mono 4.4.0.0. My guess is that you're missing a package, but I am not familiar enough with Ubuntu/Debian to know which one to suggest.

**Comment by politas** [comment]
I would suggest following the instructions for getting the latest Mono from [this page](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu-14.04)
