### ISSUE TITLE
Yes/No dialog window is not visible whole 

### ISSUE THREAD

**Issue by DELTA129** [KSP-CKAN/CKAN#1818]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:v1.18.0** 

**Operating System: Windows 8 ** 

The issue you are experiencing: Whenever a yes/no dialog window opens, the yes/no buttons are out of the box as seen in this picture: 
http://i.imgur.com/Qsd1UhA.jpg

**How to recreate this issue: I'm not sure, it happens each time the windows pops up (on my pc at least)** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Do you have any system wide settings related to font size or other screen magnification? What is your screen resolution set to?

**Comment by ayan4m1** [comment]
See step 4 of [this guide](http://www.sevenforums.com/tutorials/443-dpi-display-size-settings-change.html) - if it's set to anything other than 100%, that would be the likely cause.
