### ISSUE TITLE
Error when downloading mods: Conenction was closed unexpectedly

### ISSUE THREAD

**Issue by DELTA129** [KSP-CKAN/CKAN#1819]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version: v1.18.0** 

**Operating System: Windows 8.1** 

**The issue you are experiencing: Sometimes when I'm downloading a mod it fails and gives the below message** 

**How to recreate this issue: I don't know. It doesn't happen on a specific mod, instead it happens around 5% of times on any mod that is being downloaded** 

**CKAN error codes (if applicable):Failed to download "https://github.com/Starwaster/DeadlyReentry/releases/download/v7.4.6/DeadlyReentry_7.4.6.zip" - error: The request was aborted: The connection was closed unexpectedly. **

**Comment by trakos** [comment]
Is it always a github URL?

**Comment by ayan4m1** [comment]
That [URL](https://github.com/Starwaster/DeadlyReentry/releases/download/v7.4.6/DeadlyReentry_7.4.6.zip) gives me a 404 in a browser at present.

Are you using any firewall or "internet security" software? This looks like something down the line in your network stack is killing the connection off based on protocol.

**Comment by politas** [comment]
Resolved by KSP-CKAN/CKAN-meta#1206
