### ISSUE TITLE
KSP Version Not Found

### ISSUE THREAD

**Issue by sparkybear** [KSP-CKAN/CKAN#1820]
**CKAN Version:** 
1.16.1

**Operating System:** 
Windows 7 x64

**The issue you are experiencing:** 
 http://imgur.com/a/O49vf

**How to recreate this issue:** 
Unsure. CKAN was working this morning. No changes to KSP directory or other structures were made. 
Now when attempting to start CKAN throws the error. This occurs after doing a clean CKAN installation as well.

The first section of the readme.txt and start of the changelog from KSPDir has been copied below:

> `*******************************************
>         __   ___  ______      ______
>       /  /  /  / /  __  \   /   _   \
>      /  / /  /  /  /  |_|  /   / |  |
>     /  //  /   |  |___    /   /_/  /
>    /     /     \___   \  /   ____ /
>   /  /|  |   ___   \  | /   /
>  /  / |  |   \  \_/  / /   /
> /__/  |__|    \_____/ /___/
> 
> *******************************************
> (I'm terrible at ASCII art :P)
> 
> Thank you for downloading the Kerbal Space Program!
> 
> Version 1.1.3
> 
> ====================================================================================================
> Installation / Updating:
> 
> Zip Package:
> * Unzip the contents of this package onto a directory of your choice (ex. C:/Games/KSP)
> * If you plan to overwrite a previous version of KSP with this one, please delete the contents of the folder before unzipping.
> 
> Windows Installer:
> * Run the installer .msi file once it finishes downloading, follow the instructions it presents.
> 

> 
> ChangeLog:
> =================================== v1.1.3 ============================================================
> 
> Editor:
> * Fixed game crashing during deletion of parts under certain conditions.
> * Fixed Gizmos buttons not properly highlighting after loading a craft.
> * Fixed Fuel tank Part Action Window sliders to dynamically update symmetry partners when adjusted in editor.
> * Fixed frozen parts showing up in front of the main vessel.
> * Fixed fairings being see-through when a part inside or behind is highlighted.
> * Fixed certain fairing configurations causing inputlocks.

**CKAN error codes (if applicable):** 
Could not find KSP Directory.

**Comment by politas** [comment]
Where is your KSP game installation, and where have you placed ckan.exe? "Cannot find KSP Directory" is not a failure to find the KSP version, it's a complete failure to find KSP at all. Can you try running `ckan.exe ksp list` from a command prompt?

**Comment by sparkybear** [comment]
It's installed in the default location through steam. There were no changes
to the installation path. CKAN worked in the morning, and has been working
fine, other than a few de listings, since the latest release., I didn't
restart or have any crashes, now this error is thrown every time I try to
open it. I've tried copying KSP to another folder, removing the CKAN
folder, and downloading CKAN again but no luck.

Yes, it's running as admin and Is unblocked on my machine.

**Comment by sparkybear** [comment]
Running `ksp list `shows the default steam installation along with the secondary installation i made when trying to fix the problem.

CKAN.exe is located on a separate hard drive, though that's never been a problem. When moving it to one of the KSP installation folders, the issue persists.

**Comment by Heliosmaster** [comment]
Getting more or less the same issue with OSX. "Could not find KSP version in readme.txt". 

Nothing has changed in the system. I used it, played some KSP, quit it to install a few other mods and it stopped working altogether.

**Comment by Heliosmaster** [comment]
Nevermind, I killed my CKAN folder and any KSP folders in the same dir where ckan.exe was found, and then it worked again.

**Comment by SneakyGunz** [comment]
A bit late to the discussion here. But this was just happening to me...

I put the ckan exe into my steam ksp folder and created a shortcut to ckan on the desktop. All is working fine now. Hope this helps someone.
