### ISSUE TITLE
Update mods button not working when filter does not include compatible mods

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1821]
Very simple to reproduce, install an old version of a mod, then set the filter in the GUI to incompatible, and click the update mods button. No mods are selected to be updated.

0.18.0 CKAN
Windows 7 SP1 x64

**Comment by politas** [comment]
I always thought that was the point of the filters, that you're only working on the visible mods.

**Comment by Blu3wolf** [comment]
Well, the update mods button is the GUI equivalent of ckan upgrade --all, isnt it? It fails with a specific filter setting. If that is intentional, then it was not communicated well with the UI design. I guess this can be closed then.

**Comment by politas** [comment]
I think users who used the button expecting it to only work on visible mods would have a bigger justification for being annoyed.
