### ISSUE TITLE
CKAN Deadly Reentry Continued/USI Tools error

### ISSUE THREAD

**Issue by baboca** [KSP-CKAN/CKAN#1822]
CKAN just cant download Deadly Reentry Continued or USI tools, it just gets an error that says the connection was interrupted,i can access both sites and download it manually but because of this i cant download other mods such as Karbonite because it requires USI tools and it dosent detect the one i downloaded.

CKAN v1.18.0-0-geeb9127 (beta)
KSP 1.1.2.1260

Windows 10

Probably outdated download link in CKAN

Add USI tools or DRC and click apply changes, at the end it will stop and bring up 2 separated error messages one by one

Sadly CKAN dosent generate an error code for this

**Comment by politas** [comment]
Deadly Reentry should now install 7.4.5.1 on KSP 1.1.2, but RoverDude has removed all old releases of USITools from GitHub. He does not support any old releases of his mods on old versions of KSP, and has found the only way to prevent users asking him questions about them is to make them unavailable.
