### ISSUE TITLE
Failed to connect to repository

### ISSUE THREAD

**Issue by Schnobs** [KSP-CKAN/CKAN#1823]
Sorry the bad title; it appears the root cause is that CKAN can't determine what version of KSP I'm running.

**CKAN Version:**  v1.18.0

**Operating System:**  Linux (Debian)

1) Unpack KSP 2) d/l ckan into KSP folder, 3) run ckan

On the first start, I get: "9431 [1] ERROR CKAN.ErrorDialog (null) - Failed to connect to repository. Exception: An exception was thrown by the type initializer for CKAN.Versioning.KspVersionRange" on the command line and similar text in a window; after the error window is dismissed,, the CKAN main window remains busy/unresponsive, with the progress bar indicating busy-ness.

Subsequent starts yield "exception inside UnhandledException handler: The object was used after being disposed." on the command line, apparently in high frequency (filling my terminal's backlog in a matter of moments).

Removing ksp_dir/CKAN gets me back to "first start".

Removing ~/.mono/registry/CurrentUser/software/ckan has no obvious effect.

Not sure where CKAN gets the KSP version... readme.txt is present and says "Version 1.1.3".

I can download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz nicely using wget or curl -L. 

Rewriting the URL in registry.json to use http instead of https, I get 

"System.TypeInitializationException: An exception was thrown by the type initializer for CKAN.Versioning.KspVersionRange ---> System.TypeInitializationException: An exception was thrown by the type initializer for CKAN.Versioning.KspVersionBound ---> System.NullReferenceException: Object reference not set to an instance of an object  at System.String.FormatHelper (System.Text.StringBuilder result, IFormatProvider provider, System.String format, System.Object[] args) [0x00000] in <filename unknown>:0 " 

(plus several more lines), then CKAN exits.

**Comment by Blu3wolf** [comment]
what version of mono?

**Comment by Schnobs** [comment]
3.2.8

**Comment by Schnobs** [comment]
This apparently was a duplicate of 1791 / 1784.
Problem no longer occurs with CKAN 1.18.1.
