### ISSUE TITLE
CLI - suggestions opt-out and identifier on confirmation prompt

### ISSUE THREAD

**Issue by draeath** [KSP-CKAN/CKAN#1827]
When you install a mod that has suggestions in the GUI, you are presented with a screen of any such mods and may elect whether to install them or not. In contrast, when you try to install such a mod via the CLI, the suggestions are pulled in with no mechanism to decline these (that I can see).

As the CKAN CLI seems designed to be minimally interactive, prompting is probably out - but it would be nice if it was to indicate which mods were suggestions vs dependencies at the confirmation prompt, and if there was some additional parameter you could supply to exclude them.

Additionally, the confirmation prompt would be a little more helpful if it also indicated the mod identifier, in addition to the title.

Example mockup:

```
$ ./ckan.exe install RSSTextures4096 RealSolarSystem RP-0 KerbalConstructionTime-RP-0-Config
About to install...

 * [RSSTextures4096] Real Solar System Textures - 4096 x 2048 v10.4
 * [RealSolarSytem] Real Solar System v11.4.0(cached)
 * [RP-0] Realistic Progression Zero v0.51(cached)
 * [KerbalConstructionTime-RP-0-Config] Kerbal Construction Time RP-0 Config v0.36(cached)
 * [MechJeb2] MechJeb 2 2.5.8.0(cached,suggested)

Continue? [Y/n] n
Installation canceled at user request.

$ ./ckan.exe install --exclude=MechJeb2 RSSTextures4096 RealSolarSystem RP-0 KerbalConstructionTime-RP-0-Config
About to install...

 * [RSSTextures4096] Real Solar System Textures - 4096 x 2048 v10.4
 * [RealSolarSytem] Real Solar System v11.4.0(cached)
 * [RP-0] Realistic Progression Zero v0.51(cached)
 * [KerbalConstructionTime-RP-0-Config] Kerbal Construction Time RP-0 Config v0.36(cached)

Excluded suggestions...
 * [MechJeb2] MechJeb 2 2.5.8.0(cached,suggested)

Continue? [Y/n] y
... magic happens ...
```

**Comment by HebaruSan** [comment]
Cmdline already prompts when there are multiple "provides" and for overall confirmation, so I don't think it's "out" for suggests/recommends. Closing in favor of #965, which would be a nicer solution with less typing of identifiers.
