### ISSUE TITLE
installation error Apple OSX 10.11.5 + mono 4.4.0

### ISSUE THREAD

**Issue by 9three** [KSP-CKAN/CKAN#1830]
**CKAN Version:** 
not sure... the latest one from the /releases page

**Operating System:** 
Apple OSX 10.11.5

**The issue you are experiencing:** 
353033 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.Security.SecurityException: No access to the given key ---> System.UnauthorizedAccessException: Access to the path "/Users/felipe/.mono" is denied.

**How to recreate this issue:** 
typing in mono ckan.exe for the initial install... the process begins, and after a few minutes i get the error.... i checked the version of mono being run, and its 4.4.0 ... i had read some things about version incompatibilties with El Capitan... not sure tho. and yes.. my name is also Felipe.... i was getting help from LinuxGuruGamer on twitch chat, but couldnt get it running... thanks in advance for any assistance. will bookmark this and follow up. find me on twitch if you know whats going on here. 9three

**CKAN error codes (if applicable):** 
353033 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.Security.SecurityException: No access to the given key ---> System.UnauthorizedAccessException: Access to the path "/Users/felipe/.mono" is denied.

**Comment by politas** [comment]
Did you run the `mozroots --import --ask-remove` command as mentioned in the Release notes?

**Comment by 9three** [comment]
i did not.... um... will look now.

**Comment by 9three** [comment]
ok, ran it, got the confirmation that it was updated. ran the install command... and still got the security exception.

**Comment by politas** [comment]
Is "felipe" your local userid? Does Users/felipe/.mono exist?

**Comment by 9three** [comment]
![screen shot 2016-07-16 at 12 25 08 am](https://cloud.githubusercontent.com/assets/20469046/16892739/d0583a24-4aeb-11e6-868c-aa8ac4ecd264.png)
![screen shot 2016-07-16 at 12 23 40 am](https://cloud.githubusercontent.com/assets/20469046/16892741/d06141a0-4aeb-11e6-8ed4-9f2f4bf2f9f5.png)
![screen shot 2016-07-16 at 12 22 33 am](https://cloud.githubusercontent.com/assets/20469046/16892740/d05e379e-4aeb-11e6-99fd-7d992dddb1db.png)

**Comment by politas** [comment]
That's the mono process. I'm asking if you have a directory called ".mono" in your home directory "/Users/felipe", and what i't permissions are. eg, on my system:

    ~$ ls -al | grep .mono
    drwxrwxr-x   3 myuser mygroup     4096 Dec 21  2014 .mono

**Comment by 9three** [comment]
ok !!! now we are getting somewhere... thanks politas... you made me look at the /felipe folder.... it was locked.. so i unlocked it and it seemed to have worked. 
![screen shot 2016-07-16 at 12 29 45 am](https://cloud.githubusercontent.com/assets/20469046/16892770/931cf3e2-4aec-11e6-99f7-f44325f02e48.png)

**Comment by 9three** [comment]
next problem is... selecting the KSP folder.. it will only let me select desktop items... it wont let me go into the KSP folder which is in the Applications folder for all users....

**Comment by 9three** [comment]
i cannot select the file where KSP is.... 
![screen shot 2016-07-16 at 12 32 40 am](https://cloud.githubusercontent.com/assets/20469046/16892776/df7f8d3a-4aec-11e6-8cca-5e99b1888de4.png)

**Comment by politas** [comment]
You may need to create a link from your Personal directory to the KSP install folder

**Comment by 9three** [comment]
link ? like an "alias" ?

**Comment by politas** [comment]
Maybe? I'm not at all familiar with MacOSX' terminology

**Comment by 9three** [comment]
so, its looks like OSX creates an /applications folder, that all users (logins/accounts) can use, and is not user specific... but within the users account there is also another /applications folder... which in my case, is completely empty, except for one file for Chrome.... so i will attempt to copy all the apps (programs) from the base /applications folder which is path (macintosh HD/applications) to the user specific folder which is path (macintosh HD/users/felipe/applications/) ... lets see if that works...

thanks for the help though Politas, you have me on the right track....

**Comment by 9three** [comment]
https://www.engadget.com/2010/12/03/mac-101-the-two-applications-folders/

**Comment by politas** [comment]
I don't suppose you'd be interested in writing up a quick explanation of how to fix this issue in [our Wiki](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-OSX)? I know the problem has come up before.

**Comment by 9three** [comment]
consider it done.

**Comment by 9three** [comment]
as long as you can tell me why mono can only see the "user" applications folder, and not the "shared" applications folder in mac OSX....

**Comment by 9three** [comment]
or is it ckan that cannot see the main folder .

**Comment by 9three** [comment]
got it up and running ! thanks again Politas. will write something up in the wiki here shortly !!
![screen shot 2016-07-16 at 11 32 03 am](https://cloud.githubusercontent.com/assets/20469046/16895566/039e1d06-4b49-11e6-95a7-bef7659d3303.png)

**Comment by 9three** [comment]
ok, so correct me if im wrong... the only way to get ckan started is to go into terminal and enter "mono /applications/ckan.exe"  ???? i cannot find mono anywhere in my applications folders.

**Comment by 9three** [comment]
ok, some additional info here. once ckan has been started, i get the following errors. they are not critical, but they are present.

1830 [1] ERROR CKAN.URLHandlers (null) - There was an error while registering the URL handler for ckan:// - Could not find a part of the path "/Users/felipe/.local/share/applications/mimeapps.list".
1843 [1] ERROR CKAN.URLHandlers (null) -   at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, Boolean anonymous, FileOptions options) <0x7c25f00 + 0x0021d> in <filename unknown>:0 
  at System.IO.FileStream..ctor (System.String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, System.String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost) <0x7c25e30 + 0x0004f> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.FileStream:.ctor (string,System.IO.FileMode,System.IO.FileAccess,System.IO.FileShare,int,System.IO.FileOptions,string,bool,bool,bool)
  at System.IO.StreamWriter.CreateFile (System.String path, Boolean append, Boolean checkHost) <0x7a6cb30 + 0x000a4> in <filename unknown>:0 
  at System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize, Boolean checkHost) <0x7a6c7b0 + 0x0006c> in <filename unknown>:0 
  at System.IO.StreamWriter..ctor (System.String path, Boolean append, System.Text.Encoding encoding, Int32 bufferSize) <0x7a6c760 + 0x00042> in <filename unknown>:0 
  at System.IO.StreamWriter..ctor (System.String path) <0x7a6c670 + 0x0003d> in <filename unknown>:0 
  at (wrapper remoting-invoke-with-check) System.IO.StreamWriter:.ctor (string)
  at System.IO.File.WriteAllLines (System.String path, System.String[] contents) <0x7c23f90 + 0x0003b> in <filename unknown>:0 
  at CKAN.URLHandlers.RegisterURLHandler_Linux () <0x11f6b210 + 0x00137> in <filename unknown>:0 
  at CKAN.URLHandlers.RegisterURLHandler (CKAN.Configuration config, IUser user) <0x11f6af20 + 0x00027> in <filename unknown>:0

**Comment by 9three** [comment]
![screen-shot-2016-07-16-at-12 29](https://cloud.githubusercontent.com/assets/20469046/16895885/7b30c1b4-4b50-11e6-859b-937c79923e24.png)
