### ISSUE TITLE
Mod4 causes segfault when pressed

### ISSUE THREAD

**Issue by GinjaNinja32** [KSP-CKAN/CKAN#1831]
**CKAN Version:** v1.18.1-0-g0d2c4f0 (beta)

**Operating System:** Arch Linux x64

**The issue you are experiencing:** When the Mod4 (aka Super/'Windows key') button is pressed, CKAN segfaults. Mod4 is my i3 (WM) modifier key, which means I essentially can't interact with i3 while CKAN is focused.

**How to recreate this issue:** Launch CKAN, press Mod4.

**CKAN error codes (if applicable):** unknown

Stacktrace etc. from stderr: https://gn32.uk/f/ckan.txt

**Comment by politas** [comment]
Can't reproduce this on Ubuntu with the default Unity desktop

**Comment by politas** [comment]
Sorry, didn't mean to close.

**Comment by Postremus** [comment]
Can't reproduce on Linux Mint 18

2016-07-19 11:35 GMT+02:00 Myk <notifications@github.com>:

**Comment by politas** [comment]
CKAN does not appear to pay any attention to Mod4 normally. On Ubuntu default WM, Mod4 opens the launcher and CKAN continues to operate normally. What is your Mono version?

**Comment by politas** [comment]
Well, I installed i3, set it to use the Mod4 (Windows) key as the meta key, and still couldn't reproduce this. I know that Arch Linux does some odd things with Mono generally, so I would suspect that is where you need to look.

**Comment by GinjaNinja32** [comment]
After testing in a minimal executable, this is definitely a Mono issue, though I'm not sure what exactly went wrong; it affects Keepass and a minimal test application too, with identical stack traces.

https://bugzilla.xamarin.com/show_bug.cgi?id=42676

**Comment by Lartza** [comment]
I can't reproduce this with g602da4b or with Keepass on Arch 64-bit and Budgie Desktop as my DE

**Comment by agwilt** [comment]
I'm also using Arch x64 (with Cinnamon), and I'm having the same problem.

**Comment by politas** [comment]
Have you sourced Mono from mono-project.org?
