### ISSUE TITLE
USI tools override USI Core

### ISSUE THREAD

**Issue by hexdragoon** [KSP-CKAN/CKAN#1834]
CKAN version:
 v1.18.1 (StarTrammier)
OS:
Windows 10
Issue:
USI Tools is trying to override USI Core
How to recreate:
Download both USI Tools and USI Core
Error:
File           : GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USITools 0.7.4.0
Owning Mod     : USI-Core
CKAN Version   : v1.18.1-0-g0d2c4f0 (beta)

**Comment by spirritus** [comment]
GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USI-Core 0.2.4.0
Owning Mod     : USITools
CKAN Version   : v1.18.1-0-g0d2c4f0 (beta)

**Comment by brandonson** [comment]
FYI, it installs now, but seems I mixed up paths in my PR to the USI CKAN repo and left the files a level too deep..  To fix, you have to go to `GameData\UmbraSpaceIndustries\UmbraSpaceIndustries` and move all files in there to `GameData\UmbraSpaceIndustries` and at that point it works for me.  That said, new PR in the works, so waiting would also help, hopefully.

**Comment by Lofwyrger** [comment]
Same Error here.

**Comment by politas** [comment]
Resolved

**Comment by muppet9876** [comment]
resolved? Nope.

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USITools 0.7.4.0
Owning Mod     : USI-Core
CKAN Version   : v1.18.1-0-g0d2c4f0 (beta)

tried ckan update. No joy.

**Comment by politas** [comment]
@muppet9876 , can you try uninstalling those two, refreshing, closing and reopening ckan, then installing again?

**Comment by MidnightLightning** [comment]
Uninstalling and reinstalling USItools (and Karbonite, which depends on them) fixed this issue for me.

**Comment by muppet9876** [comment]
sry for the slow reply, uninstalling USI Tools and its dependencies allowed me to update USI Core, reinstalling USI Tools worked fine as you said. Ty.
 

    On Sunday, 7 August 2016, 3:26, Brooks Boyd <notifications@github.com> wrote:
 

 Uninstalling and reinstalling USItools (and Karbonite, which depends on them) fixed this issue for me.—
