### ISSUE TITLE
Wrong error message

### ISSUE THREAD

**Issue by spirritus** [KSP-CKAN/CKAN#1835]
if a file is owned by two mods a conflict error appears, as is expectd. However the message points to the wrong URL and has some whitespace issues. 
Correction, after copy and pasting he message in this input window the whitespaces in the message are fine - so it is a display issue with linebreaks  in CKAN (v1.18.1-0-g0d2c4f0)

======== pasted message ========
Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USI-Core 0.2.4.0
Owning Mod     : USITools
CKAN Version   : v1.18.1-0-g0d2c4f0 (beta)

Your GameData has been returned to its original state.

======== message as displayed in CKAN ========
Oh no! We tried to overwrite a file owned by another mod! Please try a `ckan update` and try again. If this problem re-occurs, then it maybe a packaging bug. Please report it at: https://github.com/KSP-CKAN/CKAN-meta/issues/newPlease including the following information in your report:File           :GameData/UmbraSpaceIndustries/FX/bubble.pngInstalling Mod : USI-Core 0.2.4.0Owning Mod     : USIToolsCKAN Version   : v1.18.1-0-g0d2c4f0 (beta)
Your GameData has been returned to its original state.

**Comment by politas** [comment]
That particular message is 100% accurate. But it should be fixed now,

**Comment by muppet9876** [comment]
https://github.com/KSP-CKAN/CKAN-meta/issues/new gives a 404 in browser.

Current correct link is this to here?

https://github.com/KSP-CKAN/CKAN/issues

**Comment by politas** [comment]
Ah, thanks. We should definitely update that messgae
