### ISSUE TITLE
Interrupted CKAN Update

### ISSUE THREAD

**Issue by excitedfermion** [KSP-CKAN/CKAN#1839]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
v1.18.1-0-g0d2c4f0 (beta)

**Operating System:** 
Windows 7

**The issue you are experiencing:** 
Cannot apply KSP mod update.

**How to recreate this issue:** 
Faulty internet connection during update of CKAN, which fails and loads last working version. 
last CKAN version tries to update mod and internet connection fails partway through.
Restart CKAN with good internet connection.
Update of CKAN completes successfully, error occurs during update of mod.

**CKAN error codes (if applicable):** 
File           : GameData/UmbraSpaceIndustries/FX/bubble.png
Installing Mod : USITools 0.7.4.0
Owning Mod     : USI-Core
CKAN Version   : v1.18.1-0-g0d2c4f0 (beta)

**Comment by politas** [comment]
Uninstall those two mods, refresh, restart CKAN and re-install and it should be fine. There was a problem with the metadata for a day or so, and it sounds like you were working from that data.

Thanks for your report!

**Comment by excitedfermion** [comment]
Thanks, I actually stumbled upon that solution myself. Good to know that it was just a metadata issue. I wanted to report it in case it was a deeper issue / undiscovered corner case.
