### ISSUE TITLE
uninstall mod is impossible when incompatible filter is selected.

### ISSUE THREAD

**Issue by rem02** [KSP-CKAN/CKAN#1842]
**CKAN Version:**
v1.18.1-0-g0d2c4f0

**Operating System:**
Windows 10

**How to recreate this issue:**
When I filter the list of mods with the incompatible option, I uncheck a mod for the uninstall but the button "Apply Changes" is not activated.

**Comment by iaz3** [comment]
I've had this ***bug*** too.

It makes it a huge pain when KSP updates and i cant remove mods that havent updated yet.

**Comment by politas** [comment]
Agreed, it's a bug. Should be able to uninstall mods from the "Installed" or "All" filters, though.

**Comment by ayan4m1** [comment]
Sorry, right I misunderstood what was being described. The offending code is https://github.com/KSP-CKAN/CKAN/blob/master/GUI/Main.cs#L701

**Comment by HebaruSan** [comment]
The fixing PR was reverted in #2150; re-opening.
