### ISSUE TITLE
GUI should make conflicts clear

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1843]
If a mod is selected to be installed, which conflicts with existing installed mods, the install mods button is 'greyed out' and cannot be clicked. If the mod selected is the only one selected, this in particular has the appearance that the selection has not been acknowledged by the program. 

One possible work around for this, would be to change either the background or foreground color of the list elements for mods which are incompatible with currently installed mods, or to mark them in some comparable way, such as italicisng the list text.

**Comment by politas** [comment]
They are currently marked with a red background. @linuxgurugamer came up with a nice suggestion for a "Conflicts" filter that I like the sound of, if it can be done.

**Comment by Blu3wolf** [comment]
A conflicts filter sounds nice, or possibly a tab that appears when conflicts exist?

**Comment by HebaruSan** [comment]
I think we can count this as fixed by #2442, since there's now an explicit text description in the status bar for conflicts.

![conflict in status bar](https://user-images.githubusercontent.com/1559108/39786503-81dc4c0a-52e6-11e8-9bea-4e2d5a13d927.png)
