### ISSUE TITLE
Option to download mods without installing them

### ISSUE THREAD

**Issue by jcc10** [KSP-CKAN/CKAN#1847]
It would be nice if you could have mods downloaded locally without having them activated so you can activate the mods later on (while offline) through ckan. (or deactivate them without deleting)

This is mostly for offline use. But it could also be usefully for people with limited bandwidth.

**Comment by politas** [comment]
If you switch to the "Contents" tab, you can do just that.

**Comment by jcc10** [comment]
Let me re-phrase that then: A checkbox on the main menu to show if it is downloaded. (Also I have had issues with mods being installed but not in the cache. Which kind of ruins the idea of switching mods on the fly while offline.)

**Comment by jcc10** [comment]
A solution would be having two settings in the menu.
When you click to install a mod it makes the downloaded checkbox get a box within it. (some menus do that, It's the best UI Idea I could come up with) This means that the mod is downloaded but will be deleted upon un-install.

Clicking the check box will switch it between two settings: Default (Empty = Uninstalled, Box = Installed) and locally mirrored (you always have a copy available of whatever version you last downloaded)

Would that be acceptable?

**Comment by ayan4m1** [comment]
There is a "Cached" filter type that only shows cached modules. The Installed checkbox there is a way to tell if it's installed.

My opinion - no code change is needed here.

**Comment by jcc10** [comment]
How about a filter for not cached? As stated above I have several mods (that are fully up to date) that I (somehow) do not have in my cache, knowing which ones quickly and downloading them would be nice.

Even just a additional checkbox for cached or not would be nice. (also that way the downloads can be done as a batch job not individually.)

**Comment by politas** [comment]
There could be multiple cached versions of a mod with the installed and latest releases each being either cached or not cached. That's a lot of information to squeeze into a single flag. What exactly are you wanting to know? That there is a cached copy of an installed mod, a cached copy of the latest release of a mod, or a cached copy of the latest compatible release of a mod?

Batching downloads would strike the same problems with timeouts that we get with installing large sets of mods.

**Comment by zatricky** [comment]
Is there a way to download to the cache (without installing) from CLI?

**Comment by HebaruSan** [comment]
@zatricky, no.

**Comment by HebaruSan** [comment]
> How about a filter for not cached?

Added in #2930.

**Comment by HebaruSan** [comment]
As previously stated by various participants, all of this functionality exists (downloading, purging, filtering by cached or not-cached). The remaining requests are about _how_ the UI is implemented, but unfortunately no motivation in terms of use cases is provided, which is needed to justify UI changes.

If this is still needed, please let us know _why_, what is it that you're trying to do that is impossible or difficult or awkward in the current UI, and we can re-open it.
