### ISSUE TITLE
Allow for "forced install" of incompatible mods

### ISSUE THREAD

**Issue by embix** [KSP-CKAN/CKAN#1855]
Every now and then a new KSP version comes out and mods cannot be installed until updated eventually (hopefully!) even if they would still work. To test compatibility of the existing versions of mods it would be helpful. I don't want to deal with a bunch of dependencies just to test whether a mod is still compatible with a newer KSP version - one of the reasons I use CKAN as package manager in the first place.

**CKAN Version:** 1.18.1

**Operating System:** Windows 10 x64 1511

**The issue you are experiencing:** cannot force install of incompatible mod/version

**How to recreate this issue:** get KSP 1.1.3 and try install BDArmory via CKAN

**CKAN error codes (if applicable):** install not supported

Suggestion: Add dev/test mode option in settings which enables forced install option. Then when filtering incompatible mods, right clicking/space could enable a context menu with the "force install" option.

**Comment by politas** [comment]
There's a bit of a philosophical problem with this. CKAN is trying to ensure a clean installation, and part of that is making it difficult to install incompatible mods. We do have a way to force the installation of any specific version of a mod, using the command line. `ckan install <identifier>=<version>`

In the case of BDArmory, You can now install BDArmory Continued on KSP 1.1.3, which will function as the dependency required for anything that requires BDArmory.

**Comment by embix** [comment]
> We do have a way to force the installation of any specific version of a mod, using the command line.
> `ckan install <identifier>=<version>`

That will totally suffice.

Thanks, I didn't found that in the documentation.
