### ISSUE TITLE
KSP Installation list loses currently invalid installs when adding a new installation

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1859]
Steps to reproduce
Add a KSP installation "install1"
Move KSP installation "install1" to a different location
Add KSP installation "install2"
Return KSP installation "install1" to its former location

install1 will not be selectable on starting CKAN

**Comment by politas** [comment]
See also related #1836

**Comment by ayan4m1** [comment]
This is intentional as far as the source is concerned: https://github.com/KSP-CKAN/CKAN/blob/master/Core/KSPManager.cs#L290

**Comment by politas** [comment]
Ideally, unavailable instances would show up in the KSP Install list greyed out, so they can be removed (fixing #1836), and they won't then be forgotten when another instance is added (fixing this)

**Comment by ayan4m1** [comment]
Ah, makes sense - that is kinda more of an enhancement rather than a ckan.dll bug right?

**Comment by politas** [comment]
I suppose you could call it an enhancement that solves two related bugs.

**Comment by politas** [comment]
@ayan4m1 , while you're working on this bit of code, we've had a feature request on the forums to maintain the "default" KSP version when selecting a non-default install. We would then need to add a button to clear the current default. Does that seem simple enough to implement?
