### ISSUE TITLE
libMonoPosixHelper.so not found on Fedora 24

### ISSUE THREAD

**Issue by sbuller** [KSP-CKAN/CKAN#1863]
Using ckan v1.18.1
```
5332 [1] ERROR CKAN.ErrorDialog (null) - Unhandled exception:
System.TypeInitializationException: The type initializer for 'Mono.Unix.Native.Syscall' threw an exception. ---> System.DllNotFoundException: /usr/lib/libMonoPosixHelper.so
```

A quick look around the internet pointed out that libMonoPosixHelper.so is actually found in /usr/lib64/, not /usr/lib/ on Fedora. The internet source suggested changing a line in `/etc/mono/config`, `<dllmap dll="MonoPosixHelper" target="$mono_libdir/libMonoPosixHelper.so" os="!windows" />` --- hardcoding the value /usr/lib64 in place of $mono_libdir. This works.

As someone very much outside the C#/Mono community, this is all very mysterious to me. I would appreciate either (preferably) a workaround/fix, or (at least) a note next to (the already very helpful) notes on the release page.

All that said, I'm up and running, although a little uncomfortable about having to edit a system file for it.

**Comment by ayan4m1** [comment]
Just did a brief investigation on this - there isn't any direct reference to the managed assembly nor the library itself directly in the source code. That said, looking around it seems that an app might be able to force its own `LD_LIBRARY_PATH` to work around this by detecting for 64-bit Linux and checking to see where the library is, but it's a lot of native hackaround to fix a simple issue that seems pretty specific to Fedora's Mono/lib location policy.

[More](https://answers.unrealengine.com/questions/240914/setupsh-cant-find-libmonoposixhelperso-in-usrlib64.html) related [issues](https://bugzilla.redhat.com/show_bug.cgi?id=1313021) about this I found.
