### ISSUE TITLE
Microsoft visual studio gets in the way of Ckan.

### ISSUE THREAD

**Issue by smiley425249** [KSP-CKAN/CKAN#1865]
CKAN Version: Unsure because I can open it
Operating System: Windows 10
The issue you are experiencing: Microsoft visual  studio is the default app ckan wants to open with and I cant open ckan itself
How to recreate this issue: Have Microsoft visual studio and download/open ckan

**Comment by ayan4m1** [comment]
This is likely something related to the Windows registry or your VS debugging settings, but I need more information to understand what is actually going wrong. What version of VS are we talking about? Where are you obtaining CKAN from? [This](https://github.com/KSP-CKAN/CKAN/releases/download/v1.18.1/ckan.exe) is the v1.18.1 binary download link which should be used. I can't reproduce your issue with that EXE, VS2015 Community and Win10x64. Also, try running ckan.exe from a command prompt. When you had this problem occur, were you double-clicking on the EXE in Windows Explorer, right clicking it and using "Open," or something else?

**Comment by smiley425249** [comment]
I'm getting Ckan right from here. If VS is Microsoft visual I'm talking I don't know the exact version but its 2015. I don't know how to run things from a cmd prompt and Ckan.exe isn't even a thing on here. as soon as I downloaded it it switched to Microsoft Visual Studio Solution. And it doesn't show anything to open it with other than Microsoft visual

**Comment by smiley425249** [comment]
what do I do?

**Comment by politas** [comment]
Did you download ckan.exe from the [current release](https://github.com/KSP-CKAN/CKAN/releases/latest), or have you forked the repo?

**Comment by smiley425249** [comment]
ah I guess I got the wrong release. THANK YOU!
