### ISSUE TITLE
CKAN Network Timeout at 100% Download. PLEASE HELP!

### ISSUE THREAD

**Issue by YoutubePhantomOfficial** [KSP-CKAN/CKAN#1869]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
Latest, 1.81.0
**Operating System:** 
Windows 10 Home
**The issue you are experiencing:** 
The most annoying connection timeout ever, it times out when the file is 100% downloaded, however that could remotely work is beyond me.
 The mods I'm downloading are:
 Mark IV Spaceplane System 2.2.1
 RasterPropMonitor 1:v0.27.0(cached)
 B9 Part Switch v1.4.3(cached)
 Community Resource Pack 0.5.4.0(cached)
 Deployable Engines Plugin 0.2.5
 Firespitter Core v7.3.0(cached)
and
 Near Future IVA Props 0.5.1
**How to recreate this issue:** 
Just download a mod. It's a network timeout. Usually happens while downloading more than one mod or anything at 20mb or higher, which at 111kb/s download (That's dumb, my connection speed is usually between 70mb/s - 144mb/s.)
**CKAN error codes (if applicable):** 
N/A. However, redownloading the file just very shortly after clicking (CONTINUE) on the .NET framework popup that mentions a network timeout seems to download and install the file(s) nearly instantaneously.

**Comment by ayan4m1** [comment]
Likely related to https://github.com/KSP-CKAN/CKAN/issues/1817

**Comment by YoutubePhantomOfficial** [comment]
No, ayan4m1, a window related to CKAN pops up and just says "Error: Network Time Out" once the download reaches 100% complete, and lists the mods that I am trying to download. This should not be happening, neither should the download speed drops, as I have a stable broadband connection.

**Comment by YoutubePhantomOfficial** [comment]
It appears as if I am either so effing stupid or the luckiest person ever. I tried to redownload it the second I clicked continue and the file downloaded within 2 seconds. WTF IS HAPPENING?! Seriously, this is weird. I would still like help with the issue, despite having found a temporary(?) way around it.

**Comment by HebaruSan** [comment]
> TRANSACTION: TIMEOUT" and all this happens in a Microsoft .NET Framework window. under details is just a bunch of garbled nonsense that a programming and modding noob as myself doesn't understand.)

For future reference, that garbled nonsense is generally the most useful thing for debugging, make sure to copy paste it into GitHub if reporting new issues.

All three non-cached mods listed here (Mark IV, Deployable Engines, Near Future IVA) are hosted on SpaceDock, whereas the mods in #1817 are on github.com and probably fail due to server-side download throttling. So I would say these probably aren't related.
