### ISSUE TITLE
Crash on start under Ubuntu 16.04

### ISSUE THREAD

**Issue by dertroglodyt** [KSP-CKAN/CKAN#1871]
**CKAN Version:**
1.18.1
mono 4.2.1
certs are synced

**Operating System:** 
ubuntu 16.04

**The issue you are experiencing:** 
mono ./ckan.exe crashes on start.
Same for new empty diectory as for old directory with 100+ mods installed.

**How to recreate this issue:** 
see above. launching it as "mono ckan" or "ckan" does crash every time.

**CKAN error codes (if applicable):** 
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'CKAN.CmdLine.MainClass' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  at log4net.Repository.Hierarchy.DefaultLoggerFactory+LoggerImpl..ctor (System.String name) <0x40298000 + 0x00013> in <filename unknown>:0

**Comment by ayan4m1** [comment]
> Could not load file or assembly 'System.Core

Do you have the [`libmoono-system-core4.0-cil`](http://packages.ubuntu.com/xenial/libmono-system-core4.0-cil) package installed?

**Comment by dertroglodyt** [comment]
How would I know? I just freshly installed mono...

**Comment by dertroglodyt** [comment]
OK, now it says:
Unhandled Exception:
System.TypeInitializationException: The type initializer for 'CKAN.Net' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  --- End of inner exception stack trace ---
[ERROR] FATAL UNHANDLED EXCEPTION: System.TypeInitializationException: The type initializer for 'CKAN.Net' threw an exception. ---> System.IO.FileNotFoundException: Could not load file or assembly 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089' or one of its dependencies.
File name: 'System.Transactions, Version=2.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089'
  --- End of inner exception stack trace ---

**Comment by dertroglodyt** [comment]
OK, installed transaction too. 
Now I get:
Could not load file or assembly 'System.Windows.Forms

How deep do I have to follow this?

**Comment by dertroglodyt** [comment]
No idea where to go now.
Now it's:

mono ./ckan.exe 
701 [1] ERROR CKAN.ErrorDialog (null) - Error in autoupdate: 
	Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
12477 [1] ERROR CKAN.Main (null) - Error in autoupdate
System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies.
File name: 'Microsoft.CSharp, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
  at CKAN.Main.OnLoad (System.EventArgs e) <0x40431090 + 0x001bf> in <filename unknown>:0 
13197 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not parse build map
13197 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not parse build map
System.NullReferenceException: Object reference not set to an instance of an object
  at CKAN.GameVersionProviders.KspBuildMap.get_Item (System.String buildId) <0x40498630 + 0x0002b> in <filename unknown>:0 
  at CKAN.GameVersionProviders.KspBuildIdVersionProvider.TryGetVersion (System.String directory, CKAN.Versioning.KspVersion& result) <0x40498070 + 0x001c2> in <filename unknown>:0 
  at CKAN.KSP.DetectVersionInternal (System.String directory) <0x4046d760 + 0x00071> in <filename unknown>:0 
  at CKAN.KSP.DetectVersion (System.String directory) <0x4046d650 + 0x00017> in <filename unknown>:0 
  at CKAN.KSP.Version () <0x4046cf50 + 0x0003f> in <filename unknown>:0 
  at CKAN.Main.<CurrentInstanceUpdated>m__B () <0x4046cdb0 + 0x00043> in <filename unknown>:0 
  at CKAN.Util.Invoke[T] (CKAN.T obj, System.Action action) <0x402f6520 + 0x000cb> in <filename unknown>:0 
  at CKAN.Main.CurrentInstanceUpdated () <0x4046cbf0 + 0x0009b> in <filename unknown>:0 
  at CKAN.Main.OnLoad (System.EventArgs e) <0x40431090 + 0x00bfb> in <filename unknown>:0 
  at System.Windows.Forms.Form.OnLoadInternal (System.EventArgs e) <0x40430e30 + 0x0007f> in <filename unknown>:0

**Comment by politas** [comment]
Are you trying to build CKAN from source?

**Comment by dertroglodyt** [comment]
No. Just put the ckan.exe into an empty folder.

**Comment by politas** [comment]
And you got that from the [current release](https://github.com/KSP-CKAN/CKAN/releases/current)?

**Comment by dertroglodyt** [comment]
Latest Releas "StarTrammier"

**Comment by politas** [comment]
I've just upgraded to Ubuntu 16.04, but I have Mono 4.4.2 from the mono-project.org PPA, and it's working fine for me.

**Comment by politas** [comment]
And you've done `apt install libcurl4-openssl-dev`?

**Comment by dertroglodyt** [comment]
Yes, did that
Why is my mono 4.2.1 when I just did apt-get it?

**Comment by politas** [comment]
That's what's Ubuntu's providing. To get 4.4.2, you have to go upstream to the [monodevelop](http://www.mono-project.com/docs/getting-started/install/linux) ppa.

**Comment by politas** [comment]
But 4.2.1 ought to work, unless Ubuntu have b0rked it.

**Comment by DinCahill** [comment]
There's the `mono-complete` package which might help. I'm not at a computer right now I can't check.

**Comment by politas** [comment]
Oh, yes, definitely need monocomplete, whether from the Ubuntu Repos or the Mono-project PPA

**Comment by dertroglodyt** [comment]
Installing...

**Comment by dertroglodyt** [comment]
...aaaaaand: Works like a charm!
Thank you so much for your help!
I wouldn't know how to play KSP without CKAN.

**Comment by politas** [comment]
Was that installing mono-complete, or switching to the mono-project PPA that fixed it?

**Comment by dertroglodyt** [comment]
Yes, last step with mono-complete soved it.
