### ISSUE TITLE
Wrong KSP Version

### ISSUE THREAD

**Issue by SamHillcoat** [KSP-CKAN/CKAN#1872]
CKAN Gui shows KSP version 1.1.2 while 1.1.3 is displayed on the KSP main menu. The readme.txt file also contains 1.1.3.

**CKAN Version: v1.18.1/StarTrammier** 

**Operating System: Windows 10**

**Comment by Olympic1** [comment]
CKAN reads the ksp version and displays it on the GUI. Do you maybe have multiple KSP installations with one of those a 1.1.2 one?

**Comment by SamHillcoat** [comment]
@Olympic1 No, I only have one install currently, being the 1.1.3 version.

**Comment by politas** [comment]
Also, CKAN now primarily uses the BuildID.txt for determining the KSP version, only looking at readme.txt as a secondary source if BuildID.txt is not present or corrupted. The table CKAN uses to determine the KSP version is [here](https://github.com/KSP-CKAN/CKAN-meta/blob/master/builds.json)

**Comment by SamHillcoat** [comment]
Ok, thanks for the help. It seems the buildID.txt file is the problem.
