### ISSUE TITLE
Norton Insight - Deletes CKAN.exe - Flags as Untrustworthy

### ISSUE THREAD

**Issue by deafmetal1** [KSP-CKAN/CKAN#1874]
As of the recent 1.18.1 update, Norton A/V Insight and Power Eraser flags ckan.exe as untrustworthy.  Fresh downloads from Github are immediately deleted by Norton based on WS.Reputation.1

Windows 10 64bit and latest version of Norton Security.

**Comment by ayan4m1** [comment]
> The reputation-based system uses "the wisdom of crowds" (Symantec’s tens of millions of end users) connected to cloud-based intelligence to compute a reputation score for an application, and in the process identify malicious software in an entirely new way beyond traditional signatures and behavior-based detection techniques.

Don't think there is anything we can do about this offhand.

**Comment by politas** [comment]
If you can find a way to add an exception for ckan.exe, I'd advise using it. The actual building of the CKAN executable is automated in a clean build environment that is created as required. It's not completely impossible that it could be compromised, but it's certainly not going to be accidentally infected, and you are welcome to peruse the code here on GitHub. 

I have submitted a Whitelisting request.

**Comment by deafmetal1** [comment]
Exception added.  Looks like your whitelist request was approved, it is now given a "Good" rating.  Thank you!
