### ISSUE TITLE
CKAN Error in Regards to Sorting

### ISSUE THREAD

**Issue by DonKalypso** [KSP-CKAN/CKAN#1875]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.18.1-0-g0d2c4f0 (beta)
**Operating System:** 
Windows 10
**The issue you are experiencing:** 
On sorting by Max KSP Version, CKAN will spit the following error: http://pastebin.com/QPuCpckw
**How to recreate this issue:** 
Sort by Max KSP Version, not replicating in --debug.
**CKAN error codes (if applicable):** 
http://pastebin.com/QPuCpckw

**Comment by DonKalypso** [comment]
I've no idea why, but now it's just not at all replicating.

If no one else can replicate this problem, then I'll chalk it up to my comp being haunted by the angry ghosts of a thousand long dead, 1950s era programmers getting their revenge on me for looking at porn or something.

**Comment by ayan4m1** [comment]
You were likely experiencing this issue: https://github.com/KSP-CKAN/CKAN/pull/1866

Were you sorting by the "Max KSP Version" column before this exception occurred?

**Comment by DonKalypso** [comment]
Before the error began happening, I would keep it on sorted by "Max KSP Version," yes.
