### ISSUE TITLE
Allow CKAN to fit on smaller resolution screens

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#1891]
CKAN Version: v1.20.0

Linux/Ubuntu 14.04

Bottom of CKAN window is cut off for screens with vertical resolution lower than 990 pixels and window cannot be made smaller. This puts the Apply/Cancel buttons off the screen for the most common screen resolution of 1366x768 ([source](http://www.rapidtables.com/web/dev/screen-resolution-statistics.htm))

**Comment by ayan4m1** [comment]
Just a quick info drop, there are [facilities](https://msdn.microsoft.com/en-us/library/3z3f9e8b(v=vs.110).aspx) in WinForms to deal with automatically "growing" and "shrinking" the controls to fit the window area, but it is a bit confusing and likely comes with some cross-platform caveats as well.

**Comment by politas** [comment]
I don't think we need to worry about that. All the CKAN GUI fits fine in 1024x700, at least on Linux.

**Comment by Olympic1** [comment]
Resizing the window to 1024x700 on windows makes the `Next` arrow not visible anymore and the KSP version overlapping the `Filter` button and `Back` arrow.

![new res](https://cloud.githubusercontent.com/assets/8020752/18409445/91073cd4-7747-11e6-9c9b-25cdd77b6486.PNG)

**Comment by Postremus** [comment]
I don't think we need the ksp version in the gui, at least on smaller
resulotions. the version can also be found in the window title.
we could also move it down into the status bar.

2016-09-10 11:15 GMT+02:00 Arne Peirs <notifications@github.com>:

**Comment by politas** [comment]
Wow. Windows must assume really bad eyesight. I'll bump it out to 1280

**Comment by Olympic1** [comment]
1280 shows everything.

**Comment by politas** [comment]
Can y'all test this?
[ckan.zip](https://github.com/KSP-CKAN/CKAN/files/465351/ckan.zip)
