### ISSUE TITLE
CKAN not responding after update.

### ISSUE THREAD

**Issue by GabrielFW** [KSP-CKAN/CKAN#1892]
Hello.

CKAN Version: 1.20.0

Operating System: Win 10 Pro

My CKAN was working perfectly but when i updated it to the 1.20.0 version it would freeze as soon as i opened the program, i even tried reinstalling KSP and CKAN but it didnt work, if i try to repair it through the cmd this shows up:  

```
Exceção Sem Tratamento: System.ObjectDisposedException: Não é possível acessar um arquivo fechado.
   em System.IO.__Error.FileNotOpen()
   em System.IO.FileStream.Flush(Boolean flushToDisk)
   em System.IO.StreamWriter.Flush(Boolean flushStream, Boolean flushEncoder)
   em System.IO.StreamWriter.Dispose(Boolean disposing)
   em System.IO.TextWriter.Dispose()
   em CKAN.RegistryManager.ReleaseLock()
   em CKAN.RegistryManager.Dispose(Boolean safeToAlsoFreeManagedObjects)
   em CKAN.RegistryManager.Finalize()
```

Would like some help with it.

Edit: Ok, i managed to make it actually repair the registry but still whenever i start the program it immediately stops responding.

**Comment by GabrielFW** [comment]
Ok, i managed to make it actually repair the registry but still whenever i start the program it immediately stops responding.

**Comment by GabrielFW** [comment]
Ok, managed to fix it turns out i had to run it as admin.

**Comment by politas** [comment]
Are you thinking we should try to get CKAN working without having to run as admin, @ayan4m1? (Or at least get it to pop up a nicer message?)

**Comment by GabrielFW** [comment]
Well yeah to be honest i do think you should try to give as much feedback to the user as possible, so yeah a message warning that would be nice.

**Comment by ayan4m1** [comment]
@politas, the log is the important bit for me. `ObjectDisposedException` is not usually harmless and not usually intended.

Also, something to note (but not really something we can "fix" as the user did it intentionally), if someone runs CKAN as admin once, they may need administrative elevation again to free a "stuck" locked registry if the process ends without removing the lockfile.

**Comment by HebaruSan** [comment]
(Google Translate: Unhandled Exception: System.ObjectDisposedException: Can not access a closed file.)

**Comment by HebaruSan** [comment]
Please let us know if this happens again with recent versions and we can re-open this.
