### ISSUE TITLE
Failed to connect to repository. Exception: Too many mods provide...

### ISSUE THREAD

**Issue by Zetal911** [KSP-CKAN/CKAN#1894]
I just updated to v1.20.0, the most recent version. I'm running on a x64 Windows 7 machine.

When I hit the 'Refresh' button, or when I start CKAN, I get the following error:

> Failed to connect to repository. Exception: Too many mods provide TACLS-Config:
> TACLS-Config-RealismOverhaul v11.3.2
> * TACLS-Config-Stock v0.12.4

I've tried restarting it to no avail. I always run the program in admin mode. This doesn't seem to happen with a fresh install, so I'm assuming it has something to do with either the cache or the CKAN folder as it exists after an update?

**Comment by politas** [comment]
It has to do with a change to TACLS and TACLS-Config-Stock. You need to uninstall and reinstall TACLS and TACLS-Config-Stock

**Comment by Zetal911** [comment]
That fixed it. I was also getting an issue where selected the 'Add available updates' button after receiving this error broke the ability to apply changes unless the program was restarted, but that seems to have been resolved by this as well, so it's probably fine.

**Comment by politas** [comment]
Yes, please do.
