### ISSUE TITLE
'Add Available Updates' Enables 'Apply changes' button but adds nothing to the Changeset page

### ISSUE THREAD

**Issue by Zetal911** [KSP-CKAN/CKAN#1895]
**CKAN Version:** 1.20.0

**Operating System:** Windows 7 x64

**The issue you are experiencing:** When I launch CKAN and click the 'Add available updates' button, the Changeset doesn't have any additional mods, and hitting 'Apply changes' doesn't actually apply any mods. Hitting the 'apply' button on the empty changeset page does nothing, too.

This probably has something to do with my install, but I'm at a loss for what to do about it.

http://pastebin.com/5dnbe5sP <-- List of installed mods.

**Comment by politas** [comment]
What is your current "Filter" setting?

**Comment by Zetal911** [comment]
My current Filter setting is 'Installed'. My registry.json was too big for pastebin, but I uploaded it on mega? http://www.megafileupload.com/oix0/registry.json Site is garbage though, so up to you if you want to actually download it from there. :/

**Comment by winsmith** [comment]
Hi, I also experience this issue. Windows 10 Pro, Version 1703. CKAN Version is 1.22.3, KSP version is 1.22.1622. The filter setting is set to "compatible", but changing it to "all" has no effect on the behaviour.

Here are my [installed mods](https://gist.github.com/winsmith/4ecb1d779bae591e52dde4606d47afdb) and my [registry.json](https://gist.github.com/winsmith/9d0b319200894082b0fd756e601ad056).

I'll try removing and reintalling CKAN first.

**Comment by politas** [comment]
I assume you have clicked on the "Refresh" button, and there are new versions of mods actually available?

**Comment by politas** [comment]
I would advise using the [Clean and reinstall process](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process) as a possible fix. Most likely occurrence is that changes to dependencies and mod availability is causing some incompatibility.

**Comment by winsmith** [comment]
Thanks for your help! I'll try that out and report back :) (btw thanks for making CKAN! You people are awesome)
