### ISSUE TITLE
64-bit version files (eg. for KSP 1.2) are ignored.

### ISSUE THREAD

**Issue by WazWaz** [KSP-CKAN/CKAN#1898]
Basically, KspBuildIdVersionProvider.cs uses buildID.txt, ignoring newer buildID64.txt

With 1.2, KSP is distributed as separate 32-bit and 64-bit versions. Worse, if using the Patch to 64-bit, the old buildID.txt from the full 1.1.3 is left, so CKAN sees that and believes it's 1.1.3 still.

**Comment by politas** [comment]
Can you give some more details about the file structure you're seeing?

**Comment by politas** [comment]
The Steam update to the prerelease gave me a new BuildID.txt (on Linux), and we've been told that the BuildIDs should be the same across platforms.

**Comment by WazWaz** [comment]
ksp-win-1-1-3.zip as distributed from the KSP Store contains these relevant files:

buildID.txt:
```
build id = 01289
2016.06.21 at 20:12:36 CEST
Branch: master

```
buildID64.txt:
```
build id = 01289
2016.06.21 at 20:49:32 CEST
Branch: master

```
readme.txt:
```
...
Version 1.1.3
...

```
After running the KSPx64-Patch-1.1.3-To-1.2.exe provided on the KSP Store (which patches "to version 1.1.9.1473"), those files become:

buildID.txt (unchanged):
```
build id = 01289
2016.06.21 at 20:12:36 CEST
Branch: master

```
buildID64.txt:
```
build id = 01473
2016.09.13 at 23:41:56 CEST
Branch: prerelease

```
readme.txt:
```
...
Version 1.2.0
...
```

**Comment by politas** [comment]
Apparently there were some problems with the store versions today. The BuildID I got from Steam is 1479. Can you try downloading the Store patch again?

**Comment by politas** [comment]
Confirmed  from Squad - 1479 is the correct buildID. You should re-download. We'll have a patch out to use buildID64.txt in preference to buildID.txt as well as a couple of other things, but in the meantime, you could copy the info from buildID.txt to buildID64.txt and CKAN will then recognise build 1479.

**Comment by Olympic1** [comment]
From the KSP store you can download 5 patches to update to the 1.2 pre (added 'enters' for clarity)

> **Downloads:**
Latest Build: 01479
Win32 Patch 1.2-Latest
Win64 Patch 1.2-Latest

> Win32 Patch 1.05-Latest

> Win32 Patch 1.1.3-Latest
Win64 Patch 1.1.3-Latest

> Win32 Full Game 1.2
Win64 Full Game 1.2

If you choose Win32 it will only update the buildID.txt, choosing Win64 wil only update buildID64.txt. Steam updates both.
