### ISSUE TITLE
Freeze on updating repositories

### ISSUE THREAD

**Issue by Dawnkeeper** [KSP-CKAN/CKAN#1907]
**CKAN Version:** 1.120.1

**Operating System:** Win10

**The issue you are experiencing:** 
CKan freezes during startup on "Updating repositories"

**How to recreate this issue:** 
After trying different things I found that deleting the registry.json solved the problem.
Here is the one that caused it:
https://www.dropbox.com/s/lf22doxzsax9h21/ckan_registry.7z?dl=0

**Comment by ayan4m1** [comment]
Thanks for providing a copy of the registry.json. How long are you waiting after starting CKAN - describe the "freeze" further if you can. I was able to start up CKAN with the registry.json you provided but it took roughly one minute for the update process to complete. Once we have #1881 we can start looking at a log file to see if an actual exception is being thrown when the user reports a GUI hang.

**Comment by Dawnkeeper** [comment]
I started CKan and forgot about it the first time this happened. Took about 5 minutes before I noticed. In subsequent tries I didn't wait that long. 30 sec max.

I can't describe it any better as I only see the progress bar and "updating repos". i used ProcessExplorer to kill it and don't remember seeing anything unusual there.

**Comment by Olympic1** [comment]
Adding `bug` tag to keep this open

**Comment by politas** [comment]
Had you done anything to your GameData directory outside CKAN before this started happening?

**Comment by politas** [comment]
Using that registry.json, I can't reproduce the problem. It took a long time to update, but it eventually did.
