### ISSUE TITLE
Replacing dependencies

### ISSUE THREAD

**Issue by diego-treitos** [KSP-CKAN/CKAN#1909]
**CKAN Version:**
v1.20.1-0-gd41fe54

**Operating System:**
Ubuntu GNU/Linux 16.04

**The issue you are experiencing:**
Cannot replace dependency: I am trying to replace RSSTextures8192 with RSSTextures4096. Both packages satisfy the same dependency requirements but it seems that I cannot replace them withouth uninstalling first all packages depending on RSSTextures8192.

**How to recreate this issue:**
Install RO with RSSTextures8192 and try to then install RSSTexture4096

**CKAN error codes (if applicable):**
RSSTextures4096 v10.4 conflicts with RSSTextures8192 v10.4, can't install both.
Install canceled. Your files have been returned to their initial state.

I would expect CKan to tell me that (as both packages satisfy the same dependency), RSSTexture8192 would be removed and RSSTextures4096 would be installed and ask for confirmation.

**Comment by politas** [comment]
It certainly would be better to be able to swap dependencies without uninstalling the requiring mod, but currently, that is what is required.

**Comment by diego-treitos** [comment]
It is not to uninstall only the requiring mod but all the dependency tree branch.
I have Realism Overhaul installed and right now, if I want to change the RSS Textures I need to uninstall all the dependencies in the branch down to RSSTextures: RSS, RP-0, KCT-RP-0 Config and RSSTextures, loosing all the mods configurations in the middle. This is far from ideal.

**Comment by diego-treitos** [comment]
BTW. A simple workaround for this would be to allow to install and uninstall packages with a `--force` flag, something that's been requested many times.

**Comment by politas** [comment]
Yeah, Realism Overhaul is a pain that way. But reinstalling shouldn't take all that long; it should all be cached.
