### ISSUE TITLE
Repositories Update

### ISSUE THREAD

**Issue by Cassio38** [KSP-CKAN/CKAN#1911]
Thanks for wanting to bring an issue to our attention!

Ckan Version: 1.20.1
Operating System: Win 10

Issue: Repository successfully updated, which seem to be a lie ^^ Lot of mods are missing, even if they actually are in the master.tar.gz files used as default | https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz and there version are up to KSP 1.2

how to recreate this issue: at the moment, just install KSP 1.2 from steam, put ckan in the installation folder and open it.

ckan error code: none

any idea how to maybe force repositories update or redo it ?
Thanks !

edit: oh and something odd: when i click on "Launch KSP" in Ckan it doesnt work

**Comment by Olympic1** [comment]
Which mods are not showing up

**Comment by Cassio38** [comment]
lot of them Karibou Exploration Rover from RoverDude for example

I just noticed, few hours ago i had 79 compatible mod in Ckan, now 83. I'm not sure i will keep an eye on that. maybe they will slowly appear

**Comment by Olympic1** [comment]
USI mods cant show up because RoverDude forgot to update a netkan file, I saw there is a PR ready t fix that.

**Comment by Cassio38** [comment]
Ok thanks !

**Comment by Olympic1** [comment]
Mods show up now, closing
