### ISSUE TITLE
CKAN proposes AmpYear update to 1.4.0.0 for KSP 1.1.3

### ISSUE THREAD

**Issue by Real-Gecko** [KSP-CKAN/CKAN#1912]
**CKAN Version:** 1.20.1

**Operating System:** Arch Linux

**The issue you are experiencing:** With version 1.2 of KSP released many mods developers released recompiled versions of their mods. CKAN proposes updates for some of them even though it's noted that new version is not meant to be run with KSP 1.1.3.

**How to recreate this issue:** 
- Download AmpYear [release 1.4.0.0](https://github.com/JPLRepo/AmpYear/releases/tag/V1.4.0.0)
- Unpack archive and open *AmpYear.version* file
- You'll see
```JSON
"VERSION":{"MAJOR":1,"MINOR":4,"PATCH":0,"BUILD":0},
"KSP_VERSION":{"MAJOR":1,"MINOR":2,"PATCH":0},
"KSP_VERSION_MIN":{"MAJOR":1,"MINOR":2,"PATCH":0},
"KSP_VERSION_MAX":{"MAJOR":1,"MINOR":2,"PATCH":0}
```
- Launch CKAN 1.20.1 with KSP 1.1.3 installation
- Refresh
- Note the update proposal
![screenshot_20161012_201508](https://cloud.githubusercontent.com/assets/2231969/19313584/d65f782a-90b8-11e6-857b-86637a9f188d.png)

I think that same is true for [Final Frontier](http://forum.kerbalspaceprogram.com/index.php?/topic/61065-12113-final-frontier-kerbal-individual-merits-120-2630/&page=1)

**Comment by politas** [comment]
The online copy of the AVC file is confusing NetKAN - http://ksp-avc.cybutek.net/version.php?id=147

**Comment by Real-Gecko** [comment]
Everything looks good now
![screenshot_20161014_024212](https://cloud.githubusercontent.com/assets/2231969/19366176/e974561a-91b7-11e6-9b2e-d47fc78c40c1.png)
