### ISSUE TITLE
CKAN generates a lot of DEBUG output now.

### ISSUE THREAD

**Issue by mathuin** [KSP-CKAN/CKAN#1913]
**CKAN Version:** tip as of this morning -- last commit 2764a1ce

**Operating System:** Linux

**The issue you are experiencing:** I run ckan, I get ninety thousand lines of DEBUG output

**How to recreate this issue:** Check out master.  `docker-compose build ckan`.  `docker-compose run --rm ckan`

**CKAN error codes (if applicable):** It succeeds.  It even updates the mods!  It just tells me allllll about it. :-)

**Comment by Olympic1** [comment]
When you did a pull from the main repo, did only that commit got pulled or others too?

**Comment by mathuin** [comment]
Other commits were pulled too -- I haven't updated in a week or two.

**Comment by Olympic1** [comment]
Ah then this will explain your issue: https://github.com/KSP-CKAN/CKAN/pull/1881

We are logging to the console during builds. If there is a `log4net.xml` somewhere, deleting it will probably fix it. Don't take my word on that though, I'm not fully up-to-date with that.

**Comment by mathuin** [comment]
The only difference between `Cmdline/log4net.xml` and `GUI/log4net.xml` is that the former has a default value of `INFO` while the latter has a default value of `WARN`.  Changing `INFO` to `WARN` does not reduce the logging output.  Most of the output is of `DEBUG` level, as if this file is being ignored.

**Comment by politas** [comment]
Yes, this is definitely a problem. It also slows the GUI down massively.

**Comment by ayan4m1** [comment]
Hey, in this case I think the lack of a `log4net.xml` is actually your issue. No XML presence calls `BasicConfigurator.Configure()` which is likely to set up a debug-level appender by default (see [here]( https://github.com/apache/log4net/blob/trunk/src/Config/BasicConfigurator.cs#L167))

**Comment by mathuin** [comment]
If you can supply me with a file and a location to place it, I can tell you whether or not it works.

If the code defaults to `DEBUG` logging, that's a bug.
