### ISSUE TITLE
CKAN proposes Final Frontier update to 1.2.0-2630 for KSP 1.1.3

### ISSUE THREAD

**Issue by Real-Gecko** [KSP-CKAN/CKAN#1914]
**CKAN Version:** 1.20.1

**Operating System:** Arch Linux

**The issue you are experiencing:** same as in #1912

**How to recreate this issue:** just do like this
![screenshot_20161014_141525](https://cloud.githubusercontent.com/assets/2231969/19380376/d5bb1d1e-9218-11e6-9a1c-19ba9576a19f.png)

**Comment by politas** [comment]
Which doesn't exist, probably due to the bad AVC file that messed up CKAN.

**Comment by politas** [comment]
Sorted.
