### ISSUE TITLE
Spacedock 404

### ISSUE THREAD

**Issue by Commissar0617** [KSP-CKAN/CKAN#1915]
Failed to download "https://spacedock.info/mod/715/No Crew Requirement Continued/download/1.01" - error: The remote server returned an error: (404) Not Found.

running v1.20.1-0 on win 8.1...

*only* occurs with this mod, currently. persists across reboots. i can download just fine with my browser...

**Comment by Olympic1** [comment]
Fixed in https://github.com/KSP-CKAN/CKAN-meta/commit/0d7a105b73804e09a9002447ba847c1b7754c8b2

Make sure to download **1.0.1**
