### ISSUE TITLE
CKAN not allowing me to open the ksp install

### ISSUE THREAD

**Issue by tylerbobs** [KSP-CKAN/CKAN#1916]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
latest
**Operating System:** 
windows
**The issue you are experiencing:** 
![error](https://cloud.githubusercontent.com/assets/22854755/19410166/e6ea56d0-92dc-11e6-91a8-7b049ec3526e.PNG)

**How to recreate this issue:** 
file, select KSP install...
**CKAN error codes (if applicable):**

**Comment by Olympic1** [comment]
Looks like you don't have a readme in your ksp folder.

**Comment by tylerbobs** [comment]
but I do

**Comment by politas** [comment]
Try reinstalling KSP / confirming KSP installation. It won't hurt anything.

**Comment by Peulleieoyukino** [comment]
Same issue here. 

Reinstalling both .net framework 4.5 and ckan along with a confirmed KSp install does not solve the problem. 

After initial issue, manual selection of KSP install indicates that the version of KSP is 1.2.0 as expected in my case, but not seems recognized by any other part of the program.

**Comment by ayan4m1** [comment]
Confirming that the state of the registry is as expected would be another thing...  the keys in `HKEY_CURRENT_USER\SOFTWARE\CKAN` may be invalid, misconfigured, out of date or need to be reset.

**Comment by tylerbobs** [comment]
So how do I fix it if that is the case?

**Comment by Peulleieoyukino** [comment]
windows+R type Regedit.exe then go to HKEY_CURRENT_USER\SOFTWARE\CKAN 

there should be something like that : 

![regedit](https://cloud.githubusercontent.com/assets/22897220/19490439/737f09a8-956f-11e6-8b49-6923b2bbb843.png)

delete all except the top one, referred as the default value. 

Didn't solve anything in my case but worth a try.

**Comment by tylerbobs** [comment]
that has worked
thx
