### ISSUE TITLE
Ckan using dead link.

### ISSUE THREAD

**Issue by Velken** [KSP-CKAN/CKAN#1917]
Link: http://ckan1.spacedock.info/storage/greystork_11180/Behemoth_Aerospace_Engineering_Large_Parts/Behemoth_Aerospace_Engineering_Large_Parts-1.2.2.zip

**CKAN Version:** 
1.20.1-0-gd41fe54 (beta)

**Operating System:** 
Windows 10 Pro - 64 Bit

**The issue you are experiencing:** 
Failed to download file.

**How to recreate this issue:** 
Downloading Behemoth Aerospace Engineering Large Parts

**CKAN error codes (if applicable):** 
404 - Not found.

**Comment by politas** [comment]
The latest version of that mod was for 1.0.5, so that earlier version should not be showing up at all. Should be gone, now.
