### ISSUE TITLE
A filter should show mods that are new, and those that are compatible with my version for the first time.

### ISSUE THREAD

**Issue by Qazerowl** [KSP-CKAN/CKAN#1923]
I want to look at all of the mods available for my version of KSP that were not available last time I refreshed the package list. I think this should replace the new in repository filter. When I use the new in repository filter, it's because I've already looked through all the mods in the compatible list, and after refreshing, I see that there are more mods in the compatible list.

Knowing whether a mod has ever been in the repo or not isn't very useful, since what really matters is if it's updated for my version of KSP.

**Comment by Qazerowl** [comment]
Or, to put it another way: I want to somehow see the changes in the "compatible" list since the last time I refreshed.

**Comment by HebaruSan** [comment]
This is where we populate the "New in repository" filter:

https://github.com/KSP-CKAN/CKAN/blob/37c8477acccd8cebe204da4905cd67760e6bdb31/GUI/MainModList.cs#L156-L172

Adding updates would involve checking compatibility there rather than just existence of the module.
