### ISSUE TITLE
CKAN won't load further than an error message

### ISSUE THREAD

**Issue by Sparkly-Panda** [KSP-CKAN/CKAN#1932]
CKAN v1.20.1

OSX El Capitan

Error message shows 'CKAN is already running in this instance! 
If you're certain this not the case, then delete:
"/Users/ejahn/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN.registry.json.locked"'

I just tried to open it. I've restarted my computer, moved the closest log to that into trash and emptied it but it still comes up.

**Comment by politas** [comment]
That filename ought to be "/Users/ejahn/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN/registry.json.locked" Not sure why it's put a "." instead of a "/" in there./

**Comment by Sparkly-Panda** [comment]
Still nothing comes up. No files, logs or anything. I got a successful load yesterday before this problem came up. I tried using rm in terminal but i get a bunch of "directory not found" messages due to the spaces

**Comment by politas** [comment]
No, you'll need to escape the spaces or cd to the directory first, or go to the relevant folder in whatever OSX uses for a file manager. This command should do the trick:

    rm /Users/ejahn/Library/Application\ Support/Steam/SteamApps/common/Kerbal\ Space\ Program/CKAN/registry.json.locked

**Comment by Sparkly-Panda** [comment]
Thank you for the help. All working now
