### ISSUE TITLE
New Mod column of CKAN Main page of "Mod install date"

### ISSUE THREAD

**Issue by jaxx050** [KSP-CKAN/CKAN#1933]
Basically, a new column on the main mod page of the CKAN program that would tell you when any given mod was installed and/or updated on your system. This would be extremely helpful for doing mod rollbacks when you get compatibility or gameplay issues and you want to diagnose what mod isn't working right. I would make this a suggestion issue but I'm not sure how. :<

**Comment by Nicolas-GUILLAUME** [comment]
I agree. I actually just screwed up my current game with a mod upgrade and I have not idea how to roll it back. I would see it as a "history" of mod installed/upgraded more than a install date on an particular mod. It would be much easier to read that way.
An other easy solution in my opinion my be a backup before apply button that simply write all the mods to an other folder before changing anything.
Thoughts?
