### ISSUE TITLE
IXSWarpshipOS not appearing on CKAN.

### ISSUE THREAD

**Issue by Rethkir** [KSP-CKAN/CKAN#1937]
I noticed that the mod IXSWarpshipOS was not on CKAN, so I thought I'd add it. But then I saw that it was already on NetKAN. It looks like the code works, so why is this not showing up on CKAN then?

[https://github.com/KSP-CKAN/NetKAN/blob/ada4f8324490724f517801fdd0bf2432612cf9bf/NetKAN/IXSWarpshipOS.netkan](url)

**Comment by politas** [comment]
Dependency AlcubierreStandalone is not yet out for 1.2.1, but apparently, RoverDude will be releasing new versions of his mods today. IXSWarpshipsOS should show up as soon as that happens. Nothing required for IXSWarpshipOS
