### ISSUE TITLE
Kerbal Planetary Base Systems missing in CKAN

### ISSUE THREAD

**Issue by Nils277** [KSP-CKAN/CKAN#1938]
**CKAN Version:** 
v1.20.1-0-gd41fe54(beta)

**Operating System:** 
Windows 8 Professional

**The issue you are experiencing:** 
The Mod "Kerbal Planetary Base System" is not available via CKAN, even though it has an entry in the [CKAN-meta](https://github.com/KSP-CKAN/CKAN-meta/blob/master/KerbalPlanetaryBaseSystems/KerbalPlanetaryBaseSystems-v1.3.4.ckan). This applies to the latest versions 1.3.3 and 1.3.4 of KPBS. It is not listed at all, not even as incompatible
This might be related to [a change](https://github.com/KSP-CKAN/NetKAN/pull/4778) of the .netkan file for this mod, which added *CommunityCategoryKit* and *CommunityResourcePack* as dependencies. 

**How to recreate this issue:** 
Search for the author *Nils277* or *Planetary Base Systems* in CKAN. The mod is not listed

**Comment by ayan4m1** [comment]
Those two dependencies are listed as `max_version` of 1.2.0, so due to #1695 your mod isn't showing up.

Still working on the fix, sorry.

**Comment by Nils277** [comment]
Thank you for the info. Should have looked more thoroughly to see that the problem is already known.
