### ISSUE TITLE
Failed to connect; trying to write to file

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1941]
The error in question is as follows:

Failed to connect to repository. Exception: Trying to write E:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/UmbraSpaceIndustries/FX/bubble.png but it already exists.

Was on StarTram, have just gone through auto update to Alexey. 

W7 SP1 x64

Exception occurred after going through the auto updater. 

Have not tried for reproduction just yet.

**Comment by Blu3wolf** [comment]
restarting CKAN with a clean install seems to result in no error, so its likely some interaction with older mods being installed?

**Comment by politas** [comment]
I think that file got moved from being installed by one mod to being in a dependency, instead.

**Comment by bdew** [comment]
I've got the same error message but for a different file (GameData\REPOSoftTech\RSTKSPUtils\RSTKSPGameEvents.dll).

Why is CKAN trying to write to files before i even told it to do anything?

**Comment by Dazpoet** [comment]
Maybe a solution to problems like these, us changing the metadata and users being caught in the crossfire, could be that we make a habit of doing an epoch-bump when we change things? That way users will be prompted for an update to what is essentially the same mod but without this issue.

**Comment by politas** [comment]
That'll make for a lot of epoch bumps. Maybe we should hide the epochs from the UI unless a config option is turned on.

**Comment by Dazpoet** [comment]
I would wholeheartedly agree to such a thing, I like my versionnumbers tidy and I guess I'm not alone.
