### ISSUE TITLE
Pretty please rename the registry lock file

### ISSUE THREAD

**Issue by olasundell** [KSP-CKAN/CKAN#1943]
I use the command line, and at times I pipe the output from ckan to grep. Sometimes it doesn't work and the registry.json.lock file remains on disk. When I delete the file, I use command line completion to rm. It kind of sucks that registry.json shows up as the first suggestion, before registry.json.lock.

I've already deleted registry.json by mistake - once. I've been close to do it a multitude of times. Please rename the lock file to registry.lock, or lock.registry.json or something similar. :)

Thanks!

**Comment by mathuin** [comment]
Would a new command `ckan clear` or something which would remove the lock for you be acceptable?

**Comment by politas** [comment]
I can't think of a reason we couldn't rename the lock file, but I'm not sure why the name was chosen.
