### ISSUE TITLE
Strategia: broken homepage link

### ISSUE THREAD

**Issue by Necessarycoot72** [KSP-CKAN/CKAN#1947]
The mod strategia homepage link leads to the KSP forum homepage. It should go [here](http://forum.kerbalspaceprogram.com/index.php?/topic/131808-12x-strategia-v140-2016-11-21/)

CKAN Version: 1.20.1
OS: Windows 10

**Comment by ayan4m1** [comment]
Patch submitted to the authors repo - for future reference if a project hosts its netkan file on GitHub you can likely submit this kind of request on that repo.
