### ISSUE TITLE
Mod: Lights Out is compatible but showing wrong version

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1948]
Just noticed this:

On a 1.2.1 game, the mod "Lights Out", which IS compatible, is properly showing up when I select to show compatible mods.  However, what is displayed is wrong.
I did refresh CKAN, and even tried restarting it.  See the attached image:
![lightsout](https://cloud.githubusercontent.com/assets/1630166/20670417/cf2442f4-b546-11e6-8f51-3154c5d54232.png)

**Comment by politas** [comment]
Yeah, it's the usual problem. "v1.2.0" comes after "0.2.0". We'll need an x_netkan_force_v or an epoch.

**Comment by mathuin** [comment]
Would it be easier to modify the CKAN code to skip the 'v' when doing comparisons?

**Comment by politas** [comment]
We don't know _why_ authors choose to change their version strings, we just have to deal with it afterwards, when we know _what_ they've done.
