### ISSUE TITLE
Jenkins support

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#195]
@Sarbian has an [awesome jenkins server](https://ksp.sarbian.com/jenkins/), that builds many important modules, including ModuleManager and MechJeb2.

It has a pretty easy JSON API (just add `/api` to the end of any URL), so it would be possible for us to check for new releases.

@Sarbian, are you happy for us to query your server and index relevant build artefacts into the CKAN? If so, I'd like to do the following:

- [x] Add support for Jenkins to the NetKAN
- [x] Index MechJeb2 via Jenkins query
- [ ] Index ModuleManager via Jenkins query.
- [ ] Check if there are other mods for which build artefacts should be considered "stable" from Jenkins.

Many thanks!

~ Paul

**Comment by hakan42** [comment]
* Work on netkan is done
* MechJeb2 is being indexed via our Jenkins from @sarbian 's Jenkins
* ModuleManager could be indexed next
