### ISSUE TITLE
CKAN failing to download mods hosted on Spacedock

### ISSUE THREAD

**Issue by Zuthal** [KSP-CKAN/CKAN#1950]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version: v1.20.1 aka Alexey** 

**Operating System: Mac OS X 10.9.5** 

**The issue you are experiencing: Whenever I attempt to install or update a mod for which the file CKAN uses is hosted on Spacedock, it fails to download with an SSL certificate error message (I think).** 

**How to recreate this issue: Attempt to download a mod which is hosted on Spacedock, such as Hide Empty Tech Node or Heat Control.** 

**CKAN error codes (if applicable): Failed to download "https://spacedock.info/mod/537/Heat Control/download/0.3.4" - error: SslCaCert**

**Comment by LuciusMartius** [comment]
I have had the same issue on Linux:
Failed to download "https://spacedock.info/mod/234/[x] Science!/download/v5.3" - error: SslCaCert

I have tried both "cert-sync" and "mozroots --import --ask-remove" to update my certificates.

**Comment by kshade** [comment]
I think this is why: https://blog.mozilla.org/security/2016/10/24/distrusting-new-wosign-and-startcom-certificates/

**Comment by linuxgurugamer** [comment]
Odd, because according to Chrome, the certificate on Spacedock was issued by Kaspersky, and is valid from Feb, 2016 to Feb 2017

**Comment by kshade** [comment]
Firefox and openssl say that it's "StartCom Class 1 DV Server CA", valid until February 16, 2017. The curl console tool doesn't like it either.

**Comment by Dazpoet** [comment]
Sounds like we might want to inform @V1TA5 about this rather than having the discussion here.

**Comment by Lartza** [comment]
@linuxgurugamer Your AV is injecting it's certificate to your system so it can intercept and read all HTTPS traffic, after intercepting and scanning the page it re-encrypts the traffic with it's on cert and sends it to your browser.

**Comment by V1TA5** [comment]
Im currently ill and very bussy till the end of the year but ill look into it. Maybe its time to switch to lets encrypt.

**Comment by kshade** [comment]
Idea for a workaround (works, tested it): Use normal http for all spacedock.info links. It really shouldn't matter from a security/privacy standpoint.

**Comment by politas** [comment]
That's not a simple workaround, unfortunately.

**Comment by techman83** [comment]
We really should get around to falling back to the internet archive. There's over 8000 mods mirrored now.

**Comment by politas** [comment]
@techman83 Do we have a method for generating the Internet Archive download URL written down somewhere?

**Comment by techman83** [comment]
Probably not in the easiest to digest manner, but yes.

https://github.com/KSP-CKAN/NetKAN-bot/blob/master/lib/App/KSP_CKAN/Metadata/Ckan.pm#L283

**Comment by dbent** [comment]
> Probably not in the easiest to digest manner, but yes.
>
> https://github.com/KSP-CKAN/NetKAN-bot/blob/master/lib/App/KSP_CKAN/Metadata/Ckan.pm#L283

Neat, I have ideas on how to support multiple download URLs (properly) and this is useful.

**Comment by techman83** [comment]
Neat! I think that'll solve a number of issues people see.

**Comment by mstrache** [comment]
Any development on this? CKAN is of limited use for more than a month now :/

**Comment by politas** [comment]
Now resolved by Spacedock
