### ISSUE TITLE
Stuck "Updating selected mods".

### ISSUE THREAD

**Issue by osmarks** [KSP-CKAN/CKAN#1951]
**CKAN Version:** 
1.20.1-0-gd41fe54 beta

**Operating System:** 
Void Linux, 4.8.11_1 kernel, mono version listed as mono-4.0.1.44_2.

**The issue you are experiencing:** 
When I apply changes to try and install a mod, it goes onto the mod download/installation screen but just says 'Updating selected mods'. The progress bar continues to scroll but it doesn't appear to be doing anything else. After quite a while it goes back to the main repository screen, with the selected mod unticked (and not installed), and oddly the Apply Changes button not greyed out (but when I click that, no mods are listed for updating).

**How to recreate this issue:** 
I'm not really sure about recreating it on all systems, but on my computer:

1. Open CKAN
2. Tick any mod's box
3. Try and apply changes.

**Comment by politas** [comment]
When it does that, you should have a new "Status Log" tab. That should give you an indication of what went wrong.

**Comment by osmarks** [comment]
It seems to work fine now for some reason.
