### ISSUE TITLE
Install failure resets all selected mods

### ISSUE THREAD

**Issue by mbartelsm** [KSP-CKAN/CKAN#1952]
Whenever an install fails for whatever reason, CKAN reverts back to mod selecting but you are unable to retry the install, and you cannot save the mod list because the mods were never installed. This means you lose all the mods you had selected.

This is particularly painful when you've been selecting mods for a new install for the las 30 minutes and it turns out that you have to do it all over again because CKAN found a conflict or it failed to download a mod.

It's even more painful when you've tried 3 different times and it has failed every time for different reasons.

Either allow players to save the list of selected mods (not installed mods) or fix the issue where players are unable to attempt to install mods again after a failure

Bonus points if you do both.

**Comment by Dazpoet** [comment]
I proposed a pseudosolution in https://github.com/KSP-CKAN/CKAN/issues/1395

**Comment by HebaruSan** [comment]
Should be fixed as of #2277. The change set is preserved on failure and you can just click Apply Changes to try again.
