### ISSUE TITLE
Stale locks under Linux

### ISSUE THREAD

**Issue by XANi** [KSP-CKAN/CKAN#1956]
If for any reason CKAN is not closed (occurs for example when I just shut down the system so ckan gets SIGTERM, just doesn't handle it) lockfile stays on disk, preventing next run until manual intervention. 

It should either:

* use "real" locking via [flock](http://man7.org/linux/man-pages/man2/flock.2.html) (dunno if C# exposes that interface tho)
* save pid of process in pidfile and exit with error only if that pid resolves to running ckan instance (if native locking is hard to do)

**Comment by politas** [comment]
I think we determined that native locking was not possible unless we write OS-specific code (and maybe not even then)

**Comment by politas** [comment]
It occurs to me that our lockfile handling seems like a good place to use a constructor and destructor on the registry class, and I don't think we're doing that.

**Comment by politas** [comment]
The idea of closing only if the PID matches the running instance will lead to inconsistencies when people mix running the GUI with using the CLI, and all the other reasons we put in the file locking code in the first place. It is possible to run multiple instances of CKAN.
