### ISSUE TITLE
Cannot start CKAN - .Net 4.5 is installed

### ISSUE THREAD

**Issue by TjarkLu** [KSP-CKAN/CKAN#1972]
**These are 2 of the 3 error files windows gave me after running it in administrator mode, i could not open or upload the third one, because its a .mdmp file**

[WER9C5.tmp.appcompat.txt](https://github.com/KSP-CKAN/CKAN/files/685468/WER9C5.tmp.appcompat.txt)

[WERFE00.tmp.WERInternalMetadata.xml.txt](https://github.com/KSP-CKAN/CKAN/files/685473/WERFE00.tmp.WERInternalMetadata.xml.txt)

**CKAN Version: 1.18.0 and 1.22.1** 

**Operating System: Windows 7 Home Premium Build 7601 SP1** 

**The issue you are experiencing: cannot start ckan: after doubleclicking the ckan.exe file a shell window appears and then another window appears saying ckan.exe stopped working** 

**How to recreate this issue: it happens every time I try to start ckan, I dont know what causes the crash, so i cant tell you how to recreate it on your side** 

I couldnt find help in your wiki or any guidelines, so i am trying it this way.

Thank you,
Tjark Lundt.

**Comment by politas** [comment]
Those files look like you're trying to open ckan.exe as a data file in some other program.

DO NOT RUN CKAN IN ADMINISTRATOR MODE!!!!!!!

**Comment by politas** [comment]
Open a command prompt and navigate to the folder where you have downloaded ckan.exe
Run the following commands

    ./ckan.exe version
    ./ckan.exe ksp list

And let us know what you get.

**Comment by TjarkLu** [comment]
I tried 
'./ckan.exe version'
but it tries to use '.' as a comman so i ran
'start ./ckan.exe version' and 'ckan.exe version'
which starts the program and it crashes as usual
using ksp list had the same results

**Comment by TjarkLu** [comment]
well, cmd accepts the command when I use backslash, but it still just starts the program, which stops working after a few seconds..

**Comment by politas** [comment]
If you right-click on ckan.exe in Explorer, what is Windows planning to use to open it?

**Comment by TjarkLu** [comment]
It shows the options 'Öffnen' (open) and 'Als Administrator ausführen' (run as administrator) 
There is no 'open with' option given
In properties it shows as file type 'Anwendung' (Application)
I am using a german version of Windows

**Comment by TjarkLu** [comment]
I just took a look at my system specifications and it says:
```
.NET Frameworks installed
	v4.6 Full
	v4.6 Client
	v3.5 SP1
	v3.0 SP2
	v2.0 SP2
```
But as I tried installing v4.5 three days ago it said
Dieselbe oder eine höhere Version der .NET Framework 4.5 wurde bereits auf diesem Computer installiert.
(The same or a higher version is already installed on this system) 
Therefore I assumed 4.5 to be installed, I will now delete all .NET versions, install v4.5 and give it another try

**Comment by politas** [comment]
It certainly looks like you have a problem in your .Net setup, but I'm far from an expert in that area. Maybe try some German-language Microsoft help resources?

**Comment by TjarkLu** [comment]
Okay, thank you for trying =)
I will let you know, if I find out what the issue is and how to solve it

**Comment by ayan4m1** [comment]
Might want to try uninstalling those 4.5 entries and see if [this](https://www.microsoft.com/en-us/download/details.aspx?id=42637) gives you a full .NET 4.5 install.
