### ISSUE TITLE
Downloads from ckan1.spacedock.info need to be redirected to Internet Archive

### ISSUE THREAD

**Issue by Argzero** [KSP-CKAN/CKAN#1977]

**Comment by politas** [comment]
Please don't shout. Which version of KSP are you using, that there are any mods on ckan1.spacedock.info you want to download?

**Comment by politas** [comment]
Ref KSP-CKAN/NetKAN#4664 it seems Spacedock have removed their copy of the kerbalstuff archive.

**Comment by Argzero** [comment]
My apologies. I was in a rush and had caps lock on.  KSP version 1.2.2

**Comment by politas** [comment]
There's a mod hosted on ckan1.spacedock.info that's compatible with KSP 1.2.2? Can you give us a list? We should prioritise them.

**Comment by techman83** [comment]
@politas let me take a looks see.

**Comment by techman83** [comment]
CKAN-meta done, script I used -> https://gist.github.com/techman83/2efcaa9b086b674368441aedf9860953

**Comment by Argzero** [comment]
I've been using some newer versions of some of these on 1.2.2. They seem to work fine. I'll put together a list including my sources once Ive finished setting up my KSP.
