### ISSUE TITLE
CKAN ERROR.ErrorDialog

### ISSUE THREAD

**Issue by LeakyAquitard** [KSP-CKAN/CKAN#1978]
Coding Noob Here,

I recently installed CKAN on my mac and installed several mods (21 to be exact). After installing these mods, I have not been able to open KSP (it stops loading at ~50%)

My idea was to go back into CKAN and unselect the mods, and see if this might remedy my situation, but when attempting to enter back into CKAN the following issue presents itself.

Apologies for the obviously noob post.

**CKAN Version:** 
Most up to date? MonoFrameWork-MDK-4.2.1.102
**Operating System:** 
El Capitan
**The issue you are experiencing:** 
Can not open CKAN
**How to recreate this issue:** 
LawrenclumsiMac:~ Manza$ cd Downloads
LawrenclumsiMac:Downloads Manza$ mono ckan.exe
**CKAN error codes (if applicable):** 
615 [1] ERROR CKAN.ErrorDialog (null) - CKAN is already running for this instance!

If you're certain this is not the case, then delete:
"/Users/Manza/Desktop/KSP/KSP_osx/CKAN/registry.locked"

**Comment by politas** [comment]
>If you're certain this is not the case, then delete:
>"/Users/Manza/Desktop/KSP/KSP_osx/CKAN/registry.locked"

Do that, then CKAN should load again.
