### ISSUE TITLE
I can't add new installs

### ISSUE THREAD

**Issue by JacobJHC** [KSP-CKAN/CKAN#1979]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**1.22.1** 

**Windows** 

**I cannot add new installs to the list of installs. When I click "add new" and find my folder it only opens it and gives me the option to select/open it. How do I add new installs?**

**Comment by politas** [comment]
Select the "buildID.txt" or "buildID64.txt"
