### ISSUE TITLE
error with downloading multiple mods installing and getting them running also very slow response time clientside 

### ISSUE THREAD

**Issue by xXDarkstormXx100** [KSP-CKAN/CKAN#1980]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.1 Gregory [v1.22.1-0-g174271a]
**Operating System:** 
windows 7 home premium 64 bit

**The issue you are experiencing:**  whenever i download or install a mod most of the time they error and dont download or install properly i think this is a bug with downloaidng older versions of certain mods because it forces them to be compatible with the current version of kerbal space program or whenever you try downloading multiple mods at once it just starts to go really slow and the process for completing and downloading and installing mods takes ages to compete 

**How to recreate this issue:** 
try downloading all mods like near future including ksp and see if you get the same issue or if its something wrong with the repository on there end 
**CKAN error codes (if applicable):** 
unhandled exception .net framework 4.5 not exactly sure what the error code is though sorry 🗡 

hope you guys can find a solution to my issue thanks in advance i would love to continue using this for mods if it wasnt for the hassle i am having i am having to put my ksp modding on hold for now

**Comment by politas** [comment]
Do you have .Net framework 4.5 installed? Windows 7 does not have that by default, you need to install it, as per the [release notes](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.22.1).

**Comment by xXDarkstormXx100** [comment]
it says i have it installed yet its giving me software issues

**Comment by politas** [comment]
Ok, well, we really need the actual error messages you are getting. It's really hard to know what's going wrong with your system otherwise. Also, please answer these questions:

- Have you selected multiple KSP versions to allow off-version installing?
- What are the mods you are installing?
- What version of KSP are you installing into?

Please note that upgrading mods and installing mods as a single action will almost always fail. That's a known bug.

**Comment by xXDarkstormXx100** [comment]
![untitled2222222222](https://cloud.githubusercontent.com/assets/25045391/21952153/f4e68d38-d9e2-11e6-972b-a84bdeb61203.png)

**Comment by xXDarkstormXx100** [comment]
kerbal space program 1.2.2

**Comment by politas** [comment]
Ah, it looks like your system is not trusting the Startcom signatures used by Spacedock

**Comment by valuial** [comment]
This problem will occure more often as Apple, Mozilla and Google stopped trusting StartCom after it being purchased by WoSign. See: https://en.wikipedia.org/wiki/StartCom#Trustworthiness
As I see it, this issue must be addressed by Spacedock - a change of CA might be in order.

**Comment by politas** [comment]
They are aware of the issue.

**Comment by xXDarkstormXx100** [comment]
thanks i well keep you guys infromed if i get any more problems
