### ISSUE TITLE
CKAN Cache Incorrectly Naming Archives After Being Downloaded, X Number of Cached Mods Installed

### ISSUE THREAD

**Issue by Tynrael** [KSP-CKAN/CKAN#1984]
I see some issues that seem similar but don't have a great many details or are a few months old, I'm hoping more and newer information may help fix this bug.

**CKAN Version:** 
1.22.1, 1.22.0, 1.20.1, 1.20.0 (didn't test any older)

**Operating System:** 
Windows10 x64

**The issue you are experiencing:**
After a certain number of mods are downloaded/added to the cache, the cache appears to start mixing up the archives and what they actually contain. This happens both when downloading around 20+ mods at a time as well as when attempting to update later when a number of mods are already installed. I was able to get about 90 mods installed 1 at a time but then to update them later I had to do it 1 at a time and even then I had to delete the cache file for some mods at least once until it was downloaded and cached correctly. In my example here the following is noted, in the install order:

Action Groups Extended is correct
Module Manager is correct
Alternate Resource Panel is correct
AmpYear is correct
REPOSoftTech-Agencies is correct
AntennaSleep is correct
AtmosphereAutopilot is correct
BetterBurn Time is correct
     _**_____Better Science Labs Continued is SpacetuxSA**_
     _**_____SpaceTuxSA is EasyBoard**_
BZ-1 Radial Attachment Point is correct
Chatterer is correct
Docking Port Alignment Indicator is correct
     _**_____EasyBoard is Editor Extensions Redux**_
Easy Vessel Switch is correct
     _**_____Editor Extensions Redux is Engine Lighting**_
     _**_____Engine Lighting is EVA Enhancements Continued**_
     _**_____EVA Enhancements Continued is Final Frontier**_
Experiment Tracker is correct
Final Frontier is correct

Better Science Labs Continued, Editor Extensions Redux, and Engine Lighting are all the mod that comes after them in the install order. Final Fronter both exists correctly as itself and is in EVA Enhancements Continued. These mods themselves are correct and downloading from the link listed when they are being downloaded results in the correct mod and archive.

There is an option to "Continue" after the JIT error but it will only freeze CKAN which will then have to be force closed. The error prevents any mods from actually being installed.

**How to recreate this issue:** 
Install the 20 mod list provided with this Issue (~13MB).

**CKAN error codes (if applicable):**
CKAN.FileNotFoundKraken: Could not find Better Science Labs Continued entry in zipfile

[Tynrael_CKAN_CRASH.zip](https://github.com/KSP-CKAN/CKAN/files/705474/Tynrael_CKAN_CRASH.zip)
![tynrael_ckan_crash_image](https://cloud.githubusercontent.com/assets/13883892/21947909/b5f16378-d9b5-11e6-95ed-84e89fc8d69e.JPG)

**Comment by Tynrael** [comment]
I'm not sure what the hex means before the cache archives but adding this in case it might help explain some kind of order issues:
![tynrael_archivetitles](https://cloud.githubusercontent.com/assets/13883892/21948241/d5eb0de4-d9b7-11e6-9541-e10dbc63b70d.JPG)

**Comment by politas** [comment]
The Hex code is a SHA1 hash of the file contents (or it's supposed to be), which is how CKAN searches for existing cached copies.

**Comment by Tynrael** [comment]
I'm started to think this might be related to multiple downloads from the same location (spacedock, github, etc...). It seems like if there are too many connections some of them may stutter or might be throttled server side, when I was breaking up my modlist of over 100 mods into pieces I found some of the ones that messed up in this way toward the end dipped down to 0k/s for download. I think some of the downloads may be doing this in general and you just can't tell because the overall download speed masks it so the individual troublesome downloads are not seen. I'm not sure why this would shuffle around mods or mess with the hash.

8C8F9477 is the correct hash for BetterScienceLabsContinued when it is correctly installed but was also the same when it contained SpaceTuxSA instead of the intended mod.

Would there be a way to download in serial and see if that had the same problem?

**Comment by politas** [comment]
Ok, so the hashes are matching the filenames rather than the contents. Can I ask what OS you are using?

**Comment by Tynrael** [comment]
Trying to test if the bandwidth could be the cause I brought my personal computer to work so I have been able to get these results:

Work Network (300+Mbps):
Windows 7 Professional x64, Full 94 Mod List w/o Issue
Windows 10 x64, Full 94 Mod List w/o Issue

Home Network (25Mbps):
Windows 10 x64, Full 94 Mod List FAIL
Windows 10x 64, 20 Mod Sample (included here) FAIL

I'll try bringing my Windows 7 machine home tonight and seeing if it has different results on my slower network.

**Comment by Tynrael** [comment]
OK so I was ready to lose my mind after it worked on 3 different computers but not on the desktop I actually play on. I disabled my anti-virus and then everything worked fine... Thanks and closing this!

**Comment by politas** [comment]
Ah, the antivirus must have been taking over the downloads.
