### ISSUE TITLE
Latest version just stopped working: Fedora 25

### ISSUE THREAD

**Issue by alan12345678** [KSP-CKAN/CKAN#1985]
Have been using ckan for a couple of weeks, running under mono. From the terminal it would always open with an error window "TrustFailure (The authentication or decryption has failed)" but clicking "dismiss" meant it would open, and I could work with my mods as necessary.

This morning I update to the latest Fedora packages (as I do every morning), and after a restart my terminal command brings up the same error window, but ckan doesn't work any more, as it simply flashes very quickly as it opens and then crashes.

Is there something else I need to change/configure/refresh in order to get this working again? I was just starting to love it!

The terminal window does bring up a LONG list of error codes. Happy to post it here but only if helpful

**Comment by politas** [comment]
Spacedock's SSL certificates are issued by a CA that is no longer being trusted by default.

**Comment by politas** [comment]
Spacedock have now moved to a trusted certificate, so this should be resolved.
