### ISSUE TITLE
CKAN Spontaneously Closing on MacOS

### ISSUE THREAD

**Issue by corbincox72** [KSP-CKAN/CKAN#1990]
CKAN Version: 1.22.1
Operating System: MacOS Sierra 10.12.2

Upon opening the GUI for the latest version of CKAN, the app loads for roughly 0.5s, displaying the list of installed mods, and immediately crashes. "registry.locked" is also deleted when the app crashes. No error messages are displayed. This began occurring spontaneously; I had not, to my knowledge, updated my computer, mono, or CKAN when the crashes began. I have tried re-booting my computer, and I have re-downloaded CKAN.

**Comment by politas** [comment]
Can you open a terminal and run `mono <path to ckan.exe location>/ckan.exe update`

**Comment by corbincox72** [comment]
That worked! Thank you so much!
