### ISSUE TITLE
AVC Transformer does not apply filters when searching for .version files which would be installed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#1996]
Running netkan.exe on a new file, got the following error:

1120 [1] WARN CKAN.NetKAN.Transformers.SpacedockTransformer (null) - Could not normalize URL:
5209 [1] FATAL CKAN.NetKAN.Program (null) - Too may .version files located: REKT-0.4.3.1/RetractableLiftingSurface/RetractableLiftingSurface.version, REKT-0.4.3.1/SHED/rekt.version

**Comment by politas** [comment]
This seems to have sorted itself out?

**Comment by linuxgurugamer** [comment]
Yes, by specifying the .version file specifically

**Comment by politas** [comment]
Looking at REKT, it looks like the search for .version files is ignoring the filter. I'm sorry, I was looking at RetractableLiftingSurfaces rather than REKT before.
