### ISSUE TITLE
System.ArgumentOutOfRangeException when uninstalling AFBW and/or Toolbar

### ISSUE THREAD

**Issue by JoshKeaper** [KSP-CKAN/CKAN#1998]
**CKAN Version:** v1.22.1-0-g174271a (beta)

**Operating System:** Windows 8.1 x64

**The issue you are experiencing:** 

Two addons, `Toolbar` and `AdvancedFlyByWire`, seem to become interlocked in some way on my system, preventing uninstallation of any (or both) of them, even after `GameData` directory is cleared (except `Squad`).

When unticking any of them in GUI (*Filter: All* to show outdated AFBW), the *Apply changes* button turns green as usual, but when both are unticked, it turns gray again, like there is nothing to change. When I try to untick just one of them (any one) and apply changes, CKAN always lists AFBW for removal (solely, when AFBW is unticked, or together with Toolbar, when Toolbar is unticked), and when I proceed to removal, it throws an exception:
<details><summary>Expand</summary><pre>
Подробная информация об использовании оперативной 
(JIT) отладки вместо данного диалогового 
окна содержится в конце этого сообщения.

************** Текст исключения **************
System.ArgumentOutOfRangeException: Индекс и показание счетчика должны указывать на позицию в строке.
Имя параметра: count
   в System.String.Remove(Int32 startIndex, Int32 count)
   в CKAN.KSPPathUtils.ToRelative(String path, String root)
   в CKAN.ModuleInstaller.<AddParentDirectories>c__AnonStorey0.<>m__0(String dir)
   в System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   в System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   в System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   в System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqualityComparer`1 comparer)
   в CKAN.ModuleInstaller.AddParentDirectories(HashSet`1 directories)
   в CKAN.ModuleInstaller.Uninstall(String modName)
   в CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   в CKAN.Main.WasSuccessful(Action action)
   в CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   в System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   в System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)

************** Загруженные сборки **************
mscorlib
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    Версия сборки: 0.0.0.0
    Версия Win32: 0.0.0.0
    CodeBase: file:///C:/Utils/CKAN/ckan.exe
----------------------------------------
System.Configuration
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Core
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Windows.Forms.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    Версия сборки: 1.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Xml.Linq
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll
----------------------------------------
System.Data
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Версия сборки: 0.0.0.0
    Версия Win32: 4.6.1087.0 built by: NETFXREL4STAGE
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_ru_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------
System.EnterpriseServices
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll
----------------------------------------
System.resources
    Версия сборки: 4.0.0.0
    Версия Win32: 4.6.1055.0 built by: NETFXREL2
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.resources/v4.0_4.0.0.0_ru_b77a5c561934e089/System.resources.dll
----------------------------------------
Accessibility
    Версия сборки: 4.0.0.0
    Версия Win32: 4.0.30319.33440 built by: FX45W81RTMREL
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
----------------------------------------

************** Оперативная отладка (JIT) **************
Для подключения оперативной (JIT) отладки файл .config данного
приложения или компьютера (machine.config) должен иметь
значение jitDebugging, установленное в секции system.windows.forms.
Приложение также должно быть скомпилировано с включенной
отладкой.

Например:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

При включенной отладке JIT любое необрабатываемое исключение
пересылается отладчику JIT, зарегистрированному на данном компьютере,
вместо того чтобы обрабатываться данным диалоговым окном.
</pre></details>

Same thing happens when trying to remove any of the mods through command line:
<details><summary>Expand</summary><pre>
C:\Utils\CKAN>ckan.exe remove AdvancedFlyByWire
About to remove:

 * Advanced Fly-By-Wire (Windows, x86) 1.6.2

Continue? [Y/n] y
Removing AdvancedFlyByWire...
4554 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire : Файл 'c:\program files (x86)\steam\SteamApps\common\Kerbal Space Prog
ram\GameData\ksp-advanced-flybywire' не найден.
4576 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire/AdvancedFly-By-Wire.version : Не удалось найти часть пути "c:\program f
iles (x86)\steam\SteamApps\common\Kerbal Space Program\GameData\ksp-advanced-fly
bywire\AdvancedFly-By-Wire.version".
4578 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire/ksp-advanced-flybywire.dll : Не удалось найти часть пути "c:\program fi
les (x86)\steam\SteamApps\common\Kerbal Space Program\GameData\ksp-advanced-flyb
ywire\ksp-advanced-flybywire.dll".
4580 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire/LICENSE : Не удалось найти часть пути "c:\program files (x86)\steam\Ste
amApps\common\Kerbal Space Program\GameData\ksp-advanced-flybywire\LICENSE".
4582 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire/toolbar_btn.png : Не удалось найти часть пути "c:\program files (x86)\s
team\SteamApps\common\Kerbal Space Program\GameData\ksp-advanced-flybywire\toolb
ar_btn.png".
4584 [1] ERROR CKAN.ModuleInstaller (null) - Failure in locating file c:/program
 files (x86)/steam/SteamApps/common/Kerbal Space Program/GameData/ksp-advanced-f
lybywire/XInputDotNetPure.dll : Не удалось найти часть пути "c:\program files (x
86)\steam\SteamApps\common\Kerbal Space Program\GameData\ksp-advanced-flybywire\
XInputDotNetPure.dll".

Необработанное исключение: System.ArgumentOutOfRangeException: Индекс и показани
е счетчика должны указывать на позицию в строке.
Имя параметра: count
   в System.String.Remove(Int32 startIndex, Int32 count)
   в CKAN.KSPPathUtils.ToRelative(String path, String root)
   в CKAN.ModuleInstaller.<AddParentDirectories>c__AnonStorey0.<>m__0(String dir
)
   в System.Linq.Enumerable.<SelectManyIterator>d__16`2.MoveNext()
   в System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   в System.Collections.Generic.HashSet`1.UnionWith(IEnumerable`1 other)
   в System.Collections.Generic.HashSet`1..ctor(IEnumerable`1 collection, IEqual
ityComparer`1 comparer)
   в CKAN.ModuleInstaller.AddParentDirectories(HashSet`1 directories)
   в CKAN.ModuleInstaller.Uninstall(String modName)
   в CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   в CKAN.CmdLine.Remove.RunCommand(KSP ksp, Object raw_options)
   в CKAN.CmdLine.MainClass.RunAction(Options cmdline, CommonOptions options, St
ring[] args, IUser user, KSPManager manager)
   в CKAN.CmdLine.MainClass.Main(String[] args)
</pre></details>

**My current addon list (according to CKAN):**
<pre>
X AdvancedFlyByWire 1.6.2
- KSPSteamCtrlr autodetected dll
- Steamworks autodetected dll
- Toolbar 1.7.13
</pre>

**How to recreate this issue:** 

Initially, there was another issue: `CKAN.ModuleNotFoundKraken: Cannot install AdvancedFlyByWire, module not available` when trying to install an unrelated mod `Precise Maneuver`. I've also had a bunch of other mods at the moment, so I've followed [an advice](https://github.com/KSP-CKAN/CKAN/issues/1864#issuecomment-240086117) from #1864 and uninstalled/removed all of them, stumbling upon these problematic ones, AFBW and Toolbar, which didn't want to be uninstalled. I've cleaned out `GameData` directory, leaving only `Squad`. But these two mods are still listed in CKAN for some reason. `ckan repair registry` hasn't changed anything. There is nothing else to remove or uninstall.

AFBW was initially installed a long time ago, when it was still listed as `compatible` in CKAN. Afterwards, when it was delisted, I've overwritten it with an updated version manually (or through ModAdmin). Then, when `PreciseNode` was superceded by `Precise Maneuver`, I've tried to install the latter, and got `CKAN.ModuleNotFoundKraken` mentioning AFBW. Manual removal of AFBW hasn't changed anything.

CKAN exported mod list: [ckan-mods-backup-29-01-2017.ckan.txt](https://github.com/KSP-CKAN/CKAN/files/737273/ckan-mods-backup-29-01-2017.ckan.txt)

**Comment by politas** [comment]
If you have deleted all mods from GameData and mods are still showing, the easist fix would be to delete CKAN/registry.json before reinstalling mods.

**Comment by JoshKeaper** [comment]
It worked, thank you.
