### ISSUE TITLE
Running ./build script errors out

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#1999]
**Operating System:** 
Windows 7 64 bit SP1

**The issue you are experiencing:** 
The build script supplied with the main repo fails to run, instead generating errors indicating the line 12 is not operating as intended.

**How to recreate this issue:** 
Fork the CKAN repo, clone that repo to your hard drive (presumably windows OS required). 
In PowerShell, run ./build in the directory you cloned the repo to. 

**Notes**
This is line 12 of the build.ps1 included with the repo. 
`$RootDir            = "${PSScriptRoot}"`
Changing the value to the actual location of the script file allowed the script to run. Testing on my windows machine indicated the value it was returning had been null.

**Comment by dbent** [comment]
Presumably you're using PowerShell 2.0? You need to upgrade, 5.1 is the most recent version: https://www.microsoft.com/en-us/download/details.aspx?id=54616

**Comment by Blu3wolf** [comment]
Well that clears it up! Thanks muchly!

**Comment by Blu3wolf** [comment]
Well that clears it up! Thanks muchly!
