### ISSUE TITLE
Error: CKAN is already running for this instance!

### ISSUE THREAD

**Issue by renoplane** [KSP-CKAN/CKAN#2001]
Every time I launch CKAN, I get this error message: 

**Error: CKAN is already running for this instance! If you're certain this is not the case, then delete: "C:/Games/KSP Reality Overhaul/CKAN\registry.locked**

I can get CKAN to start by deleting that file, but it is really inconvenient to do that every time I start CKAN so I am hoping there is a fix.

I am running the latest version of CKAN on 64-bit Windows 10.

**Comment by solarsootysmudge** [comment]
I believe this is a protection to stop two copies CKAN running whilst both trying to access the same game folder. Which would be a bad thing. 

Normally when that message appears. It indicates CKAN is already running in windows 10. There should be the icon the tool bar and the program can be found in the task manager. If for some reason the app crashes. There may be a need to delete registry.locked but it should be quite rare for this to happen. Just switch to already running copy of CKAN.

If you always get the message then that would suggest the application is not shutting down correctly.

**Comment by renoplane** [comment]
I've checked the processes in task manager before opening it and there wasn't any instance I could find. This has been happening for a very long time, even after a restart CKAN gives this error.

**Comment by politas** [comment]
If CKAN crashes, the lockfile will be left behind, and you will need to manually delete it. If CKAN is shut down normally, the lockfile should be destroyed.
