### ISSUE TITLE
CKAN.exe missing

### ISSUE THREAD

**Issue by weaselslider** [KSP-CKAN/CKAN#2002]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**1.22.1** 

**Windows 10** 

**Before installing, there seems to be no CKAN.exe for me to install** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by Commissar0617** [comment]
sure you got the right ckan?

**Comment by politas** [comment]
You'll need to download ckan.exe from [the releases page](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.22.1).
