### ISSUE TITLE
CKAN commandline treats recommends as depends

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#2004]
v1.22.1-0-g174271a (beta)

Windows 7 x64 SP1

Trying to install SVE without also installing SVT

Reproduce by opening the command line, then give it 

` ckan install SVE-HighResolution `

You get back the prompt for which sunflare to use. 

` 2 `

(AstroNiki sunflare is OP, nerf plz)

You get the prompt for which SVT to install (this is a recommends item according to the .ckan here: https://github.com/KSP-CKAN/CKAN-meta/blob/master/SVE-HighResolution/SVE-HighResolution-2-1.1.6.ckan )

pressing n or c cancels the entire install, rather than deselecting the recommends item, as per the GUI behavior. Yes, I can just run ` ckan install SVE-HighResolution --no-recommends ` but the behavior should match the GUI in this respect.

**Comment by HebaruSan** [comment]
Closing this in favor of #965, which requested the same thing; please direct any further updates to that issue.
