### ISSUE TITLE
CKAN 'Failed to connect to repository'

### ISSUE THREAD

**Issue by Swiftus** [KSP-CKAN/CKAN#2005]
I scrolled through the list of solved issues and I wasn't able to identify a solution which produced a positive result for my issue.

**CKAN Version:** 
v1.22.1-0-g174271a (beta)
**Operating System:** 
Windows 7
**The issue you are experiencing:** 
At CKAN startup getting 'Failed to connect to repository' popup dialog. Mods are no longer updating, but I am able to download and install the latest version of a mod from the 'Manage mods' tab if it existed in that list from before this issue started (about 1 week ago).

The metadata repository address is: https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz
**How to recreate this issue:** 
At start of CKAN.
**CKAN error codes (if applicable):** 
'Failed to connect to repository'

**Comment by politas** [comment]
Is this still failing? This usually indicates a network or github.com glitch.

**Comment by Klakh** [comment]
Hi, I have a similar issue, when I launch CKAN or Refresh mods. I noticed that installed mods won't update anymore, but I can still install mods. And I would guess that if I uninstalled one, deleted the .zip from CKAN cache, and reinstalling it, it would install the right version. 

What it says is this : 
"Failed to connect to repository. Exception: Trying to write C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/GroundConstruction/Icons/toolbar-icon.png but it already exists."

**Comment by Klakh** [comment]
I just resolved mine by : 
- Launching CKAN
- Unticking "USI MKS/OKS" and "Ground Constructions" mods
- Applying the update (uninstalling the mods)
- Refreshing CKAN.
Bam :) all my mods now have available updates. I even reinstalled MKS/OKS after the facts, and it still refreshes :)
