### ISSUE TITLE
Error when updating mods: "Looks like you're trying to install a mod that's already installed"

### ISSUE THREAD

**Issue by beanaroo** [KSP-CKAN/CKAN#2008]
**CKAN Version:** 1.22.1

**Operating System:** Windows 10 64bit

**The issue you are experiencing:** 
Often when I "Add available updates", the following installation error occurs:

![ckan_error](https://cloud.githubusercontent.com/assets/1748909/23091483/ff2e3232-f61b-11e6-9b40-a0edda2fe6fa.png)

```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CKAN.Main._MarkModForUpdate(String identifier)
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.PostInstallMods(Object sender, RunWorkerCompletedEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
````

Everytime, the file was installed by the mod being updated. All mods are managed by CKAN.

**How to recreate this issue:**  Update installed mods.

**Comment by politas** [comment]
If you are getting a lot of these, try uninstalling and reinstalling the affected mods rather than updating.
