### ISSUE TITLE
Module required but not listed in index

### ISSUE THREAD

**Issue by rottielover** [KSP-CKAN/CKAN#2013]
**CKAN Version:** 
1.22
**Operating System:** 
Windows 10 64bit
**The issue you are experiencing:** 
After using ckan for months now I can't upgrade mods
**How to recreate this issue:** 
Unsure
**CKAN error codes (if applicable):** 
Module GroundConstruction-Core required but it is not listed in the index, or not available for your version of KSP.

**Comment by Commissar0617** [comment]
#2003

**Comment by newtie2000** [comment]
I am getting this exact same error type while trying to update TAC-LS 

Module BackGroundResources required but it is not listed in the index, or not available for your version of KSP.
