### ISSUE TITLE
Crash on Arch Linux when pressing super (windows) key

### ISSUE THREAD

**Issue by timlyo** [KSP-CKAN/CKAN#2014]
**CKAN Version: 1.22.1** 

**Operating System: Linux 4.9.11** 

**The issue you are experiencing: Crash when changing windowing mod** 

**Mono version: 4.6.1.3**

**How to recreate this issue: Run ckan on linux and press super** 

I've included the stack trace here: https://gist.github.com/timlyo/53712dff9d83b38a1bafd746436a090e

Let me know if there's any more information required or anything else I can test.

Note: edited when I realised what the actual trigger was

**Comment by timlyo** [comment]
I've just cloned and compiled master and I can replicate the issue.

**Comment by Magnap** [comment]
This may be a Mono bug rather than a CKAN bug, I've just had the
```
=================================================================
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.
=================================================================
```
error/crash happen with KSP Mod Admin too, with the same trigger.

**Comment by timlyo** [comment]
This looks related

https://bugzilla.xamarin.com/show_bug.cgi?id=41505

**Comment by politas** [comment]
Can you get a Mono package from mono-project.com for Arch Linux? It seems clear that the problem you have is with Mono, not CKAN. CKAN does not have any code that targets the super key.
