### ISSUE TITLE
Cannot run with Mono on 16.04

### ISSUE THREAD

**Issue by raghur** [KSP-CKAN/CKAN#2015]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.1
**Operating System:** 
Linux mint 18

**The issue you are experiencing:** 
error on running `mono ckan.exe`
```
Unhandled exception:
System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x0400100a
  at Newtonsoft.Json.JsonWriter.BuildStateArray () [0x0001b] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at Newtonsoft.Json.JsonWriter..cctor () [0x000b3] in <db7f644cef3d44268a3a52ddab219b4b>:0 
   --- End of inner exception stack trace ---
  at Newtonsoft.Json.JsonTextWriter..ctor (System.IO.TextWriter textWriter) [0x00000] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager.Serialize () [0x0000e] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager.Save (System.Boolean enforce_consistency, System.Boolean recommmends, System.Boolean with_versions) [0x00082] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager.Create () [0x00021] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager.LoadOrCreate () [0x00010] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager..ctor (System.String path, CKAN.KSP ksp) [0x00063] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.RegistryManager.Instance (CKAN.KSP ksp) [0x00029] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.Main..ctor (System.String[] cmdlineArgs, CKAN.GUIUser user, System.Boolean showConsole) [0x00156] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at (wrapper remoting-invoke-with-check) CKAN.Main:.ctor (string[],CKAN.GUIUser,bool)
  at CKAN.GUI.Main_ (System.String[] args, System.Boolean showConsole) [0x00057] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.CmdLine.MainClass.Gui (CKAN.CmdLine.GuiOptions options, System.String[] args) [0x00008] in <db7f644cef3d44268a3a52ddab219b4b>:0 
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x000a1] in <db7f644cef3d44268a3a52ddab219b4b>:0  
```
**How to recreate this issue:** 
mono ckan.exe

**CKAN error codes (if applicable):** 
NA

mono updated to latest -
```
mono --version
Mono JIT compiler version 4.8.0 (Stable 4.8.0.495/e4a3cf3 Wed Feb 22 18:30:58 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
        TLS:           __thread
        SIGSEGV:       altstack
        Notifications: epoll
        Architecture:  amd64
        Disabled:      none
        Misc:          softdebug 
        LLVM:          supported, not enabled.
        GC:            sgen
```

**Comment by politas** [comment]
Can you post the results of `mono ckan.exe --debug` (preferably in a pastebin or such)

**Comment by raghur** [comment]
no idea what changed - but ckan ran without issues today...

**Comment by nmichaels** [comment]
I'm getting this error on my Debian testing system.

> $ mono --version
> Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1)
> Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
> 	TLS:           __thread
> 	SIGSEGV:       altstack
> 	Notifications: epoll
> 	Architecture:  amd64
> 	Disabled:      none
> 	Misc:          softdebug 
> 	LLVM:          supported, not enabled.
> 	GC:            sgen

I get this error when I select the buildID.txt from my KSP_linux directory. I've tried with KSP version 1.2.1 and 1.2.2 installs.

> $ mono ./ckan.exe 
> System.TypeInitializationException: The type initializer for 'Newtonsoft.Json.JsonWriter' threw an exception. ---> System.BadImageFormatException: Could not resolve field token 0x0400100a
>   at Newtonsoft.Json.JsonWriter.BuildStateArray () [0x0001b] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at Newtonsoft.Json.JsonWriter..cctor () [0x000b3] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>    --- End of inner exception stack trace ---
>   at Newtonsoft.Json.JsonTextWriter..ctor (System.IO.TextWriter textWriter) [0x00000] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager.Serialize () [0x0000e] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager.Save (System.Boolean enforce_consistency, System.Boolean recommmends, System.Boolean with_versions) [0x00082] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager.Create () [0x00021] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager.LoadOrCreate () [0x00010] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager..ctor (System.String path, CKAN.KSP ksp) [0x00063] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.RegistryManager.Instance (CKAN.KSP ksp) [0x00029] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.KSP.ScanGameData () [0x00001] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.KSP.Init () [0x0007e] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.KSP..ctor (System.String gameDir, CKAN.IUser user) [0x00042] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at CKAN.ChooseKSPInstance.AddNewButton_Click (System.Object sender, System.EventArgs e) [0x00043] in <db7f644cef3d44268a3a52ddab219b4b>:0 
>   at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001c] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00024] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ButtonBase.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00081] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WmLButtonUp (System.Windows.Forms.Message& m) [0x0007e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x0016f] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0004e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlWindowTarget.OnMessage (System.Windows.Forms.Message& m) [0x00000] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x0000b] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0 
>   at System.Windows.Forms.NativeWindow.WndProc (System.IntPtr hWnd, System.Windows.Forms.Msg msg, System.IntPtr wParam, System.IntPtr lParam) [0x0008e] in <d5b72d15d4f7424c8a1538e3f19ec2e3>:0
