### ISSUE TITLE
Ckan won't start

### ISSUE THREAD

**Issue by Sparkly-Panda** [KSP-CKAN/CKAN#2020]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
Should be the latest but i can't check

**Operating System:** 
Mac OS X El Capitan

**The issue you are experiencing:** 
I loaded CKAN a few days ago, then tried to reopen it but it gave me 
(computer name)$ rm /Users/ejahn/Library/Application\ Support/Steam/SteamApps/common/Kerbal\ Space\ Program/CKAN/registry.json.locked
rm: /Users/ejahn/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN/registry.json.locked: No such file or directory
(computer name)$ cd downloads
(computer name):downloads ejahn$ mono ckan.exe
634 [1] ERROR CKAN.ErrorDialog (null) - CKAN is already running for this instance!

If you're certain this is not the case, then delete:
"/Users/(name)/Library/Application Support/Steam/SteamApps/common/Kerbal Space Program/CKAN/registry.locked" "

**Comment by mrmodji** [comment]
Delete the indicated file and it should be fine.

**Comment by Sparkly-Panda** [comment]
Thats what the first line is, but then it comes back and says that there's no such file

**Comment by politas** [comment]
It looks like you may be entering the path incorrectly. Does MacOS command line provide tab completion of directories? That should help you get to the file to delete it.

**Comment by Sparkly-Panda** [comment]
Thank you, all working!
