### ISSUE TITLE
Some mods uninstalled through CKAN become Auto-Detected, despite having no files that I can find.

### ISSUE THREAD

**Issue by Rcannon95** [KSP-CKAN/CKAN#2021]
**CKAN Version:**
1.22.1-0-g:174271a(Beta)

**OS:** 
Win 10 64bit

**The Issue:**
When uninstalling some mods, they will become autodetected, despite having no files that I can find. I will uninstall a mod like EVA Enhancements or Kerbal Flight Indicators, they will have no files, but CKAN lists them as A-D and prevents me from uninstalling them or removing them. Is there any way to have CKAN show all the files it is detecting, Force delete files, or force install the latest version regardless of the compatible KSP Version? Another issue I have is my Module Manager broke in CKAN, so it is constantly A-D, despite deleting it several times, so I have to manually update it.

**How to recreate this issue:**
Not Sure, it happened when I uninstalled EVA Enhancements and Kerbal Flight Indicators.

**Comment by politas** [comment]
Can you upload your registry.json file?

**Comment by Rcannon95** [comment]
I had to change the extension to .txt to upload it, otherwise it is unchanged.
[registry.json.txt](https://github.com/KSP-CKAN/CKAN/files/835529/registry.json.txt)

**Comment by politas** [comment]
Ok, so this is the bit of your registry that tells CKAN you have those two mods installed:

    "installed_dlls": {
		"ModuleManager": "GameData/ModuleManager.2.7.5.dll",
		"Engineer": "GameData/KerboKatz/engineer/kerdlls/Engineer.dll",
		"EngineerToolbar": "GameData/KerboKatz/engineer/kerdlls/EngineerToolbar.dll",
		"DatedQuickSaves": "GameData/KerboKatz/DatedQuickSaves/DatedQuickSaves.dll",
		"DistantObject": "GameData/KerboKatz/DistantObject/DistantObject.dll",
		"EVAEnhancements": "GameData/KerboKatz/EVAEnhancements/EVAEnhancements.dll",
		"G-Effects": "GameData/KerboKatz/G-Effects/Plugins/G-Effects.dll",
		"KerbalEngineer": "GameData/KerboKatz/KerbalEngineer/KerbalEngineer.Unity.dll",
		"MiniAVC": "GameData/KerboKatz/KerbalEngineer/MiniAVC.dll",
		"KerbalFlightIndicators": "GameData/KerboKatz/KerbalFlightIndicators/Plugins/KerbalFlightIndicators.dll",
		"KSPTOTConnect": "GameData/KSPTOTConnect/Plugins/KSPTOTConnect.dll",
		"KSPSteamCtrlr": "GameData/Squad/Plugins/KSPSteamCtrlr.dll",
		"Steamworks": "GameData/Squad/Plugins/Steamworks.NET.dll",
		"Telemachus": "GameData/Telemachus/Plugins/Telemachus.dll",
		"websocket-sharp": "GameData/Telemachus/Plugins/websocket-sharp.dll",
		"VVDiscoDisplay - Copy": "GameData/VesselView/Plugins/VVDiscoDisplay - Copy.dll"
	},

That shows you the paths that CKAN has found the files in. Can you confirm there is no KerboKatz directory with those subdirs?

**Comment by Rcannon95** [comment]
You were right, they were hidden in subdirectories, deleting them fixed it. I apologize for the trouble I caused. The only thing I need to figure out how to fix now is the ModuleManager install.

**Comment by politas** [comment]
To get ModuleManager back under CKAN, you'll need to export your mod list as favourites, uninstall everything that depends on ModuleManager, delete ModuleManager, restart CKAN, refresh and then reinstall from the favourites .ckan
