### ISSUE TITLE
CKAN Does Not Work With OpenSSL v1.1

### ISSUE THREAD

**Issue by cedenday** [KSP-CKAN/CKAN#2038]
CKAN Version: v1.22.1

Operating System: Arch Linux

The issue you are experiencing:
CKAN does not work with OpenSSL v1.1.0.e.

How to recreate this issue:
1. Upgrade OpenSSL to OpenSSL v1.1.0.e.
2. Verify that any older versions of OpenSSL are removed.
3. Open CKAN: `$ mono ckan.exe`.
4. Try to download a package.

Error codes (if applicable):
  Example of downloading BetterBurnTime:
    `104337 [1] ERROR CKAN.ErrorDialog (null) - Failed to download 
    "https://spacedock.info/mod/21/BetterBurnTime/download/1.5.3" - error: SslConnectError`

**Comment by lamont-granquist** [comment]
spacedock is down

**Comment by Ruedii** [comment]
I think it might be good to set up a mirror system that allows developers to list multiple mod locations, to reduce this issue.

Should I file a feature request?

**Comment by techman83** [comment]
@Ruedii we do already mirror all foss mods KSP-CKAN/CKAN#1682 Supporting multiple download links is definitely something we'd like the client to support.

**Comment by Ruedii** [comment]
So you already mirror ones with the properly permissive license you just need the multiple link mechanism.

So half the work is done.  That's nice.
