### ISSUE TITLE
[Feature] List unmanaged directories (not associated with CKAN-installed mods)

### ISSUE THREAD

**Issue by hrobertson** [KSP-CKAN/CKAN#2045]
I have a handful of mods installed manually either because they're betas not in CKAN yet, or other such scenarios.

Checking these mods for updates first requires me to try to identify them from among my predominantly CKAN managed GameData directory.
If all mods were installed in a directory matching the mod name this wouldn't be so hard. However the reality is that some mods live under a directory named after their author and others named after a fictional corporation name.

I think it would be a useful feature if CKAN could output a list of the directories under GameData that do not correspond to CKAN-installed mods.

**Comment by HebaruSan** [comment]
Rather than just a list of directories, it would be neat to see a file tree like the Contents tab got in #3638:

![image](https://user-images.githubusercontent.com/1559108/234445431-0bfda15c-e5a6-49c1-b33f-2b4700155984.png)

**Comment by HebaruSan** [comment]
There's a subtle design choice here: Do we limit the display to GameData (or equivalent) only, or do we show the whole game folder?

If we show only GameData, then we potentially miss files installed to other folders, such as `Ships` or Soundtrack Editor. But it we show everything, 

The most obvious compromise is to show the whole list, but collapse all folders except GameData by default.
