### ISSUE TITLE
Selecting a particular mod bugs the install process

### ISSUE THREAD

**Issue by xenoflot** [KSP-CKAN/CKAN#2046]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.1-0-g174271a(beta)

**Operating System:** 
Win10

**The issue you are experiencing:** 
I was running through the CKAN list, selecting mods for install then when I went to hit Apply Changes, it was greyed out. I finally tracked it down to one particular mod, that when selected for installation, causes the Apply button to be greyed, and the Changeset tab to disappear.

FuelWings by BeautiCode, ver 3.2c

It appears that by de-selecting FuelWings, it returns to normal operation.
I have NOT disabled everything to see if FuelWings can be installed by itself.

edit: Also seems to happen with linuxgurugamer's "FuseBox Contined" 0.1.9 and "Modular Fuel Tanks" by taniwha et al. v5.8.3
Note: I *am* able to select more mods, mods from further down the list, and mods that are much larger, so it's not that I'm hitting a max_mods cap or max size cap.

**How to recreate this issue:** 

Install some mods then select FuelWings for installation. 
Apply button should grey out and Changeset tab disappear.

**CKAN error codes (if applicable):** 
No error codes or alerts generated. Can't find any CKAN log files.

**Comment by politas** [comment]
One of your other mods must have a conflict with Modular Fuel Tanks. If you select Modular Fuel Tanks, and click on the selection column to sort all selected mods together, the conflicting mod should show up in red.
