### ISSUE TITLE
Update wiki build instructions for cake

### ISSUE THREAD

**Issue by airminer** [KSP-CKAN/CKAN#2051]
The wiki pages "Build environment" and "Workflow" were written before the transition to cake, and thus need updating.

**Comment by politas** [comment]
I'v renamed "Building CKAN under Linux" to simply [Building CKAN](https://github.com/KSP-CKAN/CKAN/wiki/Building-CKAN) and updated the build instructions in [Build Environment](https://github.com/KSP-CKAN/CKAN/wiki/Build-Environment). I'm not sure what changes need to be made in [Workflow](https://github.com/KSP-CKAN/CKAN/wiki/Workflow)? Do you mean updating the instructions for where to get a more recent version of monodevelop?

**Comment by airminer** [comment]
I was just referring to the "Compiling" section, which you have already fixed. I can't find any more related problems on the wiki, so I'm closing the issue.
