### ISSUE TITLE
Issues with KW Rocketry Redux and its TWO (graduated and instanst) cfg providing add ons.

### ISSUE THREAD

**Issue by spirritus** [KSP-CKAN/CKAN#2052]
Module "KW Rocketry Redux" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg
Installing Mod : KWRocketryRedux-GraduatedPwr 3.1.2
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

========================================

Module "KW Rocketry Redux" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/NetKAN/issues/new

Please including the following information in your report:

File           : GameData/KWRocketry/Parts/Engines/1mMaverick1D/KW1mengineMaverick1D.cfg
Installing Mod : KWRocketryRedux-InstantPwr 3.1.2
Owning Mod     : KWRocketryRedux
CKAN Version   : v1.22.1-0-g174271a (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Olympic1** [comment]
Should be fixed know, can you confirm?

**Comment by spirritus** [comment]
confirmed, thx!
