### ISSUE TITLE
Change behavior when installation finds old files left from previous installation of mod

### ISSUE THREAD

**Issue by Ricochetv1** [KSP-CKAN/CKAN#2055]
I request a change in behavior of CKAN when it comes across old ship files from previous installations of various mods.
Instead of just killing the installation, let the user choose whether or not to continue, as the user generally has more knowledge of what is going on with their KSP installation and can make the logical decision whether or not to overwrite those files.

**CKAN Version:** 1.22.1-0-g174271a

**Operating System:** Win7

**The issue you are experiencing:** Stops installation when it finds ships left behind from previous installation

**How to recreate this issue:** Install a mod, delete the .json registry, manually remove the mods in GameData, then reinstall the mods. If ships were left behind, it kills the installation.

**CKAN error codes (if applicable):**

**Comment by dittoslash** [comment]
Fixed, maybe. Probably not stable, and you'll have to compile it yourself, but it's there if you want it. 
Doesn't actually give you a choice, just overwrites it. https://github.com/dittoslash/CKAN

**Comment by HebaruSan** [comment]
@dittoslash, if you make a [new pull request](https://github.com/KSP-CKAN/CKAN/pulls), it's much easier for the project team to check your changes, discuss, and merge them. Plus it has its own entry in the outstanding request lists, whereas replies to issues are easy to lose track of.

**Comment by dittoslash** [comment]
it's not stable, and just overwrites everything. if you're fine with that, i'll put it up :p

**Comment by HebaruSan** [comment]
Oh, nevermind; yes, that would break the normal case where the user tries to install two conflicting mods, as opposed to trying to manually reset everything and missing some things.

**Comment by HebaruSan** [comment]
It's a good idea to uninstall all mods in CKAN before you start mucking around with the files manually; this will take care of deleting the ships for you. The wiki's clean and reinstall process has been updated to recommend that, as well as include steps to clean up the ships if you still need to do that for some reason:

- https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

**Comment by HebaruSan** [comment]
As of #3043 the user is prompted to overwrite unowned files. I think that addresses this.
