### ISSUE TITLE
CKAN installing mods for higher version than what's installed.

### ISSUE THREAD

**Issue by ericfriesen** [KSP-CKAN/CKAN#2060]
Using latest version of CKAN v1.22.3
When using older version of KSP, CKAN updates and installs mods designed for newer versions of KSP.

**Comment by politas** [comment]
Some updated mods uploaded to Curse have gotten incorrect metadata due to Curse not adding the "1.3" version yet. Our NetKAN scraper is being told by Curse that they are compatible with KSP 1.2.2, so the CKAN client reflects that. When the mods are corrected on Curse, they should update automatically. You can force a downgrade of a specific mod by uninstalling in the GUI and then using the command line to install the previous version with 

    ckan.exe install <modname>=<version>

**Comment by clifcox** [comment]
Hi Guys,

sorry to wake up this old ticket, but I seem to be having the same problem. I'm running ckan v1.24.1+9712f94116e8 under Debian 9. I have mono version 5.10.160 installed. I'm using KSP 1.3.1 and CKAN is recommending from  Both the GUI and CLI, Chatterer 0.9.94 which is the version for KSP 1.4.1, and doesn't work on 1.3.1. If I try the trick above and do:

`mono ckan.exe install Chatterer=0.9.93`

Then I get the correct version and it works. Though I thought the whole idea of CKAN / apt-get is to take care of these things for you. Am I missing something? If you go here, and click the Changelog button, you will see which versions of Chatterer go with which version of KSP:

https://spacedock.info/mod/208/Chatterer

Please enlighten me! Thanks :-)
Clif

**Comment by HebaruSan** [comment]
Hi @clifcox, your question isn't related to this issue unfortunately. Chatterer 0.9.94 contains a .version file that says this:

```json
	"KSP_VERSION_MIN":
    {
        "MAJOR":1,
        "MINOR":3,
        "PATCH":0
    },
	"KSP_VERSION_MAX":
    {
        "MAJOR":1,
        "MINOR":4,
        "PATCH":99
    },
```

So Chatterer itself is saying that this version is compatible with KSP 1.3.0 and later. CKAN tries to take care of these things for you, but if the data that feeds into it is incorrect, it has no way of knowing that. If you are sure that this data is incorrect, please alert the author of Chatterer so it can be corrected.

**Comment by clifcox** [comment]
Sigh, ok thanks for the info, and a great project!  :-)

     Clif

**Comment by HebaruSan** [comment]
Hi @clifcox, thanks for the FYI. It appears that there was a version 6.8 of DPAI with incorrect versioning info that appeared briefly and was removed, leaving behind a ghost in CKAN. I have removed this now, please click Refresh and try again.

**Comment by clifcox** [comment]
Hey thanks, it works now. :-) Though AVC still complains. Is there a way to set a compatibility range for AVC like there is in CKAN? 

    Thanks,
     Clif

**Comment by HebaruSan** [comment]
@clifcox, I don't know, maybe ask the AVC devs?

**Comment by cake-pie** [comment]
The DPAI dev [wrote on forums](https://forum.kerbalspaceprogram.com/index.php?/topic/40423-141-docking-port-alignment-indicator-version-681-updated-031418/&do=findComment&comment=3316301) 
> 6.8 recompiled w/ new KSP DLLs so probably best not to use that on 1.3.x

This indicates a preference to not use new mod versions on old KSP versions.

@clifcox you should completely uninstall DPAI 6.8.0 and try again. CKAN should now fetch you DPAI 6.7.0 instead. If CKAN still insists on getting 6.8.0 then there's other problems.

**Comment by bfishman** [comment]
Navyfish here.  Thanks @clifox and @HebaruSan

That explains a lot. Next time if I make a version file mistake I'll poke over here and inform someone. I ain't afraid of no ghosts.

**Comment by clifcox** [comment]
Yep, thanks it's installing the correct version and working great now. :-)

     Clif
