### ISSUE TITLE
Don't know how to change game directory for CKAN

### ISSUE THREAD

**Issue by Grievous1** [KSP-CKAN/CKAN#2061]
**CKAN Version:** 1.22.2

**Operating System:** Windows 10

**The issue you are experiencing:**  I know the issue is that CKAN is automatically looking for KSP in "C:/Program Files 86x/etc./Steam/KSP, however, due to permissions issues on my PC, I have had to re-install steam to the directory "C:/Games/Steam" to be able to modify what I need to. Any help on changing the directory to search for KSP through CKAN would be appreciated.

                   Thanks,
          -Griev

**Comment by ndfmoab** [comment]
You can add / delete instllations of KSP through File -> Select KSP Install. Theoretically you can manage several KSP installs with CKAN.

**Comment by politas** [comment]
Or from a command line, `ckan.exe ksp (list|remove|add)`

**Comment by Grievous1** [comment]
The only problem is that whenever I open CKAN, it says 'ERROR: Cannot locate KSP in C:/etc/Program files/Steam/KSP and just instantly crashes. I have this problem with any version of CKAN I install, but I will try the command prompt suggestion.

**Comment by Grievous1** [comment]
Can't get even the command prompt to work... I don't know what to do now.

halp

**Comment by politas** [comment]
Does it crash when you run this?

`ckan.exe ksp list`

**Comment by Grievous1** [comment]
Wait, do I do that in the command prompt that opens with CKAN, or open an entirely different one?

**Comment by Grievous1** [comment]
Not sure if this will help, but hopefully someone can debug it and figure it out for me.


Unhandled exception:
System.IO.FileNotFoundException: Error reading the c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program/CKAN/downloads directory.
   at System.IO.FileSystemWatcher.StartRaisingEvents()
   at CKAN.NetFileCache..ctor(String _cachePath)
   at CKAN.KSP..ctor(String gameDir, IUser user)
   at CKAN.KSPManager.LoadInstancesFromRegistry()
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Gui(GuiOptions options, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by Grievous1** [comment]
Okay, I've fixed the issue. Hooray for unlocker software!
Turns out the issue was that the CKAN directory had been locked for no reason when I uninstalled steam... thanks windows.
I deleted the file via an unlocker tool created a new dummy CKAN folder, and voilà! problem solved.

Thanks everyone who tried to help, I just did a bit of digging around in files and figured it out.

**Comment by politas** [comment]
1. Load a command prompt separate to the ckan.exe
2. Change directory to the the directory where you downloaded ckan.exe
3. type in this:

     ./ckan.exe ksp list

**Comment by MysticalFists** [comment]
@politas Thanks so much!  I hadn't played in a while and Steam auto-updated.  Tried everything to get CKAN working.  The regedit worked!~

**Comment by D4rKing** [comment]
A bit late, but my CKAN launcher, when asking for my install path (I changed it), the installer itself won't let me select it properly. It'll show the install menu, but instead of having a selecting a button, it only has a "open" button, which pretty much does what you think it does. I cannot therefore select my install directory for KSP and play the game. I feel like it's something really simple I'm just missing, but can't figure out. Please help.

**Comment by HebaruSan** [comment]
@D4rKing, select the buildID64.txt file.

**Comment by D4rKing** [comment]
I owe you my life. Thanks!
