### ISSUE TITLE
Added download info to Metadata page

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2062]
Add a line which shows where the mod is going to be downloaded from to the Metadata page.

Right now it's a mystery, would be helpful for debugging or knowing if some location is having a download problem

**Comment by Chase22** [comment]
@linuxgurugamer Maybe close the issue?

**Comment by linuxgurugamer** [comment]
Yes, since it was now released :-)

**Comment by HebaruSan** [comment]
Oh, you wanted this in the download prompts? I thought it was about the mod info tab.
:+1:

**Comment by linuxgurugamer** [comment]
Either
