### ISSUE TITLE
Ksp Default command is not functioning 

### ISSUE THREAD

**Issue by hankscuba** [KSP-CKAN/CKAN#2065]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.3
**Operating System:** 
Mac OS 10.12.5 (16F73)
**The issue you are experiencing:** 
I can't set a default ksp using terminal
**How to recreate this issue:** 
not sure it but it happens every time i try this
**CKAN error codes (if applicable):** 
myname-MBP-3:~ myname$ mono /path/to/ckan.exe ksp default
1*) "ksp" - /Applications/KSP_osx
Enter a number between 1 and 1 (To cancel press "c" or "n". "Enter" will select 1.): 
1
Successfully set "ksp" as the default KSP installation
myname-MBP-3:~ myname$ mono /path/to/ckan.exe ksp list
Name  Version     Default  Path                 
----  ----------  -------  ---------------------
ksp   1.2.2.1622  No       /Applications/KSP_osx

**Comment by politas** [comment]
Can you try the following command?

    mono /path/to/ckan.exe ksp default ksp

Where that last "ksp" is matching the instance Name from the list. I want to see if it's just the interactive version that's failing.
