### ISSUE TITLE
Locking pid validation fails

### ISSUE THREAD

**Issue by thomas15v** [KSP-CKAN/CKAN#2075]
At this moment ckan locks itself by creating a "registery.lock" file. However this feature is relatively annoying on Linux, since shutting down your computer with programs running (this is how I shutdown my computer). Will still leave the lock file behind. Possibly since a "sigkill" is considered as a crash?

I noticed that ckan writes its PID to the lock file. However it doesn't really check it nicely.
![image](https://user-images.githubusercontent.com/2163941/27514967-184fe59a-5999-11e7-9423-6f00380bedbe.png)
If I kill ckan wrongly now (`ctr+c`). This happends:
![image](https://user-images.githubusercontent.com/2163941/27514974-4fad2e58-5999-11e7-82a6-daf3d660dce4.png)
Not sure if that % sign is messing it up. But ckan fails to properly validate if their is a instance running on pid `11749`.

I resolved this issue by doing this in my launcher file:
`rm "/games/SteamLibrary/steamapps/common/Kerbal Space Program/CKAN/registry.locked" | mono "/games/SteamLibrary/steamapps/common/Kerbal\ Space\ Program/ckan.exe"`. But this is possibly not the way you guys intended ckan to be launched :wink:.

**Comment by ayan4m1** [comment]
What happens if you issue SIGINT instead of SIGKILL?

**Comment by thomas15v** [comment]
Hmm I probably used the wrong term ctrl + c does SIGINT apparently, most likely it also sends that to programs for shutting down.

**Comment by ayan4m1** [comment]
Sorry, I don't understand what you are saying - my understanding was that you were shutting down your system with CKAN running. Most Linux distros (which are you using, by the way?) send SIGTERM to all processes on shutdown. Sending SIGINT or SIGKILL should only ever happen if the application fails to respond to SIGTERM. Furthermore, we'd need to add a dependency on the Mono.Posix library to be able to hook these signals, since .NET itself has no concept of SIGTERM/KILL/INT.

**Comment by thomas15v** [comment]
To be clear ckan does not remove the lock file when you do the following:
- Do ctrl + c in the terminal
- Shutdown your computer with the program running.

I am using Ubuntu 16.4 with zsh as my shell.

I honestly don't know much about the process signals.

**Comment by politas** [comment]
Automatically removing the lockfile on starting CKAN will prevent you being bothered by the lock file, but it also defeats the purpose the having the lockfile, which is to prevent registry corruption from running multiple processes on the same KSP instance. Do it if you want, but be aware of the dangers. If you are keeping backups of your entire KSP directory, it's probably not going to cause many issues for you.
