### ISSUE TITLE
Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.

### ISSUE THREAD

**Issue by Luluapo** [KSP-CKAN/CKAN#2076]
When I click Refresh, I get this message:

> Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
> Repository successfully updated

I am using CKAN v1.22.3 on Windows 7.

This is the same issue reported in [https://github.com/KSP-CKAN/CKAN/issues/1579](url) and [https://github.com/KSP-CKAN/CKAN/issues/1491](url). The discussions of those issues suggest several things. I have tried all of them. Specifically:

- I have confirmed that my system time is set correctly; the time zone is correct, it automatically updates, and shows the correct date and time.
- I have done a winsock reset.
- I have verified that NET Framework 4.6.1 is installed.
- I have disqualified my firewall as the cause of the problem by trying a CKAN refresh with the firewall turned off.
- I have rebooted my computer.
- I have verified that there is no problem with my network connection by browsing to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz using Firefox. I can download the file with no hitch.

**Comment by FerretR** [comment]
I have this problem as well. I followed the same steps above also. Still not working.

**Comment by SolarSupremacy** [comment]
Still an issue.

**Comment by ayan4m1** [comment]
Investigate your path to the Internet, is there anywhere these packets could be getting dropped? Router, gateway(s), any extensions you are using in browsers or "web security" products - I know you said you ruled your firewall out but that is definitely a good thing to truly rule out - i.e. try running CKAN on a computer that does not have that type of software installed and ideally uses a completely separate method of connecting to the Internet.

I also don't doubt that this URL is periodically not available to every part of the world. Having this problem over an extended period of time would be mitigating evidence.

**Comment by AlexandruSimandi** [comment]
It's happening to me also

**Comment by iancj97** [comment]
Also still an issue.

**Comment by acornett** [comment]
Could this be caused by https://githubengineering.com/crypto-removal-notice/ ?

**Comment by HebaruSan** [comment]
Today's incident was (see #2293), but back in July, probably not.

**Comment by tobimai** [comment]
Also happening to me, no Antivirus installed and it worked for a few hours. I didn't change anything and it stopped working, but KSP crashed once, probably because a lack of RAM.

**Comment by HebaruSan** [comment]
@tobimai , click on #2293. GitHub changed their servers in a way that broke CKAN.

**Comment by Praafit** [comment]
@HebaruSan thank you so much! I struggled with this a lot and the reg helped me 👍 :D

**Comment by tobimai** [comment]
@HebaruSan Thanks, sorry I misread your message and thought incident 2293 happened in July and therefore not looked at it.

**Comment by HebaruSan** [comment]
The fix is to install: https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0

**Comment by helloworld1025** [comment]
where to extract meta data for CKAN (program for Kerbal Space Program)
