### ISSUE TITLE
Select which version of a mod to install

### ISSUE THREAD

**Issue by BloodyRain2k** [KSP-CKAN/CKAN#2077]
**CKAN Version:** 1.22.3

**Operating System:** Win7 64

**The issue you are experiencing:** The UI does not offer a way of installing an older compatible version of a mod while the internal backend is already capable of doing so.

**How to recreate this issue:** Try to install any mod's version that's not the dark green one in the version list.

**CKAN error codes (if applicable):** 

I've a day ago or so updated AnalogControlContinued because well, why not, it's only the update to make it 1.3 compatible even though I'm still playing 1.2.2.
Turned out that it was a big mistake because something went seriously wrong and it was spewing NREs all over the place.
So I thought "ok no big deal, I'll just revert to the version before".

Well, turns out the UI of CKAN doesn't let you do that, or if it does, it's less obvious than Blender's UI.
I reverted it over the console by now which worked but it'd be really nice if the UI could get updated to allow selecting which version will be installed.

Easiest idea I'd have for this right now would be with a double click in the respective version in the mod's version list.

**Comment by blacknight2u** [comment]
Same ^^^^^

**Comment by politas** [comment]
Yes. We have the functionality available via the CLI, but adding it to the GUI would be a good thing.

**Comment by Olympic1** [comment]
We could do this via the `Versions` tab in the ModInfo panel. Right click a compatible (green) version to install. This will of course uninstall its dependencies and reinstall them because there could be dependency changes beteween versions.

**Comment by politas** [comment]
Uninstalling dependencies is a bit tricky. We need to make sure we re-install them if any other installed mods have them as a dependency.

**Comment by merket** [comment]
>  politas commented on Oct 8, 2017 
> Yes. We have the functionality available via the CLI, but adding it to the GUI would be a good thing.

Hello I just updated some mods believiing they were only version file change, but I broke my whole game on my server. I would really like to go back to the previous versions if it's possible with "CLI" could you guide me on how to do that @politas ?

**Comment by nevercast** [comment]
Presumably this feature has not landed yet?

**Comment by politas** [comment]
Not unless you build from the source. It'll be in v1.25.0

**Comment by nevercast** [comment]
Can versions be locked out? Say I install an older version of a mod but I still wish to use the Auto Update feature of CKAN. Can I prevent that old versioned mod from being auto-updated? Probably a nice to have before 1.25 release.

**Comment by HebaruSan** [comment]
You can feel free to submit an enhancement request (issue) for that.

**Comment by Blu3wolf** [comment]
#2364 is merged and appears to describe the functionality I want. However, when I double click an older version, the process starts, but after downloading the older version, the software determines that "mod somelatermodversion is already installed, skipping"

Is this feature currently broken?

**Comment by DasSkelett** [comment]
It only worked for new installations until #2669, so in the next release you also can downgrade a mod with the versions list, like you imagined.
