### ISSUE TITLE
Cannot Download ckan.exe artifact

### ISSUE THREAD

**Issue by Str8AWay** [KSP-CKAN/CKAN#2080]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** All

**Operating System:** Linux

**The issue you are experiencing:** Cannot download any release artifacts. It just sits and spins. It looks like you host the artifacts on AWS. This inability to establish a connection is usually a problem with AWS security groups in my experience.

**How to recreate this issue:** Try to download release artifact from [here](https://github.com/KSP-CKAN/CKAN/releases/download/v1.22.3/ckan.exe)

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Works fine as far as I can tell. It's hosted on GitHub, not AWS. We do use some AWS servers, but they're for other things. Can you download other GitHub releases?

**Comment by Str8AWay** [comment]
Seems to be a chrome specific problem. I was able to download it with firefox.
