### ISSUE TITLE
Deadly Reentry

### ISSUE THREAD

**Issue by Derica6350** [KSP-CKAN/CKAN#2081]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**Any version** 

**Any computer:** 

**CKAN just needs to pull the latest version of DRE** 

**Deadly Re-entry has been updated to version 7.6, version 7.5 makes kerbals spontaneously combust in EVA** 

**CKAN error codes (if applicable):** 

http://forum.kerbalspaceprogram.com/index.php?/topic/50296-122-deadly-reentry-v760-june-9-2017-the-ariel-edition-pre-release/

**Comment by politas** [comment]
DeadlyReentry-v7.6.0 is in the repo
