### ISSUE TITLE
[Feature] Ability to hide mod from CKAN GUI.

### ISSUE THREAD

**Issue by jonesmz** [KSP-CKAN/CKAN#2082]
I read through all existing open issues on github. If this is a duplicate, it must have been closed at some point.

I would really enjoy being able to hide a mod from the CKAN gui. I've installed mods that I ended up preferring not to have installed. If I had the ability to hide those mods, it would make it much easier to browse through the remaining list.

If a feature like this were implemented, having an option to hide until update, or hide permanently, would be nice.

**Comment by HebaruSan** [comment]
What should happen if you try to install a mod that depends on one of your hidden mods? Would you want it to install the hidden mod, hide the dependency, raise an error, or something else?

**Comment by jonesmz** [comment]
Excellent question.

I suppose my personal preference would be to have the hidden mod highlighted in the change summary view, and unhidden unless the user takes action again.

Raising an error for mods marked as permanently hidden would make sense, I think.

**Comment by politas** [comment]
This is another example of what might be possible if we had a third mod data structure storing user -local information about the entire modlist, rather than only installed mods.

**Comment by Olympic1** [comment]
If the mod is hidden, the user should probably need a way to access the hidden list to unhide a mod. Where could we add that option? Via the filter, a new button, the settings window, a new menu at the top, ...

Leave some suggestions.

**Comment by 7ranceaddic7** [comment]
KISS; make it a filter option.
