### ISSUE TITLE
Mozroots deprecated

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2083]
**CKAN Version:
1.22.3

**Operating System:
Linux Jupiter 4.10.0-25-generic #29-Ubuntu SMP Tue Jun 20 15:00:02 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

**The issue you are experiencing:
Had a problem with downloading and redid the following:

scott@Jupiter:~$ mozroots --import --ask-remove
Mozilla Roots Importer - version 4.6.2.0
Download and import trusted root certificates from Mozilla's MXR.
Copyright 2002, 2003 Motus Technologies. Copyright 2004-2008 Novell. BSD licensed.

WARNING: mozroots is deprecated, please move to cert-sync instead.

Downloading from 'https://hg.mozilla.org/releases/mozilla-release/raw-file/default/security/nss/lib/ckfw/builtins/certdata.txt'...
Importing certificates into user store...
3 new root certificates were added to your trust store.
Import process completed.

**How to recreate this issue: Maybe, delete root certs on linux systems? </sarcasm>

**CKAN error codes (if applicable): Oh no! Our download failed with a certificate error!

**Comment by mingmingrr** [comment]
I had the same issue on Debian. Try getting the latest version of [Mono](http://www.mono-project.com/download/).

**Comment by politas** [comment]
Our release notes mention using cert-sync to update certificates.

**Comment by 7ranceaddic7** [comment]
Updated wiki install instructions for Ubuntu users.

https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu

**Comment by 7ranceaddic7** [comment]
Whoops.  Updated wiki homepage to reflect/ capture dropping 14.04 from title.

**Comment by ayan4m1** [comment]
Thanks!
