### ISSUE TITLE
CKAN.NotKSPDirKraken: Could not find KSP version in readme.txt

### ISSUE THREAD

**Issue by MajesticHorse** [KSP-CKAN/CKAN#2084]
this is what i get when trying to open CKAN, not sure if its a bug or i cant install it properly, but its very irritating;

Unhandled exception:
CKAN.NotKSPDirKraken: Could not find KSP version in readme.txt
   at CKAN.KSP.DetectVersion(String directory)
   at CKAN.KSP.Version()
   at CKAN.ChooseKSPInstance.UpdateInstancesList()
   at CKAN.ChooseKSPInstance..ctor()
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by MajesticHorse** [comment]
SORRY! I FIXED IT! I WAS JUST BEING STUPID!

**Comment by Lolologist** [comment]
Well? What was wrong? I'm having the same issue!

**Comment by joshthegrate** [comment]
ya how did you fix it?

**Comment by mg1142mg** [comment]
Do you guys have any solution to that problem?

**Comment by Lolologist** [comment]
Nope. I have a workaround which is to use an earlier version of KSP though.

**Comment by mg1142mg** [comment]
... well I have read on another post about the same issue and it said that now the version is read from buildID.txt and that we should launching CKAN pointing at this specific file in order for it to get the version. Do you know how to do that?

**Comment by mg1142mg** [comment]
omg I am sooo dumb. Maybe the same happened to you guys. 

So, if in the same folder as your ckan.exe you have a Gamedata folder, it will assume that this one is the KSP one, which is not. so of course it will not find the version file... Hope that helped. 

Also, it's in the ckan wiki...

**Comment by Lolologist** [comment]
Awesome, that might do it! Thanks.
