### ISSUE TITLE
Weird Word Glitch

### ISSUE THREAD

**Issue by LegoCollecter14** [KSP-CKAN/CKAN#2086]
**CKAN Version:** 
Picture had Messed Up Info Will Repost
![image](https://user-images.githubusercontent.com/19707996/28071497-1e507b80-661e-11e7-937f-6b2d2d71dbc1.png)

Windows 10

See Picture

Unsure Just Randomly Happens

hasnt Crashed

**Comment by HebaruSan** [comment]
Haven't seen this in a long time. Fingers crossed that it was a one-time glitch on this user's computer.
