### ISSUE TITLE
CKAN gets Updating after changing installs 

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2087]
Changing installs is somewhat problematic.   If I change and install, then do a refresh, and do an update, CKAN doesn't remember:
Steps:

1.  Start CKAN, select install A at startup.  (I have CKAN set to auto refresh at startup)
2.  Use the File->Select KSP Install to change to install B
3.  Do a Refresh 
4.  Some mods need updating, so click "Add available updates"
5.  Click "Apply Changes"

After updates have been applied, it still thinks they need to be applied.  I need to exit CKAN and restart, selecting install B and then do the refresh/add available/apply changes.

My impression is that maybe the updates are NOT applied the first time, since upon the 2nd entry it still says they need updating

**Comment by politas** [comment]
I cannot reproduce this with my installs.

**Comment by ayan4m1** [comment]
I also cannot reproduce this on Win10.
