### ISSUE TITLE
Download URL corrupted bug

### ISSUE THREAD

**Issue by 2lou2** [KSP-CKAN/CKAN#2091]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version: v1.22.3

**Operating System: Windows 10 x64

**The issue you are experiencing:** 

When I try to download KSP Interstellar, the program doesn't enter the URL correctly due to "%" characters in the URL.

**How to recreate this issue:** 

Download KSP Interstellar Extended.

**CKAN error codes (if applicable):** 
![image](https://user-images.githubusercontent.com/10662948/28476748-bf28b66c-6e16-11e7-82f2-8a7e3a86ccfb.png)

**Comment by ayan4m1** [comment]
I think you are misunderstanding the "clickable URL" aspect of that field, it doesn't have anything to do with the actual URL that was requested. If you [go to](https://spacedock.info/mod/172/KSP%20Interstellar%20Extended/download/1.14.14.1) the link in your browser, you'll likely see a spacedock 404 error as I did. For some reason that version is no longer available for download and is still in your registry.
