### ISSUE TITLE
Error Code issue No error code number just this statement:

### ISSUE THREAD

**Issue by Zill4449** [KSP-CKAN/CKAN#2097]
Thanks for wanting to bring an issue to our attention!

I just got CKAN and was trying to download my first few mods for Kerbal Space Program and this popped up when i was trying to download them .....

"The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel."

What does it mean and better yet how can i fix it?

Thanks

**Comment by Zill4449** [comment]
the main item i am finding that seems to be holding up everything is that it need mod manager which is trying to install/ download and then the above message/ error code pops up....

**Comment by ayan4m1** [comment]
What OS are you using?
