### ISSUE TITLE
Silently downloading HTML as ZIP files causing corrupt zip exception.

### ISSUE THREAD

**Issue by dyleighba** [KSP-CKAN/CKAN#2100]
### CKAN Version if known (or site URL)
v1.22.3
Windows 7

### Please describe the expected behaviour
1. CKAN attempts to download mod.
2. Download is redirected but still outputs data which in this case is HTML.
3. CKAN saves the data as a ZIP in downloads.
4. CKAN checks the hash and attempts to re-download and on subsequent attempts errors.

### Please describe the actual behaviour
1. CKAN attempts to download mod.
2. Download is redirected but still outputs data which in this case is HTML.
3. CKAN saves the data as a ZIP in downloads.
4. CKAN attempts to install mod but errors due to file being 'corrupt'.

### What steps can be taken to reproduce the issue? 
1. Setup a HTTP server that always returns HTML.
2. Get CKAN to download a mod via that server.
Note: The cause of this in my setup is a proxy blocking ZIP files and returning a rejection page.

**Comment by HebaruSan** [comment]
Downloads currently returning non-ZIP files for me, for testing:

- ASETProps 1.3 (KSP 1.0.4 - 1.1.3)
- DockingSounds 1.2 (KSP 1.0.4 - 1.0.5)
- ASETAvionics 1.0 (KSP 1.0.4 - 1.1.3)
- AircraftCarrierAccessories-1.13 (KSP 1.2.2)

**Comment by politas** [comment]
We should compare the downloaded file against our SHA1 hash and reject any download that doesn't match as corrupted. This returns to the #2210 solution for checking downloads and failing over where possible.

**Comment by HebaruSan** [comment]
Yeah, we essentially do that, just a bit sloppily. The invalid file makes it into the cache, but when it comes time to use it, the hash is checked and it's treated as non-cached. We should check the hash before adding the file to the cache.
