### ISSUE TITLE
Dependency found, but it is not listed in the index, or not available for your version of KSP.

### ISSUE THREAD

**Issue by RafalLauterbach** [KSP-CKAN/CKAN#2101]
CKAN Version: 1.22.3

Xubuntu 4.4.0-87-generic

It is more like mod problem or me using ckan wrong.

When I try to install KSP Interstellar Extended it does not allow me to Apply changes, but in console i have : ERROR CKAN.RelationshipResolver (null) - Dependency on InterstellarFuelSwitch-Core found but it is not listed in the index, or not available for your version of KSP.
When I manualy install dependences Interstellar Fuel Switch Core and KSPI-E are red.

I have KSP 1.2.2 and I guess maybe newest mod version for 1.2.2 (1.14.14.1) is incompatibile with newest Interstellar Fuel Switch Core on this version, because mod jumped up whole version up. How can I select in ckan older (1.13.10) mod version to be installed to check it?

I will add some screenshots

http://screenshot.sh/mFBEbHPJfK5NW
http://screenshot.sh/m9g4CYIcfzJWI
http://screenshot.sh/odV79sx2zSZX8

**Comment by politas** [comment]
Looks like their may have been a mistake somewhere. That release is now marked on Spacedock as being for KSP 1.3.0. Thanks for bringing it to our attention!

**Comment by politas** [comment]
KSP-CKAN/CKAN-meta#1298 has fixed it. Sorry you didn't get an answer earlier.
