### ISSUE TITLE
TrustFailure when initiating a download

### ISSUE THREAD

**Issue by jgrondier** [KSP-CKAN/CKAN#2102]
**CKAN Version:** 1.22.3 

**Operating System:** Fedora 26 64 bits

**The issue you are experiencing:** When downloading any mod, ckan will give the following error message in a popup window and in the cli:

Failed to download <url> - error: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)

**How to recreate this issue:** Check any mod in the mod list, then click Apply Changes, then Apply. It will then launch the error.

**CKAN error codes (if applicable):** 

Example in app log: 

>     About to install...
>
>      * Airline Kuisine 1.3.0
>      * Module Manager 2.8.1
>      * Firespitter Core v7.6.0
>
>     Downloading "https://spacedock.info/mod/1252/Airline Kuisine/download/1.3.0"
>     Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/128/artifact/ModuleManager-2.8.1.zip"
>     Downloading "https://github.com/snjo/Firespitter/releases/download/v7.6.0/Firespitter_7.6.0.zip"
>
>
>
>
>     Error!

Console log:

>     $ mono ckan.exe  
>     19453 [1] ERROR CKAN.ErrorDialog (null) - Failed to download "https://spacedock.info/mod/1252/Airline Kuisine/download/1.3.0" - error: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
>     22248 [1] ERROR CKAN.ErrorDialog (null) - Failed to download "https://ksp.sarbian.com/jenkins/job/ModuleManager/128/artifact/ModuleManager-2.8.1.zip" - error: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)
>     22910 [1] ERROR CKAN.ErrorDialog (null) - Failed to download "https://github.com/snjo/Firespitter/releases/download/v7.6.0/Firespitter_7.6.0.zip" - error: Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)

What I have tried and didn't work:

>    mozroots --import  

(Of course I did this during the installation process)

After looking around [on the internet](http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync)

>    cert-sync /etc/pki/tls/certs/ca-bundle.crt

EDIT: Here is my mono version

>    $ mono -V
Mono JIT compiler version 4.8.0 (Stable 4.8.0.520/8f6d0f6 Wed Mar 15 15:23:40 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by politas** [comment]
Is your Mono sourced from the Mono Project, or the Fedora repositories?

**Comment by jgrondier** [comment]
From the fedora repositories.


    ~ dnf info mono-devel
    [...]
    Installed Packages
    Name         : mono-devel
    Version      : 4.8.0
    Release      : 7.fc26
    Arch         : x86_64
    Size         : 17 M
    Source       : mono-4.8.0-7.fc26.src.rpm
    Repo         : @System
    From repo    : fedora
    Summary      : Development tools for Mono
    URL          : http://www.mono-project.com
    License      : MIT
    Description  : This package completes the Mono developer toolchain with the mono
                 : profiler, assembler and other various tools.


I forgot to add that I've since reverted to 1.22.2-dev which works perfectly.

**Comment by politas** [comment]
Did you build 1.22.2-dev yourself? That would tend to fix runtime incompatibilities.

**Comment by jgrondier** [comment]
I didn't. 

Both 1.22.2 and 1.22.3 were downloaded built from the release page

**Comment by politas** [comment]
Do you have mono-complete (or whatever the Fedora equivalent is) installed? That's one option, and apart from that, I can only suggest sourcing Mono from mono.org
