### ISSUE TITLE
Launch Error on OS X

### ISSUE THREAD

**Issue by l-gothberg** [KSP-CKAN/CKAN#2106]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.3

**Mono Framework Version:**
5.2.0.215

**Operating System:**
OS X version 10.12.6

**The issue you are experiencing:**
CKAN does not launch.  See attached error log.  Launched via terminal using 'mono ckan.exe'

**How to recreate this issue:**
Launch application on same build.

**CKAN error codes (if applicable):** 
See attached file for full log.

-----MESSAGE BEGINS-----
Got a SIGSEGV while executing native code. This usually indicates
a fatal error in the mono runtime or one of the native libraries 
used by your application.

Process 12767 detached
(lldb) quit
Abort trap: 6
-----MESSAGE ENDS-----

[mono_CKAN_Error_Report.txt](https://github.com/KSP-CKAN/CKAN/files/1237512/mono_CKAN_Error_Report.txt)

**Comment by l-gothberg** [comment]
Tried downgrading my version of Mono Framework to 5.0.1.1
Encountered slightly different error.  See attached log file.

[CKAN_ERROR_LOG.txt](https://github.com/KSP-CKAN/CKAN/files/1243791/CKAN_ERROR_LOG.txt)

**Comment by gunqqer** [comment]
This may not be it but are you getting mono from Homebrew? If so this is your problem, if not,I got nothing

**Comment by l-gothberg** [comment]
I have tried both the manual installation from a compiled version downloaded from Mono-Project and the Homebrew versions.

**Comment by gunqqer** [comment]
Whelp, then I don't know. FYI the Homebrew version *only* uses the 64 bit
version even though a lot of things would use 32 bit and there are things
that *rely* on 32 bit. There's an issue on the homebrew github but it was
locked and next resolved

**Comment by l-gothberg** [comment]
Got it!

It seems that part of the mono framework that CKAN relies on hasn't yet been updated to 64-bit support (Carbon Driver), and this causes the System.Windows.Forms call to fail.

I got around this by forcing Mono to launch in 32-bit using the --arch=32 switch.  It seems that even the version directly from Mono defaults to 64-bit now.
