### ISSUE TITLE
(harmless?) error 403 upon launching ckan

### ISSUE THREAD

**Issue by donoya** [KSP-CKAN/CKAN#2107]
CKAN Version: 1.22.3

Operating System: Windows 8.1

Issue: error 403 upon launching ckan. Proceeds to interface upon clicking "okay".

How to recreate this issue: launch ckan. It happens every time for me.

CKAN error code: 403

**Comment by donoya** [comment]
Never mind. It seems to have gone away on it's own.

**Comment by politas** [comment]
Would have been a GitHub issue.
