### ISSUE TITLE
CKAN not friendly with REAL satellites

### ISSUE THREAD

**Issue by ndotb** [KSP-CKAN/CKAN#2108]
**CKAN Version:** 
1.22.3

**Operating System:** 
Windows 10 Creators

**The issue you are experiencing:** 
Upon opening, CKAN immediately begins making internet requests without direct authorization.  It does not check if the current connection on Windows 10 is metered.  Its download system does not:

- Prime DNS
- Work with high latency connections
- Resume on failure

In short, CKAN works with toy satellites but has no idea how to manage a real one.

In addition, there is no cancellation token associated with download requests.  The only way to stop it is to go into task manager and kill the program.

**How to recreate this issue:** 
Open it, then try to download on a satellite internet connection.

**CKAN error codes (if applicable):** 
Request timed out, server not found.

I would offer to help, but the build system has become an exercise in obsessive compulsive disorder for a relatively simple application.

**Comment by politas** [comment]
There are settings to turn off automatic updates and automatic refresh, and the CKAN client should be asking you about those two things on first load. The inability to resume on failure is an issue, but we are pretty much limited to what our libraries support in that regard, I believe. You can pre-download mod contents individually from the mod details "Content" tab if that helps.

**Comment by HebaruSan** [comment]
The API for metering _might_ be...

```cs
var cost = NetworkInformation.GetInternetConnectionProfile().GetConnectionCost().NetworkCostType;
bool metered = (cost == NetworkCostType.Fixed || cost == NetworkCostType.Restricted);
```

**Comment by HebaruSan** [comment]
@ndotb, what is meant by "does not work with high latency connections"? What problem specifically happens on high latency connections?

**Comment by GargamelKSP** [comment]
@HebaruSan, per your request, couple comments:
Satellite internet has extremely high ping times.  It's a very rare day if I can get a ping of less than 2000ms to my ISP host site.   Online gaming is not even possible with that type of lag.  I have not encountered any latency issues, yet, but like I said in the 1.4 thread, first time running it.

A scheduler would be a very nice feature to have, to limit updates and downloads to specific times of day, when our connections are not throttled.

**Comment by HebaruSan** [comment]
No response from OP in over 2 years.
