### ISSUE TITLE
Question about netkan --prerelease option

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2109]
It looks like pre-release versions are ignored by default (which is sensible), but "netkan --prerelease" flips it to index **only** prereleases (the left half of the comparison maps to the command line parameter, and the right half to a release's info from Github):

https://github.com/KSP-CKAN/CKAN/blob/1fe599741ec79a6fb0c92bcf1c0e62435f45a69a/Netkan/Sources/Github/GithubApi.cs#L39-L43

Is that intentional? I expected that the --prerelease flag would simply include prereleases for consideration along with normal releases, not cause normal releases to be ignored.

**Comment by dbent** [comment]
> Is that intentional?
Pretty much, the idea, I've surmised, is to enable easily generating "unstable" repositories that *only* include prerelease versions of mods. I doubt the utility of that, but we've never had much need to change it.

**Comment by HebaruSan** [comment]
OK, thanks, I didn't know there were such repositories. That answers my question.
