### ISSUE TITLE
CKAN cannot forget old deleted versions of KSP

### ISSUE THREAD

**Issue by freqout** [KSP-CKAN/CKAN#2110]
I've been looking through here and can;t find something that quite matches my issue. I deleted several old copies of KSP and moved the rest off to another drive. Now CKAN throws "Could not find KSP version in readme.txt.

So, after looking through here, I tried firing it up from the command line and using ckan ksp list to get a list of installs it knows about, and then tried using ckan ksp forget on each one. When this failed, I created a skeleton directory for each version it knows about, with an empty GameData folder and the readme,txt from 1.3. This worked on the first, but when I tried it on the other installs I'd get a CKAN.NotKSPDirKraken error.

So, given that I am no longer maintaining those old installs, is there a way to just completely wipe CKAN's information on them, like removing whatever datastore it uses, since it won't let me use its internal commands to do so? I've already downloaded a fresh copy of CKAN and searches haven't yielded any info on where it stores its config info. 

CKAN version: v1.22.3+64309722a446
OS: Windows 10 Home

**Comment by freqout** [comment]
One thing I noticed while writing this is the following. I had, at one point, installed KSP via Steam, but had since reverted to using directly downloaded copies. If I rename the CKAN folder in steam to something else, then when I try to fire up CKAN from the command line, I get this:

C:\Users\Amir\Documents\KSP> .\ckan.exe ksp list
Setting up CKAN for the first time...
Creating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN
Scanning for installed mods...
Creating C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/CKAN/downloads
1076 [1] ERROR CKAN.KSP (null) - Could not find KSP version

Unhandled Exception: CKAN.NotKSPDirKraken: Could not find KSP version in readme.txt
at CKAN.KSP.DetectVersion(String directory)
at CKAN.KSP.Version()
at CKAN.CmdLine.KSP.<>c.b__18_1(KeyValuePair2 i) at System.Linq.EnumerableSorter2.ComputeKeys(TElement[] elements, Int32 count)
at System.Linq.EnumerableSorter2.ComputeKeys(TElement[] elements, Int32 count) at System.Linq.EnumerableSorter1.Sort(TElement[] elements, Int32 count)
at System.Linq.OrderedEnumerable1.<GetEnumerator>d__1.MoveNext() at System.Linq.Enumerable.WhereSelectEnumerableIterator2.MoveNext()
at System.Collections.Generic.List1..ctor(IEnumerable1 collection)
at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
at CKAN.CmdLine.KSP.ListInstalls()

I'm not running CKAN from there (I have my KSP stuff elsewhere on the drive) so I'm wondering why it re
ally wants to work out of that directory. After getting this message, when I fire up the GUI clinet, it asks if I want to update, even though I'm already running the current version, so it seems like something in the steamapps copy of CKAN is messing things up for any copy I put on my system.

In any case, since I'd actually already uninstalled the Steam version through Steam, deleting the remnant KSP steamapps directory seems to have fixed this. it would be great though to have a straight up Reset to Defaults option that would just wipe all that stuff.

**Comment by politas** [comment]
The installs information is stored in the registry at **CurrentUser\software\ckan\**
