### ISSUE TITLE
[Feature] Mods Language Filter

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2113]
Developers introduced many languages, some mod already has user's target language, some hasn't.

I propose:

1. add languages to metadata specification, and show to user at the mod versions panel
2. - introduce language filter (it shows only target language mods) and/or
   - include languages to separate column.  
For example, if user checks target language, then target-language column will appear with [×]/[  ] values (sorting supported). English language mods still is showed. I assume that most users are mostly interested in only one target language.

**Comment by HebaruSan** [comment]
It might be worth localizing CKAN itself first. A user who prefers a non-English locale for mods might also have difficulty navigating an English-only application, and the same setting could drive both the CKAN display and the mod filter.

**Comment by politas** [comment]
So far, the only non-English mods we have are translations, and there are only a handful of them. Localizing CKAN sounds like a pretty big task.

**Comment by yalov** [comment]
There are plenty of not-only-English mods, list at forum has a tendency to become outdated. 
https://forum.kerbalspaceprogram.com/index.php?/topic/158018-addon-localization-home/

Introduce it to SCAN makes it up-to-date at CKAN.

**Comment by yalov** [comment]
@politas  if you want "start using the Mod Versions panel to give us extra functionality" from #2154 reconsider 1. there

**Comment by HebaruSan** [comment]
- CKAN's GUI was localized in #2749, including a German translation.
- We've been collecting the locales of modules in metadata since #2760.
- #2736 would provide a place to put this in the UI.
