### ISSUE TITLE
Please specify that linux (ubuntu, debian, other distro?) users should install the  mono-complete package

### ISSUE THREAD

**Issue by sapristi** [KSP-CKAN/CKAN#2124]
I tried using CKAN on debian testing, mono was installed, but couldn't start.
After some search I found that installing mono-complete solved the issue (on ubuntu 16.4).
A minor change in the wiki would make it easier for people to use CKAN.

**Comment by politas** [comment]
The wiki pages for [installing CKAN on Ubuntu](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu) and [installing CKAN on Debian](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Debian-Jessie-or-Debian-Stretch) both specify installing mono-complete. Which wiki says otherwise?

**Comment by Ruedii** [comment]
I'm not sure, but it might be good to also add it to the command line error and a user friendly error box for any library missing errors.  There is likely a way to do this with an error catch shim that catches the error, reports the user friendly dialog and console error, then passes it to the system handler so any attached debugging tools can get more detail.

Exact error should be along the lines:
"Missing library containing library object complete.mono.library.path
Please install a the complete Mono Runtime for your Operating System
This is the latest complete .Net Framework for Windows, 
The Mono-Complete for most Linux systems and
Mono Installer package (all modules but XSP and ASP) for Mac."

**Comment by politas** [comment]
Sounds like a good idea. Can you submit a PR to the codebase?

**Comment by HebaruSan** [comment]
Seems like the next step here would be to collect the exception that's raised when mono-complete is missing, so we can create a code path for showing a friendlier message. @sapristi or @Ruedii, do either of you have this handy?

**Comment by HebaruSan** [comment]
I guess not.
