### ISSUE TITLE
CKAN doesnt let me apply changes

### ISSUE THREAD

**Issue by Futureman07** [KSP-CKAN/CKAN#2126]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 1.22.3

**Operating System:** Win10

**The issue you are experiencing:** If I select a mod I want to install, I cannot click on 'apply changes'. Sadly, CKAN doesnt explain me why. 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
Are you selecting just a single mod, and do you have other mods installed already? If the Apply Changes button is greyed out, it usually indicates that you have some incompatible mods selected. Click on the Installed/checkbox column header to sort by installed mods. The conflicts should appear with a red background.

**Comment by Futureman07** [comment]
Thank you, it worked now :)

**Comment by Futureman07** [comment]
Gesendet: Donnerstag, 12. Oktober 2017 um 04:40 Uhr
Von: Myk <notifications@github.com>
An: KSP-CKAN/CKAN <CKAN@noreply.github.com>
Cc: Futureman07 <philipkius@web.de>, Author <author@noreply.github.com>
Betreff: Re: [KSP-CKAN/CKAN] CKAN doesnt let me apply changes (#2126)


Are you selecting just a single mod, and do you have other mods installed already? If the Apply Changes button is greyed out, it usually indicates that you have some incompatible mods selected. Click on the Installed/checkbox column header to sort by installed mods. The conflicts should appear with a red background.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.


Thank you, I checked the relationships now and all mods are working fine. Thank you for your help :)
