### ISSUE TITLE
I want too install a modpack but not all mods are installed and my KSP Crashes

### ISSUE THREAD

**Issue by henryscp** [KSP-CKAN/CKAN#2127]
**CKAN Version:** 
v.1.22.3

**Operating System:** 
win10
**The issue you are experiencing:** 
I want too install a modpack but nut all mods are installed and my KSP Crash every time because 1 file is missing
**How to recreate this issue:** 
install these modpack https://www.dropbox.com/s/ysr68y51wrzls19/modlist.ckan?dl=0
**CKAN error codes (if applicable):** 
dont know

**Comment by politas** [comment]
That modlist is a list of "recommends", so it will only install the mods that have compatible releases for the KSP version you are running. There are a few mods listed in that modpack that are obsolete, thanks to changes in how mods interrelate, making this modpack possibly not useful beyond KSP 1.2.2. I would advise removing all the Stock Visual Enhancements/Scatterer/EVE elements of the modpack and installing them separately, using the available options.

**Comment by henryscp** [comment]
Thx for the Help
