### ISSUE TITLE
Travis release process failing to deploy

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2133]
Not sure whether it always fails after a restart, or this was one-off. @dbent, can you take a look?
https://travis-ci.org/KSP-CKAN/CKAN/jobs/287925125

**Comment by politas** [comment]
Once again, the deploy has failed: https://travis-ci.org/KSP-CKAN/CKAN/jobs/288102463

**Comment by Olympic1** [comment]
I think 8805870 broke the build process. I'm not a cake expert but I think the `'` should be `` ` ``

@dbent is that correct?

**Comment by dbent** [comment]
@Olympic1 Nah, that change should be fine and it's only for the Windows build script anyway, which Travis does not use, it uses the Linux build script `build` (no `.ps1`). See #2151 for potential fix for this.

**Comment by politas** [comment]
Rosolved bt #2151
