### ISSUE TITLE
wont start after update, wont uninstall

### ISSUE THREAD

**Issue by Cstrider** [KSP-CKAN/CKAN#2145]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 

**Operating System:** 

**The issue you are experiencing:** 

**How to recreate this issue:** 

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
No details in template = closed ticket
