### ISSUE TITLE
User Guide broken images

### ISSUE THREAD

**Issue by ChaoticWyrme** [KSP-CKAN/CKAN#2146]
The [user guide](https://github.com/KSP-CKAN/CKAN/wiki/User-guide) has a number of broken images.
![image](https://user-images.githubusercontent.com/19155523/31617945-9edf9d80-b25e-11e7-8a82-81f81d3d29f1.png)

**Comment by HebaruSan** [comment]
Thanks for reaching out. I have replaced them with new screenshots.
