### ISSUE TITLE
updating multiple mods

### ISSUE THREAD

**Issue by Draconomial** [KSP-CKAN/CKAN#2152]
Whenever I try to install more than one mod update at a time, I get this message.

"Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install *mod* via the CKAN,
then please manually uninstall the mod which owns:

GameData/*mod*

and try again.

Your GameData has been returned to its original state.

Error!"

Using CKAN 1.22.6

**Comment by politas** [comment]
If you're getting a lot of these errors on unrelated mods, a [clean & reinstall](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process) is probably called for.
