### ISSUE TITLE
GUI not appering under Ubuntu 17.10 

### ISSUE THREAD

**Issue by Midgardsomr** [KSP-CKAN/CKAN#2157]
Hi all,

installed Ubuntu 17.10 today and tried to use ckan. Since 17.10 uses Wayland as default, maybe theres a problem with the WinForms gui. The ckan window simply does not appear, but the program seems to running normally if I'm not mistaken.

**CKAN Version:  v1.22.6** 

**Operating System: Ubuntu 17.10** 

**The issue you are experiencing: GUI not appering** 

`mono ckan.exe --debug
190 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
208 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
212 [1] DEBUG CKAN.KSPManager (null) - Loading auto from /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
216 [1] DEBUG CKAN.KSP (null) - Initialising /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
217 [1] DEBUG CKAN.KSP (null) - Initialised /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
224 [1] DEBUG CKAN.KSPManager (null) - Added auto at /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
431 [1] INFO CKAN.Main (null) - Starting the GUI
721 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
722 [1] DEBUG CKAN.KSPManager (null) - Loading auto from /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
722 [1] DEBUG CKAN.KSP (null) - Initialising /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
722 [1] DEBUG CKAN.KSP (null) - Initialised /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
722 [1] DEBUG CKAN.KSPManager (null) - Added auto at /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
723 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: /home/midgardsomr/bin
873 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
996 [1] DEBUG CKAN.RegistryManager (null) - Loaded CKAN registry at /home/midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.json
1199 [1] DEBUG CKAN.Main (null) - Asking user if they wish for autoupdates
`

**Comment by politas** [comment]
Have you installed the mono-complete package, and what does `mono --version` report?

**Comment by Midgardsomr** [comment]
Yes mono-complete is installed. Mono version output:

Mono JIT compiler version 4.6.2 (Debian 4.6.2.7+dfsg-1ubuntu1)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen

**Comment by politas** [comment]
Can you try sourcing Mono from the Mono Project? The [Installing on Ubuntu](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Ubuntu) page has the details.

**Comment by Midgardsomr** [comment]
Tried with Mono repository from Mono Project: 

Mono JIT compiler version 5.4.0.201 (tarball Fri Oct 13 21:51:45 UTC 2017)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	LLVM:          supported, not enabled.
	GC:            sgen (concurrent by default)

But still no ckan window appearing. I tried also it also with xorg session instead of wayland, but nothing changes so it looks like it has nothing to do with wayland.

Output from ckan --debug:

mono ckan.exe --debug
196 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
218 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
223 [1] DEBUG CKAN.KSPManager (null) - Loading auto from /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
226 [1] DEBUG CKAN.KSP (null) - Initialising /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
227 [1] DEBUG CKAN.KSP (null) - Initialised /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
233 [1] DEBUG CKAN.KSPManager (null) - Added auto at /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
Could not set X locale modifiers
/usr/share/themes/Ambiance/gtk-2.0/apps/mate-panel.rc:30: error: invalid string constant "murrine-scrollbar", expected valid string constant
448 [1] INFO CKAN.Main (null) - Starting the GUI
732 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
733 [1] DEBUG CKAN.KSPManager (null) - Loading auto from /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
733 [1] DEBUG CKAN.KSP (null) - Initialising /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
733 [1] DEBUG CKAN.KSP (null) - Initialised /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
733 [1] DEBUG CKAN.KSPManager (null) - Added auto at /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program
734 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: /home/Midgardsomr/bin
887 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
1021 [1] DEBUG CKAN.RegistryManager (null) - Loaded CKAN registry at /home/Midgardsomr/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.json
1221 [1] DEBUG CKAN.Main (null) - Asking user if they wish for autoupdates

**Comment by politas** [comment]
Are you on Ubuntu Mate 17.10?

**Comment by Midgardsomr** [comment]
No, vanilla ubuntu 17.10. Something strange happens. Mostly i use a dual display setup. Yesterday i used only one display and ckan appears as it should. And even after reconnecting the other displays it works. Maybe the window was there the whole time but was anyhow out of sight. Even the dock icon from ckan is visible now.

However, thanks for your support.

**Comment by politas** [comment]
That sounds like a possibility. That debug output certainly looks pretty normal and doesn't show any particular error.
