### ISSUE TITLE
Feature request: `ckan repl` command

### ISSUE THREAD

**Issue by mathuin** [KSP-CKAN/CKAN#2161]
https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop

I think it would be helpful to have a read-eval-print loop for CKAN so folks can run commands from the command line without having to type `ckan this` and `ckan that`.

```
$ ckan repl
ckan> update
ckan> upgrade --all
ckan> quit
$
```

This would be especially helpful for non-GUI users.

**Comment by HebaruSan** [comment]
This would also have the advantage of allowing command line users to keep `registry.json` loaded across multiple related commands. It's currently up to 20MB and will only get bigger, and loading it takes 2 seconds on my system, so running these commands in sequence:
```
ckan update
ckan list
ckan upgrade --all
ckan available
ckan install NewMod
```
... requires 8 seconds of redundant JSON processing.

**Comment by politas** [comment]
A CKAN shell, basically? Seems plausible.
