### ISSUE TITLE
'Apply Changes' is always grayed out.

### ISSUE THREAD

**Issue by Btini0** [KSP-CKAN/CKAN#2166]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

So, this issue has ben going on for a while. I didn't think any of it until needing to update some mods, so I tried some fixes. None worked, so I've resorted to here.

**CKAN Version: v1.22.6** 

**Operating System: Windows 10 64x** 

**The issue you are experiencing:**

 When clicking the checkbox for a mod/update, Apply Changes is always grayed out. I did a search, but none of the fixes worked (Search for incompatible mods, etc.)

**How to recreate this issue:** 

I'm using KSP 1.3.0.

Modlist
https://gyazo.com/0eec386f526b16f503f84a602bbf37df
https://gyazo.com/2f75b7d58dbf4faf8f4e3d1f3eeb5a38

Not trying to install anything, just update the ones that need to be updated.

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Please fill in the "How to recreate this issue" section of the template so we can try to help. A good start would be your version of KSP and your current mod list, plus whatever you're trying to install or update.

**Comment by Btini0** [comment]
So far, I have no idea how it happens or how to recreate it. It's been like this for a few weeks now, and like I said I just ignored it until now.

**Comment by HebaruSan** [comment]
What about your version of KSP and your current mod list, plus whatever you're trying to install or update?

**Comment by Btini0** [comment]
I'm using KSP 1.3.0.

Modlist
https://gyazo.com/0eec386f526b16f503f84a602bbf37df
https://gyazo.com/2f75b7d58dbf4faf8f4e3d1f3eeb5a38

**Comment by HebaruSan** [comment]
Thanks, I've added that to the original issue report text.

So you're updating all of them all at once?
Are you able to update any of them individually if you click one by one?

**Comment by Btini0** [comment]
I tried both. Nothing.

**Comment by politas** [comment]
Can you try a [Clean & reinstall](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process) That should help you identify the issues at least (or it may just fix it all!)

**Comment by Btini0** [comment]
That worked, thank you so much!
