### ISSUE TITLE
Trouble Installing!

### ISSUE THREAD

**Issue by Balls99** [KSP-CKAN/CKAN#2168]
I tried installing Ckan for KSP today for the first time and after downloading it doesnt allow me to select my KSP file on start up, it only allows me to open files not select. Am i doing something wrong?

![2017-10-31](https://user-images.githubusercontent.com/33257375/32227056-0f82ac8c-be42-11e7-8b49-34e30ae1e1da.png)

**Comment by HebaruSan** [comment]
Click the `buildID.txt` file and accept the popup.
