### ISSUE TITLE
CKAN detects wrong game version

### ISSUE THREAD

**Issue by Hunter-The-Gamer** [KSP-CKAN/CKAN#2190]
Thanks for wanting to bring an issue to our attention!

Before you open a ticket, please do a quick search of the existing issues to see if it's already been brought up.

**CKAN Version:** 
1.22.6
**Operating System:** 
Windows 10
**The issue you are experiencing:** 
When I updated KSP in Steam from 1.2.2 to 1.3.1, I expected CKAN to detect the update and start showing me to install mods for the new version. Instead, I can still only install 1.2.2 mods.
**How to recreate this issue:** 
I don't really know, it just doesn't work
**CKAN error codes (if applicable):** 
None
**Additional information:**
This is in the default Steam directory, with a fresh install (no mods, manual or CKAN)

**Comment by HebaruSan** [comment]
Can you show us some examples of mods for 1.3.1 that you think should be shown and are not, and mods for 1.2.2 that you think should be hidden that are shown? Alt-PrintScreen captures a screenshot on Windows, and you can paste it into a GitHub issue with ctrl-V.

**Comment by Hunter-The-Gamer** [comment]
Sure thing!

## For 1.3:
![image](https://user-images.githubusercontent.com/29361536/33181208-570dcfde-d03d-11e7-81c5-a2edfecd6343.png)

![image](https://user-images.githubusercontent.com/29361536/33181300-bd588dce-d03d-11e7-88d4-5c7d14331b46.png)

![image](https://user-images.githubusercontent.com/29361536/33181392-1b85588c-d03e-11e7-857e-c348cf9982eb.png)

## For 1.2:
![image](https://user-images.githubusercontent.com/29361536/33181347-e81ed8a6-d03d-11e7-8679-4fe58b340fba.png)

![image](https://user-images.githubusercontent.com/29361536/33181933-eeabc812-d03f-11e7-944f-a697780acf36.png)

![image](https://user-images.githubusercontent.com/29361536/33181528-8deb0e94-d03e-11e7-95d6-8c01ec0cd6c3.png)


As the top of the images show, CKAN  detects the game as being 1.2.2.1622, while when I start the game from Steam,

![image](https://user-images.githubusercontent.com/29361536/33181849-b39db1e0-d03f-11e7-9a26-74e593992751.png)

the bottom clearly shows version 1.3.1.1891. Note, launching from CKAN starts version 1.2.2.

**Comment by HebaruSan** [comment]
> Note, launching from CKAN starts version 1.2.2.

Hmm, that would not be possible if you only had 1.3.1 installed on your system (the 1.3.1 executable would have overwritten the one for 1.2.2). There must be a copy of 1.2.2 installed somewhere, and that's what CKAN knows about, and 1.3.1 is somewhere else.

Can you try this?

1. Right click Kerbal Space Program in Steam
2. Select Properties
3. Click the LOCAL FILES tab
4. Click BROWSE LOCAL FILES

![image](https://user-images.githubusercontent.com/1559108/33182449-aed6e4a2-d039-11e7-8080-8908145b5644.png)

That should open a file browser in the folder where your 1.3.1 is installed. Once you have that path, you can add it to CKAN via File -> Select KSP Install...

**Comment by Hunter-The-Gamer** [comment]
It worked! Thank you so much! If I had to guess, the location I had pinned as the default one was actually a slightly different location

**Comment by HebaruSan** [comment]
Glad you figured it out! :+1:
