### ISSUE TITLE
CI not Pushing Builds to S3

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#2191]
The latest build on S3 is from October 20. Noted in #2189 as Netkan Bot hadn't picked up the fixed Curse API.

```
leon@beast /tmp $ (rm netkan.exe || true) && wget -q http://ckan-travis.s3-website-us-east-1.amazonaws.com/netkan.exe && mono netkan.exe --version
rm: cannot remove 'netkan.exe': No such file or directory
v1.22.7-PRE+bd1c5daa6a5a
```

**Comment by HebaruSan** [comment]
Browsing the commit history, `.travis.yml` was changed the day after that, in https://github.com/KSP-CKAN/CKAN/commit/2ab5dce836ec0f0e6af055a8c9ae430582dd4891 and https://github.com/KSP-CKAN/CKAN/commit/94332582358c31566fc5335036e44bd8109e6b12 , but it's not clear to me why that would have caused any problems.

@dbent, do you see anything fishy there?

**Comment by techman83** [comment]
And we're good. The netkan bot will pick up the new version on the next run.
```
➜  /tmp (rm netkan.exe || true) && wget -q http://ckan-travis.s3-website-us-east-1.amazonaws.com/netkan.exe && mono netkan.exe --version
rm: cannot remove 'netkan.exe': No such file or directory
v1.24.0-PRE+0eacb1575574
```
