### ISSUE TITLE
CKAN opens a console window when launching from Windows Explorer (or a shortcut)

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#2193]
**CKAN Version:** 
v1.24.0-PRE+0eacb1575574

**Operating System:** 
Windows 10 (64-bit)

**The issue you are experiencing:** 
Double-clicking on 'ckan.exe' (or an equivalent shortcut) opens a Command-prompt before opening the GUI; the Command-prompt persists while the GUI is running.

I can't recall older versions of CKAN exhibiting this behaviour, but I'm not sure when this changed or even if my recollection is faulty in this regard.

Additionally, in my case, I use the "ConEMU" application. This means that when I start CKAN, it jumps to the last active ConEMU window and opens a new tab in that - even if that is on another Virtual Desktop.

It would be very nice if opening up the console could be prevented when launching the CKAN binary from a GUI.

I had a quick play, and changing the CKAN-cmdline application from 'Console Application' to 'Windows Application' does fix it, but unfortunately this completely prevents command-line interaction with ckan so is not an option.

**How to recreate this issue:** 
Double-click on 'ckan.exe' from Windows Explorer

**Comment by Olympic1** [comment]
When I start ckan from windows explorer it opens a command prompt, then the window to choose a KSP instance. After choosing one, both windows close and open the GUI.

**Comment by linuxgurugamer** [comment]
I don't see this as a problem.  And, it's been doing this for as long as I can remember

**Comment by mwerle** [comment]
> I can't recall older versions of CKAN exhibiting this behaviour, but I'm not sure when this changed or even if my recollection is faulty in this regard.

Ok, it seems that it's my particular configuration of ConEmu that's highlighted this issue.  I can work around it and presumably nobody else is bothered by the temporary console window popping up.

**Comment by errolkokbas** [comment]
Did anyone ever find any solution?

I first started seeing this on my new win11 pc.... and it's honestly kind of annoying given that it didn't happen before on win10 and I usually have a few things running at once, so less taskbar clutter would be better.
