### ISSUE TITLE
Ckan having issues patching ksp interstellar extended

### ISSUE THREAD

**Issue by iurirolho** [KSP-CKAN/CKAN#2196]
**CKAN Version: v1.22.6** 

**Operating System: Win 10 64bit** 

**The issue you are experiencing: Ckan having issues downloading the mod on title** 

**How to recreate this issue:Download mod from list and get error(thats what i got so far)(i get a 404 error)** 

**CKAN error codes (if applicable): 404 ** 
if this has been reported already feel free to close it or mention me with the solution/fix for this issue 
thanks for your time

**Comment by HebaruSan** [comment]
I just tried this and it worked for me. Are you still having this issue?

**Comment by iurirolho** [comment]
Am at work but I try again once am home I tried mainly to install from scratch the mod like on a fresh install I made to update my mod list

**Comment by iurirolho** [comment]
Failed to download "https://spacedock.info/mod/172/KSP Interstellar Extended/download/1.15.3" - error: The remote server returned an error: (404) Not Found. i got that error then it throws that after i hit dismiss
![image](https://user-images.githubusercontent.com/20928051/33377726-658d3eec-d50a-11e7-82f6-1481d3dcc5d9.png)

**Comment by Olympic1** [comment]
v1.15.3 was removed from spacedock a couple days ago. I don't know why he did that.

**Comment by HebaruSan** [comment]
v1.15.4 (for KSP 1.3.0) was released the same day as v1.16.2 (for KSP 1.3.1), and only 1.16.2 got picked up by the bot. The author probably wants people only to use the latest version for each game release. If we can index v1.15.4, this should be fixed.

**Comment by HebaruSan** [comment]
1.15.4 is now indexed, so you should be able to install if you refresh the mod list. Closing.
