### ISSUE TITLE
Repository item replaced with inconsistent entry yields exception

### ISSUE THREAD

**Issue by uxlapogi** [KSP-CKAN/CKAN#2200]
**CKAN Version:** 
1.22.6

**Operating System:** 
Win10

**The issue you are experiencing:** 
Repository item replaced with inconsistent entry

**How to recreate this issue:** 

```
About to install...

 * NavHud 1.3.4(cached)

The following inconsistencies were found:
NavHudRenewed wishes to install GameData/NavHud/NavHud.version, but this file is registered to NavHud
 * NavHudRenewed wishes to install GameData/NavHud/Plugins/NavHud.dll, but this file is registered to NavHud
 * NavHudRenewed wishes to install GameData/NavHud/ToolbarIcon.png, but this file is registered to NavHud



Error!
```

NavHud has been removed from the repository and replaced with NavHudRenewed, however it is still called NavHud. Internally it uses NavHudRenewed.

Also this results in an exception when trying to install StockVisualEnhacements:

[https://imgur.com/a/Z6WtL](https://imgur.com/a/Z6WtL)

Apparently it is looking for NavHud but "Cannot install NavHud, module not available."

Manually installing either mod severely upsets CKAN (it is so upset with the state of affairs it flat out refuses to recognize either).

**Comment by HebaruSan** [comment]
Do you still have the older one installed?

**Comment by uxlapogi** [comment]
No. The first time I downloaded NavHud was when I attempted to install Stock Visual Enhancement giving said exception.

**Comment by uxlapogi** [comment]
It might be necessary to split this into three different issues.
1. Having a non-existent module in a requirement or recommendation shouldn't give an exception.
2. Having something registered to something else should give the option to overrule.
3. Removing a module shouldn't screw everything else.

**Comment by HebaruSan** [comment]
I installed NavHudRenewed, and did not see this issue. So we need to figure out what's different on your system.

CKAN seems to think you do (or did) have NavHud installed. That's what "this file is registered to NavHud" means. Did you uninstall NavHud manually, perhaps?

**Comment by uxlapogi** [comment]
My mistake, i had NavHud 1.3.0 installed and deleted it.
Now I can't install or update it again.

**Comment by uxlapogi** [comment]
Got it to work with the CLI, for some reason it found the remnants of the old NavHud

**Comment by uxlapogi** [comment]
Thanks for the help. :)

**Comment by HebaruSan** [comment]
Glad you figured it out!
