### ISSUE TITLE
Feature: divider position persistance

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2208]
This has been a thing for me pretty much since CKAN.  Would it be possible to make the divider maintain it's position when placed?

I've uploaded a screenshot of what I'm talking about.
![screenshot from 2017-12-05 11-01-19](https://user-images.githubusercontent.com/4062616/33625615-f86d46de-d9ac-11e7-97a3-5510008ae0ac.png)

**Comment by 7ranceaddic7** [comment]
Yes.  It always resets to the width of the "Metadata", "Relationships","Contents" tabs; so, only the "Versions" tab is hidden.

**Comment by politas** [comment]
Well, we save WindowSize and WindowLoc in GUIConfig.xml, so there's no reason we can't add the position of that divider as well.
