### ISSUE TITLE
GUI dependency list omits unavailable mods

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2224]
Problem
-------

The Relationships tab in GUI leaves out entries if the depended-upon mod isn't compatible with the currently selected version. The dependency is still there in the registry object, it's just not shown to the user. This is pretty unhelpful since one of the main things the user might want to know about an incompatible mod is why it's incompatible and how hard it would be to update it, and dependencies are a big part of that.

https://github.com/KSP-CKAN/CKAN-meta/blob/7b70dd4d2e8f6979e4db43762f64ec17af24eb69/AV8HarrierWITHTRUEVTOLFlight/AV8HarrierWITHTRUEVTOLFlight-104.105.ckan#L15-L22

```json
    "depends": [
        {
            "name": "FirespitterCore"
        },
        {
            "name": "BahamutoDynamicsPartsPack"
        }
    ],
```

![missing dep](https://user-images.githubusercontent.com/1559108/34058168-a14285b8-e19f-11e7-81d0-dbc44948ec43.png)

Discovered by @politas during testing of #2216.

Cause
-----

The GUI code that loads this display just skips dependencies that aren't compatible.

https://github.com/KSP-CKAN/CKAN/blob/fd270ebcea8332c01288fe44a6bcfa148b72223f/GUI/MainModInfo.cs#L190-L201

Suggestions
-----------

If the current calls fail, pass `null` instead of `manager.CurrentInstance.VersionCriteria()`. This would return the latest version of the mod regardless of compatibility. We should include some visual indication of the problem, such as setting `node.ForeColor = Color.Red` or possibly listing the compatible KSP version range.

**Comment by politas** [comment]
It would also be nice to have a "Relationships browser" that deep-dives into all the relationships for a mod and shows the mods that depend on it as well as its dependencies, and recommendations all mixed in. That's a bit pie in the sky and not as critical as just making the Depends list show all the dependencies.

**Comment by HebaruSan** [comment]
I've got some code that does most of this, but the `Windows.Forms.TreeView` class is unbelievably badly behaved and has been sabotaging me at random. E.g. it seems to take several seconds to add a new node once you have a few dozen of them, so now I'm fishing for workarounds for things like that rather than polishing the UI. Boo winforms.

![image](https://user-images.githubusercontent.com/1559108/34086666-6b9d1c6e-e363-11e7-992f-01b504840a4e.png)
