### ISSUE TITLE
HTTP 403 from spacedock

### ISSUE THREAD

**Issue by inrepublica** [KSP-CKAN/CKAN#2229]
Background
----------
**CKAN Version:**
1.22.6

**KSP Version:**
1.31.1891

**Operating System:**
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**What steps did you take in CKAN?**
 Install any mods from spacedock.info (example [x] Science !)

**What did you expect to happen?**
 Install the mod

**What happened instead?**
```
 Failed to download "https://spacedock.info/mod/234/[x] Science!/download/v5.11" - error: Le serveur distant a retourné une erreur : (403) Interdit.
```

**Screenshots:**

![image](https://user-images.githubusercontent.com/1835999/34306090-b449f8a6-e741-11e7-86ea-2a1768c38f32.png)

**CKAN error codes (if applicable):**
HTTP 403. Same things with firefox (https://spacedock.info/content/zkeyaerospace_1268/x_Science/x_Science-v5.11.zip).

**Comment by inrepublica** [comment]
Ok, i've tested with another ISP and there is no problem... Sorry for the inconvenience.

**Comment by HebaruSan** [comment]
Glad you got it working!
