### ISSUE TITLE
Getting started on a Mac

### ISSUE THREAD

**Issue by jknowles831** [KSP-CKAN/CKAN#2244]
Background
----------

**CKAN Version:** 

**KSP Version:** 
I Have only ever run 1.3 but am trying to get rss and to do so it looks like I need to use 1.2. So I went to the website and got 1.2 so I now have 1.3 and 1.2 on my desktop in seperate folders. 

**Operating System:** 
I have mac os x el capitan. 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
I am trying to get ckan because I am having a hard time downloading all the dependancies for rss and overhaul without it. But I seem to be having just as hard of time getting the ckan to work!! I downloaded the mono. Opened the terminal to run. The program opens to the select KSP install window. I have no options to pick from so I click add new. 

**What did you expect to happen?**

**What happened instead?**
I am able to look through the whole computer but it wont let me select anything. Everything I find is in folder form and can not be selected, only opened. Hoping someone can tell me what I am doing wrong. Thanks in advance

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
CKAN needs to know where your KSP is installed. Once you are in the Add option of the Select KSP install window, try navigating to the 1.2 folder and choosing the buildID.txt file.

**Comment by HebaruSan** [comment]
Possibly related to #1276.

**Comment by HebaruSan** [comment]
I guess that must have worked? @jknowles831, if you are still having problems, please reply with details and we can re-open this.
