### ISSUE TITLE
Windows 10 launch issue

### ISSUE THREAD

**Issue by McScribble** [KSP-CKAN/CKAN#2247]
Background
----------

**CKAN Version:** 

1.24.0

**KSP Version:** 

1.3.1.1891

**Operating System:** 

Windows 10, Fall Creators

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

No

Problem
-------

**What steps did you take in CKAN?**

I installed the latest CKAN version and ran it as an Admin

**What did you expect to happen?**

CKAN to bring up the mod list and available mods

**What happened instead?**

A pop up window with an error message reading: "Failed to connect to repository. Exception: Header checksum is invalid"

This also happens with any attempt to refresh CKAN.  No mods are shown in the app window

**Screenshots:**

![image](https://user-images.githubusercontent.com/35321145/34807509-328fc1d6-f657-11e7-9fc1-0a67f0b16d72.png)

**CKAN error codes (if applicable):** 
![image](https://user-images.githubusercontent.com/35321145/34807524-44e37fda-f657-11e7-9fcb-5ea92d669749.png)

**Comment by HebaruSan** [comment]
Thanks for the report! (And thanks for testing the pre-release!)

Can you try this from a command line? You might have to `cd` to the folder where you installed ckan.exe.

```cmd
ckan update --verbose
```

That should run the same operations but with more logging output to help us pinpoint the problem.
