### ISSUE TITLE
Could not establish trust relationship for the SSL/TLS secure channel

### ISSUE THREAD

**Issue by uniybee** [KSP-CKAN/CKAN#2250]
im trying to download [x] science but i says "Failed to download "https://spacedock.info/mod/234/[x] Science!/download/v5.11" - error: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel"

i have win 10 64-bit   ckan 1.22.6  .NET 4.5

**Comment by PapaOscar90** [comment]
Having same problem. For several mods it cannot connect. RemoteTech, Scatterer, kOS to name a couple.

**Comment by nevercast** [comment]
SpaceDock SSL certificate expired. Setting your clock back in time to the 12th/13th is a workaround (before expiration date). If you don't mind the added risk of using an expired certificate. 

Overall, this is a problem with SpaceDock. However CKAN could offer a setting to disregard SSL errors, though it's implications should be explained, after all you are downloading executable code.

**Comment by viperfan7** [comment]
The fact that a faulty SSL cert causes a hardcrash in CKAN means it needs an option to ignore SSL certs

**Comment by uniybee** [comment]
@nevercast Thanks! That worked for me.

**Comment by HebaruSan** [comment]
Please remember to check previous issues before adding a new one: #2249, KSP-CKAN/NetKAN#6168

> The fact that a faulty SSL cert causes a hardcrash in CKAN means it needs an option to ignore SSL certs

@viperfan7, I'm not seeing a hard crash. There's just an error message explaining why the download failed, and then the app is usable again. Does it actually stop running for you?

**Comment by TheDanMan2** [comment]
Having same problem. Sometimes for a short time the download started, but a second later there was an error. Sometimes for a short time the download started, but a second later there was an error. What is the reason?

**Comment by HebaruSan** [comment]
@TheDanMan2, see above, the reason is a problem with SpaceDock's server. You can confirm this problem by trying to visit the SpaceDock with a browser.

**Comment by alrabe** [comment]
Bug - after SSL error:
Either I choose to close after the app form the dialog after the SSL error pop-up, than this will result in a Windows dialog a'la "CKAN is not reacting" (in German here). Or I choose to continue CKAN, than I'm not able to close the application later.

**Comment by TheCryptek** [comment]
Wouldn't it just be easier to contact spacedock support and tell them they need to update their certificate?

**Comment by HebaruSan** [comment]
@alrabe, can you please try the [1.24 pre-release](https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0-PRE-1) and let us know if you still have the "CKAN is not reacting (in German)" problem? I tested this earlier and I did not see that problem; maybe this exception is now handled as a side effect of one of the other changes.

**Comment by 7ranceaddic7** [comment]
The certificate has been updated.

**Comment by HebaruSan** [comment]
Till next time, then...

**Comment by nevercast** [comment]
Friendly reminder! Any of you that set your clocks back, you'll need to set them to real time again ;)

**Comment by Blu3wolf** [comment]
I get the same error when trying to get the list of mods in CKAN. Fresh install, cant connect.

Oddly, I can browse to the location it looks for with my browser just fine.

**Comment by dxeh** [comment]
@Blu3wolf I Second that. Also cannot connect to CKAN even after reinstall..

"Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established."

**Comment by VladoPortos** [comment]
Same issue as @dxeh , there really should be option not to use SSL as its more times broken than working...

**Comment by sundhaug92** [comment]
Solved: Use 1.24 or later

**Comment by i20100** [comment]
Download the new ckan.exe, run it. And problem should be solved. 
Link to exe: https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0
