### ISSUE TITLE
Ability to include program switched at part of launch

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2251]
Would it be possible to include optional switched to be applied at launch?

I know this is an edge-case; so, feel free to say no.

Specifically, I'm thinking about this:

./KSP.x86_64 -mm-dump

Other suggestions are welcome.

P.S.  Thank you for Save and restore panel position #2234

**Comment by HebaruSan** [comment]
I believe that's covered by this menu option:

![image](https://user-images.githubusercontent.com/1559108/34921217-166a7d34-f977-11e7-98db-25199a955e02.png)

![image](https://user-images.githubusercontent.com/1559108/34921219-1d44a166-f977-11e7-899c-1387436702d9.png)

Does it work for you?

**Comment by 7ranceaddic7** [comment]
Yep, that works.  Completely missed that feature.

Thanks.
