### ISSUE TITLE
Unhandled exception for no space on drive

### ISSUE THREAD

**Issue by codenamebambi** [KSP-CKAN/CKAN#2252]
Version 1.3.1.1891

In short if you are trying to install mods you don't have the storage space for, it will throw an exception.

Obviously this isn't a big issue but would be nice to have an appropriate error message and possibly be handled by notifying the user that they don't have enough storage space and retry once they clear some up. I would be willing to fix this myself if someone wants to point me to the right file(s), i just don't have the time to go through the project to find it right now.

**Comment by HebaruSan** [comment]
Would you mind sharing the exception text and stack trace? I don't have a full drive available at the moment for testing.
