### ISSUE TITLE
SSL error on Fedora

### ISSUE THREAD

**Issue by ykonoclast** [KSP-CKAN/CKAN#2253]
Background
----------
I seem to be having the same problem as this issue here :
https://github.com/KSP-CKAN/CKAN/issues/2102

I tried following directions from [there](https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Fedora) and ran mozroots --import --ask-remove to no avail. 

**CKAN Version:** tried all from 1.22.1 to 1.24.0-PRE-1

**KSP Version:** 1.3.1.1891 x86_64

**Operating System:** Fedora 26 x86_64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Nope

Problem
-------

**What steps did you take in CKAN?** launching it and tried to download a mod

**What did you expect to happen?** that it would launch without error message and would download the mod

**What happened instead?** pop-up window (once on auto-update at launch and once on downloading) with the following message : Error: TrustFailure (Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED)

**Comment by HebaruSan** [comment]
Which mod, and when did you try? SpaceDock's certificate expired within the last day or two and only got renewed late yesterday, so if you were downloading from SpaceDock about 24 hours ago, an SSL error would be expected.

**Comment by politas** [comment]
As stated in the release notes:

- Mac/Linux/Mono users: please use the new [cert-sync](http://www.mono-project.com/docs/about-mono/releases/3.12.0/#cert-sync) tool, to update mono's certificate store.

**Comment by ykonoclast** [comment]
Did work, thanks.

You might want to update your documentation as it is the place where users are looking for instructions, such a necessity should not be mined in the release notes of a given version.

**Comment by HebaruSan** [comment]
@ykonoclast, thanks for the feedback. I added some more text to the Fedora wiki page, but I wasn't sure of the best formatting. Can you take a look? Please feel free to make your own edits, it's a wiki after all.

**Comment by ykonoclast** [comment]
@HebaruSan
Good idea! I went there and added a few clarifications using this morning's experience in actually being able to use CKAN.
