### ISSUE TITLE
[wiki] shields.io badge

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2255]
Check code for the badge for forum at Wiki/FAQ page.
straight copy-paste don't works. Looks like forum changed after that code had been written.

Also, it is simple text, it doesn't check indexation, correct?

**Comment by HebaruSan** [comment]
Thanks for letting us know. I made two edits: the URL is updated, and the forum instructions are simpler (the current forum no longer uses BBCode). Please take a look.

**Comment by yalov** [comment]
It was worked with "insert image from url", but not as simple text. There is no markdown support for forum?

**Comment by HebaruSan** [comment]
Ahh, the text does work, but you have to circumvent the forum's attempts to paste it either as a link or as rich text. I have updated the instructions.

No, the current KSP forum does not support markdown or any other formatting syntax. It's exclusively WYSIWYG.
