### ISSUE TITLE
Bad JSON in CactEyeTelescopesContinued metadata files

### ISSUE THREAD

**Issue by CraigCottingham** [KSP-CKAN/CKAN#2261]
The CactEyeTelescopesContinued mods appear to have been discontinued and taken offline. A comment was added to all five metadata files, like:

```{
    "comment": "GitHub Repo has been deleted or made private"
    "spec_version": "v1.4",
```

Note that there's no comma at the end of the value for `comment`, making the contents of the metadata file invalid JSON and unparseable.

**Comment by HebaruSan** [comment]
Thanks for catching that. Do you need to parse them? I don't think CKAN will look at files with a .frozen file name extension.

**Comment by CraigCottingham** [comment]
I don't need to parse them, as long as I can depend on the `.frozen` file name extension.

Thanks for addressing this!

**Comment by HebaruSan** [comment]
You can rely on slightly more than that; the client skips any metadata file without a .ckan extension:

https://github.com/KSP-CKAN/CKAN/blob/26ff29b007c8a1c6bbfe774007023f567bb2c0ca/Core/Net/Repo.cs#L475-L486
