### ISSUE TITLE
The old client isn't going to be able to auto-update

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2267]
## Problem

CKAN 1.22.6 and earlier assume that ckan.exe is always the first asset in a release post when attempting to auto-update.

https://github.com/KSP-CKAN/CKAN/blob/f19213e34122191e37beea53fd7625b1085eff41/Core/Net/AutoUpdate.cs#L153-L162

As of #2187, #2212, and #2225, [we publish multiple assets](https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0-PRE-1), and ckan.exe is the **third**, after AutoUpdate.exe and CKAN.dmg. But an earlier release attempting to auto-update will download the first asset, which is AutoUpdate.exe, and run it instead of the newer ckan.exe. Obviously this is bad.

I tried editing the release to remove and re-add the assets in the correct order, and it didn't help; they reverted to the current ordering. GitHub seems to think that assets should always be in alphabetical order.

Since the released client assumes the file it needs will be `assets[0]`, and we can't make that happen, we're in a bit of a bind.

## Suggestions

After the next full release is published:

1. Download all the assets other than ckan.exe
2. Quickly edit the release
3. Remove all assets other than ckan.exe
4. Re-add the other assets as links in the release note text

For subsequent releases, #2266 fixes the first-asset assumption, so we should be able to publish them normally.

**Comment by politas** [comment]
Well, that's annoying. Seems like a good suggestion, though it does mean that our 1.24.0 release is going to have to be solid  enough to not require any quick patches. We'll have to wait for users to upgrade to that before replacing with an all - asset release

**Comment by HebaruSan** [comment]
Another option might be to add a duplicate asset called "000_ckan.exe", which ought to sort to the top so the old client can find it. I haven't tested that out yet though...

**Comment by HebaruSan** [comment]
No longer relevant, since the old client wasn't able to auto update at all anyway!
