### ISSUE TITLE
Recommendations with virtual dependencies don't appear in GUI

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2268]
Background
----------

**CKAN Version:** 
1.22.6 and current HEAD

**KSP Version:** 
1.3.1

**Operating System:** 
Windows 7, Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
1. Create a .netkan file with Scatterer as a recommendation
2. Run it through netkan.exe
3. In GUI, File &rarr; Install from .ckan...
4. Select the .ckan file generated in step 2

**What did you expect to happen?**
Scatterer should appear in the list of recommended mods to install

**What happened instead?**
Other recommendations appear, but Scatterer doesn't.

**Screenshots:**
![screenshot 2018-01-29 20 58 10](https://user-images.githubusercontent.com/1559108/35540926-28cad7c8-0550-11e8-94cd-50186418fddd.png)

**CKAN error codes (if applicable):** 

I instrumented the code with various exception handlers in `Main.GetShowableMods`:

```
Exception thrown looking up Scatterer: Exception of type 'CKAN.InconsistentKraken' was thrown.
   at CKAN.SanityChecker.EnforceConsistency(IEnumerable`1 modules, IEnumerable`1 dlls)
   at CKAN.RelationshipResolver.AddModulesToInstall(IEnumerable`1 modules)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 modules, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
   at CKAN.RelationshipResolver..ctor(IEnumerable`1 module_names, RelationshipResolverOptions options, IRegistryQuerier registry, KspVersionCriteria kspversion)
   at CKAN.Main.GetShowableMods(Dictionary`2 mods)
```

```
Kraken for Scatterer: The following inconsistencies were found:
Scatterer has an unmet dependency: Scatterer-sunflare is not installed
 * Scatterer has an unmet dependency: Scatterer-config is not installed
```

That function turns off handling of virtual mods and turns _on_ consistency checks:

https://github.com/KSP-CKAN/CKAN/blob/dfd03d7051e56dede16d4212eaad38d6f652cc51/GUI/MainInstall.cs#L410-L417

Then when it does a consistency check, it discovers that Scatterer has unsatisfied dependencies, since they're virtual, and the `InconsistentKraken` makes it skip to the next recommendation:

https://github.com/KSP-CKAN/CKAN/blob/dfd03d7051e56dede16d4212eaad38d6f652cc51/GUI/MainInstall.cs#L423-L438

Scatterer's metadata isn't actually invalid, so it should be possible for another mod to recommend it.

Thanks to @sigma88 for reporting this via forum PM.

**Comment by Sigma88** [comment]
thanks @HebaruSan for opening this 👍

**Comment by HebaruSan** [comment]
New [script to query relationships](https://github.com/HebaruSan/KSP_Tools/blob/master/ckan_relationship_search) found one example of this in live data:

- ExtrasolarPlanetsBeyondKerbol-stock recommends Scatterer

Confirmed that installing that mod in GUI doesn't pull in Scatterer in the recommendation list.
