### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by frodoringbearer** [KSP-CKAN/CKAN#2275]
Background
----------

**CKAN Version:** 
1.24.0-PRE-1

**KSP Version:** 
1.2.2.1622

**Operating System:** 
Windows 10 Home

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, deleted it along with whole KSP folder

Problem
-------

**What steps did you take in CKAN?**
Launching the CKAN app, after a fresh install and CKAN fresh install crashed upon launch and gave an error. The reinstall was done because CKAN was being very slow and then failed to open at all.

Unhandled exception:
CKAN.NotKSPDirKraken: Could not find KSP version in buildID.txt or readme.txt
   at CKAN.KSP.CkanDir()
   at CKAN.Main..ctor(String[] cmdlineArgs, GUIUser user, Boolean showConsole)
   at CKAN.GUI.Main_(String[] args, Boolean showConsole)
   at CKAN.CmdLine.MainClass.Main(String[] args)

**Comment by HebaruSan** [comment]
Reinstall of what, CKAN or KSP?

**Comment by frodoringbearer** [comment]
Both.

**Comment by HebaruSan** [comment]
OK. CKAN is still looking for KSP where it was installed previously. If you can, try naming the new KSP directory the same as the old one.

**Comment by frodoringbearer** [comment]
How do I redirect it?

**Comment by frodoringbearer** [comment]
Without moving it back to my other drive?

**Comment by HebaruSan** [comment]
I think you could do that by opening a command prompt where your ckan.exe file is, then running `ckan ksp list` to see where it thinks the game should live, and then `ckan ksp forget <name>` with the name of the old install to remove the old path.

**Comment by frodoringbearer** [comment]
Oh ok thanks! By the way, are you a dev or something?

**Comment by HebaruSan** [comment]
Yes, I joined the CKAN dev team in October, I believe.

**Comment by frodoringbearer** [comment]
Oh nice! Thanks to you and the team then, it makes my 100ish mods way easier to manage...
By the way, I'm moving the install location to see if I can do anything that way.
