### ISSUE TITLE
Sugestion-Steam

### ISSUE THREAD

**Issue by CTH999** [KSP-CKAN/CKAN#2281]
I don't know if it can do steam (I'm waiting to know if this can before I consider getting it)

But if it can, close it.

However, if it can't, would it be feasible to make it work with steam?

It's just a suggestion though!

**Comment by HebaruSan** [comment]
There is currently code to deal specifically with Steam:

https://github.com/KSP-CKAN/CKAN/blob/bb028923969f731df7b2a66b592ad4c5e9f9baa0/Core/KSPPathUtils.cs#L12-L84

What actual features did you have in mind?

**Comment by CTH999** [comment]
It's able to put mods in steam, then never mind!

That's all I was asking, sorry!
