### ISSUE TITLE
It says Open instead of Ok in the Select KSP window of CKAN

### ISSUE THREAD

**Issue by OwenKSP** [KSP-CKAN/CKAN#2292]
Background
----------

**CKAN Version:**
1.22.6

**KSP Version:**
1.2.9.1727

**Operating System:**
Windows 10 pro

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
I downloaded it and Unzipped it.

**What did you expect to happen?**
To  find the normal Select KSP Window 

**What happened instead?**
It shows an Ok button instead and a 

 Hello, I like playing KSP, but without mods it will get boring at some point. So I downloaded CKAN, but it says Open instead of the Ok button you would get when you launch CKAN for the first time. Also, I have NET 4.5 installed and tried to reinstall CKAN aswell. 

**Screenshots:**
![capture](https://user-images.githubusercontent.com/36737485/36547500-df21c9a0-17a2-11e8-8ae6-d7ae822bd307.PNG)

**CKAN error codes (if applicable):**

**Comment by OwenKSP** [comment]
![capture](https://user-images.githubusercontent.com/36737485/36547500-df21c9a0-17a2-11e8-8ae6-d7ae822bd307.PNG)

**Comment by HebaruSan** [comment]
It needs to know where your KSP folder is located. Navigate to it and select the buildID.txt file it contains.
