### ISSUE TITLE
KrakenModule and Auto Updater connection?

### ISSUE THREAD

**Issue by spartankh** [KSP-CKAN/CKAN#2295]
Background
----------

**CKAN Version:** 
-Unsure of version when problem first occurred. Have tried the latest version and the Pre release version.

**KSP Version:** 
-Latest version. Has been completely deleted and reinstalled twice.

**Operating System:** 
-Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
-no

Problem
-------

**What steps did you take in CKAN?**
-Opened CKAN and received some sort of KrakenModule error. Could not figure the problem out and deleted CKAN and KSP and reinstalled both. Then received a different error upon opening CKAN.

**What did you expect to happen?**
-To not get an error...?

**What happened instead?**
-Something about KrakenModule? Sorry don't remember the first error. But after Reinstalling everything I now get an error about the auto updater not connecting.

**Screenshots:**

**CKAN error codes (if applicable):**
 -The request was aborted :Could not create SSL/TSL secure channel
(When first opening CKAN)
-Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established.
Repository successfully updated
(When clicked on the update repositories tab)
-Something about Krakenmodule when I first ran into a problem but after deleting and reinstalling I'm having the above errors.

**Comment by tshakah** [comment]
I'm getting the same issue - even after following the instructions here: https://github.com/KSP-CKAN/CKAN/issues/1864#issuecomment-240086117

**Comment by HebaruSan** [comment]
GitHub's having some kind of a conniption. The first report was #2293, please go there if you want to follow this issue.

**Comment by spartankh** [comment]
Ah I see, thanks for the update.
