### ISSUE TITLE
error in auto update

### ISSUE THREAD

**Issue by headshotninja21** [KSP-CKAN/CKAN#2296]
Background
----------

**CKAN Version:** 
v1.22.6

**KSP Version:** 
1.3.1.1891

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
nothing just opened it

**What did you expect to happen?**
it to open as normal

**What happened instead?**
two menus poped up

**Screenshots:**

![image](https://user-images.githubusercontent.com/36750741/36573576-4e005e4a-1807-11e8-9fbb-0e842305d4a4.png)
first this pops up (above) and after I dismiss it this will pop up (below)
![image](https://user-images.githubusercontent.com/36750741/36573619-6d1611d0-1807-11e8-9f4f-c2774ebec5c5.png)

**CKAN error codes (if applicable):**

**Comment by godisnumber7** [comment]
Check out issue #2293 .  It has a solution that appears to work.

**Comment by HebaruSan** [comment]
Yeah, this is the same as #2293. Please follow that discussion for updates.

**Comment by headshotninja21** [comment]
Oh ok thank you @HebaruSan @godisnumber7
