### ISSUE TITLE
exception error  CKAN.ModuleNotFoundKraken

### ISSUE THREAD

**Issue by junwooPark** [KSP-CKAN/CKAN#2299]
Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.3.1

**Operating System:** windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
just execute ckan.exe (as admin)

**Screenshots:**

![image](https://user-images.githubusercontent.com/10040797/36603122-2619a11a-18fd-11e8-940a-afac27decb26.png)

CKAN.ModuleNotFoundKraken: 'CKAN.ModuleNotFoundKraken' 형식의 예외가 Throw되었습니다.
   위치: CKAN.Registry.AllAvailable(String module)
   위치: CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
   위치: CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   위치: System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   위치: System.Windows.Forms.DataGridView.FlushSelectionChanged()
   위치: System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   위치: System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   위치: System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   위치: System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   위치: System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   위치: System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   위치: System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   위치: CKAN.Main._UpdateFilters()
   위치: CKAN.Main._UpdateModsList(Boolean repo_updated, List`1 mc)
   위치: CKAN.Main.CurrentInstanceUpdated()
   위치: CKAN.Main.OnLoad(EventArgs e)
   위치: System.Windows.Forms.Form.OnCreateControl()
   위치: System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   위치: System.Windows.Forms.Control.CreateControl()
   위치: System.Windows.Forms.Control.WmShowWindow(Message& m)
   위치: System.Windows.Forms.Control.WndProc(Message& m)
   위치: System.Windows.Forms.Form.WmShowWindow(Message& m)
   위치: System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** 로드된 어셈블리 **************
mscorlib
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
ckan
    어셈블리 버전: 1.24.0.0
    Win32 버전: 1.24.0
    코드베이스: file:///C:/Users/Uraki/Desktop/ckan.exe
----------------------------------------
System.Core
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Configuration
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System.Drawing
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Transactions
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll
----------------------------------------
System.Windows.Forms.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_ko_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
Microsoft.GeneratedCode
    어셈블리 버전: 1.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Numerics
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0 built by: NET471REL1
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
----------------------------------------
System.Runtime.Serialization
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2612.0 built by: NET471REL1LAST_B
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
----------------------------------------
System.Data
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    어셈블리 버전: 0.0.0.0
    Win32 버전: 4.7.2633.0 built by: NET471REL1LAST_C
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Microsoft.CSharp.resources
    어셈블리 버전: 4.0.0.0
    Win32 버전: 4.7.2556.0
    코드베이스: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp.resources/v4.0_4.0.0.0_ko_b03f5f7f11d50a3a/Microsoft.CSharp.resources.dll
----------------------------------------

**Comment by HebaruSan** [comment]
GitHub changed their servers in a way that broke CKAN, see #2293.
Upgrade to: https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0

**Comment by junwooPark** [comment]
okay i solved...

 i delete CKAN folder and execute again.
