### ISSUE TITLE
Error when opening CKAN.

### ISSUE THREAD

**Issue by HyronYT** [KSP-CKAN/CKAN#2302]
My CKAN showes me this issue wenn opening. (Also when opening Settings) : 

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
CKAN.ModuleNotFoundKraken: Eine Ausnahme vom Typ "CKAN.ModuleNotFoundKraken" wurde ausgelöst.
   bei CKAN.Registry.AllAvailable(String module)
   bei CKAN.MainAllModVersions.set_SelectedModule(GUIMod value)
   bei CKAN.Main.ModList_SelectedIndexChanged(Object sender, EventArgs e)
   bei System.Windows.Forms.DataGridView.OnSelectionChanged(EventArgs e)
   bei System.Windows.Forms.DataGridView.FlushSelectionChanged()
   bei System.Windows.Forms.DataGridView.ClearSelection(Int32 columnIndexException, Int32 rowIndexException, Boolean selectExceptionElement)
   bei System.Windows.Forms.DataGridView.SetAndSelectCurrentCellAddress(Int32 columnIndex, Int32 rowIndex, Boolean setAnchorCellAddress, Boolean validateCurrentCell, Boolean throughMouseClick, Boolean clearSelection, Boolean forceCurrentCellSelection)
   bei System.Windows.Forms.DataGridView.MakeFirstDisplayedCellCurrentCell(Boolean includeNewRow)
   bei System.Windows.Forms.DataGridView.OnRowCollectionChanged_PostNotification(Boolean recreateNewRow, Boolean allowSettingCurrentCell, CollectionChangeAction cca, DataGridViewRow dataGridViewRow, Int32 rowIndex)
   bei System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged_PostNotification(CollectionChangeAction cca, Int32 rowIndex, Int32 rowCount, DataGridViewRow dataGridViewRow, Boolean changeIsDeletion, Boolean changeIsInsertion, Boolean recreateNewRow, Point newCurrentCell)
   bei System.Windows.Forms.DataGridViewRowCollection.OnCollectionChanged(CollectionChangeEventArgs e, Int32 rowIndex, Int32 rowCount)
   bei System.Windows.Forms.DataGridViewRowCollection.AddRange(DataGridViewRow[] dataGridViewRows)
   bei CKAN.Main._UpdateFilters()
   bei CKAN.Main._UpdateModsList(Boolean repo_updated, List`1 mc)
   bei CKAN.Main.CurrentInstanceUpdated()
   bei CKAN.Main.OnLoad(EventArgs e)
   bei System.Windows.Forms.Form.OnCreateControl()
   bei System.Windows.Forms.Control.CreateControl(Boolean fIgnoreVisible)
   bei System.Windows.Forms.Control.CreateControl()
   bei System.Windows.Forms.Control.WmShowWindow(Message& m)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.Form.WmShowWindow(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
ckan
    Assembly-Version: 1.24.0.0.
    Win32-Version: 1.24.0.
    CodeBase: file:///C:/Users/dumit/Desktop/ckan.exe.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2633.0 built by: NET471REL1LAST_C.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2612.0 built by: NET471REL1LAST_B.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Transactions
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.2556.0 built by: NET471REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll.
----------------------------------------

Background
----------

**CKAN Version:** 
It says V0.0.0 but I have installed the latest one.

**KSP Version:** 
1.3.1

**Operating System:** 
Windows 10 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Nope.

Problem
-------

**What steps did you take in CKAN?**
Just opening it and going to settings.

**What did you expect to happen?**
Not showing me an error? Duh. 

**What happened instead?**
Showed me an error? What are these questions? xD

**Screenshots:**

Everything already above.

**CKAN error codes (if applicable):** 
See top.

**Comment by HebaruSan** [comment]
Run `ckan update` from the command line.
Since your version isn't clear, make sure you have [1.24](https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0).

**Comment by HyronYT** [comment]
Where can i open the command line?

**Comment by HebaruSan** [comment]
Start -> Run -> cmd

**Comment by HyronYT** [comment]
There is no ckan 
"ckan" is wrong written or does not exist.

**Comment by HebaruSan** [comment]
You have to "cd" to the folder where you saved ckan.exe.

**Comment by HyronYT** [comment]
So im now in Y:\SteamLibrary\steamapps\common\Kerbal Space Program\CKAN>
and then im typing ckan update
but still not working like before.

**Comment by HyronYT** [comment]
oh...

**Comment by HyronYT** [comment]
okay nice now everything is working! Thanks!
