### ISSUE TITLE
Failed to connect to repository. Exception: Value cannot be null. Parameter name: collection

### ISSUE THREAD

**Issue by tivec** [KSP-CKAN/CKAN#2304]
Background
----------

**CKAN Version:** 
1.24.0-PRE

**KSP Version:** 
KSP 1.3.1.1891

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

Problem
-------

**What steps did you take in CKAN?**
Start up and attempt to auto update.

**What did you expect to happen?**
Update master data should be downloaded.

**What happened instead?**
Failed to connect to repository. Exception: Value cannot be null. Parameter name: collection

**Screenshots:**
https://i.imgur.com/f48cnMV.png

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
See #2293.
Install https://github.com/KSP-CKAN/CKAN/releases/tag/1.24.0 which was released specifically to fix this.
