### ISSUE TITLE
Slow when choosing mods to install or uninstall

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2310]
Not the actual uninstall, but when deselecting the mods which I want to remove, sometimes I have to wait a minute or more before it actually deselcts

**Comment by HebaruSan** [comment]
I had it take a minute and twenty seconds to de-select GPPTextures just now (confession, I just counted to 80 rather than running a stopwatch), which presumably is close enough to what you're seeing.

I thought previous releases had the same problem, though, and I don't think we changed any of that code. I think the time is spent running the consistency checker to find mods with unsatisfied dependencies caused by the deselection.

**Comment by XaeroDT** [comment]
I've had the deselect issue in past versions. It's a weird occurence I see from time to time. No idea what causes it. For me restarting CKAN has always reverted it to "immediate" deselection.

**Comment by politas** [comment]
@linuxgurugamer, is it behaving like that consistently for you, or does restarting CKAN make it faster some times?

**Comment by martinmike2** [comment]
I can tell you that a new CKAN install on Windows 10 has this problem as well.  Takes on average 45 seconds to select a mod for install, depending on the recommends and suggests it has been known to lock up the application and force a task kill after 5 minutes of "Not Responding"

**Comment by linuxgurugamer** [comment]
@politas Just tried again.  Started ckan, selected one of my big installs, started deselecting installed mods.
Was very fast on some, and was dead slow (ie:  more than a minute) on others.

**Comment by linuxgurugamer** [comment]
If you want to create a test build with additional logging, I can repeat the test and send you the logs if that helps

**Comment by danshat** [comment]
This actually happens when installing too.

**Comment by Furcraft** [comment]
I am having this exact issue on Windows 10 as well. Certain mods are excruciatingly slow to select or deselect, some taking several minutes to finish processing. Restarts do not make any difference.

**Comment by ReiDaTecnologia** [comment]
I have the same problem but don't freeze for 1 minute and i using non-gaming notebook and the time is the same compared to my computer (Which is infinitely superior and gamer). I use a trick to speedup: De-Select/Select much as possible before freeze or Stop Responding after come back he made the actions (You can see him De-Select/Select one addon by him come back responding and stopping rapidly) 
_At least for me it works._

**Comment by HebaruSan** [comment]
Confirmation that this didn't start with v1.24.0, exact same symptoms described Oct 16, 2017:

- https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1240-bruce/&do=findComment&comment=3196950
