### ISSUE TITLE
Error opening CKAN

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#2312]
Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by Bit-Fiddler** [comment]
Error in autoupdate: 
	The request was aborted: Could not create SSL/TLS secure channel.


and then the window opens up but the mod list is blank.

**Comment by XaeroDT** [comment]
Manually update to 1.24.0 and it should work

**Comment by Bit-Fiddler** [comment]
ah ok...      I guess I missed that in a history somewhere?

**Comment by XaeroDT** [comment]
> Notes

    The auto-update function in previous releases will fail trying to upgrade to this version. You will need to download it manually and replace your previous copy.

**Comment by XaeroDT** [comment]
As for the TLS/SLL issue see [here.](https://github.com/KSP-CKAN/CKAN/pull/2297)

**Comment by Bit-Fiddler** [comment]
well the manual update did fix it.   thanks
