### ISSUE TITLE
CKAN fails to add a new instance of KSP to the managed list.

### ISSUE THREAD

**Issue by Poodmund** [KSP-CKAN/CKAN#2315]
Background
----------

**CKAN Version:** 1.24.0

**KSP Version:** 1.3.1.01891

**Operating System:** Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------

**What steps did you take in CKAN?** I tried to add a new instance of Kerbal Space Program to CKAN.

**What did you expect to happen?** It would appear in the list of Kerbal Space Program copies that CKAN is managing.

**What happened instead?** I got an exception error stating: "An entry with the same key already exists".

**Screenshots:** 

![image](https://user-images.githubusercontent.com/10106634/36642099-25778a3e-1a32-11e8-9be1-fc484b514447.png)

**CKAN error codes (if applicable):** https://pastebin.com/raw/yZUUMktH - Raw text of error log

**Additional Note:** This was tried against the Steam install, totally vanilla copy of KSP.

**Comment by HebaruSan** [comment]
That means it already has an instance with the same name in the list, and it gets the name from the game folder, so you could try renaming the game folder or the existing instance with the same name.

**Comment by Poodmund** [comment]
Maybe so, but it worked fine in the previous version of CKAN. To get round this issue I actually re-installed CKAN 1.24.0-PRE-1, added the instance to the list then installed CKAN 1.24.0 back again and it all seemed to recognize the instance fine.

So whatever was changed between the Pre-Release and Release version borked this up.

**Comment by HebaruSan** [comment]
Oh, definitely, I'm not saying it's not a bug, just suggesting a possible workaround.
