### ISSUE TITLE
what is going on?

### ISSUE THREAD

**Issue by creator1104** [KSP-CKAN/CKAN#2317]
Background
----------

**CKAN Version:** 
v1.22.6

**KSP Version:** 
1.3.1

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no other than installing infernal robotics remodel and rework.

Problem
-------
the thing throws a net work error, and when i do anything to refresh the list it throws 
another error.
**What steps did you take in CKAN?**
none

**What did you expect to happen?**
for it to go normaly

**What happened instead?**
the thing would only say an error and again it showed only what i installed

**Screenshots:**

![image](https://user-images.githubusercontent.com/31461885/36644625-31e19f8e-1a1a-11e8-8c71-f415fa0ceddc.png)

![image](https://user-images.githubusercontent.com/31461885/36644630-4d7a2540-1a1a-11e8-9d02-f2a4aaac27db.png)

![image](https://user-images.githubusercontent.com/31461885/36644632-55fa9e48-1a1a-11e8-95ac-88942d03c8dc.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
GitHub changed their servers in a way that broke CKAN, see #2293, #2294, #2295, KSP-CKAN/NetKAN#6279, #2296, KSP-CKAN/NetKAN#6280, KSP-CKAN/NetKAN#6281, KSP-CKAN/NetKAN#6282, #2299, KSP-CKAN/NetKAN#6284, #2304, #2309, KSP-CKAN/NetKAN#6289, and possibly others.

Install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0
