### ISSUE TITLE
Version requirements not obeyed for recommends

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2319]
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.3.1

**Operating System:** 
Windows, Linux

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Relevant Metadata:**

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/StockalikeSolarSystem.netkan

```
	"depends": [
		{ "name": "ModuleManager" },
		{ "name": "Kopernicus", "version": "2:release-1.3.1-3" },
		{ "name": "SigmaDimensions", "version": "0.9.6" },
...
	],
	"recommends": [
		{ "name": "SigmaBinary-core", "version": "1:v1.6.9" },
		{ "name": "SigmaSciDefRenamer" },
		{ "name": "Kronometer", "version": "v1.3.1-1" }
	],
```

Problem
-------

**What steps did you take in CKAN?**
1. Run GUI
2. Check StockalikeSolarSystem
3. Apply Changes

ConsoleUI works the same as GUI (i.e., wrong).

**What did you expect to happen?**
SigmaBinary-core 1:v1.6.9 should be presented as a recommendation.

The correct version is installed if you run `ckan install StockalikeSolarSystem` from the command line:

```
$ ckan install StockalikeSolarSystem
About to install...

 * Stockalike Solar System v0.5.5 (github.com, 11.3 MB)
 * Module Manager 3.0.4 (cached)
 * Kopernicus Planetary System Modifier 2:release-1.3.1-3 (cached)
 * ModularFlightIntegrator 1.2.4.0 (cached)
 * Sigma Dimensions 0.9.6 (github.com, 839.4 KB)
 * SASS-DRP 2.0 (cached)
 * SASS-NH 2.0.1 (cached)
 * SASS-OPM 1.2.4 (cached)
 * SASS-RevSS 0.6 (github.com, 162.5 MB)
 * SASS-RevJ 1 (cached)
 * SASS-Saru 0.1 (cached)
 * SASS-SE 1.0 (cached)
 * SASS-ER 1.2.4 (github.com, 1.1 MB)
 * SASS-StockalikeNeptune 1 (cached)
 * SASS-UL 0.5.4 (cached)
 * Sigma Binary 1:v1.6.9 (github.com, 752.5 KB)
 * Science Def Renamer v0.3.2 (github.com, 7.5 KB)
 * Kronometer v1.3.1-1 (cached)

Continue? [Y/n]  
```

**What happened instead?**
SigmaBinary-core 1:v1.6.11 is presented as a recommendation in GUI.

**Screenshots:**

![image](https://user-images.githubusercontent.com/12640834/36678928-4bf52bc2-1b12-11e8-8ab2-e453b107e1e9.png)

![image](https://user-images.githubusercontent.com/12640834/36679073-9f220590-1b12-11e8-8720-1b6e12bb9fb3.png)

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 15, 2018 11:43_

[here](https://github.com/Sigma88/CKAN/blob/master/Stockalike/StockalikeSolarSystem.netkan#L29) I specify I recommend a specific version of sigma binary

if I make a PR to KSP-CKAN/NetKAN with that .netkan file, [the output](https://ci.ksp-ckan.org/job/NetKAN/6866/console) shows this:

```
Recommends:
- SigmaBinary-core, version: v1.6.9
- SigmaSciDefRenamer
- Kronometer, version: v1.3.1-1
```

but, if I generate the .ckan file using netkan.exe and I load that .ckan file manually, the version I get is Sigma Binary v1.6.11 (which is the latest release, as opposed as the latest compatible one)

![image](https://user-images.githubusercontent.com/12640834/36255183-46cbce8e-124e-11e8-8706-51b11f70c187.png)

**Comment by HebaruSan** [comment]
Thanks! Of _course_ the relationship resolver has to make me a liar. :roll_eyes:
Are you finding that it works correctly for `depends`?

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 15, 2018 21:32_

@HebaruSan it `depends` 😂

everything works fine in my locally generated .ckan file but it fails if I use ckan.exe to install the mod normally (instead of doing install from .ckan)

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 15, 2018 21:47_

I think I found the issue, the version number for mods makes absolutely no sense to me 😂

apparently:
- **Kopernicus** is `2:release-1.3.1-3` instead of `release-1.3.1-3`
- **SigmaBinary** is `1:v1.6.9` instead of `v1.6.9`
- **SigmaDimensions** is `0.9.6` instead of `v0.9.6`
- **Kronometer** is `v1.3.1-1` which is what I use on github

I have no idea why those are used, but I'm guessing those will work

**Comment by HebaruSan** [comment]
Ahh yup, those `number:` prefixes are version "epochs". Sometimes a mod's "true" version numbers change in a non-increasing way, so CKAN has to tweak them to make them make sense, and that's the main way of doing it.

https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#epoch

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 15, 2018 22:44_

as soon as ckan updates and I can verify everything works fine I will close this

let's hope 🤞

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 16, 2018 8:53_

I give up.

I have no idea what's going on with CKAN, the version requirements seem to be completely ignored by the executable while jenkins seems to install everything correctly

executable:

![image](https://user-images.githubusercontent.com/12640834/36299733-c024d7de-12fe-11e8-94f7-d571ba300822.png)


jenkins console:

https://ci.ksp-ckan.org/job/NetKAN/6872/console

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 16, 2018 9:1_

so, even tho the preview is wrong, it looks like the requirements are installed correctly 

the "recommended" however are not installed correctly

```
About to install...

 * Science Def Renamer v0.3.2(cached)
 * ModularFlightIntegrator 1.2.4.0(cached)
 * SASS-DRP 2.0(cached)
 * SASS-NH 2.0.1(cached)
 * SASS-OPM 1.2.4(cached)
 * SASS-RevSS 0.6(cached)
 * SASS-RevJ 1(cached)
 * SASS-Saru 0.1(cached)
 * SASS-SE 1.0(cached)
 * SASS-ER 1.2.4(cached)
 * SASS-StockalikeNeptune 1(cached)
 * SASS-UL 0.5.4(cached)
 * Stockalike Solar System v0.5.5
 * Sigma Binary 1:v1.6.11
 * Kronometer v1.3.1-2
 * Kopernicus Planetary System Modifier 2:release-1.3.1-3
 * Sigma Dimensions 0.9.6

Downloading "https://github.com/Sigma88/Stockalike/releases/download/v0.5.5/StockalikeSolarSystem.v0.5.5.zip"
Downloading "https://github.com/Sigma88/Sigma-Binary/releases/download/v1.6.11/Sigma-Binary.v1.6.11.zip"
Downloading "https://github.com/StollD/Kronometer/releases/download/v1.3.1-2/Kronometer.v1.3.1-2.zip"
Downloading "https://github.com/Kopernicus/Kopernicus/releases/download/release-1.3.1-3/Kopernicus-1.3.1-3.zip"
Downloading "https://github.com/Sigma88/Sigma-Dimensions/releases/download/v0.9.6/Sigma-Dimensions.v0.9.6.zip"
```

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 20, 2018 17:31_

just to be sure, is anyone else seeing what I am seeing?

or is this just happening to me?

**Comment by HebaruSan** [comment]
Sorry, I forgot what this issue was. Would you mind updating the OP?

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 20, 2018 17:48_

the OP is exactly what this issue is.

even if I select a version in the "recommended" mods, CKAN ignores it

(I've updated the OP to explain a bit more in detail)

**Comment by HebaruSan** [comment]
_From @Sigma88 on February 26, 2018 14:28_

if you are having troubles reproducing this issue please let me know what more information I can provide / tests I can make to help solve the issue

**Comment by HebaruSan** [comment]
Going to try moving this from NetKAN to the CKAN issues list since I keep missing it and it's not something that can be fixed by changing metadata. First time trying https://github-issue-mover.appspot.com/, brace for impact...

**Comment by HebaruSan** [comment]
@Sigma88, I'm confused. [The output you linked to](https://ci.ksp-ckan.org/job/NetKAN/6872/console) shows the right version being installed, and it even shows a "^" indicating that SigmaBinary-core can be upgraded:

```
 * Sigma Binary 1:v1.6.9 (github.com, 752.5 KB)
...
Downloading "https://github.com/Sigma88/Sigma-Binary/releases/download/v1.6.9/Sigma-Binary.v1.6.9.zip"
...
^ SigmaBinary-core 1:v1.6.9
```

Where did the output in the OP come from?

**Comment by Sigma88** [comment]
@HebaruSan to test my netkan I submitted a "false pull request" to trigger jenkins 

you are right in saying that the output shows the correct version of SB being installed

however, when I try to install my mod via ckan.exe the latest version of SB is installed instead

**Comment by HebaruSan** [comment]
I'm not seeing that happen either:

```
$ ckan install StockalikeSolarSystem --ksp steam
About to install...

 * Stockalike Solar System v0.5.5 (github.com, 11.3 MB)
 * Module Manager 3.0.4 (cached)
 * Kopernicus Planetary System Modifier 2:release-1.3.1-3 (cached)
 * ModularFlightIntegrator 1.2.4.0 (cached)
 * Sigma Dimensions 0.9.6 (github.com, 839.4 KB)
 * SASS-DRP 2.0 (github.com, 18.2 MB)
 * SASS-NH 2.0.1 (github.com, 72.3 MB)
 * SASS-OPM 1.2.4 (cached)
 * SASS-RevSS 0.6 (github.com, 162.5 MB)
 * SASS-RevJ 1 (spacedock.info, 4.9 MB)
 * SASS-Saru 0.1 (github.com, 40.6 MB)
 * SASS-SE 1.0 (spacedock.info, 42.5 MB)
 * SASS-ER 1.2.4 (github.com, 1.1 MB)
 * SASS-StockalikeNeptune 1 (www.dropbox.com, 108.5 KB)
 * SASS-UL 0.5.4 (github.com, 75.2 MB)
 * Sigma Binary 1:v1.6.9 (github.com, 752.5 KB)
 * Science Def Renamer v0.3.2 (github.com, 7.5 KB)
 * Kronometer v1.3.1-1 (github.com, 21.8 KB)

Continue? [Y/n] 
```

Installing StockalikeSolarSystem with an up to date registry pulls in SigmaBinary-core 1:v1.6.9. Maybe your registry wasn't up to date?

**Comment by Sigma88** [comment]
I'm having problems using ckan.exe right now, I keep getting the error `"Could not establish trust relationship for the SSL/TLS"` (or something like that, I had to translate to english)

**Comment by Sigma88** [comment]
also, after installing SASS, I can click on the "Add Available Updates" button and update Kopernicus + SigmaDimensions to the latest versions (which are not supported by SASS, hence breaking the install)

**Comment by HebaruSan** [comment]
For the TLS error, GitHub changed their servers in a way that broke CKAN, see #2293 and others.
Install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

**Comment by Sigma88** [comment]
> For the TLS error, GitHub changed their servers in a way that broke CKAN, see #2293 and others.
Install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

yeah that's the version I'm using now

**Comment by HebaruSan** [comment]
You might also have to update to .Net 4.5 or Mono 5. The exact requirements aren't crystal clear at the moment.

**Comment by Sigma88** [comment]
I already have .Net 4.5

should I try Mono5?

**Comment by HebaruSan** [comment]
No. Try running `ckan version` though to make sure it's not running an old binary from somewhere else on disk.

**Comment by snkiz** [comment]
its mono 5 on Ubuntu

**Comment by Sigma88** [comment]
I usually run ckan.exe on Win10 by double clicking on it

if I use the cmd prompt to run `ckan.exe version > ckan.txt` this is what I get:

```
v1.24.0+195ed164d95f
```

**Comment by snkiz** [comment]
I'm just saying it required mono 5 to work on Ubuntu. so that's likely the case for you.

**Comment by Sigma88** [comment]
if I install SASS through the command prompt the required mods are installed correctly

**Comment by HebaruSan** [comment]
@snkiz , Windows uses .NET instead of Mono. You _can_ use Mono on Windows if you really want to, but .NET is the reference implementation of the platform, so there's no need to do that.

**Comment by Sigma88** [comment]
I've asked on discord some other people to try installing the mod using windows and the GUI

hopefully we should be able to see if this is just an issue with my laptop or a more general issue with the executable

**Comment by HebaruSan** [comment]
@Sigma88 thanks for the updated screenshots, I rewrote the OP and deleted some of the older comments to show the issue more clearly.

There's a reason why we have those subheadings in the issue template. :)

**Comment by HebaruSan** [comment]
Sorry, should have stated explicitly: I am able to reproduce this when I try it through GUI.
And I think I know where to start looking in the code...

**Comment by HebaruSan** [comment]
> also, after installing SASS, I can click on the "Add Available Updates" button and update Kopernicus + SigmaDimensions to the latest versions (which are not supported by SASS, hence breaking the install)

Could you please submit an issue for that? I want to make sure we don't lose track of it after we fix this issue with installing recommendations.

**Comment by Sigma88** [comment]
sure

**Comment by HebaruSan** [comment]
Style-wise this is issue hitting on one of the big unresolved architectural issues: Core doesn't handle optional dependencies. Instead each UI has to have its own implementation of the optional dependency logic; GUI and ConsoleUI both try to build lists themselves and prompt the user, whereas Cmdline treats them as all-or-nothing based on some simple flags, see #965. This is bad for maintenance as bugs have to be fixed 2-3 times and the logic can easily get inconsistent. It also means that the optional dependency logic doesn't benefit from some of `RelationshipResolver`'s more sophisticated capabilities, such as specification of versions, conflict checking, etc.

`IUser` ought to have some sort of `PromptForOptionalDependencies` virtual function, so the common logic can be moved to Core and integrated properly into the installer. Then each UI would just implement that new function; GUI and ConsoleUI could use their current UI, and Cmdline could have some sort of new multiselect text list picker.

**Comment by Sigma88** [comment]
also, I believe any information about past versions is not stored so for example:

SASS v0.5.5 might be compatible with KSP 1.3.1 by using Kopernicus v1.3.1-3 but as soon as I update SASS to KSP 1.4.0 any information about 1.3.1 will be lost

I guess this would require a pretty substantial change in how CKAN works, but it is definitely something that would greatly benefit CKAN in the long run. expecially now with 1.4.0 and the DLC coming
