### ISSUE TITLE
Cannot connect to repositories (CKAN ONLY ISSUE)

### ISSUE THREAD

**Issue by diveyez** [KSP-CKAN/CKAN#2320]
Background
----------

**CKAN Version:**  1.24.0

**KSP Version:** 1.3.1

**Operating System:**  Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
NO

Problem
-------

**What steps did you take in CKAN?**
Opened CKAN

**What did you expect to happen?**
Refresh as normal.

**What happened instead?**
Failed to connect to repository. You are gonna need to switch CKAN to the API for downloads.
![image](https://user-images.githubusercontent.com/29211141/36676494-d7288948-1ad9-11e8-9ea4-d2ca14f82945.png)

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
GitHub changed their servers in a way that broke CKAN, see KSP-CKAN/CKAN#2293, KSP-CKAN/CKAN#2294, KSP-CKAN/CKAN#2295, KSP-CKAN/NetKAN#6279, KSP-CKAN/CKAN#2296, KSP-CKAN/NetKAN#6280, KSP-CKAN/NetKAN#6281, KSP-CKAN/NetKAN#6282, KSP-CKAN/CKAN#2299, KSP-CKAN/NetKAN#6284, KSP-CKAN/CKAN#2304, KSP-CKAN/CKAN#2309, KSP-CKAN/NetKAN#6289, KSP-CKAN/CKAN#2317, KSP-CKAN/NetKAN#6295, and possibly others.

Install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

**Comment by WebAhmed** [comment]
@HebaruSan Thank you so much. I've been scrambling for a few days trying to understand wth was the problem.
