### ISSUE TITLE
 ckan : Depends: mono-runtime (>= 5.0) but 4.6.2.7+dfsg-1ubuntu1 is to be installed

### ISSUE THREAD

**Issue by snkiz** [KSP-CKAN/CKAN#2321]
Just an FYI this is the latest version in Debian Sid as well. Maybe a wiki entry to point users to the latest mono. http://www.mono-project.com/download/

**Comment by politas** [comment]
Yeah. We used to have that, but then we got all hopeful.

**Comment by Ruedii** [comment]
You really should stick to keeping it compatable with Mono 4.x for now, because that is what is installed on all major Linux distros.   Currently Ubuntu doesn't even look like it is updating to Mono 5.x for it's 2018 release.  

Seriously, we shouldn't be using Mono 5.0 specific routines. 

As a note, this also affects Mac.

Do you want me to make a list of routines not implemented in the 4.x series that CKAN uses?

**Comment by Ruedii** [comment]
I was thinking, the primary routine of concern is one that doesn't even need to be run on Mono.

It is one to make it not require .Net 4.6 (and in a cruel twist of fate makes it require Mono 5.0)

Shouldn't we just ask Windows users to upgrade to .Net 4.6 anyways.  All users that can run .Net 4.5 (Those using Vesta SP2 or a newer version of Windows) can install .Net 4.6.

**Comment by politas** [comment]
@Ruedii, that sounds very helpful. We were rather under the hammer to get a working version out when GitHub went all TLS 1.2 on us. If we can get back to working under Mono 4.x, that would be ideal.

**Comment by ketsa** [comment]
Just encountered this problem and I'm on Debian Buster. no solutions ?

Dependency is not satisfiable : mono-runtime (>= 5.0)

**Comment by gallowglass** [comment]
Follow the directions here to upgrade your mono:  https://www.mono-project.com/download/stable/

Then 
`sudo apt upgrade
sudo dpkg -i ckan_1.25.4_all.deb
sudo apt --fix-broken install`

That got things working for me this evening on Pop!_OS 18.04 LTS.

**Comment by D33pfield** [comment]
Is there a solution to this? I am having the same issues on Ubuntu 18.04.4 LTS

**Comment by D33pfield** [comment]
> Follow the directions here to upgrade your mono: https://www.mono-project.com/download/stable/
> 
> Then
> `sudo apt upgrade`
> `sudo dpkg -i ckan_1.25.4_all.deb`
> `sudo apt --fix-broken install`
> 
> That got things working for me this evening on Pop!_OS 18.04 LTS.

This just installs the package and then uninstalls it for me

**Comment by techman83** [comment]
@gallowglass 's solution works for me on Linux Mint 19.3 (Ubuntu 18.04). It required an extra dependency I didn't have.

```bash
➜  Downloads sudo dpkg -i ckan_1.27.0_all.deb 
[sudo] password for leon:                      
Selecting previously unselected package ckan.
(Reading database ... 1373401 files and directories currently installed.)
Preparing to unpack ckan_1.27.0_all.deb ...
Unpacking ckan (1.27.0) ...
dpkg: dependency problems prevent configuration of ckan:
 ckan depends on liblog4net1.2-cil; however:
  Package liblog4net1.2-cil is not installed.

dpkg: error processing package ckan (--install):
 dependency problems - leaving unconfigured
Processing triggers for desktop-file-utils (0.23+linuxmint6) ...
Processing triggers for gnome-menus (3.13.3-11ubuntu1.1) ...
Processing triggers for mime-support (3.60ubuntu1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...
Errors were encountered while processing:
 ckan
➜  Downloads sudo apt-get install --fix-broken
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Correcting dependencies... Done
The following additional packages will be installed:
  liblog4net1.2-cil
The following NEW packages will be installed:
  liblog4net1.2-cil
0 to upgrade, 1 to newly install, 0 to remove and 22 not to upgrade.
1 not fully installed or removed.
Need to get 81.8 kB of archives.
After this operation, 279 kB of additional disk space will be used.
Do you want to continue? [Y/n] y
Get:1 http://mirror.tcc.wa.edu.au/ubuntu bionic/universe amd64 liblog4net1.2-cil all 1.2.10+dfsg-7 [81.8 kB]
Fetched 81.8 kB in 1s (110 kB/s)                     
Selecting previously unselected package liblog4net1.2-cil.
(Reading database ... 1373411 files and directories currently installed.)
Preparing to unpack .../liblog4net1.2-cil_1.2.10+dfsg-7_all.deb ...
Unpacking liblog4net1.2-cil (1.2.10+dfsg-7) ...
Setting up liblog4net1.2-cil (1.2.10+dfsg-7) ...
* Installing 1 assembly from liblog4net1.2-cil into Mono
Setting up ckan (1.27.0) ...
➜  Downloads ckan
10196 [1] ERROR CKAN.ErrorDialog (null) - Directory /tmp/ckan is not a valid KSP directory.
Setting up CKAN for the first time...
```

Mono installation
```bash
➜  Downloads mono -V
Mono JIT compiler version 6.8.0.105 (tarball Tue Feb  4 21:20:20 UTC 2020)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by HebaruSan** [comment]
Mono is up to 6.8 by now. Installing 5.0 shouldn't be a burden.
