### ISSUE TITLE
ckan 1.24 macOS 'CKAN.app' just launches the ckan github site

### ISSUE THREAD

**Issue by whiteknight4981** [KSP-CKAN/CKAN#2327]
no error logs since the ckan doesnt even try to launch

macOS 10.13.3
mono 5.10

Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Yup, we're working on that in #2307. Can you please try this test build and let us know if it works?

- [CKAN.zip](https://github.com/KSP-CKAN/CKAN/files/1756778/CKAN.zip)
