### ISSUE TITLE
How to actually use this now?

### ISSUE THREAD

**Issue by StalkerM8** [KSP-CKAN/CKAN#2328]
Not so much a technical issue as this not the download I expected, I dunno where I found JUST the .exe file and now I cant find it and instead downloaded all this misc. looking files or something, someone explain where to find the regular .exe

**Comment by HebaruSan** [comment]
Try the ckan.exe link here:
https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

**Comment by StalkerM8** [comment]
Right so where in the hell is download button?

**Comment by HebaruSan** [comment]
Right here:

![image](https://user-images.githubusercontent.com/1559108/36711565-a61e94a8-1b49-11e8-9d44-dae1c60b89de.png)

**Comment by StalkerM8** [comment]
Never used github, also never ever got it from github to begin with ¯\_(ツ)_/¯

**Comment by politas** [comment]
Github is the only place the CKAN client has ever been published, so if you didn't get it here, I don't know where you got it, either. @HebaruSan has given you a link to the page and an image of the object you need to click on on that page. I'm not sure how we can help you any more than that. I mean, if you want to pay my airfares and any necessary visas, I'll fly to your house and click on it for you, I suppose.

**Comment by StalkerM8** [comment]
No one gave a link, I literally just googled it a long while back got the simple .exe using that, Never once knew anything about this github until yesterday. and no I'm more than capable of clicking considering i made it to github itself
