### ISSUE TITLE
CKAN Fails to open if AutoUpdates are enabled

### ISSUE THREAD

**Issue by hetzlefetz** [KSP-CKAN/CKAN#2331]
Background
----------

**CKAN Version:** 
Current Trunk

**KSP Version:** 
Irrelvant

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes , but irrelvand

Problem
-------

**What steps did you take in CKAN?**
Tried to Open CKAN with AutoUpdates enabled

**What did you expect to happen?**
CKAN Opens

**What happened instead?**
CKAN Begins to crash after SSL / TLS Encryption Failed

**CKAN error codes (if applicable):** 
System.Net.WebException occurred
  HResult=0x80131509
  Message=The request was aborted: Could not create SSL/TLS secure channel.
  Source=System
  StackTrace:
   at System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   at System.Net.WebClient.DownloadString(Uri address)
   at CKAN.AutoUpdate.MakeRequest(Uri url) in C:\Users\knechtrootrecht\Desktop\CKAN-master\CKAN-master\Core\Net\AutoUpdate.cs:line 210

The Solutionseems to be to enable TLS1.2 before making the first call like already done elsewhere in CKAN like this:

ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;

I am working on a patch other than to just put the line above in AutoUpdate.cs but I thought this might be related to #2307  and / or #2278 and this info may be useful

**Comment by HebaruSan** [comment]
Hmm, the existing Tls12 statement _would_ happen before `AutoUpdate.cs` runs. It's in the main entry point of ckan.exe. And I think we have plenty of people running with autoupdate enabled, since it's the default, so we should have heard more about this by now.

Are you sure you're not running a copy of 1.22.6 somehow?

**Comment by HebaruSan** [comment]
Actually, if you're working on a patch, there's a good chance you don't have the Tls12 statement, depending on when you started your branch and when you last rebased. That looks like the most likely cause at this point.

**Comment by hetzlefetz** [comment]
I just build the master branch from my visual studio which resulted in the described fault
Interestingly I  tried yesterday using the MacCandless pre-release which didn't work but  
I just saw the Bruce release which seems to work fine (didn't throw the error)

**Comment by HebaruSan** [comment]
Try a `git pull`. Sounds like you have an old copy of master.

**Comment by hetzlefetz** [comment]
I just checked out a fresh copy using : https://github.com/KSP-CKAN/CKAN.git  (git pull also says I am up to date) and it still fails at  the ssl connection

**Comment by hetzlefetz** [comment]
FYI The service point manager is configured correctly for the rest of the requests, but the first request is made before the ServicePointManager has been setup

**Comment by HebaruSan** [comment]
Well as long as it's not happening in v1.24.0 (Bruce), it's going to be something local to your machine. None of the commits since that release have gone anywhere near this code.

I do notice that the line number in your error is off by one, which makes it look like you have an extra line inserted. That might be a factor. 210 is one line after the after the `DownloadString` call:

https://github.com/KSP-CKAN/CKAN/blob/86bf144ec7ce7fa36b1aaddaadfff2519481fc52/Core/Net/AutoUpdate.cs#L207-L211

**Comment by hetzlefetz** [comment]
Yes, sorry I just commented out the line I used to "work around" the Issue

```
  try
            {
                ServicePointManager.SecurityProtocol |= SecurityProtocolType.Tls12;
                var result = web.DownloadString(url);
                return JsonConvert.DeserializeObject(result);
            }
```

**Comment by HebaruSan** [comment]
OK, one more idea. Are you somehow running the CKAN-GUI.csproj project directly from Visual Studio? CKAN has kind of a crazy project structure. There are several projects that each compile to their own DLL or EXE, and the build process combines them together after the fact, with the main entry point being in CKAN-cmdline.csproj. Running CKAN-GUI.exe directly would bypass that main entry point.

**Comment by hetzlefetz** [comment]
... Yes this was what I did, I should have really familiarize myself with the project's structure. 
Running CKAN-cmdline.csproj instead it works just as expected 
Its just weird i got the ssl error from an old release ... 
Sorry for the long wait, I just did a VS update for completely  unrelated reasons.

**Comment by HebaruSan** [comment]
Cool! Looking forward to seeing your patch!
