### ISSUE TITLE
Ckan doesnt work

### ISSUE THREAD

**Issue by GidReess** [KSP-CKAN/CKAN#2335]
Background
----------

**CKAN Version:** 
v1.22.6

**KSP Version:** 
1.3.1891

**Operating System:** 
win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Before installed ckan

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**
This error

**Screenshots:**

**CKAN error codes (if applicable):** 

Connection to https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz could not be established

**Comment by HebaruSan** [comment]
See #2293, install https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0
