### ISSUE TITLE
Right-click - reinstall doesn't show progress

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2343]
Background
----------

**CKAN Version:** 
v1.24.0

**Operating System**
Ubuntu Mate 16.04 LTS
Mono JIT compiler version 5.8.0.127

Problem
-------

**What steps did you take in CKAN?**
Right-click an installed mod and select "Reinstall

**What did you expect to happen?**
Reinstallation to happen with UI switching to the progress tab and the cursor changing to the "working" cursor while the GUI is unavailable.

**What happened instead?**
Reinstallation happened with only status bar at the bottom indicating anything was happening

**Comment by HebaruSan** [comment]
I get the expected behavior on Windows (switches to progress screen during reinstall).
Will try on Linux later...

**Comment by HebaruSan** [comment]
... I also see the progress screen on Linux. We might have to try adding some `log.InfoFormat` calls to see if something is getting skipped on your system. Maybe some exceptions are being thrown and ignored.
