### ISSUE TITLE
CKAN Crash on startup

### ISSUE THREAD

**Issue by na9oooooooor** [KSP-CKAN/CKAN#2345]
Background
----------

**CKAN Version:**
 v1.24.0

**KSP Version:**
1.3.1.1981

**Operating System:**
Win 10-64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------

I had CKAN  for few weeks, it used to work probably, until a few days ago.

The problem: it crashes on startup "I took a screenshot in the attachments".
I tried to download the older version and I tried to uninstall the game folder and reinstall it several times "clean installation" I cant find out what causing this problem, I also deleted only the CKAN folder...etc. 

**Screenshots:**

![untitled](https://user-images.githubusercontent.com/37078977/36986555-29a94e38-20ab-11e8-9438-331080592af8.png)

**Comment by HebaruSan** [comment]
Here are the instructions for doing a clean reinstall:

- https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

Any idea what changed a few days ago?

**Comment by na9oooooooor** [comment]
Hello again…

I think there was java update. I’m not expert.

On Mar 5, 2018, at 9:36 PM, HebaruSan <notifications@github.com<mailto:notifications@github.com>> wrote:


Here are the instructions for doing a clean reinstall:

  *   https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

Any idea what changed a few days ago?

**Comment by politas** [comment]
Let us know if the clean reinstall process doesn't work for you.

**Comment by na9oooooooor** [comment]
Same :(
Also I wiped off the whole game folder and mods and re downloaded ckan....Same

Sent from my iPhone

On Mar 6, 2018, at 23:19, Myk <notifications@github.com<mailto:notifications@github.com>> wrote:


Let us know if the clean reinstall process doesn't work for you.

**Comment by HebaruSan** [comment]
What version of .NET do you have?

**Comment by na9oooooooor** [comment]
I have .Net Framework 4.7
[cid:D72FE1A6-6F14-4DB4-A952-D48B2FFBEDB9@Belkin]

On Mar 7, 2018, at 1:36 AM, HebaruSan <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of .NET do you have?

**Comment by na9oooooooor** [comment]
The Issue is Officially fixed by updating my .Net from 4.7 to 4.7.1 now it worked, no crash.

Thanks a lot for the help :))

On Mar 7, 2018, at 1:36 AM, HebaruSan <notifications@github.com<mailto:notifications@github.com>> wrote:


What version of .NET do you have?

**Comment by HebaruSan** [comment]
Excellent, glad you figured it out!
