### ISSUE TITLE
Linux - Can update repository, but can't install mods

### ISSUE THREAD

**Issue by laptopdude90** [KSP-CKAN/CKAN#2357]
Background
----------

**CKAN Version:** v1.24.0-PRE

**KSP Version:** 1.4.0.2077

**Operating System:** Linux Mint 18.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------

**What steps did you take in CKAN?** Updated repository (Succeeded) and then tried to install environmental visual enhancements

**What did you expect to happen?** EVE would download and install

**What happened instead?** I received an error when it tried to download the mod. The mod did not install.

**Screenshots:**
[1](
https://img.scd31.com/up/15208708118212c8a.png)

[2](https://img.scd31.com/up/1520870822b0a6dc4.png)

**CKAN error codes (if applicable):** 

 `24095 [1] ERROR CKAN.ErrorDialog (null) - Failed to download "https://github.com/WazWaz/EnvironmentalVisualEnhancements/releases/download/EVE-1.4.0-1/EnvironmentalVisualEnhancements-1.4.0.1.zip" - error: Error: SendFailure (Error writing headers)`

**Comment by HebaruSan** [comment]
Please fill in the issue template.

**Comment by laptopdude90** [comment]
Sorry, updated!

**Comment by HebaruSan** [comment]
Thanks! GitHub broke the PRE version and all earlier versions, see #2293.
Install this:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

You may get an error at startup, click Continue then Refresh.
