### ISSUE TITLE
CKAN.URLHandlers error every time when opening CKAN on Windows

### ISSUE THREAD

**Issue by francoiswnel** [KSP-CKAN/CKAN#2362]
I've received the following error every time while opening any version of CKAN I've tried on Windows 10 64-bit. It doesn't seem to affect any of the functions of the tool, but I thought I'd share it anyway, since searching for the problem does not yield a solution.

```
8468 [1] ERROR CKAN.URLHandlers (null) - There was an error while registering the URL handler for ckan:// - Cannot delete a subkey tree because the subkey does not exist.
8485 [1] ERROR CKAN.URLHandlers (null) -    at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at CKAN.URLHandlers.RegisterURLHandler_Win32()
   at CKAN.URLHandlers.RegisterURLHandler(Configuration config, IUser user)
```

**Comment by HebaruSan** [comment]
Thanks for the report.

That's very strange, as the `DeleteSubKeyTree` line only runs if the subkey is found:

https://github.com/KSP-CKAN/CKAN/blob/9ee358455b338c1164d8605dfd19559ee661919d/GUI/URLHandlers.cs#L85-L107

Could you please check these paths in `regedit` and screenshot them for us? (They might not both exist.) Hopefully that would give us enough information to start investigating:

```
HKEY_LOCAL_MACHINE\Software\Classes\ckan
HKEY_CURRENT_USER\Software\Classes\ckan
```

**Comment by francoiswnel** [comment]
Very strange indeed.

There are no entries for CKAN under current user, but I've attached a screenshot of the entries under local machine. Let me know if you need anything else.

![screenshot](https://user-images.githubusercontent.com/7825549/37485348-d2a56950-2893-11e8-9c1b-1e7685f08c16.png)

**Comment by HebaruSan** [comment]
Thanks!

Can you please try this test build? I reworked that function a bit to try to re-use the originally successful return value of the Open call to also do the deletion. Hopefully this will at least give us an exception that's different in an informative way.

- [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/1816870/ckan.zip)

**Comment by francoiswnel** [comment]
Sure. The test build prompts me to add a handler upon launch. The console window then prompts for the rights to make changes, and throws the same error. I ran it twice to check if it was setting the handler, same result the second time.

```
12186 [1] ERROR CKAN.URLHandlers (null) - There was an error while registering the URL handler for ckan:// - Cannot write to the registry key.
12200 [1] ERROR CKAN.URLHandlers (null) -    at System.ThrowHelper.ThrowUnauthorizedAccessException(ExceptionResource resource)
   at Microsoft.Win32.RegistryKey.EnsureWriteable()
   at Microsoft.Win32.RegistryKey.DeleteSubKeyTree(String subkey, Boolean throwOnMissingSubKey)
   at CKAN.URLHandlers.RegisterURLHandler_Win32()
   at CKAN.URLHandlers.RegisterURLHandler(Configuration config, IUser user)
```

**Comment by HebaruSan** [comment]
Thanks! Not to nitpick, but that's not quite the same error. It switched from:

> Cannot delete a subkey tree because the subkey does not exist.

to:

> Cannot write to the registry key.

So I think your user can't modify HKEY_LOCAL_MACHINE for whatever reason. If you're comfortable making changes in regedit, could you please try deleting HKEY_LOCAL_MACHINE\Software\Classes\ckan manually? Then we can check whether CKAN recreates it in the same place or not.

**Comment by francoiswnel** [comment]
Yeah, you're right. Sorry, I was doing something else and didn't even read the error the second time, just copied it. I've deleted the registry entry and got a new error:

```
10769 [1] ERROR CKAN.URLHandlers (null) - There was an error while registering the URL handler for ckan:// - Access to the registry key 'HKEY_CLASSES_ROOT\ckan' is denied.
10783 [1] ERROR CKAN.URLHandlers (null) -    at Microsoft.Win32.RegistryKey.Win32Error(Int32 errorCode, String str)
   at Microsoft.Win32.RegistryKey.CreateSubKeyInternal(String subkey, RegistryKeyPermissionCheck permissionCheck, Object registrySecurityObj, RegistryOptions registryOptions)
   at Microsoft.Win32.RegistryKey.CreateSubKey(String subkey)
   at CKAN.URLHandlers.RegisterURLHandler_Win32()
   at CKAN.URLHandlers.RegisterURLHandler(Configuration config, IUser user)
```

**Comment by HebaruSan** [comment]
Did you get the "CKAN requires permission to add a handler for ckan:// URLs." dialog that time? That would tell us whether CKAN is attempting to elevate permissions in order to set the key.

**Comment by francoiswnel** [comment]
Yes, I did get a permissions prompt. I just ran the test build again and received no prompt to register the handler (and thus no error message in the console). There are no CKAN entries under either current user or local machine classes.

**Comment by HebaruSan** [comment]
OK, I was being a bit dense there. The main (unelevated) process catches the unauthorized access exception, handles it fully (user prompt, retry with elevated permissions, etc.), _and then re-throws it for no reason_:

https://github.com/KSP-CKAN/CKAN/blob/9ee358455b338c1164d8605dfd19559ee661919d/GUI/URLHandlers.cs#L51-L67

... which means that the error you're seeing now will be printed every time CKAN tries to register its URL handler as a normal user, regardless of whether it's ultimately successful. It's a red herring.

Here's a new test build with that re-throw statement removed:

- [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/1817112/ckan.zip)

If that looks better, we can try making this change in the main code.
