### ISSUE TITLE
[Question] How CKAN know if a mod updated to a new version?

### ISSUE THREAD

**Issue by ReiDaTecnologia** [KSP-CKAN/CKAN#2367]
_This is not a issue and yes a question i have so i think don't need the issue layout when open a new issue (I think, if i wrong tell me and i fix it)_

I have two versions of KSP because of mods availability and language support:
1.3.1 - Most mods don't update, so this is my "Default Playing Version".
1.4.0 - Brazilian language added and for user-friendly i want use it.
I have in both a .ckan modpack made by myself and i am waiting for the mods get updated, for this i watch the github of all the mods and get email notifications of his repositories.
I know [KW Rocketry get updated](https://github.com/linuxgurugamer/KWRocketryRedux/releases) to 1.4.0 but this is not showing in the CKAN and this is weird.
I want know how CKAN know if a mod updated? because KW Rocketry get updated but he don't added this update in the you database.

**Comment by HebaruSan** [comment]
Try KWRocketryRebalanced instead of KWRocketryRedux. Rebalanced is still updating, Redux is not.
(This is pretty confusing because the repository is named Redux but the download files are named Rebalanced.)
