### ISSUE TITLE
[Request] Install Missions

### ISSUE THREAD

**Issue by Olympic1** [KSP-CKAN/CKAN#2370]
The new DLC introduced the Mission Builder. This allows players to create missions and share them with the community.

When you created a mission, KSP exports it as a zip file to `KSP_ROOT/Missions/_Exports`. This zip can be shared with the community. When downloaded you have to place the zip in `KSP_ROOT/Missions`. When you select **Play Missions** in KSP, it moves all the zip files to `KSP_ROOT/Missions/_Imported` and extracts the contents to `KSP_ROOT/Missions`.

Now I tested this a bit and this can also be used by CKAN. We can just go directly to the last step and extract the contents of the missions zip file to `KSP_ROOT/Missions`.

**What to do to make this work:**
- [x] Allow CKAN to install to the `Missions` folder
- [x] Add `Missions` folder to spec
- [x] Add `Missions` folder to the schema

**Comment by yalov** [comment]
Neither Steam Workshop nor KerbalX give a link to a mission for adding it to the CKAN.
Is another repo (github) the only option?
 
And KerbalX doesn't allow update a mission, only delete an old one and create an updated one, so no autoupdating link in the CKAN
@Sujimichi
