### ISSUE TITLE
An error when open CKAN Setting 

### ISSUE THREAD

**Issue by Johan501** [KSP-CKAN/CKAN#2372]
Hi!

First, sorry for my bad English and sorry if I make mistakes. This is the first time I make an Issue.

**CKAN Version:** 
Version 1.24.0 (the latest_)

**KSP Version:** 
1.4.1 (the latest

**Operating System:** 
Windows 10 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No not yet.

Problem:
Every time when I click on settings in CKAN there is an Error and I don't know what the problem is. Settings does open, but the error is before that. In setting, there a some missing thing. I don't know how to explain it in English, I am sorry. I have copy/paste the info about this error, with there is Dutch text and It is a little to difficult for me to translate it.

It something goes wrong the uploaded stuff, I will tried it a diffrent way.

**What steps did you take in CKAN?**
Redownload CKAN, problem is still there.

**What did you expect to happen?**
No error? Open CKAN settings without any error.

**What happened instead?**
Error, but settings does open.

**Screenshots:**
![ckan](https://user-images.githubusercontent.com/24547634/37567455-8161fb86-2ac7-11e8-9939-562831a066ba.png)

![ckan 2](https://user-images.githubusercontent.com/24547634/37567457-84fb44aa-2ac7-11e8-9d88-80fc37fdaa4f.png)

[CKAN.txt](https://github.com/KSP-CKAN/CKAN/files/1822802/CKAN.txt)

**Comment by DasSkelett** [comment]
I take the liberty to copy an answer of @HebaruSan:
Duplicate of #2300, fixed in #2301. As a workaround, click Continue and then add an auth token.

**Comment by politas** [comment]
Let us know if that doesn't fix it.

**Comment by Johan501** [comment]
The problem is solved, thanks!
In CKAN settings I added a new auth. Token with abcd efgh and now no errors en no missing text, etc.

Thanks! =D

**Comment by politas** [comment]
You can do it yourself if you'd like, or a CKAN team member can do it.

**Comment by Johan501** [comment]
Okay, I will do it now.
Have a nice day! :)
