### ISSUE TITLE
[Feature Request] Use MonoCurses for ConsoleUI

### ISSUE THREAD

**Issue by Ruedii** [KSP-CKAN/CKAN#2375]
The current console UI is a little sloppy, as is any UI using interfaces.

Using MonoCurses to run it would give a much better interface.  It would also give console mouse support on platforms that support it.  (I know Linux and Mac do, but I don't know if Windows still supports it.  They did in XP and earlier, but it may have been removed.)

**Comment by HebaruSan** [comment]
Sloppy how? What's the problematic use case?

**Comment by Ruedii** [comment]
To put it simply it can't take advantage of the various platform specific commands.  

Also, having to implement your own Console UI toolkit kind of results in reinventing the wheel.

**Comment by Ruedii** [comment]
Another option is console framework:
https://github.com/elw00d/consoleframework

**Comment by HebaruSan** [comment]
OK, so there are no actual bugs or problems that you have to report. Thanks.

If someone wants to put in the time and effort to rewrite all of that code, then we would evaluate the pros and cons at that point. But it does not make sense to leave this out there as a "to do" item when there's no upside to doing it. Closing.

**Comment by HebaruSan** [comment]
(Also, MonoCurses is _ugly_.)
