### ISSUE TITLE
.Deb Pkg - Ubuntu One: Validate your email address

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2379]
From: 
Hello

We received a request from KSP-CKAN using email address politas.ksp.ckan@gmail.com, trying to validate the email address debian.oqopxy@zapiermail.com for use in Ubuntu One.

If you made this request, click the following link to automatically confirm your email address:

https://login.ubuntu.com/token/mytxqhKddWbxGZRcZMgw/+newemail/debian.oqopxy@zapiermail.com

Thank you,

The Ubuntu One team
https://login.ubuntu.com

If you don't know what this is about, then someone has probably entered your email address by mistake. Sorry about that.
If you wish to report this email being incorrectly used, please click the following link:

https://login.ubuntu.com/invalidate-email/3YpnJ7kRZDTFBbMCyt7b/debian.oqopxy@zapiermail.com

You can also seek further assistance on:

https://forms.canonical.com/sso-support/

**Comment by HebaruSan** [comment]
Well that looks suspicious.

**Comment by politas** [comment]
It's fine, I caused it to happen.
