### ISSUE TITLE
Failed to connect to repository. Exception: Der Wert darf nicht NULL sein. Parametername: collection

### ISSUE THREAD

**Issue by DarioTech** [KSP-CKAN/CKAN#2380]
Background
----------

**CKAN Version:** 1.24.0-Pre

**KSP Version:** 1.4.1.2089

**Operating System:** Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** i pasted mods in 

Problem
-------

**What steps did you take in CKAN?**
Start up

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
The -PRE version no longer works due to changes on GitHub, see #2293. Install this:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

If you see an error on startup of that version, click Continue, then Refresh.
