### ISSUE TITLE
Failed to download "https://github.com/Sujimichi/KerbalX/releases/download/0.4.2/PartMapper.zip" - error: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden..

### ISSUE THREAD

**Issue by DarioTech** [KSP-CKAN/CKAN#2381]
Background
----------

**CKAN Version:** 1.24.9-Pre

**KSP Version:** 1.4.1.2089

**Operating System:** Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** I pasted mods into it

Problem
-------

**What steps did you take in CKAN?**I clicked on a mod(KerbalX Part Mapper but it occurs  also on other mods) and clicked on Apply changes

**What did you expect to happen?**Donwload the Mod

**What happened instead?**There was this error:Failed to download "https://github.com/Sujimichi/KerbalX/releases/download/0.4.2/PartMapper.zip" - error: Die Anfrage wurde abgebrochen: Es konnte kein geschützter SSL/TLS-Kanal erstellt werden.. And the green bar said to me Please wait

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
The -PRE version no longer works due to changes on GitHub, see #2293. Install this:

- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.24.0

If you see an error on startup of that version, click Continue, then Refresh.
