### ISSUE TITLE
Critical error - CKAN is showing and installing the wrong mod versions

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2390]
Specifically, if a .version file for a mod is only listing a specific KSP version, ie: 1.4.1, and I start CKAN on a 1.3.1 version game, it is showing me that mod as being available for the game

This is a critical error and is part of why people don't trust CKAN.

This happens to be on a Windows 10 system

I'm in the middle of adopting KSP-AVC, and can help you with the logic, if you need help.

**Comment by HebaruSan** [comment]
Need an example.

**Comment by linuxgurugamer** [comment]
AnyResContinued

**Comment by linuxgurugamer** [comment]
Local .version file:
{
  "NAME": "AnyRes",
  "URL": "https://raw.githubusercontent.com/linuxgurugamer/AnyRes/master/AnyRes.version",
  "DOWNLOAD": "https://github.com/linuxgurugamer/AnyRes/releases",
  "VERSION": {
    "MAJOR": 2,
    "MINOR": 0,
    "PATCH": 1,
    "BUILD": 0
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 3,
    "PATCH": 1
  }
}

**Comment by linuxgurugamer** [comment]
Closing issue, was a bad file. 
sorry

**Comment by linuxgurugamer** [comment]
Ok. got it to happen again:
CKAN 1.23.0
KSP 1.3.1
Mod:  Custom Barn Kit
It installed 1.1.17.0, even though the ranges were from 1.4.0 to 1.4.1
```
{
    "NAME": "CustomBarnKit",
    "URL": "https://ksp.sarbian.com/jenkins/job/CustomBarnKit/lastSuccessfulBuild/artifact/CustomBarnKit/CustomBarnKit.version",
    "DOWNLOAD": "http://forum.kerbalspaceprogram.com/index.php?/topic/109027-/",
    "VERSION":{
        "MAJOR": 1,
        "MINOR": 1,
        "PATCH": 17,
        "BUILD": 0
    },
    "KSP_VERSION": {
        "MAJOR": 1,
        "MINOR": 4,
        "PATCH": 1
    },
    "KSP_VERSION_MIN": {
        "MAJOR": 1,
        "MINOR": 4,
        "PATCH": 0
    },
    "KSP_VERSION_MAX": {
        "MAJOR": 1,
        "MINOR": 4,
        "PATCH": 1
    }
}
```

**Comment by HebaruSan** [comment]
That's just the min version being hard coded in the netkan:

https://github.com/KSP-CKAN/NetKAN/blob/870b74980eafbd89ebe5a0c53c02d166a90ef405/NetKAN/CustomBarnKit.netkan#L14-L15

**Comment by linuxgurugamer** [comment]
thank you
