### ISSUE TITLE
Ckan Mac version show a cross after "recommended mods"

### ISSUE THREAD

**Issue by rbcsky5** [KSP-CKAN/CKAN#2396]
Background
----------

**CKAN Version:** 
1.24.0

https://github.com/KSP-CKAN/CKAN/files/1756778/CKAN.zip (Using this version since the original .DMG version didn't work)

**KSP Version:** 
1.4.1

**Operating System:** 
macOS 10.13.3 (17D102)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Install KAS, KIS, Trajectories, Dmagic orbital science, Kerbal Alarm clock (basically all mods that has "recommended" page

**What did you expect to happen?**
Run normally

**What happened instead?**
It shows a big red cross after showing the dependency/recommended window

**Screenshots:**

<img width="1013" alt="screen shot 2018-03-31 at 01 25 01" src="https://user-images.githubusercontent.com/37041568/38147229-ddb9c042-3483-11e8-8a73-a5465fd3e30a.png">

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Which mods?

**Comment by rbcsky5** [comment]
KAS, KIS, Trajectories

**Comment by HebaruSan** [comment]
If that post is correct, then this would be caused by an exception in this block;

https://github.com/KSP-CKAN/CKAN/blob/a495f435fff9a8e2c55ca5fdca0cb92d9a03c0e8/GUI/MainModList.cs#L427-L444
