### ISSUE TITLE
Change our icon

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#240]
Currently the CKAN has a mono default icon. It should be a nice space-ship or something. :)

**Comment by HebaruSan** [comment]
> Hrm, this looks like it's more work than I'm willing to put in right now. I can post the raw gimp xcf file, if someone else wants to give it a shot, otherwise I'll poke around at it later (no promises on when 'later' is)

Hi @Felger! I realize this is a very long shot, but do you by any chance still have the .xcf file for the CKAN icon? @drewcassidy asked us about getting it in SVG format on Discord, and this issue is the last breadcrumb I was able to find for that.

**Comment by Felger** [comment]
Not such a long shot, it seems! I do indeed have them stashed away:

[ckan_logo_files.zip](https://github.com/user-attachments/files/29006775/ckan_logo_files.zip)
