### ISSUE TITLE
B9 PWing new fork to track

### ISSUE THREAD

**Issue by jrodrigv** [KSP-CKAN/CKAN#2403]
Good evening all,

This is the new active fork for B9 PWings compatible with KSP 1.4.2. It has the AVC file ready. 

Would you mind to add it to the CKAN database?

Regards

**Comment by HebaruSan** [comment]
I assume this is in reference to https://github.com/jrodrigv/B9-PWings-Fork ? Yes, we can index this.

**Comment by jrodrigv** [comment]
Sorry I forgot the link. Yes. Thanks!
