### ISSUE TITLE
Some mods still blocked despite being compatible

### ISSUE THREAD

**Issue by DirtyHarryE** [KSP-CKAN/CKAN#2404]
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Windows 10 Home

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

- Filter by "All"
- Search for "Near Future Electrical"

**What did you expect to happen?**
A list of three mods to appear (Near Future Electrical, Near Future Electrical Core and Near Future Electrical Extras), all of which can be installed, and have tickboxes next to them.

**What happened instead?**
Notice that Only Near Future Electrical Core and Near Future Electrical Extras appear and are allowed to be installed. Near Future Electrical, has no tickbox and cannot be installed, despite the KSP version being supported.

**Screenshots:**
![image](https://user-images.githubusercontent.com/3287957/38555489-319b6ea8-3cbe-11e8-96af-54c59c2b8f55.png)

**CKAN error codes (if applicable):** 
N/A

**Comment by HebaruSan** [comment]
Check the dependencies; this mod requires DynamicBatteryStorage, which hasn't been updated for 1.4 yet:

![image](https://user-images.githubusercontent.com/1559108/38556766-58805e42-3cba-11e8-9eb3-31c6c4b9e1cf.png)
