### ISSUE TITLE
Mod information sidebar is compressed

### ISSUE THREAD

**Issue by AndersDotExe** [KSP-CKAN/CKAN#2412]
CKAN version 1.25.0

KSP version 1.4.2.2110, Steam 64-bit

OS: Win10 64-bit

No changes have been made to my GameData folder apart from a few mods I had to download manually

Issue: mod information sidebar, [screencap here](https://imgur.com/a/sXgwA), happens every time CKAN starts, replaced CKAN install with new version ~10 minutes ago, has been a persistent issue for 1-2 months, a bit after KSP 1.4

![screenshot](https://i.imgur.com/vS4dpEO.png)

**Comment by HebaruSan** [comment]
Does it reset to that state after you drag the splitter?

**Comment by AndersDotExe** [comment]
Ah, I tried dragging the splitter and that seems to have fixed it. I did look for a splitter before, just couldn't find it. It does not seem to be resetting to the compressed state either. Thanks!
