### ISSUE TITLE
"Key not found"-exception on selecting mods

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2416]
Background
----------

**CKAN Version:** 
v1.25.1 (self-built and changed some layout stuff experimenting with little GUI changes to prevent Visual Studio changing the designer code every time you open the main form, so my changes shouldn't be relevant to this error)

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Windows 10 64bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
For testing some graphical improvements I tried, I **downloaded a mod** (with a suggested mod) to see the changeset tab. I accidently **clicked cancel during the installation process**, but it seemed to have it **installed completely nevertheless**.
So as I tried to uninstall it again, CKAN threw the following error every time I select either the same mod for Uninstall or other mods for Install.

**What did you expect to happen?**
Install / uninstall mod without errors.

**What happened instead?**
CKAN throws error on every `Install`-Checkbox click.

**CKAN error codes (if applicable):** 

```
System.Collections.Generic.KeyNotFoundException: Der angegebene Schlüssel war nicht im Wörterbuch angegeben.
   bei System.ThrowHelper.ThrowKeyNotFoundException()
   bei System.Collections.Generic.Dictionary\`2.get_Item(TKey key)
   bei CKAN.MainModList.<ComputeChangeSetFromModList>d__29.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   bei CKAN.Main.<UpdateChangeSetAndConflicts>d__55.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   bei CKAN.Main.<ModList_CellValueChanged>d__240.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

```

**Comment by HebaruSan** [comment]
The stack trace suggests this line, as `installed_modules` is the only notable `Dictionary` in the function:

https://github.com/KSP-CKAN/CKAN/blob/9e71f867240d9143e53035881e59bb4fc7d34377/GUI/MainModList.cs#L617-L618

Populated here:

https://github.com/KSP-CKAN/CKAN/blob/9e71f867240d9143e53035881e59bb4fc7d34377/GUI/MainModList.cs#L576-L577

That line is looking for mods that depend on mods being removed, and the exception suggests they're missing. Maybe `registry.InstalledModules` is in an inconsistent state, with missing dependencies? This is where the exact steps and mod names involved would be very helpful.

**Comment by HebaruSan** [comment]
Alternately, it's also possible that the registry is fine but the GUI has a problem. If the mod isn't really installed, but GUI _thinks_ it is, then GUI might be attempting to uninstall a mod that isn't installed, which could also conceivably cause this.

**Comment by DasSkelett** [comment]
Ouf, which mod was it...
I think it's been "Almost Free Launch Clamps", but I'm not sure. It's been some mod beginning with an A and having one suggested mod listed (not sure about dependencies).

After a restart, everything worked fine.
It might be relevant, that the error was thrown **every time** I **selected** (just clicking on the checkbox, not clicking Apply button) the same mod (for uninstall) **or** another mod for install.

**Comment by HebaruSan** [comment]
On further inspection, I think I pinpointed the wrong line above. `installed_modules` is a verbatim copy of `registry.InstalledModules`, and `FindReverseDependencies` uses that same list to generate its return values. So it shouldn't be logically possible for those `installed_modules[dependency]` references to throw.

**Comment by HebaruSan** [comment]
@DasSkelett, are you able to make this happen at will? I tried cancelling the installation of Almost Free Launch Clamps, but I didn't encounter any exceptions. There are some debugging statements built into this code path that might be enlightening to see [with logging enabled](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#logging).

**Comment by DasSkelett** [comment]
Meanwhile some thoughts during waiting for CKAN (because DEBUG logging is hell!):
Is it really needed to test for **every version of every mod** if it's compatible with the installed KSP version on every modlist update? So after each startup and each installation, CKAN does all those checks again.
Wouldn't it be sufficient to test for compatibility if you open the "Versions"-tab on the sidebar?
___
Furthermore, looking in the log, it seems to check every mod twice for compatibility?

I uploaded my log [here](https://nofile.io/f/Hwd30sZ1wmz) (nothing new to the original issue yet!)

**Comment by HebaruSan** [comment]
> Going to try it.

Any luck getting this to happen again? I'm reviewing some old issues, and it looks like we never got to the bottom of this one.

**Comment by DasSkelett** [comment]
Hey, back again, sorry for the long wait. I took my A-levels(?, Abitur in German) earlier this year and was traveling during summer.
I remember that I didn't get this error to show again, weird. Seems that you have to push cancel just the right millisecond to trigger this issue.

**Comment by DasSkelett** [comment]
Since there have been a bunch of releases in between and the error never showed up again, I'll close this issue.
