### ISSUE TITLE
CKAN crashes when I try to download mods

### ISSUE THREAD

**Issue by pokemoneuro** [KSP-CKAN/CKAN#2422]
v1.25.0 CKAN

1.2.2 ksp

Windows 10

Not made any changes to the folder

Problem
-------

**What steps did you take in CKAN?**
I did select the mods: Advanced Jet Engine, Airpark Continued, Airplane Plus and all B9 mods. Then applied and pressed continue, then it crashed.

**What did you expect to happen?**
Download the mods

**What happened instead?**
It crashed and gave me a message

**CKAN error codes (if applicable):** 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
   at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
   at CKAN.Main.ShowSelection(Dictionary`2 selectable, Boolean suggest)
   at CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by HebaruSan** [comment]
We're modifying `selectable` while iterating over it:

https://github.com/KSP-CKAN/CKAN/blob/9e71f867240d9143e53035881e59bb4fc7d34377/GUI/MainInstall.cs#L333-L339

**Comment by HebaruSan** [comment]
It's the KJR recommendation/suggestion that's tripping it up. (One mod recommends it, then another suggests it, and the code to avoid showing it twice has a bug.)

While we work on getting this fixed, you might be able to work around the problem by installing KJR separately before attempting the others.
