### ISSUE TITLE
Cannot install USI Kolonization Systems (MKS/OKS)

### ISSUE THREAD

**Issue by Forcas42** [KSP-CKAN/CKAN#2427]
Background
----------

**CKAN Version:** 
v1.25.0

**KSP Version:** 
1.4.2.2110

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

**Problem**
There is no update check in front of the "USI Kolonization Systems (MKS/OKS)" mod. 
![capture](https://user-images.githubusercontent.com/12395041/39273080-7b53a1da-48e6-11e8-80f1-4138cd177a6d.PNG)

I assume because it has a dependency on Ground Construction Core, which hasn't been updated for KSP 1.4.2. But Ground Construction Core has been integrated into MKS as I found at this [link,](https://github.com/UmbraSpaceIndustries/MKS/wiki/Parts-(Ground-Construction)) so the dependency shouldn't be there anymore. 

Am I understanding this wrong? Is there something wrong why the mod won't install?

**Comment by HebaruSan** [comment]
This mod's metadata is managed directly by the mod author. You'll need to contact him to get that dependency removed, if that's the issue.
