### ISSUE TITLE
Zero-byte registry file causes null reference exception on load

### ISSUE THREAD

**Issue by HobbitJack** [KSP-CKAN/CKAN#2433]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.3.1/1.4.2

**Operating System:** 
Windows 10 64x

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Launch CKAN

**What did you expect to happen?**
CKAN to launch and the directory select window to pop up

**What happened instead?**
I got an error

**Screenshots:**

![image](https://user-images.githubusercontent.com/18198370/39391768-b89953d2-4a76-11e8-90dd-30e22c1a5913.png)

**CKAN error codes (if applicable):** 
(Possibly)
7713 [1]

**Comment by HobbitJack** [comment]
BTW, if I'm a moron and did not see a previous issue relating to this, I'm sorry.

**Comment by HebaruSan** [comment]
You mention two steps that you took, but it's not clear when the problem happened. Did the error occur during launching, or sometime later?

**Comment by HobbitJack** [comment]
The problem occurres a few seconds after running CKAN. Also, I don't have my computer in front of me right now.

**Comment by HobbitJack** [comment]
I'm in front of my computer and can work on the issue.

**Comment by HebaruSan** [comment]
So you launch CKAN, and you wait a few seconds without doing anything else, and it crashes?

If you are clicking something, please specify exactly what.

**Comment by HobbitJack** [comment]
I am not clicking anything. I just launch it, then this crash occurs.

**Comment by HebaruSan** [comment]
Thanks, that helps.

The stack trace implies that `registry` is null in `ScanDlc`, which implies that `JsonConvert.DeserializeObject` returned null in `Load`, which suggests a problem in creating the registry. This looks like it may be related to KSP-CKAN/NetKAN#6459, which also describes a mysterious crash along a same or similar code path.

Can you please check whether a file called `registry.json` exists in the `CKAN` subdirectory of your KSP install?

**Comment by HobbitJack** [comment]
I'm not exactly sure which of my two KSP installs it's looking at, but i'll check both.

**Comment by HobbitJack** [comment]
Both installs have a registry.json.
![image](https://user-images.githubusercontent.com/18198370/39399573-3b3dadac-4aee-11e8-9d05-9d2d05375238.png)
![image](https://user-images.githubusercontent.com/18198370/39399578-54857a74-4aee-11e8-8af2-a3d2fc2e4530.png)

However, I did get an idea about the issue...

**Comment by HebaruSan** [comment]
Thanks for those screenshots; the file should never be 0 KB, so that gives us another clue as to what's going on. If you delete the registry.json file, does it reappear as 0 KB?

**Comment by HobbitJack** [comment]
One sec
