### ISSUE TITLE
Max KSP version should not be "any" in the UI

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2434]
I brought this up before.

Based on what I just saw in the program, the logic may wrong, and should be:

If there is ONLY a KSP_VERSION, then the min version and max version are the same as the KSP_VERSION
If there is either a KSP_MIN_VERSION or a KSP_MAX_VERSION specified, then the following applies:
If there is only a MIN version, then the max version should be any

**Comment by DasSkelett** [comment]
```
public KspVersion LatestCompatibleKSP()
{
    // Find the highest compatible KSP version
    if (ksp_version_max != null)
        return ksp_version_max;
    else if (ksp_version != null)
        return ksp_version;
    else
        // No upper limit.
        return KspVersion.Any;
}
```
As I read this code, it does exactly that.

**Comment by HebaruSan** [comment]
Yeah, as far as I know that's exactly what it does.
@linuxgurugamer, can you please elaborate on the problem you saw?

**Comment by HebaruSan** [comment]
Appears to be a non-issue, clarification not received. Closing for now.

@linuxgurugamer, if you are able to give more information about this, please do so and we can re-open it for investigation.
