### ISSUE TITLE
CKAN Attempts to use LibCurl even though removed.

### ISSUE THREAD

**Issue by Ruedii** [KSP-CKAN/CKAN#2436]
**CKAN Version:** 
 v1.25.1

**KSP Version:** 
v1.4.1

**Operating System:** 
Ubuntu Linux Mate Edition 17.10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
On a fresh install it complains the following:
23628 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
According to release notes Curl was completely removed.

**What steps did you take in CKAN?**
Fresh install on Linux, launched it selected check for updates automatically on load.

**What did you expect to happen?**
Actually work.

**What happened instead?**
Failed with error, then gave wrong error claiming it was a cert error, when it wasn't.

**CKAN error codes (if applicable):** 
Attached log
[CKAN.log](https://github.com/KSP-CKAN/CKAN/files/1958552/CKAN.log)

**Comment by Ruedii** [comment]
Well the curlsharp library is missing.

**Comment by Ruedii** [comment]
OK, updated to the Mono repository for Mono 5.x and it works fine now.

It's clearly having trouble finding the native libcurl or not recognizing that it is running on a Linux machine when under Mono 4.x.

**Comment by HebaruSan** [comment]
@Ruedii, why do you say "it's apparently looking for the windows native curl library instead of the Linux one"? Is there something in the error message that indicates that?

**Comment by Ruedii** [comment]
The issue has since been resolved.  This is no longer an issue.

On 4:37PM, Tue, Oct 2, 2018 HebaruSan <notifications@github.com> wrote:
>
> @Ruedii, why do you say "it's apparently looking for the windows native
curl library instead of the Linux one"? Is there something in the error
message that indicates that?

**Comment by HebaruSan** [comment]
OK, closing as per issue author.
