### ISSUE TITLE
[Enhancement suggestion] Purge old downloads from cache

### ISSUE THREAD

**Issue by JesusTheBird** [KSP-CKAN/CKAN#2438]
I think it would be great when a mod updates to a newer version of ksp(a version the player has currently installed) ckan should delete the older version from ..\Kerbal Space Program\CKAN\downloads folder, replacing it with the version that is installed alongside with the currently installed version of ksp. 

Issue: I see at least two different versions of many mods in my ckan downloads folder, and all ive been doing is updating mods to new versions when I see them available. it looks like ckan doesn't touch the older versions of mods once a newer version is installed alongside an updated version of ksp. 

Since Ckan can point to multiple ksp installs, a decision should be made if: Can I use this with multiple KSP installs at the same time(lets say I have 1.4.3 and 1.3.2 installed in different directories)? Can the settings be set based off what ksp version im currently using(we obviously don't want 1.4+ mods installing to a 1.3.0-2 just like that, or mods simply not appearing at all for a 1.3 install when you also have 1.4+ available )

Thank you!! I'm glad I could help!

Background
----------

**CKAN Version: 1.25.1** 

**KSP Version: 1.4.3** 

**Operating System: Windows 10 x64**

**Comment by DasSkelett** [comment]
That sounds nice :+1: .
I think the "tidy up" process would be best after install, because that's when we would hit the cache limit. "Delete all incompatible entries" should be called everytime after install, whereas the other deletions then depend on `cache > limit`

**Comment by politas** [comment]
Definitely need a checkbox in settings to allow this option to be turned off if implemented. I have never deleted a mod from my cache and don't intend to!

**Comment by politas** [comment]
Would also be good to throw a dialog box asking users to confirm they want this on after they auto-upgrade, so people aren't caught by surprise. IE, if the setting doesn't exist in the CKAN settings, prompt rather than force it on. Or default to the pre-existing behaviour.

**Comment by JesusTheBird** [comment]
this is developing into a nice idea. Keep it up guys! Yall ROCK!!
