### ISSUE TITLE
CKAN 1.25.1 is a virus, by Symantec

### ISSUE THREAD

**Issue by giblous** [KSP-CKAN/CKAN#2440]
Symantec Antivirus detects CKAN 1.25.1 as "WS.Reputation.1" malware
This is not happening on previous CKAN releases.

OS: Windows7 64bit pro

**Comment by HebaruSan** [comment]
Looks like a non-issue.

https://www.symantec.com/security-center/writeup/2010-051308-1854-99

> WS.Reputation.1 is a detection for files that have a low reputation score based on analyzing data from Symantec’s community of users and therefore are likely to be security risks. Detections of this type are based on Symantec’s reputation-based security technology. Because this detection is based on a reputation score, it does not represent a specific class of threat like adware or spyware, but instead applies to all threat categories. 
> 
> The reputation-based system uses "the wisdom of crowds" (Symantec’s tens of millions of end users) connected to cloud-based intelligence to compute a reputation score for an application, and in the process identify malicious software in an entirely new way beyond traditional signatures and behavior-based detection techniques.

So it's not even reporting a problem, it's just warning you that CKAN is unfamiliar to it. That's not a problem the CKAN team can fix.

Closing for now. If you see evidence that something is really wrong with CKAN, please reply and we can re-open this.
