### ISSUE TITLE
Kerbal Renamer releases not listing

### ISSUE THREAD

**Issue by Bornholio** [KSP-CKAN/CKAN#2446]
**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.2/1.4.3

**Operating System:** 
WIN10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
yes

Problem
-------

**What steps did you take in CKAN?**
select Kerbal renamer versions tab

**What did you expect to happen?**
list version .8 as 1.3.1 compatible and 1.0.0 as 1.4.3 compatible

**What happened instead?**
v1.0.0 listed as 1.2.2 compatible, no .8 listed

**Comment by HebaruSan** [comment]
0.8 is marked as a pre-release on GitHub, it won't be indexed till there's a regular release.

1.0.0 we can update manually...
