### ISSUE TITLE
Real Heat missing v4.6

### ISSUE THREAD

**Issue by Bornholio** [KSP-CKAN/CKAN#2447]
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.2/1.4.3

**Operating System:** 
win10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
yes

Problem
-------

**What steps did you take in CKAN?**
view version data for RealHeat mod

**What did you expect to happen?**
listing for v4.6 compatible with 1.4.3

**What happened instead?**
missing release v4.6

**Comment by HebaruSan** [comment]
There aren't any files attached to that release:

https://github.com/KSP-RO/RealHeat/releases/tag/v4.6

The Netkan bot will index it once the author fixes that.

**Comment by Bornholio** [comment]
Lol Successfully made me feel dumb !  I'll poke RsparkyC
