### ISSUE TITLE
Ckan using wrong Ksp version

### ISSUE THREAD

**Issue by unknownEnemy1345** [KSP-CKAN/CKAN#2450]
Well, its just what the title says, ckan thinks ksp is at version 1.4.xx, on a 1.2.2 install leading to downloading of 1.4 mods instead of the 1.2.2 version.

**Comment by HebaruSan** [comment]
We need more information to investigate. Please answer the questions in the issue template.

https://github.com/KSP-CKAN/CKAN/blob/master/ISSUE_TEMPLATE.md

**Comment by HebaruSan** [comment]
What are you seeing on the screen that leads you to believe that it detects 1.4? Are you looking at the actual game version somewhere as reported by CKAN, or guessing based on mods installed as in the OP?

**Comment by kurgut** [comment]
![capture](https://user-images.githubusercontent.com/39562611/40470192-11253734-5f33-11e8-829a-97fbb096c1d8.PNG)

**Comment by kurgut** [comment]
Well, it's the second one in the list, it shows 1.4.3.xx , whereas my installation is 1.2.2.  
I just wan't to install RO/ RSS and stuff on a clean 1.2.2 version.
Thanks:)

**Comment by kurgut** [comment]
Ok thank you, I try it!

**Comment by kurgut** [comment]
Hmm It didn't work..

**Comment by HebaruSan** [comment]
OK, in that case it's likely that you actually have 1.4.3. Double check the value in the Path column as compared to where you think 1.2.2 is installed.
