### ISSUE TITLE
CKAN crashes when it can't write to the windows registry

### ISSUE THREAD

**Issue by rsparkyc** [KSP-CKAN/CKAN#2452]
**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes

Problem
-------

I am running KSP on a machine under an account with limited permissions.  When CKAN starts, it attempts to create a key at `HKEY_CURRENT_USER\Software\CKAN`, but an UnautorizedAccessException is thrown

![image](https://user-images.githubusercontent.com/2042290/40387602-384b9690-5ddb-11e8-8e28-f7d95e685fd3.png)

**Comment by politas** [comment]
Yes, CKAN can't work without being able to store its configuration files in the registry. Why is your account prevented from writing to the local user's branch of the registry? That is usually writable by the local user. It's how Windows apps are meant to store their configuration.
