### ISSUE TITLE
Norton is marking CKAN as a virus again

### ISSUE THREAD

**Issue by aaronburro** [KSP-CKAN/CKAN#2454]
I'm trying to download the latest version of CKAN, and it''s getting flagged by Norton as WS.Reputation.1 and Heur.AdvML.C.

I've tried to make it accept the file as legit, but Windows won't even let it run.

**Comment by HebaruSan** [comment]
Neither of those indicate actual viruses.

> Heur.AdvML.C is a heuristic detection designed to generically detect malicious files using advanced machine learning technology. A file detected by this detection name is deemed by Symantec to pose a risk to users and is therefore blocked from accessing the computer. 

See #2440 for WS.Reputation.1

CKAN can't fix false positives with antivirus software.

**Comment by aaronburro** [comment]
I raised this as a notification so that someone involved with the project can notify Norton of the problem. I see it has happened in the past, and someone was able to fix the problem then.

**Comment by HebaruSan** [comment]
Got a link to that previous incident?

**Comment by politas** [comment]
Unfortunately, Norton's Whitelisting program has been closed, so there's no longer any way for us to register our releases. All that can be done is Norton users to mark the code as trusted themselves, which feeds in to Norton's database. For information on how to do that, if it is still an option they have, you will have to talk to Norton. They aren't listening to us, anymore.
