### ISSUE TITLE
Procedural Fairings has some very strange version numbers

### ISSUE THREAD

**Issue by rsparkyc** [KSP-CKAN/CKAN#2455]
**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Windows

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
Procedural Parts shows some interesting version numbers.  Versions `1.4.3.1` & `1.4.3.2` are showing up with a `1:` before them, apparently making them seem more recent than `1.4.3.3` and the just released but not indexed yet `1.4.3.4`

![image](https://user-images.githubusercontent.com/2042290/40741978-ff9ad536-641a-11e8-8acd-b2ef2c873316.png)

**Comment by HebaruSan** [comment]
@linuxgurugamer worked on this in KSP-CKAN/NetKAN#6547 and KSP-CKAN/NetKAN#6552. Looks like an epoch was added briefly, creating the two versions with a `1:` prefix, then removed, creating the newest numbers at the bottom of the list.

**Comment by rsparkyc** [comment]
should I add an epoch to my ProceduralFairings.version file?  I'm assuming the epoch was added because of the change is versioning.

**Comment by rsparkyc** [comment]
Ok, I'll update https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/ProceduralFairings.netkan

**Comment by rsparkyc** [comment]
Ahh, sweet, thx
