### ISSUE TITLE
Inconsistent version behaviour (Rounding issue?)

### ISSUE THREAD

**Issue by Basic0** [KSP-CKAN/CKAN#2456]
Background
----------

**CKAN Version:** 

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Win 10 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, countless, including writing my own mods.

Problem
-------

**What steps did you take in CKAN?**
I'm attempting to install the Astronomers Visual Pack. It's reporting that the Max Supported version is 1.4.3, but isn't listed as compatible.

![image](https://user-images.githubusercontent.com/3108349/40874772-6dd969b6-666b-11e8-9877-b2127d709f86.png)

In case the mod targeted something >= 1.4.3.0 and < 1.4.3.2152, I added a compatible version for 1.4.3

![image](https://user-images.githubusercontent.com/3108349/40874776-74557c30-666b-11e8-98cd-3dd0ef6c9fec.png)

Unfortunately, the mod is still listed as incompatible, and installing something that depends on it, still results in a version error.

![image](https://user-images.githubusercontent.com/3108349/40874780-88d67b50-666b-11e8-847d-8221611d30e4.png)

It turns out that adding 1.4 as a compatible version is sufficient to get the install to work, but I'd prefer to be as granular as possible to avoid unintended consequences.

**What did you expect to happen?**

For the version information displayed to be sufficient to correctly configure compatible versions.

**What happened instead?**

I was unable to target 1.4.3 specifically.

**Comment by HebaruSan** [comment]
Check the dependencies; this mod depends on Scatterer, which only supports up to 1.4.2:

![image](https://user-images.githubusercontent.com/1559108/40877491-48570b9a-6647-11e8-8e10-840962ecdb9e.png)

**Comment by Basic0** [comment]
That explains it, thanks. May I suggest an enhancement to the "incompatible version" error dialog to make the root cause explicitly clear?
