### ISSUE TITLE
CKAN crashes on startup - Not Responding

### ISSUE THREAD

**Issue by mschwa9** [KSP-CKAN/CKAN#2457]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.4.3.2152

**Operating System:** 
Windows 7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

When opening ckan.exe, the GUI opens but immediately stops responding.

**Comment by HebaruSan** [comment]
We'll need more information to help; this could have many different causes and it's impossible to guess which is applicable from this description. Please start by answering all the questions from the issue template.

https://github.com/KSP-CKAN/CKAN/blob/master/ISSUE_TEMPLATE.md
