### ISSUE TITLE
Suggestion: Show "description" for a mod in the GUI

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#2458]
Background
----------

**CKAN Version:** v1.25.1

Suggestion
-------

Show both the abstract and description for a mod. To be fancy, use the abstract as a summary which, if clicked on, opens the description.

There's currently not much point adding a description instead of an abstract in NETKAN as it's never seen in the GUI (which, I would hesitate to guess, over 99% of users use instead of the command-line version).

**Comment by politas** [comment]
That's a good point. We've got that huge box in the top right, and we're just using the abstract.
