### ISSUE TITLE
"Apply Changes" Button Showing Up Gray

### ISSUE THREAD

**Issue by CYT-SubZer0** [KSP-CKAN/CKAN#2459]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.3.1

**Operating System:** 
Win10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, but I have deleted those changes since they did nothing. Otherwise, no.

Problem
-------

**What steps did you take in CKAN?**
I checked off a large list of mods and I tried to click apply changes to install those, but the button was gray and did not function. I tried to fix this by unchecking the red highlighted mods but it still didn't work, and I'm kind of at a loss here.

**What did you expect to happen?**
Button shows up green, I install the mods.

**What happened instead?**
Button showed up gray, mods were highlighted red, and then it didn't work after unchecking them.

**Screenshots:**
https://user-images.githubusercontent.com/40218958/41321521-f437fa44-6e69-11e8-80ca-30134d2ff8bf.png

**CKAN error codes (if applicable):** 
None

**Comment by ReiDaTecnologia** [comment]
This happened with me but with a few differences:
CKAN said i have BDArmory and it's incompatible with BDArmory Continue but i don't have installed BDArmory, when i tried to update BDArmory Continue. Really weird.
