### ISSUE TITLE
Community tech tree

### ISSUE THREAD

**Issue by DavideCoco** [KSP-CKAN/CKAN#2462]
Community tech tree by Nertea was updated at version 3.3.2 (ksp 1.4.3), but in ckan i found that the ksp version supported by this version of the mod is 1.4.2.
Is this fixable?

**Comment by HebaruSan** [comment]
That [release on SpaceDock](https://spacedock.info/mod/534) says 1.4.3 in the description, but it was actually filed under 1.4.2:

![image](https://user-images.githubusercontent.com/1559108/41605233-a1211dee-73a6-11e8-927b-67e6a2d4c690.png)

I'd suggest contacting the author to have that fixed.

**Comment by politas** [comment]
Suggest to the author that including a KSP-AVC .version file would allow much better definition of supported versions than Spacedock allows.

**Comment by HebaruSan** [comment]
[It now says 1.4.4](https://spacedock.info/mod/534). Hopefully that works for the OP.
