### ISSUE TITLE
CKAN doesn't work

### ISSUE THREAD

**Issue by SACKDUDE** [KSP-CKAN/CKAN#2466]
hello can some help me i really install eve and sve with this program please HELP ME

https://github.com/KSP-CKAN/CKAN/issues

ckan latest version

1.3

WINDOWS 10

YES I PUT ALL MY MODS BUT DOESNT WORK

when i install ckan and i open auto updater it closes what i have to do_

i download the ckan files and auto updater

open an window with the ckan mods

it close the black window 

nope

**Comment by HebaruSan** [comment]
The release notes say this:

> - You don't need to download AutoUpdate.exe. This is used internally by CKAN when a new version is released.

Just run ckan.exe.
