### ISSUE TITLE
CKAN system dependencies

### ISSUE THREAD

**Issue by MagixInTheAir** [KSP-CKAN/CKAN#2472]
From https://github.com/mockingbirdnest/Principia/issues/1720 : 
"Furthermore, Principia has system dependencies (like the C++ runtime) that CKAN cannot manage."

How true is this ? Is any support planned for those dependencies in the future ?
Thanks

**Comment by HebaruSan** [comment]
As far as we know it's true. I for one am not going to tell the Principia author that he's wrong and index it against his will. See KSP-CKAN/NetKAN#6242 for the last time this was asked.

**Comment by MagixInTheAir** [comment]
The thing is, maybe it also stops mods other than Principia from integrating CKAN even though they may agree if it was technically possible. this is not an issue related only to Principia, please reopen or close for good reason as my second question wasn't answered

**Comment by HebaruSan** [comment]
As I understand it, their concern is that CKAN can't forcibly install [vc_redist](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads) on the user's computer. I would not anticipate that being added.

**Comment by MagixInTheAir** [comment]
Well the generic solution here would be to enable custom install scripts

**Comment by politas** [comment]
Or for anyone who wants to run Principia to install it outside CKAN, because CKAN doesn't change anything outside the KSP directory and its own entries in the registry.

**Comment by MagixInTheAir** [comment]
Again, this issue is not related specifically to Principia but to any mod that may need external dependencies
