### ISSUE TITLE
CKAN Won't  Remove Any Mods

### ISSUE THREAD

**Issue by CYT-SubZer0** [KSP-CKAN/CKAN#2475]
Background
----------

**CKAN Version:** 
1.25.1 or Version Broglio

**KSP Version:** 
KSP 1.3.1

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
I tried uninstalling my full modlist (around 100 mods) and on the first few mods it gave an error, then I tried restarting CKAN and it did the same thing

**What did you expect to happen?**
Uninstall my mods, like it had done many times before

**What happened instead?**
Gave an error 

```
The following inconsistencies were found:
* C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/000_AT_Utils/Plugins/002_MultiAnimators.dll is registered to AT-Utils but has not been removed!
* C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/000_AT_Utils/Plugins/000_AT_Utils.dll is registered to AT-Utils but has not been removed!
* C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/000_AT_Utils/Plugins/SubmodelResizer.dll is registered to AT-Utils but has not been removed!
* C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/000_AT_Utils/Plugins/ConfigurableContainers.dll is registered to AT-Utils but has not been removed!
* C:/Program Files (x86)/Steam/steamapps/common/Kerbal Space Program/GameData/000_AT_Utils/Plugins/001_AnisotropicPartResizer.dll is registered to AT-Utils but has not been removed!
Error!
```

**Screenshots:**

![screenshot](https://user-images.githubusercontent.com/40218958/42909085-81e987b8-8aa8-11e8-99d0-b788bcb3a42d.png)

**CKAN error codes (if applicable):** 
None given

**Comment by HebaruSan** [comment]
Origin of exception:

https://github.com/KSP-CKAN/CKAN/blob/54827d154c8cf55d48411dcbcc3438cdbf22716a/Core/Registry/Registry.cs#L762-L778

Thrown when file still exists after attempt to delete here:

https://github.com/KSP-CKAN/CKAN/blob/54827d154c8cf55d48411dcbcc3438cdbf22716a/Core/ModuleInstaller.cs#L827-L864

**Comment by HebaruSan** [comment]
I tried installing and uninstalling `AT-Utils`, and didn't get this error; some key piece of info is missing.

@CYT-SubZer0, is your KSP still running? That might explain why Windows doesn't let you delete these DLLs...

**Comment by CYT-SubZer0** [comment]
Thank you so much I completely forgot that I had KSP running in the background. I keep it on since it takes such a long time to load up. Thanks!
