### ISSUE TITLE
Install From .zip Errors

### ISSUE THREAD

**Issue by CYT-SubZer0** [KSP-CKAN/CKAN#2476]
Background
----------

**CKAN Version:** 
1.25.1

**KSP Version:** 
1.3.1

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, but quickly reverted them and made sure that only the basic install of the game (no mods installed) was still working properly.

Problem
-------

**What steps did you take in CKAN?**
I downloaded a modpack that did not have a ckan install file, but rather a zipped modpack file, so I tried installing from that .zip, and it errored out. Then I realized that I needed to compress the mods, so I did that and it gave me an error, even on mods I knew were in it's repository.

**What did you expect to happen?**
The mods would be installed through CKAN

**What happened instead?**
Gave me the error: "Not found in index: Airpark.zip" except for every mod I tried to install.

**Screenshots:**

![screenshot](https://user-images.githubusercontent.com/40218958/42941789-7d9354c0-8b23-11e8-89e4-3441b71d81a3.png)

**CKAN error codes (if applicable):** 
None

**Comment by CYT-SubZer0** [comment]
It may also be an issue that I am 1) New to installing like this (downloaded mods through CKAN) and 2) a few of the mods aren't currently in CKAN.

**Comment by HebaruSan** [comment]
What steps did you actually take? I.e., how did you "[try] installing from that .zip", what did you click?

**Comment by CYT-SubZer0** [comment]
I clicked file, import from downloaded mods, and clicked the compressed folder of the mod.

**Comment by HebaruSan** [comment]
OK, that feature is not for importing modpacks. It's for individual mod ZIP files that you downloaded yourself, which people sometimes do if they have trouble downloading with CKAN. A mod pack can only be installed manually.

**Comment by CYT-SubZer0** [comment]
No I only tried to install one mod, not a modpack.

**Comment by CYT-SubZer0** [comment]
[Firespitter.zip](https://github.com/KSP-CKAN/CKAN/files/2211040/Firespitter.zip)
Like this: wasn't found
I don't know if this matters any more because I installed them manually and they work fine, I just wanted to be sure I installed them properly.

**Comment by HebaruSan** [comment]
Hmm, that file says it's version 7.6.0, but it's not the same as the official download for that version (lots of folders are missing):

https://github.com/snjo/Firespitter/tree/v7.6.0

Whoever prepared this mod pack messed with the files so they're not recognizable by CKAN. The import feature is for the official download files released by mod authors.

**Comment by CYT-SubZer0** [comment]
ok, thank you! This modpack wasn't really made for CKAN, and like I said, this is my first time trying to do this so thank you for helping and I see now that I compressed a file that wasn't meant for CKAN and tried to run it through it. Thanks!
