### ISSUE TITLE
"Error in Auto-update"

### ISSUE THREAD

**Issue by jp-bse** [KSP-CKAN/CKAN#2477]
Background
----------

**CKAN Version:** 
1.24.0

**KSP Version:** 
1.4.4.2215

**Operating System:** 

Linux 4.4.0-130-generic #156-Ubuntu

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

No

Problem
-------

**What steps did you take in CKAN?**

Opened CKAN

**What did you expect to happen?**

Ordinary operation

**What happened instead?**

Error message:

"Error in auto-update:
	Error: SendFailure (Error writing headers)"

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
What version of Mono do you have?

Also try the latest version of CKAN: https://github.com/KSP-CKAN/CKAN/releases/latest

**Comment by jp-bse** [comment]
from "$ man mono" i think i have mono 3.0.  No updates to mono are suggested when i run apt-get upgrade

**Comment by HebaruSan** [comment]
Yeah, you need at least Mono 4, ideally Mono 5. Try here.

https://www.mono-project.com/download/stable/#download-lin

**Comment by jp-bse** [comment]
everything seems to be working now, thanks
