### ISSUE TITLE
CKAN incorrectly showing an update is available

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2478]
Note that﻿ the following .version file:

`
{
﻿  "NAME"     : "B9 Part Switch",
  "DOWNLOAD" : "https://github.com/blowfishpro/B9PartSwitch/releases",
  "URL"      : "https://s3.amazonaws.com/blowfish-ksp-b9partswitch-avc/ksp-1.4.4/B9PartSwitch.version",
  "GITHUB" : {
    "USERNAME"   : "blowfishpro",
    "REPOSITORY" : "B9PartSwitch"
  },
  "VERSION" : {
    "MAJOR" : 2,
    "MINOR" : 3,
    "PATCH" : 2
  },
  "KSP_VERSION" : {
    "MAJOR" : 1,
﻿    "MINOR" : 4,
    "PATCH" : 4
  }
}
`
 

is causing CKAN to show an update﻿ is available on a 1.4.3 install.  This is wrong﻿.﻿

Background
----------

**CKAN Version:** 

**KSP Version:** 

**Operating System:** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
There _is_ an update available:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/B9PartSwitch/B9PartSwitch-v2.3.3.ckan
