### ISSUE TITLE
Anti-virus False-Positive (Norton)

### ISSUE THREAD

**Issue by bwoneill** [KSP-CKAN/CKAN#2488]
Background
----------

**CKAN Version:** 1.25.2

**KSP Version:** 1.3, 1.4.5

**Operating System:** Windows 10 v1803

**Anti-virus Software:** Norton Security 22.14.2.13

Problem
-------

**What steps did you take in CKAN?** Downloaded latest version of CKAN (Goddard 1.25.2)

**What did you expect to happen?** Successful download

**What happened instead?** Norton Security identified ckan.exe as a Heuristic Virus and deletes the file. The same thing happens when updating from within CKAN v1.25.1 or downloading from Github. 

**Screenshots:**
![capture1](https://user-images.githubusercontent.com/486312/43746459-451761b6-9999-11e8-9495-22f5865ad6ee.PNG)

Workaround
----------
Restore and exclude ckan.exe

Solution
-----------
Submit false-positive report to https://submit.symantec.com/false_positive/

**Comment by Tabris83** [comment]
same thing happens in window defender (or whatever it's call now days)

**Comment by politas** [comment]
Unfortunately, the anti-virus people have all abandoned their whitelisting programs, so there's nothing we can do to fix it at our level of funds.
