### ISSUE TITLE
Is there a support for CKAN-Globus integration?

### ISSUE THREAD

**Issue by ghltshubh** [KSP-CKAN/CKAN#2502]
Does CKAN provide [Globus](https://www.globus.org/) integration.

**Comment by HebaruSan** [comment]
Probably not. What is it, and why do you want integration with it?

**Comment by HebaruSan** [comment]
@ghltshubh, looking at that page, I think you may have intended to ask about this project instead:

https://github.com/ckan/ckan

KSP-CKAN is an application for installing mods for Kerbal Space Program.
