### ISSUE TITLE
CKAN Mod install larger than 100%

### ISSUE THREAD

**Issue by zwang20** [KSP-CKAN/CKAN#2508]
Background
----------

**CKAN Version:** 
v1.25.2+2321d887ba46

**KSP Version:** 
1.4.5.2243

**Operating System:** 
Mac OSX High Sierra
10.13.4 (17E199)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes, but I have removed all the mods as stated in the documentation and installed them via CKAN

Problem
-------

**What steps did you take in CKAN?**
use the terminal command CKAN prompt
install SmartTank
(this also happened with other mods)

**What did you expect to happen?**
The downloading process would stop at 100%

**What happened instead?**

The downloading progress ticks over 100%
This isn't really a huge problem, but its just annoying to watch
After it finishes it resets to 100%

**Screenshots:**

![screen shot 2018-08-21 at 8 56 34 pm](https://user-images.githubusercontent.com/41721295/44397721-b6722480-a584-11e8-8e36-2afb2e0890c2.png)

**Comment by HebaruSan** [comment]
I think this has to do with the archive.org fallback URLs. If GitHub lets you download part of a file and then throttles your download, CKAN starts downloading the archive.org file without resetting the download byte count, so the total number of bytes downloaded is more than the size of the file.

**Comment by HebaruSan** [comment]
Looked into this a little more. CKAN doesn't track the download byte count independently; it always comes from `WebClient` events, both before and after we start the fallback URL. So we'd either have to tell `WebClient` to change its byte counts somehow, or tweak how we get that info from it.

**Comment by LastStarDust** [comment]
I am experiencing the very same problem in Ubuntu 18.04 as shown in [this picture](https://www.dropbox.com/s/p13e5xti4bwj5jo/CKAN.png?dl=0)
OS: Ubuntu 18.04 x86_64
CKAN: 1.25.3
KSP: 1.4.5
