### ISSUE TITLE
cant find ckan.exe anywhere in the files

### ISSUE THREAD

**Issue by coolamazing** [KSP-CKAN/CKAN#2509]
Background
----------

**CKAN Version:** 
1.25.2

**KSP Version:** 
1.4.4

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------
i cant find the ckan.exe anywhere in the ckan-master folder
**What steps did you take in CKAN?**

**What did you expect to happen?**
i expected to be able to run the program i just downloaded

**What happened instead?**
THEIR IS NO FREAKING .EXE

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
It's here:

https://github.com/KSP-CKAN/CKAN/releases/download/v1.25.2/ckan.exe

Don't click on the source code link.

**Comment by coolamazing** [comment]
![thx genius](https://user-images.githubusercontent.com/42589471/44436446-38f9e480-a583-11e8-965f-a37379ff49de.png)
...
