### ISSUE TITLE
CKAN MECHJEB 2 Install will not index mumech_mj2_pod. KSP locks on startup.

### ISSUE THREAD

**Issue by prattipus** [KSP-CKAN/CKAN#2519]
Background
----------

**CKAN Version:** 

Most Recent

**KSP Version:** 

Most Recent

**Operating System:** 

Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Attempted to reinstall the mod file.

**What did you expect to happen?**
I expected the game to find the file it's referencing.

**What happened instead?**
It locked to the loading screen MechJeb2/Parts/MecjJeb2_Pod/part/mumech_MJ2_Pod is the reference file.

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
Try the modded support forum:

https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/

The CKAN team doesn't fix in-game problems.
