### ISSUE TITLE
Corrupted registry (Unterminated string. Expected delimiter: ".)

### ISSUE THREAD

**Issue by Someone-Smart** [KSP-CKAN/CKAN#2520]
Mildly code literate (no actual experience though)

KSP 1.25.3.2243

CKAN 1.4.5.

windows10

Only uninstalled a handful of mods (by deleting the folders from GameData) after CKAN stopped working

Ckan stopped opening

ran CKAN.exe

normal CKAN operation

see screenshots

![image](https://user-images.githubusercontent.com/43073327/45232594-352ec780-b2d0-11e8-85ea-664556d21939.png)
![image](https://user-images.githubusercontent.com/43073327/45232614-4a0b5b00-b2d0-11e8-865c-30f07ae497a1.png)

see screnshots

**Comment by HebaruSan** [comment]
Your registry got corrupted somehow. Try this:

1. Go to your KSP game folder (directory)
2. Copy the "CKAN" folder to "CKAN-backup"
2. Open the "CKAN" folder
3. Select all files other than the "downloads" folder
4. Delete the selected files
5. Run CKAN again to regenerate the registry

**Comment by Someone-Smart** [comment]
That fixed it flawlessly

**Comment by HebaruSan** [comment]
Cool. Without some indication of what caused the registry file to be corrupted, I think that's the best we can do. If it happens again, try to remember what you were doing immediately before, and maybe we can figure something out.
