### ISSUE TITLE
Facebook key hash

### ISSUE THREAD

**Issue by henryscp** [KSP-CKAN/CKAN#2523]
Hallo

ich habe ein problem und zwar habe ich ein neues Handy bekommen und habe halt die apps rübergezogen doch jetzt habe ich bei einer App das wenn ich mich dort mit Facebook anmelden will das sthet "invalid key hash [...]"

ich weiß vllt gehört das nicht nach github aber ich dachte mir das die schlaue community hier vielleicht idean hat das zu lösen

Danke schonmal

Lg

English:
I have a problem and although I have got a new phone and have just pulled over the apps but now I have in an app that if I want to sign up with Facebook is the "invalid key hash [...]"

I know probably does not belong to github but I thought that the clever community here maybe idean has to solve that

Thanks in advance

**Comment by HebaruSan** [comment]
I think you meant to go here: https://github.com/ckan/ckan

KSP-CKAN is an application that manages mods for a video game; it doesn't interact with Facebook.

Deutsch:

Ich glaube, du wolltest hierher gehen: https://github.com/ckan/ckan

KSP-CKAN ist eine Anwendung, die Mods für ein Videospiel verwaltet; Es interagiert nicht mit Facebook.

**Comment by henryscp** [comment]
no i wanted to make just a aks or something dont know that i postet that6 in KSP/CKAN

**Comment by henryscp** [comment]
Ich wollte nur ein Post machen an die Comminity ich wuste nicht das ich das in KSCP/CKAn gemacht habe kann man das verschieben oder so?

**Comment by HebaruSan** [comment]
No, I can't move it. You would have to create a new post at the correct place.

Nein, ich kann es nicht bewegen. Sie müssten einen neuen Beitrag an der richtigen Stelle erstellen.

**Comment by henryscp** [comment]
dont know how and where

**Comment by HebaruSan** [comment]
I provided a link above. Please click it and try again.

https://github.com/ckan/ckan
