### ISSUE TITLE
CKAN works but now can't find root file.

### ISSUE THREAD

**Issue by kspbeginner** [KSP-CKAN/CKAN#2524]
Background
----------

**CKAN Version:** 

1.25.3

**KSP Version:** 

Not sure. downloaded it this week. should be recent version.

**Operating System:** 

MacOS High Sierra 
10.13.6

- I direct downloaded KSP from the website and do not operate on steam, so all data is in my "applications" folder.

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Not that I'm aware of

Problem
----------

**What steps did you take in CKAN?**

- manually opened ckan via terminal

Attempted to search in other folders based on previous issues searched but no resolution.

**What did you expect to happen?**

I expected to click on the applications folder, find the KSP_osx folder, and the root file

**What happened instead?**

- "select KSP install" window appears

- When searching in the applications folder, the search function comes up with nothing. I've tried moving the folder, moving the file itself. Nothing works. really frustrating.

when accessing the applications folder, there is absolutely nothing.

**Comment by HebaruSan** [comment]
So you're having trouble finding the folder where you installed KSP?

One note, there is no "search function" here. CKAN just needs you to show it where your game is installed.

**Comment by kspbeginner** [comment]
Thats correct. I'm not as computer savvy as I would like to be but the browser function on the "select KSP install" window shows the applications folder and nothing inside it. As I said, I do not play off of steam therefore do not have the default folder location. I direct downloaded it off of the Kerbal space program website so the osx folder is in my applications folder

**Comment by HebaruSan** [comment]
Can you show a screenshot (should be able to just paste into the text box on GitHub)? It's not quite clear exactly when the problem is occurring.

**Comment by kspbeginner** [comment]
<img width="1416" alt="screen shot 2018-09-21 at 4 11 36 pm" src="https://user-images.githubusercontent.com/43468814/45912206-535cf300-bdb9-11e8-8abc-ab573d3f85f8.png">

-as you can see, my KSP osx folder is in my applications folder, but nothing is coming up when I try to select applications to browse for the root folder.

**Comment by HebaruSan** [comment]
It looks like you're in your personal folder. Try going to "My Computer" first to find the system Applications folder.

**Comment by kspbeginner** [comment]
I have looked in every folder in "my computer" and nothing has turned up. Can i move the ksp_osx folder to a different location without screwing it up?

**Comment by HebaruSan** [comment]
As far as I know, you can move the KSP folder wherever you want, but I don't have a Mac to test that on. Maybe try copying it instead of moving?

**Comment by politas** [comment]
Mac OS seems to hide a lot of things from the file Open dialog box to make things less complicated for users, because they think you're too stupid. 
One suggestion is to put a link/shortcut to the KSP install directory somewhere you can see in the "Select KSP install" window.
