### ISSUE TITLE
Exception during WebClient request

### ISSUE THREAD

**Issue by Hotel26** [KSP-CKAN/CKAN#2527]
Background
----------

**CKAN Version:** 1.25.3

**KSP Version:** 1.4.5.2243

**Operating System:** Linux Mint Sonya 18.2 64-bit

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Ja.  Additional directories only.

Problem
-------
**What steps did you take in CKAN?**
Applying installation of the above-mentioned 6 mods

**What did you expect to happen?**
SUCCESS!

**What happened instead?**
FLAME-OUT!!

**Screenshots:**

**CKAN error codes (if applicable):** 

```
An exceptino occurred during a WebClient request

About to install...

 * AtmosphereAutopilot (Fly-By-Wire) v1.5.11 (github.com, 127.7 KB)
 * Kerbal Alarm Clock v3.9.1.0 (github.com, 1.3 MB)
 * Kerbal Engineer Redux 1.1.5.3 (github.com, 921.5 KB)
 * MechJeb 2 2.7.4.0 (ksp.sarbian.com, 3.3 MB)
 * TriggerAu Flags v2.9.3.0 (github.com, 297.0 KB)
 * Module Manager 3.0.7 (ksp.sarbian.com, 47.4 KB)

Downloading "https://github.com/Boris-Barboris/AtmosphereAutopilot/releases/download/v1.5.11/AtmosphereAutopilot_1.5.11.zip"
Downloading "https://github.com/TriggerAu/KerbalAlarmClock/releases/download/v3.9.1.0/KerbalAlarmClock_3.9.1.0.zip"
Downloading "https://github.com/jrbudda/KerbalEngineer/releases/download/1.1.5.3/KerbalEngineer-1.1.5.3.zip"
Downloading "https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/17/artifact/MechJeb2-2.7.4.0.zip"
Downloading "https://github.com/TriggerAu/AlternateResourcePanel/releases/download/v2.9.3.0/KSPAlternateResourcePanel_2.9.3.0.zip"
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/142/artifact/ModuleManager-3.0.7.zip"
One or more downloads were unsuccessful:

Error downloading AtmosphereAutopilot v1.5.11: An exception occurred during a WebClient request.
Error downloading KerbalAlarmClock v3.9.1.0: An exception occurred during a WebClient request.
Error downloading KerbalEngineerRedux 1.1.5.3: An exception occurred during a WebClient request.
Error downloading MechJeb2 2.7.4.0: An exception occurred during a WebClient request.
Error downloading TriggerAu-Flags v2.9.3.0: An exception occurred during a WebClient request.
Error downloading ModuleManager 3.0.7: An exception occurred during a WebClient request.

Error!
```

**Comment by HebaruSan** [comment]
Reproduction steps don't work (obviously). Does this happen every time for you?

**Comment by Hotel26** [comment]
Yes, every time.  (I just tried it again.)  But the Win7 machine downloads the same packages without a problem on the same network.  Probably an installation problem on Linux (since it wasn't easy).  I had the same problem as last time: https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1253-woomera/&do=findComment&comment=3340661

It did work in March on that machine.  But I'm not sure I'm doing it exactly the same way either.

**Comment by HebaruSan** [comment]
Thanks. If you have time, please try this test build to see if a more informative error appears:

- [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/2438196/ckan.zip)

(This is the change from #2528.)

**Comment by Hotel26** [comment]
One or more downloads were unsuccessful:

Error downloading AtmosphereAutopilot v1.5.11: Could not load type of field 'System.Net.HttpWebRequest:tlsProvider' (51) due to: Could not resolve type with token 01000045 (from typeref, class/assembly Mono.Security.Interface.MonoTlsProvider, Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756) assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Interface.MonoTlsProvider member:(null) signature:<none>
Error downloading ModuleManager 3.0.7: Could not load type of field 'System.Net.HttpWebRequest:tlsProvider' (51) due to: Could not resolve type with token 01000045 (from typeref, class/assembly Mono.Security.Interface.MonoTlsProvider, Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756) assembly:Mono.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756 type:Mono.Security.Interface.MonoTlsProvider member:(null) signature:<none>

**Comment by HebaruSan** [comment]
Cool! Googling that error turns up some clues...

https://oxidemod.org/threads/could-not-load-type-of-field-system-net-httpwebrequest-tlsprovider-outdated-mono-security-dll.30762/

Looks like some part of your mono install is missing or outdated.

**Comment by Hotel26** [comment]
Thank you very much!  Upgraded versions of libmono-*security.  AOK.

**Comment by Hotel26** [comment]
Apologies for a long silence.  (Not my usual email account.)  I'll catch up
with this on the weekend....
