### ISSUE TITLE
Inconsistent checkbox behavior when pressing spacebar

### ISSUE THREAD

**Issue by antipin00** [KSP-CKAN/CKAN#2534]
Background
----------

**CKAN Version:** v1.25.3

**Operating System:** Windows (8.1, but looks like others as well)

Problem
-------
When selecting a mod from list, 'Installed' checkbox can be toggled by pressing spacebar. But if 'Installed' checkbox was clicked by mouse, then pressing spacebar toggles it 2 times (first when pressing down, second when releasing).
If there is also 'Update' checkbox available, then:
-If mod was selected by clicking outside 'Update' checkbox, pressing spacebar works as described above
-If mod was selected by clicking 'Update' checkbox, pressing spacebar toggles 'Installed' checkbox and releasing it toggles 'Update' checkbox

![clicks](https://user-images.githubusercontent.com/17460779/46639900-97017c00-cb71-11e8-8bf0-faaaf033290a.gif)
(on the gif I held spacebar for a fraction of second so there is a pause between pressing and releasing)

Probably caused by conflict between whatever toggles 'Installed' checkbox of selected mod when pressing spacebar and OS's toggling of selected checkbox using tab controls (note the dotted border).

**Comment by Gryffen1971** [comment]
The only time i can get this to happen is when i first start up CKAN and have not clicked on another Mod when i tap the spacebar once.
Once i click on another mod and press the tap the spacebar the check mark does not reappear once it is gone. This was done on Win10-Pro.

**Comment by HebaruSan** [comment]
Here's where we handle this keypress:

https://github.com/KSP-CKAN/CKAN/blob/fc0fa20a1d31319f75bd35a83da382f19d064d0b/GUI/MainModList.cs#L327-L339

**Comment by antipin00** [comment]
@Gryffen1971 well, when I launch CKAN and press spacebar without clicking anywhere it doesn't do anything at all (even though one of the mods is selected by default). But there's also no dotted border anywhere (pressing tab and then shift+tab suggests it should be around 'Manage mods' tab above 'Launch KSP' button), so... maybe something to do with newer Windows?

**Comment by Gryffen1971** [comment]
@HebaruSan Now that is quite possible indeed.
