### ISSUE TITLE
Setting OneCache to same location as local cache wipes all cached files

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2537]
Post #2535, on initial run, if user has used the fairly common trick of making local CKAN/download folders a link to a single folder and creates a similar link as the new default shared cached location, all cached files are deleted on first load of a KSP instance.

**Comment by politas** [comment]
A second launch does not appear to delete items newly cached.

**Comment by HebaruSan** [comment]
1. `MoveFrom` should be more cautious if possible, or stop deleting things at all
2. `MoveFrom` shouldn't be getting called on the initial run. That should only happen when the user changes the setting, so there may be some problem with the logic the first time the new code runs.
