### ISSUE TITLE
Rollback function?

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2550]
**CKAN Version:** 
1.25.3

**KSP Version:** 
1.4.5

**Operating System:** 
Linux 4.18.0-10-generic/Ubuntu 18.10 Cosmic Cuttlefish

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
negative

**What steps did you take in CKAN?**
Updated EER
====
So, I was wondering about this and found #1504 but the discussion ended with install dates (YEAH!)  and a history (MOAR YEAH!).

Has this been shelved or tossed?  Having a "Rollback" on each individual mode, as you do with "Reinstall", would be nice.  Delete the offending mod and install the previous version (which is in all likelihood still cached). (And, yes, I'm sure it's more complicated than that, i.e. what if it depends or is a dependency do we rollback the associated mods type stuff).

I bring this up because EER just updated to 0.1.3.1 and now my log is filled with Part.AddModule errors.  In order to rollback this install, Imma have to:
1 - close CKAN,
2 - delete EER,
3 - manually install EER 0.1.3,
4 - run CKAN.

(I was hoping a proper-like rollback could be accomplished by including:
 - check registry.json to verify proper version numbering (e.g. 0.1.3 vs 0.1.3.0),
 - modify installed-KSP_test.ckan to "rollback" to proper version ( 0.1.3),
But, y'all store that info somewhereselse because even doing that doesn't change the installed version number.)

**Comment by HebaruSan** [comment]
Can you uninstall that mod and then install the version you want by double clicking it as shown in #2364?

**Comment by 7ranceaddic7** [comment]
P.S. I had a nah-that's-not-possible-is-it thought about the version tab.  When I d-clicked on the light-green 0.1.3 it asked me if I wanted to install 0.1.3.

YEAH! ...

![screenshot from 2018-10-23 14-47-27](https://user-images.githubusercontent.com/4062616/47392884-abe22180-d6d2-11e8-8850-177ee174ef2a.png)

 crestfallen NOT.
![screenshot from 2018-10-23 14-51-08](https://user-images.githubusercontent.com/4062616/47393013-2f9c0e00-d6d3-11e8-966b-f58fbc255eda.png)

**Comment by HebaruSan** [comment]
Uninstall it first.

**Comment by 7ranceaddic7** [comment]
Rock on!!

**Comment by 7ranceaddic7** [comment]
Created a wiki page on this.

https://github.com/KSP-CKAN/CKAN/wiki/Version-Rollback

**Comment by DasSkelett** [comment]
Could we make it so that you don't need to deinstall the newer version before installing the desired version? That's a bit unintentional, at least since there is no prompt in CKAN stating that you should.

Furthermore you have do deinstall all the dependent mods too, and reinstall them again afterwards. That's not the fast and easy way.

**Comment by 7ranceaddic7** [comment]
You'd then have to coordinate dependencies with the entire process.

If you're lucky, what you suggest is easy - uninstall then install.

If you're not and there are multiple dependencies, then not so easy.  (Not out of the realm of programming but def intensive and prob not worth effort.)
