### ISSUE TITLE
add WM_CLASS in application

### ISSUE THREAD

**Issue by ccat3z** [KSP-CKAN/CKAN#2567]
Background
----------

**CKAN Version:** 

1.25.3

**Operating System:** 

Arch Linux

Feature request
-------

Mono application do not have a WM_CLASS property by default. It will make window managers on linux can't add the application's icon on task bar. Please add support for the WM_CLASS.

I found a sample on stackoverflow that maybe useful:
https://stackoverflow.com/questions/11453687/how-can-i-change-wm-class-for-a-winforms-application-on-linux
https://bitbucket.org/hindlemail/settingwmclass/

**Comment by HebaruSan** [comment]
What kind of value is it supposed to have?
