### ISSUE TITLE
RealChute parachutes system Mods

### ISSUE THREAD

**Issue by rorav** [KSP-CKAN/CKAN#2572]
RealChute Parachutes System Mod cancel all parachutes available in part list.
In my opinion there is an incompatibility with Italian version of KSP. It worked in standard english version.

Background
----------

**CKAN Version:1.25.3** 

**KSP Version:1.5.1.2335 ITA** 

**Operating System: WIN 10** 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** NO

Problem
-------

**What steps did you take in CKAN?**
Installed Real Chute Parachute System Mod

**What did you expect to happen?**

**What happened instead?**
All the parachutes parts disappear both in VAB/SPH. If I disinstall all the parts come back.
This happens after Italian language localization via STEAM.

**Comment by HebaruSan** [comment]
The CKAN team doesn't maintain mods. Try the mod's forum thread:

https://forum.kerbalspaceprogram.com/index.php?/topic/52931-15x-realchute-parachute-systems-v1471-161018/
