### ISSUE TITLE
CKAN is not detecting the right version of ksp

### ISSUE THREAD

**Issue by PRiD357** [KSP-CKAN/CKAN#2589]
Background
----------

**CKAN Version:** 1.25.4

**KSP Version:**  1.2

**Operating System:** Win 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------

**What steps did you take in CKAN?**
I habe ksp v1.2 installed

**What did you expect to happen?**

**What happened instead?**
 but CKAN is detecting ksp version 1.5

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
My copy of KSP 1.2 is still being detected as 1.2, so we'll need more information to diagnose this.

Please post the contents of the buildID.txt file in your KSP folder.

**Comment by PRiD357** [comment]
[config]
build id = 02335
2018.10.17 at 17:32:59 PDT
Branch: master
language = de-de

This is my build ID

**Comment by HebaruSan** [comment]
Yeah, you don't have KSP 1.2. This is a buildID.txt from that version:

```
build id = 01586
2016-10-11_12-44-44
Branch: master
```

You have KSP 1.5.1.

**Comment by PRiD357** [comment]
![ksp](https://user-images.githubusercontent.com/44844385/49238069-f2c4e480-f3ff-11e8-9fe3-16bda2ab3d4a.PNG)

But it shows v1.2

**Comment by PRiD357** [comment]
I'm on Steam. I verified the local cache. CKAN is still showing ksp v1.5

**Comment by PRiD357** [comment]
I also reinstalled ksp in Steam. CKAN is still showing v1.5

**Comment by HebaruSan** [comment]
Is this game folder still being managed by steam, or did you copy it elsewhere? Verifying cache won't do anything for a game folder copied out of the steam library.

**Comment by PRiD357** [comment]
It is still being managed by Steam

**Comment by HebaruSan** [comment]
I just opted into 1.2.2 on steam and this is the buildID.txt it gave me:

```
build id = 01622
2016-12-06_07-56-46
Branch: master
```

And CKAN correctly detects it as 1.2.2.

Whatever happened on your system, you have a buildID.txt file from KSP 1.5.1. If the rest of your game files are actually from 1.2.2, then you've somehow mixed files from multiple different game versions. To get CKAN to detect 1.2.2, you'll need to fix that.

**Comment by PRiD357** [comment]
How do I know if the rest is 1.2

**Comment by HebaruSan** [comment]
Your screenshot suggests you have some 1.2.2 files and some 1.5.1 files:

![image](https://user-images.githubusercontent.com/1559108/49240878-ede63d80-f3cb-11e8-993d-98d960a78160.png)

There was never any such valid game version as "1.2.2.2335". This is a mixture of 1.2.2.1622 and 1.5.1.2335. So KSP itself is confused about which version you have.

**Comment by PRiD357** [comment]
OK.How can I fix that ? I already reinstalled KSP multiole times

**Comment by HebaruSan** [comment]
That's really a question for valve/steam support rather than the CKAN dev team, but I suppose if it was me, I would uninstall and then manually make sure that all the game files were deleted before reinstalling. Maybe steam is leaving that file behind for some reason.
