### ISSUE TITLE
Support github "source releases"

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#259]
It's common for many mods to have downloads on Github, but wihout asset files attached. These expect the user to grab the zip of the entire release directory itself, and Github automaticaly prepends files inside with a path and version, eg: "MyModIsGreat-v1.1.1/GameData/MyModIsGreat".

These are a pain for the indexer, because the top-level path changes every time. However it *is* predictable from the repo name and release.

I suggest we provide a token `#/ckan/github/:user/:repo/src` which indicates we should download the source of a release, rather than any attached asset file. The `/src` is important, because it means we won't accidentally download the source of something which *should* have an asset file, but doesn't.

This will almost certainly require a path stripping stanza or other manipulator to traverse over the top level directory, but that will be for another ticket.

**Comment by pjf** [comment]
re-opening after repo merge

**Comment by dbent** [comment]
Implemented in #1587

**Comment by plague006** [comment]
> Implemented in #1587
