### ISSUE TITLE
nothing happens as CKAN tries to update repositories

### ISSUE THREAD

**Issue by seedofcheif** [KSP-CKAN/CKAN#2603]
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.5.1
**Operating System:** 
windows 8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
no

Problem
-------

**What steps did you take in CKAN?**
i downloaded a new version of KSP and a new version of CKAN and opened CKAN as instructed and assigned it to the buildID64 in the KSP folder and let it update its repositories

**What did you expect to happen?**
CKAN would update its repositories within a few minutes

**What happened instead?**
CKAN said it was been updating its repositories for 10 minutes or so, i tried to close and reopen the file however it would not respond to my attempts to do so and i had to use task manager to close CKAN. after havinf done so i noticed no change in the issue and it is continuing to attempt to update as i type this.

it should be noted that it says "repositories successfully updated in the lower left corner of the window despite contradicting this everywhere else

**Screenshots:**

![image](https://user-images.githubusercontent.com/45648389/49561731-adfcea00-f8e6-11e8-942b-273d82d6119f.png)

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
I tried this, and got this prompt once it finished updating:

![image](https://user-images.githubusercontent.com/1559108/49620638-742ff000-f987-11e8-9cc9-210b9b467b1e.png)

Look around your desktop and see if a version of that popup is hiding behind a window somewhere.
