### ISSUE TITLE
CKAN installs recommendations even if told otherwise on "Audit recommendations"

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2604]
Background
----------
**CKAN Version:** 
1.25.4

**Operating System:** 
Linux - Kubuntu 18.04.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Nope

Problem
-------

**What steps did you take in CKAN?**
1. Have any mod with recommendations installed (in my example RasterProp Monitor)
1. Select any not installed mod in mod list (not necessary for this issue, see down below)
2. Go to File > Audit recommendations
3. Select any of the suggestions **which itself has recommendations** (in my example SCANsat, shows recursion problem) and continue
4. **Deselect the recommendation** (In my example Contract Configurator) and continue
5. See that, even if you deselected it, the recommendation (Contract Configurator) is installed, **as well as a recommendation of the recommendation** (technically of another recommendation) (Waypoint Manager), which you never got to choose if you want to install it or not.

**What did you expect to happen?**
After you deselect the recommendation, it shouldn't get installed.
Changeset is saved.

**What happened instead?**
It was installed, and a recommendation of this recommended mod as well.
Changeset was not saved.

---

It seems that CKAN skips the recommendation evaluation (recursively) if you go over File > Audit recommendations instead of the Apply Changes button.
Furthermore, the in step 2 install-marked mod is unmarked again, so the changeset is not saved.

~~I might look myself into this bug tomorrow.~~ HebaruSan was faster.

**Comment by HebaruSan** [comment]
I think it's because I used `DefaultOpts` to start the installation here:

https://github.com/KSP-CKAN/CKAN/blob/7413c232f2ff7f58692617ae7c3cfa12551a7f6f/GUI/MainRecommendations.cs#L339

This sets `with_recommends`:

https://github.com/KSP-CKAN/CKAN/blob/7413c232f2ff7f58692617ae7c3cfa12551a7f6f/Core/Relationships/RelationshipResolver.cs#L190-L202

Normal installation uses this:

https://github.com/KSP-CKAN/CKAN/blob/7413c232f2ff7f58692617ae7c3cfa12551a7f6f/GUI/MainChangeset.cs#L122-L123

It'd be nice if there was an alternative to `DefaultOpts` that actually made sense to use...

**Comment by DasSkelett** [comment]
Ha! I forgot to write something in the issue, added now:
If you have a not empty changeset when auditing and installing recommendations, it is lost.
We have basically two options:
1. Apply the preselected changeset together with the recommendations install
2. Or save the changeset, "create a new one" (clear it, as it happens now) and reload the saved changeset after the process is complete.

**Comment by HebaruSan** [comment]
I guess my question is, what would be the user intention behind doing that? If they intend to install the change set, I would think they would do that before messing with Audit recommendations.

Maybe we should disable the Audit recommendations menu option when there's a change set, similar to how the apply changes button is disabled when there isn't one. That way this scenario wouldn't be possible.

**Comment by DasSkelett** [comment]
That's the 3rd option :)
It might really be a bit unrealistic. I noticed it during testing, where I went full QA.
In normal circumstances a user will probably act as you stated. So disabling the option might be the best choice.

**Comment by HebaruSan** [comment]
OK, third option added to the fix PR. We can change it later if someone presents a compelling case.
