### ISSUE TITLE
CKAN not updating compatible mod

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2620]
Background
----------

**CKAN Version: 1.25.4** 

**KSP Version: 1.5.1.2335** 

**Operating System: Windows 10** 

Problem
-------
During updating my career game to 1.5.1, I came across this:

SXTContinued has this:

```
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 5,
    "PATCH": 1
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 5,
    "PATCH": 1
  }
```
and this is recognized properly by AVC.  However, for some reason, CKAN is not recognizing this mod as 1.5.1 compatible, and is refusing to update the mod.
I looked at the meta data, and it looks correct

**Comment by HebaruSan** [comment]
Looks fine:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/SXTContinued/SXTContinued-1-0.3.24.2.ckan

What actual problem are you having?

**Comment by linuxgurugamer** [comment]
Starting up CKAN, installed version is 1:03.23.7, latest version is 1:03.24.2
This should be marked as update available, but doesnt.  See this image
![ckan_2018-12-21_20-42-32](https://user-images.githubusercontent.com/1630166/50369307-27404200-0561-11e9-943d-17bdbb424c68.png)

**Comment by HebaruSan** [comment]
Weird, I'm not able to reproduce that.

![image](https://user-images.githubusercontent.com/1559108/50369508-e0694100-058e-11e9-8391-0926facb4b57.png)

What's in your change set in your screenshot (i.e., what do you get if you click Apply changes?)?
