### ISSUE TITLE
KSP_VERSION in the GUI

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2621]
Active ksp is 1.6.0. Let say we have two mods:
```
1) ksp_ver: 1.6.0 ksp_min: 1.2.2, ksp_max: 1.9.9
2) ksp_ver: 1.2.2 ksp_min: 1.2.2, ksp_max: 1.9.9
```
Most likely, the second one was created long time ago, creator thought what it is for any future version, and they haven't touched it since 1.2.2,
but the first one, most likely, was tested for working in 1.6.0.

Good idea to know this info — another column in the Versions tab — "Target KSP Version"

**Comment by HebaruSan** [comment]
No such thing in KSP metadata. ksp_version doesn't co-exist with ksp_version_min or ksp_version_max.

**Comment by yalov** [comment]
What do you mean? 
Many .version files have all  "KSP_VERSION",  "KSP_VERSION_MIN",  "KSP_VERSION_MAX"

**Comment by HebaruSan** [comment]
KSP-AVC is not the same as CKAN.
KSP-AVC has what you describe (in fact requires it if you want to use min/max and interpret the spec strictly).
CKAN does not.

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#ksp_version_min

> ksp_version_min
The minimum version of KSP the mod requires to operate correctly. Same format as ksp_version. **It is an error to include both this and the ksp_version field.**

> ksp_version_max
The maximum version of KSP the mod requires to operate correctly. Same format as ksp_version. **It is an error to include both this and the ksp_version field.**

**Comment by politas** [comment]
Several of our sources for version info have this distinction, so it might be good to add it.

**Comment by Sinomen** [comment]
Recently couple of mods having "KSP_VERSION" have been updated their CKAN info to "KSP_VERSION_MIN" and "KSP_VERSION_MAX" instead, I'd think this issue is related.

https://github.com/KSP-CKAN/CKAN-meta/pull/2238/files

**Comment by HebaruSan** [comment]
As noted, this request does not reflect how CKAN metadata works. Making it work this way would make things much more confusing. Closing.
