### ISSUE TITLE
meta data has wrong KSP versoin

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2629]
In this metadata (which is new, was created today after an update):

[(https://github.com/KSP-CKAN/CKAN-meta/blob/master/RaginCaucasian/RaginCaucasian-1.4.4.1.ckan)]

It says the KSP version is 1.6, yet the .version file has this data, which causes CKAN to not show it as compatible:

```
{
  "NAME": "Mk2.5 Spaceplane Parts",
  "URL": "http://ksp.spacetux.net/avc/Mk2.5Spaceplane",
  "DOWNLOAD": "https://github.com/linuxgurugamer/Mk2.5_Spaceplane_Parts/releases",
  "GITHUB": {
    "USERNAME": "linuxgurugamer",
    "REPOSITORY": "Mk2.5_Spaceplane_Parts"
  },
  "VERSION": {
    "MAJOR": 1,
    "MINOR": 4,
    "PATCH": 4,
    "BUILD": 1
  },
  "KSP_VERSION": {
    "MAJOR": 1,
    "MINOR": 4,
    "PATCH": 1
  },
  "KSP_VERSION_MIN": {
    "MAJOR": 1,
    "MINOR": 4,
    "PATCH": 1
  }
}

```

**Comment by HebaruSan** [comment]
It's getting 1.6 from SpaceDock, and there's no $vref so the .version file is ignored.

![image](https://user-images.githubusercontent.com/1559108/50564780-87677e80-0ced-11e9-9648-3ea38821f8a5.png)
