### ISSUE TITLE
HyperEdit is compatible with KSP 1.6 but CKAN shows it as compatible with 1.4.9

### ISSUE THREAD

**Issue by shadownetdev1** [KSP-CKAN/CKAN#2631]
Background
----------

**CKAN Version:** 1.6.0.2395

**KSP Version:** 1.6.*

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes. Custom parts and I installed HyperEdit

Problem
-------

HyperEdit is compatible with KSP 1.6 but CKAN shows it as compatible with 1.4.9
See: https://forum.kerbalspaceprogram.com/index.php?/topic/34785-16-hyperedit-v158-july-10-2018-cheat-teleporter-orbitplanet-editor-more/

**What steps did you take in CKAN?**

**What did you expect to happen?**

**What happened instead?**

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by DasSkelett** [comment]
It's due to ckan is getting the compatible versions out of the avc .version file of HypeEdit, and its ksp_version_max is still set to `1.4.99`.

**Comment by HebaruSan** [comment]
Created Ezriilc/HyperEdit#65 to try to get the online version file updated.

**Comment by HebaruSan** [comment]
That PR got merged and the metadata should be good now. Thanks for pointing out this issue.

https://github.com/KSP-CKAN/CKAN-meta/commit/cc6bab5b001c6d296b6a193d0f5f5ad3e147cffd#diff-e6194afe951154a3c0c272d3a42884a3
