### ISSUE TITLE
Bugs in the console UI

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2633]
Background
----------

**CKAN Version:** 
1.25.4

**Operating System:** 
Windows 10

**Keyboard layout:** 
German QWERTZ without numpad

Problem
-------
Found some bugs:

First, key issue again: On a German QWERTZ keyboard without numpad, the +-key is not working to install mods:
See: (left to the Enter key)
<p><a href="https://commons.wikimedia.org/wiki/File:KB_Germany.svg#/media/File:KB_Germany.svg"><img src="https://upload.wikimedia.org/wikipedia/commons/3/36/KB_Germany.svg" alt="KB Germany.svg" width="640" height="213"></a><br><a href="http://creativecommons.org/licenses/by-sa/3.0/" title="Creative Commons Attribution-Share Alike 3.0">CC BY-SA 3.0</a>, <a href="https://commons.wikimedia.org/w/index.php?curid=1058095">Link</a></p>

key data:
```
Key: OemPlus
KeyChar: 0x2b
Modifiers: 0
```

---
Second, CTRL-F is not working on Windows (10) in command line if `Enable CTRL shortcuts` (or something like this, only have the exact wording in German) is activated, which is by default.
I think this applies for all common CTRL shortcuts (like ctrl-c, ctrl-v, ctrl-a...) which have an assigned action in the cmdline.
Don't know if there's any way to circumvent this. Maybe advise the user to deactivate it on launch.

---
~Also, I think it would be nice to have the website of a mod linked in the info section, maybe together with a keyboard shortcut to open it in the browser.~

**Comment by HebaruSan** [comment]
The web site links are in the F10 menu of the mod info screen:

![image](https://user-images.githubusercontent.com/1559108/50732429-0982f780-1173-11e9-919b-028f244327ff.png)

We already listen for `OemPlus` on Windows, but I guess you don't have to press shift with that keyboard?

https://github.com/KSP-CKAN/CKAN/blob/48d29f1313ea1b5261a8c4014031c1db076ab6a5/ConsoleUI/Toolkit/Keys.cs#L115-L119

I don't have Windows 10, but you can still tab to the search field even if your terminal is configured to not send Control key combinations.

**Comment by HebaruSan** [comment]
Are there any settings in this part of your registry that look related to "Enable new ctrl key shortcuts"?

![image](https://user-images.githubusercontent.com/1559108/50732735-78168400-1178-11e9-8d81-e84c0a206140.png)

**Comment by HebaruSan** [comment]
Sure, see #2635.
