### ISSUE TITLE
`ckan ksp fake` doesn't create all the subdirs it should

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2639]
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake FAKETEST1 fake1 1.2.2 none`

See #2627 for background on this command.

**What did you expect to happen?**

Based on [this exchange in #2627](https://github.com/KSP-CKAN/CKAN/pull/2627#discussion_r244621435), I expected [the folders created by the validation scripts](https://github.com/KSP-CKAN/xKAN-meta_testing/blob/36ccd470cde1c6a02a8a3fc267e2eddad2b6640c/NetKAN/build.sh#L54-L59) to be present. This would allow us to replace the dummy KSP creation functions in the validation scripts with much simpler calls to the new `ckan ksp fake` command.

**What happened instead?**

It created this (Windows `tree /f` command):

```
fake1
│   buildID.txt
│   buildID64.txt
│   readme.txt
│
├───CKAN
│   │   installed-FAKETEST1.ckan
│   │   registry.json
│   │
│   └───history
│           installed-FAKETEST1-2019-01-08_06-11-51.ckan
│
└───GameData
```

Several directories are missing (the ones linked in the exchanged mentioned above):

- `Ships`
- `Ships/VAB`
- `Ships/SPH`
- `Ships/@thumbs`
- `Ships/@thumbs/VAB`
- `Ships/@thumbs/SPH`

**Comment by DasSkelett** [comment]
Well, it really doesn't. Don't know what I saw back then that I thought they are created.

**Comment by DasSkelett** [comment]
So should i add this to `KSP.SetupCkanDirectories()` or my `KSPManager.FakeInstance()`? Is there a reason this is not in `KSP.SetupCkanDirectories()`?

**Comment by HebaruSan** [comment]
It's not in that function because these folders would already exist for a real instance. This problem is specific to creating fake instances.

**Comment by DasSkelett** [comment]
That makes sense. So it better sstays in FakeInstance
