### ISSUE TITLE
`ckan ksp fake` throws exception on two-piece version

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2640]
Background
----------

**CKAN Version:** 
421332c3abf30e3cf52adc81d6cd77743c2592d2

**KSP Version:** 
1.6

**Operating System:** 
Win7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**

Ran `ckan ksp fake FAKETEST3 fake3 1.2 none`

See #2627 for background on this command.

**What did you expect to happen?**

Either create a 1.2.0 install, or a 1.2.2 install, or tell me I need to be more specific

**What happened instead?**

`ArgumentOutOfRangeException` printed (twice). We shouldn't be printing an exception with stack trace here, because it's not some unexpected weird glitch, it's a known case of failed validation of user input. This should just print a simple message explaining why we failed to create the fake instance.

Aside from that, the message itself is fairly baffling. If I was a novice user, I'm not sure I could figure out what I did wrong. The answer is that all parts of the MAJOR.MINOR.PATCH version info need to be filled in, but this only conveys that indirectly.

**CKAN error codes (if applicable):** 

```
237 [1] ERROR CKAN.CmdLine.KSP (null) - System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at CKAN.Versioning.KspVersion.FindKnownVersion()
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
   at CKAN.Versioning.KspVersion.FindKnownVersion()
   at CKAN.CmdLine.KSP.FakeNewKSPInstall(FakeOptions options)
Examples for valid version formats: 1.5.0 | 1.5.1 | 1.6.0.2395
```

**Comment by DasSkelett** [comment]
Okay, the double printing happens with other errors too, I'll change it.
Also going to adjust the the message on how the version should be formatted.

**Comment by HebaruSan** [comment]
One possibility is to print the several versions that might match what I meant (1.2.0, 1.2.1, 1.2.2) and tell the user to choose. Or if you wanted to get really fancy you could do a `User.RaiseSelectionDialog` and have them pick one.

**Comment by DasSkelett** [comment]
Didn't know we have a selection dialog, that's cool :D
