### ISSUE TITLE
CKAN KSP Texture Glitches? Uninstall Guide?

### ISSUE THREAD

**Issue by ThatAshGuy** [KSP-CKAN/CKAN#2644]
Background
----------

**CKAN Version:** 
v1.25.4 

**KSP Version:** 
Latest

**Operating System:** 
HP ENVY TS 15 Notebook PC

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Deleted all files within the download folder for CKAN in KSP Steam Version

Problem
-------

**What steps did you take in CKAN?**
Updating it to latest version.

**What did you expect to happen?**
For all models of the game itself to render properly ie textures 

**What happened instead?**
![help me](https://user-images.githubusercontent.com/25542604/50874118-7c5bcf00-140e-11e9-81b7-ea47c4dd826e.jpg)

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
The CKAN team doesn't fix in-game bugs. Try submitting this to the bug tracker for whichever texture mod you're using.

**Comment by ThatAshGuy** [comment]
@HebaruSan the thing is I don't have any texture mods. Would you happen to have a website or tutorial on how to uninstall CKAN?

**Comment by DasSkelett** [comment]
Since you have installed KSP via Steam, try to validate your installation. There are multiple reports of broken installs after the 1.6 update.
