### ISSUE TITLE
Can't scroll the modlist if it's not selected on Linux

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2651]
Background
----------

**CKAN Version:** 
1.25.4

**Operating System:** 
Kubuntu 18.04.1

Problem
-------

**What steps did you take in CKAN?**
1) Open it up
2) Move your mouse over the mod list but don't select a mod 
3) Scroll up or down

**What did you expect to happen?**
You can scroll through the mod list.

**What happened instead?**
You can't, the mod list doesn't move.
Also happens if you "deselect" the mod list (click anywhere else in the program)

Only affects Linux (and maybe MacOS?), not Windows.

Was initially fixed in #1584, but doesn't seem to work anymore.

**Comment by HebaruSan** [comment]
I've noticed the mod name label showing a highlight on load. Maybe focus is going to those controls?

**Comment by DasSkelett** [comment]
In the metadata tab? Then maybe it's related to #2610 ?

**Comment by HebaruSan** [comment]
I tried setting `.TabStop=false` for all of those and it made no difference, so I'm ruling out that hypothesis.
