### ISSUE TITLE
install from .ckan does not install all mods

### ISSUE THREAD

**Issue by RimePendragon** [KSP-CKAN/CKAN#2652]
Background
----------

**CKAN Version:** 1.25.4

**KSP Version:** 1.6.1

**Operating System:** Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**  No

Problem
-------

**What steps did you take in CKAN?**
I exported all my mods installed in KSP 1.6.0 and used "install from .ckan" to install them in a fresh KSP 1.6.1 install. I have set 1.4, 1.5 and 1.6 as compatible versions. 

**What did you expect to happen?**
All mods in the ckan file to be installed.

**What happened instead?**
75% of the mods install fine but the rest are not installed. No error reports, nothing.

The .ckan file: [KSP1_6.zip](https://github.com/KSP-CKAN/CKAN/files/2746023/KSP1_6.zip)

**Comment by HebaruSan** [comment]
Which mods aren't installed? Seems to work OK for me...

**Comment by HebaruSan** [comment]
- BetterBurnTime
- CactEyeCommunity
- CommunityPartsTitles
- DMagicOrbitalScience
- EasyVesselSwitch
- EVAStruts
- EVATransfer
- FelineUtilityRovers
- FinalFrontier
- FlexibleDocking
- HideEmptyTechNodes
- JX2Antenna
- KerbalAlarmClock
- KerbalEngineerRedux
- KerbnetController
- kOS
- ManeuverNodeEvolved
- MechJeb2
- NavBallAdjustor
- NavballDockAlignIndCE
- ScienceRelay
- ShipManifest
- SmokeScreen
- SpacetuxSA
- SpeedUnitAnnex
- Targetron
- TarsierSpaceTechnologyWithGalaxies
- TextureReplacer
- Toolbar
- TrackingStationEvolved
- TransferWindowPlanner
- TriggerAu-Flags
- VaporVent
- WaypointManager
- ZeroMiniAVC

**Comment by HebaruSan** [comment]
This might be a visual problem with the mod list. After cancelling out of another installation, it now shows all those things as installed!

@RimePendragon, can you confirm whether the mods that seem to be missing for you are actually installed in GameData?

**Comment by RimePendragon** [comment]
They are not installed in GameData.

This is an export of my mods after installing from .ckan: 
[KSP1_6_1.zip](https://github.com/KSP-CKAN/CKAN/files/2746523/KSP1_6_1.zip)

And this is a listing of my GameData:
[GameData.txt](https://github.com/KSP-CKAN/CKAN/files/2746528/GameData.txt)

**Comment by HebaruSan** [comment]
Installing from the command line (`ckan install -c KSP1_6.ckan`) seems to not have this problem, so that's a clue and a possible workaround...

**Comment by HebaruSan** [comment]
Possible cause:

https://github.com/KSP-CKAN/CKAN/blob/1bbd2fddcc9fc3663a62db90835d4d2d04ae2708/GUI/MainInstall.cs#L30

The provided .ckan file contains all of the modules in a `"recommends"` list, and the above line tells the installer not to install recommendations. Changing it to a `"depends"` list causes all the modules to install. Not sure why it installs *anything* though. Presumably we use `"recommends"` to prevent the install from failing if some of the mods aren't compatible.

**Comment by HebaruSan** [comment]
That line is fine because the installer isn't supposed to auto-install these; GUI is supposed to prompt the user. And it's filtering them out with a weird exception:

```
Can't install installed-KSP1_6, ScienceRelay: Sequence contains no elements
Can't install installed-KSP1_6, TextureReplacer: Sequence contains no elements
Can't install installed-KSP1_6, Scatterer-config: Sequence contains no elements
Can't install installed-KSP1_6, Scatterer-sunflare: Sequence contains no elements
Can't install installed-KSP1_6, DynamicBatteryStorage: Sequence contains no elements
Can't install installed-KSP1_6, NearFutureProps: Sequence contains no elements
Can't install installed-KSP1_6, NearFutureSolar-Core: Sequence contains no elements
Can't install installed-KSP1_6, FirespitterResourcesConfig: Sequence contains no elements
Can't install installed-KSP1_6, DMagicOrbitalScience: Sequence contains no elements
Can't install installed-KSP1_6, NavballDockAlignIndCE: Sequence contains no elements
```

**Comment by HebaruSan** [comment]
Thanks for the report! I think we have a fix figured out now in #2653, and in the meantime I would recommend one of the workarounds of either installing from the command line or editing the file to change "recommends" to "depends".

**Comment by RimePendragon** [comment]
ok, thanks.

**Comment by Twitchi1003** [comment]
Hey i know this is closed.. but its been so for about a month and I have been waiting on a release with this fix in it.. sharing screenshot of my mods list is a work around but kinda sucks when I am supposed to just be able to share a file with my friends
This is a long winded way of asking when a new version will be released?
