### ISSUE TITLE
Display "AD" mods with Filter (Installed)

### ISSUE THREAD

**Issue by TonkaCrash** [KSP-CKAN/CKAN#2667]
Manually installed mods should be listed with the list of CKAN installed mods in Filter (Installed). I believe this was the behavior at one point. I currently only see AD mods on Filters that show mods that have not been installed. 

I've had the case where I installed a mod before it was listed in CKAN and then go very out of date when I forgot it was in a manual mode because the AD mods aren't listed with the other installed mods and only with the lists of thousands of uninstalled mods.

**Comment by HebaruSan** [comment]
Thanks for the report. I think this changed unintentionally in #2514; before that, it used `Registry.IsInstalled`, which does return true for AD mods:

https://github.com/KSP-CKAN/CKAN/blob/61467e9d69f551dacbecb57c5b33f93db337d85f/GUI/GUIMod.cs#L74

Makes sense to fix.
