### ISSUE TITLE
Trying to change a mod from AD to installed

### ISSUE THREAD

**Issue by MikeLyno** [KSP-CKAN/CKAN#2672]
Background
----------

**CKAN Version:** 
1.25.4

**KSP Version:** 
1.6.1

**Operating System:** 
Windows 10 Pro x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Yes. Have Module Manager installed manually (it's the only mod I do have manually installed). Shows as AD in ckan. I wanted to try to get it installed through ckan like all my other mods are and get rid of the AD. 

Problem
----------

**What steps did you take in CKAN?**

1. Installed mods depending on ModuleManager (manually installed)
2. Deleted ModuleManager in ksp gamedata folder
3. Went back to ckan and refreshed it and AD was gone and the box was there
4. I checked it and clicked to apply changes

**What did you expect to happen?**

Get Module Manager installed through ckan without having to uninstall other mods

**What happened instead?**

Then got a list of about 25 of my mods to be uninstalled to get Module Manager installed. Needless to say I'm not going to do that.

**Screenshots:**

![after clicking install box](https://user-images.githubusercontent.com/38197242/52023342-950d5100-24b1-11e9-9927-28a34bb7dbd9.JPG)

**Comment by MikeLyno** [comment]
![after clicking install box](https://user-images.githubusercontent.com/38197242/52023342-950d5100-24b1-11e9-9927-28a34bb7dbd9.JPG)

**Comment by HebaruSan** [comment]
Thanks!
Confirmed that those all depend on ModuleManager. DockingCamKURS is for KSP 1.3.1, the rest are for 1.4 or later.

**Comment by HebaruSan** [comment]
OK, I've set this up for testing and reproduced it. The good news is that I think I found a workaround; it seems the command line interface is immune to this problem, so you can run:

`ckan install modulemanager`

... and it should work, or at least it did for me. And that should help us figure out what's wrong in GUI.

In case you're not familiar with command line stuff, here's the general idea for Windows:

1. Start -> Run
2. Cmd
3. `cd` to wherever your `ckan.exe` file is
4. `ckan install modulemanager`

**Comment by MikeLyno** [comment]
So that means only way to change Module Manager from AD to a ckan install is to uninstall those mods first and then reinstall them after installing Module Manager? No way I'm doing that. I guess I will just leave Module Manager as a manual install outside of ckan.

**Comment by HebaruSan** [comment]
Yeah, Windows makes that a bit of a pain. Try:

```
E:
cd "\Steam\SteamApps\common\Kerbal Space Program\CKAN"
```

**Comment by MikeLyno** [comment]
Here is where I'm stuck
![module manager cmd](https://user-images.githubusercontent.com/38197242/52029022-5afa7a00-24c6-11e9-8f02-12fda869e431.JPG)

**Comment by HebaruSan** [comment]
Try what I said in my previous comment. With the quotes and everything.

**Comment by DasSkelett** [comment]
Go the easy way: Navigate to your CKAN folder in the Explorer, click in the address/path bar on the top so that the text is selected and type 'cmd' and press enter. Opens a command prompt right in the folder where you currently are.

**Comment by MikeLyno** [comment]
![module manager cmd 2](https://user-images.githubusercontent.com/38197242/52029300-7ade6d80-24c7-11e9-9d49-37add5f5de7a.JPG)

**Comment by HebaruSan** [comment]
OK, that means your `ckan.exe` file isn't in the folder you said it was in.

When you downloaded it, where did you save it?

**Comment by HebaruSan** [comment]
Sorry, my previous comment was wrong so I deleted it.
Do you select your game instance every time you run CKAN?

**Comment by HebaruSan** [comment]
Try this:

`ckan install modulemanager --kspdir ..`

**Comment by MikeLyno** [comment]
That friggin worked dude! Thank you so much for working with my dumb ass.
