### ISSUE TITLE
Abstract in Mod Info pane is not wrapping

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2678]
Background
----------

**CKAN version**
1.25.5 current HEAD

**Operating System:** 
Ubuntu Mate 18.04

Problem
-------

**Screenshots:**

![image](https://user-images.githubusercontent.com/2109967/52171441-604f1180-27b1-11e9-9d31-3620d9bc37db.png)

As can be seen, the Name field wraps, but the Description does not. We've got lots of quite long descriptions, and it would be good to see the complete description.

**Comment by HebaruSan** [comment]
Odd, it wraps for me:

![image](https://user-images.githubusercontent.com/1559108/52171474-4ebf2880-2723-11e9-82de-4ec7bd263c1d.png)

**Comment by politas** [comment]
Well, that's weird.

**Comment by HebaruSan** [comment]
(We have a spot for both the abstract and the description here, and this mod only has an abstract.)

**Comment by politas** [comment]
So, I wonder what the difference between our setups is that means I am not seeing everything correctly?

**Comment by DasSkelett** [comment]
It works for me too, on Mono 5.18.0.240 (Kubuntu 18.10)

**Comment by HebaruSan** [comment]
I also have Mono 5.18.0.240, on Ubuntu 18.10.

@politas, is the problem completely consistent for you? I thought there might be a trick to making it happen, but clicking many different things in the UI did not seem to disrupt it.

**Comment by politas** [comment]
I don't have my computer working at the moment, so I can't investigate further at this time.

**Comment by politas** [comment]
With my new build, all is working, so it was probably something b0rked in my Mono setup.
