### ISSUE TITLE
Mod info panel versions tab: Column header invisible

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2684]
Background
----------

**CKAN Version:** 
Current HEAD (62da77df)
and current release (v1.25.4)

**Operating System:** 
Kubuntu 18.04.1 -> mono 5.18.0.240

Problem
-------

**What steps did you take in CKAN?**
~~1) Open "Metadata" tab in mod info panel (or any one besides the "Versions" tab)
2) Select a mod (don't keep the mod selected which is selected at startup, a different one!)
3) Change to "Versions" tab~~
1) Select any mod **after startup**
2) Open "Versions" tab in the mod info panel -> everything is still fine
3) Change to another tab
4) Select different mod
5) Change back to "Versions" tab

**What did you expect to happen?**
See the column headers.

**What happened instead?**
invisible and unclickable column headers
![ckan1](https://user-images.githubusercontent.com/28812678/52887227-403b2d00-3177-11e9-9813-67dff54cf595.png)

If you keep the versions tab **open** and select a different mod, the column headers reappear.
![ckan2](https://user-images.githubusercontent.com/28812678/52887386-cce5eb00-3177-11e9-9a06-8f742d2d6288.png)

**Comment by HebaruSan** [comment]
Interesting. I think I've also seen this happen with the change set list.

When you click that tabstrip, we don't do anything special for Versions or manipulate Visible properties or anything like that:

https://github.com/KSP-CKAN/CKAN/blob/62da77dfe9f8096e9adf98c2849afa782c68bc2b/GUI/MainModInfo.cs#L383-L390

Probably a Mono bug.

**Comment by DasSkelett** [comment]
Thought of that too. I'll look into the mono code once again :+1:

**Comment by HebaruSan** [comment]
If I call `VersionsListView.EndUpdate()` when activating the versions tab, it seems to fix the problem, suggesting that the problem is an unmatched `BeginUpdate` call. However, there are none of those in `ListView`.

There is a `BeginUpdate`/`EndUpdate` pair in `AddRange`, though, which we call in `MainAllModVersions.SelectedModule`, so maybe that code runs on the wrong thread? Except that wrapping it in a `Util.Invoke` call *doesn't* fix the problem...

**Comment by HebaruSan** [comment]
Also still happens if the `AddRange` call is replaced with a sequence of calls to `Add`. The only other call to `BeginUpdate` is in `AutoResizeColumns`.
