### ISSUE TITLE
Feature Request: Customise columns in GUI Modlist

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2687]
Background
----------
Several changes have added columns to the GUI modlist, providing more information for users. But some users have limited screen real estate and may not be interested in seeing all the new columns (perhaps even some of the older, original columns).

Proposal
---------
CKAN should have a way to customise the columns that appear in the modlist, turning specific columns on or off. We could then make use of this feature to activate certain columns only when there is data (such as the Update/Replace columns)

**Comment by DasSkelett** [comment]
I'd take that one.
