### ISSUE TITLE
Copy / drag&drop for mod links (Feature Request)

### ISSUE THREAD

**Issue by JebsSY** [KSP-CKAN/CKAN#2698]
Hello,

would it be possible to add a "right click, copy", a "mark" or a "drag & drop" feature to the links in the mod description?
Background: On one of my systems I don't want to open KSP links in my default browser. I have a second browser open, but it's impossible to open the link somehow in the second browser. In the end I always end up googling the link, even it's direct in front of me.

The really only thing you can do is click the link and this fires up the default browser.
Usually (with other applications) I can just drag a link and drop it in the tab bar of the second browser and it opens fine.
If this is to much work, would it maybe be possible to add a right click "copy" or at least make the link markable with the mouse, so that CTRL-C sould work?

Best Regards
Jebs_SY

PS: Not sure how to mark this as feature request?!

**Comment by HebaruSan** [comment]
Confirmed that the text cannot be selected.

![image](https://user-images.githubusercontent.com/1559108/54478188-82d74000-47dd-11e9-8771-e7f6ad4865bf.png)

Would also be nice to improve handling of "N/A", which should not be a link.

**Comment by JebsSY** [comment]
@HebaruSan 
Wow, that was fast. Thank you very much! :-)
