### ISSUE TITLE
form.checkbox breaks down when is_required=True

### ISSUE THREAD

**Issue by filipporemonato** [KSP-CKAN/CKAN#2700]
Background
----------

**CKAN Version:** 2.8.2

**KSP Version:** 

**Operating System:** Linux Ubuntu

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**  No

Problem
-------

**What steps did you take in CKAN?**
Wanted to extend the "new user" registration form with a checkbox for "I have read and agree to the user's licence". For this, I made a plugin that modifies the `user/new_user_form.html` template, and added the chekbox using the macro `form.checkbox` command. The checkbox must be flagged as required, so I set `is_required=True`. This last thing makes the code crash when loading the page.

**What did you expect to happen?**
I expected to have a checkbox as an input field of the form which was required to submit the form.

**What happened instead?**
The code breaks down and crashes on page load. This is because `macros/form.html` calls a function `input_required()` when `is_required=True`, with
`{% if is_required %} {{ input_required() }} {% endif %}`
but such function is not defined anywhere. It seems like someone had an idea and forgot to implement it.

**Comment by HebaruSan** [comment]
I think you want this project: https://github.com/ckan/ckan

KSP-CKAN has no such functionality.

**Comment by filipporemonato** [comment]
That's strange, I have no idea how I landed up on this repo... I am positive I clicked on the link on CKAN's own webpage, but clearly something has gone wrong. Thanks for the redirect! Wish you a good continuation of your work.
