### ISSUE TITLE
broken homepage link in about dialog

### ISSUE THREAD

**Issue by mvconners** [KSP-CKAN/CKAN#2701]
The "Homepage" link under Help->About goes to ksp-ckan.org, which is an advertising redirect. This should probably be pointing to ksp-ckan.space instead (which redirects to the wiki as expected).

https://github.com/KSP-CKAN/CKAN/blob/542147ea543b81f692e08228cc2788756577ea0b/GUI/AboutDialog.cs#L36

https://github.com/KSP-CKAN/CKAN/blob/542147ea543b81f692e08228cc2788756577ea0b/debian/control.in#L7

https://github.com/KSP-CKAN/CKAN/blob/542147ea543b81f692e08228cc2788756577ea0b/Tests/GUI/GUIMod.cs#L65

https://github.com/KSP-CKAN/CKAN/blob/542147ea543b81f692e08228cc2788756577ea0b/Tests/GUI/GUIMod.cs#L71

**Comment by DasSkelett** [comment]
Oh yeah, I actually fixed that some time ago together with a little rework of the about dialog, but never did a PR because of a mono bug regarding link label formatting.

**Comment by HebaruSan** [comment]
There are a few other remaining references to the old domain; added to the OP.
