### ISSUE TITLE
[Feature] Alternative game command line option

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2706]
Along the lines of #1640 

I use CKAN almost exclusively, but recently had to do something different:

I'm now doing testing with a runtime debugger, which means I need a different command line.

What I'd like is a button which would allow an alternative command line.  I don't think it would be an issue if a config file would need to be edited to enable this.  As of now, I'm stuck with either changing the command line in CKAN, or starting the debug version using an alternative mechanism.  Neither is particularly great.

**Comment by linuxgurugamer** [comment]
Not really related to running a program or script after an install.  This issue isn't talking about an install, but just having multiple command lines
Possibly an option to have a secondary "Launch Game" button, only visible when an alternative command line is set up

**Comment by HebaruSan** [comment]
Yes, I understand that. "Somewhat related" does not mean it's an identical duplicate.
