### ISSUE TITLE
Is Baikonur (1.26.0) legit? 

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#2712]
Just asking as I see an update available which was released on the 1st of April... a few other programs I use offered 'updates' yesterday... anyway, wondering if there are any 'gotcha's present which might make it worth waiting for a 1.26.1 update or something.

Background

--------
**CKAN Version:** 1.26.0 Baikonur

**KSP Version:** Any, I guess

**Operating System:** Also any

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes

Problem
-------

**What steps did you take in CKAN?** Started it

**What did you expect to happen?** No update

**What happened instead?** An update was available

**Comment by DasSkelett** [comment]
Haha, that gave me a good laugh :smile: 
Unless @politas fooled me too, I don't know of any special presents.
Should be save to use (warranty void when discovering any bugs).
