### ISSUE TITLE
Installing specific mod version desyncs checkbox status

### ISSUE THREAD

**Issue by Blu3wolf** [KSP-CKAN/CKAN#2713]
Background
----------

**CKAN Version:**
1.26.0

**KSP Version:**
1.4.5

**Operating System:**
W7

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------

**What steps did you take in CKAN?**
Installed a specific version of a mod, which is older than the currently installed version, by double clicking that version from the version tab.

**What did you expect to happen?**
I expected the Installed checkbox to be ticked at the completion of the mod install. 

**What happened instead?**
After installing, the CKAN GUI returns automatically to the mod list, but the mod checkbox is unticked, as though the mod were now uninstalled or selected to be uninstalled.

The changelist still correctly does not list the mod to be uninstalled, and ticking the checkbox does not add the mod to be installed. Ticking the checkbox again DOES add the mod to be uninstalled.

**Comment by DasSkelett** [comment]
Can confirm the issue. The mod list doesn't update correctly, most likely related to #2669.

Thanks a lot for the report!

**Comment by HebaruSan** [comment]
Thanks for pinpointing this to installing a different version of an installed module. I had seen this checkbox desync thing happen, but I couldn't pin down exactly the steps that caused it. Knowing that made it easy to figure out the cause.
