### ISSUE TITLE
Window opens offscreen if previously closed while minimized

### ISSUE THREAD

**Issue by woodbyte** [KSP-CKAN/CKAN#2717]
Background
----------

**CKAN Version:** 
1.26.0

**KSP Version:** 
1.6.1

**Operating System:** 
Windows 10 Pro 1809

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Closed CKAN by right-clicking the tasbar icon while it was minimized.

**What did you expect to happen?**
For CKAN to close without issues.

**What happened instead?**
CKAN closes fine but on the next launch the window is nowhere to be seen and the maximize shortcut (Win+Up) does not work.

**Screenshots:**
GUIConfig.xml under Kerbal Space Program\CKAN looks like this when the issue occurs. Setting the highlighted values to 0 fixes the issue.

![Annotation 2019-04-04 171001](https://user-images.githubusercontent.com/4104564/55571010-8edb6100-56fc-11e9-8dc4-4f92aca9634d.png)
**CKAN error codes (if applicable):** 
None

**Comment by woodbyte** [comment]
Having looked at the referenced issue, I'll just add that in this case I am running on a single monitor and when the issue occurs the Taskbar preview is blank (it shows but all white, as if never rendered).

**Comment by DasSkelett** [comment]
The issues most likely are not connected in any way. I wanted to point @Smorfty to this thread, as his issue is likely the same as yours.

I can confirm the bug (but with a working taskbar preview), and have an assumption what's causing it:
When quitting CKAN, the current window position is saved. If it is minimized to tray at that moment, Windows probably reports the position as (-32000,-32000).

I am currently looking for a way not to save the position on closing if minimized, but instead save it the moment CKAN gets minimized to tray.

**Comment by Sabrewulf** [comment]
Reporting the same issue.

**Comment by DasSkelett** [comment]
Okay, am working on it.

**To make it clear for everyone affected with the issue:
If it already happened:
Open your GUIconfig.xml and change the two -32000 values to 0.**

**To keep the issue from happening for the time being:
Don't quit via the tray icon.**

**Comment by diveyez** [comment]
This happened when opening CKAN after KSP updated today.

**Comment by DasSkelett** [comment]
Did you also quit it via the tray icon when CKAN was minimized beforehand?

**Comment by ResinSmoker** [comment]
Was able to get it running...
The fix was as follows:
-Renamed GUIconfig.xml to GUIconfig-Old.xml and renamed the folder CKAN (E:\SteamLibrary\steamapps\common\Kerbal Space Program\) to CKAN-OLD.
-Restarted CKAN, waited for it to finish up then closed it out.
-Copied the newly created GUIconfig.xml to CKAN-OLD folder.
-Delete the new CKAN folder.
-Rename CKAN-OLD to CKAN.

**Comment by sotrans** [comment]
Had the same problem, glad i found this issue here.

**To bring the window immediately back to screen:** On Windows 10, hold shift while right-clicking on CKAN in the taskbar, then select "Maximize" from the context-menu.
