### ISSUE TITLE
Text cut off in info window

### ISSUE THREAD

**Issue by 4x4cheesecake** [KSP-CKAN/CKAN#2718]
Background
----------

**CKAN Version:** 
1.26.0

**KSP Version:** 
1.6.1

**Operating System:** 
Win 10 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------

**What steps did you take in CKAN?**
Launched CKAN and selected an "older" KSP install

**What did you expect to happen?**
(not relevant)

**What happened instead?**
CKAN displayed a warning/info window about some changed metadata but the text exceeds the window size and is cut off. The window is not resizeable.

**Screenshots:**

![grafik](https://user-images.githubusercontent.com/40007416/55574108-e1704980-570b-11e9-8e48-87eb196d8c30.png)

**Comment by DasSkelett** [comment]
Thanks for the report!
