### ISSUE TITLE
incompatible mod, even max ksp version listed as 1.6.1

### ISSUE THREAD

**Issue by randomguyingithub** [KSP-CKAN/CKAN#2720]
Background
----------

**CKAN Version:** 1.26.0

**KSP Version:** 1.6.1.2401

**Operating System:** Windows 10 Pro (64bit)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** : Yes, removed all mods manually before reinstall ckan after encountering the problem

Problem
-------

**What steps did you take in CKAN?**
trying to install avp by ticking texture first

**What did you expect to happen?**
successful installation 

**What happened instead?**
ckan thought it's not compatible, even the max ksp version states it's 1.6.1

**Screenshots:**
![image](https://user-images.githubusercontent.com/13596387/55607926-f0103c80-57af-11e9-968e-9751bc0b6cd9.png)
The error.
![image](https://user-images.githubusercontent.com/13596387/55607952-00281c00-57b0-11e9-8f7e-4b2500869027.png)
If you tick 1.4 in compatible ksp verisons, it shows up as compatible mod thus the mod can be successfully installed

----

**Comment by 4x4cheesecake** [comment]
Check the Relationships tab. AVP depends on EVE which isn't compatible with 1.6.1: 
![image](https://user-images.githubusercontent.com/40007416/55629667-0ae4b000-57b4-11e9-9cb4-42f9d1b8fc5b.png)
This also perfectly explains why AVP becomes compatible after setting 1.4 as a comnpatible KSP version.

**Comment by DasSkelett** [comment]
Yep, thanks @4x4cheesecake .
