### ISSUE TITLE
Cannot Remove Mod

### ISSUE THREAD

**Issue by diveyez** [KSP-CKAN/CKAN#2723]
Current CKAN
Current KSP

About to remove:

 * Astronomer's Visual Pack 1:3.7.4.0
 * Astronomer's Visual Pack-2k Textures v1.7
 * Environmental Visual Enhancements 2:EVE-1.4.2-2
Removing AstronomersVisualPack...
Removing AVP-2kTextures...
Removing EnvironmentalVisualEnhancements...
The following inconsistencies were found:
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/Atmosphere.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/CelestialShadows.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/CityLights.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/EVEManager.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/PartFX.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/PQSManager.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/ShaderLoader.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/Terrain.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/TextureConfig.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/Utils.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
* D:/SteamLibrary/steamapps/common/Kerbal Space Program/GameData/EnvironmentalVisualEnhancements/Plugins/_BuildManager.dll is registered to EnvironmentalVisualEnhancements but has not been removed!
Error during installation!
An unknown error occurred, please try again!

**Comment by DasSkelett** [comment]
Please fill out the questions of the template once again.

**Comment by HebaruSan** [comment]
Try exiting KSP. The files can't be deleted while they're in use on some platforms.
