### ISSUE TITLE
Waffle is shutting down

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2731]
https://waffle.io/closing-its-doors
Waffle is shutting down on May 16th.

They have a guide how to migrate to Github Projects: https://help.waffle.io/waffle-shutdown/migration-to-github-projects/migrate-to-github-projects.
Do we want to do this?

**Comment by Olympic1** [comment]
On my other organization we already did this last week, just needed to do some little adjustments. I wanted to do this here too, but apparently I'm not an admin.

**Comment by HebaruSan** [comment]
Removed Waffle from wiki:

https://github.com/KSP-CKAN/CKAN/wiki/Issues-workflow/_compare/d748834a528d8b6a40fa023a785e2ede5e80ad9d...2c1ed1c31c80d24af37c7b3dc82307978fac1fed

**Comment by politas** [comment]
Was anyone actually using the Waffle? I never really saw the value in it.

**Comment by HebaruSan** [comment]
I looked into it when I joined, but everything I wanted to do was easier with simple searches on GitHub.

**Comment by DasSkelett** [comment]
Neither did I. So anyone want to use GitHub Projetcs? Else I would say somebody can delete the Waffle board (or just let it "die" itself in two weeks), and I will close this issue.

**Comment by politas** [comment]
I'll take the ref out of the IRC topic.

**Comment by DasSkelett** [comment]
Waffle.io is now down.
I [removed the last mentions](https://github.com/KSP-CKAN/CKAN/commit/8eabff480cc7599803c73e0ee73d63bfa434b081) of Waffle that need removing, in CONTRIBUTING.md.

I'll close this issue now, it looks like no one really wants a replacement. If someone changes his mood one day, he can open a new issue.
