### ISSUE TITLE
Master Search box

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2736]
in addition to https://github.com/KSP-CKAN/CKAN/pull/2709 I propose to merge the search boxes to one, and to add checkboxes for backward ability to leave only one search type.
Search: [----------------]        [x] by name         [x] by author name          [x] by description

**Comment by HebaruSan** [comment]
Note that that isn't backwards compatible because it doesn't support combined searches using multiple boxes:

![image](https://user-images.githubusercontent.com/1559108/56448012-7a51b800-62fb-11e9-8977-1e342d8d6ac7.png)

... so we'd inevitably have somebody moaning about how we broke their work flow.

**Comment by yalov** [comment]
=)
Search: [----------------]      [x] by name     [x] by author name      [x] by description     [x] by LGG

or another way to settle this is supporting & and | relation:
linux&exten

**Comment by DasSkelett** [comment]
Should your first proposal be a dropdown selection box? We can go with a normal search text box then, like now.

The second one is too complex in my opinion. Users don't want to learn a complete search system just to search a mod in CKAN. Also I don't think an "Or |" relationship makes much sense here.

**Comment by yalov** [comment]
it is usual search text box, the same as now, but searching all fields at once.

Someone indeed may want to search mods by name and author, and I would prefer the name and the desc have one search box, so maybe something like this?

filter by name: [--------------]   [x] include by description                      filter by author: [-----------]

**Comment by DasSkelett** [comment]
Sorry, i was very unclear. I meant the last option "[x] by LGG"

**Comment by yalov** [comment]
it is a checkbox (and a joke) because LGG is the only modder, that have enough mods for inner search

**Comment by DasSkelett** [comment]
Okay, didn't get it...
I can support this compromise:
``` 
filter by name: [--------]   [x] also search description and abstract        filter by author: [--------]
```
I don't think there's no workflow broken, but it would simplify the search.

**Comment by HebaruSan** [comment]
As a case study, GMail has a plain search box with a dropdown icon:

![image](https://user-images.githubusercontent.com/1559108/57077193-edcfce00-6cda-11e9-88b9-dbd45ec7d0bd.png)

If you click the dropdown, advanced options are revealed:

![image](https://user-images.githubusercontent.com/1559108/57077252-16f05e80-6cdb-11e9-80f4-2f5624774f1a.png)

That model could be nice for CKAN as well. I imagine the default "plain" search would search name, identifier, abstract, and description, and then in the dropdown we could have an author option and anything else that came up as desirable (host?).

**Comment by HebaruSan** [comment]
Continuing the case study, if I enter a bunch filters into that GMail popup/dropdown and click search, after it closes, the selections go into colon-prefixed strings in the main search box:

![image](https://user-images.githubusercontent.com/1559108/58117920-4665fd00-7bef-11e9-9807-cd1fb97e8a0e.png)

We would need to do something like that as well, to give the user's search terms a persistent place to live. So we're effectively talking about creating a complete search syntax (which isn't too bad of an idea in itself).

**Comment by yalov** [comment]
something like this for the Classic GUI:
closed additional line (default):
` > Search: [--------------------]`

opened additional line:
` v  Search: [--------------------] (aka filter by name)`
`filter by author: [--------------------]  filter by description: [--------------------] `

**Comment by yalov** [comment]
main search bar doesn't have the OR logic, right? 

That was my initial idea, "one search box to search them all!".


![](https://images-ext-2.discordapp.net/external/iBoTordHWtUbyZarjV7ohtYwtdW6D46y0tpSxF7PK1c/https/i.imgur.com/ZN3vWvA.png)

like, I want to write "omega" (or any other author) and get the search that include "Omega's ... " in the name and omega in the author field, and mods that include omega in their description for some reason.

Or, if I want to find, e.g., mods for submarines, I could have several search, like "submarin", or "water", but you never know where the word appears: in the name, or in the description

So proposed changes: 
- the default search box searches in the name, author, description, and probably language (all,  except the mods' relations)
- the Name search field has required tag `name:`
- when you expand the default search box, a string doesn't go to any detailed search fields, the default search box is a separate entity.

**Comment by HebaruSan** [comment]
> the default search box searches in the name, author, description, and probably language with OR logic between them (all, except the mods' relations)

So if I try to search for mods for Linux, the list will be cluttered with all of linuxgurugamer's mods?

This does not sound like an improvement.

**Comment by HebaruSan** [comment]
> when you expand the default search box, a string doesn't go to any detailed search fields, the default search box is a separate entity with AND logic with detailed search fields

That's exactly how it already works.

**Comment by HebaruSan** [comment]
> the Name search field has required tag name:

Big thumbs down on this. Users would **not** expect or like having to type "name:KER" to do a typical search.

**Comment by yalov** [comment]
> So if I try to search for mods for Linux, the list will be cluttered with all of linuxgurugamer's mods?

`linux` is exactly what I would write for all linuxgurugamer mods. 
In your case it's `name:linux`

> That's exactly how it already works.

on v1.28.0 it is not. it's online sharing Main search field and detailed Name search field.

![](https://i.imgur.com/TveyzFD.gif)

> Users would not expect or like having to type "name:KER" to do a typical search.

Typical search doesn't need any tags, and will have a little bit more results than before, and some of them could be desired.  
Also KER isn't good example, because name:KER has all mods with kerbal in their name, and this search string isn't helpful for both cases.

There is some chance, that the all-in-one search in the average will give much more results than I am expecting.

Another option is adding new detailed search field with proposed results in the Gmail way. 
(`Has the words` fileds with the `name`|`desc`|`author`|`language` results)

**Comment by HebaruSan** [comment]
> on v1.28.0 it is not. it's online sharing Main search field and detailed Name search field.

That's not correct. Try typing something in the other fields; it will show up in Search but not Name.

**Comment by HebaruSan** [comment]
@yalov, a suggestion: Focus on use cases rather than demanding specific features implemented in a specific way. What things would you like to do that you can't do today with the current UI? Then we can figure out 1.) whether those things are actually impossible, 2.) whether other users would benefit, and 3.) ways of addressing them that would actually work, rather than poking holes in a specific partial design suggestion.

**Comment by yalov** [comment]
> What things would you like to do that you can't do today with the current UI?

I want to write a word, and see all mods related to that word
