### ISSUE TITLE
VesselMover request to track new fork

### ISSUE THREAD

**Issue by jrodrigv** [KSP-CKAN/CKAN#2742]
Hi all,

This is a request to update the tracked github repo for VesselMover mod:

The new one is this one:
https://github.com/jrodrigv/VesselMover/releases/tag/1.7.4

I'm the new maintainer 

Thanks in advance!

**Comment by HebaruSan** [comment]
Mind if we call it VesselMoverContinued? That's what we currently have indexed for the previous fork.

https://github.com/KSP-CKAN/NetKAN/tree/master/NetKAN/VesselMoverContinued.netkan

**Comment by jrodrigv** [comment]
Sure sorry I meant VesselMoverContinued. Cheers!
