### ISSUE TITLE
Add downloads to cache immediately upon individual completion

### ISSUE THREAD

**Issue by jupiterbjy** [KSP-CKAN/CKAN#2746]
Background
----------

**CKAN Version:** 
v1.26.0

**KSP Version:** 
1.7

**Operating System:** 
Win10 x64

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Nothing other than installing NearFuture Aeronautics, not related with issue.

Description
-------
This is not an urgent request, rather - a minor, maybe even personal one.

![temp3](https://user-images.githubusercontent.com/26041217/56860130-f0c27a00-69cd-11e9-91ef-c2c3f3ac4040.png)

When downloading mods, CKAN wait for **all mods** to be downloaded in temporary folder before copying to 'Download Cache' folder, and does not remove those .tmp files until clean exit of CKAN.

But when downloading multiple large mods, they would easily fill up Ramdisk causing CKAN to hang on download indefinitely. In that case: .tmp files will stay and take up space until reboot.

If CKAN moves **a mod** to 'Download Cache' folder as soon as it's complete and remove corresponding .tmp file, user can cancel download and not loose progress of already completed downloads, or need to care about their Temporary folder capacity.

**Comment by DasSkelett** [comment]
This would need some changes in the after-download logic.
Right now, the temp files are deleted `ModuleDonwloadsComplete()`, after all downloads have finished and have been copied to the cache:
https://github.com/KSP-CKAN/CKAN/blob/2119b5802494a8e1fa7f9250dfe834a27da64fdf/Core/Net/NetAsyncModulesDownloader.cs#L79-L117

If we want to delete tempfiles after each download, we basically need to move the whole `ModuleDownloadsComplete()` function to `FileDownloadComplete()`, and do it for one mod at a time (which isn't too different to how we handle it now, with a for-loop).

**Comment by HebaruSan** [comment]
I just want to make a note regarding this:

> But when downloading multiple large mods, they would easily fill up Ramdisk

If downloading multiple large mods can fill your temp folder, you're at risk of **one** large mod filling your temp folder, and you need a bigger temp folder.

**Comment by jupiterbjy** [comment]
Yup, but I still didn't see any mod that's over 4GB yet. And it's quite rare to see that Temp folder filled up unless some big mods decide to release update at same time. Therefore, I was referring this as 'not urgent' request, which might still cause issue to some players.
