### ISSUE TITLE
RPM support

### ISSUE THREAD

**Issue by enderger** [KSP-CKAN/CKAN#2748]
Background
----------

**CKAN Version:** 
All(packaging issue)

**KSP Version:** 
N/A

**Operating System:** 
RPM Linux distros

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 

Problem
-------

**What steps did you take in CKAN?**
N/A

**What did you expect to happen?**
I expected to find an RPM download link

**What happened instead?**
There was only a DEB link. This only works on Debian derivatives. Supporting RPM or even Snap or Flatpak would allow non-Debian installations.

**Screenshots:**

**CKAN error codes (if applicable):**

**Comment by HebaruSan** [comment]
You can still use the plain `ckan.exe` file. The .deb just has some niceties like putting it in the system `$PATH`, adding an icon to the system menus, and falling back to ConsoleUI if `$DISPLAY` isn't defined.

**Comment by enderger** [comment]
It would be nice to be able to run a .rpm file for those who use RPM-supporting Linux distros.

**Comment by HebaruSan** [comment]
Yup, and thanks for submitting the suggestion!
