### ISSUE TITLE
CKAN AD problem even though it is not installed

### ISSUE THREAD

**Issue by mynameis1234** [KSP-CKAN/CKAN#2750]
Background
----------

**CKAN Version:** 
Dragon

**KSP Version:** 
1.7.0

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
Ckan says my mods are AD when they are not in gamedata, let alone installed!

**What steps did you take in CKAN?**
1. Pressing reinstall on the mods 2. attempting to install the following ckan plugin:
https://forum.kerbalspaceprogram.com/index.php?/topic/96098-ckan-plugin-migration-tool-v11-alpha-clean-install-auto-detected-mods/

**What did you expect to happen?**
Fixing the problem

**What happened instead?**
1. Ckan had the modnotinstalled kraken 2. ckan crashed

**Comment by HebaruSan** [comment]
That plugin thread has 5 people reporting it doesn't work, last updated in 2016!

**Comment by mynameis1234** [comment]
> That plugin thread has 5 people reporting it doesn't work, last updated in 2016!

Oh. That is why it crashed. Thank you!

I will reinstall KSP and ckan and get back to you if it does not work. Again, thank you.

**Comment by mynameis1234** [comment]
UPDATE: Still does not work unfortunately. It still says these mods are AD even after reinstalling and verifying integrity of game files. Any config files for CKAN etc that can fix this? Thank you.

**Comment by HebaruSan** [comment]
Start over at the beginning. What did you do, in what order, and what happened?

**Comment by mynameis1234** [comment]
I had a bunch of other mods installed although I do not remember exactly which ones. I began installing Realism Overhaul and picked all the reccomended and suggested mods. Then it went to 0 bytes per second so I opened task manager and closed CKAN. Afterwards, I reopened and went back to the download. I got low system storage space and started deleting some things, then CKAN just stopped installing so I verified the integrity of my game files and reopened CKAN. Then I noticed this. 

This is correct to the best of my memory, I may be incorrect.

**Comment by HebaruSan** [comment]
OK, sounds like things just got corrupted. You can try the clean and reinstall process from the wiki:

https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

**Comment by mynameis1234** [comment]
I deleted the parts

> OK, sounds like things just got corrupted. You can try the clean and reinstall process from the wiki:
> 
> https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

I deleted all the files in CKAN instead in my KSP directory. I believe the problem should be fixed now. 

Thread closed, thank you!
