### ISSUE TITLE
Aborting a `ckan scan` halfway through leaves a corrupt registry.json file

### ISSUE THREAD

**Issue by lamont-granquist** [KSP-CKAN/CKAN#2754]
Think this is related to or possibly a spiritual-duplicate of #1114 

I don't really want to recreate the issue at this point and I've since repaired my installation, but the use case was simple, which was to do `ckan scan` on the commandline and then ctrl-c it halfway through it.  I actually had typed something like `ckan scan Proc` when I meant `ckan search Proc` so I just quickly ctrl-c'd it to fix the typo.

What resulted was a registry.json which was clearly half-written and truncated, and any subsequent ckan command was throwing JSON parsing errors.  Doing a `ckan repair registry` didn't help any.

It's probably a simple case of where the routines that write out JSON files need to write to a tempfile first, then close the filehandle, then move/rename the file into place.

**Comment by HebaruSan** [comment]
We've already got a file system transaction library, maybe we can use that?
