### ISSUE TITLE
Add local directory link to Metadata (GUI ENHANCEMENT DISCUSSION)

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#2763]
Just had a thought that it would be convenient to be able to click on a link in the Metadata section and be directed to the local directory for that mod.

Something like this:
![CKAN_localfile_mockup](https://user-images.githubusercontent.com/4062616/57797878-4a31e500-7700-11e9-8088-fb47b44bf3f2.png)

**Comment by DasSkelett** [comment]
You can double click on a folder/file in the `Contents` tab. This will open the file manager at the corresponding folder.

**Comment by DasSkelett** [comment]
Does this satisfy your request @7ranceaddic7? If so, let us know, so we can close this issue. If not, let us know too, so we can work out what you want :).

**Comment by 7ranceaddic7** [comment]
Yeah, that's fine.  No need to insert complexity.
