### ISSUE TITLE
'ckan compare' cmd warns of invalid autostart instance

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2774]
Background
----------

**CKAN Version:** 
v1.26.2

Problem
-------

**What steps did you take in CKAN?**
1) Have no autostart instance set, or an invalid one
2) Run `ckan compare 1.2.3 4.5.6`

**What did you expect to happen?**
```
"1.2.3" is lower than "4.5.6".
```

**What happened instead?**
```
342 [1] WARN CKAN.KSPManager (null) - Auto-start instance was invalid: Exception of type 'CKAN.InvalidKSPInstanceKraken' was thrown.
"1.2.3" is lower than "4.5.6".
```

This shouldn't happen. The compare command shouldn't care about any KSP instances and stuff (well, the `Compare.RunCommand()` itself doesn't, but some things before...).

Funnily enough there is a comment right above the call of `RunSimpleAction()` (line 139):
https://github.com/KSP-CKAN/CKAN/blob/00211bd8f288b5a2ea8054f953b184d632640c58/Cmdline/Main.cs#L125-L140

But as you can see a new `KSPManager` object is created a few lines above.
The constructor calls `LoadInstancesFromRegistry()`, in there the warning message is created:
https://github.com/KSP-CKAN/CKAN/blob/00211bd8f288b5a2ea8054f953b184d632640c58/Core/KSPManager.cs#L422-L430

So to fix this the creation of the `KSPManager` instance should be moved somewhere else, so that all commands that need it have it, and those which don't need it don't trigger the warning.

**Comment by HebaruSan** [comment]
This is the instance stuff that that comment was referencing:

https://github.com/KSP-CKAN/CKAN/blob/ad32e9ed8ad8b95c440252005d0d405d27ce0a9f/Cmdline/Main.cs#L155-L164

When that comment was written, only `ckan ksp`, `ckan version`, and `ckan gui` were exempted from running `KSPManager.GetPreferredInstance()` at startup (in a pretty hack-y way), which triggered the slow loading of `registry.json`, and you could use options like `--ksp blah` and `--kspdir blahblah` for commands that had no need for a KSP instance (see #2197).

https://github.com/KSP-CKAN/CKAN/commit/58970360e30b9c5aad1dc2557714f24d705215f3#diff-65b046d81019d814ad7bb97371cf4955

https://github.com/KSP-CKAN/CKAN/blob/a3f7eb50b726ffb208227ef959cdf6b8dd0a8b3f/Cmdline/Main.cs#L144-L148

Maybe the `AutoStartInstance` assignment doesn't belong in the constructor. If we don't use it, then we don't really need a warning about it.

**Comment by HebaruSan** [comment]
Yeah, we don't need that assignment. It's assigning the value that the `get` accessor will return anyway!

https://github.com/KSP-CKAN/CKAN/blob/ad32e9ed8ad8b95c440252005d0d405d27ce0a9f/Core/KSPManager.cs#L25-L36

The only effect that has is to take up CPU time and throw this exception!
