### ISSUE TITLE
CKAN.InvalidModuleFileKraken: DarkMultiPlayer v0.3.3.0

### ISSUE THREAD

**Issue by Elana-chan** [KSP-CKAN/CKAN#2779]
Background
----------

**CKAN Version:** 
1.26.2

**KSP Version:** 
1.7.1.2539

**Operating System:** 
Windows 7 Pro

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
Deleted DarkMultiPlayer folder AFTER uninstall via CKAN with intention of clean install following first appearance of error.

Problem
-------

**What steps did you take in CKAN?**
1. Attempt mod update: Error occurs
2. Confirm issue is repeatable: true
3. Is it happening with other mods?: false
4. Error occurs after clean-install attempt: true

**What did you expect to happen?**
Automated one-button update.

**What happened instead?**
Error as shown bellow.

**Screenshots:**

![image](https://user-images.githubusercontent.com/6004010/59250317-c6262c80-8bdb-11e9-98d3-1ea63571e561.png)
![image](https://user-images.githubusercontent.com/6004010/59250596-94fa2c00-8bdc-11e9-9723-1ef574ff31f0.png)
Pastebin for text body in second error window:
https://pastebin.com/JF5i3gpK

Edit: Issue became known immediately after updating CKAN to 1.26.2, previous version unknown (likely 1.24 or later).

**Comment by HebaruSan** [comment]
@techman83, can you please purge `5A6DCDCD-netkan-DarkMultiPlayer.zip` from the bot's cache?

**Comment by techman83** [comment]
Done + triggered it to re-index

**Comment by HebaruSan** [comment]
Wonderful, thanks! The hashes were updated.
https://github.com/KSP-CKAN/CKAN-meta/commit/937961cde757741702eddedd9cae2a3da1c4a592
