### ISSUE TITLE
recline jsonpdataproxy fix? 

### ISSUE THREAD

**Issue by Quackpower** [KSP-CKAN/CKAN#2785]
Hello!

i'm completly new with ckan, is it installed already and it work well but the server that the recline.js library uses "jsonpdataproxy" , is down most of the time, what is a work around to this, as i unstderstand, the proxy is used to load the file form an external source, but all of my files are locally stored, anyone has ha this issue before??? thanks!

**Comment by HebaruSan** [comment]
Hi! I think you want to go here instead:

https://github.com/ckan/ckan

KSP-CKAN is a mod manager for a video game. We don't do things with recline.js or proxies. Good luck!
