### ISSUE TITLE
Add menu option to open an issue in the CKAN repo

### ISSUE THREAD

**Issue by tofof** [KSP-CKAN/CKAN#2790]
Background
----------
* Operating System: Win10
* CKAN Version: 1.26.2
* KSP Version: 1.7.2.2256

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
CKAN's menu option, Help->Report Issue opens an issue in the the NetKAN repo instead of here in the CKAN repo.

**Steps to reproduce**
Open Ckan
Click Help
Click Report an Issue
Observe URL in browser: `https://github.com/KSP-CKAN/NetKAN/issues/new`

**Expected behavior**
Ckan's menu option should point to `https://github.com/KSP-CKAN/CKAN/issues/new/choose`

**Comment by DasSkelett** [comment]
https://github.com/KSP-CKAN/issues/new doesn't work, do you mean https://github.com/KSP-CKAN/CKAN/issues/new?

I think the thought behind pointing the link to the NetKAN repo was that most issues are about indexed mods (relationships, version compatibility, stuff like this) and they shouldn't spam the CKAN repo.

I think we should add a sentence in the`Mod request` issue type descriptions like
`"Please consider opening this issue in the NetKAN repository"`
and for the other two types
`"Please consider opening this issue in the CKAN repository"` or something like this.

The URL definitely needs changing too `.../issues/new/choose`

**Comment by tofof** [comment]
You're correct about both URL points; I've updated my post accordingly.

As far as I can tell from the readme in the NetKAN repo (emphasis mine):

>The NetKAN consists of CKAN **fragments which are used by our indexing bots to generate metadata** for use by the CKAN client and other tools. The files themselves live in the NetKAN directory.
>If you're wondering what the CKAN is, start with this README.
> Opening issues
**If you want to suggest something or report a bug relating to CKAN as a whole, open an issue on the CKAN repository.**
>If you wish to add support for a new mod yourself, Read our guide on how to do this.
>The format of NetKAN files is that described in the CKAN Spec, including the special use fields at the end.

Even to the extent that the NetKAN repo should be where mod authors complain about indexing metadata, that certainly doesn't mean that's expected behavior from a 'help->report an issue' user-facing menu item in the general CKAN executable used by everyone, not just mod authors.

If that is intended to be the only purpose of the menu item, the menu item should be renamed: "Report an incorrectly indexed mod".

**Comment by HebaruSan** [comment]
Yeah in #1502 it was specifically requested as, "Can we have a NetKan issue link on the GUI please?" (added in #1849).

**Comment by tofof** [comment]
And in #1502 the suggestion was for it to read "Report an issue with mod".

But right now, "Help->report an issue" certainly seems like it's for CKAN, not for mods.
Help->About is certainly entirely about CKAN, for example.

**Comment by DasSkelett** [comment]
So basically we should have two menu items, one
`Report an issue with the CKAN client` or similar, and one
`Report an issue with mod metadata` or similar.

I support that.

**Comment by HebaruSan** [comment]
Fixed in #2801

**Comment by DasSkelett** [comment]
Why did the auto-close not work?

**Comment by HebaruSan** [comment]
Because before I edited it, it said "Fixes #2801", which was itself :smirk:
