### ISSUE TITLE
[Feature][UI] Description field - add scrollbar

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#2795]
Problem
-------
**Is your feature request related to a problem? Please describe.**
Long description truncated if window is not large enough to display full text.

Suggestions
-----------
**Describe the solution you'd like**
If description does not fit, add vertical scrollbar to description text box.

**Describe alternatives you've considered**

**Additional context**
For an example of a mod with a long description, check out "Nehemia Engineering Orbital Science".

**Comment by DasSkelett** [comment]
If you focus it (click in it), you can scroll. However, scroll bars are missing indeed.
