### ISSUE TITLE
[Bug] Can't install GroundConstruction

### ISSUE THREAD

**Issue by YellowApple** [KSP-CKAN/CKAN#2797]
Background
----------
* Operating System: Linux 4.19.44 x86_64 (Slackware64-current)
* CKAN Version: 1.26.2
* KSP Version: 1.7.2.2556

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**  
No.

Problem
-------
**Describe the bug**  
On a fresh copy of KSP's GameData with a fresh install of the latest CKAN, checking the box to install the "Global Construction" mod (`GroundConstruction`) immediately results in a pop-up error stating "`GroundConstruction 2.4.1.0.1 depends on GroundConstruction-Core, which is not compatible with the currently installed version of KSP`".  This is despite both [`GroundConstruction-Core`](https://github.com/KSP-CKAN/CKAN-meta/blob/master/GroundConstruction-Core/GroundConstruction-Core-2.4.1.0.1.ckan) and [`GroundConstruction`](https://github.com/KSP-CKAN/CKAN-meta/blob/master/GroundConstruction/GroundConstruction-2.4.1.0.1.ckan) specifying `"ksp_version": "1.7.2"` in their metadata.

On further examination, it looks like one of `GroundConstruction-Core`'s *dependencies* (specifically, `CommunityResourcePack`) is marked as supporting only up to KSP 1.6.9 (despite [some indication that it works fine on newer KSPs](https://forum.kerbalspaceprogram.com/index.php?/topic/83007-15x-community-resource-pack/&do=findComment&comment=3616082); if I test and confirm, would it be appropriate for me to submit a PR for that supported KSP version bump?), so it seems like the error is warranted, but complaining about the wrong dependency.

**Steps to reproduce**  
* Download a fresh copy of KSP
* Download a fresh CKAN and put it in the freshly-downloaded copy of KSP
* Run `mono ckan.exe`
* Let the metadata refresh
* Click on the check box next to "Ground Construction"
* Observe the error message

**Expected behavior**  
Either no error message at all (ideal; the upstream [forum post](https://forum.kerbalspaceprogram.com/index.php?/topic/154167-17-global-construction/) indicates the mod to be explicitly KSP 1.7.x compatible) or at the very least complain about the right dependency being incompatible.

**Screenshots (if applicable)**  
![image](https://user-images.githubusercontent.com/2379422/59979466-2e421e80-959d-11e9-9d78-a02c11be94a3.png)

**CKAN error code (if applicable):**<details><summary>Click to expand</summary>
```
1249860 [1] ERROR CKAN.ErrorDialog (null) - GroundConstruction 2.4.1.0.1 depends on GroundConstruction-Core, which is not compatible with the currently installed version of KSP
```
</details>

**Comment by HebaruSan** [comment]
CommunityResourcePack's metadata is managed by its author; try a PR over there:

https://github.com/BobPalmer/CKAN/pulls

Or just mark 1.6 as compatible:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by YellowApple** [comment]
Cool, thanks; I'll submit the version bump PR over there, then.  I'm probably going to do the "mark 1.6 as compatible" workaround to get up and running (and also to test and verify compatibility), but that doesn't seem like a particularly safe long-term solution ;)

In the meantime, it's at the very least still a bug to list the wrong dependency as being incompatible in that error message, no?
