### ISSUE TITLE
CKAN stops working immediately after launch with no code or anything

### ISSUE THREAD

**Issue by RDambrosio016** [KSP-CKAN/CKAN#2802]
Background
----------

**CKAN Version:** 
bruce? 1.24.0 i think

**KSP Version:** 
1.3.1 heavily modded

**Operating System:** 
windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
yep its modded but i have tried moving my ksp folder out of steam and letting steam download a fresh one and tried to run ckan on that but that doesnt work too

**Affected mods and mod versions:**
ehhhhhhh ???????
all of them i guess

Problem
-------

**What steps did you take in CKAN?**
put it into my ksp directory (1.3.1) (heavily modded)

launch it

**What did you expect to happen?**
launch normally lol

**What happened instead?**

ckan stops working immediately after launching it from inside the ksp directory, ive tried deleting the ckan folder but that doesnt do anything 

IMMEDIATELY a windows error pops up saying "ckan has stopped working" then says close program

**Screenshots:**

![screenshot_32](https://user-images.githubusercontent.com/38166539/38459964-ab6943aa-3a7e-11e8-83ac-7552eb73d74a.png)

**CKAN error codes (if applicable):**

**Comment by politas** [comment]
After that last incoherent message, I'm tempted to just close this issue

**Comment by RDambrosio016** [comment]
yikes this is old
