### ISSUE TITLE
[Mod]  Request to update PhysicsRangeExtender suggestions

### ISSUE THREAD

**Issue by jrodrigv** [KSP-CKAN/CKAN#2806]
Hi,
This is a request to update the mod suggestions for my mod PhysicsRangeExtender.

Currently is suggesting an obsolete version of KJR. Would it be possible to change to suggest the new repository of https://github.com/KSP-RO/Kerbal-Joint-Reinforcement-Continued?

Cheers

**Comment by HebaruSan** [comment]
That suggestion already pulls in that mod thanks to its `"provides": [ "KerbalJointReinforcement" ]` property:

![image](https://user-images.githubusercontent.com/1559108/60041667-98cc8a80-9681-11e9-8ebc-845a050a26b3.png)

**Comment by HebaruSan** [comment]
@jrodrigv, this looks unnecessary, see previous comment.

**Comment by jrodrigv** [comment]
Thanks for your reply. I was wrong then, sorry.

**Comment by HebaruSan** [comment]
No problem!
