### ISSUE TITLE
[Feature] Show current instance not only in title bar

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2807]
Problem
-------
Request from the forum thread: https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1262-dragon%EF%BB%BF/&do=findComment&comment=3624643

Users with window managers configured to hide title bars can't see the current instance in use.

Suggestions
-----------
**Describe the solution you'd like**
Show the instance name (and path) somewhere else too, for example in the lower right corner in the status bar.
Problem: right now the status bar is hidden at start-up and only shown when there are messages / the progress bar to show. I thought this was introduced in an extra PR, but I can't find it right now. If it were only design reasons, we could revert that and show the current instance on the right side.

**Describe alternatives you've considered**
Well, that's where I'm struggling. Are there alternatives? I thought of the menu bar too, on the far right, but I'm not sure if this is possible.

**Comment by HebaruSan** [comment]
I think the status bar hiding is automatic on Mono when there is no text in it. I think it's always visible on Windows. So that should not stop us from adding this.

**Comment by nesingho** [comment]
Thanks @HebaruSan !
