### ISSUE TITLE
[Feature] Avoid Spurious build.json download in NetKAN

### ISSUE THREAD

**Issue by techman83** [KSP-CKAN/CKAN#2809]
Problem
-------
#2808 ensures NetKAN is up to date, but this file doesn't change super regularly. So the process will refresh it > 1800 times per index run, which is less than ideal.

Suggestions
-----------
We could use a special message type + webhook to handle this, but we're a little ways off from having the webhooks moved over to the new infra. 

For now we could put a time stamp in the refresh logic and short cut it if it has been checked in the last 4 hours. Which will mean it gets checked once per index run.

**Comment by HebaruSan** [comment]
My preference would be:

- Make the bot use the embedded build map
- Make the infrastructure somehow keep netkan.exe up to date (already happens currently, not sure how it would work with the future architecture)

When we edit https://github.com/KSP-CKAN/CKAN/blob/master/Core/builds.json , that automatically triggers a new build of netkan.exe which includes the new builds in the embedded build map and is uploaded to the S3. So if the container infrastructure can somehow update netkan.exe when it changes on S3 and restart the Inflator, that would do the trick if Netkan used the embedded build map.

**Comment by techman83** [comment]
I think rebuilding Netkan when the builds.json is changed would be more than acceptable. As I commented on the linked, we'll have an automated way to ensure it's kept up to day. My current primary motivation for the re-architecture is to remove me from the process as much as possible. Simple code changes + improvements shouldn't involve me for anything more than at most a code review.

I don't want to be a blocker for making things better :slightly_smiling_face:
