### ISSUE TITLE
[Feature] Force install

### ISSUE THREAD

**Issue by Artemonim** [KSP-CKAN/CKAN#2822]
Problem
-------
To install old but working modifications I have to open the list of versions.

Suggestions
-----------
I propose to add the "Force install" item to the context menu of the list of modifications, which will mark the modification for installation in spite of any restrictions.

**Comment by Artemonim** [comment]
[PlanetShine](https://forum.kerbalspaceprogram.com/index.php?/topic/173138-141-planetshine-0261-mar-28-2018/), [AlternateResourcePanel](https://forum.kerbalspaceprogram.com/index.php?/topic/54876-14x-ksp-alternate-resource-panel-v2930-march-17/)
Some of 1.6.X modifications work correctly in 1.7.2

**Comment by HebaruSan** [comment]
But why couldn't you just install those normally? Why does this request mention the versions list?

![image](https://user-images.githubusercontent.com/1559108/60412013-1bdc6c00-9bbf-11e9-8aac-146240ebf233.png)

![image](https://user-images.githubusercontent.com/1559108/60412015-1f6ff300-9bbf-11e9-920b-11b984897441.png)

![image](https://user-images.githubusercontent.com/1559108/60412020-2139b680-9bbf-11e9-9940-52a173a3088f.png)

**Comment by Artemonim** [comment]
In CKAN there is a list of KSP versions. If any of the marked versions is suitable for any version of the modification — the modification is displayed in the list. Let's say I found out about some old modification that is unsupported but works in the latest version of the game. Here's what I need to do now:
1. Click "Settings" on the top panel.
2. Click "Compatible KSP versions" in the dropdown list.
3. Find and select the version of the game I need.
4. Find and select the desired modification.
5. Installation...
6. Click "Settings" on the top panel.
7. Click "Compatible KSP versions" in the dropdown list.
8. Find and deselect used version of the game. (To make the filters "Compatible" and "Newly compatible" show modifications only for my version of the game.)

What I suggest:
1. Select the "All" filter in the CKAN action bar.
2. Find and select the desired modification.
3. Installation...
4. Change the list filter if I need to.

**Comment by HebaruSan** [comment]
Oh! I thought you meant the "list of versions" on the Versions tab of mod info:

![image](https://user-images.githubusercontent.com/1559108/37540859-7b3c2380-2950-11e8-9914-13447e6148fd.png)

**Comment by Artemonim** [comment]
Perhaps the proposed feature will be needed by someone in the "list of versions" too :)
