### ISSUE TITLE
[Bug] GUI doesn't clear changeset after successful installation

### ISSUE THREAD

**Issue by DasSkelett** [KSP-CKAN/CKAN#2828]
Background
----------
* Operating System: Kubuntu 19.04
* CKAN Version: current master@aad98c7a -> #2821 is the baddie

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
The GUI doesn't clear the changeset after any type of mod change.
Also, the refresh of the modlist puts the log messages in the `Changeset` tab, not in the `Status log` tab.

**Steps to reproduce**
Select any mod to install.
Install it.

See that during that the log tab opens the GUI switches to it (all right until now), but then after everything is done, the GUI switches to the `Changeset` tab (whioch mostly looks like the status tab now) and puts the log messages for the modlist update there.

After installation, open the changeset tab (which now looks normal again) and see that the mod change is still in the changeset.
Is you click `Apply` again, CKAN wants to reinstall the mod again, and since the mod is already installed, an error is thrown (and the GUI is in a broken condition, this should be fixed too some day).

**Expected behavior**
The changeset is empty after all mod changes were done.
The log messages are outputted in the right tab.

**Comment by HebaruSan** [comment]
I doubt #2821 caused this by itself; I tested this quite a lot during dev. Maybe an interaction with another recently merged PR.

**Comment by HebaruSan** [comment]
> Also, the refresh of the modlist puts the log messages in the Changeset tab, not in the Status log tab.

Can you show a screenshot of this? I'm not sure I understand.

**Comment by DasSkelett** [comment]
> Can you show a screenshot of this? I'm not sure I understand.

![grafik](https://user-images.githubusercontent.com/28812678/60768870-55ced600-a0c9-11e9-8789-93cda7954b8b.png)

The `changeset` (=`Änderungen`) tab appears to be active and open, but what is shown is the content of the tab on the right, `Loading Modules` (=`Module laden`)
