### ISSUE TITLE
CKAN not Responding On Load

### ISSUE THREAD

**Issue by w1wwwwww** [KSP-CKAN/CKAN#2832]
Background
----------
* Operating System: Windows 10 Home
* CKAN Version: 1.26.2, Dragon
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No.

Problem
-------
**Describe the bug**

CKAN Not responding on load.
Repositories have been loaded.

**Steps to reproduce**
Open CKAN
Wait for repositories to load
See that CKAN is not responding

**Expected behavior**
CKAN should freeze.
Windows will not act as if the CKAN is not responding.

**Screenshots (if applicable)**

![Screenshot (1)](https://user-images.githubusercontent.com/26696846/61233470-44538280-a6f6-11e9-9d6d-9d746dc2b468.png)

**CKAN error code (if applicable):**<details><summary>Click to expand</summary>
```
No code avalable
```
</details>

**Comment by w1wwwwww** [comment]
CKAN also will not close

**Comment by DasSkelett** [comment]
Could you try to [get a log output](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#logging)? Might help us narrow down where to begin the search.

**Comment by HebaruSan** [comment]
From the disabled menu and toolbars I'm guessing there's a CKAN popup window somewhere, maybe on another monitor.

**Comment by w1wwwwww** [comment]
DasSkelett I'll get one.
And No Popup

**Comment by w1wwwwww** [comment]
I also don't have access to that computer currently

**Comment by w1wwwwww** [comment]
Nevermind, it fixed itself
