### ISSUE TITLE
[Bug] Unnecessary mods added

### ISSUE THREAD

**Issue by Monniasza** [KSP-CKAN/CKAN#2833]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.26.2
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Add mods listed on fist comment on [https://forum.kerbalspaceprogram.com/index.php?/topic/141872-ksp-komplete-modpack-ckan-list-113/](https://forum.kerbalspaceprogram.com/index.php?/topic/141872-ksp-komplete-modpack-ckan-list-113/)
* Apply changes
* Look at modlist

**Expected behavior**
Only mods listed on first comment are added

**Actual behavior**
33 extra mods are added
**Screenshots (if applicable)**

**CKAN error code (if applicable):**<details><summary>Click to expand</summary>
This doesn't produce error code, but adds unnecessary mods.
PLACE CODE HERE !
```
</details>

**Comment by DasSkelett** [comment]
It's explained on the changeset tab why all those extra mods are installed. They are dependencies (that are not listed in this mod list, which is btw very outdated!):
![changeset](https://user-images.githubusercontent.com/28812678/61529895-d58e6600-aa22-11e9-80dc-e87d6ac3a124.png)

You might have installed the recommendations too.
