### ISSUE TITLE
[Bug] Curse download URLs in old metadata need updating

### ISSUE THREAD

**Issue by KrappyKream** [KSP-CKAN/CKAN#2836]
Background
----------
* Operating System: Windows 10 1903
* CKAN Version: Dragon
* KSP Version: 1.3.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
nop

Problem
-------
**Describe the bug**
 failing installation

**Steps to reproduce**
* Go to... RealismOverhaul
* Click on...Versions/V12.6.0/Install/ Choose KJR Continued/ check all recommended except Persistent Rotation, TestFlight, TAC LS, Remote Tech, RealismOverhaul Craft files and the 4 Near Future mods.
* See error
a smoll window pops up when installing.
**Expected behavior**
Unfinished installation => unchanged GameData Folder

**Screenshots (if applicable)**

**CKAN error code (if applicable):**<details><summary>Click to expand</summary>
```
CKAN.InvalidModuleFileKraken: KAS 0.6.3.0: C:\Users\kerba\AppData\Local\Temp\tmp7D61.tmp has length 178430, should be 2982090
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadsComplete(NetModuleCache cache, Uri[] urls, String[] filenames, Exception[] errors)
PLACE CODE HERE !
```
</details>
Succesfully installed this a while back with the same Version of CKAN and KSP. both are fresh.

**Comment by HebaruSan** [comment]
Can you please give us the complete stack trace? Those two lines do not say what the problem was.

**Comment by DasSkelett** [comment]
It's there, it wasn't displayed because it was in the same line as the three backticks.

**Comment by DasSkelett** [comment]
It's KAS 0.6.3.0

**Comment by HebaruSan** [comment]
Yup, another consequence of the Curse server-side change that caused KSP-CKAN/NetKAN#7268. The old download URLs don't work anymore.

**Comment by DasSkelett** [comment]
Oh you are right, that downloads the complete webpage...

**Comment by DasSkelett** [comment]
@KrappyKream please refresh and try again, it should work now.
It was due to an issue with the CurseForge API.
