### ISSUE TITLE
Error When Using Drive Root Folder

### ISSUE THREAD

**Issue by CommanderGizmo** [KSP-CKAN/CKAN#2837]
CKAN v1.26.2
An error occurs when trying to update or install mods if you have used a drive root for your game path.  I use a RAM-drive for my game and KSP is installed in the root of the drive.  The error includes the text 'Cannot find path "R:\ameData"'. Starting CKAN shows the path 'R:' in the titlebar.  These suggest the software is improperly trimming root folders.  As a workaround I created a folder junction on another drive to point to the RAM-drive, but I thought you ought to know.

**Comment by DasSkelett** [comment]
If someone wants to test it, use this to map a KSP instance to a drive:
`subst R: "C:/path/to/KSP/instance"`

**Comment by DasSkelett** [comment]
Complete stack trace for upgrading/removing a mod:
```
System.IO.DirectoryNotFoundException: Ein Teil des Pfades "R:\ameData" konnte nicht gefunden werden.
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileSystemEnumerableIterator`1.CommonInit()
   bei System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   bei System.IO.Directory.EnumerateFileSystemEntries(String path)
   bei CKAN.ModuleInstaller.Uninstall(String modName)
   bei CKAN.ModuleInstaller.AddRemove(IEnumerable`1 add, IEnumerable`1 remove, Boolean enforceConsistency)
   bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 modules, IDownloader netAsyncDownloader, Boolean enforceConsistency)
   bei CKAN.ModuleInstaller.Upgrade(IEnumerable`1 identifiers, IDownloader netAsyncDownloader, Boolean enforceConsistency)
   bei CKAN.Main.InstallMods(Object sender, DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   bei System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

**Comment by DasSkelett** [comment]
It's also present in the contents tab, but there the 'G' is written with the '/' missing...
![Contents](https://user-images.githubusercontent.com/28812678/63052346-613ec980-bedf-11e9-88e3-33e3f65179a3.png)

**Comment by HebaruSan** [comment]
This is why friends don't let friends use drive letters.

**Comment by HebaruSan** [comment]
I set up a K: drive for testing.

- Adding it to CKAN produces a name ` (0)` (with a leading space)
- `KSP.GameDir()` returns `K:`
- `KSP.GameData()` returns `K:GameData`

So, `Path.Combine(GameDir(), "GameData")` is just appending them without adding a slash.
https://github.com/KSP-CKAN/CKAN/blob/9da096b39e1604345c93c2cc551b6d7e3c649219/Core/KSP.cs#L289-L294

**Comment by HebaruSan** [comment]
The extra character is lost here, because `root.Length + 1` is too many characters when `root` is just "K:":

https://github.com/KSP-CKAN/CKAN/blob/9da096b39e1604345c93c2cc551b6d7e3c649219/Core/KSPPathUtils.cs#L246-L251
