### ISSUE TITLE
[Bug]All mods under compatible are visually checked as installed, but do not appear under the installed tab, and are not actually installed.

### ISSUE THREAD

**Issue by nascarlaser1** [KSP-CKAN/CKAN#2843]
Background
----------
* Operating System: Windows 10 
* CKAN Version: Orion
* KSP Version: 2594 (according to launcher)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No

Problem
-------
**Describe the bug**
All mods under compatible are visually checked as installed, but do not appear under the installed tab, and are not actually installed. It appears to just be visual, since gamedata folder and the installed tab are perfectly fine.

**Steps to reproduce**
Update to orion,reboot Ckan.

**Expected behavior**
Works perfectly fine, minus the graphical portion of the checkbox.

**Screenshots (if applicable)**
![ckan bug 1](https://user-images.githubusercontent.com/54118676/63047251-0d61bf80-bea2-11e9-8a51-dfc8d66efb8c.PNG)
![ckan bug 2](https://user-images.githubusercontent.com/54118676/63047332-3c783100-bea2-11e9-819d-835a82366248.PNG)

**Comment by DasSkelett** [comment]
I suspect you restarted CKAN a second time already? And the issue is still there? After refreshing it stays the same?
Can you export you installed mods (under `File` > `Export installed mods` > `CKAN favourites list (*.ckan)` and upload it here?

**Comment by nascarlaser1** [comment]
I've restarted program repeatedly over multiple days, as well as refreshing. 
I'm not sure how to upload the mod list due to github not supporting the file type.

**Comment by DasSkelett** [comment]
Either zip it, or just add `.txt` after the .ckan extension.

**Comment by nascarlaser1** [comment]
[ckan mod export.zip](https://github.com/KSP-CKAN/CKAN/files/3512311/ckan.mod.export.zip)
Here ya go ^^

**Comment by HebaruSan** [comment]
I tried installing that mod list in Windows (except StockalikeMiningExtension which can't be installed currently), and it worked normally:

![image](https://user-images.githubusercontent.com/1559108/63229122-8045a000-c1ec-11e9-94c0-c8e078b46ec8.png)

Can you upload a copy of your `CKAN\registry.json` file as well? There may be some clues in there.

**Comment by nascarlaser1** [comment]
Where do I find the registry.json?

**Comment by HebaruSan** [comment]
It's in the CKAN folder in your KSP folder.

**Comment by nascarlaser1** [comment]
Here it is ^^
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/3520558/registry.zip)

**Comment by HebaruSan** [comment]
Thanks!
I tried replacing my copy of that file with yours, and unfortunately it still works fine for me, so something else is causing it.

**Comment by nascarlaser1** [comment]
Ok. It seems to just affect it visually,so I'm fine with it until i re-install ckan. Was mostly a "Hey look" sorta bug then anything else ^^

**Comment by HebaruSan** [comment]
Still no hint of how to reproduce this. Without that, we can't investigate or fix it.
Please let us know if you have more information, we can re-open.
