### ISSUE TITLE
Travis Broke the .NET Core Builds

### ISSUE THREAD

**Issue by jbrot** [KSP-CKAN/CKAN#2844]
It looks like something changed in the past month causing the .NET Core build script to fail. For instance, see https://travis-ci.org/KSP-CKAN/CKAN/jobs/571858878. I found this issue documented with a solution here: https://benlimmer.com/2019/01/14/travis-ci-xvfb/. I'll try and submit a PR resolving the issue sometime this weekend.

**Comment by HebaruSan** [comment]
> I'll try and submit a PR resolving the issue sometime this weekend.

Thanks for volunteering!

**Comment by HebaruSan** [comment]
Looks like the other builds still worked because they use trusty instead of xenial. I don't know how that's set up.

**Comment by HebaruSan** [comment]
I had time and was curious whether the linked change would fix it (it did).
All builds succeeded for #2845, and it seems like we need this anyway to avoid having future problems with all builds.
