### ISSUE TITLE
[Bug] Slow response on clicking install checkbox with many mods installed

### ISSUE THREAD

**Issue by shdwlrd** [KSP-CKAN/CKAN#2846]
Background
----------
* Operating System: Win10 Pro build 1903
* CKAN Version: 1.26.4
* KSP Version: 1.7.3.2594

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
nope

Problem
-------
I have extreme lag when selecting or deselecting a mod to update, install or uninstall. ckan will go unresponsive then recover, afterwards the mod will select in about 10-15 seconds later per mod I clicked on. on a side note, ckan is eating up to 25-35% of my cpu while during the whole process, and seems to be waiting for my hdd.

All other functions work as expected.

**Steps to reproduce**
* Install 300+ mods
* Click the install checkbox for another mod
* It takes a while to respond

**Screenshots (if applicable)**

![screenshot](https://user-images.githubusercontent.com/54296570/63316870-2de0ae00-c2d6-11e9-98e2-5f004d24ca7c.png)

**Comment by HebaruSan** [comment]
Thanks for submitting this!

I've tried selecting and deselecting a mod, and it didn't slow down for me, so we'll need more information to figure out what's going on.

- How many and which mods do you have installed?
- Can you show us a screenshot of before/after you click?

**Comment by shdwlrd** [comment]
I have 363 mods that ckan is managing. I have screens of before and during the problem with ckan and task manager running side by side. All taken a few seconds apart. In this case I clicked on sounding rockets by roverdude.
![Screenshot (6)](https://user-images.githubusercontent.com/54296570/63316868-2de0ae00-c2d6-11e9-9bcd-7e9157aff73c.png)
![Screenshot (7)](https://user-images.githubusercontent.com/54296570/63316869-2de0ae00-c2d6-11e9-80d8-19e954ff9006.png)
![Screenshot (8)](https://user-images.githubusercontent.com/54296570/63316870-2de0ae00-c2d6-11e9-98e2-5f004d24ca7c.png)

**Comment by HebaruSan** [comment]
> I have 363 mods that ckan is managing

That's probably what's different between your test and mine, I didn't have nearly that many installed. Thanks, that gives us a clear scenario to target for optimization.

**Comment by HebaruSan** [comment]
Investigation notes...

- `UpdateChangeSetAndConflicts` may be getting called twice now, once by `ModList_CellValueChanged` and once by `GUIMod.SelectedMod`, so fixing that would cut the time by 50%

**Comment by whiteknight4981** [comment]
also seeing this (or something very similar) when trying to check the update box
CKAN - 1.26.4
OS - ubuntu 18.04
installed MOD count under KSP-CKAN - 150

**Comment by HebaruSan** [comment]
@whiteknight4981, there's a test build linked from #2855 if you want to see whether the fix will help your case.
