### ISSUE TITLE
[Bug] user.RaiseMessage does not properly handle newlines on GUI

### ISSUE THREAD

**Issue by sundhaug92** [KSP-CKAN/CKAN#2847]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.26.4
* KSP Version: N/A

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**: N/A

Problem
-------
Example: user.RaiseMessage in https://github.com/KSP-CKAN/CKAN/blob/56eded6390f3f63787c06ca9e9e01c2fabb43729/Cmdline/Action/Install.cs#L236-L247 renders as

`Oh no!It looks like you're trying to install a mod which is already installed,or which conflicts with another mod which is already installed.As a safety feature, the CKAN will *never* overwrite or alter a filethat it did not install itself.If you wish to install ExtraPlanetaryLaunchpads 6.6.1.0 via the CKAN,then please manually uninstall the mod which owns:Ships/SPH/Ore Scanner.craftand try again.`

**Steps to reproduce**
* Install a mod with a file that is already installed

**Expected behavior**
* user.RaiseMessage handles newlines properly

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/519283/63356611-616c1880-c368-11e9-9886-bbb3fb1c732d.png)

**CKAN error code (if applicable):**<details><summary></summary>
</details>

**Comment by sundhaug92** [comment]
Incidentally, the text is rendered correctly by say notepad if you copy it into it

**Comment by HebaruSan** [comment]
Here's what it looks like for me:

![image](https://user-images.githubusercontent.com/1559108/63368574-b3fc0380-c36d-11e9-9e0b-6d870faa28e6.png)

**Comment by sundhaug92** [comment]
Well that's odd. What language are you running? I'm nb-no. 

KSP (auto): 1.7.3.2594
No plugins
Github token, only default metadata repo
d/l cache 4.4 GiB
![image](https://user-images.githubusercontent.com/519283/63371893-3fcd5a00-c385-11e9-9362-5baaa885e078.png)
![image](https://user-images.githubusercontent.com/519283/63371922-4eb40c80-c385-11e9-8120-504b9191de44.png)

**Comment by HebaruSan** [comment]
> What language are you running?

I have en-US.
Maybe the text box changed behavior between Win7 and Win10?

**Comment by sundhaug92** [comment]
> Maybe the text box changed behavior between Win7 and Win10?

It's possible, wouldn't surprise me, could explain why notepad handles it correctly when the same text is pasted in

**Comment by HebaruSan** [comment]
This page makes it sound like another property is needed for multiline strings, bu tit's for another toolkit (UI.Xaml):

https://docs.microsoft.com/en-us/uwp/api/windows.ui.xaml.controls.textbox.acceptsreturn#Windows_UI_Xaml_Controls_TextBox_AcceptsReturn

> Gets or sets the value that determines whether the text box allows and displays the newline or return characters.

It exists in WinForms, but the description is different (doesn't say it controls display of newlines):

https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.textbox.acceptsreturn

Maybe Microsoft confused the two properties at some level in Win10?
We currently don't set this property. @sundhaug92 , can you please try this test build with it set to see if it makes a difference?

- [ckan.zip](https://github.com/KSP-CKAN/CKAN/files/3522104/ckan.zip)

**Comment by HebaruSan** [comment]
Don't think CKAN's doing anything wrong here, since it seems to work for all other users. Might be some OS quirk, corrupted DLL, or some third party component screwing things up, who knows. Can't investigate or fix anything based on this; please let us know if you figure something out, we can re-open.

**Comment by HebaruSan** [comment]
This was probably a pre-duplicate of #3470. The quoted code block was a red herring because `CmdLine` code is not used by GUI; instead, that message was coming from here:

https://github.com/KSP-CKAN/CKAN/blob/2d67c29aabaa631f67723fbdcf28545a677863bd/GUI/Properties/Resources.resx#L242-L255

So `user.RaiseMessage` was fine all along, but the resource DLLs had LF instead of CRLF.

**Comment by sundhaug92** [comment]
Nice, grats on fixing it. For future reference, it might be an idea to `git config` `core.autocrlf=false` either globally or on the repo (adding
```
[core]
    autocrlf = false
```
to the .gitattributes) to avoid this bug-class
