### ISSUE TITLE
[Bug] Error launching KSP

### ISSUE THREAD

**Issue by CorSPACE** [KSP-CKAN/CKAN#2850]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.26.4
* KSP Version: 1.7.3.2594

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

I did a fresh install prior to installing CKAN

Problem
-------
CKAN will not launch KSP with the default command line argument or any other ones I found online

**CKAN error code (if applicable):**

```
Couldn't start KSP.

The system cannot find the file specified
```

**Comment by HebaruSan** [comment]
What is the command line configuration under Settings &rarr; KSP command-line?

**Comment by CorSPACE** [comment]
KSP_x64.exe -single-instance

**Comment by HebaruSan** [comment]
Thanks. If you click File &rarr; Open KSP Directory, does it open a folder, and if so, is there a KSP_x64.exe file there?

**Comment by CorSPACE** [comment]
No, This is a faked instance

**Comment by HebaruSan** [comment]
Instances that don't have KSP can't run KSP. That should not be a surprise.
