### ISSUE TITLE
CKAN doesn't do anything when I open it

### ISSUE THREAD

**Issue by Krakon01** [KSP-CKAN/CKAN#2860]
When I double click or right click>open ckan.exe loads for a short while then just stops. It isn't in task manager, it's nowhere, as if it hasn't even been opened.

EDIT1: DRAGON works properly, Orion doesn't.

**Comment by HebaruSan** [comment]
We need some background info to begin investigating (you can ignore the weird table at the very top):

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
