### ISSUE TITLE
Cannot force install a mod which is not supported [Bug]

### ISSUE THREAD

**Issue by xZise** [KSP-CKAN/CKAN#2868]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.26.4
* KSP Version 1.7.3 (basically fresh install, just played a bit without mods yet)

Problem
-------
Selecting any version of a mod to install, where no version supports the current version, doesn't make it appear in the change sets. For example when I select the any version of `PlanetShine`, no change entry appears. And if it is the only change, the tab also won't appear.

Selecting a mod which has support for the current version (e.g. `[x] Science! Continued`), does properly work and shows me the queued installation with the selected version. As a note I get the warning that the mod doesn't support the current version in both cases (`PlanetShine` and `[x] Science! Continued`).

For reference, if I read it correctly this feature was requested with #2822 and implemented in #2821.

**Comment by xZise** [comment]
Okay that part looks fixed, but now I've the issue that it says that dependencies are not compatible. Should I open a new bug report?

**Comment by HebaruSan** [comment]
No, it's supposed to say that.

**Comment by xZise** [comment]
But in this case it is a virtual dependency, so I couldn't even override that error message.
