### ISSUE TITLE
[Bug] New mod version isn't showed on the update screen

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2873]
New mod version isn't showed on the update screen

![](https://i.imgur.com/SipBXZo.png)

Expected "Update selected by user to version 0.5.0"

**Comment by HebaruSan** [comment]
Confirmed, the old (installed) version is added to the description here:

https://github.com/KSP-CKAN/CKAN/blob/baf9a7fb2f314c6aed9bb67bfa52d11989ed32e0/GUI/MainChangeset.cs#L66-L69
