### ISSUE TITLE
[Bug] Superfluous metadata changed message with non-normalized install_to

### ISSUE THREAD

**Issue by yalov** [KSP-CKAN/CKAN#2880]
already third time I got
![](https://i.imgur.com/ak1mCDm.png)

possibly an every bot iteration

**Comment by HebaruSan** [comment]
I think `install_to` is changing here, in the `TrimEnd` call:

https://github.com/KSP-CKAN/CKAN/blob/d79c04a47bde87d98bd1a29b638610630cdf4dc4/Core/ModuleInstaller.cs#L411-L413

https://github.com/KSP-CKAN/CKAN/blob/d79c04a47bde87d98bd1a29b638610630cdf4dc4/Core/KSPPathUtils.cs#L170-L178

That is called during installation, so the string with the trailing slash lasts from refreshing until you install it, at which point the trailing slash is removed from the available module, which is cloned to produce the installed module. So after installation they appear consistent, but then if you refresh again the trailing slash comes back. Kind of a nasty violation of the apparent immutability of a public property.

Looks like a pretty old bug that would affect any module with an `install_to` that isn't normalized (e.g., with trailing slash). For a short-term workaround, we can normalize the path in the netkan.

For a long-term fix we can follow through on the `TODO` comment above and normalize paths earlier. Might also make sense to normalize paths anytime we compare them, just in case things like this slip through in the future.

**Comment by HebaruSan** [comment]
Affected netkans:

- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/CommunityPartsTitlesExtrasNoCCKDup.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/VersatileToolboxSystem-USIPack.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/VersatileToolboxSystem-TACLSPack.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/BlacklegIndustriesMMTantaresTACLS.netkan
- https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/OinkersSkybox.netkan

**Comment by DasSkelett** [comment]
I found that too, but I'm wondering how this changes the stanza of the module in the end, since C# is call-by-value, or am I just brain-dead right now?

**Comment by HebaruSan** [comment]
Isn't it call-by-reference for object types? So the `stanza` object is passed in, and then its `install_to` property is assigned, affecting the original object.

**Comment by DasSkelett** [comment]
Yeah, finally found a good explanation of it [(but it's German)](http://www.lerneprogrammieren.com/blog/praxis/call-value-und-call-reference-bei-der-parameteruebergabe).
For primitives it always copies the value (call-by-value), for "reference types" (objects) it is some mix: the reference to the object is copied. So if you assign a new object to the parameter, it won't affect the outside object, but if you don't and manipulate the parameter, it will be visible outside...

Too wild mix of C and Python the last days...
