### ISSUE TITLE
[Feature] Dark mode

### ISSUE THREAD

**Issue by Brettdah** [KSP-CKAN/CKAN#2881]
Suggestions
-----------
It should be great if you could add a dark mode for the main windows late at night the window is killing my eyes ;)

Edit :
Oopsy may by the GUI redisign could be enough ;)
https://github.com/KSP-CKAN/CKAN/issues/2848

**Comment by DasSkelett** [comment]
I'm not sure on the Windows side of things, but on Linux Mono took the active GTK theme, so a dark theme was possible (and indeed used by me and @HebaruSan and maybe others).
But with the release of Mono 6 it broke again (after @HebaruSan contributed multiple commits to Mono to make it work), and Mono ignores the active theme again, thus you only have the standard white theme.

I think Windows added some darkmode functionality in the last couple of updates, but I don't know if it is only for UWPs or if you can somehow use it in .NET apps too.

**Comment by HebaruSan** [comment]
As stated, the loss of dark mode on Linux is a Mono issue (presumably an unintentional bug), but we've helped them fix things before. Investigation notes for that:

- It **does** still try to load the GTK colors in `X11DesktopColors`'s static constructor
  - In fact it gets all the way through that block of code
  - However, it looks like the values it retrieves are wrong:
    ```
    Button face: 240,240,240,255
    ```

**Comment by HebaruSan** [comment]
My fix for Mono was accepted, so Linux users should have dark mode again at some point in the hopefully not-too-distant future.

Windows users already have access to dark theming via the standard/classical desktop theme color settings:

![image](https://user-images.githubusercontent.com/1559108/69889600-c7622780-12e9-11ea-8eb0-8ed6d0a09372.png)

In Windows 7:

1. Right click desktop
2. Personalize
3. In the list of themes find the section at the bottom called "Basic and High Contrast Themes"
4. Choose High Contrast Black
5. Launch CKAN!

Yes, this will change the color of all your apps and taskbar and so on. I'm looking into a way around that now, there should be some way to combine this with the more modern Aero theming.

**Comment by HebaruSan** [comment]
OK, partial success with this method (it seems that not quite every color is theme-able):

1. Right click desktop
2. Personalize
3. Window Color (in the bottom middle)
4. Advanced appearance settings...
5. Choose the colors that you want to us
6. Launch CKAN!

![image](https://user-images.githubusercontent.com/1559108/69890422-794f2300-12ed-11ea-8e43-3d97a8a1ba24.png)

I'm going to see whether we can do anything at the application level to improve upon that, maybe there are a few hard coded colors left in there somewhere...

**Comment by HebaruSan** [comment]
Well, we can do significantly better in a dark theme context, but it requires turning off the "visual style" setting that gives the grid headers and inactive tabs a gradient. The result is a more Windows 95-98 look when NOT in a dark theme:

![image](https://user-images.githubusercontent.com/1559108/69895028-80435900-1320-11ea-968d-f02b62538d9d.png)

![image](https://user-images.githubusercontent.com/1559108/69895045-b7196f00-1320-11ea-801b-b1b8916a2475.png)
