### ISSUE TITLE
[Bug] Unclear problem when downloading

### ISSUE THREAD

**Issue by lx1587496147** [KSP-CKAN/CKAN#2885]
Background
----------
* Operating System: Windows7
* CKAN Version: 1.26.4
* KSP Version: 1.7.2.2556

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Not

Problem
-------
**Describe the bug**
If CKAN is denied access more than once during download and is not handled, another form exception will be triggered, and finally CKAN will stop working.

**Steps to reproduce**
* Go to...
Download
* Click on...
Apply changes
* See error

**Expected behavior**
Downloaded And Installed Mod.

**Screenshots (if applicable)**

![图片](https://user-images.githubusercontent.com/47657299/66469142-f0202a80-eab9-11e9-8689-88b4b24271f3.png)

**Comment by HebaruSan** [comment]
@lx1587496147 , what does that error message say in English?

**Comment by HebaruSan** [comment]
Can't investigate a message we can't read. @lx1587496147 , if you are able to provide a translation of the error message, please post it in a reply and we can re-open this.
