### ISSUE TITLE
File conflict with Ships/VAB/M2X Stork.craft

### ISSUE THREAD

**Issue by CKANNoob** [KSP-CKAN/CKAN#2894]
Background
----------
* Operating System: HP Spectre x360
* CKAN Version: 1.26.4
* KSP Version: 1.8.0.2686

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
only the deletion and re installation of both ckan and ksp + cache. 

Problem
-------
when after deleting my ckan cache, ckan application, ksp mod folder and the game and folder. i try to download my new first mod "Mk2 Stockalike Expansion 2:1.8.6" the error appears during download

I cant install mods when this error appears and i don't know another file where mods can be kept or hidden any ideas??

**Steps to reproduce** 
* Go to CKAN
* Click on... Any mod that adds new VAB ship parts 
* See error during status log 

**Expected behavior**
to complete download and function as intended 

**Screenshots (if applicable)**
none

**CKAN error code (if applicable):**

```
Error during installation!
An unknown error occurred, please try again!

Oh no! It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.
As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.
If you wish to install Mk2Expansion 2:1.8.6 via the CKAN,
then please manually uninstall the mod which owns:
Ships/VAB/M2X Stork.craft and try again.
```

**Comment by HebaruSan** [comment]
Try removing `Ships/VAB/M2X Stork.craft` as per the error

**Comment by CKANNoob** [comment]
sorry bit I can't find the file where woul I look for it? cause I deleted the ckan cache and ksp one too

**Comment by HebaruSan** [comment]
There is a Ships folder in the Kerbal Space Program folder. Check there.

**Comment by CKANNoob** [comment]
awesome that worked thanks!
