### ISSUE TITLE
[Bug] CKAN crashing with Unhandled Exception Autofac.Core.DependencyResolutionException

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#2897]
Background
----------
* Operating System: Manjaro Linux
* CKAN Version: Current Repo master branch
* KSP Version: 1.8.0
* Mono Version: 5.20.1.19-1 or 6.0.0.334-1
* nuget version: 2.14-2
* msbuild-stable version: 16.0_xamarinxplat.2018.09.26.17.53_0xamarin3_ubuntu1404b1-1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Not recently

Problem
-------
**Describe the bug**
CKAN crashes with Unhandled Exception
Running ./build test reports 391 failed tests

**Steps to reproduce**
run the program in the normal way

**Expected behavior**
It opens

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

https://pastebin.com/50nBxyY2
```
Test Run Summary
  Overall result: Failed
  Test Count: 638, Passed: 243, Failed: 391, Warnings: 0, Inconclusive: 0, Skipped: 4
    Failed Tests - Failures: 17, Errors: 374, Invalid: 0
    Skipped Tests - Ignored: 0, Explicit: 4, Other: 0
  Start time: 2019-10-21 01:09:15Z
    End time: 2019-10-21 01:09:30Z
    Duration: 15.587 seconds

Results (nunit3) saved as TestResult.xml
An error occurred when executing task 'Test-UnitTests+Only'.
```

**Comment by HebaruSan** [comment]
Can you share your `~/.local/share/CKAN/config.json`? Looks like it's not parsing correctly.

**Comment by politas** [comment]
https://pastebin.com/qr4P4nBV

**Comment by politas** [comment]
Note, if I try building with Mono 6.0.0.334-1, the build fails, too.

**Comment by HebaruSan** [comment]
I think some file format changes were made after yours was generated. Try changing `AuthTokens` to:

```json
  "AuthTokens": {
    "github.com": "**nope***"
  },
```

**Comment by politas** [comment]
Ah! Fixed! Excellent!

**Comment by politas** [comment]
is this going to be an issue for other users, or is it only because I've been running dev builds?

**Comment by HebaruSan** [comment]
Dev builds. I thought we made that change before merge.

**Comment by politas** [comment]
Entirely possible.
