### ISSUE TITLE
[Bug] "Launch KSP" Button not working

### ISSUE THREAD

**Issue by hinneLinks** [KSP-CKAN/CKAN#2902]
Background
----------
* Operating System: Ubuntu 18.04.3 LTS
* CKAN Version: v1.26.4
* KSP Version: 1.8.0.2686

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Yesterday i opened Steam, and that updated my KSP vrom 1.7 to 1.8. Since then the Button "Launch KSP" in CKAN does nothing, KSP wont open.
For every Button-Click i see this in the console (if i start CKAN via terminal):
`Found path: /data/SteamLibrary/steamapps/common/Kerbal Space Program/./KSP.x86_64`
I also tried turning the log on, there for every click on the Button Messages like this appear for each Mod i've installed:
`2019-10-23 19:24:00 DEBUG CKAN.CkanModule - Testing if SCANsat v18.13 is compatible with KSP [Versions: 1.8.0.2686, 1.8, 1.7, 1.6, 1.5]
`
No other logs are created on the Button-Click. No ERROR or WARN Log Messages at all.
Worked with KSP 1.7.3.2594 I've tried to downgrade KSP via Steam (https://steamcommunity.com/sharedfiles/filedetails/?id=1086279994), but then even 1.7 didn't work anymore. Reinstalling CKAN or removing all Mods didn't help either. 

Starting KSP via Terminal or Steam works fine, including the Mods installed.

**Steps to reproduce**
Open CKAN
Click on "Launch KSP"
*nothing happens*

**Expected behavior**
KSP should start

**Comment by HebaruSan** [comment]
What's in your Settings &rarr; KSP command-line?

![image](https://user-images.githubusercontent.com/1559108/67428291-7735ce00-f5a3-11e9-8c88-276712623507.png)

**Comment by HebaruSan** [comment]
Also, does that file exist on your system?

`/data/SteamLibrary/steamapps/common/Kerbal Space Program/./KSP.x86_64`

**Comment by hinneLinks** [comment]
The command line settings where a good hint, mine where:
`./KSP.x86_64 -single-instance -popupwindow`
I only added the `-popupwindow`.
When I remove the `-single-instance`, KSP starts again clicking the "Launch KSP" Button.

So its not directly a CKAN-Problem. It might be an [Unity Problem](https://issuetracker.unity3d.com/issues/linux-segmentation-fault-when-running-a-built-project-with-single-instance-argument).

Nevertheless, I never set that parameter, it is a CKAN Default:
https://github.com/KSP-CKAN/CKAN/blob/d00a9f22bb6b3ce077f02ee760028344f7bf870a/GUI/GUIConfiguration.cs#L103

May be the `-single-instance` should be removed as a default? It only prevents multiple Instances, see [here](https://docs.unity3d.com/Manual/CommandLineArguments.html).
I don't see any use in it, there are even addons for Multi-Window out there that uses two KSP-Instances.

**Comment by HebaruSan** [comment]
I'm also on Ubuntu, can confirm a seg fault with that argument:

```
$ ./KSP.x86_64 -single-instance
Set current directory to /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program
Found path: /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/KSP.x86_64
Segmentation fault (core dumped)
```

Thanks for catching this!

**Comment by HebaruSan** [comment]
Apparently the reason for this was that people were double-clicking the button:

- KSP-CKAN/CKAN#1232
- KSP-CKAN/CKAN#1255

**Comment by hinneLinks** [comment]
Ah, the famous doubleclicker, make sense.
Can't mono detect the douebleclicks? Maybe only starting a KSP-Session once every 3 Seconds or so would help.

**Comment by HebaruSan** [comment]
I'm not sure that having a workaround for double clicking is necessary.

![doctor meme](https://www.azquotes.com/picture-quotes/quote-the-patient-says-doctor-it-hurts-when-i-do-this-then-don-t-do-that-henny-youngman-129-8-0851.jpg)

**Comment by Robou** [comment]
I am also on Ubuntu and I had exactly the same bug. And I deleted "-single instance" and it worked too.
Thanks

**Comment by hinneLinks** [comment]
> I'm not sure that having a workaround for double clicking is necessary.
Yeah, I agree. At least Linux People should now how to click. On the other hand, people like my mom doublecklick mostly everything. But she isn't playing KSP so delete that argument as Default.
