### ISSUE TITLE
No Altimeter when launching from Ckan

### ISSUE THREAD

**Issue by MytosBR** [KSP-CKAN/CKAN#2905]
I always used ckan without any troubles. Now when I launch KSP my altimeter dosen't display numbers on it for some reason.

I found out that when I launch from the steam library my altimeter works just fine, but if I launch from Ckan there are no numbers on it, even if I have no mods at all.

Anyone using Ckan have this issue? Anyone using Ckan have their altimeters working normally?

Any clues on how to fix it?

**Comment by DasSkelett** [comment]
Please fill out the issues template (see https://github.com/KSP-CKAN/CKAN/issues/new/choose), we need some infos like KSP version, CKAN version and so on.
What did you change before this problem arose?

**Comment by MytosBR** [comment]
As above on the OP
----------
* Operating System: W10
* CKAN Version: 1.26.4
* KSP Version: 1.8.0.2686

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Whenever I reduce the UI scale of both the navball or the altimeter the numbers on the altimeter goes blank.


**Steps to reproduce**
* Set a pod or ship on the launchpad
* Click on settings and change the UI scale. Quit to main menu, load your game and go back to the launchpad.
* See there is no numbers showing up on the altimeter anymore.

Alternatively, when you open settings in the launchpad, change individual scales for the navball and altimeter and you will see that the altimeter looses the number under 100% or when the navball goes down from 94%.

**Expected behavior**
 Altimeter will only show numbers at 100% UI scale.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**
No error code
![KSP CKAN Support](https://user-images.githubusercontent.com/57037794/67620584-e4817300-f7de-11e9-906d-f3f22822c4f7.jpg)

**Comment by DasSkelett** [comment]
Hmm, doesn't sound like a issue of CKAN itself.
Maybe it's the Windows equivalent of #2902?
Can you look at Settings > KSP commandline in CKAN and paste the content here?
Remove `-single-instance` and try again.

Have you set anything special in your Steam commandline settings?

**Comment by DasSkelett** [comment]
I knew I've read already about this bug:
https://forum.kerbalspaceprogram.com/index.php?/topic/188994-ksp-180-altimeter-blank-when-full-screen-win10/

This is a KSP bug. No idea why this only happens to you if you start via CKAN. Are you starting in windowed mode via Steam?

**Comment by MytosBR** [comment]
The command line is: KSP_x64.exe -single-instance
There is no command line added.
I tried again and nothing changed.

Should I reinsert the -single-instance on the command line again?

**Comment by DasSkelett** [comment]
You don't need to, it's just there to prevent people from opening KSP twice on double-clicks. Apparently it makes problems since 1.8.0 on Linux based OSes, but seemingly not Windows.

You should get the Altimeter bug when you launch via Steam too, are you sure that's not the case?

**Comment by MytosBR** [comment]
Ok, People on steam already warned me it's a known bug.
I am starting the game form my steam library, using the launcher not in Big Picture mode. The game is set to run on fulscreen.  I use 2 monitors.

I will just go double ckeck if it's not happening when launched form steam. I am sure I tryed and it worked, but I will make sure. Give me a couple of minutes and I will get back to you.

Thank you.

**Comment by MytosBR** [comment]
So, I tried to reproduce what i saw earlier and I couldn't.
Maybe it was in the first launch after install the game when the game was windowed or with other resolution. I am getting know the same results when launching from CKAN and from Steam.

I know I am not crazy, but I must had mave done something wrong.

As Joseph Campbell says: Computer are like old testament Gods, lots of rules and no mercy!

Thanks anyway, I think this should be an easy fix for Squad and it seems they are aware of the issue.

**Comment by DasSkelett** [comment]
Thanks for checking it out again!
I'm sure 1.8.1 will have the fix in it.
