### ISSUE TITLE
[Bug] Newtonsoft.Json.JsonReaderException: Bad JSON escape sequence: \U. Path 'DownloadCacheDir'

### ISSUE THREAD

**Issue by empereur51100** [KSP-CKAN/CKAN#2910]
Background
----------
* Operating System: windows 10 pro
* CKAN Version: 1.26.4
* KSP Version: 1.8.1.2694

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
Ckan not run
**Describe the bug**
when i run ckan from the KSP root i get this window.
https://zupimages.net/up/19/44/k5se.png
the KSP address where I put CKAN is C: \ Program Files (x86) \ Steam \ steamapps \ common \ Kerbal Space Program, but after instal it, i find in the folder  in C: \ Users \ name\ AppData \ Local \ CKAN, the file named "config.json" gives the path "W: / SteamLibrary / SteamApps / common / Kerbal Space Program, 
W: w is dead and remove from my computer from long time and I deleted all the "ckan" file on all the disks, but still impossible to make CKAN work, some one can help me ? 
thanks

(sorry for my bad english, im french ^^)

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Please show us the beginning of that error message. That's where the important information is.

**Comment by empereur51100** [comment]
Thank you for your reply

this is the full windows
[url=http://zupimages.net/viewer.php?id=19/44/4u36.png][img]https://zupimages.net/up/19/44/4u36.png[/img][/url]

**Comment by HebaruSan** [comment]
Can you scroll up further? That's not the beginning, you can see that the top line says `istingValue)`, which is the last part of a line that has been cut off.

**Comment by empereur51100** [comment]
the window remains open for less than 2 seconds
I'm going to try

**Comment by empereur51100** [comment]
[[url=http://zupimages.net/viewer.php?id=19/44/gj8a.png][img]https://zupimages.net/up/19/44/gj8a.png[/img][/url]](url)

**Comment by HebaruSan** [comment]
Thanks! That's what we needed.
There's something about your download cache folder setting that it doesn't like. Can you take a look at it and let us know what it is? 
`C:\Users\<username>\AppData\Local\CKAN\config.json`
See the discussion in #2907 for further details.

**Comment by empereur51100** [comment]
thank you, in the registry, I found I had not thought about it !! thank you very much HebaruSan !! :-)

**Comment by HebaruSan** [comment]
@empereur51100 did you find the download cache folder setting? If so can you tell us what it was?
