### ISSUE TITLE
The Update column is gone after crash.

### ISSUE THREAD

**Issue by Frank-Einstein** [KSP-CKAN/CKAN#2917]
Background
----------
* Operating System: Windows
* CKAN Version: 1.26.4
* KSP Version: 1.7.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, I have some mods installed manually.

Problem
-------
**Describe the bug**

I updated a mod using CKAN (clicked the "Update" box of the mod, then Apply)
and CKAN crashed during the update. I restarted it, everything is normal except the update column is not there anymore. 
I right-clicked on the tabs (Inst, auto-inst, name...) but "updates" is not in this list either.
Also, renaming GUIConfig.xml didn't help.

Is there anything I can try before reinstalling CKAN?
(I already exported all my mods to a .ckan file, just in case.)

**Comment by HebaruSan** [comment]
> I updated a mod using CKAN

- Which mod?
- Which version of that mod does CKAN say you have installed now?
- Which version of that mod does CKAN say is the highest available now?

**Comment by Frank-Einstein** [comment]
I'm not entirely sure what mod I was curently updating. I wasn't expecting CKAN to crash... 
I think it is 'TAC fuel balancer' because this mod was corrupted just after the crash (Missing toolbar icon). 
Updating mod from 2.21.4.0 to 2.21.4.1

Before the crash I updated many mods without any issus but I had some problems with my hdd recently with random files that can't be deleted, apparently for 'being used by explorer.exe' , so this also might be the reason of the crash...

If you need to take a look at a config file, I can post it if you want.

**Comment by HebaruSan** [comment]
@Frank-Einstein , thanks for the detailed response.
The thing I was trying to determine with those questions was whether the Update button is **supposed to** be displayed for you right now. If CKAN finished installing the update (or *thought* it finished installing the update) before the crash, then it's possible that CKAN thinks you have the latest version and therefore do not need to access the Update button. The update column automatically hides itself when all mods are up to date.

**Comment by Frank-Einstein** [comment]
"The update column automatically hides itself when all mods are up to date."
I didn't know that... So, maybe CKAN crashed when I was updating the last mod requiring an update?

OK, I verified all my mods, everything seems up-to-date... then, clicked the refresh button...
It found a new update, the update row is back!

I'm sorry for the confusion!
I didn't know it was only there when there is new updates.
Problem solved!

Thank you for your support!

**Comment by HebaruSan** [comment]
Sounds like everything is in order. Thanks for your patience!
