### ISSUE TITLE
[Bug] Epoching old mods breaks archive.org fallback URLs

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#2938]
## Background

* Operating System: Windows, Linux
* CKAN Version: 1.26.6
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
:poop:

## Problem

**Describe the bug**
While cleaning up old version epochs in KSP-CKAN/CKAN-meta#1574, I realized that epoching a historical version breaks its automatic archive.org fallback from #2284. There were a few in that PR that are only available on archive,org since they've been removed from GitHub, and they failed to download when the validation scripts attempted to install them. Checking https://archive.org/details/kspckanmods , the mods *were* there, just without an epoch.

**Steps to reproduce**
* Add a netkan for a mod with a redistributable license
* Allow multiple versions of this mod to be indexed; its releases will be added to archive.org automatically
* Remove the original downloads for some of the older versions; the CKAN client will still be able to download them from archive.org 
* Edit the .ckan files in CKAN-meta to change the mods' epochs
* Now the fallback doesn't work

**Expected behavior**
Somehow find the original uploads to archive.org 

## Suggestions

1. Strip epochs when archiving; archive.org would have only the pure upstream version numbers
2. Run a conversion on the currently archived mods to remove epochs
3. Strip epochs out when the download fallback code runs

We would need to figure out a migration strategy; clients from before and after step 3 would expect different fallback URLs, so steps 1 and 2 would need to run at a time that would be minimally disruptive to users.

**Comment by DasSkelett** [comment]
This came to my mind: The pure upstream version part doesn't have to be unique currently. It's theoretically possible that the version exists with two or more different epochs, for example if someone forgot to delete the old ckan file after epoching the netkan.
However, it is very likely that all versions with the same base part are pointing to the same download, so the archived file remains the same in the end.

In this case we just have to deal with it in the mirrorer/converter and decide what to do if the version already exists.

**Comment by techman83** [comment]
1. Agreed. The epoch's are purely an operational thing for CKAN and don't belong as part of archive.org.
2. We can alter the metadata and identifiers of the archived items.
    - Do we want to do this? (I have no strong feelings either way, but we should think on it)
    - This will be a reasonable undertaking, but shouldn't be super hard.
3. Options pending on if step 2 is done.
    - Pretend epoch'd archived items don't exist, we can back fill all epoch'd CKANs with alternate 
download links (this is potentially a lot of items)
    - Fallback fallback? Try stripped, then try with epoch? (this sounds ugly)

I had that same thought @DasSkelett - in theory the put will just add extra files to the item on archive.org and we'll still pick up the right one when it comes to fallback. But it muddys the meta data a little. I guess it comes down to how much we care about this edge case and should we be relying on more data for our identifiers?
