### ISSUE TITLE
I can't download realisam overhaul via ckan

### ISSUE THREAD

**Issue by EpicSpaceMan** [KSP-CKAN/CKAN#2943]
Background
----------
* Operating System: Windows 10
* CKAN Version:  1.26.6
* KSP Version: 1.3.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
I was trying for 2h to get realisam overhaul installed unfortunately it didn't work it (see error below)

I deleted the folder nothing happened 

I put it back nothing happened

I might try just deleting E42.png

**Steps to reproduce**
* Select realism overhaul all normal options
* Apply changes
* See error below

**Expected behavior**
Instalation completed

**CKAN error code (if applicable):**

```
Oh no!

It looks like you're trying to install a mod which is already installed,
or which conflicts with another mod which is already installed.

As a safety feature, the CKAN will *never* overwrite or alter a file
that it did not install itself.

If you wish to install FerramAerospaceResearch 3:0.15.9.1 via the CKAN,
then please manually uninstall the mod which owns:

Ships/@thumbs/SPH/E42.png

and try again.
```

**Comment by EpicSpaceMan** [comment]
I have fixed the issue by deleating all ships Thumbs And craft files

**Comment by DasSkelett** [comment]
Was just about to write the following:

Did you closely follow the [installation instructions of the KSP-RO wiki](https://github.com/KSP-RO/RP-0/wiki/RP-1-v1.1-Installation-Instructions)?

Especially, was your installation completely clean before beginning the install? Nothing leftover in GameData?

If it _was_ empty, and you _did_ follow the installation instructions, I'd guess there are two mods trying to install the same craft file.

**Comment by EpicSpaceMan** [comment]
I did exactly as you said thx for replaying tho
