### ISSUE TITLE
Can a mod depend on another mod, when the dependency is not compatible with the current game?

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2951]
Here is the situation:  

1.  The mod, AIES Aerospace, is only compatible for 1.0.5, and license restrictions prevents it from being distributed any other way
2.  I'm about to release a patch mod which updates it to 1.8.1.  
3.   AIES is installed into a 1.8.1 gameby changing the compatibility setting.  After installation, the compatibility setting change is undone

What would happen if the new mod had AIES as a dependency?  Would it be available in 1.8.1, or not?

Thanks in advance

LGG

**Comment by HebaruSan** [comment]
What exactly do you mean by "changing the compatibility setting" ? Are you talking about a version file? Something in a DLL?

**Comment by HebaruSan** [comment]
Oh, maybe you meant the compatibility setting in CKAN. If you make a module for 1.8.1 that depends on a module for 1.0.5, this is what would happen:

CKAN compatibility | Old mod | New mod
--- | --- | ---
1.0.5 | Installable | Not installable
1.8.1 | Not installable | Not installable
1.0.5, 1.8.1 | Installable | Installable

So yes, the user would have to have both 1.0.5 and 1.8.1 marked compatible, and that would allow installation of both mods.

**Comment by HebaruSan** [comment]
I think this was resolved in KSP-CKAN/NetKAN#7600.
