### ISSUE TITLE
List of incompatible mods is hard to read

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#2954]
When starting a game with a number of mods which, according to CKAN, are not compatible, a dialog is show with all the mods listed in a single line of text.  It's hard to read.

Would be better to show a listbox , or at least a text field with one mod per line

**Comment by HebaruSan** [comment]
I assume you're hitting this because of the AIES stuff?

**Comment by linuxgurugamer** [comment]
At this point, I can't reproduce this, and don't even remember what caused it.  I'll close for now, will reopen if I get it again

**Comment by linuxgurugamer** [comment]
What I did notice was that the AIES patches, are NOT available unless I go into the settings and make 1.0 compatible so that the original mod becomes compatible.  not sure if this is something that can be fixed or not, I thought we had fixed it a while ago

**Comment by HebaruSan** [comment]
@linuxgurugamer I think you're referencing #3000, which was closed without code changes after a workaround was suggested.

Here's the warning I get if I mark 1.0 as compatible, install the AIES patches, and then remove 1.0 from compatibility:

![image](https://user-images.githubusercontent.com/1559108/80557920-1ea21c00-899e-11ea-974e-faabde08c3f5.png)

I think it's fair to point out that this UI could be improved (along with #2955), might as well keep this open for a while.
