### ISSUE TITLE
[Feature] CLI should auto-detect KSP install based on working directory

### ISSUE THREAD

**Issue by blowfishpro** [KSP-CKAN/CKAN#2956]
I use the CKAN CLI when I'm on my (OSX) laptop.  It works fine but it's quite annoying to have to pass the `--ksp whatever_install` parameter to every call that needs it.  Very often I find myself making the calls from within that KSP install's directory anyway.

Setting a default install works but is annoying, especially when I need to change installs (and as a modder I often find myself with several for testing different things).

So it would be great if the CKAN CLI would auto-detect an install if the current working directory is in that install or a subdirectory.  This would take lower priority than the default install or directly specifying the `--ksp` option.

I think I see how to implement this, just wanted to get buy-in before I started trying to work on it.

**Comment by HebaruSan** [comment]
I think you can do something similar with the "portable" installs feature. If you put a `ckan.exe` file in each game folder and then run that local copy, it should find an install at the executable's folder. I.e.:

```bash
$ cd ~/.ksp-1.7.3-testing
$ ./ckan.exe list
```

(Obviously that's not as convenient as being able to run it from your PATH.)
