### ISSUE TITLE
[macOS] version numbers of '1.26.8' release are broken

### ISSUE THREAD

**Issue by core-code** [KSP-CKAN/CKAN#2977]
the version numbers of the '1.26.8' release are broken. if you select the app on the Mac via 'Column View' or open 'Get Info' or'QuickLook', you'll see that the app claims to be version '1.26.6'

the 'CFBundleShortVersionString' and 'CFBundleVersion' entries in your 'Info.plist' have not been updated for this release:

<img width="298" alt="Screenshot 2020-01-29 at 20 38 45" src="https://user-images.githubusercontent.com/1261954/73391093-9e551780-42d7-11ea-88f4-13093cef905c.png">

**Comment by DasSkelett** [comment]
I hope I didn't build the wrong version...

**Comment by DasSkelett** [comment]
It was indeed 1.26.6 in `Info-plist`, after rebuilding it's 1.26.8.
@core-code, what does CKAN display in the title bar when you start it? v1.26.8 or v1.26.6?

**Comment by HebaruSan** [comment]
We can check that ourselves:

```bash
$ 7z x CKAN.dmg
$ mono CKAN.app/Contents/MacOS/ckan.exe
```

Mine says 1.26.8, so looks like a packaging issue.

**Comment by DasSkelett** [comment]
Okay, I guess it just didn't overwrite the `Info.plist` file for some reason. I cleaned the build output folder this time before building, and it has the right version now.

I'll replace the asset once more to avoid confusion. The deb is fine, the rpm doesn't seem to have any internal metadata files, and the filename is right.

**Comment by core-code** [comment]
i can confirm the issue is fixed in the updated download. thanks for the super-quick turnaround here!
