### ISSUE TITLE
[Bug] Latest Release pulls in incompatible versions of mods

### ISSUE THREAD

**Issue by Theysen** [KSP-CKAN/CKAN#2979]
Background
----------
* Operating System: Windows 10 Professional
* CKAN Version: 1.26.8
* KSP Version: 1.7.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

-

Problem
-------

CKAN downloads the latest release despite having 1.8 deselected as compatible and 1.7.3 marked as compatible although the latest release is clearly versioned for 1.8 and greater. 
When selecting the mod, CKAN actually lists the correct version number for the latest 1.7.3 release of a mod, the versions tab also has the compatible version marked correctly, yet it installs the latest version for 1.8.
Did not happen with the prior release for me. 
Best explained in screenshot section. 

**Steps to reproduce**
* Install 1.7.3
* Start CKAN for that new install
* Select compatible versions for 1.7 (and/or below)
* Choose  correctly versioned example mod for download (SCANsat here)
* Install and check versioning tab

**Expected behavior**

Install latest compatible version respecting the mods versioning and compatibility.

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/15719566/73535736-93f46400-4424-11ea-8645-882cd8a9ce74.png)

![image](https://user-images.githubusercontent.com/15719566/73535790-b5ede680-4424-11ea-85bb-c861eff0d26e.png)

![image](https://user-images.githubusercontent.com/15719566/73535811-c56d2f80-4424-11ea-98f6-95dcc17e42d1.png)

![image](https://user-images.githubusercontent.com/15719566/73535819-cbfba700-4424-11ea-8c09-d4fbd24fa1d1.png)

![image](https://user-images.githubusercontent.com/15719566/73535831-d322b500-4424-11ea-868c-679b4907b2aa.png)

Error on my end somehow? It's all fresh and no caching. 
Need any logs / files from that directory?

Cheers
Theysen

**Comment by HebaruSan** [comment]
Yikes!

https://github.com/KSP-CKAN/CKAN/blob/7dbae84ba26e1de9eabbe5e8bbfa9cf0d8f1560c/Core/Registry/Registry.cs#L487

**Comment by HebaruSan** [comment]
Thanks for catching this!
