### ISSUE TITLE
[Bug] Mod installed by CKAN not shown in it

### ISSUE THREAD

**Issue by CommodoreGamer118** [KSP-CKAN/CKAN#2982]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.26.8
* KSP Version: 1.8.1.2694

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, I installed: reDIRECT, Benjee_10Shared assets, PlumeParty, htRobotics, Benjee_10 Shuttle Orbiter

Problem
-------
**Describe the bug**
CommunityResourcePack was installed via the previous version of CKAN ´´Orion´´ 
In the new version CommunityResourcePack is avaible for install, when its already installed.

**Steps to reproduce**

(Not sufficient to reproduce)

1. In previous version of CKAN ´´Orion´´ , install CommunityResourcePack
2. Update to CKAN 1.26.8
3. CommunityResourcePack is avaible for install

**Expected behavior**
CommunityResourcePack should be shown as already installed.

**Screenshots (if applicable)**
![imagen](https://user-images.githubusercontent.com/59520953/73598220-1e0efc00-44fb-11ea-926b-78896ab73935.png)
![imagen](https://user-images.githubusercontent.com/59520953/73598237-43036f00-44fb-11ea-8626-3684af26fe30.png)
**Aditional notes**
I guess this is important because some who uses just CKAN and makes a bug report when mod liist is required, the CKAN mod list will not be complete

**Comment by HebaruSan** [comment]
How exactly did you install and run the new CKAN? Via the autoupdater? Manually?

**Comment by CommodoreGamer118** [comment]
Autoupdater, i always like auto things and i suck at installing them manually.

**Comment by HebaruSan** [comment]
Thanks. We'll need to figure out how to make this happen on-demand in order to fix it, so I have a few more questions...

- Were any other mods affected similarly, or just CRP?
- Had you just installed CRP or was it installed for a long time?
- Was it like this immediately after you started using the new version, or did it happen later?
- Did you do anything else that might be relevant, such as following the [clean and reinstall process](https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process)?

**Comment by CommodoreGamer118** [comment]
1.- Just CRP
2.- 1 Week before Kodiak was released
3.- Immediately
4.- No

**Comment by HebaruSan** [comment]
OK, I tried installing CRP in 1.26.6 and then opening 1.26.8 (it says .9 because it's a dev build, but it's the same), and everything worked fine:

![image](https://user-images.githubusercontent.com/1559108/73598576-10c13400-4532-11ea-9a38-c25c41396c80.png)

Not enough info to fix at this time. If anyone else sees something similar, please let us know what additional steps are needed to reproduce.

**Comment by CommodoreGamer118** [comment]
Alright, that was my copy install, if i go to my main install (with more mods from CKAN) there are more mods not showing as installed, for example AdjustableModPanel 
![imagen](https://user-images.githubusercontent.com/59520953/73599177-3afcfc80-4506-11ea-8693-0a46d27d0fa1.png)
![imagen](https://user-images.githubusercontent.com/59520953/73599179-45b79180-4506-11ea-825b-9879d38e2f8e.png)
ContractConfigurator
![imagen](https://user-images.githubusercontent.com/59520953/73599189-67b11400-4506-11ea-9e91-d6bfd3495869.png)
![imagen](https://user-images.githubusercontent.com/59520953/73599191-73043f80-4506-11ea-8e64-87ce52ac3ca2.png)
Mining Expansion
![imagen](https://user-images.githubusercontent.com/59520953/73599201-95965880-4506-11ea-95b8-62b38d61ddef.png)
![imagen](https://user-images.githubusercontent.com/59520953/73599204-a0e98400-4506-11ea-8d17-06a11a6860f2.png)
That means some other mods have the same problem, it is not just CRP
What more info can i provide to close the issue?
Is anything else relevant?

**Comment by HebaruSan** [comment]
What we need is the steps to make this happen, in other words what you're doing differently from me. Unfortunately this can be difficult to determine, since each person brings their own assumptions about how things are done normally; that's why it's so helpful to specify in detail every single thing that you do without leaving anything out. Often a lot depends on the person experiencing the bug; #2967 was a bug for 4 years and there were sporadic reports for 2 years before someone finally pinned down a set of steps that allowed us to crack it. Till then all I can do is ask about factors that might be relevant, such as...

- How many game instances do you have registered with CKAN?
- Where is your ckan.exe file installed, in one of the game dirs or somewhere else?

**Comment by CommodoreGamer118** [comment]
1.- Two installs, the main one and the copy one
2.- In both game dirs (I think thats bad)
3.-Installed
Extremely detailed steps (I think) : Open Orion version of CKAN, Install newly CRP for example, wait until Orion asks you to update THAT CKAN install, when done autoupdating, open THAT updated CKAN, note the CRP is avaible for install.
I think thats detailed enough? Its my first time opening an issue.

**Comment by HebaruSan** [comment]
It might be worth having a look at your registry file...

1. Launch CKAN
2. File &rarr; Open KSP Directory
3. Open the CKAN folder
4. Find `registry.json`
5. Put it in a ZIP file
6. Back here on GitHub, click the bottom margin of the comment box to attach the file to a reply

I can imagine certain scenarios in which the modules are actually tracked as installed behind the scenes but a race condition causes confusion in the GUI, for example.

____

> wait until Orion asks you to update THAT CKAN install

What does that mean? What exactly is it asking you?

**Comment by CommodoreGamer118** [comment]
When a new version is released CKAN launches a pop-up telling you to update, you need to accept updating and wait untill its done.
[Registry JSON.zip](https://github.com/KSP-CKAN/CKAN/files/4143308/Registry.JSON.zip)
(I dont know if it needs WinRar, probably not)

**Comment by CommodoreGamer118** [comment]
Alright, the new release Alcubierre has nt fixed the issue (just letting you know) 
Some information that can be usefull is: 
When i try to install it again the CKAN says the following:
![imagen](https://user-images.githubusercontent.com/59520953/73610906-17878f80-45a2-11ea-9477-06889ff9b28c.png)
So, when installing CRP, CKAN does detect it there, but if i go again in  Installed filter, no CRP is listed, not even an ´´AD´´ mark.
**ADITIONAL NOTE**
It is very hard to notice this issue, I did just detected it because i was making a mod list to report a bug in the KSP forums, and i knew that CRP was installed when I saw the incomplete mod list.

**Comment by HebaruSan** [comment]
> the new release Alcubierre hasnt fixed the issue (just letting you know)

To try to set expectations on this, **no** future update will ever bring these mods back as CKAN-installed by itself. Looked at your `registry.json` file, contrary to my previous suspicion, they're not listed as installed. That will still be the case from now on, unless you remove them manually and re-install in CKAN.

My current best guess is that you experienced some variant of #2967 for a particular batch of mod installs on CKAN 1.26.6 before upgrading and didn't notice it for a while, and then after upgrade you had a reason to look at the mod list in detail and spotted that those mods were missing. There are a number of possible ways this could have happened given that you're using "portable" installs (ckan.exe in the KSP folder).

The thing to watch for at this point is *additional* mods disappearing, or mods that can be definitively confirmed as shown as installed in CKAN 1.26.6 that then revert to not-installed or manually installed on CKAN 1.26.8+.

**Comment by CommodoreGamer118** [comment]
Actually I remember that i installed it, so i knew it was there and constantly checking for it due to some mods having that as a hard depency, i might try to get screenshots from Orion but i have no idea how to revert version.

**Comment by HebaruSan** [comment]
If you want to try it all again, you can download the previous version and run it. It would be great to find out if you can make it happen again:

- https://github.com/KSP-CKAN/CKAN/releases/download/v1.26.6/ckan.exe

(Previous version was Leonov, not Orion)

**Comment by CommodoreGamer118** [comment]
Hmmm, well, in CKAN v1.26.6, CRP was still missing, ouch for me, uninstalled it, reinstall from CKAN, this time it was shown, updated THAT CKAN to Alcubierre, already shown, I couldn´t reproduce the issue as you couldn´t too, well, idk what to do next, i have no more information to provide and no tests to do, I think this is a one-time issue, I guess I will keep this issue open?

**Comment by HebaruSan** [comment]
I think we can regard that as confirmation that this was a variant of #2967. There's not much point in leaving it open if there's nothing we can investigate. If you manage to make it happen again, let us know and we can re-open.
