### ISSUE TITLE
Detection of fancy-pants steam installs

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#30]
People can have steam-managed installs of KSP in all sorts of locations. Apparently there are registry keys we can poke at, and files we can parse to figure out where they are.

We already handle detection of default location steam/KSP installs across all platforms.

Branched from #23 .

**Comment by HebaruSan** [comment]
I think this was completed in #146. The current code looks up a Steam registry key on Windows here:

https://github.com/KSP-CKAN/CKAN/blob/62a0bc7c32686df333e9319082349fd332aa7c25/Core/CKANPathUtils.cs#L42-L50

This is used to find Steam's `config/config.vdf`, which lists the Steam library locations, each of which is checked for a `SteamApps/common/Kerbal Space Program` folder:

https://github.com/KSP-CKAN/CKAN/blob/62a0bc7c32686df333e9319082349fd332aa7c25/Core/Games/KerbalSpaceProgram.cs#L49-L73
https://github.com/KSP-CKAN/CKAN/blob/62a0bc7c32686df333e9319082349fd332aa7c25/Core/Games/KerbalSpaceProgram.cs#L337-L342

That seems to satisfy the intent of this issue. If more is needed, we'd have to know what was missing in more detail.
