### ISSUE TITLE
Add a way for a patch to allow an otherwise incompatible mod to be installed

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3000]
There are a number of mods which are old and outdated, for which there are current patches which bring the mod up-to-date.

One in specific is AIES Aerospace, which is only listed for 1.0.5.
I've created a set of patches for it which modernizes it for 1.8.x.

It would be nice if there was a way to allow the patches to be installed, and at the same time to install AIES

**Comment by HebaruSan** [comment]
I don't think we should do this. Version compatibility is already complicated enough as it is without allowing overrides by random third party modules, and it would open the door to shenanigans where a depending mod with a metanetkan decides to pretend it's a "compatibility patch" just to make some dependency available on an unsupported version.

It gets hairier once you get into the details:

- Does the incompatible mod stay compatible if I uninstall the patch?
- What if two of my installing mods want to make *different* changes to the compatibility of a third module, who wins?

Adding 1.0.5 as a compatible version temporarily is a good enough workaround for one case of this.

**Comment by politas** [comment]
You could create a new "AIES Aerospace-Patched" mod listing with compatibility "Any", which downloads the unpatched mod and has a dependency on the patch, so you can control the compatibility with the patch. No code changes required!
