### ISSUE TITLE
[Feature] Do not display max version 1.99 as ANY

### ISSUE THREAD

**Issue by ihsoft** [KSP-CKAN/CKAN#3016]
Problem
-------
My mod [EVS](https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/EasyVesselSwitch.netkan) defines maximum version of KSP as `1.99` (and I'm going to change KIS, KAS and SurfaceLights as well). CKAN client displays this version as "any". However, my intention was not setting upper bound to "any" version. In the past 3 or 4 minor version releases of KSP the changes were not breaking (as opposed to what they used to be in the past). So, I reasonably assume that the Squad team started following a usual approach to the versioning, where the major version number stands for the compatibility. Thus, I set the max version to some maximum value in scope of "major version one" - `1.99`. Otherwise, each improvement to the game (for which we all are very grateful!) would trigger senseless mod update and people guessing if the mod is compatible.

Suggestions
-----------
Can we make a distinguished constant for "any version"? It's ok if this constant will be `1.99` (for the historical reasons). I'd reasonably assume that the next "really incompatible version" will be `2.x`. Maybe not, but likely. Given how the new versioning model is working.

I'd love to have a constant, that marks my mod as "for any _major_ version X".

**Describe alternatives you've considered**
I considered using insane values (like 1.999999) and find one that is not displayed as "any". However, I decided not to go this way. It would be stupid.

**Comment by HebaruSan** [comment]
What is the concern? That it will appear compatible with the sequel KSP 2?

**Comment by ihsoft** [comment]
No. The concern is that `2.x` version of KSP will __not__ be a brand new game. Thru the last 5 years the Squad team used to address minor changes via the _"patch"_ portion of the version. It doesn't stand anymore. Today, _any_ KSP release increases the minor part of the version.

There are actually _two_ concerns:
1. `KSP 2 `. Indeed. But, I guess, it will be addressed at the binary level of CKAN.
2. Changes within `KSP v1` that completely change the course.  They may easily trigger version `2.x`.

**Comment by HebaruSan** [comment]
Good news, if they do ever release a 2.x version, 1.99 will no longer be shown as "any", because we compare to the max real game version when doing that formatting. Does that address your concerns?

https://github.com/KSP-CKAN/CKAN/blob/821c57f9de70f059fe18f042964ba98c23755cc9/Core/Versioning/KspVersion.cs#L276-L293

**Comment by politas** [comment]
And if we get to a version over 1.50.x, we'll revisit the 1.99 number and switch it to 1.999. Updating the metadata in that case will take some time, but we'll still have plenty in hand.

**Comment by politas** [comment]
> No. The concern is that `2.x` version of KSP will **not** be a brand new game. 

All indications at this time is that any "KSP 2.x" _will_ be a new game, though. 

>Thru the last 5 years the Squad team used to address minor changes via the _"patch"_ portion of the version. It doesn't stand anymore. Today, _any_ KSP release increases the minor part of the version.

KSP v1 will just go to 1.10, then 1.11, etc. These are not decimal places.

> There are actually _two_ concerns:
> 
> 1. `KSP 2 `. Indeed. But, I guess, it will be addressed at the binary level of CKAN.

Definitely. We will likely have to generate a whole slew of new metadata rules and code for KSP 2

> 2. Changes within `KSP v1` that completely change the course.  They may easily trigger version `2.x`.

There's no indication they will do that. They used minor version numbers under 0.x up to 26 and then jumped to 90 to indicate the transition to beta. Why would they engender confusion by having KSP (v1) 2.x as well as KSP 2? There is no significant stage of release that would justify moving the 1.x codebase to a 2.x release numbering. You do that for a major rewrite, which is what KSP 2 will be.

**Comment by ihsoft** [comment]
>  There is no significant stage of release that would justify moving the 1.x codebase to a 2.x release numbering

From what I learned about KPS 2, it's a brand new game, made by a new team form the scratch. That said, their versioning is not bound to the existing game codebase anyhow. For us, the players, `KPS 2` appears to be a "next version of the old good KPS", but for them it will be a new code repository. The next version of the game (or, better say, "sequel") will not be based on the existing code base, it was said cleare expressed on the presentation. So, unless the new team purposely made this decision, the version of the new game _binary_ can easily be `0.x` or `1.x`. As well as the old (existing) codebase can continue going its own path, and, potentially, evolve up to `2.x` point.

But it's just my speculations. I worked with the user facing products for some time, and I learned that it's never good to set false expectations. If you say "any version", then people will expect literally that: _any version_. No matter what!

Given we're talking about free stuff (third-party mods), there will be no legal or money consequences, but at the very least there will be confused people. As a simple example: for a mod that marked as compatible with `1.9` there are always a dozen of questions "is it compatible with `1.9.1`?". Of course, it is! It's obvious to any technically skilled person, but not to those who are not. And many (if not most) players in KSP are not IT skilled people. For them `1.9` and `1.9.1` are two different versions. Imagine what they think about version "any".

Anyway, this feature request is just an idea. If you don't feel this should be addressed in CKAN, I'm fine :) Feel free to close it.

**Comment by HebaruSan** [comment]
> If you say "any version", then people will expect literally that: any version. No matter what!

As I understand it, this isn't a false expectation. Since there is no KSP 1.10 or 2.0 yet, "any version" is accurate now. Once there is such a version, the application's behavior will change as noted earlier.

> Feel free to close it.

OK.
