### ISSUE TITLE
[Bug] MacOS install guided wiki page dissapeared.

### ISSUE THREAD

**Issue by Toonu** [KSP-CKAN/CKAN#3017]
The github wiki page for installation on the MacOS dissapeared. What else to say?

**Comment by DasSkelett** [comment]
It's still here, has just been renamed. It's linked in the sidebar if the wiki.
https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-macOS

**Comment by Toonu** [comment]
My apologies then. But there are still some broken links in the wiki linking to the old page. Feel free to close on your discretion.

**Comment by DasSkelett** [comment]
Oups, looks like I missed some more.
The wiki is open to edit for everyone, if you want you are free to correct the broken links.
Otherwise I'd be really happy if you could list the pages with broken links you discovered.

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/blob/master/macosx/CKAN#L42

Can we set up a permanent redirect?

**Comment by DasSkelett** [comment]
I don't think you can setup a true redirect that returns a 301 (would be a really cool feature!), but a human readable one à la "This page has been moved to <link>" is certainly possible.

**Comment by HebaruSan** [comment]
> list the pages with broken links

There was one on the main user guide page, now fixed.

- https://github.com/search?q=user%3AKSP-CKAN+OSX&type=Wikis
