### ISSUE TITLE
unable to update automatically

### ISSUE THREAD

**Issue by JoraG03** [KSP-CKAN/CKAN#3022]
Windows 7 64x
CKAN version - 1.27
KSP version - 1.2.2

when running a scan, it cannot automatically update the repository. Returns  and loads indefinitely. I don 't know what this is about

```
Scanning for DLCs and manually installed modules...
Updating repositories...
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: System.Net.WebException: Базовое соединение закрыто: Непредвиденная ошибка при приеме. ---> System.ComponentModel.Win32Exception: Затребованный пакет безопасности не существует
   в System.Net.SSPIWrapper.AcquireCredentialsHandle(SSPIInterface SecModule, String package, CredentialUse intent, SecureCredential scc)
   в System.Net.Security.SecureChannel.AcquireCredentialsHandle(CredentialUse credUsage, SecureCredential& secureCredential)
   в System.Net.Security.SecureChannel.AcquireClientCredentials(Byte[]& thumbPrint)
   в System.Net.Security.SecureChannel.GenerateToken(Byte[] input, Int32 offset, Int32 count, Byte[]& output)
   в System.Net.Security.SecureChannel.NextMessage(Byte[] incoming, Int32 offset, Int32 count)
   в System.Net.Security.SslState.StartSendBlob(Byte[] incoming, Int32 count, AsyncProtocolRequest asyncRequest)
   в System.Net.Security.SslState.ForceAuthentication(Boolean receiveFirst, Byte[] buffer, AsyncProtocolRequest asyncRequest)
   в System.Net.Security.SslState.ProcessAuthentication(LazyAsyncResult lazyResult)
   в System.Net.TlsStream.CallProcessAuthentication(Object state)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   в System.Net.TlsStream.ProcessAuthentication(LazyAsyncResult result)
   в System.Net.TlsStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   в System.Net.PooledStream.Write(Byte[] buffer, Int32 offset, Int32 size)
   в System.Net.ConnectStream.WriteHeaders(Boolean async)
   --- Конец трассировки внутреннего стека исключений ---
   в System.Net.WebClient.DownloadFile(Uri address, String fileName)
   в System.Net.WebClient.DownloadFile(String address, String fileName)
   в CKAN.Net.Download(String url, String& etag, String filename, IUser user)
   в CKAN.Repo.UpdateRegistry(Uri repo, KSP ksp, IUser user, SortedDictionary`2& downloadCounts, String& currentETag)
Repository update failed!
```

**Comment by HebaruSan** [comment]
Seems to be working fine for me. Are you having other network difficulties?

**Comment by JoraG03** [comment]
> Seems to be working fine for me. Are you having other network difficulties?

I don’t have any problems with my network. I am use all methods for correct work CKAN but it’s don’t work.

P.s. sorry my English, I am from Russia

**Comment by HebaruSan** [comment]
OK. When I input "Затребованный пакет безопасности не существует" into Google Translate, it says "The requested security package does not exist". If that's accurate, you may be missing some .NET component related to network communication. Can you check that your .NET install is up to date?

- https://dotnet.microsoft.com/download

**Comment by JoraG03** [comment]
> OK. When I input "Затребованный пакет безопасности не существует" into Google Translate, it says "The requested security package does not exist". If that's accurate, you may be missing some .NET component related to network communication. Can you check that your .NET install is up to date?
> 
> * https://dotnet.microsoft.com/download

Oh no. I am already lastest version Framework and Core .NET but CKAN don't work

**Comment by helloworld1025** [comment]
I have the same problem. Writes that .NET has the latest version

**Comment by HebaruSan** [comment]
@JoraG03, I recommend searching for parts of the error, someone else must have had a similar problem before. Do any of these links help?

- https://ithelp.bakabuka.com/%D0%B7%D0%B0%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BD%D0%B5/
- https://www.admin01.ru/faq/the_authentication_error_when_connecting_to_rdp.html
- https://infotecs.ru/forum/topic/8127-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B8-%D0%BF%D0%BE-rdp-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0%D0%B7%D0%B0%D1%82%D1%80%D0%B5%D0%B1%D0%BE%D0%B2%D0%B0%D0%BD%D0%BD%D1%8B%D0%B9-%D0%BF%D0%B0%D0%BA%D0%B5%D1%82-%D0%B1%D0%B5%D0%B7%D0%BE%D0%BF%D0%B0%D1%81%D0%BD%D0%BE%D1%81%D1%82%D0%B8-%D0%BD%D0%B5-%D1%81%D1%83%D1%89%D0%B5%D1%81%D1%82%D0%B2%D1%83%D0%B5%D1%82-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D1%83%D1%81%D1%82%D0%B0%D0%BD%D0%BE%D0%B2%D0%BA%D0%B8-vipnet-client/
