### ISSUE TITLE
How should `any_of` dependency be implemented?

### ISSUE THREAD

**Issue by 01010101lzy** [KSP-CKAN/CKAN#3023]
I'm implementing an alternative CKAN commandline client myself, and I am interested in the `any_of` directive in [`depends` section](https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#relationships) as it is not thoroughly documented. I'm not sure how should the CKAN client select the right mod to install if none of the `any_of` mod is installed.

I came up with several ways to implement that:

1. Select the first mod listed in `any_of` that is compatible.
2. Select the mod that satisfies the most number of `any_of` directives and not being incompatible.
3. Let the user select the mod he/she wants (additional interaction needed).

Which behavior is the desired behavior for a CKAN client, or any one would be okay?

**Comment by HebaruSan** [comment]
See #2660 for the notes from when this was implemented. The official client prompts the user, but any of the options you've listed would fit the spec.

**Comment by 01010101lzy** [comment]
Thanks!
