### ISSUE TITLE
BetterTimeWarpCont is trying to use multiple downloads per version number

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3024]
KSP 1.8.1 game on Windows

Wrong version of BTW gets installed.

To start, I removed it entirely,  including from the CKAN/downloads directory (both copies, one for 1.7.3 and one for 1.8.0)

I have 1.7.3 compatibility set for some other mods
Refreshed CKAN, and go to look at the contents.  CKAN downloads it (apparently), but when I open the file, it's the wrong version.
Specifically, the file name is:
     R:\CKAN\downloads\855463ED-BetterTimeWarpCont-2.3.12.5.zip
but opening the file shows the 1.7.3 version file.

When I remove the 1.7.3 compatibility, it downloads the 2.3.12.4 for 1.8.5, which is one version behind.

**Comment by linuxgurugamer** [comment]
Let me know if I need to release a new version to bump it for 1.8.1

**Comment by HebaruSan** [comment]
So it's downloading this file?

![image](https://user-images.githubusercontent.com/1559108/77853066-8dd6f580-71d1-11ea-816f-121fbca05184.png)

**Comment by HebaruSan** [comment]
I'm going to try to edit this so I can read it, please bear with me...

**Comment by HebaruSan** [comment]
Oh, this is because you're trying to associate multiple downloads with a single version number. That doesn't work. Only the first asset listed will be indexed:

![image](https://user-images.githubusercontent.com/1559108/77853160-308f7400-71d2-11ea-84ca-fb6408ee4bbf.png)

**Comment by linuxgurugamer** [comment]
So it sounds like i should release an update for 1.8 only, right?

**Comment by HebaruSan** [comment]
One GitHub release per download, is the rule of thumb. And the version number of the GitHub release should match the version number of the download:

![image](https://user-images.githubusercontent.com/1559108/77855027-61c17180-71dd-11ea-9f8d-ebcecc590ec4.png)

There should be a separate GitHub release for 2.3.11.9, as it is that version will be indexed as 2.3.12.5 because that's the version number associated with its GitHub release.

**Comment by linuxgurugamer** [comment]
ok.  I'm dropping the 1.7.3, so I'll just do a 1.8 update and finish it that way

**Comment by linuxgurugamer** [comment]
I just released 2.3.12.6 for 1.8, so next time the bot updates, this should be fixed.  Please confirm when you can.

**Comment by HebaruSan** [comment]
@linuxgurugamer That new version was just indexed:

https://github.com/KSP-CKAN/CKAN-meta/commit/c2457aa28614aebcb3346dc181da7c88b8b2a8eb#diff-96d35fe83b8cac937d18382b729ffafe

While you're here, please address the comment tagging you in KSP-CKAN/NetKAN#7801.
