### ISSUE TITLE
Windows Defender "Protects my device"

### ISSUE THREAD

**Issue by IB8000** [KSP-CKAN/CKAN#3026]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.0
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When I attempt to run ckan.exe, my device opens a window saying that "Microsoft Defender SmartScreen prevented an unrecognized app from starting. Running this app might put your PC at risk."

**Steps to reproduce**
Run ckan on Windows
**Expected behavior**
ckan GUI opens
**CKAN error code (if applicable):**
N/A

**Comment by HebaruSan** [comment]
Please report false positives to your antivirus vendor.
