### ISSUE TITLE
Permissions problem with downloads folder after changing drive letter of active game instance and configured download folder

### ISSUE THREAD

**Issue by mishi5250** [KSP-CKAN/CKAN#3030]
Background
----------
* Operating System: win10 1909
* CKAN Version: 1.27
* KSP Version: 1.90

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Add an instance
* Set the download cache folder to that instance's `CKAN\downloads` folder
* Delete the drive letter that it's on
* Launch CKAN

```
未经处理的异常:  System.IO.DirectoryNotFoundException: 未能找到路径“K:\SteamLibrary\steamapps\common\Kerbal Space Program\CKAN\downloads”的一部分。
   在 System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   在 System.IO.Directory.InternalCreateDirectory(String fullPath, String path, Object dirSecurityObj, Boolean checkHost)
   在 System.IO.Directory.InternalCreateDirectoryHelper(String path, Boolean checkHost)
   在 System.IO.Directory.CreateDirectory(String path)
   在 CKAN.KSPManager.LoadInstancesFromRegistry()
   在 CKAN.CmdLine.MainClass.Execute(KSPManager manager, CommonOptions opts, String[] args)
   在 CKAN.CmdLine.MainClass.Main(String[] args)
```

![image](https://user-images.githubusercontent.com/14813912/78520372-ea04cf80-77f8-11ea-8910-b1c26fcd3645.png)

**Comment by HebaruSan** [comment]
The error text is reporting a permissions problem with `K:\SteamLibrary\steamapps\common\Kerbal Space Program\CKAN\downloads`. Does that folder exist?

**Comment by mishi5250** [comment]
my game folder  J:\SteamLibrary\steamapps\common\Kerbal Space Program,I have  K: before,but now only  J：，ckan.exe in J

**Comment by mishi5250** [comment]
> Does that folder exist?
no ，i only  have  J  folder,but i have it  before

**Comment by mishi5250** [comment]
I deleted the K disk，I merged K disks，

**Comment by mishi5250** [comment]
by the way ,im use  Mobile Hard disk

**Comment by HebaruSan** [comment]
Did you edit the download cache directory path to point to that `K:` drive location? CKAN 1.27.0 should never attempt to create a folder in that location otherwise. Otherwise it's possible that you actually have an older version.

![image](https://user-images.githubusercontent.com/1559108/78696594-2a467980-78ef-11ea-8f79-193f664be664.png)

You might be able to work around this by deleting your `%LOCALAPPDATA%\CKAN\config.json` file.

**Comment by mishi5250** [comment]
when i delete **%LOCALAPPDATA%\CKAN\config.json**,i‘m run CKAN.exe again  ,Create folder again，the path still in K：

**Comment by HebaruSan** [comment]
OK, that sounds like you have an older version, because 1.27.0 doesn't do that. Please upgrade:

https://github.com/KSP-CKAN/CKAN/releases/latest

**Comment by mishi5250** [comment]
hi ,im done,its work ,i edit  json file  by  VSCODE, i  change the download cache path 。thank you for the suppose ，thanks

**Comment by mishi5250** [comment]
thank for  you help @HebaruSan
