### ISSUE TITLE
Blank warning screen on startup, hang

### ISSUE THREAD

**Issue by hngdog** [KSP-CKAN/CKAN#3032]
Background
----------
* Operating System: MacOS 10.13.6
* CKAN Version: 1.27.0
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Craft Manager, Modular Flight Integrator, Module Manager

Problem
-------
Ocassionally when CKAN starts, during Updating Repositories step, 
there is a small dialog box shown, but it is blank. No interface elements work at this point, have to force quit.  Starts fine immediately after. Not every time.

**Steps to reproduce**
Launch
see dialog
force quit

**Expected behavior**
no hang. or at least properly display dialog so I know what it wants.

**Screenshots (if applicable)**

![Screen Shot 2020-04-09 at 10 25 36 AM](https://user-images.githubusercontent.com/60797305/78912985-ef0e8c80-7a4d-11ea-9e8b-f6d4f89c4b9a.PNG)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Probably the same as #3027, with a fix already merged for the next release.

**Comment by HebaruSan** [comment]
Release v1.27.2 is building now and will fix this.
