### ISSUE TITLE
[Bug] Reinstalling AD mods results in infinite download screen

### ISSUE THREAD

**Issue by EricBorges2019** [KSP-CKAN/CKAN#3033]
Background
----------
* Operating System: macOS 10.14.6
* CKAN Version: 1.27.0
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes

Problem
-------
**Describe the bug**
trying to reinstall AD mods freezes CKAN app into infinite "downloading", despite displaying correct download link at the bottom of the window

**Steps to reproduce**
* Right-click on one or more AD mods
* click 'Reinstall'

**Expected behavior**
AD mod is reinstalled

**Screenshots (if applicable)**

<img width="1457" alt="Screen Shot 2020-04-10 at 19 11 29" src="https://user-images.githubusercontent.com/9995803/79028709-2325a280-7b5f-11ea-9ed4-16c69c2fdda2.png">

<img width="569" alt="Screen Shot 2020-04-10 at 19 11 24" src="https://user-images.githubusercontent.com/9995803/79028708-2325a280-7b5f-11ea-8dde-d20c150d13fe.png">

**CKAN error code (if applicable):**

```
N/A
```

**Comment by HebaruSan** [comment]
Oh, interesting. That's not really supposed to work for AD mods, we'll have to gray out the option.
