### ISSUE TITLE
"Path does not correspond o a KSP folder" on MACOS 10.15.5

### ISSUE THREAD

**Issue by Hazuka** [KSP-CKAN/CKAN#3047]
I have a big problem whili initiated the CKAN nogui on macos 10.15
I cant follow the path of my KSP folder (on Application/Kerbal\ Space\ Program)

Any ideas ?

https://imgur.com/sWBnblW
<img width="682" alt="Capture d’écran 2020-05-07 à 20 31 47" src="https://user-images.githubusercontent.com/17553127/81331864-8513f200-90a2-11ea-92fd-b17f8d648c33.png">

Thank you`

**Comment by HebaruSan** [comment]
What if you remove the back slashes? I don't think they're required (but I would have to check).

**Comment by Hazuka** [comment]
Sorry i cant find a way to add the labels xD

**Comment by Hazuka** [comment]
> What if you remove the back slashes? I don't think they're required (but I would have to check).

Omg its that...
Thank you xD

**Comment by HebaruSan** [comment]
Glad you got it working!

**Comment by HebaruSan** [comment]
> Sorry i cant find a way to add the labels xD

GitHub only allows dev team members to manipulate labels (in general, not just for CKAN). It's not super important, just a convenient way to organize things.

**Comment by I-need-help140** [comment]
Could you help? I do not understand what to do, I tried. Application/Kerbal Space Program and Application Kerbal Program.
