### ISSUE TITLE
UnauthorizedAccessException when AppData\Local is missing

### ISSUE THREAD

**Issue by Teej72** [KSP-CKAN/CKAN#3048]
Background
----------
* Operating System:  Windows 7 pro
* CKAN Version:  1.27
* KSP Version:  2019.2.2.4392
**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
I haven't played KSP since January and I wanted to start again vanilla but when I open CKAN ( to turn off the mods) it crashes. I haven't changed anything on my PC. I saw there was an update to Kerbal so I re-downloaded CKAN but that didn't help.

After opening a windows shell appears. Error in it says Unhandeled exception: Systme.UnauthorizedAccessException : Access to the path 'c:\USers\User01\appdata\local\CKAN\config.json' is denied

A long list of "at " statements follows

**Steps to reproduce**
Double click on Icon.( I had it on my desk top. Tried it int the Main KSP folder and the Game data folder
**Expected behavior**
to launch

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Does the file in the error message exist? If so, delete it and try again.

**Comment by Teej72** [comment]
I could not find the file but I did see a debut text from today : in the KSP folder 

[0425/171832.340:ERROR:settings.cc(325)] Settings version is not 1
[0520/182449.046:ERROR:settings.cc(325)] Settings version is not 1
[0523/212647.358:ERROR:settings.cc(325)] Settings version is not 1
[0523/212647.390:ERROR:settings.cc(325)] Settings version is not 1
[0526/135016.207:ERROR:settings.cc(325)] Settings version is not 1
[0624/174607.648:ERROR:crash_report_database_win.cc(469)] failed to stat report
[1130/070018.920:ERROR:settings.cc(325)] Settings version is not 1
[1130/070431.599:ERROR:settings.cc(325)] Settings version is not 1
[1201/192644.559:ERROR:settings.cc(325)] Settings version is not 1
[1225/130234.100:ERROR:settings.cc(325)] Settings version is not 1
[0510/103810.479:ERROR:settings.cc(325)] Settings version is not 1

**Comment by HebaruSan** [comment]
What about the directory? Does `c:\ USers\User01\appdata\local\CKAN\config.json` exist?

**Comment by Teej72** [comment]
I found the appdata folder but local wasn't there

**Comment by HebaruSan** [comment]
Try this:

1. Start -> Run
2. `%LOCALAPPDATA%`

That might find it if there's something weird with the naming of your folders.

**Comment by Teej72** [comment]
That leads me to a folder called "LocalLow" and CKAN isn't there.

**Comment by Teej72** [comment]
Would uninstalling and reinstalling KSP or CKAN help?

**Comment by HebaruSan** [comment]
No, you need the Local folder to exist, and KSP and CKAN don't control that.
I'm not able to find any documentation on why the Local file might be missing in Windows. Maybe try creating a new user account, and see if it appears? It's possible that you deleted it accidentally somehow.

**Comment by Teej72** [comment]
Creating a new user worked but that is going to be a pain. I'll see what I can do about the local folder.

I really appreciate you answering so quickly and hope you and your family are sating safe.
