### ISSUE TITLE
[Bug] Access a socket in a way forbidden

### ISSUE THREAD

**Issue by CarToyz** [KSP-CKAN/CKAN#3049]
Background
----------
* Operating System: WIndows 10
* CKAN Version: v1.27.2
* KSP Version: v1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
None.

No changes made to CKAN or KSP - error just started.

**CKAN error code (if applicable):**
One or more downloads were unsuccessful:

Error downloading <Enter Mod Here>: An attempt was made to access a socket in a way forbidden by its access permissions 88.99.249.174:443

Get this error with any MOD or Version of KSP.

**Comment by DasSkelett** [comment]
Do you still get this error?
This is the IPv4 address of SpaceDock. It had a small hiccup earlier, but should be fine again.
At least for me everything seems to work fine again, downloads in CKAn from SpaceDock are working.

**Comment by CarToyz** [comment]
Still getting the error -

System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: An attempt was made to access a socket in a way forbidden by its access permissions 88.99.249.174:443
   at System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   at System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- End of inner exception stack trace ---
   at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
   at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)

**Comment by DasSkelett** [comment]
Do you have a firewall software installed? Are you behind some sort of restrictive firewall?

Can you try to download a GitHub-hosted mod, like `xScienceContinued`?

I wonder whether that's SpaceDock specific or also affects other hosts.
Also, do you see any message regarding trying to fallback to archive.org? That should normally happen when it can't get a mod from the primary host.

**Comment by CarToyz** [comment]
Nothing new to my setup - CKAN worked normally until recently - I already had  [X]Science loaded, so I unloaded and reloaded it - no issue.   It appears the issue is just with SpaceDock hosted mods.

**Comment by DasSkelett** [comment]
> I already had [X]Science loaded, so I unloaded and reloaded it

That doesn't necessarily prove it, because it was probably still in your cache.
Try right-clicking xScienceContinued and select `Remove contents`, then reinstall it again.
If it works now, it's indeed a SpaceDock-only problem.
