### ISSUE TITLE
SXT Download issues

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3050]
Quite possible this is a problem with SXT.

I updated SXT earlier today.  New file in Spacedock and Github.
I can download the file manually, and it opens up fine.
I have plenty of disk space available.

Using CKAN v1.27.2, it gets the following error while opening it up:

CKAN.InvalidModuleFileKraken: SXTContinued 2:0.3.29.3: C:\Users\jbb\AppData\Local\Temp\tmp7DDE.tmp is not a valid ZIP file: Error in step EntryHeader for GameData/SXT/: Exception during test - 'Wrong local header signature @0'
   at CKAN.NetModuleCache.Store(CkanModule module, String path, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)

**Comment by linuxgurugamer** [comment]
Let me add that this was built the same way all my mods are built and packaged, so I'm not sure what could have gone wrong.

**Comment by linuxgurugamer** [comment]
@HebaruSan please look at this, it's my modding night, if I  have to do something, I will have the time to do it early.
Thjx

**Comment by linuxgurugamer** [comment]
Additional piece of information:  I went to the downloaded file:
 C:\Users\jbb\AppData\Local\Temp\tmpC5BD.tmp 
renamed it to be a .zip and it opened up without any issues

**Comment by HebaruSan** [comment]
I'm getting a 404 error on the link.
- https://spacedock.info/mod/1030/SXTContinued/download/0.3.29.3
Maybe a SpaceDock problem, possibly same as #3049?

**Comment by HebaruSan** [comment]
Something's definitely up w/ SD:

```
$ wget https://spacedock.info/mod/1030/SXTContinued/download/0.3.29.3
--2020-05-11 16:51:13--  https://spacedock.info/mod/1030/SXTContinued/download/0.3.29.3
Resolving spacedock.info (spacedock.info)... 88.99.249.174, 2a01:4f8:10b:751::9601:9
Connecting to spacedock.info (spacedock.info)|88.99.249.174|:443... connected.
HTTP request sent, awaiting response... 502 connect failed
2020-05-11 16:51:14 ERROR 502: connect failed.
```

**Comment by DasSkelett** [comment]
Yeah, VITAS is restarting the server (and running updates) because uploads didn'#'t work. But the `Entryheader` error shouldn't be related to this.

**Comment by HebaruSan** [comment]
> But the Entryheader error shouldn't be related to this.

My thought was that if SD returned an HTML page with an error instead of a ZIP, that would fail ZIP validation. But we'll see once SD is back up.

**Comment by linuxgurugamer** [comment]
ok, thanks.  I'll keep my eye on this page

**Comment by linuxgurugamer** [comment]
Update:  Just worked fine, thank you
