### ISSUE TITLE
[Bug] Incorrect mod versions for install

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#3067]
Background
----------
* Operating System: Windows 10 Pro
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

Problem
-------
I have a brand new 1.9.1 install with some 1.8.* mods.

Is the expected behavior that a mod with newer versioning is restricted to using the mod version of dependencies?

Example: Real Fuels can only be accessed by setting 'Compatibility KSP Versions' to include 1.8.

CKAN Install Version Reported 
Real Fuels: Stockalike configs   3.2.6.6.
Real Fuels                                  rf-v 12.8.4.1

KSP Install Version from .version
Real Fuels: Stockalike configs   3.2.3.0
Real Fuels                                  rf-v 12.8.4.1

I have verified the actual install version by cfg errors present that are fixed in the newer version.

**Comment by HebaruSan** [comment]
> Is the expected behavior that a mod with newer versioning is restricted to using the mod version of dependencies?

It's expected that a mod needs its dependencies to be installed.
It's expected that a mod needs a compatible game version.
So yes, if a mod depends on another mod that isn't compatible, you can't install it.

Looks like another duplicate of BobPalmer/CommunityResourcePack#244.

![image](https://user-images.githubusercontent.com/1559108/83697262-24ee6e00-a5c4-11ea-9ce2-a86457145916.png)

If you want to install mods for 1.8 on 1.9, you can customize the compatibility:

- https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by 7ranceaddic7** [comment]
Yeah, that's how I got RealFuels installed.  Even thou it says Any Max KSP, I had to select 1.8 compatibility.  I get that since RFStockalike depends on RealFuels.  As such, it would install the most up-to-date version for 1.8 - which I'm guessing CKAN thinks is 3.2.3.0.

The confusion comes from CKAN saying 3.2.6.6 is installed when it's not.

Here, you can see, It's showing CKAN installed version as 3.2.6.6 ...
![CKAN versions](https://user-images.githubusercontent.com/4062616/83707512-0772d180-a5cf-11ea-9e63-4e410ff57326.png)

But the ACTUAL installed version is 3.2.3.0 ...
![KSP versions](https://user-images.githubusercontent.com/4062616/83707518-09d52b80-a5cf-11ea-8316-46a7826cf65c.png)

**Comment by HebaruSan** [comment]
Nah, CKAN's right. The mod author forgot to update the version file. Check the download.

https://github.com/Raptor831/RFStockalike/releases/download/v3.2.6.6/RFStockalike--v3.2.6.6-39.zip

![image](https://user-images.githubusercontent.com/1559108/83708396-cdf79180-a5e1-11ea-84d8-728ccdcfc875.png)

**Comment by 7ranceaddic7** [comment]
Ummm, (I really hate doing this), not really.

I am quite familiar with the file indicated.  I submitted the PR removing the errant 'L' indicated.

On the right is the GAME file.  On the left is the CKAN download file (2F16B9EE-RFStockalike-v3.2.6.6.zip)
![fix-part-cats](https://user-images.githubusercontent.com/4062616/83709652-d6e16680-a5d3-11ea-8a54-1499e133e59f.png)

**Comment by 7ranceaddic7** [comment]
Yeah, I see, sorry.

Uh, err, umm, just keeping you on your toes. ;)

(shuffling off to buffalo)
