### ISSUE TITLE
[Feature] A debug mode

### ISSUE THREAD

**Issue by enderger** [KSP-CKAN/CKAN#3068]
Problem
-------
**Is your feature request related to a problem? Please describe.**
Whenever I install mods, there is an inevitable unknown conflict. What we currently have to do is launch KSP, see if it's broken, close it out, try uninstalling a mod, and repeating

Suggestions
-----------
**Describe the solution you'd like**
A mode for CKAN where you have your current modlist shown, from where you can disable mods. This effectively uninstalls them without updating the menu.

**Describe alternatives you've considered**
See above

**Additional context**

**Comment by HebaruSan** [comment]
CKAN's default mode shows your current modlist and lets you uninstall them.

What does "without updating the menu" mean? What menu?
