### ISSUE TITLE
[Question] Dependency selection logic

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [KSP-CKAN/CKAN#3070]
I'm in the early process of implementing dependency checks in [neuCKAN][neuCKAN], and came across a problem of mismatching reciprocal/bidirectional dependency versions. Consider the following situation:

`A`, `B`, and `C` are 3 mods. `A` depends on both any version of `B` and any version of `C`. Both `B` and `C` depend on any but the latest version of each other.

There are at least 3 ways of resolving this: 

- latest version of `A`, latest version of `B`, penultimate version of `C`
- latest version of `A`, penultimate version of `B`, latest version of `C`
- latest version of `A`, penultimate version of `B`, penultimate version of `C`

What does CKAN do in this kind of situation?

[neuCKAN]: https://github.com/WowbaggersLiquidLunch/neuCKAN

**Comment by HebaruSan** [comment]
I'm guessing we'd take the latest version of whichever one appeared first in the `depends` list. But in reality we'd probably go yell at those silly modders. :wink:

**Comment by WowbaggersLiquidLunch** [comment]
My original post is flawed. There is only 1 way: latest version of `A`, penultimate versions of `B` and `C`. No indecisiveness.

However, I did come up with a new, slightly more complicated situations that will keep this discussion live:

- Mod `O` depends on any version of `P` or `Q`.
- `P` depends on the any version of `S` and any but the latest version of `T`.
- `Q` depends on the any version of `T` and any but the latest version of `S`.

Does CKAN still go for whichever is first in the `depends` list?

What if `P` depends on any version of both `S` and `T`, and `Q` depends on any but the latest version of both `S` and `T`, and `P` and `Q` `provides` each other? Should we set up a rule and specify a clear preference for latest dependency versions?

**Comment by HebaruSan** [comment]
These hypotheticals are getting pretty complicated. Maybe you should try setting them up and testing what CKAN really does. You can edit your `KSP/CKAN/registry.json` file (make a backup!) to tweak whatever mods you like and then see what happens when you try to install. My guess is you'll get an error. (Note that if you do an update/refresh, it'll reset your changes and you'll have to edit the file again.)

**Comment by WowbaggersLiquidLunch** [comment]
Ok I'll experiment a bit with CKAN and see how it handles this kind of things. Thanks for pointing me to the file to play with.

The main reason (which I forgot to mention) behind why I want to check if CKAN has any rules for selecting from competing dependencies, is that relationship fields are represented with set-like data types in neuCKAN. I want to ensure a stable behaviour across installs of the same mod, and keep neuCKAN consistent with CKAN.
