### ISSUE TITLE
[Bug] Metadata changed popup doesn't seem to work

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3073]
Windows, CKAN v1.27.2

I get the following warning at least once a day, when I refresh CKAN:

![xmFVPJZ](https://user-images.githubusercontent.com/1630166/84268861-5f8d6480-aaf6-11ea-8461-0c3d73036533.png)

Always the same mod

**Comment by linuxgurugamer** [comment]
Will do in a bit.
Regarding the click, there was no click, that appears when I start CKAN
[registry.zip](https://github.com/KSP-CKAN/CKAN/files/4761651/registry.zip)

Output from the ` ckan update --verbose`
```
$ /d/KerbalInstalls/ckan/ckan.exe update --verbose
228 [1] INFO CKAN.CmdLine.CommonOptions (null) - Verbose logging enabled
243 [1] INFO CKAN.KSP (null) - KSP found at R:\KSP_1.9.1_Tetrix
245 [1] INFO CKAN.KSP (null) - Initialising R:/KSP_1.9.1_Tetrix/CKAN
245 [1] INFO CKAN.KSP (null) - Initialised R:/KSP_1.9.1_Tetrix/CKAN
Downloading updates...
1960 [1] INFO CKAN.RegistryManager (null) - Loaded CKAN registry at R:/KSP_1.9.1_Tetrix/CKAN\registry.json
No changes since last update
Updated information on True compatible modules
2288 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN exiting.
```

**Comment by linuxgurugamer** [comment]
Note that this is Windows, I'm using Cygwin, which is why the linux form of the path

**Comment by HebaruSan** [comment]
> Regarding the click, there was no click, that appears when I start CKAN

It's a yes/no popup. Whether you click Yes or No matters for what happens next. :smile: 

> `No changes since last update`

OK, we'll need to catch it when there are updates to CKAN-meta. This output didn't go through the codepath that we want to investigate.

**Comment by HebaruSan** [comment]
Here's the installed module from that registry file:

```json
"ModularPods": {
	"install_time": "2020-06-10T18:54:20.5152739-04:00",
	"source_module": {
		"spec_version": "v1.4",
		"identifier": "ModularPods",
		"name": "ModularPods",
		"abstract": "The 2.5m base pod too small?  Extend it with these modular extensions from 2.5m to 3.75m and beyond.",
		"author": [
			"TiktaalikDreaming"
		],
		"version": "1.0.11",
		"ksp_version": "1.6.1",
		"license": [
			"CC-BY-SA-4.0"
		],
		"resources": {
			"homepage": "http://forum.kerbalspaceprogram.com/index.php?/topic/152811-ksp-121-mod-pods/",
			"spacedock": "https://spacedock.info/mod/1017/ModularPods"
		},
		"tags": [
			"parts",
		"crewed"
		],
		"depends": [
		{
			"name": "TDProps"
		}
		],
		"install": [
		{
			"find": "ModPods"
		}
		],
		"download": "https://spacedock.info/mod/1017/ModularPods/download/1.0.11",
		"download_size": 11309531,
		"download_hash": {
			"sha1": "87090FA0C52130153E58C24B384EE5FBD6699EA2",
			"sha256": "4F938342FEA34539187B5A6013AA41A6196103A746947ECEF82A5E43E2A591F2"
		}
	},
```

The ModuleManager dependency from https://github.com/KSP-CKAN/CKAN-meta/commit/b19de0c4896c595e93c5015f4884a3df9c1022c6#diff-32ba68f0d16e97769751ece9ebdc0782 is missing, but it's present in the `available_modules` version of the same module. So somehow 23-day-old metadata got installed and marked with an `install_time` of today. Or maybe the install time was updated and the source module wasn't.

**Comment by linuxgurugamer** [comment]
Do you need me to do anything?  save files, configs, saves, install, etc?

**Comment by HebaruSan** [comment]
> Do you need me to do anything? save files, configs, saves, install, etc?

What do you do when the popup appears? Do you click Yes, or do you click No? And what happens next?

**Comment by linuxgurugamer** [comment]
I click yes, it proceeds and everything is normal, until the next time.  It's an annoyance, that's all

**Comment by Carnildo** [comment]
I'm experiencing the same issue (in my case, with Surface Experiment Pack and Better Burn Time).  It doesn't matter what I click:

* If I click "yes", CKAN re-installs the mods, and the next time I refresh the mod list, I get the popup again.
* If I click "no", CKAN does not re-install the mods, and the next time I refresh the mod list, I get the popup again.

Running on Linux, if it matters.

**Comment by HebaruSan** [comment]
@linuxgurugamer and/or @Carnildo what are your compatible version settings? A code audit has turned up a possible explanation for this if the module attempting reinstallation isn't compatible, and notably LGG's mod is for 1.6.1 and being reinstalled on 1.9.1.

**Comment by Carnildo** [comment]
CKAN has forgotten about my compatibility settings, and shows no additional versions as being compatible.  Looking through my backups, this forgetting seems to have happened when I upgraded from KSP 1.7.3 to 1.8.1.

I'm currently running KSP 1.8.1, and when I installed my current set of mods, I had a compatibility setting of "all versions of 1.6, all versions of 1.7".
