### ISSUE TITLE
Where to extract meta data for CKAN (program for Kerbal Space Program)

### ISSUE THREAD

**Issue by helloworld1025** [KSP-CKAN/CKAN#3077]
I do not know where to extract metadata for CKAN. Help me please

**Comment by HebaruSan** [comment]
You don't need to extract metadata. What are you trying to do?

**Comment by helloworld1025** [comment]
I get this error when starting CKAN:
Scanning for DLCs and manually installed modules ...
Updating repositories ...
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: Connection is not established, because The destination computer rejected the connection request 127.0.0.1-00-0043
   in System.Net.Sockets.Socket.DoConnect (EndPoint endPointSnapshot, SocketAddress socketAddress)
   in System.Net.ServicePoint.ConnectSocketInternal (Boolean connectFailure, Socket s4, Socket s6, Socket & socket, IPAddress & address, ConnectSocketState state, IAsyncResult asyncResult, Exception & exception)
   --- End trace of internal exception stack ---
   in System.Net.WebClient.DownloadFile (Uri address, String fileName)
   in System.Net.WebClient.DownloadFile (String address, String fileName)
   in CKAN.Net.Download (String url, String & etag, String filename, IUser user)
   in CKAN.Repo.UpdateRegistry (Uri repo, KSP ksp, IUser user, SortedDictionary`2 & downloadCounts, String & currentETag)
Repository update failed!


And I don’t know what to do. I thought it was necessary to extract it to some folder. I have everything installed and even disabled Windows Firewall

**Comment by helloworld1025** [comment]
If something I reinstalled Windows. But before reinstalling, CKAN worked perfectly

**Comment by HebaruSan** [comment]
A firewall sounds like the right place to look. When I search for this error, people are saying that "The destination computer rejected the connection request" probably refers to firewall software interfering rather than the actual server (which makes sense, since github.com is currently working fine). Something on your system is blocking github.com.
