### ISSUE TITLE
[Bug] BetterBurnTime is available for 1.9.x and included in CKAN but it can not find it as Compatible

### ISSUE THREAD

**Issue by musabagriyanik** [KSP-CKAN/CKAN#3081]
Background
----------
* Operating System: Windows 7 64 bit
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
BetterBurnTime add-on is available for all 1.9 versions (1.9.x or 1.9.9) but CKAN can not find it as Compatible filter.

**Steps to reproduce**
* Go to CKAN
* Search BetterBurnTime in Compatible filter. Make sure you are on 1.9.1 KSP version.
* You can not see BetterBurnTime.
* Change filter as All
* Search BetterBurnTime again, you will see CKAN find it. It can not find it as Compatible because the max KSP version is 1.9.0, but it is wrong. According to the producer of BetternBurnTime, this is compatible with all 1.9 versions.

**Expected behavior**

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/40427422/84778987-6fbcac80-afec-11ea-971a-665f3ce83ecf.png)
![image](https://user-images.githubusercontent.com/40427422/84778945-616e9080-afec-11ea-9502-b094884d333d.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
> It can not find it as Compatible because the max KSP version is 1.9.0, but it is wrong.

The compatibility data is pulled from this mod's [SpaceDock listing](https://spacedock.info/mod/21/BetterBurnTime), which only has 1.9<b>.0</b> compatibility:
![BetterBurnTime-SpaceDock](https://user-images.githubusercontent.com/28812678/84781272-ea82c900-afe6-11ea-842e-a7145c4b022c.png)

The author needs to update the compatibility on SpaceDock for CKAN to reflect it.

But you can also tell CKAN to accept 1.9.0 as compatible KSP version:
Go to Settings > Compatible KSP versions > Select 1.9 > Accept

**Comment by HebaruSan** [comment]
Upstream issue, closing.
