### ISSUE TITLE
[Question] How does CKAN handle integer overflow in version comparison?

### ISSUE THREAD

**Issue by WowbaggersLiquidLunch** [KSP-CKAN/CKAN#3092]
Part of the version comparison algorithm stated in the metadata specification:

> Then the initial part of the remainder of each string which consists entirely of digit characters is determined. The numerical values of these two parts are compared, and any difference found is returned as the result of the comparison. For these purposes an empty string (which can only occur at the end of one or both version strings being compared) counts as zero.

What happens if a mod release is versioned as "18446744073709551616.0.0"? The string itself doesn't cause any trouble, but the first component is exactly 2⁶⁴ after it's parsed as an integer. Does CKAN treat it as an error, or does it just let the value wrap around to 1?

This question is perhaps silly, but I want to make sure my neuCKAN's version comparison behaviour matches CKAN's.

**Comment by HebaruSan** [comment]
Oh come on, these questions are getting silly. Who cares?
