### ISSUE TITLE
Error retrieving build map

### ISSUE THREAD

**Issue by ljx17374223** [KSP-CKAN/CKAN#3094]
Background
----------
* Operating System:  win10
* CKAN Version:        v1.27.2
* KSP Version:           1.9.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
437 [1] WARN CKAN.Curl (null) - Curl environment not pre-initialised, performing non-threadsafe init.
468 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json

**Steps to reproduce**
* start CKAN

**Comment by HebaruSan** [comment]
Is this a persistent problem? The file is available to download at that URL.
Recommend checking firewalls and/or virus protection for possible blockage of raw.githubusercontent.com.
