### ISSUE TITLE
[Bug] Unable to load DLL 'libcurl'

### ISSUE THREAD

**Issue by Sniper296** [KSP-CKAN/CKAN#3095]
Background
----------
* Operating System: Windows 10 1909 18363.900
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
CKAN errors with "Unable to load DLL 'libcurl'"

**Steps to reproduce**
* Clean install KSP (empty directory, including CKAN, verify files on Steam)
* Download latest ckan.exe
* Run it.
* Close it after it complains about registry locked and run it agian...
* See error

**Expected behavior**
Updater runs

**Screenshots (if applicable)**
![error](https://user-images.githubusercontent.com/13880171/86167622-c78c0500-bb0e-11ea-8547-4b6a5600cb71.png)

**CKAN error code (if applicable):**
```
Error in auto-update:
Unable to load DLL 'libcurl': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
```

**Comment by HebaruSan** [comment]
> after it complains about registry locked

Why is the registry locked?

**Comment by Sniper296** [comment]
> 
> 
> > after it complains about registry locked
> 
> Why is the registry locked?

That only appears to happen if I don't have the CKAN directory. (I clean installed it originally) It creates both `registry.locked` and `registry.json`, then complains about finding the `registry.locked` file. Clicking `Dismiss` also CTDs it.
![Procmon64_2020-07-10_18-04-52](https://user-images.githubusercontent.com/13880171/87180328-47b52600-c2d8-11ea-97b0-5347ba7255b2.png)
No registry issues after re-launching though. Just the `libcurl.dll` issue.
