### ISSUE TITLE
[Bug] Switching mod versions uninstalls dependent mods

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#3098]
Background
----------
* CKAN Version: v1.28.0-PRE1

Problem
-------
https://forum.kerbalspaceprogram.com/index.php?/topic/154922-ckan-the-comprehensive-kerbal-archive-network-v1272-chandrasekhar/&do=findComment&comment=3814992

> If you revert to an older version of a mod that mod uninstalls and installs the version you request.  Which is good, but this also has a side effect of uninstalling mods dependent on the mod you change, but doesn't reinstall any of these..
> 
> Yesterday I updated ClickThruBlocker to latest.  Found the new version buggy so reverted to the previous version.  This had the side effect of uninstalling everything that had ClickThruBlocker as a dependency, i.e. (most of LGG's mods) But then didn't reinstall any of them.

**Steps to reproduce**
* Install mods with dependencies
* Select one of the dependencies
* Go to the Versions tab
* Select a different version to install
* Apply changes

**Expected behavior**
Old version removed, new version installed, dependent mods not removed.

**Actual behavior**
Old version removed, new version installed, dependent mods removed and not re-installed.

**Cause**
The removal and re-installation steps are too separate, so the re-install step doesn't know that the user is expecting it to re-install things. Or the removal step should only remove dependent mods that the re-install step won't satisfy.

**Comment by Lafreakshow** [comment]
On a somewhat related note, It would be neat if it was possible to tell CKAN to ignore missing dependencies. Something like "This mod has missing dependencies, install anyway?" and the related "Other mods depend on this one, uninstall anyway?" Or perhaps a way to tell CKAN that it may ignore a certain mod for the sake of dependency resolution. For example, if mod A depends on mod B, tell ckan to ignore mod B (as in treat it like a compatible version is already installed) so mod a can be installed and managed by CKAN without also installing mod B.

Probably not a good idea to enable such a feature by default but it could be an opt-in advanced feature or perhaps even something that is set by config file only. The idea being to make it unlikely for regular users to use this feature without understanding what it does while still giving those who do know the extra convenience.

One concrete use case I had to deal with recently was a mod with an outdated version on CKAN that was needed as a dependency. Someone made an unofficial update which had to be installed manually. The way CKAN currently works I had to first install an old version of the dependency so I could install the mod I was after and then had to manually override the dependency.

It may also be useful in cases where one is testing new, yet to be released versions of certain mods. One could install all related mods with CKAN and then manually manage the pre-release mod.

Not really an important or even particularly helpful addition, pretty low on the priorty list I would say, hence I tather mention it here than open a seperate issue.

**Comment by HebaruSan** [comment]
> tell CKAN to ignore missing dependencies

Yeah, that's really unlikely to ever happen. The `depends` relationship is supposed to be for mods that are necessary to make the dependent mod work. If you can omit a mod and have things still work, it belongs in `recommends`.

If you're referring to Kopernicus... waiting for a stable release is a much better idea than new features to hack around it.

**Comment by Lafreakshow** [comment]
I think you misunderstood what I was talking about. The mods don't work without their dependencies. The point is that in some cases installing one of the dependencies manually is necessary and right now the only way to achieve this is to either install all of them manually or install an old version of the dependency first and then manually install the newer version on top of it. In addition to being mildly annoying, CKAN just generally doesn't seem to deal well with this, not noticing that the mod was manually overidden and such. I purposefully didn't mention a mod by name here because frankly it is irrelevant which mod lead to me having this idea because there is more than this one very special case where this would be useful.

I've had to deal with this particular quirk quitre a bit while troubleshooting multiple mods recently, trying different versions, combinations of versions and prerelease builds. During this I also ran into the bug this issue is about multiple times and after a while it got quite annoying. 

I understand this is a feature only a tiny percent of the user base would even notice, hence I alluded to it being way down on the priority list. I was more or less just throwing my thoughts out there.

**Comment by HebaruSan** [comment]
> I understand this is a feature only a tiny percent of the user base would even notice, hence I alluded to it being way down on the priority list. I was more or less just throwing my thoughts out there.

Thanks for contributing, but this issue isn't related to what you're talking about. Please start an enhancement issue if you want this to be considered.

**Comment by HebaruSan** [comment]
Hmm, the places that call `FindReverseDependencies` are already excluding mods that will be re-installed. 

https://github.com/KSP-CKAN/CKAN/blob/e39d735583e2e965cc99e8196e8f76a99ea3c822/GUI/Model/ModList.cs#L150-L155

https://github.com/KSP-CKAN/CKAN/blob/e39d735583e2e965cc99e8196e8f76a99ea3c822/Core/ModuleInstaller.cs#L653-L657

Will need to figure out why that wouldn't work.

**Comment by HebaruSan** [comment]
I just installed a bunch of mods that depend on ClickThroughBlocker, then switched CTB to an older version, and the problem did **not** happen as reported. All the mods I had installed previously are still installed:

![image](https://user-images.githubusercontent.com/1559108/100144999-48042700-2e5d-11eb-9e66-0e3fc1453ba0.png)

@TonkaCrash, are you still seeing this issue with current versions of CKAN? Your original problem report was very clear and specific, so I'm reluctant to close this, but at this point it looks like a non-issue. Can you give us any further info to help with the investigation?

**Comment by TonkaCrash** [comment]
I just checked the behavior again and I'm not seeing the issue.  It appears to have been fixed in one of the CKAN updates since I first reported the issue.  I don't have any objections to closing this.

**Comment by HebaruSan** [comment]
Cool! :tada:
