### ISSUE TITLE
Cannot update mods that require ZeroMiniAVC

### ISSUE THREAD

**Issue by Renfrew** [KSP-CKAN/CKAN#3100]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.27.2
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, I add StockVisualEnhancemnts mod and the mods it required.

Problem
-------
The game has pop up window and said mods need to be update. Therefore, I use CKAN to update, and some mods fail to update because it require ZeroMiniAVC
 
**Steps to reproduce**
* Go to Manage mods
* Click on available updates
* See error 
          ClickThroughBlocker 1:0.1.10.6 requires ZeroMiniAVC but it is not listed in the index, or not available for your version of KSP.
          Error during installation!
          If the above message indicates a download error, please try again. Otherwise, please open a issue for us to investigate.
          If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
          If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose"

**Expected behavior**
update mods that can be updated. I have to manually unchecked the mods that fail to update, then update other mods.

```
PLACE CODE HERE !
I am a bad programmer, I will try.
```

**Comment by HebaruSan** [comment]
KSP version?

**Comment by HebaruSan** [comment]
Probably 1.10.0, with which ZeroMiniAVC wasn't compatible, but now is:

https://github.com/KSP-CKAN/CKAN-meta/blob/master/ZeroMiniAVC/ZeroMiniAVC-1-1.1.0.1.ckan
