### ISSUE TITLE
Mod (Spectra) with incompatible dependency (EVE) incorrectly shown as compatible

### ISSUE THREAD

**Issue by zaropas** [KSP-CKAN/CKAN#3101]
Background
----------
* Operating System: Win10 64
* CKAN Version: 1.27.2
* KSP Version: 1.9.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
My CKAN is set up to list compatible mods. (1.91).  I have Spectra on the list.  Update offered today and now it has listed a dependency to Mod Environmental Visual Enhancements.  

Error given in CKAN is "Spectra v1.4.0 requires EnvironmentalVisualEnhancements but it is not listed in the index, or not available for your version of KSP. Error during installation"

**Steps to reproduce**
* Go to... Spectra v1.4.0
* Click on...Update
* See error Above

**Expected behavior**
~~Install the update to an a Mod that is showing compatible to 1.9.1.~~
Spectra should not be shown as compatible.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Also happens in v1.28.0-PRE1.

**Comment by HebaruSan** [comment]
Tried searching for all mods depending on EVE in a 1.9.1-only instance. Only Spectra has this problem. Maybe an older version is confusing matters, since we've done a lot of relationship rearranging with Spectra?

**Comment by HebaruSan** [comment]
Confirmed, KSP-CKAN/NetKAN#8016 changed EVE from a recommends to a depends. So Spectra [v1.3.3] is compatible but [v1.4.0] is not, and both are available for 1.9.1. The mod list sees v1.3.3 and wants to allow the user to install it, but the installer sees v1.4.0 and says it can't.

[v1.3.3]: https://github.com/KSP-CKAN/CKAN-meta/blob/master/Spectra/Spectra-v1.3.3.ckan
[v1.4.0]: https://github.com/KSP-CKAN/CKAN-meta/blob/master/Spectra/Spectra-v1.4.0.ckan

**Comment by HebaruSan** [comment]
@zaropas, go to the Versions tab and click to install v1.3.3:

![image](https://user-images.githubusercontent.com/1559108/86619357-08a56e80-bf80-11ea-9283-c6475572234a.png)

That should avoid the EVE dependency.

**Comment by zaropas** [comment]
I can't find this list in the format you show.  I have found this in my CKAN. 

<img width="333" alt="2020-07-06 10_27_21-Compatible KSP Versions" src="https://user-images.githubusercontent.com/48962265/86621916-e86fb280-bf73-11ea-9fea-d25493db7557.png">

**Comment by HebaruSan** [comment]
Over on the right of the main window.

**Comment by zaropas** [comment]
Got it.  Thanks

**Comment by zaropas** [comment]
Interestingly it is already clicked over there.

**Comment by zaropas** [comment]
Still the same issue on re attempt with Spectra update.

**Comment by HebaruSan** [comment]
Right, don't try to install that update. It requires EVE.

**Comment by zaropas** [comment]
OK.  Understood.  So spectra is ok just don't try to update at this time.  Thanks.  Now I know why it worked originally, as the 1.3.3 version was already checked.  Good to know.  Thanks for the help.

**Comment by HebaruSan** [comment]
I think we can improve how this scenario is handled in GUI (more compatibility checks for upgradeability?). Re-opening for that.

**Comment by zaropas** [comment]
Awesome.

**Comment by HebaruSan** [comment]
Possibly related (or at least worth investigating at the same time), I just noticed that GPP is shown as incompatible due to the GPPTextures dependency (it's only compatible up to KSP 1.4.5), even if GPPTextures is already installed by bypassing compatibility in the Versions tab. In this situation GPP can be installed from the Versions tab and there isn't even a warning.
