### ISSUE TITLE
[Bug] Update column gone in 1.28, no way to install updates

### ISSUE THREAD

**Issue by dziban303** [KSP-CKAN/CKAN#3116]
Background
----------
* Operating System: W10 20H2
* CKAN Version: 1.28.0
* KSP Version: 1.10.0.2917

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
In 1.28, the 'Update' column is gone, and 'Add Available Updates' is greyed out, leaving no way to update mods.

I don't know what the new "auto installed" column is for, but adding a tick to any box does nothing, either.

**Steps to reproduce**
Simply start CKAN.

**Expected behavior**
Should allow updates to be installed

**Screenshots (if applicable)**
1.28: 
![ckan_2020-07-15_17-19-39](https://user-images.githubusercontent.com/7931765/87606119-d56d8880-c6bf-11ea-9506-4757a2ff49d4.png)

1.28-PRE1:
![ckan_(1)_2020-07-15_17-18-36](https://user-images.githubusercontent.com/7931765/87606244-18c7f700-c6c0-11ea-8dd6-178ab5f5b35d.png)

**CKAN error code (if applicable):**
n/a

**Comment by HebaruSan** [comment]
The column is hidden when there are no updates to install.

**Comment by dziban303** [comment]
But there _are_ updates to install, eleven of them, as you can clearly see from the second screenshot taken in the previous release, 1.28-PRE1.

I opened CKAN 1.28-PRE1 and saw the updates, then remembered 1.28.0 had been released. So without updating the mods, I closed CKAN. Then I downloaded the new version, and placed it in my KSP folder, overwriting the 1.28-PRE1 executable. When I ran the new 1.28.0 version, it showed no updates available. 

I redownloaded 1.28-PRE1 to verify and, yes, those eleven updates were back. I also checked using 1.27, and it showed the updates as well.

Why would it be saying there are no updates available, when the older versions say there are?

**Comment by dziban303** [comment]
@HebaruSan I believe you've closed this issue prematurely, [please see my response](https://github.com/KSP-CKAN/CKAN/issues/3116#issuecomment-659066805). Thank you

**Comment by HebaruSan** [comment]
Here's v1.28.0 exhibiting neither of those problems with the older versions of those mods installed:

![image](https://user-images.githubusercontent.com/1559108/87611467-c1c91e80-c6cd-11ea-870b-a3856e6d02b0.png)

So the column doesn't just go missing.

**Comment by 7ranceaddic7** [comment]
I can confirm 1.28.0 is functioning as expected.

![image](https://user-images.githubusercontent.com/4062616/87612201-bcb0a300-c6be-11ea-9e66-035659795466.png)

**Comment by dziban303** [comment]
> So the column doesn't just go missing.

@HebaruSan What are you saying here, that I'm lying or incompetent? Just because an issue doesn't happen to everyone doesn't mean it doesn't happen at all. Do you not have any interest in trying to figure out why the newly-released version is showing abnormal behavior for a user? 

If you don't want to help me investigate, that's fine, but can you reopen the ticket so someone else might?

Thanks

**Comment by HebaruSan** [comment]
Let's get some accurate/useful steps to reproduce, then. "Simply start CKAN" does not make this problem happen.
