### ISSUE TITLE
Problem installing real solar system textures - 8192 x 4096

### ISSUE THREAD

**Issue by Mme26** [KSP-CKAN/CKAN#3121]
Installation failure occurred during the installation of real solar system textures - 8192 x 4096 v18.1. No reason was given.

**Comment by HebaruSan** [comment]
Just tried this and it worked fine for me.

> No reason was given.

How did you know it failed then?

**Comment by Mme26** [comment]
Maybe it's because I use the Internet in China




 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSP-CKAN/CKAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月19日(星期天) 晚上11:09
收件人:&nbsp;"KSP-CKAN/CKAN"<CKAN@noreply.github.com&gt;;
抄送:&nbsp;"雅典王子"<709855992@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [KSP-CKAN/CKAN] [Bug] Briefly summarize your issue here (#3121)





 
Just tried this and it worked fine for me.
  
No reason was given.
  
How did you know it failed then?

**Comment by HebaruSan** [comment]
OK so you had an error during the download, @Mme26 ?

**Comment by Mme26** [comment]
Yes, the download speed is only 20 + KB / s, and the task will be prompted to time out after a few minutes. Now I've solved it. I've used ckan.


Yes, the download speed is only 20 + KB / s, and the task will be prompted to time out after a few minutes. Now I've solved it. I've used ckan.

 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSP-CKAN/CKAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 上午7:44
收件人:&nbsp;"KSP-CKAN/CKAN"<CKAN@noreply.github.com&gt;;
抄送:&nbsp;"雅典王子"<709855992@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [KSP-CKAN/CKAN] Problem installing real solar system textures - 8192 x 4096 (#3121)





 
OK so you had an error during the download, @Mme26 ?

**Comment by Mme26** [comment]
I changed a download source and the problem was solved.


我换了一个下载源，问题解决了。我换了一个下载源，问题解决了。

 

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "KSP-CKAN/CKAN"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年7月24日(星期五) 上午7:44
收件人:&nbsp;"KSP-CKAN/CKAN"<CKAN@noreply.github.com&gt;;
抄送:&nbsp;"雅典王子"<709855992@qq.com&gt;;"Mention"<mention@noreply.github.com&gt;;
主题:&nbsp;Re: [KSP-CKAN/CKAN] Problem installing real solar system textures - 8192 x 4096 (#3121)





 
OK so you had an error during the download, @Mme26 ?

**Comment by HebaruSan** [comment]
Hmm, what did you change, from what, to what? I would like to know so that we can help other users reporting similar problems downloading from China.
