### ISSUE TITLE
[Feature] Support for alternative archive formats / (de)compressors

### ISSUE THREAD

**Issue by Chryseus** [KSP-CKAN/CKAN#3126]
Currently CKAN only supports zip which has a pretty poor compression ratio compared with more modern algorithms such as the popular LZMA (7zip, xz, etc), this is particularly problematic for larger mods but can also be an issue for people with a slow internet connection or data limits, a large modded install can easily consume many GB.
This also results in a larger than desirable download cache requiring more frequent cleaning.

**Additional context**

As a quick test I compressed the latest release of RSS 8192 textures which is 1531 MiB uncompressed with 7zip (LZMA2 Ultra) and Zstandard level 22.
Method | Compressed Size | Ratio | Decompression Time (seconds)
---------|------------------|-------|----------------------
Original | 973.7 MiB | 1.57 | 14.09
LZMA2 | 794.1 MiB | 1.93 | 9.50
Zstd | 876.4 MiB | 1.75 |  5.40

As you can see there is a good increase in compression ratio and and a fairly substantial increase in decompression speed, particularly with Zstandard, this is going to vary with what is compressed of course but in all cases there should be a meaningful improvement.

**Comment by HebaruSan** [comment]
Are any mod authors on board for this change? The ZIP format is pretty standard for KSP mods, even those not indexed on CKAN. Working on this would only help if there were actual files we could download in these formats.

**Comment by linuxgurugamer** [comment]
Not here.  I understand and agree about the desirability of reducing the size, but OTOH, introducing a new format would simply create chaos for mod authors.

@HebaruSan It probably isn't a big deal to do, especially if CKAN will rely on an external program to do the decompression.  The only mod authors who would get the headache would be those who decide to package it up with a new format

**Comment by HebaruSan** [comment]
Still haven't heard of any modder experimenting with alternate formats. If it happens, we can look at doing this, until then there's no point in having it open in the issues list.
