### ISSUE TITLE
Runtime Error R6034

### ISSUE THREAD

**Issue by MikeLyno** [KSP-CKAN/CKAN#3130]
Background
----------
* Operating System: Windows 10 Pro x64
* CKAN Version: 1.28.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
Every time I start CKan I get a runtime error R6034. I click ok and then ckan works as normal.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Duplicate of #3115

**Comment by MikeLyno** [comment]
I saw nothing in  that thread even remotely addressing this problem with viable answers. It's a nuisance. just after last ckan update.

**Comment by DasSkelett** [comment]
> I click ok and then ckan works as normal.

What else do you need @MikeLyno?

**Comment by MikeLyno** [comment]
How about not getting the error to begin with each time I open CKAN?

**Comment by HebaruSan** [comment]
This is a duplicate and has already been investigated. This isn't helping.
