### ISSUE TITLE
[Bug] Exporting a modpack using CKAN 1.27.2 on Debian 4.19.118-2 locks up CKAN

### ISSUE THREAD

**Issue by mgalyean** [KSP-CKAN/CKAN#3138]
Background
----------
* Operating System: Debian 4.19.118-2
* CKAN Version: 1.27.2
* KSP Version: 1.9.1.2788

* Mono version: 5.18.0.240

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Some minor cfg file nudges, nothing earth shaking

Problem
-------
When attempting to export a modpack, the tab comes up and I can edit the name, identifier, and description, but not the version dropdowns,  The window where the list of mods is supposed to appear does not populate and no buttons do anything other than reflecting a click by changing color momentarily.  One cannot cancel out as it behaves as all other buttons.  Using the OS window widget to close CKAN does not exit, though it does change color so is reflecting the click.  I have to kill the mono process to get CKAN to end, then delete the lock file (hope that is what I should do and all I should do)

**Steps to reproduce**
* Go to...Export Modpack
* Click on...Cancel, or Export, or X-window close widget
* See error

**Expected behavior**
Populates modlist, exports, doesn't hang

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
I can confirm that the modlist doesn't get filled (visually), and that "Cancel" doesn't work.
The "Export" button seems to work though, and actually also _does_ export a proper .ckan file with all the mods installed listed as dependencies.

Have to take a look at why the mods are not shown, and why the cancel button doesn't work (and whether there's more broken.

**Comment by mgalyean** [comment]
> I can confirm that the modlist doesn't get filled (visually), and that "Cancel" doesn't work.
> The "Export" button seems to work though, and actually also _does_ export a proper .ckan file with all the mods installed listed as dependencies.
> 
> Have to take a look at why the mods are not shown, and why the cancel button doesn't work (and whether there's more broken.

I did find that list eventually, but how to I use that to start moving my install to 1.10 other than manually?  I didn't see a way in the interface to do that.  I guess I expected a zip file containing the mods or something, but a simple list makes much more sense.  I definitely expected some visual feedback that something happened and where the result was placed etc

**Comment by DasSkelett** [comment]
> I did find that list eventually, but how do I use that to start moving my install to 1.10 other than manually?

You can import that list again on another instance via `File > Install from .ckan`.

I also found the cause of the problem in my case. It's a mod installed from a locally crafted .ckan file, not listed in the repository. If I remove the mod the export tab works as expected and shows all mods (and you can cancel too)

```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
---> CKAN.ModuleNotFoundKraken: Module not found: LocalMod 
  at CKAN.Registry.LatestAvailable (System.String module, CKAN.Versioning.KspVersionCriteria ksp_version, CKAN.RelationshipDescriptor relationship_descriptor) [0x0002d] in /git/CKAN/Core/Registry/Registry.cs:527 
  at CKAN.EditModpack+<>c__DisplayClass7_0.<AddGroup>b__1 (CKAN.RelationshipDescriptor r) [0x00000] in /git/CKAN/GUI/Controls/EditModpack.cs:117 
  at System.Linq.Enumerable+SelectIPartitionIterator`2[TSource,TResult].PreallocatingToArray (System.Int32 count) [0x0001e] in <cf901b2fef6a46be8867198917d43970>:0 
  at System.Linq.Enumerable+SelectIPartitionIterator`2[TSource,TResult].ToArray () [0x00023] in <cf901b2fef6a46be8867198917d43970>:0 
  at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <cf901b2fef6a46be8867198917d43970>:0 
  at CKAN.EditModpack.AddGroup (System.Collections.Generic.List`1[T] relationships, System.Windows.Forms.ListViewGroup group, CKAN.IRegistryQuerier registry) [0x0001e] in /git/CKAN/GUI/Controls/EditModpack.cs:115 
  at CKAN.EditModpack.LoadRelationships (CKAN.IRegistryQuerier registry) [0x0008a] in /git/CKAN/GUI/Controls/EditModpack.cs:96 
  at CKAN.EditModpack+<>c__DisplayClass1_0.<LoadModule>b__0 () [0x00219] in /git/CKAN/GUI/Controls/EditModpack.cs:61 
  at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
  at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <873b82372c1942cead3b4ea98a2d7306>:0 
```

Now I'm wondering whether it is also a mod not listed in the index in your case, or maybe a mod we deindexed since you installed it?
Can you upload a screenshot of your installed mods (e.g. when selecting the installed filter)?

**Comment by mgalyean** [comment]
> > I did find that list eventually, but how do I use that to start moving my install to 1.10 other than manually?
> 
> You can import that list again on another instance via `File > Install from .ckan`.
> 
> I also found the cause of the problem in my case. It's a mod installed from a locally crafted .ckan file, not listed in the repository. If I remove the mod the export tab works as expected and shows all mods (and you can cancel too)
> 
> ```
> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. 
> ---> CKAN.ModuleNotFoundKraken: Module not found: LocalMod 
>   at CKAN.Registry.LatestAvailable (System.String module, CKAN.Versioning.KspVersionCriteria ksp_version, CKAN.RelationshipDescriptor relationship_descriptor) [0x0002d] in /git/CKAN/Core/Registry/Registry.cs:527 
>   at CKAN.EditModpack+<>c__DisplayClass7_0.<AddGroup>b__1 (CKAN.RelationshipDescriptor r) [0x00000] in /git/CKAN/GUI/Controls/EditModpack.cs:117 
>   at System.Linq.Enumerable+SelectIPartitionIterator`2[TSource,TResult].PreallocatingToArray (System.Int32 count) [0x0001e] in <cf901b2fef6a46be8867198917d43970>:0 
>   at System.Linq.Enumerable+SelectIPartitionIterator`2[TSource,TResult].ToArray () [0x00023] in <cf901b2fef6a46be8867198917d43970>:0 
>   at System.Linq.Enumerable.ToArray[TSource] (System.Collections.Generic.IEnumerable`1[T] source) [0x0001f] in <cf901b2fef6a46be8867198917d43970>:0 
>   at CKAN.EditModpack.AddGroup (System.Collections.Generic.List`1[T] relationships, System.Windows.Forms.ListViewGroup group, CKAN.IRegistryQuerier registry) [0x0001e] in /git/CKAN/GUI/Controls/EditModpack.cs:115 
>   at CKAN.EditModpack.LoadRelationships (CKAN.IRegistryQuerier registry) [0x0008a] in /git/CKAN/GUI/Controls/EditModpack.cs:96 
>   at CKAN.EditModpack+<>c__DisplayClass1_0.<LoadModule>b__0 () [0x00219] in /git/CKAN/GUI/Controls/EditModpack.cs:61 
>   at (wrapper managed-to-native) System.Reflection.RuntimeMethodInfo.InternalInvoke(System.Reflection.RuntimeMethodInfo,object,object[],System.Exception&)
>   at System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x0006a] in <873b82372c1942cead3b4ea98a2d7306>:0 
> ```
> 
> Now I'm wondering whether it is also a mod not listed in the index in your case, or maybe a mod we deindexed since you installed it?
> Can you upload a screenshot of your installed mods (e.g. when selecting the installed filter)?

Things are in flux here.  Not sure the modlist is the same now.  I'm working between 4 different test installs while trying to get a working one that my current game will have all it needs parts and modwise.  But now that you mention it, i do know that I manually installed an Infernal Robotics Next beta version that I'd hoped would fix something, I thought I'd removed it but there it is

**Comment by mgalyean** [comment]
Here is another datapoint.  I have a clean install of KSP 1.10, manually installed only mods listed as compatible via CKAN.  I wanted to do a diff of its modlist to the one from my old install and when I select 'Export Modlist' in CKAN all I get is a blank tab.  Out of the frying pan and into the fire, lol

**Comment by DasSkelett** [comment]
Can you give us a screenshot of all the mods you installed via CKAN?
