### ISSUE TITLE
NullReferenceException on ctrl-F in ConsoleUI

### ISSUE THREAD

**Issue by edoluck90** [KSP-CKAN/CKAN#3140]
Hello , when i try to search mod using ctrl + F and start digits CKAN crash with this screen
![Schermata 2020-08-15 alle 20 34 37](https://user-images.githubusercontent.com/37956494/90319280-eca9cb00-df36-11ea-800c-b0482f445876.png)

**Comment by Vedvod** [comment]
Can verify this bug occurring on latest release of Mono and CKAN for MacOS 10.16+ (Console UI)

**Comment by HebaruSan** [comment]
@edoluck90 and/or @Vedvod, can you please share a screenshot of your screen _without_ the error on it? I think this _might_ have something to do with the DLCs. I don't get an error when searching, but for me the DLCs show up as installed:

![image](https://user-images.githubusercontent.com/1559108/94965783-b95cd480-04c1-11eb-9fc4-b9ba865b8d56.png)

Or show their names (on an instance without DLC):

![image](https://user-images.githubusercontent.com/1559108/94966879-9df2c900-04c3-11eb-947a-6531183c1288.png)

But you both seem to have something that shows up differently, as "MakingHistory-DLC" or "BreakingGround-DLC":

![image](https://user-images.githubusercontent.com/1559108/94966982-d397b200-04c3-11eb-9272-82f6778fad9a.png)

![image](https://user-images.githubusercontent.com/1559108/94966736-6257ff00-04c3-11eb-9503-a7f3345775cd.png)

![image](https://user-images.githubusercontent.com/1559108/94966703-553b1000-04c3-11eb-902d-7b1e4b7e35f5.png)

I guess some follow-up questions, too:

- Do you have the DLCs installed?
- Have you updated your registry recently? There were some DLC related changes a while back that may be related somehow.

ConsoleUI may need some further tweaks to handle `"kind": "dlc"`.

**Comment by HebaruSan** [comment]
New guess: The DLC module synthesizing code doesn't populate the Searchable properties. If that's the cause, then it would happen anytime your DLC version isn't in the registry (e.g., before KSP-CKAN/CKAN-meta#2130).
