### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by PeruMapper** [KSP-CKAN/CKAN#3141]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.28.0
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**when i wanted o download Tantares mods and the beale neptune mod it say me error everytime**

**Steps to reproduce**
* Go to ckan
* Click on the check to install and when installing
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
* TantaresSP 1.0 (cached)

    TantaresSP 1.0 already installed, skipped
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open a issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

```

**Comment by HebaruSan** [comment]
_Is_ it already installed?

**Comment by PeruMapper** [comment]
The error only happen when it says reviewing gamedata something like that.

**Comment by HebaruSan** [comment]
@PeruMapper, is TantaresSP already installed or not? Please answer this question.
