### ISSUE TITLE
CKAN Leadership: The time has come to pass the torch

### ISSUE THREAD

**Issue by politas** [KSP-CKAN/CKAN#3152]
It can probably be argued that that the time came a few years back for me to step down as CKAN Mission Director. My involvement has slowly petered off as I've been working on other projects and not even playing KSP.

I've tried sounding out people to see if anyone wanted to step up to take on the titular project leadership without getting any nibbles, so I think the only thing to do is to make it clear. I can't justify holding the title any more even to myself.

I'm really proud of the team that has grown into the ongoing project support role. you're all so responsive to queries and concerns, and wonderfully patient with the occasional weird and incomprehensible ones. 

All the controversies that were the driver for the last leadership change seem to have died away, thankfully. It's nice to be able to hand over leadership when there isn't a crisis.

I'd like to propose a new leader, but in truth, I haven't really been paying enough attention to ongoing discussions in order to make an assessment. So please, lets have some nominations, either for yourself or another team member, and remember, it's not all about the tech skills.

**Comment by HebaruSan** [comment]
What are the duties associated with the role? I assume it's not too heavy if you've been able to do it near-absentee?

**Comment by tj-murphy** [comment]
I'm very new to CKAN, but I'd like to vouch ffor DasSkelett as a person who seems to know their stuff and be invested in the project and the people using it. Obviously up to them if they want to increase commitment, but, let's put it this way, I certainly get "head of the project" vibes from them.

**Comment by DasSkelett** [comment]
I appreciate the support @tj-murphy, thanks!
However I'd like to point out that I'm the newest member of the team, and the other team members are certainly more experienced and more familiar with the history of the CKAN.

But before bringing up other names, I'd join @HebaruSan in the question about what awaits the Mission Director. You can judge best who's a good fit for a role when you know what the role's requirements are.

**Comment by politas** [comment]
Ok, here's the role as I see it:

- Maintain the CKAN Thread on KSP forums (the one task that has to be done by just one person due to forum software)
- Be the public face of the project, both as the 'authority' and 'scapegoat'
- Be the ultimate arbiter in disputes between team members
- Be the legal interface between other organisations and the CKAN (for such things as JetBrains licenses, certificates, code signing)

A team leader should have sufficient technical knowledge to understand the issues, but need not be able to solve all technical issues. The position, for an ongoing project like this, is best held by someone with strong social skills. A primary duty (and one I have been very poor at) is working to encourage/assist people to move from the periphery of the project into the main sphere.

The CKAN could really use a few more people helping out, and this is where I think I've been falling down more than anywhere else.

**Comment by HebaruSan** [comment]
> The position, for an ongoing project like this, is best held by someone with strong social skills.

From what I've seen, @DasSkelett is the strongest of us in this area. I think he's still our only representative in the wild world of Reddit (possibly the only one wtih an account). He has a record of being patient and helpful. I'd support his candidacy if he'd accept the nomination.

**Comment by techman83** [comment]
I second @HebaruSan 's motion here. It's been a pleasure watching @DasSkelett grow to become a valuable team member. I would also be on hand to support whomever takes over the reigns.

**Comment by DasSkelett** [comment]
Thank you all very much! I do accept the nomination, but I also want to suggest @HebaruSan.
He's certainly the public face of the project, especially on the forums.
He has also shaped the CKAN project as it is today, and is definitely the one putting the most work in it.
He's a great person to work with, and as you could see in my case, he does a great job getting new contributors familiar with the project and actually building up their programming skills.

**Comment by politas** [comment]
Ok, @DasSkelett, I've bumped you up to "Owner" of the KSP-CKAN GitHub org. If you would like to start a new CKAN thread, I'll ask the mods to lock off my thread and redirect further comments over. @Olympic1, can you bump Das up to owner on Discord?

I would also like to add that I've been very impressed with Das' work on Reddit. I've had a notification for CKAN related posts on Reddit for ages, and most of the time, Das has replied before I get to them, with excellent helpful and informative responses!

**Comment by politas** [comment]
I've just renewed our JetBrains licences, and I think the only other thing I have control over is the Debian package's help email address (it's buried in the packaging rules, I think, and currently points to an address I set up: politas.ksp.ckan@gmail.com.) I've just re-enabled the Zapier script that turns emails addressed there into GitHub issues, so it should be good until you can get a new address embedded.) I'm not sure how to switch the team management over in Jetbrains. Might be easiest to just do the re-application under your email next year, @DasSkelett.

**Comment by DasSkelett** [comment]
That was fast :D
Thank you all very much for your support, means a lot to me. You are a great team, so I expect that job to be a rather quiet one.
Thank you for holding the steering wheel for so long @politas.

> If you would like to start a new CKAN thread, I'll ask the mods to lock off my thread and redirect further comments over.

That's probably a good idea, especially since the current one is already over 90 pages. I'll set one up later.

> I think the only other thing I have control over is the Debian package's help email address (it's buried in the packaging rules, I think, and currently points to an address I set up: politas.ksp.ckan@gmail.com.) I've just re-enabled the Zapier script that turns emails addressed there into GitHub issues, so it should be good until you can get a new address embedded.)

The email address in the deb changelog is `debian@ksp-ckan.space`, and there's one for the rpm, `rpm@ksp-ckan.space`. I couldn't find a mention of `politas.ksp.ckan@gmail.com`. Are those @ksp-ckan.space addresses forwarded to yours?
They seem to be hosted on AWS, so maybe we can find a better way to handle them? Like forward to all the devs so we don't rely on a single one, or run that Zapier script directly, or forward them to a dev-only Discord channel, or whatever options AWS offers. I'm guessing @techman83 has set it up, maybe you have some ideas, knowing what AWS is capable of?

**Comment by politas** [comment]
> That was fast :D
> Thank you all very much for your support, means a lot to me. You are a great team, so I expect that job to be a rather quiet one.

I've found it to be so. 


> That's probably a good idea, especially since the current one is already over 90 pages. I'll set one up later.

It does take a while to get through it!

> The email address in the deb changelog is `debian@ksp-ckan.space`, and there's one for the rpm, `rpm@ksp-ckan.space`. I couldn't find a mention of `politas.ksp.ckan@gmail.com`. Are those @ksp-ckan.space addresses forwarded to yours?
> They seem to be hosted on AWS, so maybe we can find a better way to handle them? Like forward to all the devs so we don't rely on a single one, or run that Zapier script directly, or forward them to a dev-only Discord channel, or whatever options AWS offers. I'm guessing @techman83 has set it up, maybe you have some ideas, knowing what AWS is capable of?

Ah, yes, it's probably something like that. Zapier has a great little script for turning an email into a Github issue, but you need to authorise zapier to read email and post to Github, so a dedicated throwaway email address seemed better.

**Comment by HebaruSan** [comment]
Looks like the transition is complete?
