### ISSUE TITLE
Using CKAN on a USB

### ISSUE THREAD

**Issue by puppydoggy230** [KSP-CKAN/CKAN#3154]
As my pc has very little storage ive put steam on my usb, so how can i use ckan? 
I try selecting the ksp folder but it says its not valid

**Comment by HebaruSan** [comment]
What exactly are you having a problem with?

**Comment by politas** [comment]
@puppydoggy230 , you need to select the build64.txt in the KSP directory, not the directory itself. We know at it would be better to be able to select the directory, but there are technical limitations involved in a multiplatform app that makes that not work.
