### ISSUE TITLE
[Bug] Cant even install a basic mod

### ISSUE THREAD

**Issue by Coaxgames** [KSP-CKAN/CKAN#3158]
Background
----------
* Operating System: win 10
* CKAN Version: 1.28.0
* KSP Version: 1.7.1.2539

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
1:~Installed mod"Lshipparts" or the "large ship parts" mod

2:~a small verity of mods that never installed

Problem
-------
after going thru and installing some mods ~(via right click, then install)  and i noticed that not one was installing
(noticed when i was looking for the parts in question) and then i did some testing

turned out that any mod i install says it does(even with the progress bar) and returns 0 errors

(note also that purge files does nothin not even a load screen)
(but does when manually installing files, but doesnt show)

~~side note:
(yes ik) i used a 1.6.1 version of ksp to see if ckan worked in that(no)
so i reinstalled it and to my surprise it didnt work(even on 2 different versions and dir's) 

**Steps to reproduce**
* N/a
* 
* 

**Expected behavior**
after installing the mod above i should have it in the directory(gamedata)
or even throw an error

**Screenshots (if applicable)**
![Bug1](https://user-images.githubusercontent.com/57080080/94114034-04615280-fe05-11ea-833d-945f2d38e0c6.png)
![bug2](https://user-images.githubusercontent.com/57080080/94114045-088d7000-fe05-11ea-9a2e-12fb5640e343.png)

screen sidenote:
~as seen half the mods do not show up along with no mods being downloaded
    (yes i did go thru and try to reinstall or look at my gamedata folder)
~~also i did try to back it up(half of em dont show either) so i did backup my gamedata folder directly
    (so i can look at the mods when i need)
~~just to note this happened with most of the mods shown(even in a entirely different ksp directory and version)  
                                                                                                     (aka 2 games, 1 is just used for debugging)

**CKAN error code (if applicable):**
surprisingly none at all
```
n/a
```

(ps i can provide anything and also dont mind manual installs but ckan makes it so much easier)

Edit:
10 mins later,

so ckan now installs only compatible mods but ANY others are ignored or at least arent installing
(also appears that certain mods can be downloaded but any manual mods dont install)
~via rightclick then download(when the checkbox isint there)
(should i just download em manually?)

**Comment by DasSkelett** [comment]
Your text is written in a very confusing way, I tried my best to understand what did and what you wanted to achieve.

> after going thru and installing some mods ~(via right click, then install) and i noticed that not one was installing
(noticed when i was looking for the parts in question) and then i did some testing

> turned out that any mod i install says it does(even with the progress bar) and returns 0 errors

> (note also that purge files does nothin not even a load screen)
(but does when manually installing files, but doesnt show)

There is no "Install" option in the right-click menu. There's only "Download Contents", "Reinstall" and "Purge Contents".
* "Download Contents" only downloads the mod into the cache. It does not install it. If you clicked that one, that would explain why the mods didn't get installed.
* "Reinstall" is only for reinstalling already installed mods.
* "Purge Contents" purges a mod from the cache again. It does not uninstall it.

For installing mods, you have to select its checkbox on the left in the mod list, and click "Apply changes" afterwards.

> so ckan now installs only compatible mods but ANY others are ignored or at least arent installing

Yes, you can't install incompatible mods, CKAN doesn't allow that. If you want to widen the version range CKAN accepts as compatible, see this guide: https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by Coaxgames** [comment]
Odd and srry being up at 2am is meh for me, also yah "download" but small thing the mods worked before?
again side note, ckan is not installing ANY MODS what so ever not just "incompatible", i am aware of that
(assuming as to why theres a tag with "compatible and not"

but ckan isint installing anything apart from 1 or 2 compatible mods,
(also again the mods that i was downloading worked like 2-3 days ago)

considering "kas" and "Rover engines" is installed and i have older ones installed from ckan itself


![Screenshot_16](https://user-images.githubusercontent.com/57080080/94175581-161e1680-fe54-11ea-940f-285592bd6eb3.png)

**Comment by DasSkelett** [comment]
Honestly, I still have no idea of what you are trying to say.

I can only repeat that "Download contents" won't install mods, **it will only download them into the cache, not install them into GameData**. Use the checkbox on the left to install mods!
Please read our [user guide](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#using-the-gui).

If that's not your problem, answer the following questions in a very clear and structured way, one question after another. Try not to use any brackets. Proofread your comment before submitting it. Try to put yourself in our position: we don't know anything about what you tried to do, how you tried to do it and what actually happened.

1) What did you try to achieve? What was your ultimate goal of the steps you have taken? (Install mods using CKAN? Uninstall mods? Update mods? Which mods?)
2) What exact steps did you take? Explain it step-by-step, which buttons you clicked and for which mods. Can you still reproduce the problem? If yes, can you reproduce it with other mods, or only with certain mods?
3) What did you expect to happen after taking these steps? What do you think CKAN should've done?
4) What actually happened? In what state were CKAN and the GameData folder in?

**Comment by Coaxgames** [comment]
No thxs it was neither For some reason ckan wasn't installing ANY MODS
compatible or not check box or not, also the cache helped but ckan fixed
itself when reinstalled ckan and some mods and magic,

 Mods (EVEN COMPATIBLE) are installing even some of the non compatible
stuff, if i can next time ill just remove it as the solutions did nothing

STEPS I DID TO FIX;
1: Remove Ckan
2: remove Oldest installed mods
3: reinstall ckan(possibly a mod as well)

Last step: after reinstalling ckan I moved all old mods back to my gamedata
folder as ckan was updating repositorys


RESULT:
For somereason redoing the steps above fixed both ksp instances and mods


LAST NOTE:
Again before the fix(if it even was) no mods
(Compatible or not) even if a checkbox was there it still would not show up
in folder

(If I installed a compatible mod myself it would show in game fine but ckan
sees the mod)
Now mods I install manually or by ckan work now

(some mods still not installed bc of ckan not allowing it)

Anyway the problem resolved by the the steps I took
(from the looks of it I could be wrong there)

**Comment by HebaruSan** [comment]
@Coaxgames, so you fixed it?

**Comment by Coaxgames** [comment]
Well I didn't do much but those are the steps I took to attempt a fix(as
you can tell it worked).

I wouldnt pay much mind to this, but still odd
(bc my pc is kinda iffy^)

but incase for anyone else who might come across this can help, the problem
was fixed though.

As mentioned in steps above(my last response)
But at some point it started actually adding mods to the gamedata folder.


After yesterday I had added another 2 mods and no problem but it was slow?

My thinking is when I hit 42 mods ckan must've had something weird happen
like
(How it didnt even Uninstall or install any mod)
Or not throwing an error.

So maybe something with me making those steps might have reset a variable
inside of ckan? Or just fixing itself somehow, im rlly confused by what
happend with ckan but it works now(for incompatible mods and compatible
mods)

altho contracts are still not downloading, that might be my game version

Sorry for the iffy responses, I been trying to fix alot of stuff cause we
had a surge so sleep has been gone, but I hope no one else come across this
problem
(its not big but 3 reinstalls is kinda annoying sometimes)

**Comment by HebaruSan** [comment]
> (as you can tell it worked)

Great to hear!
