### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by mgalyean** [KSP-CKAN/CKAN#3171]
Background
----------
* Operating System: 4.19.0-10-amd64 #1 SMP Debian 4.19.132-1 (2020-07-24) x86_64 GNU/Linux
* CKAN Version: 1.28.0
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Nope

Problem
-------
Search box not found

**Steps to reproduce**
Open client, no search box

**Expected behavior**
A search box

**Screenshots (if applicable)**
![ckan_no_search_box](https://user-images.githubusercontent.com/5876493/95663182-03216c80-0b0b-11eb-9881-996b88de7a06.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by mgalyean** [comment]
Nvrmind.  It moved

**Comment by HebaruSan** [comment]
Related to #3163.
