### ISSUE TITLE
No search function?

### ISSUE THREAD

**Issue by HippoDrummer** [KSP-CKAN/CKAN#3178]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.28.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
There is no search function when looking for a mod, happened when I reinstalled CKAN. Tried reinstalling again, still didn't work.

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**
The search function should be available to look for a certain mod.

**Screenshots (if applicable)**
https://imgur.com/a/LO84gqS
**CKAN error code (if applicable):**

```
PLACE CODE HERE!
```

**Comment by HebaruSan** [comment]
It's at the bottom left.

![image](https://user-images.githubusercontent.com/1559108/97031626-1fcc9400-1550-11eb-870f-65b6811095d3.png)

Related to #3163.
