### ISSUE TITLE
[Bug] Bdarmoury Continued requires a nonexistent dependency called "BDArmoury"

### ISSUE THREAD

**Issue by AmethystEdits** [KSP-CKAN/CKAN#3182]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.28.0-PRE1
* KSP Version: 1.9

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I added BDArmoury continued and Physics Range Extender but I deleted those while I had ckan open before I applied changes

Problem
-------
BDArmoury Continued has a nonexistent dependency called "BDArmoury" so I cant install bdarmoury continued

**Steps to reproduce**
* Go to BDArmoury continued
* Click on the dependencies tab thing on the right
* See BDArmoury as a nonexistent dependency

**Expected behavior**
Clicking on the dependencies tab thing and seeing either "BDArmoury" being existent or not being In the dependencies tab or selecting BDArmoury Continued as something you want to download, saving changes and not getting a error
also downloaded a fake instance on my laptop (error is happening on desktop) and I get "BDArmoury" as a "virtual" instance which I don't get on my desktop

**Screenshots (if applicable)**
![Screenshot 2020-10-25 222604](https://user-images.githubusercontent.com/57216385/97103406-1a6a7780-1711-11eb-8bdb-950f2aa52467.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by AmethystEdits** [comment]
might not realise so ill elaborate, on my desktop I get the "BDArmoury" conflict but not with the (virtual) part at the end and it isn't like a folder like it is here

**Comment by HebaruSan** [comment]
That's a conflict, not a dependency. It's so you can't install the old BDArmory and BDArmoryContinued at the same time.
