### ISSUE TITLE
Path does not correspond to a KSP folder (macOS Catalina)

### ISSUE THREAD

**Issue by I-need-help140** [KSP-CKAN/CKAN#3185]
I am on the latest version of macOS Catalina, and I am trying to use Ckan on my mac. I have been playing KSP for three years but on a PC and my PC recently broke and I have been trying to play on my MacBook. Whenever I try to put in my file directory, this error shows up *Path does not correspond to a KSP folder!* 
<img width="558" alt="Screen Shot 2020-10-31 at 10 43 04 AM" src="https://user-images.githubusercontent.com/73739262/97776167-35504800-1b66-11eb-81f4-b504566bc44e.png">

I will appreciate any help.

**Comment by HebaruSan** [comment]
Try `/Applications/Kerbal Space Program` instead.

**Comment by I-need-help140** [comment]
Yes,  that worked. Thank you. 
<img width="558" alt="Screen Shot 2020-10-31 at 7 24 12 PM" src="https://user-images.githubusercontent.com/73739262/97786862-af0c2400-1bae-11eb-8dd9-640a018d2f6b.png">

**Comment by I-need-help140** [comment]
Could you also help me on how to use this version of CKAN. What commands I have to put in. I have very basic experience with *Terminal*

**Comment by HebaruSan** [comment]
The bottom of the window lists the actions available on each screen. They take the form of the name of the keys to press and then a short description of what that keystroke does. For example, to quit CKAN from the above screen, you could press Ctrl+Q.

**Comment by I-need-help140** [comment]
Okay, so how would I list all currently available mods and install them? 
I'm not sure if this is right but is it: *control+ R/F10* then select the mod and. *Enter*?

**Comment by HebaruSan** [comment]
If you are still on the above screen, then "Enter - Select" is how to satisfy the "Select a game instance:" prompt.

**Comment by I-need-help140** [comment]
<img width="558" alt="Screen Shot 2020-10-31 at 9 33 32 PM" src="https://user-images.githubusercontent.com/73739262/97789470-087d4e80-1bc1-11eb-9239-f5d4c6844f0c.png">
Is this right?

**Comment by HebaruSan** [comment]
Yes.

**Comment by I-need-help140** [comment]
Thank you so much for your help and I'm sorry for my inexperience with macOS causing you trouble.

**Comment by HebaruSan** [comment]
You're welcome, and it's no trouble.
