### ISSUE TITLE
Mods Not Installing CKAN (macOS Catalina)

### ISSUE THREAD

**Issue by I-need-help140** [KSP-CKAN/CKAN#3186]
I am on the latest version of macOS *Catalina* and am using CKAN with mono. I tried downloading different mods, and it said that it was downloading all the data. When I look in my game data folder, I can only see module manager (which I installed manually) and the stock *squad* and *squad expansion files*
<img width="201" alt="Screen Shot 2020-11-01 at 10 12 51 AM" src="https://user-images.githubusercontent.com/73739262/97798922-d30d4b00-1c2a-11eb-9c81-83d23f0a198f.png">
I have downloaded different mods. for example the kerbalized SpaceX an Astronomers visual pack mods.
<img width="557" alt="Screen Shot 2020-11-01 at 10 14 28 AM" src="https://user-images.githubusercontent.com/73739262/97798957-0b148e00-1c2b-11eb-99dc-706a4556d379.png">
It says I have downloaded and installed them but they are nowhere to be found in my game data folder and when I launch the game, it is stock. 
<img width="558" alt="Screen Shot 2020-11-01 at 12 00 53 PM" src="https://user-images.githubusercontent.com/73739262/97801011-f1c70e00-1c39-11eb-89f8-aca5c098f0fd.png">

 <img width="1920" alt="Screen Shot 2020-11-01 at 10 20 12 AM" src="https://user-images.githubusercontent.com/73739262/97799124-495e7d00-1c2c-11eb-8df6-4a53e8cb89fa.png">
<img width="1920" alt="Screen Shot 2020-11-01 at 10 21 49 AM" src="https://user-images.githubusercontent.com/73739262/97799138-609d6a80-1c2c-11eb-9201-48f3c03b6bcf.png">

**Comment by I-need-help140** [comment]
I fixed my problem

**Comment by HebaruSan** [comment]
> I fixed my problem

Glad you got it working!
