### ISSUE TITLE
Make it for 1.10.1

### ISSUE THREAD

**Issue by shayan2007** [KSP-CKAN/CKAN#3191]
I have 1.10.1 it is for 1.7.0 :(

**Comment by DasSkelett** [comment]
@shayan2007 are you speaking of CKAN or a mod?
CKAN works with all versions of KSP.
If you want to get a newer version of KSP, you need to update it via Steam or the website.
If you are speaking of a mod, please specify which mod you are talking of. But keep in mind, we can't update mods for you. We can only update wrong metadata.

**Comment by HebaruSan** [comment]
@shayan2007 we can re-open this if you clarify what you're talking about. No point in letting it sit at the top of the issues list for a week as it is.
