### ISSUE TITLE
Can't install Kopernicus Bleeding Edge

### ISSUE THREAD

**Issue by DarkEnergy9999** [KSP-CKAN/CKAN#3193]
Problem
whenever i click on Kopernicus Bleeding Edge Beta the apply changes button stays gray, but when i click any other mod it goes green.
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**
![screenshot](https://media.discordapp.net/attachments/765935261271719937/775830559279677440/Screenshot_2020-11-10_161244.png?width=408&height=427)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
There's probably a conflict. Can you screenshot the whole window? The message explaining the conflict would appear in the lower left.

**Comment by DarkEnergy9999** [comment]
> There's probably a conflict. Can you screenshot the whole window? The message explaining the conflict would appear in the lower left.

yes i will put a pic of the whole screen
![Screenshot 2020-11-10 164654](https://user-images.githubusercontent.com/72878452/98737564-5c7ff400-2374-11eb-9dc0-3d3f9b7318bb.png)

**Comment by HebaruSan** [comment]
Yeah, this is due to how @R-T-B decided to structure the BE releases; it replaces ModularFlightIntegrator itself rather than creating a separate build for that mod. Uninstall ModularFlightIntegrator and try again.

![image](https://user-images.githubusercontent.com/1559108/98737837-70275c80-236c-11eb-9290-2b7cab4815d3.png)

**Comment by DarkEnergy9999** [comment]
ok thank you that worked

**Comment by R-T-B** [comment]
@HansSebaru, I would be happy to stop doing this if ModularFlightIntegrator is now marked as 1.10.1 ready...  is it, per chance?

**Comment by HebaruSan** [comment]
Doesn't look like it:

- https://ksp.sarbian.com/jenkins/job/ModularFlightIntegrator/lastSuccessfulBuild/artifact/ModularFlightIntegrator/ModularFlightIntegrator.version

**Comment by R-T-B** [comment]
Well the 1.9.1 version is what we use actually.  It works fine in 1.10.1.  Could we get the metadata updated manually pethaps for that reason?

**Comment by HebaruSan** [comment]
@R-T-B better to go upstream when possible.

@sarbian any chance you could update this version file to reflect apparent compatibility with KSP 1.10?

https://ksp.sarbian.com/jenkins/job/ModularFlightIntegrator/lastSuccessfulBuild/artifact/ModularFlightIntegrator/ModularFlightIntegrator.version

**Comment by sarbian** [comment]
@HebaruSan Done. Thanks for the reminder.

**Comment by HebaruSan** [comment]
Thanks!

@R-T-B, the default install of MFI should show up for 1.10 now:

- https://github.com/KSP-CKAN/CKAN-meta/commit/70de1a6d4f2228806ff3b8e4c4bc85b0b25ce2bb
