### ISSUE TITLE
mod won't remove

### ISSUE THREAD

**Issue by vclrbm** [KSP-CKAN/CKAN#3195]
Background
----------
* Operating System: Windows 8.1
* CKAN Version: 1.29.0
* KSP Version: 1.9.1.2788

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I removed the mod folder for the mod and deleted it

Problem
-------
**Describe the bug**
so I have enjoyed using ckan for playing modded ksp for about 6 months and I can't get a mod to remove
when I go to remove the mod which is Advanced fly by wire (windows) 1.8.3.2 it says /is already absolute error during installation

**Steps to reproduce**
* Go to... advanced fly by wire install it
* Click on... remove
* See error /is already absolute error during installation

**Expected behavior**
shouldn't remove the mod and give an error message

**Screenshots (if applicable)**
![Screenshot (1)](https://user-images.githubusercontent.com/70306347/99153375-b806f600-2682-11eb-968a-60fef9d596eb.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE!
```/is already absolute

**Comment by HebaruSan** [comment]
Thanks for the report. This is because this mod installs into GameRoot:

- https://github.com/KSP-CKAN/CKAN-meta/blob/master/AdvancedFlyByWire/AdvancedFlyByWire-1.8.3.2.ckan

Probably related to changes made in #3180, when we found out that `NormalizePath` behaved weirdly for `/`.

**Comment by vclrbm** [comment]
So how would I go about removing it from the game root

**Comment by HebaruSan** [comment]
Let us investigate. We'll fix the issue in CKAN, and along the way we might find a workaround for you.

**Comment by vclrbm** [comment]
Alright than thank you

**Comment by HebaruSan** [comment]
`--debug` doesn't give much info:

```
50760 [Thread Pool Worker] DEBUG CKAN.Registry (null) - Pardon me, but I couldn't help overhear you're in a transaction...
51365 [Thread Pool Worker] DEBUG CKAN.Registry (null) - State saved
51366 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing SDL2.dll
51367 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing SDL_LICENSE
51368 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing XINPUTDOTNET_LICENSE
51368 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing XInputInterface.dll
51368 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/Plugins/XInputDotNetPure.dll
51368 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/Plugins/ksp-advanced-flybywire.dll
51369 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/Plugins/ksp-advanced-flybywire.dll.mdb
51369 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/LICENSE
51369 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/README.md
51370 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/Textures/toolbar_btn.png
51370 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/Textures/toolbar_btn_38.png
51370 [Thread Pool Worker] DEBUG CKAN.ModuleInstaller (null) - Removing GameData/ksp-advanced-flybywire/ksp-advanced-flybywire.version
51373 [Thread Pool Worker] INFO CKAN.Registry (null) - Aborted transaction, rolling back in-memory registry changes.
```

**Comment by HebaruSan** [comment]
The error message specifically is from `KSPPathUtils.ToAbsolute` (which we did not change in #3180).

**Comment by HebaruSan** [comment]
It's this one.

https://github.com/KSP-CKAN/CKAN/blob/a494e1dafb5ed2f19307bdc6180a163c6f5ef9ed/Core/ModuleInstaller.cs#L904-L908

**Comment by HebaruSan** [comment]
@vclrbm I think we've figured out the problem and have a fix in progress in #3196, but as far as I can tell there is no user workaround for it in CKAN v1.29.0. You will need either a new release or a test build that contains the fix.

If you really really need to get rid of this mod right now, it looks like your only option would be to clean out the folder and start over:

- https://github.com/KSP-CKAN/CKAN/wiki/Clean-and-reinstall-process

Sorry for the inconvenience!

**Comment by vclrbm** [comment]
That's perfectly fine I don't mind reinstalling and it'll even give me the cab he to update to a newer version

**Comment by vclrbm** [comment]
Everything is cleaned and reinstalled and seems to be working a okay plus while I was at it updated to the new versions of ckan as well as ksp

**Comment by Aquilux** [comment]
Am I correct in my understanding that this is caused by a mod installing items in KSP's root directory? Should this only occur while attempting to modify (update/uninstall) that particular mod, or would it's existence trip up all attempts at modification?

**Comment by vclrbm** [comment]
Any attempts at modifying the mod list

**Comment by vclrbm** [comment]
But the issue is resolved due to me reinstalling

**Comment by linuxgurugamer** [comment]
Any idea when the fix will be released?

**Comment by HebaruSan** [comment]
@linuxgurugamer probably pretty soon, all the changes I wanted for the next release have been merged and we've already agreed on a title and image. But the build infrastructure is broken at the moment so it will be at least a day or two while that gets fixed.

**Comment by linuxgurugamer** [comment]
Ok, thank you.

**Comment by HebaruSan** [comment]
@linuxgurugamer It's out now.
- https://github.com/KSP-CKAN/CKAN/releases/tag/v1.29.2
