### ISSUE TITLE
[Bug] Can't uninstall mods

### ISSUE THREAD

**Issue by jonassm** [KSP-CKAN/CKAN#3210]
Background
----------
* Operating System: Windows 10, version 1909
* CKAN Version: Eddington v1.28.0
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When trying to uninstall a mod, it says following inconsistencies found and then pointing to the .DLLs still being there. When manually trying to delete, i'm told the file is still in use.
KSP is closed, and processexplorer tells me the DLLs is being used by explorer.exe.
Also tried to restart explorer.exe process

**Steps to reproduce**
Open CKAN, try to uninstall any mod with .DLLs

**Expected behavior**
Normal deletion

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```

```

**Comment by HebaruSan** [comment]
If you can't even delete the files manually, then this isn't a CKAN problem. You'll need to get help specifically for Windows somehow.
