### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by Aquilux** [KSP-CKAN/CKAN#3211]
Background
----------
* Operating System: Windows 10 Pro Version 20H2, OS build 19042.630, Windows Feature Experience Pack 120.2212.31.0
* CKAN Version: v1.29.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No unless you count the official expansions.

Problem
-------
**Describe the bug**
Some time between the 14th and the 25th of November (did not track first instance of bug, sorry) auto update of a mod was attempted and failed with the text "/ is already absolute", and all attempts to alter mods (including removal) since have failed with the same text. This may have been the first attempted update since upgrading to the latest version of CKAN.

**Steps to reproduce**
* Go to...
Any installed mod.
* Click on...
Check box to remove mod. Apply changes. Confirm.
* See error
Uninstall begins, progress bar advances while removing. Error occurs, removal aborted.
Event log output:
`About to remove:

 * Advanced Fly-By-Wire (Windows) 1.8.3.2
Removing AdvancedFlyByWire...
/ is already absolute
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
`
**Expected behavior**
Mod removed with no errors.

**Screenshots (if applicable)**
Can be provided if desired.

**CKAN error code (if applicable):**
None, unless error code location is not obvious.

**Comment by Aquilux** [comment]
AAAnnnd I feel dumb. Frogot to

**Comment by HebaruSan** [comment]
Duplicate of #3195

**Comment by Aquilux** [comment]
Sorry about the post spam.
