### ISSUE TITLE
[Feature] Make a checkbox allowing CKAN to overwrite stuff automatically without the yes/no boxes for every single mod.

### ISSUE THREAD

**Issue by joey-lg** [KSP-CKAN/CKAN#3228]
Problem
-------
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when... Those yes and no boxes appear asking to overwrite mods.

Suggestions
-----------
**Describe the solution you'd like**
Remove them.

**Describe alternatives you've considered**
Or reduce the number to one.

**Additional context**

**Comment by HebaruSan** [comment]
Sorry, the user needs to be able to cancel that, since there's no way to un-do it.
