### ISSUE TITLE
CKAN not starting up

### ISSUE THREAD

**Issue by andyu11** [KSP-CKAN/CKAN#3229]
I have noticed something has gone wrong with my CKAN when I try to start up I get an error message with the following:

Unhandled exception:
Newtonsoft.Json.JsonReaderException: Unterminated string. Expected delimiter: ". Path 'available_modules.WarpShip.module_version['0.3.2'].resources.repository', line 878236, position 44. 
 
I have tried reinstalling several times with no luck and I think it is on 1.29.0 but I am not 100% sure. I use 64 bit Windows 10. I am sorry if this is has been posted before but I couldn't find anything that works. Can anyone help me out here please? Thanks.

**Comment by HebaruSan** [comment]
Your `<KSP>/CKAN/registry.json` file got corrupted. Unfortunately you'll have to delete it and try again.

**Comment by andyu11** [comment]
Thank you for the help, I will locate and delete the file and I will comment again if it worked or not.

**Comment by andyu11** [comment]
> Your `<KSP>/CKAN/registry.json` file got corrupted. Unfortunately you'll have to delete it and try again.

I could not locate this file, where would it be under?

**Comment by HebaruSan** [comment]
It's in the CKAN folder under your Kerbal Space Program folder.

**Comment by andyu11** [comment]
> It's in the CKAN folder under your Kerbal Space Program folder.

The CKAN folder isn't there anymore for some reason I don't remember if I did anything to it but its not there anymore and I don't know why

**Comment by HebaruSan** [comment]
If you're still getting the `Newtonsoft.Json.JsonReaderException` error, then it's still there somewhere. Unfortunately we can't help you search your disk.

**Comment by andyu11** [comment]
I see, I will try to search my disk and see where it might be located

**Comment by andyu11** [comment]
I couldn't find it, I have no idea why it is still doing it

**Comment by HebaruSan** [comment]
Have you made multiple copies of your KSP folder? Sometimes we get questions from people who are looking at the wrong copy.

**Comment by andyu11** [comment]
I have the steam version and the non steam version so ill check the steam version but I intended for the CKAN to be off the steam version

**Comment by HebaruSan** [comment]
If there is no CKAN folder in the Steam copy, then CKAN does not yet know about that copy.

**Comment by andyu11** [comment]
> If there is no CKAN folder in the Steam copy, then CKAN does not yet know about that copy.

I found it on the steam copy! strange because I meant for the steam one to be pure stock

**Comment by HebaruSan** [comment]
Yes, CKAN auto-detects KSP if it's installed in Steam, otherwise you have to add it manually via File &rarr; Manage KSP instances.

**Comment by andyu11** [comment]
It is working again! thank you for your help, it seems to be working normally again now.

**Comment by HebaruSan** [comment]
Cool! :tada:
