### ISSUE TITLE
Error installing ProceduralAirships

### ISSUE THREAD

**Issue by Gnanmorder** [KSP-CKAN/CKAN#3236]
Background
----------
* Operating System: windows 10 x64
* CKAN Version: 1.29.2
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no.

Problem
-------
**Describe the bug**

Could not find a part of the path 'C:\Users\***\Downloads\KSP via CKAN 2\saves\training\saves\training\airship_flight.sfs'. Error during installation! If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate. If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose your issue here

can't apply ckan. everytime i do i get the error message "Could not find a part of the path 'C:\Users\***\Downloads\KSP via CKAN 2\saves\training\saves\training\airship_flight.sfs'.
Error during installation!1

![error](https://user-images.githubusercontent.com/75864579/101961364-93496400-3bd7-11eb-8e5b-46255f4b3d5b.png)

**Comment by HebaruSan** [comment]
I see the instance name is "KSP via CKAN 2". Is this by any chance a fake instance, without the game actually installed there?

**Comment by HebaruSan** [comment]
Well that doesn't look right!

![image](https://user-images.githubusercontent.com/1559108/102171430-1f6bbd80-3e5c-11eb-9987-f5f140ba7235.png)

**Comment by HebaruSan** [comment]
@Gnanmorder can you please answer this question, "Is this by any chance a fake instance, without the game actually installed there?" ?

It looks like this may be a problem with fake instances specifically, so if you are experiencing it with a real game install we would need to know that.

**Comment by HebaruSan** [comment]
This mod's install stanza fixed in KSP-CKAN/CKAN-meta#2185.
Although you shouldn't install ProceduralAirships, its forum thread has people complaining about compatibility problems going back to **2015**.
Fake instance generation fixed in 042c3f52c4685a42c3b05b2b00568c587fe955e9.

Closing as fixed in next release.
