### ISSUE TITLE
[Feature] Rewrite CKAN Desktop with wpf

### ISSUE THREAD

**Issue by Stehsaer** [KSP-CKAN/CKAN#3237]
Well, i feel like my eyes are ruined when i'm using CKAN's current GUI

So CKAN Desktop into C# wpf?

This change can make it easier to use and look way better

I have some exp on wpf dev and i know making customize styles can be a big issue, i suggest using opensource libs like Material Design (i like the style)

**Comment by HebaruSan** [comment]
Thanks for contributing.
The GUI rewrite issue is here: #1840
