### ISSUE TITLE
CKAN believes mod that I deleted still exists.

### ISSUE THREAD

**Issue by 0xide0ri0n** [KSP-CKAN/CKAN#3238]
Background
----------
* Operating System: Windows 11
* CKAN Version: v1.29.2
* KSP Version: v1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes. I manually had to delete the mod KAS from the following file sequence: C:\Program Files (x86)\Steam\steamapps\common\Kerbal Space Program\GameData\GameData. I did, but CKAN is still reading that the KAS.dll still exists in the file sequence that I visited and deleted KAS from.

Problem
-------
**Describe the bug**
CKAN is reading the mod KAS as still existing, even though I 

**Steps to reproduce**
UNKNOWN HOW TO REPLECATE.

**Expected behavior**

**Screenshots (if applicable)**
![KASproblem](https://user-images.githubusercontent.com/75944954/102018382-f69fd700-3d3a-11eb-89f2-1c07382cb597.PNG)

**CKAN error code (if applicable):**
NO ERR. CODE PRESENT.
```
PLACE CODE HERE !
DLL for module KAS found at GameData/GameData/KAS/Plugins/KAS.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by HebaruSan** [comment]
Try clicking Refresh to force it to re-scan GameData. If that doesn't work, can you show us a screenshot or two to confirm that you really did delete what you think you deleted? Sometimes we get requests for help that turn out to be due to confusion over manipulation of files.
