### ISSUE TITLE
[Bug] KSP newest vers. 1.11 - moving mods from 1.10 to 1.11 error requires making history 1.10

### ISSUE THREAD

**Issue by contact-one** [KSP-CKAN/CKAN#3240]
Background
----------
* Operating System: Win10
* CKAN Version: 1.29.2 (just updated Dec 17,2020)
* KSP Version(s):  **two instances**

[Overall goal: duplicate ckan modpack from alpha to omega instance]

This is alpha instance - C:\Users\Aorus\Downloads\ksp-win64-1.10.1\KSP_win64
* 1. KSP 1.10.1 for Windows
* 2. Making History Expansion 1.10.1
* 3. Breaking Ground Expansion 1.5.1

This is omega instance - C:\Kerbal Space Program
* 1. KSP 1.11.0 for Windows, Some Reassembly Required
* 2. Making History Expansion 1.11.0
* 3. Breaking Ground Expansion 1.6.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** NO

Problem
-------
The problem is that it doesnt tell me which mod caused the issue, so maybe ckan is not yet ready for 1.11?

**Steps to reproduce**
Today I setup the 2nd instance of KSP  (1.11 and both KSP major updated addons) here: (C:\Kerbal Space Program).  I will call this omega.

First thing I did was look into ckan and figure out if exporting a modpack from alpha 1.10 would easily allow all my current mods to move from alpha to omega instance.  
I used "manage KSP instances", added the new instance to ckan.
I saved/exported the modlist from alpha instance as "mymods20201217.ckan".
I selected omega instance as the new default.
I selected load the  "mymods20201217.ckan".

The error says: (Installation error)
The following inconsistencies were found:
* MakingHistory-DLC 1.10.1 required, but an incompatible version is installed
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
It looks like you had the "Save mod versions" checkbox checked when exporting your modpack. Can you try exporting it again, without that checkbox checked? Then CKAN shouldn't complain about mismatching DLC versions.

**Comment by HebaruSan** [comment]
Might also want to not include the DLCs in the pack.

**Comment by contact-one** [comment]
1. I dont have much ckan experience, I cant find the button for "dont
include dlc"..
I need step by step button clicking directions.. :)

2. All I did from your email so far is this..  I unclicked the "include
versions" and tried again..  new error..  (this might be progress?  Now
its moving down the list of mods to see which mods are 1.11 ready?)

installed-KSP-win64 2020.12.17.10.11.46 requires
EnvironmentalVisualEnhancements but it is not listed in the index, or not
available for your version of KSP.
Error during installation!
If the above message indicates a download error, please try again.
Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem:
https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client:
https://github.com/KSP-CKAN/CKAN/issues/new/choose

3. OR - MAYBE - I didnt copy all the actual mod folders to the new instance
yet, soo that could be a problem?  I wasnt sure how the export works, if it
just makes a list, or if it also copies all the directories info from where
they sit currently?

I have no idea what the rules for each step actually are.. so again, I need
more info, step by step..

**Comment by HebaruSan** [comment]
> 1. I dont have much ckan experience, I cant find the button for "dont include dlc".. I need step by step button clicking directions.. :)

While in the export screen, click on each DLC, then click the "Ignore" button towards the bottom to remove it for the pack.

**Comment by HebaruSan** [comment]
For the EnvironmentalVisualEnhancements message, it looks like you have not set your compatible versions for the new instance yet. EVE was last update for KSP 1.8.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions

**Comment by contact-one** [comment]
Now I went back to default instance, selected export, found the button which only says "ignore", and I shift clicked all the above entries to highlight them blue, then I clicked the "ignore" button.  I exported, and went to the omega instance and imported.
This time no errors, also loading the game shows no results..

The screenshot shows the result.  
But I am not sure this is right because:
1. the ignore button doesnt mention dlc.. and I dont know if there is a reason..
2. and logically I dont understand exporting mods if you tell me to ignore them..  why does this sound illogical?  Again, I dont know the rules for this operation...
3. after the import to the new instance omega, how do I continue to get it working?
4. there is a tiny checkbox in the upper right with some kind of text cutoff and unreadable.. do you know what this says and what it does?  Am I using the wrong checkbox?  I think this is a secondary issue, but I can screenshot if you need.

This screenshot shows some progress because now there are no specific errors.
![image](https://user-images.githubusercontent.com/55115863/102551331-4d841400-408d-11eb-9315-e3930436abfc.png)

**Comment by HebaruSan** [comment]
> shift clicked all the above entries to highlight them blue

That was where you went wrong; you removed **all** of the mods from the modpack. **Only** do that for the DLCs.

**Comment by contact-one** [comment]
well I already mentioned that I dont understand what ckan is doing.  
Because a mod is a "downloadable content".
The list you see in the screenshot is my total list..  there are no other items defined as dlc, I dont know what youre looking at when you say you see me ignoring a dlc..  and because none of the items in the list are separately labled as "dlc" or "not dlc", so how does anyone know?
How do you define the actions I should be taking?  again, I need step by step directions with clear terminology.

And I cannot read the checkbox I already mentioned, do you know what it says or does?

**Comment by HebaruSan** [comment]
These are the DLCs. The ones that are named after the game's official DLC and say "DLC" in their names.

![image](https://user-images.githubusercontent.com/1559108/102553414-6b02af00-4088-11eb-959e-4f3b5be29a7d.png)

![image](https://user-images.githubusercontent.com/1559108/102553429-7229bd00-4088-11eb-9a7a-715c28a5101d.png)

**Comment by contact-one** [comment]
I dont see any of these in the screenshot of mods I provided, so how am I ignoring them or not ignoring them?  I cant even select on something that I dont see.  Am I missing a checkbox somewhere again?

And maybe in the USA store page you can see in the screenshot below, the Making History, and Breaking Ground are not labeled as DLC..  they specifically have the words "Expansion" after each one of them..  so maybe you are looking somewhere I dont see?

![image](https://user-images.githubusercontent.com/55115863/102553999-d9983a80-4091-11eb-8e56-6e86bac38e7b.png)

Can you answer the other questions not answered yet from above  (so I dont have to keep retyping them..)

Thanks for your help to this point, but loading the game does not yet show updated graphics.

**Comment by HebaruSan** [comment]
> I dont see any of these in the screenshot of mods I provided, so how am I ignoring them or not ignoring them?

I literally copied and pasted those from the screenshot in your previous reply!

![image](https://user-images.githubusercontent.com/1559108/102554229-f9c3fb80-4089-11eb-90da-9e3b4c394bb5.png)

**Comment by contact-one** [comment]
oh I found the letters DLC..  ok,  what are the next steps?

**Comment by HebaruSan** [comment]
If you've forgotten why were were trying to identify DLCs, scroll up and re-read. It's all still there.

**Comment by DasSkelett** [comment]
![102551331-4d841400-408d-11eb-9315-e3930436abfc-edited](https://user-images.githubusercontent.com/28812678/102554318-d8cccc00-40c4-11eb-9aaf-156bed594f58.png)

1) Select "BreakingGround-DLC"
2) Click "Ignore" on the bottom
3) Select "MakingHistory-DLC"
4) Click "Ignore" on the bottom

5) Click "Export" on the bottom right.

Nobody cares whether the DLCs are officially called DLCs or Addons or Expansions or something else. Neither should you.

**Comment by contact-one** [comment]
I am making progress now, but the other question you havent talked about is 4.

[quote]on the main screen, (not shown) there is a tiny checkbox in the upper right with some kind of text cutoff and unreadable.. do you know what this says and what it does? Am I using the wrong checkbox? I think this is a secondary issue, but I can screenshot if you need.[/quote]

In a few moments, I will be uninstalling a screen flare inconsistency that I ran into in my alpha instance, and then exporting a modlist again.  But Im getting better at figuring out some of these other errors so far..

**Comment by HebaruSan** [comment]
We're ignoring that because it isn't relevant to exporting or installing a modpack.

**Comment by contact-one** [comment]
Well, there are no more errors. But I didnt receive the final instructions on how to get all the mods working?
I removed the sunflare issue from the alpha and exported without the expansions.  Whats next?

**Comment by HebaruSan** [comment]
Let's review. You wanted to set up a new KSP 1.11.0 instance with the same mods you had on KSP 1.10.0 by exporting a modpack file in the former and installing it in the latter. This is a valid idea, so we are trying to help you make it work rather than suggesting something else. You encountered a few problems:

- The export-modpack screen was configured to save the version of each mod, which turned out to be a problem specfically for the DLCs because they have only one version per game version, and the version of a DLC for KSP 1.10 cannot be used on KSP 1.11
- Your new instance could not install EnvironmentalVisualEnhancements because it was last updated for KSP 1.8

Accordingly you have made a few changes to your process:

- Unchecked the "Save mod versions" checkbox when exporting the modpack
- Also excluded the DLCs from the modpack (not necessarily required but a good idea in general)
- Add previous game versions as compatible in the new instance so EnvironmentalVisualEnhancements can be installed

The next step would be installing the modpack on the 1.11.0 instance again, with those changes in place.
