### ISSUE TITLE
[Bug] NullReferenceException on spacebar with empty filter

### ISSUE THREAD

**Issue by Hydroxa** [KSP-CKAN/CKAN#3241]
Background
----------
Operating System: Windows 10
CKAN Version: 1.29.2
KSP Version: 1.11.0

No manual changes to GameData

Problem
-------
A NullReferenceException is thrown in ManageMods.cs when the space bar is pressed on ModList, though I'm not sure on which line. I would suspect the cause be something around line 595, where ModGrid.CurrentCell is referenced..

The error occurred while on an empty Upgradeable filter, as this means there is no selected entry to reference, so ModGrid.CurrentCell is likely null. This would mean that, upon pressing the space bar, it would try to reference a null object, thus throwing the named exception.

**Steps to reproduce**
Go to the mod manager, and open a filter that makes the list empty
Press the space bar
Get NullReferenceException

**Comment by HebaruSan** [comment]
Sounds like you're pretty close to a fix. Any interest in submitting a pull request? The CKAN project welcomes contributions.

**Comment by Hydroxa** [comment]
I'll look into it. Despite having GitHub for a little while now, I'm still learning about its features haha

**Comment by HebaruSan** [comment]
Hi @Hydroxa, how's it going? I saw that you made a branch with a fix for this, do you need any assistance in submitting it?

**Comment by Hydroxa** [comment]
I had some issues when trying to build the solution, so I couldn't test the fix :/ The solution was unable to find any dependencies, despite other solutions succeeding in this

But yeah, I did also try to push it here in case the issue was just with my computer and couldn't really work out how ^^;

**Comment by HebaruSan** [comment]
Well, doing a quick checkout and compile on my system, it looks OK so far. There are some build instructions over here that might help (substitute `.\build.ps1` for `./build` on Windows):

- https://github.com/KSP-CKAN/CKAN/blob/master/doc/building.md
- https://github.com/KSP-CKAN/CKAN/wiki/Build-Environment
- https://github.com/KSP-CKAN/CKAN/wiki/New-Developers%27-Guide

If you click here, it should take you to the pull request creation flow, where you can enter a description of the change and then submit it:

- https://github.com/Hydroxa/CKAN/pull/new/new_branch

That gives us a place to do code review and, once any issues are figured out, eventually merge it.
