### ISSUE TITLE
Confused about how to install mods in ConsoleUI

### ISSUE THREAD

**Issue by borisworksfarm** [KSP-CKAN/CKAN#3256]
Background
----------
* Operating System: Mac OS X Catalina 10.15.7
* CKAN Version: the most recent
* KSP Version: 1.11 and 1.10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
manually installed mods (Kerbal engineer, vessel mover ksp interstellar extended, hyper edit)

Problem
-------
**Describe the bug**
I do ctrl D and install and it says installed correctly, but nothing is installed, even in the ~I menu

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by borisworksfarm** [comment]
this same issue happens on my windows computer too

**Comment by HebaruSan** [comment]
Ctrl+D isn't for installing, it just downloads the file into the download cache. Use the "+" key and "F9" on the main mod listing to install, as the tips at the bottom of the screen say.

**Comment by borisworksfarm** [comment]
thank you so much!

**Comment by HebaruSan** [comment]
Glad you figured it out!
