### ISSUE TITLE
[Bug] The process cannot access the file '....json' because it is being used by another process, in unclear circumstances

### ISSUE THREAD

**Issue by jebdied** [KSP-CKAN/CKAN#3260]
Background
----------
* Operating System: windows 10
* CKAN Version: v1.29.2
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
to delete mods, yes, when this error prevents mods from being correctly deleted.

Problem
-------

there is an error that says a .json that ckan has to use to validate files is in use already
it downloads mods fine, but cant validate, and sometimes results in a nested transaction attempt. 
i hadnt done anything the night before but download and delete some mods, and then a clone of ckan opened after this. i have no way of downloading mods correctly.
this doesn't occur when downloading 1 or 2 mods. never happens on deleting.
**Steps to reproduce**
* Go to and open CKAN, 
* Click on a bunch of mods to download
* See error  .json xxxxxxxxxxxxxxxxx is already in use

**Expected behavior**
if this doesnt occur then i dont know how to help you. 
i havent been doing anything with ckan but downloading mods

**Error message**
```
The process cannot access the file 'C:\Users\themi\AppData\Local\Temp\CdFileMgr\38c0528a-0d70-45.json' because it is being used by another process.
Error during installation!
```
```
CKAN registry does not support nested transactions.
Error during installation!
```

**Comment by jebdied** [comment]
i really dont know how this happened.

**Comment by jebdied** [comment]
The process cannot access the file 'C:\Users\themi\AppData\Local\Temp\CdFileMgr\749df976-d0d3-41.json' because it is being used by another process.
Error during installation!

**Comment by jebdied** [comment]
The process cannot access the file 'C:\Users\themi\AppData\Local\Temp\CdFileMgr\326ba17e-0076-43.json' because it is being used by another process.
Error during installation!

**Comment by HebaruSan** [comment]
Which mods are you installing?

**Comment by jebdied** [comment]
everything b9, everything near future, bd armory, airplane plus,

**Comment by jebdied** [comment]
![image](https://user-images.githubusercontent.com/77080144/103828387-77e34480-502f-11eb-8e16-0e9f856be00c.png)
![image](https://user-images.githubusercontent.com/77080144/103828473-7e71bc00-502f-11eb-8dbc-49d0cd086d24.png)
![image](https://user-images.githubusercontent.com/77080144/103828552-83cf0680-502f-11eb-900a-d67917baf27e.png)
![image](https://user-images.githubusercontent.com/77080144/103828627-8893ba80-502f-11eb-98c2-9cc29dd7292a.png)

**Comment by jebdied** [comment]
@HebaruSan screenshots

**Comment by HebaruSan** [comment]
OK, that's not too helpful. Our goal here is to narrow this down to the specific mod or mods that cause the problem.
Can you try installing just one or two of them and see if it works?

**Comment by jebdied** [comment]
i have already done that.
that doesnt work
ckan only works like 2 mins after startup

**Comment by HebaruSan** [comment]
OK so which specific mod did you try installing by itself?

**Comment by HebaruSan** [comment]
What does this mean? "a clone of ckan opened after this"
A clone of CKAN?

**Comment by DasSkelett** [comment]
Also what's interesting is that the temp file ends on `.json`. I don't think Windows/.NET does this on its own. Do we append this somewhere ourselves when creating a temp file to download something (e.g. download counts)?

**Comment by HebaruSan** [comment]
Yeah, that's why I want to know which mod it was. It looks like some mod is set up to download a JSON file somehow.

**Comment by HebaruSan** [comment]
It's also crucial to know exactly when the error message appears. The current steps are probably not accurate, since they imply that the error appears after you check a few checkboxes, without starting the installation process, and there are no transactions involved at that point.

**Comment by HebaruSan** [comment]
We have a preliminary guess about what might be going on. @jebdied, can you please open the settings and show us what this section looks like?

![image](https://user-images.githubusercontent.com/1559108/103832547-22fdf900-5044-11eb-991a-1432cb371d6d.png)

**Comment by jebdied** [comment]
![image](https://user-images.githubusercontent.com/77080144/103912442-2af97f80-50bc-11eb-8cb3-e24d7b8e684d.png)
i have it set to zero with nothing checked

**Comment by jebdied** [comment]
but it still doesnt work

**Comment by HebaruSan** [comment]
Clipping out for easier reading:

![image](https://user-images.githubusercontent.com/1559108/103915667-1ecbed00-50d1-11eb-85bb-c9610b38329d.png)

**Comment by jebdied** [comment]
should i change it to how u had it above?

**Comment by HebaruSan** [comment]
I would say leave it as you have it for now. We are investigating and may have other things for you to check to pinpoint the cause of the issue.

**Comment by jebdied** [comment]
thanks for the help:)

**Comment by HebaruSan** [comment]
@jebdied:

- Please edit the issue description and add accurate steps if you can.
- What does this mean? "a clone of ckan opened after this"

**Comment by jebdied** [comment]
it means there is another instance of CKAN that i cannot access but shows up when starting CKAN and on task manager
other times this doesnt show up but the error still occurs

**Comment by HebaruSan** [comment]
So you see two CKAN windows running next to each other?

**Comment by jebdied** [comment]
no but the other instance shows on task manager and when opening
also there are issues with nested transactions, is there anything about that?

**Comment by HebaruSan** [comment]
@jebdied  What does this mean "and when opening"? What shows, when opening what?

**Comment by jebdied** [comment]
next to ckan it has (2) 
i imagine this means it has a second instance since the same thing happens with chrome when 2 windows are open there

**Comment by HebaruSan** [comment]
@jebdied  Where do you see "(2)"? Can you provide a screenshot?

**Comment by jebdied** [comment]
it only happens on startup but yeah i can get it for u

**Comment by jebdied** [comment]
![image](https://user-images.githubusercontent.com/77080144/104111511-70be6f80-5297-11eb-92ac-f13199bb195f.png)

**Comment by HebaruSan** [comment]
Thanks, clipping that out for easier viewing; looks like it's in the title bar of a console window:

![image](https://user-images.githubusercontent.com/1559108/104111746-863d9480-52ab-11eb-90b5-6c28f86430b2.png)

I don't think that means much; my guess is you downloaded ckan.exe, then downloaded it again and your browser named the new file `ckan (2).exe`, and that's the one you're running now.

**Comment by jebdied** [comment]
hmm
but i deleted the other ckan
and yes i tried reinstalling ckan cuz that might have helped but didnt

**Comment by DasSkelett** [comment]
Yeah but deleting the old `ckan.exe` doesn't automatically rename the new `ckan (2).exe`.
Can you check how the exe you double-click to launch CKAN is called exactly?
If it's called `ckan (2).exe`, can you rename it to `ckan.exe` and see if the `(2)` in the console's window title bar goes away?

**Comment by jebdied** [comment]
the one i launch is just called ckan

**Comment by jebdied** [comment]
and there is no other file named ckan or with ckan in it other than the ksp file

**Comment by Sinomen** [comment]
Looks like two CKAN instances are running, one with a GUI, one without (might have crashed, which happens sometimes with Windows applications).
You could check if CKAN is automatically run and how it was started using Process Explorer
http://live.sysinternals.com/procexp.exe
Example: https://i.ibb.co/hcXQFNz/Process-Explorer-Sysinternals-www-sysinternals-com-CAMELOT-Admin-2021-01-17-05-12-25.png

**Comment by jebdied** [comment]
i have task manager, not process explorer
do u have to download or sumthin?

**Comment by Sinomen** [comment]
Yes, see the link above. ProcessExplorer is part of the Sysinternals suite which belongs to Microsoft, so this is not an obscure download from an obscure site:
https://docs.microsoft.com/en-us/sysinternals/

**Comment by Sinomen** [comment]
So it's definitely only one CKAN instance running then?

If yes, what happens if you kill that process and start CKAN again manually?

**Comment by jebdied** [comment]
it starts up by finding the ksp instance, the version, updating repositories and checking all the mods, but has the same error but only around a minute or 2 in
occasionally small 1-2 mod downloads are fine, and if you download soemthing soon after startup of ckan it goes thru fine.

**Comment by DasSkelett** [comment]
> @HebaruSan is it possible that "Error during installation!" refers to a botched CKAN auto update maybe?

I don't think the auto-update goes through code that could output "Error during installation!" anywhere. The error message is only used in `PostInstallMods()`, which, is only run after installing mods, but not during CKAN's auto-update process.

**Comment by HebaruSan** [comment]
Yeah, that message means the install flow is implicated somehow.

> It's also crucial to know exactly when the error message appears. The current steps are probably not accurate, since they imply that the error appears after you check a few checkboxes, without starting the installation process, and there are no transactions involved at that point.
> 
> @jebdied please edit the issue description and add accurate steps if you can.

> @jebdied:
> 
> * Please edit the issue description and add accurate steps if you can.

The steps haven't been updated. We can't investigate this if we don't know the steps to reproduce it.

@jebdied, we can re-open this if you're able to do that.

**Comment by jebdied** [comment]
so, the error happens when the install is at 90% every time, with a few occasions it doesnt and it works fine.
but it doesnt uninstall the mod from the error, it leaves it there, it just cant check if it did everything right.

**Comment by jebdied** [comment]
and also the issue is still here so, can u reopen it?

**Comment by HebaruSan** [comment]
> and also the issue is still here so, can u reopen it?

Please see my previous comment:

> Yeah, that message means the install flow is implicated somehow.
> 
> > It's also crucial to know exactly when the error message appears. The current steps are probably not accurate, since they imply that the error appears after you check a few checkboxes, without starting the installation process, and there are no transactions involved at that point.
> > @jebdied please edit the issue description and add accurate steps if you can.
> 
> > @jebdied:
> > 
> > * Please edit the issue description and add accurate steps if you can.
> 
> The steps haven't been updated. We can't investigate this if we don't know the steps to reproduce it.
> 
> @jebdied, we can re-open this if you're able to do that.

The steps to reproduce are still not updated.

**Comment by jebdied** [comment]
well i dont know exactly how to reproduce it since i just loaded up ckan and it had this error.

**Comment by HebaruSan** [comment]
> well i dont know exactly how to reproduce it since i just loaded up ckan and it had this error.

Yes, that's the problem. We need you to pay close attention to what is happening and describe it fully.

**Comment by Sinomen** [comment]
Without seeing the issue directly (e.g. via Teamviewer), I don't know how to investigate this further.
