### ISSUE TITLE
Mods only considered compatible when their dependencies are compatible

### ISSUE THREAD

**Issue by Krazy0** [KSP-CKAN/CKAN#3261]
Background
----------
* Operating System: WIN10
* CKAN Version: 1.29.2
* KSP Version: 1.11

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Select: settings> compatible KSP versions: 1.11, 1.10, 1.9, 1.8
Set "Filter (compatible)"
Search term: portrait
results: none

Add compatible KSP version: 1.7

Results: Portrait Stats from DMagic, max KSP version 1.8.8

Apparently this mod should be shown when KSP version 1.8 compatibility is selected.

**Comment by DasSkelett** [comment]
PortraitStats depends on CommunityTraitIcons, which is only compatible with KSP 1.3 through 1.7.
Since CKAN also considers dependencies when determining compatibility of a mod, PortraitStats only shows up as compatible when KSP 1.7 is also selected as compatible version.

**Comment by Krazy0** [comment]
Thanks. That's a good sanity check. I haven't run into this before. 
I think the modders claiming the mod is compatible should consider this too...
