### ISSUE TITLE
[Bug] Compatible mod not shown in search results

### ISSUE THREAD

**Issue by Krazy0** [KSP-CKAN/CKAN#3262]
Background
----------
* Operating System: WIN10
* CKAN Version: 1.29.2
* KSP Version: 1.11

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Select: settings> compatible KSP versions: 1.11, 1.10, 1.9, 1.8
Set "Filter (compatible)"
Search term: portrait
results: none

Add compatible KSP version: 1.7

Results: Portrait Stats from DMagic, max KSP version 1.8.8

Apparently this mod should be shown when KSP version 1.8 compatibility is selected.

**Comment by DasSkelett** [comment]
Dublicate of #3261

**Comment by Krazy0** [comment]
sorry... it gave me a 404 error and I went back
