### ISSUE TITLE
repository update failured!

### ISSUE THREAD

**Issue by soldanithiago** [KSP-CKAN/CKAN#3267]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**
![image](https://user-images.githubusercontent.com/39207335/104637348-70e9b100-5683-11eb-805a-0ee0595b55dc.png)
Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
This is because R-T-B's server which hosted the metadata for Kopernicus Bleeding Edge releases is down.
We've since migrated it to GitHub. Please go into the settings, remove the `Kopernicus_BE` repository and add it again to get the new URL.

**Comment by soldanithiago** [comment]
> This is because R-T-B's server which hosted the metadata for Kopernicus Bleeding Edge releases is down.
> We've since migrated it to GitHub. Please go into the settings, remove the `Kopernicus_BE` repository and add it again to get the new URL.

It works! Thank you!
