### ISSUE TITLE
Sounds Of Space mod

### ISSUE THREAD

**Issue by volcanoboy08** [KSP-CKAN/CKAN#3274]
Mod info
--------
* Mod name: Sounds Of Space
* Author(s): itsmeowdev
* License: by nc sa 4.0
* Homepage: https://www.curseforge.com/kerbal/ksp-mods/sounds-of-space
* Download: https://www.curseforge.com/kerbal/ksp-mods/sounds-of-space/download/2630260

**Comment by HebaruSan** [comment]
Curse doesn't let us crawl their mods, sorry. Last discussed in KSP-CKAN/NetKAN#7446.
