### ISSUE TITLE
The specified path, file name, or both are too long on Windows

### ISSUE THREAD

**Issue by Seggan** [KSP-CKAN/CKAN#3275]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.29.2
* KSP Version: 1.3.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Trying to install KSP Interstellar Extended gives an error: The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.

**Steps to reproduce**
* Try installing KSP Interstellar Extended

**Expected behavior**
It should install fine

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
```

**Comment by HebaruSan** [comment]
I just tried installing KSPIE and it worked fine (on Linux).

What is the full path to your KSP folder? The error is saying a path is too long, maybe that's true.

**Comment by HebaruSan** [comment]
Longest path in the ZIP is 128 characters, leaving 132 for the game folder:

```bash
unzip -l C56A9BC5-KSPInterstellarExtended-1.26.15.zip | awk '{print $4}' | wc -L
128
```

**Comment by Seggan** [comment]
Ah yes, the path was way too long. I moved the folder higher up and it was all fixed. Thanks.
