### ISSUE TITLE
[Bug] CKAN sends error on out-of-date dependency even though it is compatible 

### ISSUE THREAD

**Issue by MINDcraftYT** [KSP-CKAN/CKAN#3288]
Background
----------
* Operating System: Windows 10 64 bit
* CKAN Version: 1.29.2
* KSP Version: 1.11.0
  Compatibility mode is in use, and mods from 1.8 to 1.11 are selected as compatible

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
When I install a mod CKAN auto adds the dependency but stops the download due to incompatible dependency, even though it is up to date. Only can be bypassed by selecting the mod and manually selecting the mod version installed.

**Steps to reproduce**
Select a mod with hard dependency/ies
Select Apply Changes
Click Apply
(Possible step: select recommended mods(unsure))
Error message on screen

**Expected behavior**
After Apply is selected mods will start installing

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/33611747/106533174-81cd5b80-64a6-11eb-9fd6-c47ddead844b.png)

**CKAN error code (if applicable):**

```
No code
```

**Comment by HebaruSan** [comment]
RPM is **not** compatible with 1.11.0:

![image](https://user-images.githubusercontent.com/1559108/106533409-bdbcec80-64b7-11eb-9194-7a1629ce3206.png)

**Comment by MINDcraftYT** [comment]
Compatibility mode is in use, and mods from1.8 to 1.11 are listed as compatible, so I suppose your comment is incorrect. Sorry for not listing this

**Comment by MINDcraftYT** [comment]
Just close it, an error on my side. Sorry for all the inconvenience

**Comment by HebaruSan** [comment]
Glad you got it working! :tada:
