### ISSUE TITLE
New Kopernicus Version

### ISSUE THREAD

**Issue by ZYLKerman** [KSP-CKAN/CKAN#3289]
Kopernicus now have a developing edition that supports KSP 1.8.1 to 1.11.1,but it seems that CKAN hasn't offered its download yet.As a 1.11 user,I strongly suggest to contain it in CKAN.

The BE edition is (almost) the same as the edition you're offering now,but it support a wider range of KSP versions,as well less stable.

Link of the BE version:[here](https://forum.kerbalspaceprogram.com/index.php?/topic/195699-181-111r-t-bs-kopernicus-unified-bleeding-edge-branch/)

**Comment by HebaruSan** [comment]
Hi, we've already dealt with this, see KSP-CKAN/CKAN-meta#2159 and https://github.com/KSP-CKAN/CKAN-meta#2229. From the OP of the forum thread you linked to:

![image](https://user-images.githubusercontent.com/1559108/106710283-4f615280-65bb-11eb-8ba4-7587a8068123.png)
