### ISSUE TITLE
[Bug] BDArmory Continued won't download because it conflicts with BDArmory but never had it installed.

### ISSUE THREAD

**Issue by calebfrieler** [KSP-CKAN/CKAN#3295]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.29.2
* KSP Version: 1.9.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug** BDArmory Continued will get an installation error because it conflicts with BDArmory. The problem with this is I don't even have BDArmory installed and I have never had it installed.

**Steps to reproduce**
* Go to: the main page with the check marks to install the mods you choose.
* Click on: BDArmory Continued check mark, then click “Apply Changes” 
* See error:
**The following inconsistencies were found:
BDArmoryContinued 1:v1.3.4 conflicts with BDArmory
BDArmoryContinued 1:v1.3.4 conflicts with BDArmory
Error during installation!**

**Expected behavior**
To install BDArmory Continued

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/65574962/107891861-e8ab3580-6ee6-11eb-860c-af94970de426.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
The "Steps to reproduce" section is meant to capture what you're doing in the application so we can investigate. Can you please fill that out?

**Comment by calebfrieler** [comment]
> The "Steps to reproduce" section is meant to capture what you're doing in the application so we can investigate. Can you please fill that out?

Just fixed it thanks for pointing that out

**Comment by HebaruSan** [comment]
Thanks! I just tried installing BDArmoryContinued, and it worked fine, so there's something else different on your system.
What other mods do you currently have installed?

**Comment by calebfrieler** [comment]
> Thanks! I just tried installing BDArmoryContinued, and it worked fine, so there's something else different on your system.
> What other mods do you currently have installed?

Just MechJeb 2 and DeepFreeze Continued plus any dependencies they may have needed.

**Comment by HebaruSan** [comment]
Hmm, that wasn't it, everything's still working fine on my end.
Can you do a search of your game folders for a file called "BDArmory.dll"? A conflict like this might happen if such a file exists somewhere, maybe some other mod included it.

**Comment by calebfrieler** [comment]
> Hmm, that wasn't it, everything's still working fine on my end.
> Can you do a search of your game folders for a file called "BDArmory.dll"? A conflict like this might happen if such a file exists somewhere, maybe some other mod included it.

I’ll do that later as I am no longer at my pc, thank you

**Comment by HebaruSan** [comment]
Sounds good, please let us know what you find.

**Comment by calebfrieler** [comment]
> Sounds good, please let us know what you find.

I ended up installing in with curse forge launcher and then deleting it, it seemed to delete anything that may have been conflicting and everything was installed fine :)

**Comment by HebaruSan** [comment]
Did you have a chance to search for a "BDArmory.dll" file before doing that?

**Comment by calebfrieler** [comment]
> Did you have a chance to search for a "BDArmory.dll" file before doing that?

Yes I did and I could not find it anywhere in GameData, that was why I reinstalled it and deleted it so that the CurseForge launcher would delete all parts of it.

**Comment by HebaruSan** [comment]
OK, so you're no longer having this issue then?

**Comment by calebfrieler** [comment]
> OK, so you're no longer having this issue then?

No I am not, you may close the thread, unless I have to
