### ISSUE TITLE
Checkbox to (de)select all mods covers column header

### ISSUE THREAD

**Issue by Zaureau15** [KSP-CKAN/CKAN#3301]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.29.2
* KSP Version: 1.11.1.3066

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
nope
![ckan bug](https://user-images.githubusercontent.com/56055012/108878819-9d6fe180-75ce-11eb-9ff7-945641378e2c.png)

![image](https://user-images.githubusercontent.com/1559108/109051718-6964f100-76a0-11eb-9182-870c5b9c2506.png)

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**
Not to cover the text

**Screenshots (if applicable)**
File attached

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
So the way this works is the checkbox just floats above the grid by default, so we make room for it by adding spaces to the beginning of that cell:

https://github.com/KSP-CKAN/CKAN/blob/b748670c20db29ea366af3095837e2ffe0cbd7b7/GUI/Controls/ManageMods.resx#L169

On Linux it looks a bit better, if still crowded:

![image](https://user-images.githubusercontent.com/1559108/109051569-45091480-76a0-11eb-95db-5df2046aee88.png)

It looks like the cell is wrapping for you. If you make the column wider, it should be able to show the text. Can you confirm that?

**Comment by Zaureau15** [comment]
Here's what it looks like, now that I made the row wider. I still can't see
most of the word, but I should be fine. Thanks! [image: image.png]
-Tristan

**Comment by HebaruSan** [comment]
Maybe we should move this checkbox up above the grid. There's room now that the search field is moved over.
