### ISSUE TITLE
[Bug] Warns about incompatible modules which are actually DLC

### ISSUE THREAD

**Issue by SliceofLie** [KSP-CKAN/CKAN#3302]
Background
----------
* Operating System: Windows 10 Home 20H2 build 19042.804
* CKAN Version: 1.29.2
* KSP Version: 1.11.1.3066

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
CKAN complains some installed modules are incompatible and warns might not be safe to launch KSP. (MakingHistory-DLC 1.11.0 (KSP 1.11.0)). This does NOT happen on a clean install of CKAN with no downloaded/cached, or installed modules. Only after a module has been downloaded and installed does it complain, and removing the module does not change this constant popup. No actual incompatibility has been found.

**Steps to reproduce**
Fresh install of CKAN and KSP with all DLC.
Install module(s).
Attempt to launch KSP from CKAN
Warning window appears, only listed item is the Making History DLC.

**Expected behavior**
CKAN should not erroneously warn about incompatible modules which aren't even modules, its an official DLC. 

EDIT: screenshot of pop-up as requested
![ckan](https://user-images.githubusercontent.com/25392186/108900815-b339d280-75df-11eb-84a9-912ec97afa3e.png)

**Comment by HebaruSan** [comment]
Can you please show us the error message? You should be able to copy and paste it into the issue.

**Comment by HebaruSan** [comment]
I think this is caused by an error in SQUAD's `readme.txt` for the latest version of MH. It says `Version 1.11.0`, when it's clearly 1.11.1 since that version is mentioned in the changelog below. MH 1.11.0 is for KSP 1.11.0, hence the message.

Nonetheless, it would probably make sense to exclude DLCs from this check.

**Comment by HebaruSan** [comment]
As a short term workaround, adding 1.11 or 1.11.0 as compatible versions should make CKAN consider that DLC as compatible:

- https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions

**Comment by StevenLi-phoenix** [comment]
Same issue for #3306

**Comment by DasSkelett** [comment]
@StevenLi-phoenix see the workaround above or the test build linked in #3304.
