### ISSUE TITLE
[Bug] Update not working with the deb file repo

### ISSUE THREAD

**Issue by blazux** [KSP-CKAN/CKAN#3309]
Background
----------
* Operating System:  Debian 10
* CKAN Version: Latest

Problem
-------
apt upgrade fails to update to the latest CKAN version

Problem with the deb file maybe ?

```
The following packages will be upgraded:
  ckan
1 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
Need to get 775 kB of archives.
After this operation, 0 B of additional disk space will be used.
Do you want to continue? [Y/n] Y
Get:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065 [775 kB]
Err:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065
  File has unexpected size (774308 != 774780). Mirror sync in progress? [IP: 52.218.184.25 443]
  Hashes of expected file:
   - SHA256:20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
   - SHA1:24241c129cf0b4478706b430362568df35d55cd5 [weak]
   - MD5Sum:3bd7a5896c00e81b1bcd1ebe19c34909 [weak]
   - Filesize:774780 [weak]
E: Failed to fetch https://ksp-ckan.s3-us-west-2.amazonaws.com/deb/pool/ckan_1.30.0.21065_all.deb  File has unexpected size (774308 != 774780). Mirror sync in progress? [IP: 52.218.184.25 443]
   Hashes of expected file:
    - SHA256:20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
    - SHA1:24241c129cf0b4478706b430362568df35d55cd5 [weak]
    - MD5Sum:3bd7a5896c00e81b1bcd1ebe19c34909 [weak]
    - Filesize:774780 [weak]
E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?

```

**Comment by DasSkelett** [comment]
Interesting, I had this happen to me a few days ago, but right now it is fine, for both nightly and stable.
But looking at the files, it _should_ also happen to me:
`deb/dists/stable/main/binary-amd64/Packages.gz` contains
```
Version: 1.30.0.21065
Filename: pool/ckan_1.30.0.21065_all.deb
Size: 774780
MD5sum: 3bd7a5896c00e81b1bcd1ebe19c34909
SHA1: 24241c129cf0b4478706b430362568df35d55cd5
SHA256: 20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
```
but the release deb `deb/pool/ckan_1.30.0.21065_all.deb` has `<Size>774308</Size>`.

Maybe the nightly workflow replaced the deb after the release workflow?
This doesn't explain how this happened to me a few days ago, but it could have been two "nightly"/deploy workflows interacting with each other.

**Comment by HebaruSan** [comment]
> This doesn't explain how this happened to me a few days ago, but it could have been two "nightly"/deploy workflows interacting with each other.

Yes, I think that's exactly what happened (I saw the same thing at the time). #3304 and #3300 were merged within 1 minute of each other, so they probably clobbered each other's uploads in various ways. I thought the stable releases would have been immune to this, since they should only be updated when we create a release, which tend to have spacing on the order of months rather than minutes.

... Oh, right. Debian made us put those in a shared `/pool/` folder instead of something specific to `stable` or `nightly`, and there would have been a `nightly` build of v1.30.0 when 0376e0332f3815a0fc0e23329204bdab00b5dff5 was pushed. The release was out 2 minutes later, so I guess something similar may have happened there.

So either we need to wait 5-10 minutes between actions that update S3, or we need to make our build system less sensitive to timing.

**Comment by HebaruSan** [comment]
Another idea, we could skip uploading `nightly` builds if the build number is even (v.1.30.**0** vs v1.30.**1**). That's how we distinguish releases from test builds now, so it should be a reliable way to draw a line.

**Comment by HebaruSan** [comment]
To deal with the more immediate problem, I'm going to try re-running the release triggers now in the hopes of having it update both the .deb file and the release listing. There should be no remaining risk of conflicts now that nightly builds are on v1.30.1.

**Comment by DasSkelett** [comment]
> To deal with the more immediate problem, I'm going to try re-running the release triggers now in the hopes of having it update both the .deb file and the release listing. There should be no remaining risk of conflicts now that nightly builds are on v1.30.1.
> 
> EDIT: Fail. GitHub blocked us from updating the assets on the release, so the whole work flow stopped before it got to the S3 steps.

Probably for the better. Regenerating the releases would've resulted in different files with different hashes. This likely wouldn't only have meant another round of antivirus false positives, but also screwed several package managers that already indexed v1.30.0 (the same thing we complained so much about in the past).

**Comment by Myricaulus** [comment]
Hi thanks for all your hard work. I love CKAN for KSP. 
But I am sorry, i still get the same error right now: 
`Holen:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065 [775 kB]
Fehl:1 https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable/main amd64 ckan all 1.30.0.21065
  Datei hat eine unerwartete Größe (774308 != 774780). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 52.218.221.145 443]
  Hashes of expected file:
   - SHA256:20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
   - SHA1:24241c129cf0b4478706b430362568df35d55cd5 [weak]
   - MD5Sum:3bd7a5896c00e81b1bcd1ebe19c34909 [weak]
   - Filesize:774780 [weak]
E: Fehlschlag beim Holen von https://ksp-ckan.s3-us-west-2.amazonaws.com/deb/pool/ckan_1.30.0.21065_all.deb Datei hat eine unerwartete Größe (774308 != 774780). Eventuell läuft gerade eine Spiegel-Synchronisierung? [IP: 52.218.221.145 443]
   Hashes of expected file:
    - SHA256:20bd6bbfe1132e3656e696f4e77bce8a5e0ae7e605563814b2f149ace96dbd0b
    - SHA1:24241c129cf0b4478706b430362568df35d55cd5 [weak]
    - MD5Sum:3bd7a5896c00e81b1bcd1ebe19c34909 [weak]
    - Filesize:774780 [weak]
E: Einige Archive konnten nicht heruntergeladen werden; vielleicht »apt-get update« ausführen oder mit »--fix-missing« probieren?
`

**Comment by HebaruSan** [comment]
Yeah, it's not fixed. We're close to a new release, which will resolve the issue, so it's probably best to wait for that. Or try the nightly builds:

```
sudo curl -sS -o /etc/apt/trusted.gpg.d/ksp-ckan.gpg https://raw.githubusercontent.com/KSP-CKAN/CKAN/master/debian/ksp-ckan.gpg
sudo apt-add-repository -u -y deb https://ksp-ckan.s3-us-west-2.amazonaws.com/deb nightly main
sudo apt install ckan
```

**Comment by HebaruSan** [comment]
The new release is out:  https://github.com/KSP-CKAN/CKAN/releases/tag/v1.30.2

I tried installing the stable build with `apt`, and it worked for me. I think we fixed this.
