### ISSUE TITLE
Windows Defender: Possible false positive 

### ISSUE THREAD

**Issue by Tabris83** [KSP-CKAN/CKAN#3310]
just tried updating to the new version
![image](https://user-images.githubusercontent.com/8855255/110204140-3949f900-7ebd-11eb-8607-59bc9ee3b5c5.png)

**Comment by XerdosLoreskull** [comment]
Same issue.

**Comment by DasSkelett** [comment]
Windows Defender keeps detecting release assets by various GitHub projects as this.
Their [info page](https://www.microsoft.com/en-us/wdsi/threats/malware-encyclopedia-description?Name=Trojan:Win32/Emali.A!cl) on this detection type explains literally nothing about it.

[VirusTotal](https://www.virustotal.com/gui/file/c22879351cde3b2e16317437c95f56fe6db1ec1d82e53d05efc4dba6c9e08a04/summary) agrees that the file is fine.

Please report false positives to your antivirus software.

**Comment by DasSkelett** [comment]
@XerdosLoreskull that exception happens because there's a new mod indexed already that requires CKAN v1.30.0, and you already refreshed after you updated so it's in your registry now.
I recommend to stay on v1.30.0 and dismiss the warning, there's nothing we can do about it.

**Comment by DasSkelett** [comment]
A Discord user found a way to make Windows Defender ignore the file:

![image of comment explaining where to find the settings](https://user-images.githubusercontent.com/28812678/110209219-84e3af00-7e8b-11eb-9bf2-7077325756b7.png)

![image of settings screen](https://cdn.discordapp.com/attachments/295199794102796288/817753177553764372/image0.jpg)

Also @Draconomial kindly provided a link where you can report false positives. Maybe if everyone who has a Microsoft account and is suffering from this reports it, there might be a chance to get them to allowlist it (or whatever they do so it doesn't get blocked anymore):
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by DasSkelett** [comment]
I've just received an answer by Microsoft on the report. They removed the detection and provided steps to update the malware definitions (I guess so you don't have to wait 24h or so until it refreshes automatically:

![answer](https://user-images.githubusercontent.com/28812678/110211654-e4e05280-7e97-11eb-9fcd-2ab2ddb0dc0d.png)

<details>
<summary>
Expand for a text version to make copy-pasting the commands easier
</summary>

> Analyst comments:
> We have removed the detection.  Please follow the steps below to clear cached detection and obtain the latest malware definitions.
>    1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>    2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>    3. Run "MpCmdRun.exe -SignatureUpdate"
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions
> Thank you for contacting Microsoft.

</details>
