### ISSUE TITLE
[Feature]MacOS 64bit terminal version missing adding "incompatible mods"

### ISSUE THREAD

**Issue by StealthHydra179** [KSP-CKAN/CKAN#3316]
Problem
-------
**Is your feature request related to a problem? Please describe.**
I might be missing something here, but in the 64 bit mac version (the one in the terminal), I can't seem to figure out where I can enable old mods or incompatible mods. For the 32 bit versions and the windows versions I can see those options, but in the 64 but mac version I can't find it. Some of the mods that I want to install are only available for previous versions and I can't find it in the list because I cannot enable that setting. Am I missing something?

Suggestions
-----------
**Describe the solution you'd like**
Having a setting where we can enable incompatible mods just like in the gui version.

**Describe alternatives you've considered**
Reinstalling to a different OS (not very feasible)
Using other programs (none are as good)
Manual install (tedious)

**Additional context**

**Comment by HebaruSan** [comment]
Are you just looking for the compatible versions list?

F10 → Select KSP install... → Pick your install → Press 'e' to edit → Tab a few times to get to the compatible version list

**Comment by StealthHydra179** [comment]
I am looking to look for mods only compatible with previous versions and incompatible mods like you can on the gui version

**Comment by HebaruSan** [comment]
OK. Are you familiar with the compatible versions list? It's true that incompatible mods aren't shown in ConsoleUI, but if you mark, for example, KSP 1.9–1.10 as compatible, then many of those mods will appear and be installable.

**Comment by StealthHydra179** [comment]
ah ok thank you, maybe writing it in the docs would be helpful, I might have missed it though

**Comment by HebaruSan** [comment]
> ah ok thank you, maybe writing it in the docs would be helpful, I might have missed it though

Heh, I agree, I was editing it as we were discussing here, although whether folks are able to find the relevant documentation in any given case tends to be pretty unpredictable:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide/_compare/35061c5%5E...35061c5
