### ISSUE TITLE
[Bug] Mods wont install, changeset blank. If download content - error

### ISSUE THREAD

**Issue by Hunweibyn** [KSP-CKAN/CKAN#3321]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.0
* KSP Version: 03066 1.11.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes

Problem
-------
After launching CKAN and choose what mode to install, there is changeset tab appear, but when i open it - it's empty but apply is active. When i press Apply it shows error 

If you'd do download content on any mod, you'll get error #2 (code2, screen2)

**Steps to reproduce**
Launch CKAN, choose mod and open changeset

**Expected behavior**

![Снимок экрана 2021-03-09 231414](https://user-images.githubusercontent.com/28391654/110532018-5edd3980-812d-11eb-9efb-523689a8784d.png)

![Снимок экрана 2021-03-09 231639](https://user-images.githubusercontent.com/28391654/110532228-9d72f400-812d-11eb-80d5-2e08a674f980.png)
**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
About to install:
code1:
Ссылка на объект не указывает на экземпляр объекта.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

code2:

Unhandled exception:
System.NullReferenceException: Ссылка на объект не указывает на экземпляр объекта.
   в CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error)
   в CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error)
   в CKAN.NetAsyncDownloader.NetAsyncDownloaderDownloadPart.<ResetAgent>b__20_1(Object sender, AsyncCompletedEventArgs args)
   в System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   в System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   в System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   в System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Comment by HebaruSan** [comment]
Google Translate says:

> An object reference does not point to an instance of an object.

**Comment by Hunweibyn** [comment]
Found the source of my problem and solved it.
The goal was in cache folder %userapps%\local\ckan\downloads which was symlinked to the instance already don't exist. So it was looked like broken shortcut for ckan. 
After recreated downloads - everything goes ok!
