### ISSUE TITLE
Intermittent timeouts of ksp.spacetux.net slow down the bot

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3324]
just an FYI, my systems suffered a new DHCP address change today, so the calls to ksp.spacetux.net have been failing for a couple of hours.

I've just gotten the ddclient to run, so it should be ok in a few minutes.

Go ahead and close this when you read it, was just the fastest way I knew to get you the message

**Comment by DasSkelett** [comment]
> Sounds good to me. I wonder how much of a risk there would be of false positives, timing out something that is actually working and just needs a few more seconds.

The risk exists of course, but I think if we only apply it to NetKAN downloads, it is manageable. I'm open for suggestions about the timeout duration. I'm currently thinking of 10 seconds, which should be plenty for text downloads.
