### ISSUE TITLE
System Access Exception after changing PC username

### ISSUE THREAD

**Issue by DeNomaly** [KSP-CKAN/CKAN#3333]
After changing my name (and with this the username of my PC), CKAN seems to be unable to grasp that this change has occured and gives me an error through the console stating there was a system access exception after trying to reach the C:\Users\[oldusername]\AppData\Local\CKAN\Downloads

*oldusername refers to the username of my PC before changing the name. It's most definitely part of the PCs registries since deleting CKAN and downloading it again does absolutely nothing to fix the issue. I'd love to get some help with how to fix this since it not only makes CKAN unusable for me but also means that my deadname is still present somewhere on my PC despite me having gone through and removed it from the registries once already. Very annoying, plz help
(name removed from screenshot on purpose)
![Screenshot (1008)](https://user-images.githubusercontent.com/77215953/112760574-c3d2d380-8ff7-11eb-90c7-4f3e5a1fc86f.jpg)

**Comment by HebaruSan** [comment]
Try this:

1. Start → Run
2. `%LOCALAPPDATA%\CKAN`
3. Find the file `config.json`
4. Open it in a text editor
5. Find the old user name and replace it with the new user name
6. Save and close the file
7. Run CKAN
