### ISSUE TITLE
[Bug] Import Downloaded Mods doesn't have an effect

### ISSUE THREAD

**Issue by alexschneider** [KSP-CKAN/CKAN#3336]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30
* KSP Version: 1.11.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug**
I'm using this mod: https://github.com/linuxgurugamer/KSP-X-Science/releases
I'm pretty sure this issue happened previously with another mod, but I don't recall which it was. 

**Steps to reproduce**
* Download the 6.0.0.6 release of KSP X Science
* Open CKAN
* Click on File
* Click on "Import Downloaded Mods"
* Navigate to Downloads folder and open previously downloaded file "x.-Science.-1.10.1-6.0.0.6.zip"\

**Expected behavior**
The mod gets imported or shows up in pending changes

**Actual Behavior**
The application screen briefly flashes and nothing apparent happens. The mod is not put in the game directory.

**Comment by DasSkelett** [comment]
That mod isn't indexed on CKAN yet (it's still in beta, and linuxgurugamer doesn't put beta mods on CKAN for understandable reasons). Thus CKAN can't import the zip for you - it can only import zips it knows about and knows how to install.

The lower left corner contains an error message to indicate that the import failed:
![image](https://user-images.githubusercontent.com/28812678/112922816-6e88e600-910d-11eb-81b8-2949d8ad335f.png)

I know that little error message down there isn't very visible (as with conflicts), but I have yet to find a good way to give them more visibility - a pop-up you have to click away is too interruptive IMHO.

So until the mod is out of beta and linuxgurugamer adds it to CKAN, you need to install it manually.

**Comment by HebaruSan** [comment]
Thanks for doing that leg work, @DasSkelett.
Closing as everything seems to be working as expected.

**Comment by alexschneider** [comment]
Ah ok. I'd argue that a pop up in the case of failing to install a mod from a zip isn't too interruptive as there's no way for the user to discover otherwise (and it only happens once). Conflicts, sure, since they happen more often. But of course, it's your software.
