### ISSUE TITLE
Only 32 mods showing, all unavailable

### ISSUE THREAD

**Issue by Miles8704** [KSP-CKAN/CKAN#3338]
Background
----------
* Operating System: Mac OSX (latest big sur update)
* CKAN Version: v1.30.0
* KSP Version: 1.8.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes i downloaded a number of mods to my GameData folder manually, however i deleted the entirety of my KSP folder and reinstalled the game to clear previous mods

Problem
-------
**Describe the bug**
So i was using CKAN to download Realism Overhaul and a number of related mods, after installing MechJeb2 Dev and returning to CKANs home screen, only 32 mods show and every one of them has the '!' for being unavailable except for MechJeb which shows as installed. All the mods i previously installed via CKAN arent showing either but do show in /GameData

**Steps to reproduce**
Open CKAN and the problems there... 
Steps i did leading up to the problem, downloaded RO, RP1 and RSS. started to select the other mods i intended on installing, couldn't find mechjeb dev version, figured that out by editing game instance and then adding mechjeb dev under mod list. saved changes, clicked esc, and bam everything go bye bye

**Expected behavior**
?? i believe the answer to this is i expected to see the mod list as i had every other time i opened CKAN?

**Screenshots (if applicable)**
<img width="611" alt="Screen Shot 2021-03-30 at 9 33 12 PM" src="https://user-images.githubusercontent.com/81661457/113077736-b3f5f380-919f-11eb-82e5-71495798bea9.png">

**CKAN error code (if applicable):**
```
PLACE CODE HERE !  N/A
```
side note, thanks :)

**Comment by Miles8704** [comment]
Sorry to bother with that, it decided to show the mods just after i submitted the post (it hadn't been working for like 30 mins don't yell at me)

**Comment by HebaruSan** [comment]
Don't worry, yelling is against the code of conduct.
