### ISSUE TITLE
[Feature] Manually declare dependency satisfied

### ISSUE THREAD

**Issue by LupusTheCanine** [KSP-CKAN/CKAN#3339]
## Problem

There are multiple mods that depend on some configuration package (another mod), but not all of said mod support CKAN which forces users to manually install both the base mod and configuration package which is annoying.

## Suggestions

Option to claim dependency satisfied by manually installed mod.

The only other option is to manually install mods.

**Comment by HebaruSan** [comment]
Can you please share the specific example you encountered? It always helps to have a motivating use case when analyzing a request and designing a feature.

**Comment by Fernir2000** [comment]
In my case it was  Less Real than Real(ism) providing config for Kerbalism.
I believe allowing for manually satisfying dependencies would be helpful when users want to use homebrew or just not indexed configs for mods that rely on external config sets.

**Comment by HebaruSan** [comment]
> In my case it was Less Real than Real(ism) providing config for Kerbalism.

I see. CKAN has a `LessRealKerbalism` module which I believe installs that config and should integrate properly with Kerbalism. Could that work for you?

**Comment by LupusTheCanine** [comment]
> I see. CKAN has a `LessRealKerbalism` module which I believe installs that config and should integrate properly with Kerbalism. Could that work for you?

That should work but I would like to have a way to deal with manually installed mods as dependencies because adding all mods to CKAN is infeasible and some people want to use custom configs. Support for manually satisfying dependencies could be really useful in my opinion.

**Comment by HebaruSan** [comment]
> Support for manually satisfying dependencies could be really useful in my opinion

Yes, we know that's your opinion, you said it already. :grin: 

That perceived benefit has to be balanced against the many downsides of making CKAN's relationship 
handling less reliable. We have a responsibility to mod authors to install their mods correctly, and any gap that we create in dependency handling is a risk that "just mark it as manually installed to bypass" becomes a suggested solution among users, leading to support requests when things don't actually work.

> That should work

Good! Closing.
