### ISSUE TITLE
[Bug] CKAN can't read zips from custom cache location on Windows

### ISSUE THREAD

**Issue by melon-husk** [KSP-CKAN/CKAN#3355]
Background
----------
* Operating System: Windows 10  20H2
* CKAN Version: v1.30.0
* KSP Version: v1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Installations of any mod fails when cache is purged and cache path is changed.

**Steps to reproduce**
* Go to CKAN settings and Purge All cache
* Change the cache folder path to somewhere else
* Try to install any mod
* You would get this error _sometimes_
```
Downloading "https://spacedock.info/mod/1466/FuelEfficientPilots/download/0.2"
Trying to install FuelEfficientPilots 0.2, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose
```

**Expected behavior**
Mod would install

**Screenshots (if applicable)**
![1](https://user-images.githubusercontent.com/30780724/115972995-82d6cc00-a56f-11eb-9ed9-a1204c0ee825.png)
![2](https://user-images.githubusercontent.com/30780724/115972999-84a08f80-a56f-11eb-8b22-8f71eae23191.png)

**Comment by DasSkelett** [comment]
An important detail from the conversation on Discord:
The cache is located at `D:\KSP Mods Cache`; files get stored in it, but either they get corrupted while moving into cache, or CKAN has trouble reading them from the cache:
![](https://cdn.discordapp.com/attachments/132503638793912320/835620084202209295/unknown.png)

@melon-husk to make sure, did you just purge the cache and it worked again, or did you change the reset the cache location?

**Comment by melon-husk** [comment]
@DasSkelett I purged the cache again and it didn't work, only way to make it work was to reset the cache path

**Comment by melon-husk** [comment]
@DasSkelett Were you able to reproduce the bug ?

**Comment by DasSkelett** [comment]
Not yet, still in the process of setting up a USB stick to serve as new drive. I'll let you know of the results once I tested it.

**Comment by DasSkelett** [comment]
Yup, I can reproduce it, simply by formatting a USB stick with NTFS, inserting it, creating a folder called "KSP Mod Cache" and setting CKAN's cache to that folder.
Now onto debugging this...

**Comment by melon-husk** [comment]
Any way I can help with this ?

**Comment by DasSkelett** [comment]
If you know some C#, you could try to look at the code, and see if you can spot what's wrong.
To start, this is where we try to get the file out of the cache (after we downloaded it beforehand), and if we can't find it, we throw the exception you saw in the output log:
https://github.com/KSP-CKAN/CKAN/blob/491e042f03d82c76898029af523bec8dca7f086f/Core/ModuleInstaller.cs#L285-L295

It goes down to
https://github.com/KSP-CKAN/CKAN/blob/491e042f03d82c76898029af523bec8dca7f086f/Core/Net/NetFileCache.cs#L244
and
https://github.com/KSP-CKAN/CKAN/blob/491e042f03d82c76898029af523bec8dca7f086f/Core/Net/NetFileCache.cs#L159
and so on, something somewhere is failing to find the file.

**Comment by DasSkelett** [comment]
Okay, this is getting weird. Out of nowhere, without changing anything, I can't reproduce it anymore.

This makes me think it's Windows doing Windows things with other drives, that somehow interferes with CKAN. And sometimes it decides to not do Windows things.

**Comment by HebaruSan** [comment]
This is a stretch, but have the USB drives in question been subjected to any integrity checking? Flash memory does go bad after a while, I think, and NTFS isn't exactly designed for it.

**Comment by DasSkelett** [comment]
That would have been some luck, hitting the bad section at the first attempt but not anymore since (not sure whether good or bad luck).

But it is a possibility. But not sure whether @melon-husk uses a flash drive too. It would be a big one though, here's another image they sent earlier in the Discord:

![](https://cdn.discordapp.com/attachments/132503638793912320/835618818998927411/unknown.png)

**Comment by HebaruSan** [comment]
> not sure whether @melon-husk uses a flash drive

Ahh, I misunderstood, then. Never mind.

**Comment by melon-husk** [comment]
> But not sure whether @melon-husk uses a flash drive too. 
C and D drives are SSD's, E is HDD

**Comment by HebaruSan** [comment]
Is it drive letters that cause this? What was that other thing we had where Windows made us do insane gymnastics to accommodate drive letters?

**Comment by DasSkelett** [comment]
Okay, I somehow just managed to trigger the error again. What I can confirm is that the file is not actually corrupt, the hashes match:
```
$ sha256sum.exe 7FED6881-MechJeb2-2.12.0.0.zip
3cdec0fe9db145b3b3d6075bef3e8ccfed1fa36cf15defdb6b6678342a6b6f71 *7FED6881-MechJeb2-2.12.0.0.zip
```
https://github.com/KSP-CKAN/CKAN-meta/blob/ba7b4f7b2ef914e2145ac3fce0b9c2b4c5953352/MechJeb2/MechJeb2-2.12.0.0.ckan#L42

Now let's see if I can find a way to reproduce it reliably, and where exactly it fails.

**Comment by DasSkelett** [comment]
Well, I found a reliable way to reproduce and a good hint at what's happening - in my case.
The trick wasto insert the USB stick while CKAN is running (which also means changing the cache back to the thumb drive location since #3334).
It looks like only parts of CKAN switch to the new cache location (i.e. the actual downloading), but other parts still try to read from the old location (the final cache lookup to open the zip for installation):
(look at the last message in each block, it contains the cache location we're trying to access, logged from inside `GetCachedFilename()`)
```
# Lookup for changeset tab
DEBUG Checking cache for 7FED6881 https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/29/artifact/MechJeb2-2.12.0.0.zip
DEBUG cachedFile 7FED6881 E:\KSP Mod Cache\7FED6881-MechJeb2-2.12.0.0.zip
DEBUG hash in files, using
DEBUG found != null or empty, cachePath E:\KSP Mod Cache

# Lookup for recommendation tab
DEBUG Checking cache for E66CA611 https://spacedock.info/mod/1204/ASET Props/download/1.5
DEBUG cachedFile 7FED6881 E:\KSP Mod Cache\7FED6881-MechJeb2-2.12.0.0.zip
DEBUG found == null or empty, cachePath E:\KSP Mod Cache

# Lookup to determine whether it needs downloading, maybe?
DEBUG Checking cache for 7FED6881 https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/29/artifact/MechJeb2-2.12.0.0.zip
DEBUG hash not in files
DEBUG found == null or empty, cachePath C:\Users\User\AppData\Local\CKAN\downloads

# Lookup during the download logic, maybe? At least the file gets also downloaded to this 
DEBUG Checking cache for 7FED6881 https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/29/artifact/MechJeb2-2.12.0.0.zip
DEBUG cachedFile 7FED6881 E:\KSP Mod Cache\7FED6881-MechJeb2-2.12.0.0.zip
DEBUG hash in files, using
DEBUG found != null or empty, cachePath E:\KSP Mod Cache

DEBUG Checking cache for 7FED6881 https://ksp.sarbian.com/jenkins/job/MechJeb2-Release/29/artifact/MechJeb2-2.12.0.0.zip
DEBUG hash not in files
DEBUG found == null or empty, cachePath C:\Users\User\AppData\Local\CKAN\downloads
DEBUG GetCachedFilename returned null
```

However further testing showed this is also the case for simply changing the cache location on the same disk, and doesn't seem to have anything to do with drives or so...

So I'm not sure if that's what's happening to @melon-husk as well. The current release doesn't have #3334, so CKAN should always stay with `D:\KSP Mod Cache` and not change it during runtime.

**Comment by HebaruSan** [comment]
Interesting. Everyone _should_ be sharing `Manager.Cache` now, but clearly somebody's making a new cache object somewhere, to get different cache paths interleaved in the log like that. I wonder where that happens...

**Comment by HebaruSan** [comment]
I guess it's the settings window, indirectly, when you change the path. `TrySetupCache` makes a new `NetModuleCache` object and assigns it to `GameInstanceManager.Cache`. Any persistent references are out of date at that point.

https://github.com/KSP-CKAN/CKAN/blob/8f2a1d8185da691fb5684146d4c5e5da051af241/GUI/Dialogs/SettingsDialog.cs#L124-L125

https://github.com/KSP-CKAN/CKAN/blob/8f2a1d8185da691fb5684146d4c5e5da051af241/Core/GameInstanceManager.cs#L551-L560

**Comment by HebaruSan** [comment]
Aha, it's probably `ModuleInstaller`'s singleton pattern. `MainInstall.cs` gets its `ModuleInstaller` via `ModuleInstaller.GetInstance`, which only uses its `cache` parameter if the instance isn't found. So...

1. Install something; this will create a persistent `ModuleInstaller` instance for your game instance, using the currently configured cache path
2. Change the cache path; this _replaces_ `Manager.Cache` with a new cache object, _but the persistent `ModuleInstaller` instance doesn't know that happened and still has the old object_
3. Install something else; the old `ModuleInstaller` and cache object will be used

**Comment by HebaruSan** [comment]
We could patch `ModuleInstaller.GetInstance` to set `instance.Cache` when it finds an instance, but it might probably be smarter to remove that function completely and make the installer a normal class instead of a singleton.
