### ISSUE TITLE
[Support] how to reset application settings on macOS

### ISSUE THREAD

**Issue by AUnicornWithNoLife** [KSP-CKAN/CKAN#3358]
Hi, i recently changed the name for my home directory, and now CKAN is reporting an error that it cant open a file located in my old home directory, how can I reset CKAN so that it works?

i have tried reinstalling

**Comment by HebaruSan** [comment]
Looks approximately the same as #3333 (pinned just now).
There's a Windows-specific workaround suggestion there that I'll try to translate to Mac...

1. Open Finder
2. Starting from your home folder, navigate to `.local/share/CKAN`
4. Find the file `config.json`
5. Open it in a text editor
6. Find the old user name and replace it with the new user name
7. Save and close the file
8. Run CKAN

**Comment by AUnicornWithNoLife** [comment]
thank you so much

**Comment by HebaruSan** [comment]
Closing this on the assumption that that worked. If it didn't, let us know and we can re-open this.
