### ISSUE TITLE
Every time I try to download a mod, it says failed and that I dont have enough storage on the disc, which I do.

### ISSUE THREAD

**Issue by alexbro44** [KSP-CKAN/CKAN#3360]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
That description doesn't give us anything to investigate. Please fill in the template.
