### ISSUE TITLE
Ckan new instances

### ISSUE THREAD

**Issue by Kaai07** [KSP-CKAN/CKAN#3364]
Background
----------
* Operating System: windows 10
* CKAN Version: v1.29.2
* KSP Version: 1.11.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no i have not made any changes

Problem
-------
i recently installed a new ssd on my laptop and installed ksp on it.
now i wanted to instal Ckan so i can mod my ksp, but when i launched ckan it asked for the game instance.
my ksp file on the new ssd wasn't inbetween the options so i decided to make a new game instance.

but the problem of what i don't understand is when i try to open the new ksp file the file screen disappears and nothing is added to the game instance list.
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**
![12b050e4cfebedee8fb021669bba142f](https://user-images.githubusercontent.com/84129602/118115242-fcccd900-b3e8-11eb-9b05-3acb81f96086.png)

**CKAN error code (if applicable):**

```
26620 [1] ERROR CKAN.ErrorDialog (null) - Directory c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program is not a valid game directory.
```

**Comment by DasSkelett** [comment]
Just to confirm, your new instance is the one on the `S:` drive shown in the screenshot, and the old one is the one on `C:`?

> when i try to open the new ksp file the file screen disappears and nothing is added to the game instance list.

You need to select the `buildID` or `buildID64` file, did you do that?

**Comment by Kaai07** [comment]
yes i used to have ksp on my c: drive but had to delete it due to limited space now i have a new drive the S: drive in which i downloaded ksp again.

i did not know i had to select the buildID so i will try that.

thanks

**Comment by DasSkelett** [comment]
> it worked haha thank you very much.

Great!
