### ISSUE TITLE
[Bug] HyperEdit 1.5.8 is compatible with KSP 1.10.1

### ISSUE THREAD

**Issue by BenEvolent333** [KSP-CKAN/CKAN#3365]
Background
----------
* Operating System: Linux (Artix Linux)
* CKAN Version: 1.30.0
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I installed HyperEdit 1.5.8 manually from the Kerbeltek website.

Problem
-------
**Describe the bug**
CKAN does not manage HyperEdit for KDE 1.10.1, I have not tried it for other recent versions, but the mod is compatible.

**Steps to reproduce**
* Install KSP 1.10.1 from the website
* Install CKAN
* Search for HyperEdit
* HyperEdit doesn't show up

**Expected behavior**
HyperEdit should show up.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Hi, thanks for contributing. The compatibility of this mod is controlled by the author in this file:

https://github.com/Ezriilc/HyperEdit/blob/master/HyperEdit.version

You can try submitting an issue or pull request for that file, and if the author updates it there, it will update in CKAN automatically.

**Comment by HebaruSan** [comment]
Oops, meant to include this in the initial reply...

In the meantime, you can mark 1.9 as compatible in your CKAN client to install it anyway:

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions
