### ISSUE TITLE
[Feature] Dark Mode Interface

### ISSUE THREAD

**Issue by Midcon113** [KSP-CKAN/CKAN#3371]
Problem
-------
I usually play KSP at night in a dark room and when I open CKAN - the screen lights up brighter than a KSP RUD! :)

Suggestions
-----------
Implement a dark mode option, or at least tone the interface down so it's not bright white. I play on Windows and everything is set to dark mode by default; could it detect the Windows theme and set itself accordingly?

Thanks!

**Comment by DasSkelett** [comment]
> could it detect the Windows theme and set itself accordingly?

He, it actually already does take whatever colors the OS tells it to use, we've put a bunch of work into that [here](https://github.com/KSP-CKAN/CKAN/pull/2937). And this works great on Linux and macOS with Mono + GTK themes, however for whatever reason, Microsoft decided to not let WinForms apps know of the dark mode on Windows.
And even worse, the dialog with which you could manually change the color scheme on Windows 7 got removed on Windows 10. But you can still change the settings in the registry: https://superuser.com/a/1190188/672860

With the current WinForms UI, this is all we can do right now. Writing a custom theme would be a disproportionately high amount of work, unfortunately.
