### ISSUE TITLE
[Docu] apt-add-repository command not backwards compatible to Ubuntu LTS

### ISSUE THREAD

**Issue by Myricaulus** [KSP-CKAN/CKAN#3373]
Background
----------
* Operating System: Ubuntu 1804
* CKAN Version: not related
* KSP Version: not related

The line in the release notes for Debian is wrong

```
sudo apt-add-repository -y deb https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main
Fehler: Eine einzelne Paketquelle wird als Argument benötigt
```
There are missing quotes around the packet info like:

```
sudo apt-add-repository -y "deb https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main"
```
This did work.

**Comment by HebaruSan** [comment]
Hmm, that's unfortunate. It's not _wrong_, per se, just new; here's a usage example from [the man page on Ubuntu 20.10](http://manpages.ubuntu.com/manpages/groovy/man1/add-apt-repository.1.html):

```
       add-apt-repository deb http://myserver/path/to/repo stable main
```

Apparently your `apt-add-repository` tool will be getting some increased capabilities next time you upgrade your OS.

However, the man page does suggest that we should specify what format we're using (`-S` for sources line), and that leaving it out falls back on a deprecated autodetection mode.

**Comment by HebaruSan** [comment]
OK, I added quotes to the release note:

https://github.com/KSP-CKAN/CKAN/releases/tag/v1.30.0

Thanks for letting us know about this, Ubuntu does not make it easy to know how far back a particular command will work.

**Comment by Myricaulus** [comment]
I am sorry, still a newbe to linux, i actually have 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux. And my APT Version is: 2.0.5. Just so you know.

**Comment by HebaruSan** [comment]
That's fine, and it's good to know you're on Ubuntu 20.04 LTS, since that's a newer version that will be supported for a longer time span.

I wonder if I pasted this in from a wiki somewhere that also needs to be updated...

**Comment by HebaruSan** [comment]
> I wonder if I pasted this in from a wiki somewhere that also needs to be updated...

Found it, it was in my local `CKAN_releases.md` file that I update to compose new release notes. It now has both the `-u` and the quote marks.
