### ISSUE TITLE
ReStock tries to overwrite files registered to ReStock

### ISSUE THREAD

**Issue by Idiotplaysgames** [KSP-CKAN/CKAN#3377]
I don't know what's happening but I only tried to install restock and restock+ this just happened while doing so( I manually downloaded it last time but I want to use ckan for all my mods so I deleted and reinstalled everything) I just downloaded mods when this happened and it only happened to restock and restock+
![res](https://user-images.githubusercontent.com/84636014/119234001-bea48780-bb55-11eb-9021-f67272e77d1a.PNG)
my mods
![m](https://user-images.githubusercontent.com/84636014/119249854-42965800-bbc6-11eb-8abe-c91975ff6892.PNG)

**Comment by Idiotplaysgames** [comment]
Only happens to restock btw

**Comment by DasSkelett** [comment]
Can you fill out the bug report template please?
What did you try to achieve? What did you do before this happened? What mods do you have installed, especially: is ReStock already installed and you are trying to update it, or is ReStock not installed at all yet and you are trying to install it anew?
Did you install ReStock manually before?

**Comment by Idiotplaysgames** [comment]
updated with needed info

**Comment by HebaruSan** [comment]
I tried installing ReStock and it worked fine, and the needed info wasn't actually added, so further investigation of this is impossible. Closing.

@Idiotplaysgames, if you are able to answer the questions that @DasSkelett asked, please do so and we can re-open this for investigation.
