### ISSUE TITLE
Build failing when installing aur/ckan

### ISSUE THREAD

**Issue by lzacchi** [KSP-CKAN/CKAN#3378]
Background
----------
* Operating System: Arch Linux
* CKAN Version: 1.30.2-1 

Build failed when trying to install the aur package. It currently reports 7 errors, which I can post here if requested, but I'll show one example in order to keep this issue clean:

```
"/home/user/.cache/yay/ckan/src/CKAN-1.30.2/CKAN.sln" (Build target) (1) ->
"/home/user/.cache/yay/ckan/src/CKAN-1.30.2/Tests/Tests.csproj" (default target) (8) ->
  /usr/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.CurrentVersion.targets(331,5): error MSB4019: 
  The imported project "/usr/lib/mono/msbuild/15.0/bin/Roslyn/Microsoft.CSharp.Core.targets" was not found. 
  Confirm that the path in the <Import> declaration is correct, and that the file exists on disk. [/home/user/.cache/yay/ckan/src/CKAN-1.30.2/Tests/Tests.csproj]
```

I have tried fulfilling the dependencies either with `aur/msbuild-15-bin` or `community/mono-msbuild` both on the latest version, but the errors are the same.

**Steps to reproduce**
* Try to install aur/ckan. For example: `yay -S ckan`

**Comment by DasSkelett** [comment]
Sorry, we can't help with build issues on Arch. While the error message is slightly different than #3361, it still looks like a issue with the mono/msbuild installation, not our build system. Compilation works fine on other Linux distros, like Ubuntu and derivatives.

I suspect Arch distributes broken packages for mono and/or msbuild. Try asking their maintainers for help.

In the meantime, you can download the `ckan.exe` binary from the release assets, and run ckan with `mono ckan.exe`.

Closing this as there's nothing we can do to fix it to our knowledge.

**Comment by HebaruSan** [comment]
The error here is exactly the same as https://bugs.archlinux.org/task/63636, which reported that this happens for any and all C# projects on Arch (i.e., not CKAN's fault). However, in a fresh Arch install on a virtual machine, I found that this file did exist and the errors were different, so maybe try updating your system?

```sh
sudo pacman -Syu
```
