### ISSUE TITLE
Lunches the game without mods

### ISSUE THREAD

**Issue by Statsuss** [KSP-CKAN/CKAN#3386]
Background
----------
* Operating System:  Windows 10
* CKAN Version: v1.30.2
* KSP Version: 1.11.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Added mods before I istalled CKAN.

Problem
-------
**Describe the bug**
Lunches the game without mods

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
It would really help if you would describe the problem you're having, but from the clues available, it sounds like you're launching the game, and the mods you expect to be there aren't there. When I've seen this reported before, it was because the user launched a different copy of the game from the one where CKAN installed the mods. So...

- How are you launching the game?
- Can you show a screenshot of your CKAN, so we can see the path that it's using?

**Comment by Statsuss** [comment]
Well,That example that you said was exactly what’s happening.I’m launching the game from the ckan app...This is the screen shot: Sent from Mail for Windows 10 From: HebaruSanSent: May 27, 2021 4:45 PMTo: KSP-CKAN/CKANCc: Statsuss; AuthorSubject: Re: [KSP-CKAN/CKAN] [Bug] Briefly summarize your issue here (#3386) It would really help if you would describe the problem you're having, but from the clues available, it sounds like you're launching the game, and the mods you expect to be there aren't there. When I've seen this reported before, it was because the user launched a different copy of the game from the one where CKAN installed the mods. So...How are you launching the game?Can you show a screenshot of your CKAN, so we can see the path that it's using?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by HebaruSan** [comment]
Hi, no screenshot came through. Are you replying via email? If so, try clicking on the link to the issue on GitHub, then paste the screenshot there.

**Comment by Statsuss** [comment]
Ok. Sent from Mail for Windows 10 From: HebaruSanSent: May 27, 2021 5:07 PMTo: KSP-CKAN/CKANCc: Statsuss; AuthorSubject: Re: [KSP-CKAN/CKAN] Lunches the game without mods (#3386) Hi, no screenshot came through. Are you replying via email? If so, try clicking on the link to the issue on GitHub, then paste the screenshot there.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by Statsuss** [comment]
![image](https://user-images.githubusercontent.com/84943341/119911481-36840080-bf0e-11eb-9362-b813960e4d80.png)

**Comment by HebaruSan** [comment]
Thanks, we can see it now!
OK, so you were saying that you click Launch Game, and some mods seem to be missing? Which ones are missing?

**Comment by Statsuss** [comment]
I willl be back in 1h

**Comment by HebaruSan** [comment]
That's fine, reply when you can, there's no hurry.

**Comment by Statsuss** [comment]
K
I'm back

**Comment by Statsuss** [comment]
Also, all the mods are missing

**Comment by Statsuss** [comment]
Also, also, thank you for waiting.

**Comment by HebaruSan** [comment]
OK. If you click the File menu and select "Open game directory", then open the GameData folder, do you see the files and folders for the mods?

**Comment by HebaruSan** [comment]
A few times when someone said a mod was missing, the problem was that they did not know what to look for. Which specific mods are you looking for and how do you know they are missing?

**Comment by Statsuss** [comment]
No I do not see the mods in the gamedata folder.
However, Before I got ckan I gust used that for my mods (I just dragged and dropped the folders)

**Comment by HebaruSan** [comment]
How did you end up with all those mods checked in CKAN? Did you actually use CKAN to install those mods, or did you perhaps copy some files that may have confused CKAN? Did you delete the files that CKAN installed in GameData?

**Comment by Statsuss** [comment]
No,
I got the mods from just searching them up on google ex: https://github.com/post-kerbin-mining-corporation/NearFuturePropulsion/releases
I did delete the mod folders before I got ckan

**Comment by HebaruSan** [comment]
So you have never used CKAN to install any mods? It started like that the first time you ran it, with all those mods checked?

**Comment by Statsuss** [comment]
No, I got those mods on ckan without any mods before the ones I just got

**Comment by Statsuss** [comment]
here is the gamedata folder right now...
![image](https://user-images.githubusercontent.com/84943341/119918280-fe37ee80-bf1c-11eb-8d90-30f635cc3cf9.png)

**Comment by HebaruSan** [comment]
OK, your registry has gotten confused somehow. Try unchecking all the boxes and applying changes; CKAN should try to "uninstall" all those mods, but since the files aren't there it will just update its tracking so it no longer thinks they are installed. Then check the boxes of the ones you want to install and apply changes, CKAN will then install them.

**Comment by Statsuss** [comment]
Ok Thank You!!

**Comment by HebaruSan** [comment]
You're welcome, and good luck! :racehorse:
