### ISSUE TITLE
Well thank you and when will I be able to properly install SKAN?

### ISSUE THREAD

**Issue by NetherCraft1B** [KSP-CKAN/CKAN#3392]
There was a big outage of many many web sites due to a problem at a CDN. Guessing that's what got ya.

https://www.cnn.com/2021/06/08/tech/internet-outage-fastly/

_Originally posted by @HebaruSan in https://github.com/KSP-CKAN/CKAN/issues/3391#issuecomment-856721515_

**Comment by HebaruSan** [comment]
Please don't open multiple issues for the same problem.
