### ISSUE TITLE
Can't remove mods because files are locked

### ISSUE THREAD

**Issue by dfisher0306** [KSP-CKAN/CKAN#3393]
Background
----------
* Operating System: Windows
* CKAN Version: v1.30.4
* KSP Version: 1.11.2.3077

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yes

Problem: it wont let me delete any mod
-------
**Describe the bug**
it wont let me delete anything and when i tried to do it manually it said the files were open or being used even though nothing was open

**Steps to reproduce**
* Go to... filter, installed
* Click on... any mod, apply
* See error

**Expected behavior**
to delete said mods

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Is KSP still running? Check the Task Manager, and kill the process if you find it.
If you can't find a KSP process in Task Manager, reboot your PC. Afterwards removing mods should work again.

**Comment by dfisher0306** [comment]
i did that, ksp wasnt even running and i made sure it wasnt ill try rebooting tho

**Comment by DasSkelett** [comment]
So, I assume you rebooted your PC at least once by now, did it work?

**Comment by dfisher0306** [comment]
yes it worked
