### ISSUE TITLE
[Feature] Allow ordering of mod labels

### ISSUE THREAD

**Issue by d-faure** [KSP-CKAN/CKAN#3395]
Using labels to classify the mods I need/want in my games, I found that there's a _de facto_ label ordering which apply when several one are selected for one mod. I.e. a label is always created at the end of the label list and when a mod is multi-labeled, the displayed color is the one of the first selected in label list.

Could we have a easier way to reorder this label list than manually editing the related json configuration file?

Nota: I'm only using labels on a global scope, but some care should be taken to have consistent behaviors with instances related ones.

**Comment by HebaruSan** [comment]
(Sorry for the edit, but unnecessary editorializing on whether or not a change is easy is one of those things that just annoys me. It'll be easier to process this request without that.)

**Comment by HebaruSan** [comment]
Documenting the current logic:

When loading the label editing form, we sort by group name, then by label name name, although this ordering isn't saved to disk:

https://github.com/KSP-CKAN/CKAN/blob/8c6760a597f09b693a3b550dbc2fa61e817f9fef/GUI/Dialogs/EditLabelsDialog.cs#L35-L37
https://github.com/KSP-CKAN/CKAN/blob/8c6760a597f09b693a3b550dbc2fa61e817f9fef/GUI/Dialogs/EditLabelsDialog.cs#L45

Newly created labels are added to the end of the list:

https://github.com/KSP-CKAN/CKAN/blob/8c6760a597f09b693a3b550dbc2fa61e817f9fef/GUI/Dialogs/EditLabelsDialog.cs#L207-L209

As far as I can tell, there is currently no re-ordering of labels anywhere, which is probably good for this enhancment request as it means there will be minimal need to worry about backwards compatibility.

**Comment by HebaruSan** [comment]
The right click menu just uses whatever ordering is in the file:

https://github.com/KSP-CKAN/CKAN/blob/8c6760a597f09b693a3b550dbc2fa61e817f9fef/GUI/Controls/ManageMods.cs#L220-L229

https://github.com/KSP-CKAN/CKAN/blob/8c6760a597f09b693a3b550dbc2fa61e817f9fef/GUI/Labels/ModuleLabelList.cs#L16-L19

Again this is probably good, since we can re-order the labels in the object and the menu will reflect it.

**Comment by HebaruSan** [comment]
The most familiar UI idiom for this is probably a pair of up/down buttons next to the list.

![screenshot1](https://social.technet.microsoft.com/wiki/cfs-filesystemfile.ashx/__key/communityserver-wikis-components-files/00-00-00-00-05/6237.Figure10a.png)

![screenshot2](https://social.technet.microsoft.com/wiki/cfs-filesystemfile.ashx/__key/communityserver-wikis-components-files/00-00-00-00-05/6327.Figure2a.png)

Probably would make sense to show/hide those when you're editing a label:

![image](https://user-images.githubusercontent.com/1559108/126081013-9a079445-4e0f-4c4d-a175-e8fa3f2a5b9b.png)

**Comment by HebaruSan** [comment]
`ModuleLabelList.Labels` is an array, so we should be able to assign a newly sorted array to it and save it.
