### ISSUE TITLE
[Feature] Negative statements in search

### ISSUE THREAD

**Issue by SunSerega** [KSP-CKAN/CKAN#3397]
Problem
-------
As you noted [here](https://github.com/KSP-CKAN/CKAN/issues/3071#issuecomment-791656558) - any boolean expression can in fact be written in [DNF](https://en.wikipedia.org/wiki/Disjunctive_normal_form) (or [CNF](https://en.wikipedia.org/wiki/Conjunctive_normal_form) to that matter, but no one likes it).

Except afaik, rn you only added local `and`'s and global `or`'s, and to complete DNF you also need `not`'s.

Well, as for the more practical side of this issue:
1. There are a few kinds of mods I would not want in my mod pack, like flag mods.
2. I've installed a few planet packs, a tech pack, etc. It's safe to assume, I wouldn't need any more of these in the current mod pack.
So it would be great to exclude them, to more comfortably check out the rest of misc mods.

Suggestions
-----------
Many advanced search engines (at least those with `:` syntax, like google and Github issues) use `-` to negate the term.
So for instance: `is:compatible -flags -dep:Kopernicus`

That said, it's definitely not a universal syntax, so would be great to consider more possibilities.
Some search engines use `!`. And IMO `~` would be far more readable with the font you've chosen.

On the other hand - you seem to be leaning towards using more words and fewer symbols.
And I can see `not:compatible` being more readable to non-programmers than `~is:compatible`.
(not 100% sure tho, been a programmer for too long)

**Comment by HebaruSan** [comment]
`not:compatible` is already supported—try it! :+1: 

![image](https://user-images.githubusercontent.com/1559108/122780685-b0d94380-d274-11eb-8f42-f30f24a47b26.png)

**Comment by SunSerega** [comment]
> `not:compatible` is already supported

Yeah, that's what I said - I used it as an example where you already use human-readable words instead of symbols.

**Comment by HebaruSan** [comment]
This is a logical extension of the search system and makes sense to investigate. The tricky thing I see is, how would this translate to and from the per-field search boxes? Does `-dep:Kopernicus` in the main field turn into `-Kopernicus` in the Depends on field? That seems a little weird, not sure why.

**Comment by SunSerega** [comment]
How about this: Words in those per-field boxes could snap into rounded rectangles when validated.
Then clicking it would toggle inclusion/exclusion, indicated by the background of that rounded rectangle.

Though if you decide to implement that - please leave the main search box without such snapping.
IMO it's like an address bar in browsers: an easily copyable and shareable path.

Would also be a good reason to implement in-flight suggestions, especially wanted for tags.
But that's offtop and harder/more_long-term to implement well. Should I open a separate issue for them?

**Comment by HebaruSan** [comment]
> Words in those per-field boxes could snap into rounded rectangles when validated.
> Then clicking it would toggle inclusion/exclusion, indicated by the background of that rounded rectangle.

Hmm, I see some problems with that. First, background color is not a clear visual cue, we would have to add other UI elements somewhere explaining what the colors meant and hope that users noticed it when they needed that info. Second, toggling inclusion/exclusion on click assumes that I never make typos, users would still need to be able to click the text to place the cursor for editing when they fat-finger `Kopnericus`. Third, this is a `System.Windows.Forms.TextBox`, good luck getting it to do web-style rounded rectangles.

A plain text solution is probably the way to go.

**Comment by HebaruSan** [comment]
> 1. There are a few kinds of mods I would not want in my mod pack, like flag mods.

For what it's worth, this specific example doesn't require changing the search. You can already hide mods that have the `flags` tag by right clicking the column headers and de-selecting the "flags" option:

![image](https://user-images.githubusercontent.com/1559108/125145493-09b73180-e0e7-11eb-88d5-667d3f6625f2.png)
