### ISSUE TITLE
[Feature] Delay search while typing

### ISSUE THREAD

**Issue by kfsone** [KSP-CKAN/CKAN#3402]
Problem
-------
GUI search on Windows can be painful because search is triggered OnChange:
- Open CKan,
- Clear the search bar,
- Type 'is:'
- -> CKAN begins searching as soon as the input box receives the 'i', which retrieves a huge result set and takes a while to process, significantly delaying the processing of the 's' and then again the ':'.

Suggestions
-----------
Don't restrict the filter timer to Mono platforms:

https://github.com/KSP-CKAN/CKAN/blob/master/GUI/Controls/EditModSearch.cs#L266-L277

**Comment by HebaruSan** [comment]
Hi @kfsone, since you've looked into the code for this already, would you be interested in submitting a pull request with the needed code change? We would be happy to work with you to get through the process.

**Comment by kfsone** [comment]
For the record: I'd just gotten done installing VS2022 and aside from changing the default target from .net core to .net dropping into the project was smooth as glass.
