### ISSUE TITLE
CKAN doesn't have permissions to access KSP directory

### ISSUE THREAD

**Issue by Spoonifer** [KSP-CKAN/CKAN#3406]
Background
----------
* Operating System: Windows10
* CKAN Version: 1.30.4
* KSP Version: 1.12

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** NO

Problem
-------
**Describe the bug**
Creates this error report:
```
 * Environmental Visual Enhancements Redux 3:1.11.3.1 (spacedock.info, 948.1 KiB)
 * Environmental Visual Enhancements - Stock Planet Config files 2:EVE-1.2.2-1 (cached)
Downloading "https://spacedock.info/mod/2631/Environmental%20Visual%20Enhancements%20Redux/download/1.11.3.1"
"Access to the path 'C:\Users\info\Documents\KSP1.12\KSP_win64\GameData\EnvironmentalVisualEnhancements\button.png' is denied.
Error during installation!"
```

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Comment by DasSkelett** [comment]
CKAN doesn't have permissions to access your KSP directory. It this your first time running CKAN?
Did you move the game directory between users, or did you run CKAN as a different user or admin in the past?

**Comment by Spoonifer** [comment]
Hi DasSkelett

Exactly as you said. I have downloaded the new KSP1.2, then downloaded CKAN and linked it to this version. There are two other versions of KSP & CKAN on my drive but in completely different directories. Maybe I will try installing this on the Default User rather than my personal one.

Many thanks

**Comment by DasSkelett** [comment]
> Maybe I will try installing this on the Default User rather than my personal one.

Did this fix it?

**Comment by DasSkelett** [comment]
Closing as probably fixed
