### ISSUE TITLE
CKAN can't reach raw.githubusercontent.com

### ISSUE THREAD

**Issue by timmyislol** [KSP-CKAN/CKAN#3407]
After an presumably botched auto update of ckan it won't connect to the servers anymore
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.0

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** no I haven't

Problem
-------
I clicked yes on a pop up window on ckan that I assume asked me to update ckan, something happened and now I see:
```
"788 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json" on startup and: "Failed to connect to repository. Exception: Unable to connect to the remote server
```
in an error pop up message. Ckan can't connect to the servers needed to update mods and maybe even itself.

**CKAN error code (if applicable):**
```
Failed to connect to repository. Exception: Unable to connect to the remote server
```

**Comment by DasSkelett** [comment]
Yes, CKAN can't reach GitHub to download the latest metadata.
This is usually caused by broken firewalls or anti-virus software, or custom edits to the `C:\Windows\System32\drivers\etc\hosts` file.
Or maybe by whatever this pop-up did, but we need more details than "_a_ popup", that you _assumed_ to do something, with _something_ happening afterwards, to be able to help you.

**Comment by timmyislol** [comment]
> Yes, CKAN can't reach GitHub to download the latest metadata.
> This is usually caused by broken firewalls or anti-virus software, or custom edits to the `C:\Windows\System32\drivers\etc\hosts` file.
> Or maybe by whatever this pop-up did, but we need more details than "_a_ popup", that you _assumed_ to do something, with _something_ happening afterwards, to be able to help you.

No you don't, that was it, my firewall, thanks
