### ISSUE TITLE
[Question] Where is metadata (.version file) pulled from?

### ISSUE THREAD

**Issue by jwvanderbeck** [KSP-CKAN/CKAN#3409]
I have set up some new CI for some of the RO/RP1 repos which generates a .version file dynamically and includes it into the zip that is attached to the release.  But there is some concern that this .version file is not where CKAN gets it's metadata from, that it instead takes the data from the .version file in the repo, which CI is not updating.

Can I get some clarification on this please? 

Thanks!

**Comment by HebaruSan** [comment]
Just like with KSP-AVC, the version file inside the ZIP is checked first. If it contains a `URL` property, then that remote version file is also checked, _but only if its `VERSION` property matches the one in the ZIP_ (i.e., it has to be talking about the same release). Here's where that logic lives:

https://github.com/KSP-CKAN/CKAN/blob/a8fb9028a2d1de811ad8de46cd44f0f914e7362f/Netkan/Transformers/AvcTransformer.cs#L65-L107

**Comment by jwvanderbeck** [comment]
Ah perfect thanks. So is that `URL` property optional?

**Comment by HebaruSan** [comment]
Yes, if it is missing or does not point to a valid version file, then only the one in the ZIP is used.
