### ISSUE TITLE
CKAN not working at start

### ISSUE THREAD

**Issue by ThatUnreal** [KSP-CKAN/CKAN#3410]
**Background**
----------
* Operating System: Windows
* CKAN Version: latest version
* KSP Version: 1.12, steam

Have you made any manual changes to your GameData folder (i.e., not via CKAN)?
Not yet

Problem
-------
I installed CKAN from the Github page and opened it up, the first time it opened it showed me the update page (no screenshot for that), but than I noticed that something was wrong and since I couldn't understand why I deleted it and reinstalled it, but than it completely stop working, giving me two error pages, one with code and one with the list of errors

**Expected behavior**
CKAN opening

**Screenshots (if applicable)**
![ckan error 1](https://user-images.githubusercontent.com/87145454/124969067-8fbf7380-e026-11eb-835a-cce6b0b4d601.png)
![ckan error 2](https://user-images.githubusercontent.com/87145454/124969087-95b55480-e026-11eb-9b67-cfa44db080a5.png)
![ckan error 3](https://user-images.githubusercontent.com/87145454/124969112-9bab3580-e026-11eb-83e2-90887e972949.png)

**Comment by DasSkelett** [comment]
Looks like you grabbed an older release when reinstalling, this error happens after downgrading to a pre-v1.30.0 release.

Make sure to remove each and every ckan.exe you have on your PC, then download the [latest](https://github.com/KSP-CKAN/CKAN/releases/latest) release again.

**Comment by DasSkelett** [comment]
Btw. this is why putting `* CKAN Version: latest version` into the issue body is pretty useless. We don't know what you think the latest version is. Instead, check what it saysin the window title bar, and put this exact version into the issue. This is guaratneed to be the one you are running.

**Comment by ThatUnreal** [comment]
> Btw. this is why putting `* CKAN Version: latest version` into the issue body is pretty useless. We don't know what you think the latest version is. Instead, check what it saysin the window title bar, and put this exact version into the issue. This is guaratneed to be the one you are running.

Ok sorry about that

**Comment by HebaruSan** [comment]
Looks like the cause of this was figured out. @ThatUnreal, if you still have this problem on the actual latest version of CKAN, let us know and we can re-open for investigation.

**Comment by HebaruSan** [comment]
Duplicate of #3331
