### ISSUE TITLE
Include mod author in search results

### ISSUE THREAD

**Issue by liamdennehy** [KSP-CKAN/CKAN#3415]
Problem
-------
I'd like to be able to see mods created/maintained by a particular author, especially when I know they will work well together or just to see what else they've done. Sorting by author isn't always great because:
- Not all mods have a single author, so the sorting doesn't always show me all an author's mods (e.g. I'm looking for author x, but the author column says authors are "y,x")
- I can't apply another sort, meaning I can't ask "Show me the most popular (downloaded) mods from author <x>".

Just another way to give mod authors the visibility they deserve.

Suggestions
-----------
When typing in the search bar, include the author in the filter set. Perhaps a toggle to include author (and description for that matter) if the result is too different from the current behaviour.

**Comment by DasSkelett** [comment]
You can already search by author, either by prefixing am `@` in the main search box, or by entering the name into the "Author" box in the expanded view (doing one will also fill out the other):
![image](https://user-images.githubusercontent.com/28812678/126065850-cd1ae54d-9d72-4106-b2d2-f46fc97fcd3b.png)

> I can't apply another sort, meaning I can't ask "Show me the most popular (downloaded) mods from author ".

You can add multiple secondary sort columns using shit-click. Select the main sorting column using the normal left click, then you can add an arbitrary list of secondary sort columns using shit + left click.

**Comment by HebaruSan** [comment]
@liamdennehy, it seems that this is a request for features that already exist, see @DasSkelett's post.
If there's more to it, please let us know and we can re-open this.
