### ISSUE TITLE
I need help with something

### ISSUE THREAD

**Issue by Unsoar** [KSP-CKAN/CKAN#3418]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.30.4
* KSP Version: 1.10.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I have deleted all mods

Problem
-------
**Describe the bug**
I have deleted all of my mods through the KSP GameData folder, then I downgraded the version, then I went to CKAN to try and install the other mods, I realized that CKAN still said I had the previous mods that I deleted from the GameData folder manually without CKAN, I tried to uncheck them and uninstall them but the apply changes was not appearing at all

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
> the apply changes was not appearing at all

Can you share a screenshot of your CKAN? There might be a message in the lower left of the window explaining what is wrong.

**Comment by Unsoar** [comment]
Very much sorry for this, it fixed itself, I think it was just buggy but I'm all good now
