### ISSUE TITLE
Suggestion: Add a way to clear all mods 

### ISSUE THREAD

**Issue by TechPenguineer** [KSP-CKAN/CKAN#3420]
You should make a button that resets all the game files to the defaults

**Comment by HebaruSan** [comment]
If you uncheck the checkbox over the Installed column and then click Apply changes, it will uninstall all of your mods. Does that do what you need?

![image](https://user-images.githubusercontent.com/1559108/126873105-e40dd940-799e-4382-b1f1-19e3e952bc6d.png)

**Comment by TechPenguineer** [comment]
Yea it does! Thank you! I wasn't aware you could do that

**Comment by HebaruSan** [comment]
Excellent, glad it works for you1
