### ISSUE TITLE
[Bug] Mods missing from mod list in Console UI on Mac

### ISSUE THREAD

**Issue by technic-void** [KSP-CKAN/CKAN#3427]
Background
----------
* Operating System: macOS Big Sur
* CKAN Version: 1.30.4
* KSP Version: 1.12.1.3142

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I have installed Astronomer's visual pack, Toolbar controller, clickthrough blocker, Parallax, and several other mods due to them not being on the mod list of CKAN.

Problem
-------
Several mods are missing from the mod list of CKAN, despite apparently being available on windows and having notes from the developers saying that their mods are in the CKAN database. This is specifically a problem for mods that are intended to be in the database but do not show up, not mods that are not in the database at all. 

**Steps to reproduce**
open CKAN on a Mac. Search for astronomer's visual pack or several other well-known mods that have announced that they are on the database.

**Expected behavior**
Mods that are on the database should show up. 

**Screenshots (if applicable)**

<img width="564" alt="Screen Shot 2021-08-02 at 6 04 04 PM" src="https://user-images.githubusercontent.com/84088137/127929669-a67fa4fe-3ad6-4481-863a-ea68e64ca078.png">

not sure if that screenshot worked properly

**Comment by technic-void** [comment]
if the devs see this, even though I'm sure they would know much more about this than me, I'd say that there was a change in file formats and the old UI is not built to handle it and avoids displaying the mods to not have bugs. Best-case scenario, just copy-paste what you did for the GUI into the console UI

**Comment by HebaruSan** [comment]
Incompatible mods and mods that depend on incompatible mods are hidden. You can control which mods are incompatible via:

F10 → Select game instance... → Pick your install → Press 'e' to edit → Tab a few times to get to the compatible version list

**Comment by technic-void** [comment]
Thank you for a solution, but what do I do if the compatible versions list is empty? It seems that all the mods I have installed are compatible with my version, but I guess they are not marked as such in CKAN

**Comment by HebaruSan** [comment]
> what do I do

Press 'a' to add a new version
