### ISSUE TITLE
[Bug] Ampersands not escaped in mod info, doubled in grid on Windows

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN#3428]
Background
----------
Windows 10
CKAN 10.30.4 

Problem
-------
The text "&&" displays in the inline description, but not in the metadata panel to the right.

Specifically, for the mod Animate Generic Effects Module by linuxgurugamer the inline description shows "Added effects && part symmetry to ModuleAnimateGeneric", while the description in the metadata panel shows "Added effects _part symmetry to ModuleAnimateGeneric".

Expected behavior
-------
Assuming both strings come from the same source, the description in the metadata panel should match the inline description. 

**Screenshots (if applicable)**

![CKAN metadata error](https://user-images.githubusercontent.com/1124476/128133562-8edd9046-8287-4cb5-898b-a48feca9d5e4.png)

**Comment by HebaruSan** [comment]
It's really just one `&`:

https://github.com/KSP-CKAN/CKAN-meta/blob/3f04f33a4af4fa10be084ebc03001b2bbeb191af/ModuleAnimateGenericEffects/ModuleAnimateGenericEffects-0.1.3.ckan#L5

```json
    "abstract": "Added effects & part symmetry to ModuleAnimateGeneric",
```

The grid doubles it as of #3149, which was supposed to make it display normally:

https://github.com/KSP-CKAN/CKAN/blob/a8331592dda3bbfed3e42cdeb5e39f6858d23c5c/GUI/Model/ModList.cs#L352

**Comment by HebaruSan** [comment]
The mod info abstract label is populated here:

https://github.com/KSP-CKAN/CKAN/blob/a8331592dda3bbfed3e42cdeb5e39f6858d23c5c/GUI/Controls/ModInfo.cs#L127

**Comment by HebaruSan** [comment]
In Mono, one spot is wrong and one is right:

![image](https://user-images.githubusercontent.com/1559108/128211981-80a48b79-d6cc-4094-b59c-2c87e725ac64.png)

So it might not be possible to make the grid work correctly for everyone, but the mod info label is probably fixable.

**Comment by HebaruSan** [comment]
Recommendation screen looks OK:

![image](https://user-images.githubusercontent.com/1559108/128216327-00520c49-0ce2-4eb7-ad46-e30334267815.png)

**Comment by tjanke42** [comment]
Sure thing.  It looks like this:  

![CKAN metadata error 2](https://user-images.githubusercontent.com/1124476/128653270-f74b1c48-1a86-4235-a93d-02a41253cb82.png)

CKAN 1.30.4
