### ISSUE TITLE
i can't choose new game instance

### ISSUE THREAD

**Issue by BobaczeQ** [KSP-CKAN/CKAN#3431]
when i click to add instance for ksp instead of select i can only open folders.

**Comment by HebaruSan** [comment]
You need to select the buildID.txt or buildID64.txt files.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#adding-game-folders

**Comment by BobaczeQ** [comment]
i don't have that file.

**Comment by HebaruSan** [comment]
It's present in every legal copy of the game. Previously when people have said that, they obtained it illegally.

**Comment by BobaczeQ** [comment]
idk if it's legal but i bought the game from eneba

**Comment by HebaruSan** [comment]
Here are some places you can obtain a legitimate copy of KSP:

- https://www.kerbalspaceprogram.com/store/
- https://store.steampowered.com/app/220200/Kerbal_Space_Program/
- https://www.gog.com/game/kerbal_space_program

**Comment by BobaczeQ** [comment]
i clicked to verify my files on steam and now i have this file, thanks for help anyways.
