### ISSUE TITLE
[Bug] Cannot boot game from CKAN

### ISSUE THREAD

**Issue by CursedAuroran** [KSP-CKAN/CKAN#3433]
Background
----------
* Operating System: Pop_OS! 21.04
* CKAN Version: 1.30.4
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I have not made any manual changes to my GameData folder.

Problem
-------
**Describe the bug**
Because I have a 2 GPU system I am forced to use a bootup parameter for games to have them run on the dGPU, entering this parameter in the same way as one would in steam results in the parameter being ignored, and putting the parameter in the spot that would work from the terminal results in the game not booting at all through CKAN, with CKAN stating that "Couldn't start game. Cannot find the specified file". The entry into the command line thing is "__NV_PRIME_RENDER_OFFLOAD=1 ./KSP.x86_64 -single-instance". Without the parameter the game starts but runs extremely poorly.

**Steps to reproduce**
In my case I am running an intel nvidia system, something this parameter was specifically made for (it acts like a terminal command). Go to settings -> Game command-line, enter the parameter "__NV_PRIME_RENDER_OFFLOAD=1" in front of "./KSP.x86_64".
Then, click on OK and then Launch Game.
Watch the error.

**Expected behavior**
Assuming it works just like a terminal command line, the Game command-line entry should just load the game and tell the system to offload the GPU load to the nvidia GPU.

**Screenshots (if applicable)**
![Screenshot from 2021-08-10 19-19-42](https://user-images.githubusercontent.com/84097469/128906174-7a73d1d6-52e7-431e-a188-66d66fb6d1d1.png)
![Screenshot from 2021-08-10 19-25-29](https://user-images.githubusercontent.com/84097469/128906246-eb785a67-6f28-4f76-81a6-8b0ab9a11701.png)

**CKAN error code (if applicable):**

```
Couldn't start game.

Cannot find the specified file
```

**Comment by DasSkelett** [comment]
We aren't executing the command-line in a shell, but split it at whitespace and directly start the binary specified with the first argument.
So when you try to put an environment variable before `./KSP.x86_64`, CKAN tries to start a binary with the name `__NV_PRIME_RENDER_OFFLOAD=1`, which doesn't exist.

You can try launching a shell manually, i.e. `/bin/bash -c "__NV_PRIME_RENDER_OFFLOAD=1 ./KSP.x86_64 -single-instance"`.

**Comment by HebaruSan** [comment]
You might also consider setting that environment variable system-wide rather than trying to cram it into every game's command line:

https://help.ubuntu.com/community/EnvironmentVariables

> ### System-wide environment variables
> A suitable file for environment variable settings that affect the system as a whole (rather than just a particular user) is /etc/environment. An alternative is to create a file for the purpose in the /etc/profile.d directory.
> 
> #### /etc/environment
> This file is specifically meant for system-wide environment variable settings. It is not a script file, but rather consists of assignment expressions, one per line.
> 
> ```
> FOO=bar
> ```
> Note: Variable expansion does not work in /etc/environment.

Are there any disadvantages to having it set?

**Comment by DasSkelett** [comment]
> Are there any disadvantages to having it set?

Without having experience on the topic of two graphics cards, I think that this would cause every application to be rendered b< the dedicated GPU, which causes it to be always active and consume energy, even if you are only running the calculator, which the iGPU could do just fine with much less power consumption.

**Comment by HebaruSan** [comment]
The NVIDIA documentation kind of makes it sound like the variable is only checked by Vulkan, not some part of the OS, so calculator might be safe:

https://download.nvidia.com/XFree86/Linux-x86_64/435.17/README/primerenderoffload.html

> To configure a graphics application to be offloaded to the NVIDIA GPU screen, set the environment variable __NV_PRIME_RENDER_OFFLOAD to 1. If the graphics application uses Vulkan, that should be all that is needed. If the graphics application uses GLX, then also set the environment variable __GLX_VENDOR_LIBRARY_NAME to nvidia, so that GLVND loads the NVIDIA GLX driver. NVIDIA's EGL implementation does not yet support PRIME render offload.

**Comment by CursedAuroran** [comment]
> We aren't executing the command-line in a shell, but split it at whitespace and directly start the binary specified with the first argument.
> So when you try to put an environment variable before `./KSP.x86_64`, CKAN tries to start a binary with the name `__NV_PRIME_RENDER_OFFLOAD=1`, which doesn't exist.
> 
> You can try launching a shell manually, i.e. `/bin/bash -c "__NV_PRIME_RENDER_OFFLOAD=1 ./KSP.x86_64 -single-instance"`.

hmm no that didn't work unfortunately, but I think I may have found a workaround through steam, but thanks for the suggestion, will try and see if I can get it to work
