### ISSUE TITLE
[Bug] Error during installation.

### ISSUE THREAD

**Issue by PodpischikOvera** [KSP-CKAN/CKAN#3442]
Background
----------
Operating System: Windows 10
CKAN Version: 1.30.4
KSP Version: 1.11.1

Have you made any manual changes to your GameData folder (i.e., not via CKAN)? - No.

Problem
-------
Whichever mod I install, I get an "error during installation!"

**Steps to reproduce**

Select mod
Click on "Apply changes"
See error

**Expected behavior**
Successful installation

Screenshots (if applicable): 
![](https://user-images.githubusercontent.com/72693739/131484402-29be4215-0718-4c60-b47d-09bc2bcfd8b9.png)

**Comment by DasSkelett** [comment]
Can you please paste the full output log here (not just the last 3 lines)?

**Comment by PodpischikOvera** [comment]
https://user-images.githubusercontent.com/72693739/131496293-efebe8d4-f53b-4952-95f7-45ddf309ad9a.png

**Comment by DasSkelett** [comment]
Did you try restarting CKAN?

Does this really happen for _any_ mod you try to install? Even if you try, say, Astrogator?
Do you have the RealismOverhault / RP-1 mods installed? If so, how did you installed them, using the "Realistic Progression One (RP-1) Express Install" pseudo mod?

When did this start to happen? What did you do before? Did you touch any files in the KSP directory, maybe in the CKAN folder?

Can you show a screenshot of the list of installed mods in CKAN?

**Comment by PodpischikOvera** [comment]
1) I even reinstalled the scan

2) This happens with any mods
3) At the moment, neither the first nor the second has been installed, but RP-1 was about one and a half months ago, and RO was about a month ago.

4) It started today. Before that, I did not do anything unusual, I just installed mods and suddenly it appeared. In the latter, I manually changed the ksp folder for a long time, and did not touch the ckan folder at all.

5) https://user-images.githubusercontent.com/72693739/131512443-30accce0-a536-4d94-a6ee-4cadd040cd57.png - However, as soon as the problem is solved, I will download many more)


(sorry for mistakes, strange spelling or wording, I use google translate)

**Comment by DasSkelett** [comment]
Hm, hard to say why this happened. Maybe when the RO/RP-1 relationships got restructured for the new Express option.
Try installing the dependencies that CKAN says are missing, i.e. B9PartSwitch, DeployableEngines,  DynamicBatteryStorage, CryoTanks, StationParzsExpansionRedux, NearFutureProps, RealFuels.
Alternatively, uninstall all mods and reinstall (following the [official installation guide](https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1)  for RO/RP-1)
