### ISSUE TITLE
[Bug] Application Not Showing On On MacOS

### ISSUE THREAD

**Issue by The0n1y5pace4ce** [KSP-CKAN/CKAN#3447]
Background
----------
* Operating System: MacOS
* CKAN Version: Hubble
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When Opening Application, it shows up briefly before shutting down and not showing anything else

**Steps to reproduce**
* Go to Kerbal Space Program Folder
* Click on Ckan Application File
* See error

**Expected behavior**
Ckan GUI Not Showing Up At All

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```
I'm Sorry I Don't Know What That Means

**Comment by HebaruSan** [comment]
Do you have the Terminal installed?

**Comment by The0n1y5pace4ce** [comment]
Yes i just found it and attempted to use it, And sometimes it says that Lock File With with process id Found at...
I Bypassed it to get to the application and try to install RSS, but it did not work and still took up storage space

**Comment by The0n1y5pace4ce** [comment]
Ok, i just got it working
