### ISSUE TITLE
[Bug] New to Ckan accidently hit no to handler access and have no idea how to fix it

### ISSUE THREAD

**Issue by FenianKnight** [KSP-CKAN/CKAN#3449]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Don't worry, the URL handler feature isn't used anyway (and doesn't work currently either). CKAN will work just fine without it.
