### ISSUE TITLE
[Bug] registry.locked not deleted at exit

### ISSUE THREAD

**Issue by Shizzak** [KSP-CKAN/CKAN#3452]
Background
----------
* Operating System: Win10 64bit
* CKAN Version: 1.30.4
* KSP Version: 1.11.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes

Problem
-------
**When CKAN is opened for the first time a "registry.locked" file is created preventing me from reopening ckan unless I delete that file**

**Steps to reproduce**
* Open Ckan
* Ckan immediately creates a "registry.locked" file
* Any attempt to reopen ckan again gives me the error "CKAN is already running for this instance!" 

**Expected behavior**
Should be able to open ckan with no error

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
It's supposed to do that. Are you saying it isn't being deleted when CKAN exits?

**Comment by Shizzak** [comment]
No it does not. I physically watch it as i exit ckan

**Comment by HebaruSan** [comment]
OK, how are you exiting CKAN? Since this is only happening for you, we'll need more information to figure out what's wrong.

**Comment by Shizzak** [comment]
oddly enough its working now. Working in the IT field this is a common meme were software works when its being investigated,

**Comment by Shizzak** [comment]
this is weird. Ive been having this issue for a year now. I just uninstalled tantares and it seems to be working fine *for now*

**Comment by HebaruSan** [comment]
Glad you got it working. If it happens again and you're able to give steps to reproduce, please do and we can re-open this.
