### ISSUE TITLE
[Bug] Could not find file during install, transaction failed to roll back

### ISSUE THREAD

**Issue by OmegaX123** [KSP-CKAN/CKAN#3455]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4 "Hubble"
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Install fails with no context/information

**Steps to reproduce**
* Select mods to install
* Click on "Apply changes"
* Mods start to install, many of them complete successfully
* After a while "Install failed" pops up, occasionally accompanied by an unhandled exception crash stating that CKAN doesn't have access to one file or another

**Expected behavior**
Mods should properly install, or at the very least some info about why it failed (in cases where it only fails but doesn't crash) should be displayed.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/26946935/135222199-470ee9d0-ed77-402b-8765-bea80953be1a.png)
(I managed to catch it while it was both crashing and failing - the fail state this time did give info, but it conflicts with the info given in the crash, the fail state says that it can't find the file at all, the crash report says that it can find the file but can't access it because another program is using it - which is not the case)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by OmegaX123** [comment]
Correction: I just noticed it seems to be talking about two different files, as opposed to one file that both can't be found and is found but can't be accessed, so that makes a little more sense, though I'm pretty sure the mod that it's trying to install there is the mod that adds those craft files.

**Comment by HebaruSan** [comment]
Hmm, something is blocking, removing, and/or locking files that CKAN is trying to work with. Maybe check your antivirus software's logs to see whether it's messing with CKAN's installation process, or turn your antivirus off temporarily to find out if that helps.

**Comment by OmegaX123** [comment]
That was the problem I guess, created an exception in my antivirus for CKAN and tried again, it worked. Thanks!
