### ISSUE TITLE
[Bug] Localized line breaks missing on Windows

### ISSUE THREAD

**Issue by Normolo** [KSP-CKAN/CKAN#3470]
Background
----------
* Operating System:  Windows 10
* CKAN Version:  v1.30.4
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No. 

Problem
-------
Grammatical Error

**Steps to reproduce**
1. Start a removal of a mod
2. Have the removal of the mod fail

Lack of a space

![image](https://user-images.githubusercontent.com/53821637/139573383-280b9bf4-1405-4cfc-bc50-43cb7be94b46.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Sorry, what grammatical error or lack of a space are you referring to? IT's not clear what part of the screenshot is relevant.

**Comment by HebaruSan** [comment]
Is it this?

![image](https://user-images.githubusercontent.com/1559108/139583859-f2446b21-7d12-429a-8285-e7d1e68bf13f.png)

We do already have a line break there:

https://github.com/KSP-CKAN/CKAN/blob/41a0143b5cfb48b5767db306f045ae1640143e0a/GUI/Properties/Resources.resx#L272-L274

Possibly similar to #2818?

**Comment by HebaruSan** [comment]
From [some casual reading](https://github.com/dotnet/msbuild/issues/2206), it seems that `.resx` files are supposed to use CRLF line endings, but we have them as normalized to LF in the repo and OS-specific in the working dir (CRLF when checked out on Windows, LF on Linux and Mac), so it would be LF when we build in an Ubuntu container:

https://github.com/KSP-CKAN/CKAN/blob/41a0143b5cfb48b5767db306f045ae1640143e0a/.gitattributes#L31

**Comment by HebaruSan** [comment]
Hi @Normolo, can you please try this test build and see whether it still has the same problem?

- https://github.com/KSP-CKAN/CKAN/suites/4214190858/artifacts/108890297
