### ISSUE TITLE
Apply Changes Button is Disabled (Grayed out)

### ISSUE THREAD

**Issue by Davidtank70** [KSP-CKAN/CKAN#3487]
Background
----------

**CKAN Version:** 
CKAN v1.22.6

**KSP Version:** 
KSP 1.3.1.1891

**Operating System:** 
Windows 10

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
I deleted all of my old mods. Before deleting them though I was installing all of the mods and then quickly canceled the installation. After doing so deleted the mods refreshed the page and then installed them. It worked fine I got on. But I forgot that I needed module manager but I cant install it as you will see in the screenshot it is grayed out.

**Affected mods and mod versions:**
Any not previously installed before this glitch happened (may not be a glitch may be an Id10t error but idk)

Problem
-------
Apply changes button is grayed out and I cant click it
**What steps did you take in CKAN?**
I cleared cache as well as all of my currently installed mods

**What did you expect to happen?**
For the button to work

**What happened instead?**
Nothing happened it was the same as before

**Screenshots:**

![image](https://user-images.githubusercontent.com/36216761/35896407-021a0942-0b8a-11e8-8460-e78b011947cd.png)

**CKAN error codes (if applicable):** 
I had no error codes

**Comment by HebaruSan** [comment]
The screenshot just looks like ModuleManager is already installed (quite likely for it to get pulled in as a dependency if you installed several other mods). There would be a message in the status bar if the apply changes button was being disabled with a non-empty change set. Then again this issue and version are quite old, so who knows what might be happening.

@Davidtank70, is this still happening for you on the latest version of CKAN?

**Comment by Davidtank70** [comment]
I honestly haven't played KSP in like a year or two so I'm not sure (waiting for KSP2).
