### ISSUE TITLE
[Feature] Anti Piracy

### ISSUE THREAD

**Issue by NameLord** [KSP-CKAN/CKAN#3491]
**So noone with pirated version of the game should have this**
or something that when you enter on any world it does something glitchy like the 
Stormworks Build & Rescue Pirated version which fly sharks into you everytime.

**Comment by HebaruSan** [comment]
We agree that users should not pirate KSP, but CKAN can't tell whether that has happened, and CKAN does not interfere with how the game works other than installing other mods. This isn't something for CKAN to work on.
