### ISSUE TITLE
Am using ksp 1.0.5 and when I try to launch the message Couldn't start game.  The system cannot find the file specified appears

### ISSUE THREAD

**Issue by Sam80404** [KSP-CKAN/CKAN#3493]
Background
----------
* Operating System:  Windows 10
* CKAN Version:  1.30.4
* KSP Version: 1.0.5.1028

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** 
No

Problem
-------
When I try to launch, the message 

Couldn't start game.

The system cannot find the file specified

Only happens on 1.0.5. The message appears with or without mods downloaded
**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**
The game launches

**Screenshots (if applicable)**
<img width="603" alt="image" src="https://user-images.githubusercontent.com/82413800/144681039-8d047e39-24a2-4e90-9589-02e42d4b421b.png">
**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Did you use the "fake" option? If so, it isn't supposed to download the game for you, it just makes a non-functional instance for testing.

**Comment by HebaruSan** [comment]
If that's not it, please fill in the template if you want to keep this issue open. We need to know those things to help you.

**Comment by Sam80404** [comment]
> Did you use the "fake" option? If so, it isn't supposed to download the game for you, it just makes a non-functional instance for testing.

I don't think so. Don't know what that is

**Comment by HebaruSan** [comment]
OK, the next thing to check is Settings &rarr; Game command line in the menu:

![image](https://user-images.githubusercontent.com/1559108/144681676-059498d1-e170-43bc-ae49-4e8823741f4e.png)

... and then check whether that file exists in your game folder. I'm guessing this version was before the switch to 64-bit, so you may have to change the setting to `KSP.exe` instead (see KSP-CKAN/CKAN#1711).

**Comment by Sam80404** [comment]
> OK, the next thing to check is Settings → Game command line in the menu:
> 
> ![image](https://user-images.githubusercontent.com/1559108/144681676-059498d1-e170-43bc-ae49-4e8823741f4e.png)
> 
> ... and then check whether that file exists in your game folder. I'm guessing this version was before the switch to 64-bit, so you may have to change the setting to `KSP.exe` instead (see #1711).

That worked. Thanks

**Comment by leoponka** [comment]
What if it still wont launch ?

**Comment by HebaruSan** [comment]
Then you should share a screenshot of your command line arguments popup and a screenshot of your game folder.
