### ISSUE TITLE
Registry already enlisted with tx error during install

### ISSUE THREAD

**Issue by ninnnika** [KSP-CKAN/CKAN#3502]
![Screenshot (192)](https://user-images.githubusercontent.com/96836474/147683520-fad7dab4-56e5-440e-a64a-ae8e43e5a567.png)
![Screenshot (193)](https://user-images.githubusercontent.com/96836474/147683522-c84b4bc1-fdca-4b7d-a089-4bdf19c42bf2.png)

i dont know how or why its happening

**Comment by HebaruSan** [comment]
Code reference for this exception:

https://github.com/KSP-CKAN/CKAN/blob/136c26dcf6bc74d5854c474c1012a51a084f0167/Core/Registry/Registry.cs#L406-L435

**Comment by HebaruSan** [comment]
@ninnnika, does it keep happening if you close CKAN and re-open it?

**Comment by HebaruSan** [comment]
Can't investigate without getting questions answered.
@ninnnika, if you're able to respond, please do and we can re-open this.

**Comment by ninnnika** [comment]
> @ninnnika, does it keep happening if you close CKAN and re-open it?

sorry for late response, yes if i re-open ckan it still happens

**Comment by HebaruSan** [comment]
Hi @ninnnika, thanks for responding. We don't have enough information yet to figure out what's wrong, so I have prepared a debug build of CKAN and a log4net.xml file with some settings to make it generate a log file for us. Please download it here:

- [ckan-tx-debugging.zip](https://github.com/KSP-CKAN/CKAN/files/7824891/ckan-tx-debugging.zip)

1. Extract both files in the ZIP to a folder on your disk
2. Run the copy of ckan.exe in that folder
3. When CKAN appears, make the error happen
4. Close CKAN
5. In the folder from step 1 find a file called CKAN.log
6. Upload this file to a sharing site like Google Docs and share the link here
   (Or if you put it into your own new ZIP file, you can upload it directly to GitHub by clicking on the bottom of the text box where it says, "Attach files...")

This will help us to figure out the sequence of events that lead up to the error. It may allow us to determine the problem, or we may need to gather more information.

Thanks for reporting this!

**Comment by HebaruSan** [comment]
Can't investigate without getting questions answered.
@ninnnika, if you're able to respond, please do and we can re-open this.
