### ISSUE TITLE
[Bug] Missing mods from list

### ISSUE THREAD

**Issue by MacKenzieHnC** [KSP-CKAN/CKAN#3508]
Background
----------
* Operating System: Windows 10
* CKAN Version: v1.30.4
* KSP Version: 1.10.1.2939

Fresh install, freshly switched to beta 1.10.1

Problem
-------
Several mods are missing from the list, seemingly regardless of compatibility settings or filter choices. The ones I am certain should be here that aren't are Ferram Aerospace, RSS, and RP-1.

**Steps to reproduce**
Fresh install.
Install beta 1.10
Follow instructions for RP-1 install
RP-1 does not show up in list

![ckan_bug](https://user-images.githubusercontent.com/20330711/148283094-5b34899c-1a6b-478c-a144-eeac2fb89e77.png)

**Comment by MacKenzieHnC** [comment]
I am happy to provide any additional information, but I do not know what else is needed. I thought I followed the bug reporting instructions exactly.

Do the mods appear for other people? Is this problem unique to me?

**Comment by HebaruSan** [comment]
Sorry, it's not so much that _you_ need to provide more info yet, as that this will require some investigation and puzzling out. Yes, the mods appear for everyone else (or we would see a _lot_ more traffic from RP-1 users).

Can you share your `<KSP dir>/CKAN/registry.json` file (a link to a filesharing site is probably best)? That's where all the mods should be listed, so looking at that file would let us determine whether they're missing from the database or just not being displayed somehow.

**Comment by MacKenzieHnC** [comment]
Okay, perfect. And yes, I thought that would be the case. 

Can do. Is Google Drive acceptable for file sharing?

**Comment by HebaruSan** [comment]
Probably, as long as we can access the file.

**Comment by MacKenzieHnC** [comment]
Got it. Here's the file: https://drive.google.com/drive/folders/1GjrB8VZH8zuqG4DMcPFEHJCsFdW9mrzU?usp=sharing

It seems related to an older issue (I'll find the link if you like).

**Comment by HebaruSan** [comment]
Yeah, I see only a few differences when I diff it against my own file:

1. The `release_date` timestamps are from different time zones (unimportant)
2. I have some additional download count data from old frozen mods (unimportant)
3. I have the DLCs and you don't (probably unimportant)
4. You have the `MechJeb2-dev` repo set up

By process of elimination, maybe there's something weird with the `MechJeb2-dev` repo now. I'll try running my CKAN with your registry.json...

**Comment by HebaruSan** [comment]
... well, your `registry.json` works fine for me; I can see the RP-1 modules as well as the MechJeb2-dev modules:

![image](https://user-images.githubusercontent.com/1559108/148298970-2d6532c7-d48e-4691-b55a-90875b4f2052.png)

**Comment by MacKenzieHnC** [comment]
Got it. I'll try one more fresh install of both KSP and ckan to remove further variables

**Comment by HebaruSan** [comment]
Finally a guess:  Right click the column headers and see if you have any of the tags hidden. I can reproduce your list if I turn off `planet-pack`, `plugin`, `resources`, and `science`:

![image](https://user-images.githubusercontent.com/1559108/148299916-39fd9cd1-2f4d-4ce1-9336-7a01daebfda5.png)

**Comment by HebaruSan** [comment]
> Where does ckan store its data? (i.e. I know where the .exe is, where does it keep settings?)

Mostly in `%LOCALAPPDATA%\CKAN`, but also some in `<KSP dir>\CKAN`.

The hidden tag list is in `%LOCALAPPDATA%\CKAN\tags.json`.

**Comment by MacKenzieHnC** [comment]
I am such a dingus... Yes, I had turned off those tags for God-knows-why. I am terribly sorry for wasting your time.

**Comment by HebaruSan** [comment]
Don't worry about it, there's no such thing as useless feedback. We might want to make it more obvious in the UI when tags are hidden, for example.

**Comment by MacKenzieHnC** [comment]
Thank you tremendously.

Closing this now.
