### ISSUE TITLE
Downloads from SpaceDock failing

### ISSUE THREAD

**Issue by zekepeanut** [KSP-CKAN/CKAN#3511]
Background
----------
* Operating System:  Windows 10 Home 20h2
* CKAN Version: v1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
multiple mods failing to download

**Steps to reproduce**
* Go to... install mods
* Click on... install mods
* See error

**Expected behavior**
mods download

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/43897041/148847321-9a998454-4a55-4a9e-b3b3-ec6f341f67ea.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Apparently you're having trouble downloading from SpaceDock, but the server seems OK currently. Are you in Australia? We had a user in Australia report early termination of SpaceDock downloads in a browser recently. SpaceDock is just one server in Germany rather than a CDN, so if you don't have a good route to it, there can be problems.

**Comment by zekepeanut** [comment]
no, i am in northern  new york

**Comment by zekepeanut** [comment]
i have downloaded some of these before with no problems

**Comment by HebaruSan** [comment]
Is the site working OK for you in a browser now?

https://spacedock.info/

That Australian user was also on a wireless connection, which may have been related. Are you using a wireless network?

**Comment by zekepeanut** [comment]
i am on ethernet, and i cannot connect to that website, it says it took too long to respond

**Comment by HebaruSan** [comment]
OK, sounds like your computer or router has blocked SpaceDock. You'll need to figure out what's doing that and remove it to fix this issue.

**Comment by zekepeanut** [comment]
interesting, ill look into that

**Comment by zekepeanut** [comment]
well, i've confirmed that the problem is with my internet, not my pc, but still not sure what it is.

**Comment by HebaruSan** [comment]
Good luck! Closing because CKAN isn't involved and can't fix this.
