### ISSUE TITLE
Could not find the file specified when launching game

### ISSUE THREAD

**Issue by 1212winner** [KSP-CKAN/CKAN#3513]
Background
----------
* Operating System: windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.0.5

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
yep

Problem
-------
**Describe the bug**
cant launch ksp and says the system could not find the file specified

**Steps to reproduce**
* Go to launch with bdarmory on ksp 1.0.5
* Click on launch
* See error

**Expected behavior**
launch game w/ mods

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Is the `KSP_x64.exe` file present in your game folder?

**Comment by 1212winner** [comment]
no

**Comment by 1212winner** [comment]
which one too ckan or game data

**Comment by HebaruSan** [comment]
That's your problem, then. You need to have the game installed to launch it. CKAN doesn't install the game for you.

**Comment by 1212winner** [comment]
where is ksp x64

**Comment by 1212winner** [comment]
reinstalled and it doesn't work too

**Comment by HebaruSan** [comment]
You can buy the game from Steam or the KSP Store:

- https://store.steampowered.com/app/220200/Kerbal_Space_Program/
- https://store.privatedivision.com/en/game/buy-kerbal-space-program-ksp

**Comment by 1212winner** [comment]
i own it 
idk how to find the file

**Comment by 1212winner** [comment]
look
![image_2022-01-11_224548](https://user-images.githubusercontent.com/97559875/149065354-fcbbd708-eeb6-4f5a-bb03-a9839471b253.png)

**Comment by 1212winner** [comment]
its still happening

**Comment by DasSkelett** [comment]
Does launching the game through Steam work?
Can you send a screenshot of your game folder?

**Comment by 1212winner** [comment]
no and how do i take a screenshot

**Comment by DasSkelett** [comment]
Try validating the game files (right click on the game in Steam > Properties > Local files > Validate (or so)).

For screenshots, try the "Print Screen" button (or a short form of that), or the Snipping Tool, or however its new replacement is called.

**Comment by 1212winner** [comment]
![image_2022-01-12_102436](https://user-images.githubusercontent.com/97559875/149180302-ddab24a7-9f9b-47b6-8d0b-94190325eda8.png)

![image_2022-01-12_102539](https://user-images.githubusercontent.com/97559875/149180510-a175dac2-93da-412e-ad8d-0252dfa74221.png)

**Comment by 1212winner** [comment]
ok

**Comment by 1212winner** [comment]
i want bdarmory

**Comment by 1212winner** [comment]
thats why

**Comment by HebaruSan** [comment]
Ahh, OK. There are two teams maintaining forks of BDArmory for recent versions, you can install one of them instead:

![image](https://user-images.githubusercontent.com/1559108/149182672-cd02b4d7-8763-46c6-bb26-9ec84f584a30.png)

For how to make the one for 1.9 installable on 1.12, see: 
https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions

**Comment by 1212winner** [comment]
yeah this happened
![image_2022-01-12_105348](https://user-images.githubusercontent.com/97559875/149185402-ea656424-2d8b-4b24-bc14-17bb6dd6c9d9.png)

**Comment by 1212winner** [comment]
idk why

**Comment by HebaruSan** [comment]
Wait, is there something wrong in that screenshot? I thought you were confirming success.

**Comment by 1212winner** [comment]
its stuck on serenity

**Comment by HebaruSan** [comment]
Modded KSP support can be had here:

https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/

**Comment by 1212winner** [comment]
couldent find help

**Comment by HebaruSan** [comment]
Try asking!

**Comment by 1212winner** [comment]
found another mod

**Comment by 1212winner** [comment]
https://spacedock.info/mod/1646/KerbalField

**Comment by 1212winner** [comment]
link to mod above

**Comment by DasSkelett** [comment]
It is nice that you found a mod that you like, but please remember that this issue section is for CKAN bug reports and support requests, not general KSP and modding discussions. The forums are the best place for this, many people are watching it, and chances for qualified help for non-CKAN topics are much higher. Thanks :)

**Comment by HebaruSan** [comment]
I was just about to say most of that. :grin: 

I'm going to go ahead and "lock conversation" here to save team members from further off-topic notification spam. Good luck and have fun!

**Comment by HebaruSan** [comment]
Pinned because people are still doing this. :facepalm:
