### ISSUE TITLE
CKAN wont start

### ISSUE THREAD

**Issue by Fr8monkey** [KSP-CKAN/CKAN#3521]
Background
----------
* Operating System: Win 10
* CKAN Version: Hubble
* KSP Version: 1.12.1

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Start CKAN, and quits 2 seconds later

![image](https://user-images.githubusercontent.com/1559108/150465671-021fd9b4-f0da-4410-8c4d-043d601b6c23.png)

**Comment by Fr8monkey** [comment]
Go to... CKAN icon on desktop
    Click on... See above
    See error No error, just stops and goes to desktop.

**Comment by Fr8monkey** [comment]
This is the C:\Users\Ashley\AppData\Local\CKAN config data

{
  "AutoStartInstance": null,
  "DownloadCacheDir": "C:\\Users\\Ashley\\AppData\\Local\\CKAN\\downloads",
  "CacheSizeLimit": null,
  "RefreshRate": null,
  "Language": "en-US",
  "GameInstances": [
    {
      "Name": "Auto KSP",
      "Path": "c:/program files (x86)/steam/SteamApps/common/Kerbal Space Program",
      "Game": "KSP"
    }
  ],
  "AuthTokens": {}
}

**Comment by DasSkelett** [comment]
Did you run CKAN as administrator once in the past? That would be one possible explanation of why it can no longer access the file.
For the future, please don't do that, it works fine running as user, and it's not a good idea to run arbitrary software with elevated privileges.

To fix the situation now, the easiest would be to just delete the file. There don't seem to be any non-default settings set. It should also detect the game instance automatically again, and regenerate the config file.

**Comment by HebaruSan** [comment]
Glad you got it working!
