### ISSUE TITLE
I want to install RSS

### ISSUE THREAD

**Issue by MichaelZ2801** [KSP-CKAN/CKAN#3523]
![Screenshot (15)](https://user-images.githubusercontent.com/98266849/150681146-45f0d2af-35c0-4be3-ab39-d7d23c82a646.png)

my game data folder is clear except for squad and squad expansion

**Comment by DasSkelett** [comment]
If you want to install RSS together with RealismOverhaul and RP-1, follow these instructions: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1
Most notably, you need to be on KSP 1.10.1.
If you want to only install RSS wtih RO (but no RP-1), follow these instructions: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Advanced-Install-for-1.10.1

**Comment by MichaelZ2801** [comment]
I want to stay in the newest ksp and what is rp1?Am 23.01.22, 14:51 schrieb DasSkelett ***@***.***>:

   
  If you want to install RSS together with RealismOverhaul and RP-1, follow these instructions: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Installation-for-1.10.1 Most notably, you need to be on KSP 1.10.1. If you want to only install RSS wtih RO (but no RP-1), follow these instructions: https://github.com/KSP-RO/RP-0/wiki/RO-&-RP-1-Advanced-Install-for-1.10.1

**Comment by DasSkelett** [comment]
RSS/RO/RP-1 are not stable yet on KSP 1.12. If you want to to this, you are on your own. This page may help you: https://github.com/KSP-RO/RP-0/wiki/Experimental-RO-&-RP-1-Installation-for-1.12.2

If you need help there, please ask in the appropriate channels (RP-1 forum thread, their Discord, ...).

> what is rp1?

This question is easily answered by using a search engine of your choice, you will find this thread for example: https://forum.kerbalspaceprogram.com/index.php?/topic/190040-rp-1-realistic-progression-one-for-ksp-110/
RP-1 is needed if you want to play RSS/RO in Career mode, but not needed for Sandbox.

**Comment by MichaelZ2801** [comment]
It's still Kerbin
![Uploading 20220123_154855.jpg…]()
