### ISSUE TITLE
Access to the path 'E:/Games/KSP_10_1_RP0/GameData/RP-0/Parts/SampleReturnCapsule/Assets' is denied. Error during installation!

### ISSUE THREAD

**Issue by kp0llux** [KSP-CKAN/CKAN#3536]
Background
----------
* Operating System: win11
* CKAN Version: hubble (1.30.4)
* KSP Version: 1.10.1.2939

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
copied over mechjeb global cfg like with every new install, hasnt broken anything before but who knows

Problem
-------
**Describe the bug**
was able to install RP-1 et al via ckan with slight modifications to allow for version differences, but then idk a few weeks after setting it up i went to install the updates that had accumulated and i started getting that message. ensured the folders existence, tried giving admin rights, no joy. 

doesnt matter if i modify the requested updates to not include the folder, it just says it cant access the first thing it tries and nothing starts. installing a new mod works just fine, likely bc it doesnt have to touch an existing folder?

**Steps to reproduce**
* Go to... ckan main window
* Click on... add available updates -> apply changes -> apply
* See error

**Expected behavior**
updates applied

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
About to upgrade:

 * Upgrade: Realistic Progression One (RP-1) v1.11.4.0 to v1.11.6.0 (cached)
 * Upgrade: RO Capsules v1.6.0.0 to v1.7.0.0 (cached)
 * Upgrade: Procedural Fairings 1:v6.1 to 1:v6.2 (cached)
 * Upgrade: Real Antennas v2.1 to v2.1.1 (cached)
 * Upgrade: Test Flight v2.1.1.0 to v2.2.0.1 (cached)
 * Upgrade: Scatterer Sunflare 3:v0.0829 to 3:v0.0831 (cached)
 * Upgrade: Realism Overhaul v14.9.0.0 to v14.10.0.0 (cached)
 * Upgrade: Advanced Jet Engine v2.19.0 to v2.20.0 (cached)
 * Upgrade: Solver Engines plugin v3.12.0 to v3.13.0 (cached)
 * Upgrade: Real Fuels 1:rf-v13.5.3 to 1:rf-v13.6.0 (cached)
 * Upgrade: Kopernicus Planetary System Modifier 2:release-1.12.1-71 to 2:release-1.12.1-82 (cached)
 * Upgrade: scatterer 3:v0.0829 to 3:v0.0831 (cached)
 * Upgrade: Scatterer Default Config 3:v0.0829 to 3:v0.0831 (cached)
Access to the path 'E:/Games/KSP_10_1_RP0/GameData/RP-0/Parts/SampleReturnCapsule/Assets' is denied.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

```

**Comment by HebaruSan** [comment]
When we've seen this before, it's because CKAN was run as administrator to install, then as non-administrator to remove or upgrade. Don't run CKAN as administrator.
