### ISSUE TITLE
Saving Mod List for later

### ISSUE THREAD

**Issue by AflackR** [KSP-CKAN/CKAN#3538]
Is there any way to save a mod list to download later and if there is how?

**Comment by HebaruSan** [comment]
Does this help?

https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29

**Comment by AflackR** [comment]
yes, it does unfortunately it seems like i can't save one unless i use the complicated way since my export doesn't work thank you though

**Comment by HebaruSan** [comment]
OK, do you want to share what problems you are having with the export, or is this issue ready to be closed?

**Comment by AflackR** [comment]
whenever i go to export a modpack it asks for a file name but no matter what file i put in it doesn't let me save anything
![Screenshot (4)](https://user-images.githubusercontent.com/93016599/155859328-1fc30dbd-ded7-434f-97db-7fbacb0ead75.png)

**Comment by HebaruSan** [comment]
It looks like it's working fine in that screenshot. What actual problem are you having?

**Comment by AflackR** [comment]
so it did work but for some reason the file/notes i saved it as was hidden but i got it unhidden and everything is working fine

**Comment by HebaruSan** [comment]
Cool, glad you got it working!
