### ISSUE TITLE
DLL for module FilterExtensions found at GameData/GameData/000_FilterExtensions/...

### ISSUE THREAD

**Issue by mcbix12** [KSP-CKAN/CKAN#3540]
Background
----------
* Operating System: windows 10
* CKAN Version: v1.30.4
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
module manger cant update

**Steps to reproduce**
* Go to... module manger
* Click on... update
* See error installation failed

**Expected behavior**
failed

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Please share a screenshot of the error so we can try to figure out what's wrong.

**Comment by mcbix12** [comment]
![image](https://user-images.githubusercontent.com/100975541/156857148-1a0485d7-4fd1-4ca5-a7e2-31c33af76621.png)

**Comment by mcbix12** [comment]
![image](https://user-images.githubusercontent.com/100975541/156857198-5cf662cf-ac51-4ee3-b323-cff0e4eb3177.png)

**Comment by HebaruSan** [comment]
Thanks. Your manually-installed copy of FilterExtensions is installed wrong (notice the `GameData/GameData` in the path, there should only be one GameData folder). Fix that or remove it and try again.

**Comment by mcbix12** [comment]
so do i go into the ckan files? what do i do?

**Comment by HebaruSan** [comment]
1. Open your game folder
2. Open GameData
3. Open GameData again
4. Select everything
5. Cut
6. Move to parent folder (the first GameData folder)
7. Paste
