### ISSUE TITLE
Ksp wont launch through ckan

### ISSUE THREAD

**Issue by PnefsL** [KSP-CKAN/CKAN#3541]
![image](https://user-images.githubusercontent.com/100996923/156879091-631d86e1-e5e1-4059-ba38-fcea4b18aac5.png)
Im trying to launch ksp through a copied ksp file which might be the problem but i dont see why it would

**Comment by PnefsL** [comment]
![image](https://user-images.githubusercontent.com/100996923/156879259-89676b91-4f8f-45c9-9678-7b6f0c98eb23.png)
this might help

**Comment by DasSkelett** [comment]
You are missing the executable file, `KSP_x64.exe`. It needs to be in the game directory for it to be able to start.

Try using CKAN's instance cloning feature to create a working copy of an already existing instance.

**Comment by PnefsL** [comment]
i just realised that when i was making a shortcut to the .exe file i forgot to actually make a shortcut copy so i just pulled it straight out. I am currently trying to fix the problem but i will tell you if i need any more help

**Comment by PnefsL** [comment]
I got it working now thank you for the quick response
