### ISSUE TITLE
3 second delay on clicking Scatterer in main mod list

### ISSUE THREAD

**Issue by EmpXander** [KSP-CKAN/CKAN#3547]
Background
----------
* Operating System: WindowOS
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------

Whenever hovering over and clicking Scatterer the application freezes for 3 seconds before it does nothing or actually selects

**Steps to reproduce**
* Go to... Ckan
* Click on... Scatterer
* See error Lag

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
I see no delay when clicking on Scatterer. We'll need more information about what's different with your computer to investigate this. I guess a good start would be a list of your installed mods.
