### ISSUE TITLE
Scrolling the list of compatible game versions "jumps down"

### ISSUE THREAD

**Issue by EmpXander** [KSP-CKAN/CKAN#3548]
Background
----------
* Operating System: WindowsOS
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

Problem
-------

When changing compatibility I'll be scrolling then it jumps down, skipping alot of versions. I tested if it was my mouse, it wasn't

**Steps to reproduce**
* Go to... CKAN
* Click on... Compatible Game Versions & scroll down
* See error

**Expected behavior**
It will jump down far, skipping many of the options

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
This seems to be working fine, and the description is very vague. Are you clicking the scrollbar arrow, the trough, dragging the scroll indicator, using the mouse wheel? Please describe what you're doing in sufficient detail to allow us to investigate.
