### ISSUE TITLE
Install fails, "The operation is not valid for the state of the transaction"

### ISSUE THREAD

**Issue by thatNbaguy** [KSP-CKAN/CKAN#3549]
Background
----------
* Operating System: Windows 10 
* CKAN Version: 1.30.4
* KSP Version: 1.12.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** yes? I deleted all the mods but ckan still thinks there are mods there but I installed them with ckan. I also have mods installed by ckan a few hours before it happened and worked fine

Problem
-------
**Describe the bug**
Whenever I try to add a lot of mods (48 mods in this case) and downloads all the mods and at the end just gives me the error "The operation is not valid for the state of the transaction" and then says error during installation on the next line, even when I retry it does not work.

**Steps to reproduce**
* Select A lot of mods (in this case I had been installing 48 mods)
* Click on "Apply Changes"
* See error

**Expected behavior**
Installing the mods

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/101854669/158938098-bfc273a4-48a2-43e9-9805-87eb11ee0e5b.png)

**CKAN error code (if applicable):**
I did not get any
```
PLACE CODE HERE !
```
I did not get any

**Comment by thatNbaguy** [comment]
As of now it works but has happened a lot, I have not done anything to change it but it but it happens every so often

**Comment by HebaruSan** [comment]
Hmm, more weird transaction stuff on Windows, may be related to #3539.

**Comment by HebaruSan** [comment]
In the KSP-RO Discord rp1-support channel this week, a user reported the error from #3455, followed by this one. So maybe these are all different symptoms of the same underlying issue, and maybe they're all fixed in #3512? :crossed_fingers:
