### ISSUE TITLE
[Feature] Modpack/Modlist Codes

### ISSUE THREAD

**Issue by Hyperion-21** [KSP-CKAN/CKAN#3550]
I was messing around with ROR2's mod loader, r2modman, a long while ago, and discovered that one of the ways to share mod lists is through a code, that someone else can input and the modloader would automatically install that modpack/modlist.

This made me think, "What if this, but CKAN?"

How I envision this working, is that someone can create an instance, with whatever mods they desire. Then, they can share that instance's mods, by making CKAN generate a code. This code can then be given to other users, that upon inputting, will attempt to install the mods, only failing with conflicts.

Potentially, this may require the receiving user to clone a new instance of the KSP version the original user used in their instance.

**Comment by HebaruSan** [comment]
Does this help?
https://github.com/KSP-CKAN/CKAN/wiki/Sharing-a-modlist-%28metapackages%29

**Comment by HebaruSan** [comment]
No response yet; closing as the feature already exists. Please reply if you think there's more to it.
