### ISSUE TITLE
i cant uninstall certain mods like TACS life support for some reason

### ISSUE THREAD

**Issue by albingladh** [KSP-CKAN/CKAN#3551]
Background
----------
* Operating System: idk
* CKAN Version: v1.30.4
* KSP Version: 1.12.1.3142

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
kinda

Problem
-------
**Describe the bug**
some mods i cant uninstall
and i wanna make a new modpack but i cant
the mods are
TAC life support 
backround resouces
Editor Extensions Redux
**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Why can't you uninstall them? Is there an error message?
