### ISSUE TITLE
[Bug] The following inconsistencies were found: * RSSVE-HR 2.1.5 missing dependency Scatterer * KabramsSunFlaresPack-Blue-High 001 missing dependency Scatterer

### ISSUE THREAD

**Issue by Charleshzh** [KSP-CKAN/CKAN#3553]
Background
----------
* Operating System: Windows 10 21H2
* CKAN Version: v1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When I am going to install some mods it show this 

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
The following inconsistencies were found:
* RSSVE-HR 2.1.5 missing dependency Scatterer
* KabramsSunFlaresPack-Blue-High 001 missing dependency Scatterer
安装时发生错误！
如果上面的消息指明是一个下载错误，请重试. 否则请向我们提交一个issue便于我们调查.
如果怀疑是元数据问题: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
如果怀疑是客户端问题: https://github.com/KSP-CKAN/CKAN/issues/new/choose

```

**Comment by HebaruSan** [comment]
Which mods are you trying to install, and which do you already have installed?
