### ISSUE TITLE
[Bug] Installation Mods (.CKAN)

### ISSUE THREAD

**Issue by Greg4833** [KSP-CKAN/CKAN#3556]
Background
----------
* Operating System: Windows 10 
* CKAN Version: 1.30.4
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No, I just want to install mods with a .ckan file.

Problem
-------
**Describe the bug**
I want to install mods with a .ckan file, but I have this error :

FR : Le chemin d'accès spécifié, le nom de fichier ou les deux sont trop longs. Le nom de fichier qualifié complet doit comprendre moins de 260 caractères et le nom du répertoire moins de 248 caractères.
EN : The specified path, filename or both are too long. The full qualified file name must be less than 260 characters and the directory name must be less than 248 characters. (traduction)

**Steps to reproduce**
* Go to Files > Import with a .ckan
* Click on the file
* See error

**Expected behavior**
Normally, mods should be installed.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/1559108/161976916-2749fb01-1cbc-4582-b2bb-90b175150601.png)

**CKAN error code (if applicable):**
I don't have or don't find any code..

**Comment by HebaruSan** [comment]
Please share the .ckan file.

**Comment by Greg4833** [comment]
No problem, I share it with mediafire...

Link : https://www.mediafire.com/file/2kogjz32vpjdpyp/installed-Kerbal_Space_Program_Mod.ckan/file

(Github doesn't accept) : https://i.imgur.com/D22pD6p.png

**Comment by DasSkelett** [comment]
Does the output also say which file is affected?
But assuming the file in question gets installed correctly from CKAN, there's nothing we can do to fix this, this is a (stupid) limitation of Windows. You'll have to move your KSP directory further up the directory tree so the path is shorter. `C:\Games\KSP` for example.

**Comment by Greg4833** [comment]
I will test it, thanks

**Comment by HebaruSan** [comment]
Glad you got it working!
