### ISSUE TITLE
[Feature] Option to delete registry.locked and continue in GUI

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#3558]
**Extremely low priority; me just being lazy after a recent issue which caused CKAN to crash repeatedly.**

Problem
-------
It's a tiny bit annoying to have to manually delete the "registry.locked" file after CKAN has crashed or was killed/incorrectly shut down.

Suggestions
-----------
It would be nice if CKAN could warn the user (as at present), but then also allow the user to continue without having to manually delete the registry.locked file.

Granted this introduces a higher level of risk with users accidentally launching a second instance of CKAN, continuing, and then presumably causing filesystem/registry corruption. Perhaps gate this functionality behind an "experienced user" option?

**Comment by HebaruSan** [comment]
We are accumulating issues about bringing ConsoleUI into feature parity with GUI, but in this case it's the other way around:

![image](https://user-images.githubusercontent.com/1559108/162081430-d7b86761-84eb-4c2f-90cd-e7dc6c59177c.png)

**Comment by HebaruSan** [comment]
ConsoleUI's strategy is pretty straightforward: catch `RegistryInUseKraken` thrown by `RegistryManager.Instance`, and if the user opts to delete the file, loop back around and try again.

https://github.com/KSP-CKAN/CKAN/blob/d9a68dc3cca2cd8902b6d39ccf80d4036a694d6a/ConsoleUI/GameInstanceListScreen.cs#L175-L201
