### ISSUE TITLE
[Bug] New dependencies of upgraded mods missing from change set

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#3559]
CKAN 1.30.4; Debian GNU/Linux 11; Mono 6.12.0.122

Problem
-------
I went to update a mod recently (X Science! Continued) and it now contains new dependencies after having been taken over by another developer.

Apart from confirming the list of mods to update, the new dependencies were not listed or needing to be confirmed during this step. It was only when the download started that I noticed the additional mods.  I had to kill the CKAN process in order to abort the update (the "Cancel" button was, for some reason, unresponsive)

Suggestions
-----------
I'd like CKAN to pop up a similar confirmation as happens when first installing a mod; that is, listing all new dependencies during the confirmation step.

Alternatively/relatedly, there is no way to check whether a new version of a mod has new dependencies. The dependencies list in the UI only shows the dependencies of the currently installed version. It would be nice to be able to display the information about another version of the mod.

Semi-Relatedly, it would be nice to "pin" a mod to its current version, to prevent it from being updated when using the "Add available updates" button.

Semi-Relatedly, it would be nice to be able to blacklist mods, which would prevent any updates to existing mods which depend on blacklisted mods. (EDIT: This is actually raised in #3129)

**Comment by HebaruSan** [comment]
> Semi-Relatedly, it would be nice to "pin" a mod to its current version, to prevent it from being updated when using the "Add available updates" button.

That exists: #3220

**Comment by HebaruSan** [comment]
> I'd like CKAN to pop up a similar confirmation as happens when first installing a mod; that is, listing all new dependencies during the confirmation step.

Huh, the change set preview screen _is_ shown, but the dependencies are missing. I think we can safely regard that as a simple bug in the change set preview screen; it should be showing those new installs as dependencies of the upgrade.

![image](https://user-images.githubusercontent.com/1559108/162083790-2528703e-056b-4cae-817d-992fce69d5e2.png)

&rArr;

![image](https://user-images.githubusercontent.com/1559108/162083951-bf9bdcec-4d72-41dc-9c65-1283acb035b3.png)

**Comment by mwerle** [comment]
> > Semi-Relatedly, it would be nice to "pin" a mod to its current version, to prevent it from being updated when using the "Add available updates" button.
> 
> That exists: #3220

Huh.. I did quite a bit of searching (terms : pin / hold / keep) and could not find this.  Thank you!!

**Comment by HebaruSan** [comment]
This line explicitly excludes upgrades from the dependency listing logic:

https://github.com/KSP-CKAN/CKAN/blob/04484a6a0b695611d936ccbd91ae1cdf624f6663/GUI/Controls/Changeset.cs#L35

I wonder why we did that...

**Comment by HebaruSan** [comment]
OK, that wasn't too bad... :relieved: 

![image](https://user-images.githubusercontent.com/1559108/162088464-34d6b5c9-c345-49e6-b16a-93c9d6ca5261.png)

Only complication was this line was actually enqueueing the old version, not the upgraded version:

https://github.com/KSP-CKAN/CKAN/blob/04484a6a0b695611d936ccbd91ae1cdf624f6663/GUI/Model/ModList.cs#L134

**Comment by HebaruSan** [comment]
There should be a test build under the Artifacts dropdown here when it finishes compiling:

https://github.com/KSP-CKAN/CKAN/pull/3560/checks

**Comment by HebaruSan** [comment]
> > That exists: #3220
> 
> Huh.. I did quite a bit of searching (terms : pin / hold / keep) and could not find this. Thank you!!

Hmm, ideally it would be more easily discoverable in the app itself. Any suggestions? I guess we could look into auto-creating a Held label for existing users.
