### ISSUE TITLE
[Bug] Mods wont install!!!

### ISSUE THREAD

**Issue by AtackYT** [KSP-CKAN/CKAN#3561]
Background
 Operating System: Windows 10
 CKAN Version: 1.304
 KSP Version: 1.12.3

Problem

Mods wont install and it gives me weird error messages!

![image](https://user-images.githubusercontent.com/87932425/162567709-dcbc5b19-8bb4-4625-8138-e5782b149953.png)

```
653 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - 
Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json

One or more downloads were unsuccessful:

Error downloading NiceMKseriesBody V3.6: En befintlig anslutning tvingades att stänga av fjärrvärddatorn
Error downloading AutomatedAerialRefueling 1:1.9.1: En befintlig anslutning tvingades att stänga av fjärrvärddatorn

English:
Error downloading NiceMKseriesBody V3.6: existing connection was forced to shut down the remote computer
Error downloading AutomatedAerialRefueling 1:1.9.1: An existing connection was forced to shut down the remote host
```

**Comment by DasSkelett** [comment]
You seem to have network issues. CKAN can't reach anything, neither GitHub nor SpaceDock nor archive.org.

If your network is otherwise fine, it is probably some sort of firewall or antivirus software that blocks CKAN, try allowlisting it.

**Comment by AtackYT** [comment]
My firewall and my antivirus is not the issue here ive tried without but thank you dasskelett fir helping me!

**Comment by AtackYT** [comment]
reinstalling ckan fixed it!
