### ISSUE TITLE
[Bug] Failed to connect to repository. Exception: Unable to connect to the remote server

### ISSUE THREAD

**Issue by ElonMusk0423** [KSP-CKAN/CKAN#3565]
Background
----------
* Operating System: Windows 10
* CKAN Version: V 1.30.4
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I only deleted all mods in my game data folder, then I installed CKAN.

Problem
-------
**Describe the bug**
Mods don't seem to install no matter what I try. It notifies me that the mod failed to download. 

**Steps to reproduce**
* Go to... CKAN.EXE
* Click on... Waterfall Mod
* See error Failed to download/Failed to connect to repository

**Expected behavior**
Failed to download |Mod Name| no matter what I try it doesn't seem to work.

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/103706482/163501236-f90cc459-1779-4f3e-81c7-e5bf54c1c941.png)

**CKAN error code (if applicable):**
![image](https://user-images.githubusercontent.com/103706482/163501163-fa34d591-9e96-41fd-b188-af4a145901cc.png)

```
PLACE CODE HERE !
```
I don't know what code?

**Comment by HebaruSan** [comment]
When we've seen this before, it's been because the user's antivirus or firewall software was blocking CKAN. I'd check that and add an exception for CKAN if you can.

**Comment by ElonMusk0423** [comment]
@HebaruSan Just an FYI at this moment I'm currently not paying for antivirus, by any chance can you give me information on how I can allow windows security to give an exception for CKAN. And btw, thank you for your help :)

**Comment by ElonMusk0423** [comment]
Houston we have a problem! It seems even if I exempt CKAN from antivirus and firewall, it doesn't seem to load.

**Comment by DasSkelett** [comment]
GitHub and ksp.sarbian.com are fine, so it's something on your computer or in your network that blocks it from accessing them. You'll have to figure out what and how to disable it.
