### ISSUE TITLE
[Bug] Installation Failed: RSSTextures16k

### ISSUE THREAD

**Issue by JordanMilly** [KSP-CKAN/CKAN#3569]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

No

Problem
-------
**Describe the bug**
The following inconsistencies were found:
* F:/Steam Games/SteamApps/common/Kerbal Space Program/GameData/RSS-Textures/PluginData/TritonColor.dds is registered to RSSTextures16K but has not been removed!
Error during installation!

**Steps to reproduce**
Add available updates
Apply Updates
Wait for installation to process
RSSTextures16K file removal stalls at 5%
Error comes up

**Expected behavior**
No error, update of mods takes place

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
When we've seen this previously, it has been caused by the game still running (and locking the mod files). Is your game still running?

**Comment by JordanMilly** [comment]
> When we've seen this previously, it has been caused by the game still running (and locking the mod files). Is your game still running?

Nope, the game wasn't running, I checked Task Manager.

I ended up getting around it by manually deleting the folder for the RSSTextures manually.

**Comment by HebaruSan** [comment]
Maybe a permissions thing, then. Glad you got it working! :tada:
