### ISSUE TITLE
Please add a Devuan Linux template to the repo

### ISSUE THREAD

**Issue by VulcanRidr** [KSP-CKAN/CKAN#3572]
Devuan Linux is a fork of base Debian, but without systemd, using instead, either sysvinit, openrc, or runit. Since it _is_ Debian, can you add a distribution template for Devuan, so that the repo can be added to apt? When I tried to include the key or add the repo, I got:

```
# sudo apt-add-repository -u -y 'deb https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main'
Traceback (most recent call last):
  File "/usr/bin/apt-add-repository", line 95, in <module>
    sp = SoftwareProperties(options=options)
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 109, in __init__
    self.reload_sourceslist()
  File "/usr/lib/python3/dist-packages/softwareproperties/SoftwareProperties.py", line 599, in reload_sourceslist
    self.distro.get_sources(self.sourceslist)    
  File "/usr/lib/python3/dist-packages/aptsources/distro.py", line 91, in get_sources
    raise NoDistroTemplateException(
aptsources.distro.NoDistroTemplateException: Error: could not find a distribution template for Devuan/chimaera
````

Thanks

**Comment by HebaruSan** [comment]
Looks like this might be a problem with your system rather than the repo:

https://www.devuan.org/gitlab-issues/devuan.devuan-maintainers.33.html

Can you try without using `apt-add-repository`?

**Comment by DasSkelett** [comment]
Yes I was about to write that I can't remember encountering the term "distribution template" when we've setup the apt repository. Looking through the repository files I'm not seeing anything Debian-specific, after all it does also work on all versions of Ubuntu.

Googling for this error returns some similar help requests mostly affecting Elementary OS users,
and looking at the sources it appears more like a system configuration problem:
https://git.launchpad.net/python-apt/tree/aptsources/distro.py#n91
```python
        # find the distro template
        for template in self.sourceslist.matcher.templates:
            if (self.is_codename(template.name) and
                    template.distribution == self.id):
                #print "yeah! found a template for %s" % self.description
                #print template.description, template.base_uri, \
                #    template.components
                self.source_template = template
                break
        if self.source_template is None:
            raise NoDistroTemplateException(
                "Error: could not find a distribution template for %s/%s" %
                (self.id, self.codename))
```

**Comment by VulcanRidr** [comment]
I got it installed, by manually adding the repository. I just did it the old-fashioned way:

`echo "deb https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main" > sources.list.d/ckan.list`

I was then able to get ckan installed. I will look at my configs...

Also, please note that there is another CKAN project out there (https://docs.ckan.org/en/2.9/user-guide.html). I ran across that, and was following the guide, but the fact that it wanted solr-jetty installed made me take a second look. :) Found it was the wrong project, and was then able to search you out. 

--vr

**Comment by HebaruSan** [comment]
Glad you got it working! :tada:

**Comment by HebaruSan** [comment]
> Also, please note that there is another CKAN project out there (https://docs.ckan.org/en/2.9/user-guide.html). I ran across that, and was following the guide, but the fact that it wanted solr-jetty installed made me take a second look. :) Found it was the wrong project, and was then able to search you out.

Heh, yep, we know about "the other CKAN." :stuck_out_tongue_closed_eyes: Their users occasionally submit bug reports here (though not many recently). The usual telltale is the heavy database lingo, since CKAN uses a pretty simple JSON-based data model.

**Comment by VulcanRidr** [comment]
Agreed. The first thing I saw was "install solr-postgresql" and I was like "okay..." (but I am installing on Linux, and am a Unix/Linux sysadmin by trade), so that wasn't _too_ weird... But then the guide said "install solr-jetty" (with java and all of the dependencies), and I was like, "wait, what?!?" So I started digging around and found I was on the wrong project.
