### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by Antimee6** [KSP-CKAN/CKAN#3577]
Background
----------
* Operating System:  Windows 10 
* CKAN Version:  1.30.4
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
When downloading  some SpaceX addons to ksp some of the mods didnt got downloaded and it just said : The remote certificate is invalid according to the validation procedure.

**Steps to reproduce**
Search for the mods listed on the screenshot 
Check the install thingie 
Press apply 
And it should say download failed : The remote certificate is invalid according to the validation procedure.

**Expected behavior**

It should have downloaded the mod 

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/80589249/166652301-2febef00-abe0-4061-9a14-d3b5b32801ef.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
There was a temporary problem with SpaceDock that seems to be over now.
