### ISSUE TITLE
[Feature] Add a green loading bar in the taskbar

### ISSUE THREAD

**Issue by AmiSimon** [KSP-CKAN/CKAN#3578]
Could you add a loading bar in the ckan app title in the taskbar to see the total progress of mods installation please ?

**Comment by HebaruSan** [comment]
So far it looks like this may be Windows-specific...

https://docs.microsoft.com/en-us/dotnet/api/system.windows.shell.taskbaritemprogressstate?view=netframework-4.7.2

![image](https://user-images.githubusercontent.com/1559108/166678460-9a79e1d9-d09c-492d-960c-0db3259d457c.png)

**Comment by HebaruSan** [comment]
dotnet/winforms#3851 seems to be asking for this API to be added to WinForms, though I doubt Mono would be included in that.

**Comment by HebaruSan** [comment]
@AmiSimon, what is the reason that this feature interests you? It looks like we probably will not be able to support the taskbar progress indicator, but if we know the use case, we may be able to cover it in other ways.

For example, if you just want to be able to switch to other applications and still know when CKAN finishes an installation, we could add a popup notification for that to the CKAN tray icon.

**Comment by HebaruSan** [comment]
Closing as this appears to be a Windows API, not .NET, and so it isn't cross-platform or available for CKAN to use. If you think of other ways to solve the same problem that you'd like us to consider, please let us know.
