### ISSUE TITLE
Could not retrieve latest build map

### ISSUE THREAD

**Issue by dhefan** [KSP-CKAN/CKAN#3579]
Background
----------
* Operating System: windows 11
* CKAN Version: v1.30.4
* KSP Version: 1.12

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**nope

Problem
-------
i cant download mods 

**Expected behavior**
i cant download mods 

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
8861 [1] WARN CKAN.GameVersionProviders.KspBuildMap (null) - Could not retrieve latest build map from: https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json
```

**Comment by DasSkelett** [comment]
CKAN can't reach GitHub. If you opened this issue from the same PC, it must be something blocking CKAN specifically.
Check any installed antivirus or firewall software and try to make an exemption for CKAN.

**Comment by dhefan** [comment]
still gets an error

**Comment by DasSkelett** [comment]
Unfortunately we can't help you from CKAN's side, you'll have to find the source of the block and disable it.
Again, if you are accessing github.com for this issue on the same machine, then it is some software/setting on your PC that blocks CKAN. If you are using another device in a different network, like your mobile phone, then it's also possible that the block happens at your router (over-eager parental controls for example).
If you can, try CKAN on different devices and try to narrow it down step by step.

**Comment by dhefan** [comment]
ok it fix now my internet is just bad.
