### ISSUE TITLE
Unknown problem in Japanese locale

### ISSUE THREAD

**Issue by zyzzzwxzz** [KSP-CKAN/CKAN#3582]
Background
----------
* Operating System: 
* CKAN Version: 
* KSP Version: 

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**

**Screenshots (if applicable)**

<img width="897" alt="image" src="https://user-images.githubusercontent.com/98269696/169497790-82f0b8e1-7124-48a3-bcd8-8ee50f2e853c.png">

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by DasSkelett** [comment]
Please fill out the template. We need to know what you did to help you.
