### ISSUE TITLE
Add automatic install dialog for MacOS DMG

### ISSUE THREAD

**Issue by thonkinator** [KSP-CKAN/CKAN#3584]
Problem
-------
When opening the MacOS DMG file to install CKAN, no DiskImageMounter window pops up, as do most other DMGs. Here's an example, the discord DMG installer:
<img width="350" alt="Screen Shot 2022-06-01 at 11 33 00 PM" src="https://user-images.githubusercontent.com/51034477/171547597-636382c9-9a82-49d4-8f39-68ae17a336bb.png">

 This can be quite confusing, which I know from experience because it took me 10 minutes to figure out what was going on when I tried installing CKAN. You are apparently supposed to go to your desktop, and open up the disk image icon, which looks like this:
<img width="94" alt="Screen Shot 2022-06-01 at 11 34 07 PM" src="https://user-images.githubusercontent.com/51034477/171547742-7e6ed1de-37c9-4b9b-b597-13500a8d1fb2.png">
This is quite unusual, is not stated in the directions, and could be quite confusing for non-techsavvy people.

-----------
**Describe the solution you'd like**
I think the ideal solution is to have a window pop up when the DMG is opened. However, I have never made an app with a DMG installer, and thus do not know how that would be accomplished or how hard it would be.

**Describe alternatives you've considered**
An alternative is just stating this in the instructions, but wording it in a way that is clear and concise might be difficult.

**Additional context**
I'm on MacOS Monterey. I am unsure what the install process is like for any previous versions of MacOS, although I assume it's relatively the same.

**Comment by HebaruSan** [comment]
As far as I know, a window should already pop up when you open the .dmg. It's just a disk image file, and your OS should know what to do with it. Is it possible that you closed the window accidentally, or opened another window in front of it and missed it?

**Comment by thonkinator** [comment]
@DasSkelett sorry, I didn't realize that wiki page existed. the release page gives the not very descriptive instructions I was talking about, and makes no mention of the wiki page.
@HebaruSan no window pops up. i know because DiskImageMounter doesn't even open, shown by the dock.

**Comment by HebaruSan** [comment]
I finally dug up a Mac to check this. This pops up after I double click `CKAN.dmg`:

![CKAN dmg](https://user-images.githubusercontent.com/1559108/179411371-cf983fcd-341b-46e5-ac8c-62472c3530ca.png)

So it looks like the file we generate is still fine. Yes, that's an older OS, but if Apple has made their OS dumber since that one, consider complaining to them about that.

If a Mac developer felt like contributing improvements to how this package is built, we would welcome that, but I don't think we are going to put time into making our own installer dialog.

**Comment by HebaruSan** [comment]
If anyone else has problems opening the `.dmg` file, a user on Discord reported that moving it from Downloads to Desktop fixed that problem for them:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/f25442cf-2b17-491e-96c5-331efce1459e)

That might be worth a try for other users. Maybe Apple added some "security" logic with no UI/UX feedback to confuse users and waste the time of app developers?
