### ISSUE TITLE
[Feature] Keep downloading mods on error

### ISSUE THREAD

**Issue by NathanPeake** [KSP-CKAN/CKAN#3588]
Problem
-------
**Is your feature request related to a problem? Please describe.**
when one mod fails to download and forces you to redownload all the mods and reselect mods

Suggestions
-----------
**Describe the solution you'd like**
Don't stop on error, finish and then retry errored mods

**Comment by HebaruSan** [comment]
CKAN doesn't redownload mods (each one goes into the cache as soon as it finishes), but we can look into keeping selections when there's a problem.
