### ISSUE TITLE
Unknown complaint about GUI theming on Linux

### ISSUE THREAD

**Issue by Voreck** [KSP-CKAN/CKAN#3589]
Background
----------
* Operating System: Linux (Arch Linux)
* CKAN Version: v1.30.4

Problem
-------
The Ui respects the gtk theme at some points but not all, the mod list is just normal which looks kind of messed up

**Steps to reproduce**
* Start CKAN
* See the UI

**Expected behavior**
I expect all of the UI to respect the gtk theme

![image](https://user-images.githubusercontent.com/22007229/173202379-ecaf3afe-8a77-46f4-bf95-68a3bb488bf5.png)

**Comment by HebaruSan** [comment]
What specifically are you pointing out in that screenshot?

**Comment by Voreck** [comment]
Onb linux you can set a gtk theme thatapplications respect (as long as they arent with qt, but even then you can give them a theme), for example a dark theme. In the screenshot you can see my theme is applied to part of the ui. But for the modlist for some reason it just picks the standard white theme which in combination look quite jarring. I could look for a method to deactivate the theme for ckan but i'd prefer if it respected it instead

**Comment by Voreck** [comment]
What i expect is for the white parts to be in the same dark style

**Comment by HebaruSan** [comment]
I see, thanks for the clarification.

The grid's colors are `SystemColors.Window` and `SystemColors.WindowText`, so CKAN's already doing what it should be there.

https://github.com/KSP-CKAN/CKAN/blob/1ad0b8289288b544d40c285de14c65a5b6f467e8/GUI/Controls/ManageMods.Designer.cs#L299-L303

You'd have to appeal to the Mono team to change how those values are derived from the theme, but if you try that, be prepared to receive no response as Mono isn't being very actively maintained anymore.

**Comment by HebaruSan** [comment]
Here's a previous pull request where we fixed how Mono's colors are set for them, for reference:

mono/mono#17888

It's not directly related, but it's a starting point if anyone wants to dig in.
