### ISSUE TITLE
CmdLine: Handle console-less operations (including cygwin mintty terminal)

### ISSUE THREAD

**Issue by phardy** [KSP-CKAN/CKAN#359]
ckan.exe is able to complete some operations when running in a cygwin bash/mintty session, but not all.

`./ckan.exe available` crashes with the following output

```
$ ./ckan.exe available
Mods available for KSP 0.25.0


Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at CKAN.CmdLine.MainClass.Available()
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

`./ckan.exe install` attempts installation but immediately crashes when polling for user input:

```
$ ./ckan.exe install RemoteTech
About to install...

 * RemoteTech v1.5.1

Continue? [Y/N]

Unhandled Exception: System.InvalidOperationException: Cannot read keys when either application does not have a console or when console input has been redirected from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at CKAN.User.YesNoDialogConsole(String text)
   at CKAN.ModuleInstaller.InstallList(List`1 modules, RelationshipResolverOptions options)
   at CKAN.CmdLine.MainClass.Install(InstallOptions options)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

`./ckan.exe remove` behaves identically to `ckan.exe install`:

```
$ ./ckan.exe remove RemoteTech
About to remove:

 * RemoteTech

Continue? [Y/N]

Unhandled Exception: System.InvalidOperationException: Cannot read keys when eit        her application does not have a console or when console input has been redirecte        d from a file. Try Console.Read.
   at System.Console.ReadKey(Boolean intercept)
   at CKAN.User.YesNoDialogConsole(String text)
   at CKAN.ModuleInstaller.UninstallList(IEnumerable`1 mods)
   at CKAN.CmdLine.MainClass.Remove(RemoveOptions options)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

All other commands seem to behave identically when run under bash/mintty and when run in a Windows command prompt. This is running on a 64 bit Windows 7 Professional installation, with SP1 and all updates installed.

**Comment by Sxderp** [comment]
I don't believe this is fully fixed in the latest version. (Regression perhaps?).

`./ckan.exe install RemoteTech` and `./ckan.exe remove RemoteTech` work just fine. No errors.

`./ckan.exe available` on the other hand crashes with the below

```
Unhandled Exception: System.IO.IOException: The handle is invalid.

   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.Console.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at System.Console.get_WindowWidth()
   at CKAN.CmdLine.ConsoleUser.get_WindowWidth()
   at CKAN.CmdLine.MainClass.Available(KSP current_instance, IUser user)
   at CKAN.CmdLine.MainClass.RunAction(Options cmdline, CommonOptions options, String[] args, IUser user, KSPManager manager)
   at CKAN.CmdLine.MainClass.Main(String[] args)
````

For info (this is grabbed from https://github.com/KSP-CKAN/CKAN/releases)
```
Novles@CRIP /cygdrive/c/Steam/steamapps/common/Kerbal Space Program
$ ./ckan.exe version
v1.20.1-0-gd41fe54 (beta)
```

**Comment by politas** [comment]
I'll have to enable SSH on my desktop to reproduce this.

**Comment by politas** [comment]
@sxderp, Have you tried using the --yes switch mentioned above?

**Comment by Sxderp** [comment]
Yeah, using it just throws up the 'usage' menu. I don't think the program recognizes it.
I find it really weird that (as far as I can tell, though I haven't tested everything*) only 'available' seems to have a problem. Yet, all that it should be doing is listing lines of text, no? If text can be displayed using other commands then there shouldn't be a problem here..?

*Currently away from my desktop, I only have my laptop which KSP is not installed and therefore cannot adequately test ckan features. Unless a skeleton KSP directory would be enough for it to recognize as an 'install directory.'

**Comment by techman83** [comment]
Indeed it is. From the metadata testing this is what we do for a dummy install: 

```
    # Create a new dummy KSP.
    mkdir dummy_ksp
    mkdir dummy_ksp/CKAN
    mkdir dummy_ksp/GameData
    mkdir dummy_ksp/Ships/
    mkdir dummy_ksp/Ships/VAB
    mkdir dummy_ksp/Ships/SPH
    mkdir dummy_ksp/Ships/@thumbs
    mkdir dummy_ksp/Ships/@thumbs/VAB
    mkdir dummy_ksp/Ships/@thumbs/SPH
    
    echo "Version $KSP_VERSION" > dummy_ksp/readme.txt
```

**Comment by Sxderp** [comment]
@techman83 thanks. I was able create the skeleton directory.

Just as a heads up, my laptop and desktop cygwin environments are basically identical (I keep it this way for compatibility).

Anyway, I was messing with the other commands of the tool and pretty much anything that's reasonable to execute, I can do without issue. I'm able to install / remove packages. I can list installed packages, I can mess with ksp installs and repos. The only issue that I've come across is `./ckan available`

**Comment by politas** [comment]
We aren't calling System.Console.get_WindowWidth() for any other command option, so that would explain why only this one verb throws the exception. There doesn't really seem to be any point in right-padding just this one command option.
