### ISSUE TITLE
Accesso al percorso negato

### ISSUE THREAD

**Issue by Shad03** [KSP-CKAN/CKAN#3591]
Background
----------
* Operating System: windows 10
* CKAN Version: 1.30.4
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
Accesso al percorso 'F:/SteamLibrary/SteamApps/common/Kerbal Space Program/GameData/KerbalKonstructs/FreeStatics/SoundCube' negato.
Error during installation!

**Steps to reproduce**
* Go to... kerbal konstrukts
* Click on... install
* See error

**Expected behavior**

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
CKAN needs to be able to access the files in your game folder, and this error means Windows isn't letting it. That probably means the permissions on the folder are wrong, but it's impossible to say exactly what's wrong without being able to look at your computer. Take a closer look at the file permissions and try to fix them. Good luck!
