### ISSUE TITLE
CKAN saying that "Another mod owns that file" or something similar

### ISSUE THREAD

**Issue by Goombaderp123** [KSP-CKAN/CKAN#3597]
Background
----------
* Operating System: Windows
* CKAN Version: 1.30.4
* KSP Version: 1.10.1 (for Real Solar System)

I have deleted some files MANUALLY without the help of CKAN, so idk if this is causing the bug.

**Problem:**
it won't let me install any mods, after I deleted some files without the help of CKAN.

**Steps to reproduce:**
* Delete some files (mod files) without CKAN's help
* I used RSS, idk if it's RSS only, but it could be either way just use RSS
* [ATTEMPT TO] Install RSS
* see error lol

**Expected behavior:**
I expected RSS to just install after I selected RP-1

**Comment by HebaruSan** [comment]
What does the error say? We need to know that to help you.

**Comment by HebaruSan** [comment]
Please also indicate which files you deleted. It's quite relevant if they include the file mentioned in the error.

**Comment by Goombaderp123** [comment]
> Please also indicate which files you deleted. It's quite relevant if they include the file mentioned in the error.

So, the only files I deleted was some mods installed with the help of CKAN (mainly visuals like E.V.E. or Spectra), I don't know if this helps, but I hope it does.
I'll attach a screenshot showing the error when I get the chance
