### ISSUE TITLE
[Bug] SSL Error even after following all the steps on the relevant wiki page

### ISSUE THREAD

**Issue by Jade-TheCat** [KSP-CKAN/CKAN#3608]
Background
----------
* Operating System: Fedora 36
* CKAN Version: 1.31.0
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug**
Every time I try and download from Spacedock (in this case trying to install Near Future propulsion) I get an SSL Error, even after syncing my certificates.

**Steps to reproduce**
* recieve SSL Error
* Run the steps on the wiki to resolve SSL Errors
* Attempt to install mod
* Recieve SSL Error again

**Expected behavior**
Following the steps on the wiki to resolve SSL errors should.. resolve the SSL errors

**CKAN error code (if applicable):**

```
Error downloading NearFuturePropulsion 1.3.5: Ssl error:1000007d:SSL routines:OPENSSL_internal:CERTIFICATE_VERIFY_FAILED
  at /builddir/build/BUILD/mono-6.12.0.122/external/boringssl/ssl/handshake_client.c:1132
```

**Comment by HebaruSan** [comment]
Which specific steps did you follow? This happens because you have an expired certificate, and you need to remove it. If you just "sync [your] certificates", that won't help.

https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors#fedora

**Comment by HebaruSan** [comment]
Previous report of this on Fedora: #3580

**Comment by Jade-TheCat** [comment]
i tried everything on that page, including removing the old Let's Encrypt certs. I even used `crtmgr --ssl https://spacedock.info` as crtmgr (certmgr?) is suggested on the Mono page for this kind of issue. I am fully expecting this to be an issue with my system configuration, but I don't know where as it was working fine a few months ago last time I played the game and I haven't touched anything mono since then, except to update CKAN yesterday.

**Comment by HebaruSan** [comment]
The last issue notes that for for some users, the right folder is `blocklist`, whereas for others it is `blacklist`, and there's no pattern as to when or why that is yet. Maybe you've moved from one category to the other?

**Comment by Jade-TheCat** [comment]
Oh my goodness that worked. I just did it for both blocklist and blacklist cus I don't want to try for both and it worked... Thank you for your help!

**Comment by HebaruSan** [comment]
Cool, I've added the blacklist/blocklist thing to the wiki since this clearly wasn't a one-off fluke as one might have hoped.
