### ISSUE TITLE
[Not Working] CKAN is failing to show any repositories. 

### ISSUE THREAD

**Issue by emelin33** [KSP-CKAN/CKAN#3611]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.24.0 - PRE
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No, I have not.

Problem
-------
**Describe the bug**
I can't download any mods. 

**Steps to reproduce**
* Go to... CKAN.exe
* Click on... refresh/ updating repositories
* See error

**Expected behavior**
That I'd be capable of downloading a few mods on KSP through CKAN.

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/1559108/180570721-4fa04f52-c738-4dcb-982e-88593cf8f8f2.png)

https://gyazo.com/8a65767280af6be5c4bb0b7fc467928c
**CKAN error code (if applicable):**
No error code was provided.
```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Use the latest version. 1.24.0-PRE is beyond ancient and not expected to work anymore.

**Comment by emelin33** [comment]
> Use the latest version. 1.24.0-PRE is beyond ancient and not expected to work anymore.

I just did and it worked. Thanks!
