### ISSUE TITLE
KSP. "Flight Manager for Reusable Stages (FMRS)"

### ISSUE THREAD

**Issue by vipAavos** [KSP-CKAN/CKAN#3619]
KSP.
Installed "Flight Manager for Reusable Stages (FMRS)" via CKAN.
Please explain to me the following: before installing FMRS, I had 996 patches downloaded, and after installing this mod, there were 2456 of them!!! Where did this amount come from? Immediately 1500 more! Why is that?
It may not be a CKAN problem, but I don't know where to look for the problem.
Thanks for understanding.
![MM](https://user-images.githubusercontent.com/93523697/183277034-329d80ab-d9c1-4127-98f8-6feeac6c2c13.png)

**Comment by HebaruSan** [comment]
Hi, this bugtracker is for problems with CKAN. Try this for game support:

https://forum.kerbalspaceprogram.com/index.php?/forum/70-technical-support-pc-modded-installs/
