### ISSUE TITLE
Incorrect client version reported in CLI

### ISSUE THREAD

**Issue by Ippo343** [KSP-CKAN/CKAN#362]
Using Galaxy Rise, `ckan.exe` reports the version as 0.0.0.0:

```
CKAN Client 0.0.0.0
MIT License - CKAN Team
```

**Comment by pjf** [comment]
From @hakan42 in January:

> 

This is especially complicated now that we have multiple repositories...

Maybe something based on Jenkins build number of the "CKAN" build job ( http://ci.ksp-ckan.org:8080/job/CKAN/ )?


From @AlexanderDzhoganov in January:

> We should not bump up the DLL version. I repeat **we should not bump up the DLL version**, this will make all plugins and everything that depends on CKAN break, this is because assembly references are resolved by exact version (stupid, stupid). This problem should be solved in another way.

**Comment by pjf** [comment]
For the record, we just want it to show what the user expects from `ckan version`. I'm totally for replacing/rebuilding whatever cmdline library we use.

(I was *really* surprised how hard cmdline libraries were in .NET compared to how easy they are on Unix systems, but really I *shouldn't* be surprised by that.)

**Comment by ayan4m1** [comment]
```
C:\code\CKAN\Cmdline\bin\Debug>CmdLine.exe version
development (beta)
```

This is on Win10 x64. If I run the latest binaries from GitHub, I get:

```
C:\Users\adelisa\Downloads>ckan.exe version
v1.22.4+e9575cd8da50
```

Exactly what I would expect. Looking for any comments on _recent_ occurrences of this specific output from `ckan version`.

**Comment by politas** [comment]
I think it was the results from Galaxy Rise that were the concern

**Comment by Ippo343** [comment]
I confirm this has been fixed in the recent releases.
I'm too lazy to bisect the repo to find out when, but I'd say it's irrelevant as long as it's fixed now :)
