### ISSUE TITLE
[Feature] Add a delay before searching

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#3620]
Problem
-------
When starting to type in the search box, it seems to immediately start searching, which causes a bit of a delay (on an i9-9900k) before further typing can be done.

Suggestions
-----------
I had the same problem with the QuickSearch mod, and was able to solve it by adding a 1/2 second delay (configurable in the settings) before actually starting to search.  This allows the user to get a few more characters typed which narrows the search.

**Comment by linuxgurugamer** [comment]
After looking at the PRs, it appears this _may_ be fixed in this:

https://github.com/KSP-CKAN/CKAN/pull/3419

The description matches what I'm seeing

**Comment by HebaruSan** [comment]
Can you please give some examples of searches that seem slow?

I had questions in #3419 based on my observation at the time that most searches seemed fast. I'd like to investigate the specific things you're trying to see if I can identify problems that are slowing down the search.

**Comment by linuxgurugamer** [comment]
Sure, I'll make a short video for you

[ckan-mov.zip](https://github.com/KSP-CKAN/CKAN/files/9310665/ckan-mov.zip)

**Comment by HebaruSan** [comment]
So it's not a "special" search like `is:compatible`, but just looking for keywords in the mod names/descriptions. Thanks. :+1:

**Comment by HebaruSan** [comment]
I wonder whether we should simply ignore searches for 1 or 2 characters. By the time you get to 3 or more, the mod list ought to be cut down significantly, with a quicker refresh.
