### ISSUE TITLE
[Bug] Bad Metadata? Shaddy has relationships with Shabby set to Supports and also Conflicts

### ISSUE THREAD

**Issue by nan0bug00** [KSP-CKAN/CKAN#3623]
Background
----------
* Operating System: Windows 10
* CKAN Version:  1.31.0
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** no

Problem
-------
Trying to install Shaddy (collection of shaders) which also needs Shabby (shader asset bundle loader with an incredibly similar name) and Textures Unlimited in order to apply the shaders to stock/restock parts.  When selecting Shaddy, it says there is a conflict.  However it also says under the relationships tab that it supports it.  

**Steps to reproduce**
* Go to CKAN, open a KSP install, and try to install Shabby and Shaddy at the same time.

**Expected behavior**
Should just install both mods without issue.  If there is a conflict, then the relationships setting under Shaddy should be set to *either* conflicts or supports, not both.

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/8329580/183772557-1efd8b55-01f8-4345-a664-309cf462c19d.png)

**CKAN error code (if applicable):**

n/a

**Comment by HebaruSan** [comment]
The conflict is version-specific; you can install it alongside Shabby, but it has to be for a version later than v0.2.0:

https://github.com/KSP-CKAN/NetKAN/pull/9240#issuecomment-1199814794

> It should also **support** [Shabby](https://github.com/taniwha/Shabby) as it can be used as a shader loader for Shaddy and Shaddy's asset bundle follows Shabby's naming scheme. 
> 
> Shabby should also have a minimum version **greater than** v0.2.0 (the current newest version), since I have spotted a conflict between it(0.2.0) and Textures Unlimited([1.5.10.25](https://github.com/shadowmage45/TexturesUnlimited/releases/tag/1.5.10.25)), but I am working with the author of Shabby and this has been fixed, but not yet released, the new version should be releasing soon.

https://github.com/KSP-CKAN/NetKAN/blob/master/NetKAN/Shaddy.netkan

```yaml
conflicts:
  - name: Shabby
    max_version: v0.2.0
depends:
  - name: ModuleManager
recommends:
  - name: TexturesUnlimited
supports:
  - name: ReStock
  - name: Shabby
```

**Comment by nan0bug00** [comment]
> The conflict is version-specific; you can install it alongside Shabby, but it has to be for a version later than v0.2.0 (which doesn't exist yet, the authors are still working on it):

According to the Shaddy github, 0.3.0 is done.  The link in the readme is broken, but the release is on the [Shabby github release page.](https://github.com/taniwha/Shabby/releases/tag/v0.3.0)

Not sure if the authors are ready to have that up on CKAN yet or not, but figured I'd let you know.  I'll just manually install them, no big deal to me :)

**Comment by HebaruSan** [comment]
Hmm, that's a tag, not a release. Trying to install a source code ZIP probably won't work given that Shabby has a plugin.

@drewcassidy, can you update Shabby's version file to reflect the new version? That's how the CKAN bot is set up to find releases of this mod, and it still says 0.2.0:

- https://pileof.rocks/KSP/Shabby.version

**Comment by HebaruSan** [comment]
Hmm, @taniwha's version file looks like it's up to date, might make sense to switch back:

- https://taniwha.org/~bill/Shabby.version

http://taniwha.org/~bill/Shabby_v0.3.0.zip

**Comment by HebaruSan** [comment]
@nan0bug00, thanks for calling our attention to this; Shabby 0.3.0 is now indexed and should be installable alongside Shaddy.
