### ISSUE TITLE
Could not find file 'C:\Users\VNBLor\AppData\Local\Temp\CdFileMgr\65f85249-3bff-45.GPL-2_0'.

### ISSUE THREAD

**Issue by VNBLor** [KSP-CKAN/CKAN#3626]
Could not find file 'C:\Users\VNBLor\AppData\Local\Temp\CdFileMgr\65f85249-3bff-45.GPL-2_0'.
i am new to this program and dont know wha t this is

**Comment by HebaruSan** [comment]
Hi @VNBLor, please fill in the issue template:

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md

We need that info to help you.
