### ISSUE TITLE
CKAN launches a blank cmd window

### ISSUE THREAD

**Issue by HolyTeddybear** [KSP-CKAN/CKAN#3628]
- CKAN is located in KSP´s directory

When I launch CKAN, a completely black cmd window appears and nothing more happens. I cannot type in the window, though i can highlight stuff in it as shown in the screenshot.

![image](https://user-images.githubusercontent.com/83548493/184686109-fd7f7b31-6c70-48e2-b5e0-92689b447a87.png)

**Comment by HebaruSan** [comment]
It's loading, wait.

**Comment by luiandresgonzalez** [comment]
Hi I got this same issue today, it is not a loading issue. Using latest version and this same version was working ok two days ago.
