### ISSUE TITLE
when I try to install RSS,CKAN tells me there is a invaild dll in a folder that doesn't exist

### ISSUE THREAD

**Issue by 2-nitroethylbenzene** [KSP-CKAN/CKAN#3636]
Background
----------
* Operating System: Win 10
* CKAN Version: v1.31.0
* KSP Version: Latest (was 1.12.3 at time of writing, not confirmed whether user has this version)

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Unconfirmed, presumably user tried to install RSS from a source ZIP

Problem
-------

User received this message:

> DLL for module RealSolarSystem found at GameData/RealSolarSystem-master/RealSolarSystem/Plugins/RealSolarSystem.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.

**Comment by 2-nitroethylbenzene** [comment]
Win 10
ckan v1.31.0
Latest
Code below:
DLL for module RealSolarSystem found at GameData/RealSolarSystem-master/RealSolarSystem/Plugins/RealSolarSystem.dll, but it's not where CKAN would install it. Aborting to prevent multiple copies of the same mod being installed. To install this module, uninstall it manually and try again.

Problem is I already delete that folder

**Comment by DasSkelett** [comment]
> Problem is I already delete that folder

Restart CKAN or hit the "Refresh" button so CKAN rescans GameData and gets an updated view.

Also make sure there is no (manually installed) other mod remaining either. For RP-1 you need a completely fresh and empty installation.

**Comment by 2-nitroethylbenzene** [comment]
Ok，I've fixed this problem,Thank you!



At 2022-08-18 17:22:09, "DasSkelett" ***@***.***> wrote:

Problem is I already delete that folder

Restart CKAN or hit the "Refresh" button so CKAN rescans GameData and gets an updated view.

Also make sure there is no (manually installed) other mod remaining either. For RP-1 you need a completely fresh and empty installation.
