### ISSUE TITLE
[Bug] Entire download list lost one one mod fails to download

### ISSUE THREAD

**Issue by Ricochetv1** [KSP-CKAN/CKAN#3646]
Background
----------
* Operating System:  Win8.1
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
If you have selected a list of mods to install, and one fails to download, you can only either retry the download, or cancel the operation. If you cancel the operation, you return to the mod selection list, and ALL your selections have been nullified.

**Steps to reproduce**
* Go to... Select mods
* Click on... Apply Changes
* See your time and work selecting mods disappear

**Expected behavior**
Allow to choose to skip that mod that failed, but finish downloading and installing the others, allowing for dependencies

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Hi @Ricochetv1, thanks for contacting us. We actually just addressed this last week in #3635, which keeps the changeset after a download failure, among other improvements. You can try a test build with the latest changes here:

- https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe
