### ISSUE TITLE
game instances

### ISSUE THREAD

**Issue by lordshitass** [KSP-CKAN/CKAN#3658]
Background
----------
* Operating System: 22000.795
* CKAN Version: 1.31.0
* KSP Version: 1.12.2

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
I'm stupid and messed up the game instances I've uninstalled both KSP and CKAN but it doesn't help and it makes things worse
(sorry if this isn't enough I'm not exactly sure how I messed it up also I'm sorry if I've upset y'all)

**Steps to reproduce**
* Go to...
* Click on...
* See error

**Expected behavior**
im just trying to open my game with mods 

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Please describe the problem you're having with CKAN.

**Comment by lordshitass** [comment]
> Please describe the problem you're having with CKAN.

I've tried to get CKAN to recognize that I have uninstalled KSP once but its not doing that so I tried my best to make a new instance but I did something wrong and it wont open KSP

**Comment by HebaruSan** [comment]
> I tried my best to make a new instance

Did you use the "Fake new KSP instance" option to do that?

![image](https://user-images.githubusercontent.com/1559108/188696738-ecc55800-f06a-4f9a-95f9-fff82c9dd9ed.png)

If so, "it wont open KSP" is expected, that option creates a folder without the game for testing. To play KSP, you need to purchase and install it outside of CKAN.

**Comment by lordshitass** [comment]
> > I tried my best to make a new instance
> 
> Did you use the "Fake new KSP instance" option to do that?
> 
> ![image](https://user-images.githubusercontent.com/1559108/188696738-ecc55800-f06a-4f9a-95f9-fff82c9dd9ed.png)
> 
> If so, "it wont open KSP" is expected, that option creates a folder without the game for testing. To play KSP, you need to purchase and install it outside of CKAN.

I did do that but I've already purchased KSP before

**Comment by HebaruSan** [comment]
OK, do **not** use the "fake" option, it's not what you want. Use "Add instance to CKAN" to tell CKAN where your game is installed.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#adding-game-folders

**Comment by lordshitass** [comment]
> 

thank you
