### ISSUE TITLE
Parallax 2.0

### ISSUE THREAD

**Issue by FreehandZAlt** [KSP-CKAN/CKAN#3668]
Mod info
--------
* Mod name: Parallax
* Author(s): Gameslinx
* License: Attribution-NonCommercial-NoDerivatives 4.0 International (CC BY-NC-ND 4.0)
* Homepage: https://forum.kerbalspaceprogram.com/index.php?/topic/209714-112x-parallax-pbr-terrain-and-surface-objects-201/
* Download: https://github.com/Gameslinx/Tessellation/releases

**Comment by DasSkelett** [comment]
Already indexed: https://github.com/KSP-CKAN/CKAN-meta/tree/master/Parallax
