### ISSUE TITLE
There is not enough space on the disk

### ISSUE THREAD

**Issue by Jack-Tozer** [KSP-CKAN/CKAN#3674]
Background
----------
* Operating System: Windows 10 Pro
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Negative

Problem
I Installed RP-1, and after I attempt to remove it, the response is "Installation failed!" and "There is not enough space on the disk"

**Steps to reproduce**
* Go to... Unknown
* Click on... Unknown
* See error Unknown
I expect it to be client side

**Expected behavior**
After reaching 98% completion, It fails (Response Above)

**Screenshots (if applicable)**

![image](https://user-images.githubusercontent.com/111403344/195735019-9a6b6e58-67b4-4223-8697-677111d0a657.png)

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
How much space is available on your disk?
