### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by Typ97** [KSP-CKAN/CKAN#3677]
cant deinstall or install mods

**Comment by HebaruSan** [comment]
Hi @Typ97, I'm sorry to hear that you're having problems, but that description is much too short for anyone to be able to help you. If you still would like help, the issue template is here; please fill it out completely and accurately so we can begin to understand the problem you're having, and then we can re-open this;

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
