### ISSUE TITLE
[Bug] CKAN already running dialog appears even if PID in registry.locked is stale

### ISSUE THREAD

**Issue by MusaSSH** [KSP-CKAN/CKAN#3686]
Problem
-------
If you need to close CKAN with SIGKILL, the `<GameDir>/CKAN/registry.locked` file keeps the PID of your SIGKILL'ed PID of previous CKAN session, which results in a CKAN already running error on the next start.

Suggestions
-----------
Add a check if that PID in registry.locked exists and belongs to a CKAN process. If true show the already running error dialog, otherwise open CKAN without error dialog.

**Describe alternatives you've considered**

**Additional context**
Linux

**Comment by HebaruSan** [comment]
This was done in #2139. Can you try running with the `--debug` flag? The code that does this has debug logging, so it might give us an idea of why it might not be working in your case.

**Comment by HebaruSan** [comment]
OK, I'm able to reproduce this, and from the logging, it seems that `IsInstanceMaybeLocked` is returning `false` when it should be `true.

```
1385 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
1385 [1] DEBUG CKAN.RegistryManager (null) - Checking for stale lock file at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1386 [1] DEBUG CKAN.RegistryManager (null) - Trying to create lock file: /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
```

**Comment by HebaruSan** [comment]
Yup, this line is bugged:

https://github.com/KSP-CKAN/CKAN/blob/cd7c3a0f180d7114101b2b5cdfa8604befd6efc2/Core/Registry/RegistryManager.cs#L171

That function takes the `<KSP>/CKAN` dir path as a parameter, but we're passing the path to the `registry.json` file.

https://github.com/KSP-CKAN/CKAN/blob/cd7c3a0f180d7114101b2b5cdfa8604befd6efc2/Core/Registry/RegistryManager.cs#L46-L54

https://github.com/KSP-CKAN/CKAN/blob/cd7c3a0f180d7114101b2b5cdfa8604befd6efc2/Core/Registry/RegistryManager.cs#L62

`GameInstance.cs` uses it correctly:

https://github.com/KSP-CKAN/CKAN/blob/cd7c3a0f180d7114101b2b5cdfa8604befd6efc2/Core/GameInstance.cs#L84-L91

**Comment by HebaruSan** [comment]
Confirmed that fixing that problem fixes the overall issue:

```
1392 [1] DEBUG CKAN.RegistryManager (null) - Preparing to load registry at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN
1393 [1] DEBUG CKAN.RegistryManager (null) - Checking for stale lock file at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1393 [1] DEBUG CKAN.RegistryManager (null) - Lock file found at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1393 [1] DEBUG CKAN.RegistryManager (null) - Lock file contents: 122202
1393 [1] DEBUG CKAN.RegistryManager (null) - Looking for process with ID: 122202
1394 [1] DEBUG CKAN.RegistryManager (null) - Deleting stale lock file at /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1394 [1] DEBUG CKAN.RegistryManager (null) - Trying to create lock file: /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1394 [1] DEBUG CKAN.RegistryManager (null) - Lock file created: /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.locked
1395 [1] DEBUG CKAN.RegistryManager (null) - Trying to load registry from /home/user/.local/share/Steam/steamapps/common/Kerbal Space Program/CKAN/registry.json
```

**Comment by MusaSSH** [comment]
Tested it on latest build, couldn't reproduce that behaviour. Thanks 👍

**Comment by HebaruSan** [comment]
Let's leave this issue open until the fix is merged. If we did a release from the `master` branch right now, the bug would still be present.
