### ISSUE TITLE
[Bug] Unspecified problem with plus key on Mac

### ISSUE THREAD

**Issue by Toaster-42** [KSP-CKAN/CKAN#3688]
Background
----------
* Operating System: macOS 12.1
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

I've previously installed a couple of mods manually.

Problem
-------
On the console UI, the '+' and f9 keys don't do anything, which prevents mods from downloading.

**Steps to reproduce**
* Open CKAN
* Open the info screen for a mod
* Press ctrl+D to download to cache
* Press f9 to open download screen

**Expected behavior**
Download screen opens

**Comment by HebaruSan** [comment]
Hi @Toaster-42, thanks for contacting us.

I'm confused; your summary says there's a problem with the <kbd>+</kbd> key, but your steps to reproduce say you're using Ctrl+D. Can you please clarify exactly what you're doing adn what the problem is? Thanks!

**Comment by Toaster-42** [comment]
I think I might have gotten the details wrong. I thought you had to save a mod to cache and then download it, but are you saying that you can just press `+` to download? Either way, the problem I'm having is that both `+` and `F9` don't do anything.

**Comment by HebaruSan** [comment]
OK, so what steps exactly are you taking? A screenshot or three would probably help out a lot.

**Comment by Toaster-42** [comment]
<img width="554" alt="Screen Shot 2022-10-29 at 12 06 59 PM" src="https://user-images.githubusercontent.com/116971554/198853795-22bf729c-f138-479a-85ee-6ebb764b7f42.png">
So I'm on this screen, have the mod highlighted, and press `+` and nothing happens. Same for `+` in all other mod list screens I've tried so far. 

I also found [this](https://github.com/KSP-CKAN/CKAN/pull/2177) page, which says that `F9` would open the installation screen, but it also does nothing. 

`Ctrl+D` on the mod details screen does work, and gives me this screen, however the mod is not downloaded, just saved to cache.
<img width="560" alt="Screen Shot 2022-10-29 at 2 54 06 PM" src="https://user-images.githubusercontent.com/116971554/198853826-e1ff6a8f-80ae-42e0-8463-53a08fff0f00.png">

**Comment by HebaruSan** [comment]
Thanks, that helps. Trying to guess what's happening, are you sure you're typing <kbd>+</kbd> and not <kbd>=</kbd>? Typically <kbd>+</kbd> requires <kbd>Shift</kbd> to be held while pressing the key. If you're just pressing the key by itself, that would probably generate <kbd>=</kbd> which wouldn't register with that screen.

**Comment by Toaster-42** [comment]
For some reason, everything works fine when I open CKAN now! Before it didn't show `F9` in the bar at the bottom, but now it's there and pressing it opens the download screen. Yesterday, I had tried `Shift` and `+`aka`=` and that also had no effect, but now it also works. I haven't changed anything whatsoever since yesterday.

**Comment by HebaruSan** [comment]
That's great news! Glad you got it working.

**Comment by Toaster-42** [comment]
Thanks so much for trying to help!
