### ISSUE TITLE
[Bug] Downloads from Spacedock hangs, but curl/wget have no problems

### ISSUE THREAD

**Issue by hpax** [KSP-CKAN/CKAN#3689]
Background
----------
* Operating System: Linux Fedora 36
* CKAN Version: 1.31.0
* KSP Version: 1.12.3.3173

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
Downloading from spacedock.info either fails or just hangs forever. However, accessing the exact same URL from the same computer using curl or wget works just fine.

**Steps to reproduce**

Attempting to install Near Future Solar:

```
About to install:

 * Near Future Solar 1.3.2 (spacedock.info, 24.4 MiB)
 * Community Tech Tree 1:3.4.4 (spacedock.info, 611.8 KiB)
 * Near Future Electrical 1.2.3 (spacedock.info, 13.1 MiB)
 * Near Future Propulsion 1.3.5 (spacedock.info, 35.9 MiB)
 * Near Future Spacecraft 1.4.3 (spacedock.info, 87.0 MiB)
 * Near Future Solar Core 1.3.2 (spacedock.info, 24.4 MiB)
 * Near Future Electrical Core 1.2.3 (spacedock.info, 13.1 MiB)
 * Near Future IVA Props 1:0.7.1 (cached)
Downloading "https://spacedock.info/mod/559/Near%20Future%20Solar/download/1.3.2"
```
<hang apparently forever>

Using "wget" or "curl" downloads the same file in less than 4 seconds:

```
wget -v https://spacedock.info/mod/559/Near%20Future%20Solar/download/1.3.2
--2022-10-31 19:15:36--  https://spacedock.info/mod/559/Near%20Future%20Solar/download/1.3.2
Resolving spacedock.info (spacedock.info)... 2a01:4f9:4a:1392::9601:9, 95.217.59.158
Connecting to spacedock.info (spacedock.info)|2a01:4f9:4a:1392::9601:9|:443... connected.
HTTP request sent, awaiting response... 302 FOUND
Location: https://spacedock.info/content/Nertea_200/Near_Future_Solar/Near_Future_Solar-1.3.2.zip [following]
--2022-10-31 19:15:39--  https://spacedock.info/content/Nertea_200/Near_Future_Solar/Near_Future_Solar-1.3.2.zip
Reusing existing connection to [spacedock.info]:443.
HTTP request sent, awaiting response... 200 OK
Length: 25611361 (24M) [application/zip]
Saving to: ‘1.3.2.1’

1.3.2.1                                   100%[===================================================================================>]  24.42M  7.64MB/s    in 3.2s    

2022-10-31 19:15:42 (7.64 MB/s) - ‘1.3.2.1’ saved [25611361/25611361]
```

**Comment by HebaruSan** [comment]
Problems with SpaceDock on Linux commonly are due to an expired certificate. Here's how to handle that:

https://github.com/KSP-CKAN/CKAN/wiki/SSL-certificate-errors#removing-expired-lets-encrypt-certificates

**Comment by hpax** [comment]
OK, I can verify that this resolves the problem. So this is a bug in Mono, not CKAN or Spacedock. This is extremely useful information.

I will also file a bug with Fedora to make them drop or blocklist the invalid certificate by default.

**Comment by hpax** [comment]
I have filed the following bug to request that Fedora includes this blocklist entry in their upstream ca-certificate bundle:

https://bugzilla.redhat.com/show_bug.cgi?id=2139631

**Comment by HebaruSan** [comment]
> this resolves the problem.

That's great, glad you got it working!

> So this is a bug in Mono

If I recall correctly, we found that Mono contains an internal fork of OpenSSL from before it was updated to handle the current certificate tree well, and then never updated it.

> I have filed the following bug to request that Fedora includes this blocklist entry in their upstream ca-certificate bundle:

Thanks, it will be really helpful if that gets done!
