### ISSUE TITLE
Revamp UI and and add theme settings

### ISSUE THREAD

**Issue by glowingc4** [KSP-CKAN/CKAN#3690]
Do yuo ever want a new theme? Do yuo want a COOL dark theme and not get blinded ever time you open CKAN?
I have a enchantment request and that's to have theme settings and also to have UI revamped, cuz I hate ANYTHING without a dark option cuz why do you want to be blinded?
Anyways, please revamp the UI to look cleaner or polished, and add theme settings cuz I NEED DARK!!

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Windows#dark-theme
