### ISSUE TITLE
[Feature] Use alternative buffer in consoleui

### ISSUE THREAD

**Issue by doinkythederp** [KSP-CKAN/CKAN#3692]
Problem
-------
**Is your feature request related to a problem? Please describe.**
Right now you can't scroll though the list of mods in the console ui, which makes it difficult as you are limited to arrow keys.

Suggestions
-----------
**Describe the solution you'd like**
Enabling the alternate screen buffer would enable scrolling on terminals such as iTerm2, making getting through the list of mods a lot faster.

**Additional context**
On POSIX systems, this is done by running the command `tput smcup` when the program starts and `tput rmcup` when it ends. Alternatively, it may work in certain terminals to send the escape sequences `\e[?1049h` and `\e[?1049l`.

Another benefit of using this feature is restoring shell history once the program ends. This is the same feature used by programs like `vim` and `less`. However, it could prevent the "Thanks for downloading CKAN" screen from showing.

Here's what this would look like:

https://user-images.githubusercontent.com/75394401/199400246-afa6574d-f7a0-40eb-bfbf-663fd13569bc.mov

**Comment by HebaruSan** [comment]
Sounds Unix-specific. Does this feature exist on Windows? We have to keep CKAN cross-platform.

**Comment by doinkythederp** [comment]
> Sounds Unix-specific. Does this feature exist on Windows? We have to keep CKAN cross-platform.

@HebaruSan Looks like the escape sequences work in the Windows Terminal, but not cmd.exe.
Sources:
https://learn.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences#alternate-screen-buffer
https://stackoverflow.com/questions/62267123/alternate-screen-buffer-for-the-windows-console

**Comment by HebaruSan** [comment]
> enable scrolling on terminals such as iTerm2

Are you talking about the mouse wheel here? I was confused about what this meant as that screen already supports scrolling through the list.

> you are limited to arrow keys

Note that <kbd>Home</kbd>, <kbd>End</kbd>, <kbd>PgUp</kbd>, and <kbd>PgDn</kbd> also work and provide faster navigation.

If my above speculation is correct, then the proposed benefits here are:

- The mouse wheel would scroll through the mod list on some terminals (presumably those terminals translate mouse wheel events into arrow key escape sequences? If so, then they could probably be configured to do this anyway)
- The terminal contents would be restored at exit

And the costs/risks are:

- Attempting to use a `tput` executable that isn't available on all platforms, causing problems for anyone who doesn't have it
- Attempting to use escape sequences that don't work on all platforms, causing problems for anyone who doesn't have it
  - The correct escape sequence to use [might vary from terminal to terminal](https://jameshfisher.com/2017/12/04/how-less-works/), so for full support we would need to probe the `terminfo.h` database
- Breaking the exit screen

This doesn't look like something we should do. The downsides outweigh the benefits.

Closing; thanks for the submission.

**Comment by HebaruSan** [comment]
Oops, I meant to add that users who happen to be on a platform where this functionality exists and want to use it can create a shell function to do that:

```bash
ckancon() { tput smcup; ckan consoleui "$@"; tput rmcup; }
```

The `ckancon` command would then run `ckan consoleui` in the alternative buffer. This has all the same advantages as the original suggestion without any of the risks or downsides of hard coding non-portable terminal stuff in CKAN.

**Comment by doinkythederp** [comment]
Because my keyboard doesn't have page up, page down, home, and end keys, I'm limited to my terminal's keyboard shortcuts to do these functions. However, it doesn't look like CKAN understands these. Maybe a better solution to my problem of not being able to scroll fast would be alternative keybinds for those functions? For example u, d, h, e.

**Comment by HebaruSan** [comment]
That sounds like something to fix in your terminal configuration rather than adding a custom hack to CKAN for one user. :stuck_out_tongue:
