### ISSUE TITLE
[Feature] I am really annoyed when i have to manually install a mod that is compatible and on the program but not downloadable through it i suggest the ability to brute force install through ckan if we are confident that it is compatible.

### ISSUE THREAD

**Issue by idkgeek** [KSP-CKAN/CKAN#3701]
Problem
-------
**Is your feature request related to a problem? Please describe.**
Ex. I'm always frustrated when...

Suggestions
-----------
**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by HebaruSan** [comment]
Just set the compatible versions. That's why that feature is there.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions
