### ISSUE TITLE
CKAN gives a SSL/TLS error when startup

### ISSUE THREAD

**Issue by hDLw08** [KSP-CKAN/CKAN#3704]
Failed to download https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz: The underlying connection was closed: Could not establish trust relationship for the SSL/TLS secure channel. when startup. Also i can click dismiss but there are no mods.

game ver 1.31.0

**Comment by HebaruSan** [comment]
Hi @hDLw08, please fill out the issue template so we have a basis for investigation. Problems like this frequently relate to your specific operating system, version, etc.:

https://github.com/KSP-CKAN/.github/blob/master/.github/ISSUE_TEMPLATE/bug_report.md
