### ISSUE TITLE
[Bug] GUI freezes on switch to changeset tab after refresh removing ZeroMiniAVC dependencies

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#3707]
## Background

* Operating System: Windows (probably others)
* CKAN Version: v1.31.2, v1.31.3
* KSP Version: 1.12.3, 1.12.4

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

## Problem

After KSP-CKAN/NetKAN#9438 and KSP-CKAN/CKAN-meta#3125, ZeroMiniAVC becomes auto-uninstallable (see #2753) for most users who have it. Unfortunately the client has problems with this.

In my own testing, the change set tab appears and the Apply changes button becomes enabled while the GUI is still responsive, so actually calculating the changeset in the background seems to be working, but _clicking_ Apply changes or the change set tab froze the GUI. So some code that runs when the changeset becomes visible is running forever. Should be able to figure this out with proper test data and some debug logging.

Multiple users have reported this on the forum.

Steps to reproduce even if you've already worked around the issue:

1. Start CKAN
2. Install ToolbarController, ClickThroughBlocker, and ZeroMiniAVC
3. Close CKAN
4. Edit `registry.json`
5. Find the `installed_module`s for ToolbarController and ClickThroughBlocker
6. Add ZeroMiniAVC to their `depends` lists
7. Start CKAN
8. Mark ZeroMiniAVC as auto-installed
9. Close CKAN
10. Edit `registry.json`
11. Delete the repo's `last_server_etag` property to force a refresh
12. Start CKAN
13. Refresh the registry
14. You'll be prompted to reinstall ToolbarController and ClickThroughBlocker; say Yes
15. The change set tab appears and Apply changes is enabled, and using either one will freeze the GUI

Easier:

1. Start CKAN
2. Install ToolbarController, ClickThroughBlocker, and ZeroMiniAVC
3. Mark ZeroMiniAVC as auto-installed
4. Close CKAN
5. Start CKAN
6. The change set tab appears and Apply changes is enabled, and using either one will freeze the GUI

### Workarounds

- `ckan remove ZeroMiniAVC` worked for me

**Comment by HebaruSan** [comment]
Weirdly, just installing ZeroMiniAVC and checking the auto-installed checkbox does **not** reproduce this. So there's some lingering state from before the refresh that somehow behaves differently from that simple setup.

**Comment by HebaruSan** [comment]
After adding lots and lots of new debug messages, `TabControl.SelectTab` is freezing with almost no CKAN code involved (`ThemedTabControl.OnDrawItem` is called 4 times, but finishes normally each time).

Noting new theory for later investigation: Some part of the change set tab must be failing to initialize properly at startup. This would explain why it matters whether the auto-removable mod is present at startup or later on. We must be trying to set the changeset before the tab is initialized, or something along those lines.

**Comment by HebaruSan** [comment]
Looks like a classic WinForms threading issue :facepalm:; the problem goes away if I wrap `Changeset.LoadChangeset` inside a `Util.Invoke` call. So we must be calling that from a background thread sometime during startup.

**Comment by HebaruSan** [comment]
For users landing here after reporting duplicates, you can try the test build with the fix:

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe>

**Comment by EoD** [comment]
I can confirm that the above ckan.exe (`v1.31.3`) does not freeze anymore after pressing "Add available updates".
