### ISSUE TITLE
Expired key signature for apt repo

### ISSUE THREAD

**Issue by BrettRyland** [KSP-CKAN/CKAN#3722]
On Ubuntu 22.04.1 LTS (and, most likely, other versions too), updating apt gives the following warning about CKAN's key signature being expired:
```
W: An error occurred during the signature verification. The repository is not updated and the previous index files will be used. GPG error: https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable InRelease: The following signatures were invalid: EXPKEYSIG 20338C5DC15BF412 KSP CKAN <debian@ksp-ckan.space>
W: Failed to fetch https://ksp-ckan.s3-us-west-2.amazonaws.com/deb/dists/stable/InRelease  The following signatures were invalid: EXPKEYSIG 20338C5DC15BF412 KSP CKAN <debian@ksp-ckan.space>
```

**Comment by HebaruSan** [comment]
The workflow to build the packages is failing as well:

https://github.com/KSP-CKAN/CKAN/actions/runs/3510762968/jobs/5881089338

Key was created in #3203. @techman83, can we make one that doesn't expire?

**Comment by HebaruSan** [comment]
@BrettRyland and @ckuethe and @SaigaTaiga and @amedee, I think you'll have to re-add the new key as in the repo instructions, but it should be updated now:

https://github.com/KSP-CKAN/CKAN/blob/master/doc/apt-repo.md

**Comment by BrettRyland** [comment]
Yep, works for me too. The only point of note was that the old apt .list file was `ckan-ksp.list` instead of `ksp-ckan.list`, which may trip up some people.

**Comment by amedee** [comment]
Confirmation that the new key works.

**Comment by BrettRyland** [comment]
Maybe, or maybe I had just renamed it at some point for some unknown reason... :-)
