### ISSUE TITLE
after removing BDArmory, it still said i had it and BDArmoryForRunwayProject, and there was an error

### ISSUE THREAD

**Issue by jesuschristgithub** [KSP-CKAN/CKAN#3735]
Background
----------
* Operating System: Windows 11
* CKAN Version: VKAN v1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
I added some mods files from curseforge, then deleted them, other than that, no.

Problem
-------
**Describe the bug**
After removing BDArmory it said i had a few extensions and BDArmory, and they werent compatible, so now my mods wont work.

**Steps to reproduce**
* Go to... BDArmory
* Click on... Install
* See error

**Expected behavior**
Upon downloading mods for KSP 1.12.4, it will no longer work.

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Did you remove it with CKAN, or by deleting files?
