### ISSUE TITLE
[Bug] Briefly summarize your issue here

### ISSUE THREAD

**Issue by NovaRaptorTV** [KSP-CKAN/CKAN#3736]
Background
----------
* Operating System: Windows 11 Home
* CKAN Version: V1.31.2
* KSP Version: 1.12.4.3187

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Windows is not recognizing CKAN when you type it into the windows search bar after installation

**Steps to reproduce**
* Go to...windows start
* Type...ckan.exe
* See error

**Expected behavior**
Ckan.exe should pop up as the first result. However, it does not show up as an application

**Screenshots (if applicable)**

**CKAN error code (if applicable):**

```
PLACE CODE HERE !
```

**Comment by HebaruSan** [comment]
Yeah, that's not something we try to do. Just double click on the file you downloaded.
