### ISSUE TITLE
DLCs wont work.

### ISSUE THREAD

**Issue by intScalezzOS** [KSP-CKAN/CKAN#3742]
So, I am trying to install this modpack and I have the two DLCs Breaking Ground and Making History, but when I try and download this modpack it tells me that CKAN cannot install Making History for me, despite me having it. Is there anyway I can fix this?

**Comment by intScalezzOS** [comment]
I don't know how to reproduce this, the best I can do is downloading a modpack (linked here: https://www.reddit.com/r/martincitopants/comments/o0mrav/this_is_our_lords_ksp_modpack/) and when I load it, it just tells me that CKAN cannot install Making History for me.

**Comment by HebaruSan** [comment]
Just edit the .ckan file and delete this:

```json
        {
            "name": "MakingHistory-DLC"
        },
```

Then you'll be able to install it.
