### ISSUE TITLE
[Bug] CKAN may not work for users without IPv6 access

### ISSUE THREAD

**Issue by unquietwiki** [KSP-CKAN/CKAN#3751]
### Observation

![CKAN_Spacedock_IPv6_IPv4](https://user-images.githubusercontent.com/1007551/209451338-78e6a37a-f6f6-49c1-b97d-86f0e05cd5af.png)

So for the past month or so, I've had unreliable access to CKAN mods. This lines up with the time I haven't had reliable IPv6 access: Starry doesn't support it (yet), so I was using Route48.org until it stopped working for me. Last night, I got a Hurricane Electric tunnel going, and my CKAN build from #3749 just pulled a bunch of content. [SpaceDock is hosted in Germany](https://dnschecker.org/ip-whois-lookup.php?query=95.217.59.158) on a 250ms latency to Los Angeles; my experience with IPv6 over the years suggests it's been more resilient on long-distance network use.

### Possible solutions

- Regional mirrors of SpaceDock, done with volunteers.
- SpaceDock can set up a CDN, or someone can volunteer to set one up for CKAN/SpaceDock.
- Encourage users of CKAN to enable IPv6 via ISP, Hurricane Electric, Route48.org, or VPN-based method.

**Comment by HebaruSan** [comment]
I only have IPv4 at home and CKAN works fine for me.

**Comment by unquietwiki** [comment]
> I only have IPv4 at home and CKAN works fine for me.

Starry's been a bit weird lately with peering; particularly after they laid off half the staff. I'm lead mod on r/ipv6: seeing something like this doesn't surprise me.

**Comment by HebaruSan** [comment]
What is "Starry"?

**Comment by unquietwiki** [comment]
> What is "Starry"?

[It's a WISP](https://starry.com/) here in LA, NYC, and some other metro areas; LA has a few other WISPs too. My IT background has shown anything past 200ms latency gets really wonky, and IPv6 traffic is on newer backbones and simpler packets. IPv4 runs into weird MTU issues that drop packets.

**Comment by HebaruSan** [comment]
Does the "W" stand for "wireless"? If so, then yes, wireless downloads do tend to be pretty crap.

**Comment by unquietwiki** [comment]
> 

Yeah, Wireless. They usually use what's called "Air Fiber" to link to multipoint drops on high-rises and mountainsides. I get 200/200mbit vs 200-400/25 on cable here.

**Comment by unquietwiki** [comment]
@HebaruSan I brought up the situation on the SpaceDock Discord, since if they can fix it, then there really is no issue "here", except any workaround suggestions. Thank you for indulging me on this.
