### ISSUE TITLE
[Bug] Unknown issue

### ISSUE THREAD

**Issue by rocketsboi** [KSP-CKAN/CKAN#3753]
Background
----------
* Operating System: idk
* CKAN Version: v1.30.2
* KSP Version: 1.12.4

i havent made any changes. to my gamedata folder

Problem
-------
i am deleting the mod, but it says it is not installed

**Steps to reproduce**
* install 73 mods
* delete the mods
* See error

it should say a certain mod is not installed

**Comment by HebaruSan** [comment]
- When you say "delete the mods", are you uninstalling via CKAN, or deleting files yourself?
- What error are you seeing?

**Comment by rocketsboi** [comment]
ckan

**Comment by HebaruSan** [comment]
What's the error?

**Comment by rocketsboi** [comment]
oh wait nvm they just auto deinstalled lol

**Comment by HebaruSan** [comment]
Cool.
