### ISSUE TITLE
[Bug] Microsoft Defender SmartScreen and ckan.exe

### ISSUE THREAD

**Issue by Puggoz** [KSP-CKAN/CKAN#3758]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.0
* KSP Version: 1.12

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes, but no, I have copied the game file from my original folder, which already had CurseForge mods, but I deleted all of the gamedata and also the the new folder was outside of steam's folder

Problem
-------
**Describe the bug**
Microsoft Defender SmartScreen is saying that CKAN is an unrecognized app (possibly a virus)
When pressed more info it said something around the following and nothing else:
File: ckan.exe
Publisher: Unknown Publisher

**Steps to reproduce**
Want mod only on ckan (or is too complicated to download manually)
Follow this video: https://www.youtube.com/watch?v=slN1QA92RD4
Download CKAN
Open file in ksp folder

Screenshot
------------

user-images.githubusercontent.com/112920706/211181174-4d28edec-e4f8-4a25-a4a5-582ec5648aad.png

user-images.githubusercontent.com/112920706/211181323-d5182c2c-d05b-4bb6-b4d6-3708aaeb688a.png

**Comment by HebaruSan** [comment]
Thanks. CKAN isn't a virus, so your virus scanner is malfunctioning. Some of them have ways to report this so they can fix their database.

**Comment by Puggoz** [comment]
> Thanks. CKAN isn't a virus, so your virus scanner is malfunctioning. Some of them have ways to report this so they can fix their database.

I think it is only from the publisher not being clear, is that supposed to happen
Meaning you guys haven't put who published it in the download file
Like if you open steam on some update and it says, "would you like Steam to access your computer" or something like that, and it also says, "publisher: Valve Corp." My problem is that if you guys included the publisher, that is a problem
