### ISSUE TITLE
[Bug] Repository update failed, failed to roll back after loading download counts

### ISSUE THREAD

**Issue by teostrom1** [KSP-CKAN/CKAN#3763]
## Background

* Operating System: Windows
* CKAN Version: v1.31.2
* KSP Version: 1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

## Problem

heres the entire log from start to finish: 

```
Scanning for DLCs and manually installed modules...
Updating repositories...
Refreshing game version data
Downloading "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz"
Loading modules from default repository...
Loaded download counts from default repository
Repository update failed!
Failed to roll back.
```

**Describe the bug**
basically repository update failed then failed to roll back.

**Steps to reproduce**
* for me i just installed it by following a guide

**Expected behavior**
normal startup i guess

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/122676687/212470987-31fe901f-b256-4691-9197-a85d1c78109e.png)

**Comment by HebaruSan** [comment]
That's printed here:

https://github.com/KSP-CKAN/CKAN/blob/8390a617db167e79255ed0da2a8416e3cb3b8e4c/GUI/Main/MainRepo.cs#L172-L177

"Failed to roll back" is the `Message` property of the exception, and "Repository update failed!" is just the generic description printed before that. They don't reflect two things that happen in sequence, but the general and specific messages for one event.

**Comment by HebaruSan** [comment]
"Failed to roll back" unfortunately is probably not the original problem, since rolling back is not part of the normal update process. Some other exception was thrown, then in response to that CKAN tried to roll back, which failed, and _that_ is the message we see.

**Comment by HebaruSan** [comment]
#3890 is trying to improve the "Failed to roll back" error messages, so we should at least have a clearer idea of what is happening here in the next release.
