### ISSUE TITLE
It says Installation error for a mod I don't want to install.

### ISSUE THREAD

**Issue by Robenmaster** [KSP-CKAN/CKAN#3764]
I have selected a few mods and try loading it, everything works until it gets to kethane, it says kethane is corrupted or uninstalled, but I never tried to install kethane and its not in the list of mods im trying to download, I cant find kethane anywhere in the mod list so i don't know why its not letting me launch. 
![image](https://user-images.githubusercontent.com/122828759/212756191-a5639fae-b3e1-4aec-9edc-e8d9fce1fc01.png)
![image](https://user-images.githubusercontent.com/122828759/212756213-26682606-7c47-4e59-89fa-c7536eabb3e4.png)

**Comment by linuxgurugamer** [comment]
What other mods are you trying to install?
It's probably being pulled in as a dependency

**Comment by linuxgurugamer** [comment]
Looks like the Kethane download is bad

**Comment by Robenmaster** [comment]
I checked the list of mods that it wants to download with all the dependancy ones and i cant find kethane anywhere

**Comment by linuxgurugamer** [comment]
@HebaruSan Just an FYI, I was able to download a good copy from the link on the web page:  http://taniwha.org/~bill/Kethane-0.11.0.zip
which looks like the same URL that CKAN is using

**Comment by linuxgurugamer** [comment]
@Robenmaster Are you trying to install ExtraplanetaryLaunchpads?

**Comment by Robenmaster** [comment]
yep
i just noticed it a second ago

**Comment by linuxgurugamer** [comment]
Kethane is a recommended mod for EPL, you need to unselect it when installing if you don't want Kethane

**Comment by Robenmaster** [comment]
Thank you

**Comment by HebaruSan** [comment]
Kethane 0.11.0 was indexed successfully in July 2022, and recently has an inflation error on the status page:

http://status.ksp-ckan.space/

```
http://taniwha.org/~bill/Kethane-0.11.0.zip is not a valid ZIP file: Error in step EntryData for GameData/Kethane/Parts/kethane_smallDrill/model000.mbm: Exception during test - 'Unexpected EOF'
```
