### ISSUE TITLE
[Bug] Unknown problem during download

### ISSUE THREAD

**Issue by Alice20030309** [KSP-CKAN/CKAN#3765]
Background
----------
* Operating System: 
版本	Windows 10 专业版
版本号	22H2
安装日期	‎2022/‎5/‎24
操作系统内部版本	19045.2486
体验	Windows Feature Experience Pack 120.2212.4190.0

* CKAN Version: 1.31.2
* KSP Version: 1.12.2.3167

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**

Problem
-------
**Describe the bug**
can not add rss and bda

**Steps to reproduce**
* Go to...
* Click on...
* See error[捕获](https://user-images.githubusercontent.com/66291389/212812685-2e1ec0e2-79aa-4f86-8593-c75d0dc90ebd.PNG)

**Expected behavior**

**Screenshots (if applicable)**
![捕获](https://user-images.githubusercontent.com/66291389/212812685-2e1ec0e2-79aa-4f86-8593-c75d0dc90ebd.PNG)

**Comment by HebaruSan** [comment]
Actually, contrary to my updated title, I wonder whether this is actually the SpaceDock URL timing out when accessed from China, since it doesn't say that download finished.

@Alice20030309, are you able to load that mod's info page normally in a browser from your computer?

- <https://spacedock.info/mod/2487/BDArmory%20Plus>

**Comment by Fierce-Cat** [comment]
Whoops! This problem is related to my CKAN accelerator service in China, our CDN may perform gzip compression right after pulling the MOD of Github, resulting in verification failure.
Please open an issue ticket at KerbCat Git website, so we can address this problem further.

**Comment by HebaruSan** [comment]
> Please open an issue ticket at KerbCat Git website

You'll probably have more success with that request if you share a link with it.

**Comment by Fierce-Cat** [comment]
> You'll probably have more success with that request if you share a link with it, and @-tag the person who has experienced the issue.

Thank you HebaruSan, comment updated ^_^

**Comment by HebaruSan** [comment]
Thanks! Where is the bug report link on that site? I see "Explore", "Help", and "Sign In" across the top, and "Easy to install", "Cross-platform", "Lightweight," and "Open source" below. None of those are clearly bug-related. With some GitHub experience I would probably start poking around under the "Open Source" section, but most users trying to report a bug probably would give up.

**Comment by Fierce-Cat** [comment]
You are right, I have changed the link to the Issue page. Thank you for your advice again :)

**Comment by HebaruSan** [comment]
Thanks again! I've added a note at the top of our bug report template to hopefully send folks your way if they end up here initially:

![image](https://user-images.githubusercontent.com/1559108/224407495-295ea602-31ab-4442-ba70-9e7bcfa6dfc2.png)
