### ISSUE TITLE
Multiple threads validating same download simultaneously after one was cancelled

### ISSUE THREAD

**Issue by Retr0r0cket** [KSP-CKAN/CKAN#3777]
Background
----------
* Operating System: Windows 11 21H2 w/ all updates as of 2/16/2023
* CKAN Version: 1.31.2
* KSP Version: 1.12.5 on steam

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
No

Problem
-------
**Describe the bug**
Initially while installing a set of mods Parallax Stock textures refused to validate for a few minutes (it was the last package that needed to validate), so I cancelled the install and restarted it.

When installing Parallax Stock Textures again (last package to validate again), got this error message upon validation alongside the validation completion bar going back and forth rapidly:

NOTE: It says IO error because another process was accessing the folder, but no process was accessing the folder at the time that I'm aware of other than CKAN itself.

```
Unhandled exception:
System.IO.IOException: The process cannot access the file 'C:\Users\danny\AppData\Local\CKAN\downloads\downloading\E4B2C9E4-Parallax-StockTextures-2.0.0.zip' because it is being used by another process.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.File.InternalDelete(String path, Boolean checkHost)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
   at CKAN.NetAsyncDownloader.FileDownloadComplete(Int32 index, Exception error, Boolean canceled, String etag)
   at CKAN.NetAsyncDownloader.<>c__DisplayClass20_0.<DownloadModule>b__1(Object sender, AsyncCompletedEventArgs args, String etag)
   at System.Net.WebClient.OnDownloadFileCompleted(AsyncCompletedEventArgs e)
   at CKAN.ResumingWebClient.OnOpenReadCompleted(OpenReadCompletedEventArgs e)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch() 
```

**Steps to reproduce**
1. Attempt to download Parallax Stock Textures and wait for validation
2. Have it not validate and cancel install
3. Attempt install again 

**Expected behavior**
Would validate package and install as normal

**Comment by HebaruSan** [comment]
Check your antivirus. Often when a file is mysteriously being accessed, that turns out to be the culprit.

**Comment by Retr0r0cket** [comment]
I don't have any antivirus software installed.

**Comment by HebaruSan** [comment]
You mentioned "the validation completion bar going back and forth rapidly", which sounds a bit like there were two downloads in parallel for this file. Did you maybe start one and then try again?

**Comment by Retr0r0cket** [comment]
Yeah I did because initially it wasn't validating at all so I cancelled the install and then attempted to do it again.

**Comment by HebaruSan** [comment]
OK, can you please add that to the description so we can understand the problem without reading all the comments? That would explain it. One thread tried to delete the file while another is still downloading it.

**Comment by Retr0r0cket** [comment]
Will do right now, apologies for forgetting about that.

**Comment by HebaruSan** [comment]
OK, I wasn't sure about this, but checking the code, it turns out that the validation step doesn't support cancellation (because we're mostly calling into third-party code that also doesn't support cancellation). So for now, don't try to cancel it and/or don't expect that to work.

**Comment by HebaruSan** [comment]
`HashAlgorithm.ComputeHash` does seem to support cancellation, so we can look into adding that. Need to make sure it also works with the `IProgress<long>` notifier, though; that whole parameter seems to be missing from the documentation.

https://learn.microsoft.com/en-us/dotnet/api/system.security.cryptography.hashalgorithm.computehashasync?view=net-7.0&viewFallbackFrom=netframework-4.7.2#system-security-cryptography-hashalgorithm-computehashasync(system-io-stream-system-threading-cancellationtoken)

**Comment by HebaruSan** [comment]
@Retr0r0cket, thanks for the report. You can try a test build with a probable fix in the Artifacts dropdown here:

https://github.com/KSP-CKAN/CKAN/pull/3778/checks
