### ISSUE TITLE
[Bug] Instead of quitting on Ctrl-Q, CKAN quits on Ctrl-a, making "Select all" unavailable in the search field

### ISSUE THREAD

**Issue by JuhaJGamer** [KSP-CKAN/CKAN#3779]
Background
----------
* Operating System: `Linux odin 6.1.11-arch1-1 #1 SMP PREEMPT_DYNAMIC Thu, 09 Feb 2023 20:06:08 +0000 x86_64 GNU/Linux
`
* CKAN Version: ckan 1.31.2-1 as per pacman
* KSP Version: Irrelevant, but 1.12.5

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Deleted the CKAN and GameData folders some time ago and verified files through Steam as a reset. Other than that, no.

Problem
-------
The "File" menu describes Exit as having the hotkey Ctrl-Q. This does nothing. However, Ctrl-A kills CKAN. 

As the nosy idiot I am, I looked around a bit to see if I could find a fix and just PR it, but I couldn't.
The designer file does seem to suggest that it really should be Ctrl-Q. The latest change to that file is a good six years ago. If it's any help, I'm using the fi-kotoistus qwerty keyboard layout. This could very well be a one-off "only on my machine" or a bug in the AUR package. However, the AUR package does not contain any patches and its source tarball matches the repository.  If it's a mono-specific issue, I use `mono 6.12.0.177-1` and `mono-msbuild 16.10.1.xamarinxplat.2021.05.26.14.00-4`.

**Steps to reproduce**
* Open CKAN
* Press Ctrl-Q, noting that the application does not close
* Press Ctrl-A

**Expected behavior**
CKAN should close on Ctrl-Q, not Ctrl-A.

**Screenshots (if applicable)**
N/A

**CKAN error code (if applicable):**
N/A

**Comment by HebaruSan** [comment]
I just tried it, and ctrl-Q does still work, so it's something weird with your system. Please let us know if you figure it out; closing because we almost certainly will not be able to.

**Comment by JuhaJGamer** [comment]
Thanks for trying it out, I have absolutely no clue why it does this on my system then. Reinstalling doesn't seem to help. It's not very critical so I won't spend much time on it, and it clearly affects nobody else.

**Comment by Commander07** [comment]
I am experiencing this bug too using version 1.36.0 from nixpkgs.

**Comment by HebaruSan** [comment]
Hi @Commander07, same response for you then—please let us know if you are able to identify the cause!
