### ISSUE TITLE
[Bug] some specific mods don't show up in the mod selection screen

### ISSUE THREAD

**Issue by rhysdh540** [KSP-CKAN/CKAN#3783]
Background
----------
* Operating System: macOS
* CKAN Version: 1.31.2
* KSP Version: 1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
no

Problem
-------
**Describe the bug**
some mods that SpaceDock says are on CKAN (ex: Scatterer, Stock Waterfall Effects, Throttle Controlled Avionics) don't show up. I have no filters on.

**Steps to reproduce**
* open ckan
* attempt to find mod
* fail

**Expected behavior**
the mods should show up

**Screenshots (if applicable)**

<img width="1041" alt="image" src="https://user-images.githubusercontent.com/98863820/220108855-072ad7b8-bca8-43ba-aee7-a0b2045ef64b.png"> (scatterer should be here)

**CKAN error code (if applicable):**

**Comment by HebaruSan** [comment]
https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions-1
