### ISSUE TITLE
[Bug] Cannot connect to github to download CKAN-meta-master.tar.gz; download times out.

### ISSUE THREAD

**Issue by s-daveb** [KSP-CKAN/CKAN#3784]
Background
----------
* Operating System: endeavourOS 22.12 (Linux Kernel 6.1.12-arch1-1)
* CKAN Version: 1.31.2-1
* KSP Version: 1.12.5.3190
* Network: Machine has assigned IPv4 and a **SLAAC-allocated IPv6 address.**

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
- No.

Problem
-------
Cannot download latest module metadata from https://github.com. 
The GUI simply says the download timed out.  The consoleui displays the following:
```
The operation has timed out. at CKAN. NetAsyncDownloader.DownloadAndWait (System.Collections.Generic. ICollection '1[T] targets) [0x0036a] in <16566a61d4784adfbf04b40389f9fa>:0 at CKAN. Repo. UpdateAl1Repositories (CAN.RegistryManager registry_manager, CAN. GameInstance ksp, CKAN.NetAsyncDownloader downloader, CAN. NetModuleCache cache, CAN. IUser user) [0x000f3] in <16566a61d4784adfbf04b4038e9f9fa>: 0
at CAN. ConsoleUI.ModListScreen+<>c__DisplayClass11_0.<UpdateRegistry>b__0 (CKAN.ConsoleUI.Toolkit.ConsoleTheme th) [0x800a6] in <16566a61d4784adfbf04b48e389f9fa>: 0
```

**Steps to reproduce**
* Open CKAN
* It should try to get the latest module metadata
* Download times out

**Expected behavior**
* The download should show progress and then complete.

**Screenshots (if applicable)**
![Screenshot 2023-02-20 at 11 51 02 AM](https://user-images.githubusercontent.com/2100425/220165503-7079821a-ed53-4186-95e7-baa8b22f2248.png)

The same download succeeding in FireFox:
![Screenshot 2023-02-20 at 11 53 00 AM](https://user-images.githubusercontent.com/2100425/220165752-b92649a6-f291-4584-88fd-f5af28a1cda4.png)

Something interesting of note - when I try to `wget` the URL for the `master.tar.gz` file, I get a similar timeout. 
```
wget https: //github.com/KSP-CKAN/CKAN-meta/archive/master. tar.gz
--2023-02-20 11:51:59- - https: //github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz
Loaded CA certificate 'etc/ssl/certs/ca-certificates.crt'
Resolving github.com (github.com) ... 140.82.114.4
Connecting to github.com (github.com) |140.82.114.41:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/KSP-CKAN/CKAN-meta/tar.gz/refs/heads/master [following]
--2023-02-20 11:51:59-- https://codeload.github.com/KSP-CKAN/CKAN-meta/tar.gz/refs/heads/master
Resolving codeload.github.com codeload.github.com)... 64:ff9b: :8052:718a, 140.82.113.9
Connecting to codeload.github.com (codeload.github.com) |64:ff9b::8c52:710al:443.
```

**CKAN error code (if applicable):**
```
The operation has timed out. at CKAN. NetAsyncDownloader.DownloadAndWait (System.Collections.Generic. ICollection '1[T] targets) [0x0036a] in <16566a61d4784adfbf04b40389f9fa>:0 at CKAN. Repo. UpdateAl1Repositories (CAN.RegistryManager registry_manager, CAN. GameInstance ksp, CKAN.NetAsyncDownloader downloader, CAN. NetModuleCache cache, CAN. IUser user) [0x000f3] in <16566a61d4784adfbf04b4038e9f9fa>: 0
at CAN. ConsoleUI.ModListScreen+<>c__DisplayClass11_0.<UpdateRegistry>b__0 (CKAN.ConsoleUI.Toolkit.ConsoleTheme th) [0x800a6] in <16566a61d4784adfbf04b48e389f9fa>: 0
```
--- 

Is anyone else seeing this faulty behavior?   At first, I thought maybe github is rejecting the CKAN client's user-agent, but I've recently learned github has horrible IPv6 support, where I can't even clone a repository on an ipv6-only host.  

However, my machine has both an IPv6 *and* Ipv4 interface.    

Could this be a CKAN bug? I'll retry the download after disabling IPv6 and wi

**Comment by HebaruSan** [comment]
If `wget` has the same issue, then it's something between your computer/network and GitHub, not something CKAN can fix. Please let us know if you figure it out so we can advise other users having the same issue.

**Comment by s-daveb** [comment]
@HebaruSan   I figured it out.   I disabled ipv6 on the host that runs ckan, and I was able to download updates.   In my case, the issue was with my DNS resolver, returning the ipv6 endpoint for github.  

That being said, knowing that Github has terrible IPv6 support, would it be possible for CKAN to set up its TCP/HTTP connection using a flag forcing it to use the ipv4 endpoint?
