### ISSUE TITLE
how to clear the downloads cache Mac OS 

### ISSUE THREAD

**Issue by Rhycecomley** [KSP-CKAN/CKAN#3785]
Hey,
wondering if someone can help me, no matter what I do I cannot seem to clear the ckan cache. I did some messing about and now it won't run so I want to do a fresh install so that I can install them fresh again. 
can't seem to see it anywhere in the CKan mono screen

Any help would be greatly appreciated, Cheers

**Comment by HebaruSan** [comment]
I don't think the ConsoleUI has that. But before we mark this as a feature request to add it, can you explain why you think you need it? It's not clear that it would actually help with a problem like "it won't run" as you describe.

**Comment by Rhycecomley** [comment]
hi, 
so basically, I used to run ckan fine etc, and then I installed the new volumetric clouds and then I started messing with my mods, cut a long story short I want to do a fresh install but for some reason, whenever I start CKAN and start adding mods, it says they are coming from cache and then when I run there is still errors. 

basically I want to do a clean install of both ksp and ckan and start again.

Im sorry if I have been unclear, hope this clear it up?

**Comment by Rhycecomley** [comment]
I doing know if ive joust not explained myself properly, and there Is actually a way and im just being stupid. sorry

**Comment by Rhycecomley** [comment]
I have followed the instructions for a clean install but I still get mods installed from cache and I do not want them to do that. I tried reinstalling but that didn't fix either

**Comment by Rhycecomley** [comment]
![Screenshot 2023-02-20 at 20 44 54](https://user-images.githubusercontent.com/119439599/220195946-b3558cbc-abda-4836-bf3e-dadd99cbd17f.png)
like how do I clear the cache that these mods are downloaded in so I can start fresh

**Comment by HebaruSan** [comment]
Thanks, I think I understand. It looks like clearing the cache would not actually help you. All that means is that the ZIP files for those mods are saved in a folder so they don't have to be re-downloaded when installing. If you do re-download them, you'll get the exact same ZIP files again and they'll work exactly the same way. As far as I can tell, there's no indication here that there's anything wrong with the files in your cache.

**Comment by Rhycecomley** [comment]
ohhhh okay, its strange as I tried to install 1 mod and remove another and now the b9partswitch doesn't work with any installed mods not the new combination or old, so I assumed a fresh install of both ksp/ckan/mods might fix

**Comment by HebaruSan** [comment]
Well, if you want to do a fresh install, installing mods from cached downloads should be fine for that.

**Comment by Rhycecomley** [comment]
ahh okay no problem thanks for you help!!
