### ISSUE TITLE
Upgrade build to work with dotnet@6 or dotnet@7

### ISSUE THREAD

**Issue by chenrui333** [KSP-CKAN/CKAN#3787]
It looks like the project still builds with dotnet@5

https://github.com/KSP-CKAN/CKAN/blob/04034c000817d8159c02be96229797c6f2373144/.github/workflows/build.yml#L105

And it is to note that dotnet@5 has already [EOL on May 10 2022](https://learn.microsoft.com/en-us/lifecycle/products/microsoft-net-and-net-core), so it might be better to upgrade to use dotnet@6 or dotnet@7

**Comment by HebaruSan** [comment]
Yeah, we know. Thanks, but we don't really need an open issue to track this.
