### ISSUE TITLE
[Bug] CKAN crashes when select to install

### ISSUE THREAD

**Issue by deboi238** [KSP-CKAN/CKAN#3788]
Background
----------
* Operating System: Windows 10 
* CKAN Version: 1.31.2
* KSP Version: Latest

Problem
-------
**When ever i select any mod within install in ckan, it keep crashes even if i reinstall KSP and ckan**

**Steps to reproduce**
* Go to... Ckan
* Click on... install box
* See error... CKAN crashes/freezes

**Expected behavior**
CKAN freezes/crash

**Comment by deboi238** [comment]
i also cant do anything since it keep crashes

**Comment by HebaruSan** [comment]
We'll need much more information for us to investigate.

When you say it crashes or freezes, what does it look like? Is there a message? Can you share a screenshot?

**Comment by deboi238** [comment]
@HebaruSan it just freeze up CKAN and windows says want to close this window with a option wait until respond or close window

**Comment by HebaruSan** [comment]
Duplicate of #3707

**Comment by HebaruSan** [comment]
Cool, thanks, that sounds like #3707. You can try the dev build to see if it helps.

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe>

**Comment by deboi238** [comment]
it works thanks
