### ISSUE TITLE
[Feature] Add support for KSP2

### ISSUE THREAD

**Issue by sundhaug92** [KSP-CKAN/CKAN#3791]
Problem
-------
KSP2 just came into early access, and it's going to need a mod-manager. CKAN is best positioned to fit that position.

Suggestions
-----------
That a JSON key is added that specifies if the mod is for KSP1 or 2. This could either be adding a key that just outright says it, or making `ksp_version` optional and adding an optional `ksp2_version`

**Comment by HebaruSan** [comment]
Duplicate of #2863
