### ISSUE TITLE
[Bug] Errors when trying to build on macOS Catalina

### ISSUE THREAD

**Issue by rob5408** [KSP-CKAN/CKAN#3792]
Background
----------
* Operating System: macOS Catalina
* CKAN Version: master branch, [#04034c00](https://github.com/KSP-CKAN/CKAN/commit/04034c000817d8159c02be96229797c6f2373144)
* KSP Version: NA

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
**Describe the bug**
I was hoping to help solve [this issue](https://github.com/KSP-CKAN/CKAN/issues/3768) that I am also encountering. When trying to build on my Mac I am getting build errors. I read [building.md](https://github.com/KSP-CKAN/CKAN/blob/master/doc/building.md) and tried the build script `% ./build Ckan` or `% ./build osx`. 

```
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(17,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(21,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(25,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(29,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(33,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
~/CKAN/GUI/Controls/ModInfoTabs/Relationships.cs(37,51): error CS0234: The type or namespace name 'Resources' does not exist in the namespace 'CKAN.GUI.Properties' (are you missing an assembly reference?) [~/CKAN/GUI/CKAN-GUI.csproj]
```

I develop for tons of different platforms, but C#/Visual Studio is pretty alien to me so I'm pretty confident it is my setup. Be gentle!

**Expected behavior**
Was hoping for a ckan.exe in the _build/ directory.

**Comment by HebaruSan** [comment]
Can you try just `./build` ? The `Ckan` target is used internally by the build, and `osx` is just for the packaging. It'll probably be the same, but it would still eliminate one source of variance from the norm.

Thanks for trying this out on a Mac!

**Comment by HebaruSan** [comment]
If it helps you figure it out, `CKAN.GUI.Properties.Resources` is defined here:

https://github.com/KSP-CKAN/CKAN/blob/04034c000817d8159c02be96229797c6f2373144/GUI/Properties/Resources.Designer.cs#L11-L25

**Comment by rob5408** [comment]
@HebaruSan same thing when running just `./build`. I did write a lil C# for a Unity project ... 8 years ago. Let's see if I remember anything.

**Comment by rob5408** [comment]
Weird, `CKAN/GUI/Properties/Resources.Designer.cs` is completely empty for me.

**Comment by HebaruSan** [comment]
Oh wait, I forgot that Mono's WinForms doesn't work on Catalina anyway, because it's 32 bit only. I don't actually know whether that affects compiling it on a Mac, but I wouldn't be surprised, so it's probably better to not try to build the GUI.

... but I don't see any easy way to do that. Looks like nobody has worked all the way through building on a Mac before in the current state. You might have to edit the `.sln` and `build.cake` to remove the GUI parts:

https://github.com/KSP-CKAN/CKAN/blob/04034c000817d8159c02be96229797c6f2373144/CKAN.sln#L14-L15

https://github.com/KSP-CKAN/CKAN/blob/04034c000817d8159c02be96229797c6f2373144/build.cake#L267

> Weird, `CKAN/GUI/Properties/Resources.Designer.cs` is completely empty for me.

That alarming. Can you revert the file back to what it is in the git repo?

**Comment by HebaruSan** [comment]
It might be easier to spin up a Linux VM and build there, and just test it on the Mac.

**Comment by rob5408** [comment]
I was actually hoping I could just build the exe without the disk space check and just swap it into the bundle. I am full of bad ideas.

**Comment by HebaruSan** [comment]
Well that might be close enough to what we'd have to do anyway depending on the details (wrap it in a `if (!Platform.IsMac) {}` check).

**Comment by rob5408** [comment]
Up to 87 errors now. All still related to CKAN-GUI.csproj. I must be missing a reference somewhere.

**Comment by HebaruSan** [comment]
> Up to 87 errors now. All still related to CKAN-GUI.csproj. I must be missing a reference somewhere.

Yeah, see above comment, don't try to compile the GUI.

I'm not 100% certain, but I _think_ this is Mono's `GetDrives` implementation for Unix:

https://github.com/mono/mono/blob/5d2e3bc3b3c8184d35b2f7801e88d96470d367c4/mcs/class/Mono.Posix/Mono.Unix/UnixDriveInfo.cs#L142-L167

**Comment by rob5408** [comment]
I removed the lines you suggested for not building the GUI, but still had the build errors referencing it. Getting closer to firing up that VM. I also have an older Mac

**Comment by HebaruSan** [comment]
Taking a closer look, CmdLine references GUI (because CmdLine is the overall app entrypoint and it needs to be able to start up the GUI), and that's much harder to get rid of than just those other few lines. So I take back the suggestion to not compile the GUI.

**Comment by rob5408** [comment]
I have four Macs and every single one has Catalina :(

**Comment by HebaruSan** [comment]
Maybe you could build a small toy application in Mono to print the return value of `DriveInfo.GetDrives()`. That should be a lot easier than figuring out for example what is overwriting some of our source files.

**Comment by rob5408** [comment]
I'll try it out a lil later. Gotta jet now. Thanks so much!

**Comment by HebaruSan** [comment]
@rob5408, if you come back to this, please let us know and we can re-open it. Closing to avoid accumulating inactive stuff in the issues list.
