### ISSUE TITLE
[Feature] Install the mods while downloading others

### ISSUE THREAD

**Issue by Impre-visible** [KSP-CKAN/CKAN#3793]
Problem
-------
I'm always frustrated when I have to wait for all my mods to be downloaded to finally install them

Suggestions
-----------
Is that possible to, while you're downloading all the mods, the downloaded on are installing and the not installed are downloading?

**Comment by HebaruSan** [comment]
- <https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.concurrentqueue-1?view=netframework-4.8>
- <https://learn.microsoft.com/en-us/dotnet/api/system.collections.concurrent.blockingcollection-1?view=netframework-4.8>
