### ISSUE TITLE
[Bug] CKAN will not open at all

### ISSUE THREAD

**Issue by guyontheinternet2000** [KSP-CKAN/CKAN#3795]
Background
----------
* Operating System: macOS 10.13.6
* CKAN Version: 1.13.2
* KSP Version: 1.12.3

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
Yes

Problem
-------
**Describe the bug**
I have downloaded both Mono and CKAN and have tried to open it, but nothing comes up. Not even the UI. It just keeps loading and loading.

**Steps to reproduce**
* Go to Applications folder
* Click on CKAN app
* Wait for it to load

**Expected behavior**
It actually opens and starts doing stuff

**Comment by HebaruSan** [comment]
Are you on a Mac?

**Comment by guyontheinternet2000** [comment]
Yes! Sorry, I forgot to add that

**Comment by guyontheinternet2000** [comment]
Yes, I'm on Mac and yes I have Terminal

**Comment by johnaustin1995** [comment]
I am having the same issue.

### Background

Operating System: macOS 13.3.1
CKAN Version: 1.32.0
KSP Version: 1.12.5

Have you made any manual changes to your GameData folder (i.e., not via CKAN)?
No

### Describe the bug
CKAN quit working. I have redownloaded CKAN and have tried to open it, but nothing comes up. Not even the UI. It just keeps trying to open, but quitting immediately..

**Comment by HebaruSan** [comment]
What about Mono, is Mono installed? I know it was mentioned in the original description, but it only said "downloaded", and it has to be installed as well.

https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-macOS

**Comment by guyontheinternet2000** [comment]
Mono is installed

**Comment by Kokonico** [comment]
what computer are you using? M1? M2? Intel?

**Comment by Lambdanaut** [comment]
Just wanted to say, same experience here. Running on an Apple M3 Max with 128GB of memory on Sequoia 15.1.1.
