### ISSUE TITLE
[Bug] MacOS Ventura: Cannot open CKAN at all, because f2 accept types Q in the textfield instead

### ISSUE THREAD

**Issue by Tony1324** [KSP-CKAN/CKAN#3796]
Background
----------
* Operating System: MacOS 13
* CKAN Version: 1.31.2 console ui

Problem
-------
When launching CKAN, first page prompts to add game instance, where it says press f2 to accept, pressing f2 types Q into textfield. f1 types P, f3 types R. 

I'm pretty certain this is because I can't unfocus the text field where the name and path is supposed to be entered, the same thing happens in another terminal ui like vim.

**Comment by HebaruSan** [comment]
No, F2 works regardless of focus; the screen-level hotkeys take precedence over the text fields.
My guess is there's something off with your terminal config.

**Comment by Tony1324** [comment]
I tried both the default macOS Terminal and and iTerm, with and without my zshrc config (and bash), none work. I also used a keyboard tester to make sure the f2 key is actually pressed

**Comment by HebaruSan** [comment]
We've had Mac users using this successfully since 2017.

**Comment by Tony1324** [comment]
I remember I had CKAN working on my previous mac too, and the setup here is basically the exact same, so it's weird. Issue #3688 might be the same problem, but it's the f9 key and the plus key that don't work. Apparently it was fixed after waiting a few days, so I might just try that too.

**Comment by HebaruSan** [comment]
That issue didn't report any problems with F9; it said the F9 _hotkey tip didn't appear in the bottom bar_, which means there weren't any mods queued to be installed, supposedly because the <kbd>+</kbd> key wasn't working. But after I pointed out that you have to hold shift to avoid pressing <kbd>=</kbd> instead, it started working. Looked like a PEBCAK.

**Comment by Tony1324** [comment]
Just took a look at it today.

The command that launching the app runs goes to the directory where ckan.exe is
`cd "/Applications/KSP_osx/CKAN.app/Contents/MacOS"; "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" "ckan.exe" consoleui`

If i instead go to the KSP install folder and then pass in the path for ckan.exe to mono, the first screen is skipped.

`cd "/Applications/KSP_osx"; 
"/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" "CKAN.app/Contents/MacOS/ckan.exe" consoleui`

When focusing on the search text field, I can still press f10 and f9, however f1-f5 have the problem of typing into the text field.
