### ISSUE TITLE
[Bug] Cache path setting can be just a drive letter but it doesn't work

### ISSUE THREAD

**Issue by navuek** [KSP-CKAN/CKAN#3801]
Background
----------
* Win11
* CKAN Version: V1.31.2 
* KSP Version: V1.12.5.3190

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** No

Problem
-------
Installation fails every time for what ever mods used.

**Steps to reproduce**
It seems what causes the error during installation is changing the cache directory in the settings as shown in the picture:(Blue is before change, red after)
![image](https://user-images.githubusercontent.com/126896119/222924418-9da20021-9a40-446d-9f84-85cf6e5c6df2.png)
then i try to change the directory by just entering through the text box 
![image](https://user-images.githubusercontent.com/126896119/222924470-4057abe9-734b-46c9-85e2-7317da722b12.png)
at first it seems like it works, but do not be fooled, it's sneaky.
then after leaving and re-entering the settings page, this is what you get
![image](https://user-images.githubusercontent.com/126896119/222925438-a8fec581-600d-4b07-993a-914e0dd28cd2.png)
you can no longer edit the download cache location with the change button or any button.

then when attempting to install a mod an error will be out put as so:
Access to the path 'E:\System Volume Information' is denied.
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Be advised - if you first install a mod or two, then try to change the directory. it will all work as it should with no problems!**
**Expected behavior**
Installation succesful

![image](https://user-images.githubusercontent.com/126896119/222763190-e3d99388-2243-41d1-b4d8-128747476930.png)
[CKAN DOWNLOAD CACHE EDIT FAILURE.txt](https://github.com/KSP-CKAN/CKAN/files/10889497/CKAN.DOWNLOAD.CACHE.EDIT.FAILURE.txt)

**Comment by navuek** [comment]
I just reinstalled KSP into another drive, and put CKAN into the same drive F.
 And i still get the error attempting to find system volume information of drive E. something is bugged here.
![image](https://user-images.githubusercontent.com/126896119/222828192-4adc2d1d-bd76-410e-be1f-b51740062f55.png)

**Comment by HebaruSan** [comment]
Is your download folder configured to use the E: drive?

**Comment by navuek** [comment]
Yes i have an E drive, The old cache folder was in the E drive but now i can't even change it, the Directory stays blank like so no matter how many times i change it and to what drive i change it
![image](https://user-images.githubusercontent.com/126896119/222829764-6c698e04-52df-4b88-9d98-59718f45fd0f.png)

**Comment by HebaruSan** [comment]
Does the "Change..." button do anything?

**Comment by navuek** [comment]
Yes it open the 'browse for folder window' and the window works, but it stays blank after i click OK
![image](https://user-images.githubusercontent.com/126896119/222830008-73b267f9-caa0-4dbf-ab4b-4a10d6e749bb.png)
Reset does nothing, it remains blank

**Comment by navuek** [comment]
Wilco

**Comment by HebaruSan** [comment]
(The "N files, M MB" string is a placeholder that's supposed to be overwritten with real info about your cache folder, so something's stopping it from getting to that point.)

**Comment by HebaruSan** [comment]
That error means that folder does **not** contain ckan.exe, unfortunately. Maybe double check it?

**Comment by navuek** [comment]
Now it's running! 
give me a moment

**Comment by navuek** [comment]
When trying to input a new directory the CMD doesn't react at all, no change, no new lines
some lines were added when the install failed however.  so I added below the entire output of the cmd
[CKAN INSTALL FAILURE.txt](https://github.com/KSP-CKAN/CKAN/files/10886183/CKAN.INSTALL.FAILURE.txt)

**Comment by navuek** [comment]
When i don't mess with the directory of the cache and reach that weird state where the line is empty, the installations just work
i just managed to install the kerbal engineer and testing it now

it seems that any change to the cache directory bricks the program, but resetting it completely by deleting the CKAN localdata folder and reinstalling KSP fixes it
atleast letting me use the CKAN

**Comment by navuek** [comment]
edited to reflect the problem seems to stem from changing the download cache location

**Comment by navuek** [comment]
Here is the json config file:
{
  "AutoStartInstance": null,
  "DownloadCacheDir": "E:",
  "CacheSizeLimit": null,
  "RefreshRate": null,
  "Language": "en-US",
  "GameInstances": [
    {
      "Name": "Kerbal Space Program",
      "Path": "F:/SteamLibrary/steamapps/common/Kerbal Space Program",
      "Game": "KSP"
    }
  ],
  "AuthTokens": {},
  "GlobalInstallFilters": []
}
