### ISSUE TITLE
[Bug] CKAN freezes on checking updates

### ISSUE THREAD

**Issue by buba56** [KSP-CKAN/CKAN#3802]
Background
----------
* Operating System: Windows 10
* CKAN Version: 1.31.2
* KSP Version: 1.12.5

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?**
NO

Problem
-------

I have a problem with installing CKAN. When I open CKAN.exe , CKAN opens, a window about automatic update checking appears, after that the update check begins and CKAN completely freezes at this point. Because of this, I can't normally run the program and do anything in it. I completely reinstalled KSP and CKAN, but CKAN still freezes and does not respond on checking for updates.

Screenshots 

![image](https://user-images.githubusercontent.com/127053791/222985595-a999a2f7-46e3-42e1-8144-8b494a41aba8.png)

**Comment by buba56** [comment]
btw, its freezes always on Downloading "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz". I tried to open this link, and this doesn't open, maybe because I'm from Russia, because when i open this link with VPN its opened and file goes downloading to my pc. Maybe problem related to this.

**Comment by buba56** [comment]
okay, i solved this problem by myself. CKAN really freezes because CKAN can't download archive from link. I opened C:\Windows\System32\drivers\etc\hosts, and in file hosts i delete ip addresses of hundreds random sites and delete unnecessary spaces. After this archive normally downloads and CKAN is working.

**Comment by alphaleadership** [comment]
nope i forgot to disable the proxy before the proxy suhtdown

**Comment by alphaleadership** [comment]
is not a real issue

**Comment by BONDARENKOLEG** [comment]
Still an issue

**Comment by HebaruSan** [comment]
@BONDARENKOLEG, if you are seeing this issue, read the previous comments and check your system for malware.
