### ISSUE TITLE
[Bug] Ampersands doubled in mod grid on Windows

### ISSUE THREAD

**Issue by GreenKeldeo** [KSP-CKAN/CKAN#3806]
Background
----------
* Operating System: Windows 10 Home
* CKAN Version: 1.31.2
* KSP Version: N/A; Metadata bug

**Have you made any manual changes to your GameData folder (i.e., not via CKAN)?** Yes

Problem
-------
**Describe the bug:** Crew R and R mod (CrewQueueTwo) has 2 &s in its name on CKAN 

**Steps to reproduce:** Open CKAN
* Search "Crew R"
* Read name field for Crew R&R mod

**Expected behavior**
Text matches mod name

**Screenshots (if applicable)**
![image](https://user-images.githubusercontent.com/37720445/224451597-e64c2462-922a-4314-b6d8-7e1bec8827be.png)

**CKAN error code (if applicable):** N/A

**Comment by HebaruSan** [comment]
These calls to `Replace` probably need to be wrapped in `if (Platform.IsMono)`:

https://github.com/KSP-CKAN/CKAN/blob/2d387d91a3e9ba49b0778ff08012828dcf0d82bf/GUI/Model/ModList.cs#L376-L377

https://github.com/KSP-CKAN/CKAN/blob/2d387d91a3e9ba49b0778ff08012828dcf0d82bf/GUI/Model/ModList.cs#L406
