### ISSUE TITLE
macOS Ventura, Path not found

### ISSUE THREAD

**Issue by vintheruler1** [KSP-CKAN/CKAN#3812]
So im trying to install CKAN on my Mac running Ventura, I put the correct path, dragged and dropped the name, everything, nothing works.
<img width="556" alt="Screenshot 2023-03-11 at 6 48 27 PM" src="https://user-images.githubusercontent.com/83379181/224516627-de008c83-f443-4a95-bdcc-e57000f1dc43.png">

<img width="379" alt="Screenshot 2023-03-11 at 6 47 50 PM" src="https://user-images.githubusercontent.com/83379181/224516618-991a7807-1a64-40a5-9311-857212040498.png">
ec5c91b-3fca-4af2-9a5d-f1554cb86dcb.png">

**Comment by HebaruSan** [comment]
What's in that folder? Last time I saw this it was because the wrong folder was being selected.

**Comment by vintheruler1** [comment]
> What's in that folder? Last time I saw this it was because the wrong folder was being selected.
<img width="702" alt="Screenshot 2023-03-11 at 7 16 04 PM" src="https://user-images.githubusercontent.com/83379181/224517296-a74b567f-a5ba-4fd3-96fe-8c7ea3997004.png">

**Comment by HebaruSan** [comment]
Yeah, the message is correct that's not a valid game folder.
You're looking for a folder that contains a folder called `GameData`.

**Comment by vintheruler1** [comment]
> Yeah, the message is correct, that's not a valid game folder.
> You're looking for a folder that contains a folder called `GameData`.

Ohhhh, that makes more sense. It worked. Tysm

**Comment by HebaruSan** [comment]
Glad you got it working!
