### ISSUE TITLE
[Bug]: Extraplanetary Launchpads (versions for 1.9.x) failing to install; CRC mismatch?

### ISSUE THREAD

**Issue by nan0bug00** [KSP-CKAN/CKAN#3818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 19045

### CKAN Version

1.31.2

### KSP Version

1.9.1

### Did you make manual changes?

Yes

### Describe the bug

CKAN is reporting that the zip file for Extraplanetary Launchpads v 6.99.1 and 6.99.0 are not valid zip files.  Could be happening for other versions as well, I only tested these two. 

Downloading the mod manually by going to the thread and following the directions there works fine, the zip file opens okay, contents appear as they should be.   I'm not entirely sure if this is a CKAN error or something on Taniwha's end, but in the interest of just spreading awareness I'm reporting it here as well as in the EL thread.  If the error is not a CKAN problem, disregard this report.

### Steps to reproduce

* Open a 1.9.1 instance in CKAN. 
* Set compatible version to 1.9
* Attempt to install Extraplanetary Launchpads.  Fail.  Attempt to install the previous version.
* See error

### Relevant log output

```shell
CKAN.InvalidModuleFileKraken: ExtraPlanetaryLaunchpads 6.99.1.0: C:\Users\nan0b\AppData\Local\CKAN\downloads\downloading\B7FBB4F8-ExtraPlanetaryLaunchpads-6.99.1.0.zip
is not a valid ZIP file: Error in step EntryData for ExtraplanetaryLaunchpads/Parts/LandingPad/LandingPad.mu: CRC mismatch
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
```

**Comment by nan0bug00** [comment]
Well, it appears that this was premature.  Opening the manually downloaded zip works.  Attempting to copy the files out of it into gamedata does not, and fails on LandingPad.mu, as the CKAN error so helpfully pointed out despite my failing to read past CRC mismatch.  Appears CKAN is doing exactly what it should do, sorry for wasting time.

**Comment by HebaruSan** [comment]
Yup, taniwha's server has been providing corrupted ZIP files for quite a while now, unfortunately. There's not much CKAN can do about this, but that mod's bugtracker is here:

- <https://github.com/taniwha/Extraplanetary-Launchpads/issues>
