### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by louden-preble** [KSP-CKAN/CKAN#3820]
### Problem

![image_2023-04-09_183943360](https://user-images.githubusercontent.com/124315802/230804480-4b976049-e01b-4163-ba76-b3d8909d269e.png)
as seen in the pic, the 3 mods are not compatible with one another.

### Suggestion

make an easier way to see what mods are conflicting, like when you right click them below download to cash or purge from cash add a button saying "conflicting mods" (if applicable) then that button sows you a window with a list said conflicting mods.

**Comment by HebaruSan** [comment]
The lower left part of the window shows messages for conflicts. I'm not sure why it's cut off in your screenshot.

**Comment by HebaruSan** [comment]
Also there's a Relationships tab on the right part of the screen that shows _all_ the relationships, conflicts plus everything else:

![image](https://user-images.githubusercontent.com/1559108/230805966-8be22964-b842-4ebf-b8c7-d13ea041de34.png)
