### ISSUE TITLE
[Bug]: Repeated "metadata has changed" messages

### ISSUE THREAD

**Issue by Silvia-Dragoness** [KSP-CKAN/CKAN#3825]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.32.0

### KSP Version

KSP2 v0.1.2.0

### Did you make manual changes?

No

### Describe the bug

![image](https://user-images.githubusercontent.com/98713909/232527154-72123b6d-ca7c-49d8-88d2-9ff041d6bdc8.png)

I periodically check for mod updates in CKAN throughout the day.  This message showed up a few days ago, and I clicked "yes" and reinstalled the mod.  Later that day, and a few times every day since, on subsequent mod list refreshes, the same message reappears for the same mod.

Initially reported in Discord; HebaruSan asked me to open an issue for it.

### Steps to reproduce

* Have CheatsMenu installed via CKAN on KSP2
* Periodically refresh mod list in CKAN

**Comment by HebaruSan** [comment]
Could you please share your `<game dir>/CKAN/registry.json` file? This contains all the data that CKAN checks to determine whether to show that popup, so it should give us some insights.

**Comment by HebaruSan** [comment]
OK, for the case I'm investigating, the `InstalledModule`'s `.Module` property is actually being passed to `ModuleInstaller.Upgrade`, so that's where the restored metadata comes from; it temporarily removes the object and then re-inserts the same object. That could also be what's happening in the OP, but that's not certain.

**Comment by HebaruSan** [comment]
Hi @Silvia-Dragoness, I made some code changes in #3828, where you can download a test build from the Checks tab's Artifacts dropdown. If you have a chance, please take it for a test drive to see if it seems to fix the problem. The popup should be gone completely, the update checkbox should show up for this mod, and updating it should perform the reinstall properly and make it stop bothering you.
