### ISSUE TITLE
[Bug]: CKAN Uninstalls Mods for KSP2 That Are Not Selected For Uninstall

### ISSUE THREAD

**Issue by Scarecrow-71** [KSP-CKAN/CKAN#3826]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.32.0

### KSP Version

0.1.2.0

### Did you make manual changes?

No

### Describe the bug

I have multiple mods installed for KSP2, but I wanted to add 2 new ones (K2-D2 and OAB Extensions), as well as checking the Auto-Update box for those mods I have installed.  Upon selecting Apply Changes, the 2 new mods were installed...and all existing mods were uninstalled.  So I went back through and reselected the mods I needed to have installed (which included both BepInEx and SpaceWarp)...and those were installed while K2-D2 and OAB were both uninstalled.  I had to uninstall everything and then select everything from scratch so that everything would be installed.

I'm not sure if Git supports youtube video for documentation, but I can replicate this and I will be more than happy to provide video to show what is happening if needed.  Find me on Discord or the Forums (Scarecrow71).

### Steps to reproduce

- Open CKAN as Administrator
- Filter for mods that are installed
- Check the box to Auto-Update any installed mods

ALSO

- Open CKAN as Administrator
- Filter for mods that are not installed
- Select one or more mods and apply changes

**Comment by Scarecrow-71** [comment]
Yep, that's what I meant.  Sorry; sometimes the words I use don't always match what people see or understand.

I'm uploading a video to YT right now showing what happens.  Although processing up to HD, link is:  https://youtu.be/FdTDU9rrBNM

**Comment by HebaruSan** [comment]
Thanks, and don't worry about uploading a video, there's no need for something that's working as intended.
Have a great day!
