### ISSUE TITLE
[Bug]: CKAN taking long time to validate downloaded mods.

### ISSUE THREAD

**Issue by asdewful** [KSP-CKAN/CKAN#3836]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.26.0

### Game Version

KSP 1, 1.12.5.3190

### Describe the bug

I have been downloading 70+ mods at once, its stuck at validating multiple.

### Steps to reproduce

Download over 20 mods, wait for something to freeze validating, happens with some small mods and mainly larger.

**Comment by HebaruSan** [comment]
Some KSP mods are >1GiB, and these can indeed take a long time to validate. Without more information, we have to assume that's what happened here.
