### ISSUE TITLE
[Feature]: Recommendations/Suggestions should be transitive; provide a way for mods to opt-out

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3838]
### Problem

If ModA depends on ModB and I only select to install ModA, I don't see any of ModB's recommendations or suggestions.  For example if I install a sweet IVA mod that depends on RasterPropMonitor-Core, I don't get the option to install all the other cool stuff that RPM supports.

In discord discussions, it was brought up that RO/RP-1 folks explicitly asked for this, because they have such a sprawling network of mods that the number of recommendations and suggestions would be overwhelming (and likely conflicting I don't doubt).

### Suggestion

Create a new property that would prevent a related mod from transitively including its recommendations/suggestions (i.e. the current behavior):

```yaml
depends:
  - name: ProceduralParts
    suppress_recommendations: true
 ```
Note this should probably also be available for recommendations, not just dependencies...but that would probably mean that you might have to go through the "recommend/suggest" cycle multiple times...or selecting a mod in that dialog could repopulate the dialog with new transitive suggestions/recommendations.

Once this property exists, it could be added to the RO/RP-1 mods so they retain the current behavior.  And then finally switch CKAN's default behavior to include the transitive relationships.

### Alternatives

The "audit recommendations" feature can also be used to address this issue but I think it's not very discoverable.

**Comment by HebaruSan** [comment]
> RO/RP-1 folks explicitly asked for this, because they have such a sprawling network of mods that the number of recommendations and suggestions would be overwhelming

Finally found the references for that in #8688:

https://github.com/KSP-CKAN/NetKAN/issues/8688#issuecomment-890599062

> One thing that bothers me is that you're putting substantial effort into maintaining recommendations and suggestions for RealismOverhaul and RealSolarSystem, which currently are just ignored if the user starts from RP-1. We should consider showing recommendations and suggestions for the entire initial change set. And possibly even for mods that are added later on via the various lists and prompts.

> You do show recs for the entire manual initial changeset, not for dep'd in mods. And I think that is 100% correct. Having thought about it a bunch since my original recs question (about RSS-Textures and RSS-CanaveralHD) I've come to the conclusion that it's much riskier to have the reqs of dependencies added automatically, because e.g. RO/RP-1 could depend on a mod, but that mod's use case is mostly in a stock setup and therefore recommends a bunch of mods that don't make sense for RO/RP-1. And being in the business of copying our recs across multiple mods is easier than passing around giant lists of Conflicts.

> I have these on a branch already, should be relatively simple to move them along. I'll leave out the full-change-set-recommendations change for now since it's, let's say, not universally popular at this point.
