### ISSUE TITLE
Support meta-packages

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#384]
A meta-package (to use the Debian term) is one with no files, but has relationships. We should support these.

We'll need to signal somehow that that we're not just doing a default install.

```
"spec_version" : "v1.2",
"package_type" : "meta",
...
```

The advantage of having a `package_type` over something like `metapackage: true` is that we can define additional package types in the future.

Suggestions for better names welcome. I haven't checked how Debian does this, but Debian doesn't exactly have our default install stanzas.

**Comment by Dazpoet** [comment]
We very much have metapackages as of CKAN 1.6.0 thanks to @Ippo343 and as such I'm closing this.
