### ISSUE TITLE
[Bug]: CKAN won't let me install any more mods

### ISSUE THREAD

**Issue by EliteBroccoli** [KSP-CKAN/CKAN#3846]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 Pro

### CKAN Version

V1.32.0

### Game Version

KSP 1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No, i did not do anything manually.

### Describe the bug

I tried to download FreeIVA along with many other mods and it didn't work, specifically i was trying to use IVA in a Command Pod, spent 30 minutes uninstalling and installing mods to try and fix it but it didn't work. I then just deleted all my mods and started from scratch, but after downloading 16 mods it doesn't work anymore. I can click on the checkmark and all but it doesn't give me the option to "Apply Changes"

### Steps to reproduce

https://github.com/KSP-CKAN/CKAN/assets/135456414/5aaa3200-3a35-4af1-99a3-5cc8606da64c

**Comment by TheRaveninGitHub** [comment]
Is it possible that a mod is conflicting with another?
