### ISSUE TITLE
[Bug]: Extraplanetary Launchpads downloads from the wrong website, and breaks the zip file

### ISSUE THREAD

**Issue by coolguyanciaa** [KSP-CKAN/CKAN#3855]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

v1.32.0

### Game Version

KSP 1 with both expansions, v1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Only ships and a manual install of Extraplanetary Launchpads after multiple attempts to download it through CKAN.

### Describe the bug

CKAN downloads the mod from taniwha.org and believes that the ZIP file is corrupted, proceeding to discard the mod and revert to the previous configuration.

I would expect the download to start and finish as normal, and install the mod correctly.

### Steps to reproduce

* Select Install on Extraplanetary Launchpads and apply the changes
* Proceed through suggested mods
* Download will fail, and the installation will be cancelled

### Relevant log output

```shell
About to install:

 * Extraplanetary Launchpads 6.99.3.0 (taniwha.org, 16.1 MiB)
 * Kerbal Attachment System 1.12 (cached)
 * Toolbar 1:1.8.1 (cached)
Downloading "http://taniwha.org/~bill/ExtraplanetaryLaunchpads_v6.99.3.zip"
Finished downloading ExtraPlanetaryLaunchpads 6.99.3.0, validating and storing to cache...
Trying to install ExtraPlanetaryLaunchpads 6.99.3.0, but it's not downloaded or download is corrupted
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose


--below is from a popup window--


CKAN.InvalidModuleFileKraken: ExtraPlanetaryLaunchpads 6.99.3.0: C:\Users\forer\AppData\Local\CKAN\downloads\downloading\5E0A4EB7-ExtraPlanetaryLaunchpads-6.99.3.0.zip is not a valid ZIP file: Error in step EntryData for ExtraplanetaryLaunchpads/Parts/LandingPad/LandingPad.mu: Exception during test - 'Unknown block type 6'
   at CKAN.NetModuleCache.Store(CkanModule module, String path, IProgress`1 progress, String description, Boolean move, CancellationToken cancelToken)
   at CKAN.NetAsyncModulesDownloader.ModuleDownloadComplete(Uri url, String filename, Exception error, String etag)
```

**Comment by HebaruSan** [comment]
That's the right web site, in fact the only place this mod is hosted.

<https://forum.kerbalspaceprogram.com/topic/54284-112-extraplanetary-launchpads-v6993/>

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/ec2f0961-2ad9-4389-8638-64d91c73d194)

And the server is broken and has been so for quite a while, unfortunately. See taniwha/Extraplanetary-Launchpads#202 taniwha/Extraplanetary-Launchpads#205.

**Comment by HebaruSan** [comment]
Duplicate of #3818
