### ISSUE TITLE
[Feature]: 

### ISSUE THREAD

**Issue by IMoud47** [KSP-CKAN/CKAN#3874]
### Problem

my eyes always hurt when I am using CKAN
I can't look at CKAN for 2 min

### Suggestion

please I beg you have a mercy and add a dark mode

### Alternatives

my eyes!!!!!!!

### Additional context

dark mode!!!!!!!

**Comment by HebaruSan** [comment]
Hi, thanks for the suggestion.

https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-Windows#dark-theme

**Comment by IMoud47** [comment]
> 

thanks!
