### ISSUE TITLE
[Bug]: running ckan.exe does nothing 

### ISSUE THREAD

**Issue by classictimmy** [KSP-CKAN/CKAN#3894]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 11

### CKAN Version

the newest

### Game Version

12.25

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

nope

### Describe the bug

i download CKAN.exe and when i run it it says im missing the app to run it, so it takes me to the microsoft store to download it, but the app dosent exist and CKAN dosnt tell me what it wants me to download so i cant fix it

### Steps to reproduce

click on ckan.exe and it does this

**Comment by HebaruSan** [comment]
Hi @classictimmy, thanks for the report. Can you please add a screenshot of whatever error message you're seeing? No "app" is needed to run CKAN, so it looks like something very out of the ordinary is happening on your PC.

**Comment by classictimmy** [comment]
![Screenshot 2023-08-26 085153](https://github.com/KSP-CKAN/CKAN/assets/143279533/d4a70592-2744-4513-bc5f-0fe117451881)
![Screenshot 2023-08-26 085225](https://github.com/KSP-CKAN/CKAN/assets/143279533/c801c9d2-aeb9-481a-8916-650a6a444bb2)
@HebaruSan hopefully this helps

**Comment by HebaruSan** [comment]
Hmm, that doesn't look like it has anything to do with CKAN. Maybe try searching the web for other users who've had similar problems with Windows?

**Comment by classictimmy** [comment]
ive already tried that, no one else is having this issue, or there not talking about it

**Comment by HebaruSan** [comment]
What did you search for? I'm getting promising results for "windows search for app in store".

**Comment by classictimmy** [comment]
windows 11 ksp ckan.exe not running telling me to go to the microsoft store but the store isn't showing anything
i tried this and im getting nothing noteworthy

**Comment by HebaruSan** [comment]
Yeah, that's not going to find anything because CKAN doesn't really have anything to do with it. You want to focus on Windows and the string on the screen. Try the search I mentioned above. ☝️

**Comment by classictimmy** [comment]
okay ill look hopefully this helps, thanks

**Comment by HebaruSan** [comment]
Sounds good, and good luck!
