### ISSUE TITLE
[Bug]: starts but it gets stuck on game instance screen 

### ISSUE THREAD

**Issue by classictimmy** [KSP-CKAN/CKAN#3895]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 11

### CKAN Version

the newest

### Game Version

12.25

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

nope

### Describe the bug

ckan.exe runs, it open ckan but now it has a manage game instance screen and when i try make a new game instance it does nothing, and when i try to close the manage game instances it crashes how do i fix this

### Steps to reproduce

start ckan, try to close the manage game instances screen

**Comment by HebaruSan** [comment]
Here's the user guide, good luck!

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#adding-game-folders

**Comment by classictimmy** [comment]
thanks
