### ISSUE TITLE
Debian 12 bookworm doesn't have liblog4net

### ISSUE THREAD

**Issue by MartinKurtz** [KSP-CKAN/CKAN#3896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Debian 12

### CKAN Version

None yet

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I did add some mods to the linux install of KSP, HOWEVER these mods were installed in a windows install via ckan

### Describe the bug

ckan fails to install, errors out due to a dependency which cannot simply be installed via apt

### Steps to reproduce

Get fresh debian 12 install
add ckan repo as described in the guide
apt update
apt install ckan

### Relevant log output

```
root@MartinPC:/home/martin/Downloads# apt install ckan
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 ckan : Depends: liblog4net1.2-cil but it is not installable
E: Unable to correct problems, you have held broken packages.
```

**Comment by HebaruSan** [comment]
Debian does seem to have this package:

https://packages.debian.org/search?searchon=names&keywords=liblog4net1.2-cil

Maybe your APT sources are messed up somehow?

**Comment by MartinKurtz** [comment]
I dont think so, this was a fresh install of debian 12 and i hadnt messed with the sources then

**Comment by HebaruSan** [comment]
What happens if you try this?

```
apt install liblog4net1.2-cil
```

**Comment by MartinKurtz** [comment]
apt install liblog4net1.2-cil fails, no installation candidate i think, i cant try it right now though. That was the first thing i tried

**Comment by HebaruSan** [comment]
Hi @MartinKurtz, can you try running the raw `ckan.exe` (rather than trying to install the .deb) to see if it works without this dependency? I think our build process might be repacking this dependency's DLL into the EXE, so if that works, we might be able to remove the dependency from the .deb.

- <https://github.com/KSP-CKAN/CKAN/releases/download/v1.33.2/ckan.exe>

**Comment by MartinKurtz** [comment]
The ckan.exe runs fine, but thats a windows file

**Comment by HebaruSan** [comment]
It's the same file that's in the `.deb` package, just without all the extras (e.g. launch script in `/usr/bin`, desktop entry, icon, man page,  etc.). Technically it's not strictly a Windows file, it's a .NET Framework file, which Mono can run.

**Comment by HebaruSan** [comment]
But if it runs fine, that's a good sign that we should be able to remove that dependency. Taking a look at a current `ckan.exe` with ILSpy, I see a bunch of `log4net` entries, which should mean that it is indeed being repacked in there.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1f2d72fb-92c6-439f-a2c4-e2f782a03228)
