### ISSUE TITLE
Downloads failed dialog doesn't appear

### ISSUE THREAD

**Issue by P1XZL** [KSP-CKAN/CKAN#3901]
Every time I try to start CKAN it keeps being stuck on the repositories. I have reinstalled ckan multiple times, even tried an older version and it still crashed. What do I do?
![image_2023-09-10_173546516](https://github.com/KSP-CKAN/CKAN/assets/94076564/f2b1d852-e650-4539-b915-c823f6990bb8)

**Comment by HebaruSan** [comment]
Sorry to be the bearer of bad news, but in previous cases of this the cause was that the user's PC was infected with crypto mining malware that changed the hosts file, see #3802 and #3814. But at least now you know and can clean it up!

**Comment by HebaruSan** [comment]
Although, now I'm curious what this is about:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/29a5b99e-fd54-419c-91fe-df2e6d2ebea5)

Did you add that repository yourself? If so, why and what is it for?

**Comment by P1XZL** [comment]
> 

I'm trying to just use the kerbal mod installer. Also, do you have any idea on how I could fix that malware issue and completely reset the ckan configs?

**Comment by HebaruSan** [comment]
@P1XZL, can you please answer this question?

> Did you add that repository yourself? If so, why and what is it for?

You may not have malware; that was my first guess before I squinted more closely at that screenshot and saw that weird repository.

You don't need to completely reset the CKAN configs. Just go to the settings and remove the extra repo.

**Comment by P1XZL** [comment]
> 

Sorry for that, yes I added the repository myself. I thought that was like a plugin for ckan. Btw I cannot access the settings because it keeps freezing.

**Comment by HebaruSan** [comment]
> Btw I cannot access the settings because it keeps freezing.

Ahh, I see. In that case you can reset that config by going to `<KSP folder>/CKAN` folder and deleting `registry.json`.

**Comment by P1XZL** [comment]
> 

I'll try that, thanks. I'll come back if something went wrong or not

**Comment by P1XZL** [comment]
Ay man, thanks. It works again! Now I can go bombard my gamedata folder with mods again

**Comment by P1XZL** [comment]
> 

Oh and something else completely, what is the best version for modding?

**Comment by HebaruSan** [comment]
This is just my personal opinion, but I would use 1.12.5 with a compatible version range of 1.10–1.12. Most mods released for that range still work.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions

**Comment by P1XZL** [comment]
> 

I'll try that, one thing tho, I use 1.11.1 now just to try and I see a lot of mods there that I never saw on ckan KSP version 1.12.5

**Comment by HebaruSan** [comment]
Yeah, if you click that link, it will tell you how to make those mods appear for 1.12.5 as well.

**Comment by HebaruSan** [comment]
... aaand there's also a bug here. It should be popping this up instead of freezing.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/5eacd9c6-00e3-4830-b1cc-1ecc6b70e8db)

Reopening to fix.
