### ISSUE TITLE
[Feature]: Managing mods (and saves, config, etc.) using symlinks

### ISSUE THREAD

**Issue by xsrvmy** [KSP-CKAN/CKAN#3905]
### Problem

Currently the simplest way to setup KSP is to create a new copy of the game and point CKAN to it. This duplicates the base game files which wastes space. Also, with the current unity situation going on, it's not clear if doing so would be tracked as an install. If it is, that is a problem, because doing so would cost the devs money while breaking the EULA.

### Suggestion

Instead of creating new copies for each mod pack, one instance of the game files is used, and symlinks are set up for the folders that are modified during gameplay (saves, ships, config files, etc.), and GameData would use nested symlinks for the Squad folder and the DLCs. When switching instances, these symlinks would then point to new folders.

### Alternatives

The symlink could be done the other way around, linking only the large files to save space. I used to do this when my disk space was limited. However probably does not solve the unity issue.

**Comment by HebaruSan** [comment]
That's a fine idea! I believe if you make symlinks instead of copying all the game files, CKAN would still be able to add the instance and install mods just fine. Give it a try!
