### ISSUE TITLE
Plugins cant be added

### ISSUE THREAD

**Issue by Lorange7** [KSP-CKAN/CKAN#3918]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.33.2

### Game Version

1.12.5.3190

### Describe the bug

Plugins cant be added, when linking the Dll it closes the file explorer page and doesnt add the dll.

### Steps to reproduce

attempt to add a plugin

**Comment by HebaruSan** [comment]
Hi @Lorange7, thanks for the report. What plugin are you trying to add?

**Comment by HebaruSan** [comment]
Checking @Lorange7's profile, every previous issue they've submitted to other projects was missing key information, which was never provided. Closing since that'll probably happen here.

https://github.com/issues?q=author%3ALorange7
