### ISSUE TITLE
[Feature]: An issue that affects the download experience

### ISSUE THREAD

**Issue by xmkxgepi** [KSP-CKAN/CKAN#3922]
### Problem

When downloading spacedock, the connection is slow, but it can be downloaded.  However, ckan will forcefully disconnect the download due to slow connection and use the unreachable Archive.org mirror, which is a very stupid design.

### Suggestion

Give this function a switch, or add multithreaded download function.

### Alternatives

Copy the download link of Spacedock to other download tools.

**Comment by linuxgurugamer** [comment]
Why do you say that archive.org is unreachable?

**Comment by xmkxgepi** [comment]
> Why do you say that archive.org is unreachable?

You know, there are some problems with the network in Chinese Mainland. I'm not likely to use a proxy to download things.

**Comment by HebaruSan** [comment]
The description is wrong, CKAN doesn't "forcefully disconnect" anything.
