### ISSUE TITLE
[Bug]: Error in autoupdate: The request was aborted: Could not create SSL/TLS secure channel. Fresh new install, lastest version

### ISSUE THREAD

**Issue by Bin-Ban** [KSP-CKAN/CKAN#3925]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.33.2 (latest)

### Game Version

1.12.5.3190

### Describe the bug

![image](https://github.com/KSP-CKAN/CKAN/assets/100521844/a0503622-2711-48db-a8f2-3406213603a0)

Ckan's attemp to connect to github/update repositories fails due to not being able to create a secure channel through STL/TLS

### Steps to reproduce

Open CKAN
Wait for repository update
Error message "Se ha terminado la conexión: No se puede establecer una relación de confianza para el canal seguro SSL/TLS." aka "Error in autoupdate: The request was aborted: Could not create SSL/TLS secure channel."

**Comment by HebaruSan** [comment]
Hey @Bin-Ban, if I had to guess, there's a decent chance you got infected by some crypto mining malware that's trying to block you from accessing certain GitHub-related URLs. Check your hosts file (see #3802 and #3814).

Maybe we should add a crypto mining malware question to the FAQ...

**Comment by Bin-Ban** [comment]
Performing full antivirus scan on the whole PC, checked host files and theres nothing in there. It does redirect to codeload which is something I dont understand if there's nothing in the hosts file. Could you please provide further help

**Comment by HebaruSan** [comment]
Are you able to access the repo URL with a browser, and if so, does it give you any warnings? Knowing that could help to narrow down the source of the problem:

- https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz

**Comment by Bin-Ban** [comment]
already decided to check that, it seems to be that my firewall is blocking it for some reason, maybe some windows 11 security update blocked it for whatever reason. Trying the same link with a vpn works and downloads the file. Using it without a vpn, redirects to codeload and then my internet provider blocks it.

**Comment by HebaruSan** [comment]
Ahh, glad you figured it out!
