### ISSUE TITLE
[Bug]: mod compatibility conflict  between two instances of the same version of CKAN and KSP

### ISSUE THREAD

**Issue by ctbram** [KSP-CKAN/CKAN#3926]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 10

### CKAN Version

1,33,2

### Games

KSP 1

### Game Version

1.12.3

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no manual changes were made to either

### Describe the bug

you can see both kvv and amp year are compatible in one managed 1.12.3 instance of KSP but not in another instance of KSP 1.12.3 managed under the same 1.33.2 CKAN instance???

### Steps to reproduce

installed a 3rd instance of a 1.12.3 KSP game and both mods were also not compatible according to CKAN.,  This are three managed instances of a KSP 1.12.3 installation in the same CKAN instance

That is all I could think of to try.  One instance both are available and in another they are not.

### Relevant log output

I did not see a log file in the CKAN directory of either instance of the game.

Not sure what to do.  I hate to have to manually add and maintain kvv and ampyear in some instances of the same version of the game and not others?

### Screenshots

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1eaeb10e-cfdc-43d5-8143-a3e0fd59c936)

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/35c6952c-522d-4be7-b9f1-48705878372c)

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/55c1c641-095f-41d8-a1f1-06f95426f9f1)

**Comment by HebaruSan** [comment]
Sounds like you may have different compatibility settings for the different instances. That's the first thing I'd check:

- https://github.com/KSP-CKAN/CKAN/wiki/User-guide#Choosing-compatible-game-versions
