### ISSUE TITLE
[Bug]: current dev version leaves TweakScale folder behind when uninstalling

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3936]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows 10

### CKAN Version

https://github.com/KSP-CKAN/CKAN/commit/5684cd65e1de1ff0a1c0d65786851ce2acfc7477

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

uninstalling tweakscale can leave folders behind in the dev build.  This does NOT occur on the current official release, 1.33.2

### Steps to reproduce

1. install tweakscale
2. run the game (I'm not sure if this step is required)
3. close the game
4. uninstall tweakscale with ckan

**Comment by HebaruSan** [comment]
I'm not able to reproduce this; my GameData is clean after the uninstall.
Do I have to load a save game? I loaded the main menu and then exited.

**Comment by JonnyOThan** [comment]
> I'm not able to reproduce this; my GameData is clean after the uninstall. Do I have to load a save game? I loaded the main menu and then exited.

Quite possibly, TweakScale creates a config.xml file inside its PluginData but that might not happen until the game is loaded.

**Comment by HebaruSan** [comment]
Thanks. After starting a save and launching to high suborbital, I see that file created:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1e300589-61a3-47a0-a987-ecea10fade6e)

**Comment by HebaruSan** [comment]
Probably related to #3890.

The unusual thing about this use case is that the mod is not only creating a file in a CKAN-created folder, it's creating a _folder_ in a CKAN-created folder and creating a file inside that. So the updated logic is probably not considering that possibility.
