### ISSUE TITLE
Could not create SSL/TLS secure channel

### ISSUE THREAD

**Issue by AYesRU** [KSP-CKAN/CKAN#3941]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11 23H2

### CKAN Version

1.33.2

### Games

KSP 2

### Game Version

0.1.5.0

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

 The request was aborted: Could not create SSL/TLS secure channel

### Steps to reproduce

When starting CKAN

### Relevant log output

Search for DLC and manually installed modules...
Updating repositories...
Refreshing game version data
Failed to update repositories!
Underlying connection closed: Trust could not be established for the SSL/TLS secure channel.

**Comment by HebaruSan** [comment]
Hi @AYesRU, there's a good chance you've been infected by some crypto malware. Check your hosts file (see #3802 and #3814).

**Comment by AYesRU** [comment]
> Hi @AYesRU, there's a good chance you've been infected by some crypto malware. Check your hosts file (see #3802 and #3814).

the host file is fine

**Comment by AYesRU** [comment]
costs nod32, checked ADWCleaner and CureIt

**Comment by HebaruSan** [comment]
OK, the next thing to check is your routers and firewalls. From the message you quoted, something is stopping CKAN from accessing one of these URLs:

- https://raw.githubusercontent.com/KSP-CKAN/KSP2-CKAN-meta/main/builds.json
- https://github.com/KSP-CKAN/KSP2-CKAN-meta/archive/main.tar.gz

If you can figure out what that is and fix it, then the repository update should succeed.

**Comment by AYesRU** [comment]
Got a blue screen. After rebooting and restoring, everything worked.
