### ISSUE TITLE
Conflict message in changeset flow needs to be more prominent

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3946]
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/d9a7f9bb-3eef-4e66-bc41-0f2f1ebd4b34)

I spent a while trying to figure out why I couldn't click "Continue" here.  At the very bottom left of the screen it explains the conflict, but it's very strange to show this on the recommend/suggest/support page (I guess it's here because this is where it checks all relationships).  

It would be way better to do it on the *previous* page and highlight conflicts in red or something, and not let you proceed from there:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/783ddfc1-735f-46d8-9218-f79415c15476)

**Comment by HebaruSan** [comment]
The changelog page **does** show conflicts. Or it's supposed to.

**Comment by HebaruSan** [comment]
🤣 
Workaround: Instead of clicking Apply, click the Changeset tab when it appears. The Apply button as it currently stands clears out the conflicts. 😡
