### ISSUE TITLE
SelectionBackColor of conflict rows should be a different color (dark red?)

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3947]
If you mark a mod to install that is in conflict (e.g. install Grannus and then Scatterer), you might not notice the red background of the conflict row because selected rows still use the default blue background color.

It should be possible to set the background color of selected conflict rows to a darker red:

https://learn.microsoft.com/en-us/dotnet/api/system.windows.forms.datagridviewrow.defaultcellstyle?view=windowsdesktop-8.0#system-windows-forms-datagridviewrow-defaultcellstyle

**Comment by HebaruSan** [comment]
What about blue+red=purple?
