### ISSUE TITLE
Only seeing two mods in mod list

### ISSUE THREAD

**Issue by 8800101160600999** [KSP-CKAN/CKAN#3949]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

win11

### CKAN Version

v1.34.0

### Games

KSP 1

### Game Version

1.12.5.3190

### Describe the bug

![E3C02256-B4EF-49fb-AF8C-1EE4B67D4095](https://github.com/KSP-CKAN/CKAN/assets/153432566/72eed3c4-e2fd-4628-8b9c-47cb082dbdc7)
我这里就只有两个mod,我不知道是不是我的问题,前阵子他的元数据库一直更新不了,这次更新之后,我把它重新安装了,但是这只有两个mod,刷新之后还是这样

### Steps to reproduce

重新下载完ckan后,我就打开他了,我一打开他,就只看见了两个mod

**Comment by HebaruSan** [comment]
Hi @8800101160600999, thanks for the report!

What are the two mods that you have? Knowing this could give us clues as to what's happening.
