### ISSUE TITLE
[Bug]: CKAN doesn't delete mods after i delete them manually

### ISSUE THREAD

**Issue by gamergab** [KSP-CKAN/CKAN#3954]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.0

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Deleted all the mods manually 

### Describe the bug

I expected CKAN to go through everything and delete them all as if nothing happened but it gives me error during installation for some reason.

### Steps to reproduce

1. Delete all mods manually, leaving only squad and squadexpansion folders in gamedata
2. go into ckan and uncheck all mods
3. press apply

**Comment by HebaruSan** [comment]
Hi @gamergab, please show us the error it gives you. Without that, we can't really do anything with this report.

**Comment by gamergab** [comment]
Here it is.

**Comment by HebaruSan** [comment]
Hi @gamergab, thanks for responding, but it looks like whatever you tried to send didn't come through. I think email attachments are not automatically posted into GitHub issues. So we'll still need the information about the error to get started here.

**Comment by gamergab** [comment]
![image_2023-12-14_142801335](https://github.com/KSP-CKAN/CKAN/assets/153859189/fc3e9351-fc01-436c-89b8-2838368d29b4)

**Comment by HebaruSan** [comment]
Noting this here because this possibility was absolutely considered during development of that error mesage:

https://learn.microsoft.com/en-us/dotnet/api/system.io.file.delete?view=netframework-4.8#remarks

> If the file to be deleted does not exist, no exception is thrown.

**Comment by gamergab** [comment]
Is there a fix for this? i reinstalled the game and ckan to no avail?

**Comment by HebaruSan** [comment]
Patient: Doctor, it hurts when I do this.
Doctor: Then don't do that!

For now the workaround is to not delete files manually.

**Comment by gamergab** [comment]
but how do i install mods with CKAN now if i can't uncheck the boxes?

**Comment by HebaruSan** [comment]
As a workaround, you could open the `<Game Root>/CKAN` folder and rename `registry.json` to something else (or delete it, but renaming is safer in case you want to recover the data). This will make CKAN forget everything that was installed.

Or you could wait a day or two for the next CKAN release that will have this fixed.
