### ISSUE TITLE
Trying to run CKAN as an administrator

### ISSUE THREAD

**Issue by mnh713** [KSP-CKAN/CKAN#3956]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 home

### CKAN Version

version before v. 1.33.2 update

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

After selecting update Ckan to v.1.33.2 from the Ckan main page. Ckan closed and no longer will open

### Steps to reproduce

removed Ckan from computer and re-download Ckan v. 1.33.2 and launch. Ckan still does not launch.

**Comment by HebaruSan** [comment]
Hi @mnh713, which version of .NET Framework do you have installed? 4.8 is required to run the latest CKAN release, so you'll need to update that if you haven't already.

**Comment by mnh713** [comment]
Yes I have v. 4.8

**Comment by HebaruSan** [comment]
OK. And when you say it will no longer open, is there an error message?

**Comment by mnh713** [comment]
No, after opening (launching) Ckan, the program launching window (looks
like a DOS window) then immediately closes. No error message is shown

**Comment by HebaruSan** [comment]
Hmm, are you comfortable working from the command line? We might be able to capture more information like this:

1. Start → run
2. cmd
3. `cd` to the folder where ckan.exe is
4. `ckan.exe --show-console`

That should cause the output from the terminal window to be shown in the window you opened. If any messages were printed before it was closed, it would remain visible instead of disappearing too quickly to read.

**Comment by mnh713** [comment]
Sure, I'll give it a try

**Comment by mnh713** [comment]
Okay, I had to use the --asroot--show-console

**Comment by HebaruSan** [comment]
Ahh, if you're running as administrator, can you try not doing that?

**Comment by mnh713** [comment]
Okay, I'll try again

**Comment by mnh713** [comment]
I typed (see attached),

**Comment by HebaruSan** [comment]
Hi @mnh713, attachments don't come through GitHub's email interface. Can you share what you found in some other way?

**Comment by mnh713** [comment]
I typed,

d:\SteamLibrary\steamapps\common\ckan.exe --show-console

The replay is "You are trying to run as CKAN as an administrator"

**Comment by HebaruSan** [comment]
Thanks. Do you have a non-administrator user on your PC that you could try this as?

**Comment by mnh713** [comment]
No, would need to create a non-administrative user, can try and do this now

**Comment by HebaruSan** [comment]
OK, sounds good.

For what it's worth, CKAN should not be run as an administrator, but if you must do that, the `--asroot` parameter will allow it.

**Comment by mnh713** [comment]
So it did not work in the user account I just made??? However I ran it back
on my original account using the --asroot

Ckan v1.34.0 is running

With the "manage game instances" window open over the the main clan window

**Comment by mnh713** [comment]
Should I proceed with the instructions given in the manage game instance
window "new game instant" ?

**Comment by mnh713** [comment]
So I proceeded ahead and CKAN is running with no lost to (mods). Ckan is
v1.34.0, KSP is v1.12.5.3190

Thank you for your help

Respectfully,

Marshall Hitt

**Comment by HebaruSan** [comment]
Glad you got it working!

**Comment by linuxgurugamer** [comment]
@HebaruSan I wonder if it's trying to read/write a protected file?  Maybe add some additional debugging statements around each attempted file access (try/catch) to be a bit more verbose?

**Comment by HebaruSan** [comment]
@linuxgurugamer  No, it's detecting that the user is an administrator, printing an error, and exiting.

**Comment by Armour9** [comment]
I am having this error as well.  I have uninstalled CKAN and have reinstalled it and I am getting the immediate popup and CKAN closes. When I did a quick screenshot is says because I am trying to run as Admin.  I have ensured "run as admin" is unchecked.  Now CKAN does not work at all.

**Comment by HebaruSan** [comment]
> I honestly have no idea what you mean by "try the --asroot parameter". I have googled it and nothing relevant came up. I am sure it is second nature to people that know about coding
> 
> How do I "try the --asroot parameter"?

Hi @Armour9, I'm replying here instead of on #3985 so other users who land on the original pinned issue can find it. Don't worry, it's nowhere near as complicated as coding! 😁 Here are some introductions to Windows shortcuts that show how you can set up command line parameters for use with programs:

- <https://www.digitalcitizen.life/shortcut-arguments-parameters-windows/>
- <https://www.bleepingcomputer.com/tutorials/understanding-command-line-arguments-and-how-to-use-them/>

In the case of CKAN, this is where you would put `--asroot`:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/f4b731a4-4641-4baf-852b-acfd12024594)

(This can also be done by typing in a `cmd` window, but shortcuts are the quickest way to get back into "click on icons" territory.)

**Q: But isn't that annoying? Why do I have to do that?**
A: Yes! Because you really should **not** run CKAN (or most other programs) as an administrator user! It removes important safeguards and gives a program far too much power to affect your computer. The `--asroot` flag is a solution for advanced users who understand the risks.

**Comment by QuackQuackZA** [comment]
So I just want to confirm, there is no way to run the app without administrator privileges? Did some googling and from what I understand is if the app doesn't have admin rights then it won't be able to read/write correctly and thus not work, i.e. running this app requires admin rights? If this is not the case, is it possible to strip the exe of privileges while still logged into the admin profile. 

I found a cmd line that allows you to run an exe as another user (preferably as one without admin rights) with the "/runas <user_name>" command line, but this still requires that the non-admin user profile exists on the PC. I don't want to do that. 

From what I see from the earlier "--asroot" flag post and mnh713's post that running it requires admin rights and exposing yourself to risk is unavoidable.

**Comment by HebaruSan** [comment]
@QuackQuackZA no, you've misunderstood. CKAN does not need admin privs, and you should not run CKAN as admin. The whole point of this check is to catch it when someone does that.

**Comment by QuackQuackZA** [comment]
Thanks. Is the only way to do it, to create another user on your PC?

**Comment by jayhawker6** [comment]
> Thanks. Is the only way to do it, to create another user on your PC?

You can run CKAN as a user with admin pillages and not give CKAN admin access easily! Windows UAC should be set up by default to ask you if you want to run it with admin when you try to (such as clicking "run as administrator") regardless of what account you are on. You can then click no, and it would not be given admin level access. This goes for most every program on your computer. The UAC window is the one that asks you if you want to allow [insert program here] to make changes to your computer. @QuackQuackZA. You can also run programs as admin from a non-admin account as if you don't have admin perms and UAC pops up, it instead has an input for the admin account's password, allowing you to grant admin perms as admin to a program while on someone else's account (this is required to install most programs). Hope this helps point people to the right search query to make next in the future.

**Comment by QQY021** [comment]
I have just downloaded CKAN yesterday and met the same issue. It is strange that there was no UAC popping up and I did not have any chance to deal with the problem before the notification of “You are trying to run CKAN as an administrator user." jumped out. I checked the properties of CKAN and made sure I did not run CKAN as an administrator user.

Is there any kind of method to deal with that?

**Comment by QQY021** [comment]
just want to add something up:
the game version is 1.12.5, CKAN version is Quasar 1.35.2, the game was installed 2 days before and I downloaded principia via Github. There were not any more changes done.
