### ISSUE TITLE
Adding new instances doesn't check for duplicates

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3959]
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/fe049e98-81e7-4e34-998c-2ca59e3259fb)

Initially I thought this was a case-sensitivity problem, but it seems like you can just add the same instance over and over.  I suspect that this can then cause issues in the registry (or at least, I heard a user report that they uninstalled a mod through CKAN and it wasn't actually uninstalled).

**Comment by HebaruSan** [comment]
As noted elsewhere, there is no way to check whether two path strings point to the same location due to things like network shares and symbolic links. I don't think we should write code pretending that we can do that, especially if we aren't sure that it causes a real problem.
