### ISSUE TITLE
Adding a new KSP1 instance should allow for selecting the ksp_x64 exe to reduce confusion

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3962]
This is especially bad because if you don't have file extensions enabled, the file filter dropdown only says "build metadata file" and doesn't tell you WHAT file it's looking for.

**Comment by HebaruSan** [comment]
It's because that file is only on Windows. On Linux:

```
~/.local/share/Steam/steamapps/common/Kerbal Space Program$ ls -gGh
-rwxrwxr-x  1 6.2K 2021-06-24 12:49 PM KSP.x86_64
```

**Comment by JonnyOThan** [comment]
Is there really no possible solution here?

**Comment by HebaruSan** [comment]
I guess we could still get the version info from buildID.txt but have the add-instance window prompt for something else.

Can you find somebody with KSP1 on Mac? The GUI doesn't run there anymore, but it might again someday if we get .NET7 figured out, and I can't remember whether GameData is inside or outside the KSP.app bundle.

**Comment by HebaruSan** [comment]
Found one on Discord#macos. `KSP.app` is the closest thing to `KSP_x64.exe`, but unfortunately an app bundle is a directory at the filesystem level, so the file selection prompt can't pick `KSP.app`.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/4140adab-a87e-4895-ae4b-dd4a24f5efbd)
