### ISSUE TITLE
[Bug]: "Audit recommendations" not working

### ISSUE THREAD

**Issue by zhangyuesai** [KSP-CKAN/CKAN#3987]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Windows 11 23H2 (22631.2861)

### CKAN Version

1.34.2

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No.

### Describe the bug

In previous versions of CKAN, the "Audit recommendations" feature would show me suggestions and recommendations based on my installed mods. But in the lastest version, nothing happens after I click on "Audit recommendations".

### Steps to reproduce

* Go to "File" menu
* Click on "Audit recommendations"
* Nothing happens

**Comment by HebaruSan** [comment]
Thanks for the report! There's a build with a fix here under the Artifacts dropdown if you'd like to test it out:

- https://github.com/KSP-CKAN/CKAN/pull/3988/checks
