### ISSUE TITLE
[Feature] Get game version from DLLs with Mono.Cecil

### ISSUE THREAD

**Issue by HebaruSan** [KSP-CKAN/CKAN#3990]
@cheese3660 made this suggestion in the context of how CKAN gets the version of a game instance, and I have not been able to forget about it:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/25b7b81c-393c-4cf5-af1a-377661f4c042)

Despite the tongue-sticking-out emoji at the end, this could be a quite good idea:

- It solves the problem of how to get the game version in a cross-platform way once `KSP2_x64.exe` is replaced by `KSP2.x86_64` on Linux and we can no longer rely on getting properties from a Windows EXE
- It doesn't require the KSP2 devs to add a separate `buildID.txt`-style file specifically for us that may or may not be kept accurate and up to date or have a convenient format
- It's probably the best "source of truth" for the info, given that they're not going to forget to update that part of the game DLL
- It could also be used for KSP1, replacing the cumbersome `IGameVersionProvider` / `KspBuildIdVersionProvider` / `KspReadmeVersionProvider` family of classes
- I already used Mono.Cecil in #3914, and it's a nice tool and distributed under an MIT license

**Comment by cheese3660** [comment]
Let me grab cecil and see if I can write a simple version of this as a test

**Comment by cheese3660** [comment]
```cs
using Mono.Cecil;

Console.Write("Assembly-CSharp Path: ");
var path = Console.ReadLine();
var assembly = AssemblyDefinition.ReadAssembly(path);
var type = assembly.Modules.SelectMany(x => x.GetTypes()).First(x => x.Name == "VersionID" && x.Fields.Any(y => y.Name == "VERSION_TEXT"));
var field = type.Fields.First(x => x.Name == "VERSION_TEXT");
var constant = field.Constant as string;
Console.WriteLine($"Version {constant}");
```
![image](https://github.com/KSP-CKAN/CKAN/assets/10365484/f2dec5c8-e75f-4a5d-843e-fe4af9e2c3f2)

**Comment by cheese3660** [comment]
Now let me see if KSP1 has a similar class

**Comment by cheese3660** [comment]
Okay, on inspection KSP1 does some wacky stuff with having a `Versioning` monobehaviour running somewhere that has the version set in its prefab likely, not really fetchable with Mono
