### ISSUE TITLE
(macOS) mono: bad cpu type

### ISSUE THREAD

**Issue by jepye-3141** [KSP-CKAN/CKAN#3995]
**System**: macOS Sonoma 14.2.1 | arm64

**Causes**: Trying to open CKAN; trying to run CKAN from the command line; trying to compile CKAN from source.

**Description**: CKAN.app does not open, or opens to a "bad cpu type" error code in the terminal.

**Solution**: Following the instructions on https://www.mono-project.com/docs/getting-started/install/mac/
1. Uninstall mono
2. Install the latest version of mono
3. Open CKAN.app
4. Success, hopefully.

_Best of luck._

**Comment by HebaruSan** [comment]
Yup, that's been the recommendation on the wiki and in the release notes for a long time now. Thanks!

- https://github.com/KSP-CKAN/CKAN/wiki/Installing-CKAN-on-macOS
- ![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/39bba2f5-d1f7-4ec8-a57a-901ac7845176)
