### ISSUE TITLE
After downloading and installing a mod for the first time, the "Contents" tab is not refreshed properly

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#3998]
I just installed Gold Standard (and it was not previously cached).  The contents tab was open when I installed it.  After installing it, the "download" button is still enabled and "Open ZIP" is not:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/e67b3202-6dc1-4fb0-bf0c-fb34266c18d7)

Further, clicking "download" DOES seem to download the mod again.

Swapping tabs doesn't refresh the panel, but clicking on some other mod and back again does.

**Comment by HebaruSan** [comment]
#1096 is similar and should be investigated along with this.
