### ISSUE TITLE
[Bug]: CKAN KSP2 time not counting towards Steam playtime

### ISSUE THREAD

**Issue by k0smonaut** [KSP-CKAN/CKAN#4003]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.4

### Games

KSP 2

### Game Version

0.2.0.0

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No manual changes.

### Describe the bug

Steam shows that I have a total of 46 hours in-game with 0.0 in the past 2 weeks. I am quite sure I have played well over 20 hours in just the last 2 weeks. I want to make sure my playtime is being counted so that the devs and Steam get accurate statistics. 

![image](https://github.com/KSP-CKAN/CKAN/assets/153154218/287e5070-77ef-4c5b-a00e-9341d16eb7b2)

I am signed into Steam when playing.
The game does **not** show as running in Steam when the game is running.
CKAN is pointed directly at the KSP2 install folder. 
This is the original, clean install folder and has not been copied or altered. 

Not only that, but CKAN counts over 90 hours in KSP2: 
![image](https://github.com/KSP-CKAN/CKAN/assets/153154218/931a5c1f-95f1-41a4-b311-d08987eb7132)

Is this because Steam launches the launcher executable, but CKAN launches the game executable?

*** UPDATE *** 
I used my critical thinking brain and launched the game executable directly from the install folder.
The same issue occurs. This is not necessarily a bug unique to CKAN but rather to Steam or the game and I'll be posting it on KSP's forums. Feel free to remove this or leave it for visibility. 

### Steps to reproduce

1. Install and configure CKAN.
2. Launch KSP2 
3. Observe whether Steam registers the launch of KSP2

**Comment by HebaruSan** [comment]
Right, this isn't a CKAN bug. Steam counts time when you launch through Steam.

To configure CKAN to launch through steam, you can set Settings → Game command line to:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/d6de366d-b5d0-4ac1-8d22-24d694ac1a3d)

**Comment by k0smonaut** [comment]
> Right, this isn't a CKAN bug. Steam counts time when you launch through Steam.
> 
> To configure CKAN to launch through steam, you can set Settings → Game command line to:
> 
> ![image](https://private-user-images.githubusercontent.com/1559108/297895225-d6de366d-b5d0-4ac1-8d22-24d694ac1a3d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU2MTkwNTAsIm5iZiI6MTcwNTYxODc1MCwicGF0aCI6Ii8xNTU5MTA4LzI5Nzg5NTIyNS1kNmRlMzY2ZC1iNWQwLTRhYzEtOGQyMi0yNGQ2OTRhYzFhM2QucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDExOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAxMThUMjI1OTEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YjJkZWYxNmUwOTQxODU0YmMxOWQ0NjI2MjMzY2E0ZTNjYjhhMWRkNmM2MWU2YjEyMWYyNjYwMjAyZTFmYzkxZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.6hqI2reS-IKkBDM4y2DSSCK7uJSOyLcJCLhju_I1PuA)

I appreciate your quick feedback and clear instructions. I would suggest that in future releases, this be clearly or more visibly disclosed upon initial deployment of CKAN, and that the fix be more easily integrated into the CKAN launcher (such as within the settings menu, which I did check before opening this topic). 

In other instances, I have observed Steam and other launchers detect when a game is running even when launched manually. I have also observed that other modloaders default to run-from-Steam behavior. I think is more intuitive and "expected" behavior.

**Comment by HebaruSan** [comment]
I can see how you'd think that, but it would be incorrect behavior to make this the default.
CKAN supports multiple game instances in different folders, but the `steam://` URL can only launch one instance, and there's no way for CKAN to know whether it's the right instance.

**Comment by k0smonaut** [comment]
> I can see how you'd think that, but it would be incorrect behavior to make this the default. CKAN supports multiple game instances in different folders, but the `steam://` URL can only launch one instance, and there's no way for CKAN to know whether it's the right instance.

Thanks for the clarity! Yes, that makes sense.

I stand by my suggestion to add a disclosure on initial CKAN deployment. 
I am surely not the only user for whom this is unanticipated behavior. 
I'm only now realizing that KSP1 is likely missing hundreds of hours of playtime on my Steam profile. 

Thanks for your hard work! I love CKAN and have used it extensively.
