### ISSUE TITLE
Recommendations should not be automatically selected for install if they conflict with already-installed mods

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4011]
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/47fc1503-25ad-4784-9d01-8773fbc2be0f)

It's cool that they're in the list, so you can be aware that there's something recommended you're not getting and why.  But they should just be unchecked by default.

**Comment by HebaruSan** [comment]
@JonnyOThan what is the conflict in the example so I can test this?
