### ISSUE TITLE
Relationships screen usability improvements

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4016]
As an alternative to #4015, we could significantly improve the usability of the recommendations/suggestions screen.

1. The "deselect all" checkbox should be moved to the top of the screen.  Many people never even realize it's there, because your attention tends to start at the top left and then move to the bottom right to click the "continue" button.
2. There could be additional buttons or checkboxes at the top of the screen for "select all recommendations," "select all suggestions," "select all supporting mods"
3. One or more of the following:
   * Mods with the hidden label should not be checked by default in recommendations
   * Mods with the hidden label should not be shown at all in relationships (I like this less, but it seems more consistent with the meaning of “hidden”)
   * The “held” label should make recommendations unchecked by default when applied when the mod isn’t installed
   * Some new label is introduced to enable this behavior (my least favorite option because it increases complexity and burden on users to understand what each label does)

The use case here is essentially someone who never wants to install a mod like Waterfall. Waterfall is recommended by many mods (justifiably), so it would be nice for this person to be able to express that desire once instead of every time they install a mod that recommends it.  The label system seems like a great fit there, without being quite so wide in scope as the idea in #4015 .  Perhaps this labeling idea should be split into its own issue.

**Comment by HebaruSan** [comment]
Part of the confusion is probably due to representing an **action** with a checkbox. If you want to _do something_, it's plausible that your eye would scan right past a UI element that usually represents _toggling_ a setting.

A toolbar across the top should be much clearer. Trying to imagine which buttons it would contain, I think we only need three actions:

- Uncheck all
- Check all
- Check recommendations

I don't think there's a general case where you'd want to install all suggestions without recommendations, since suggestions are even more tenuously related to the mods you picked. If you want all suggestions or all supported, you probably want everything.

**Comment by HebaruSan** [comment]
@JonnyOThan know anybody who can make us some nice toolbar button icons?

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1592c042-92d6-40a0-a0cc-dc44555feabd)

**Comment by JonnyOThan** [comment]
I don't think the checkbox is *terrible* as long as it changes state in response to actions in the list - like if all recommendations are checked, the "include recommendations" checkbox should be checked.  Then if you manually uncheck one, it should change state to "indeterminate" - I don't even know if OSs other than windows support that.  And if you uncheck all of them, it changes state to unchecked.  But I have nearly no preference one way or another for checkbox vs buttons.  Just that it's a little weird to have buttons that do opposite things when most of the time only one of them will have any effect (notably right when the window opens the first 2 buttons are probably viable, but "check recommendations" is a no-op).  You could disable the buttons that wouldn't do anything, just like the checkbox state.  But I can also understand if that complicates the UI code unnecessarily and the cost isn't worth the benefit.

**Comment by HebaruSan** [comment]
How should the buttons interact with the logic around leaving conflicts/held/hidden unchecked? Currently I'm taking the simplistic route of treating all unchecked mods the same (I have Bureaucracy in a Held label):

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/41226190-5da9-477f-9a57-caa9965312a3)
![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/3ecfd5e5-652a-49d7-8996-6c5aaafa76f3)

**Comment by JonnyOThan** [comment]
Works for me.
