### ISSUE TITLE
Access to config.json is denied

### ISSUE THREAD

**Issue by ericilvec** [KSP-CKAN/CKAN#4022]
this is the window that pops up when i try to run the .exe program
![screen](https://github.com/KSP-CKAN/CKAN/assets/142198291/94b0fa02-e88b-465a-aef5-b7227230ecba)

**Comment by HebaruSan** [comment]
Make sure you run ckan.exe as a user that can access that path.

**Comment by ericilvec** [comment]
i need it to access my b file not my c file that is where the game is installed

I am the only user and have admin privilege's

**Comment by HebaruSan** [comment]
Cool. So what you'll want to figure out is why your OS won't let CKAN write to the path in the error message.
