### ISSUE TITLE
Repository Update Failed: "Downloads failed" dialog does not appear when custom metadata repository goes missing and switching game instances

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4027]
I had set up a zip file with metadata for TweakScaleRescaled at https://github.com/JonnyOThan/TweakScale/raw/master/Docs/CKAN.zip

When TweakScaleRescaled finally got added to CKAN officially, I deleted the zip file.  In most cases I would have expected this dialog box to show up:

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/08121536-a36e-4856-a064-054750debaf0)

But a user on discord reported they saw this:
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/6ba617d3-ae79-456e-997f-97fe6d29bb7a)

And I just saw the same thing when switching to a game instance where the custom repository had been in use - just the error message, not the dialog about what you want to do.

In fact, if you just add `https://github.com/doesntexist` as a repository, you just get an error screen instead of the dialog asking what you want to do about it.

**Comment by HebaruSan** [comment]
From the description, this sounds suspiciously like 404s (server exists but doesn't have the URL we want) are being treated differently from other network errors (bad hostname, no server). Is there any info that contradicts that so far?

**Comment by JonnyOThan** [comment]
Right, that fits the observations.  But on the client side, I'd expect any failure to fetch the repository to pop up that dialog box.

I'm pretty sure I had tested CKAN's behavior when deleting the zip locally with `file:///` URIs when I initially set this up, to make sure it would do the right thing.  But either there's some difference in how that's handled or I didn't test it correctly.

**Comment by JonnyOThan** [comment]
Also note - I've replaced the TweakScaleRescaled zip file with an empty one so no one else will hit this in the short term.

**Comment by HebaruSan** [comment]
@JonnyOThan, I'm not able to reproduce this. I always see the Downloads Failed window.

Can you give specific steps that consistently produce the bad outcome?

**Comment by JonnyOThan** [comment]
@HebaruSan 

1. Launch CKAN
2. Select a game instance
3. Go to settings -> CKAN Settings
4. click "Add" under repositories
5. add an entry with the URL `https://github.com/doesntexist`
6. Close the settings window

Result:
![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/974a1cb3-ba93-42b6-82aa-a620d60ae6d6)

Note that it doesn't actually say 404 error there either.

**Comment by HebaruSan** [comment]
Right, that's because that isn't a 404 but rather a user's profile. Is that actually the same use case?

**Comment by JonnyOThan** [comment]
Hypothesis: around the time that this was actually happening, the *main* repository also had an update.  Perhaps that is a prerequisite for the issue of the dialog not appearing to occur - if ONE of the repository updates succeeds, does it stop the dialog from popping up if other ones do?

**Comment by HebaruSan** [comment]
> Hypothesis: around the time that this was actually happening, the _main_ repository also had an update. Perhaps that is a prerequisite for the issue of the dialog not appearing to occur - if ONE of the repository updates succeeds, does it stop the dialog from popping up if other updates fail?

Doesn't look like it. You can simulate that by shift-clicking the refresh button, and that still gives me the Downloads Failed dialog with a report of a 404.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/4160746e-31ee-456b-8b42-59ee09d928d5)

**Comment by HebaruSan** [comment]
What version of CKAN was the user on Discord using?

**Comment by JonnyOThan** [comment]
Huh.  Yeah, I'm unable to force that to happen again with a 404 error.  But I think the point still stands - any kind of failure should probably trigger the dialog.

> What version of CKAN was the user on Discord using?

I don't know, but I *do* know that I observed the same behavior when switching game instances on the dev build.  I didn't actually grab my own screen so I'm not sure if it was a 404 error, but the game instance that I was switching to had been pointed at the same jonnyothan/tweakscale metadata respository.

Hypothesis: is there a different behavior if the repository had EVER been successfully downloaded from that URL?  We're mostly trying contrived cases by creating URLs that don't exist, but in the *real* case the URL was valid at one point and then returned 404 (pedantic: that's probably not the correct status code...)

**Comment by HebaruSan** [comment]
That could be it. We retrieve the `ETag` header before the actual download to determine if there are any changes, and that probably doesn't occur if there isn't a locally cached etag to compare to. I'll see if I can mock up a test of that...

**Comment by HebaruSan** [comment]
... bingo!

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/2bc40729-8135-438b-9051-a83ba5ca89ae)

```
ERROR CKAN.GUI.Main - The remote server returned an error: (404) Not Found.
System.Net.WebException: The remote server returned an error: (404) Not Found.
   at System.Net.HttpWebRequest.GetResponse()
   at CKAN.Net.CurrentETag(Uri url)
   at CKAN.RepositoryDataManager.<>c__DisplayClass7_0.<Update>b__1(Repository r)
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at CKAN.RepositoryDataManager.Update(Repository[] repos, IGame game, Boolean skipETags, NetAsyncDownloader downloader, IUser user)
   at CKAN.GUI.Main.UpdateRepo(Object sender, DoWorkEventArgs e)
   at CKAN.GUI.Wait.DoWork(Object sender, DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.OnDoWork(DoWorkEventArgs e)
   at System.ComponentModel.BackgroundWorker.WorkerThreadStart(Object argument)
```

Required setup:

- Add a fake etag to `%LOCALAPPDATA%\CKAN\repos\etags.json`
- Add a fake repo file to `%LOCALAPPDATA%\CKAN\repos` with a name starting with the first 8 characters of the `sha1sum` of the repo URL
