### ISSUE TITLE
I get a error every time I olaunch ckan and have to give it permission to run on every launch

### ISSUE THREAD

**Issue by ctbram** [KSP-CKAN/CKAN#4032]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

win 10 edu

### CKAN Version

1.34.4

### Games

KSP 1, KSP 2

### Game Version

not sure the latest for both.

### Describe the bug

I get this on every launch ckan

CKAN requires permission to add a handler for ckan:// URLs.
Do you want to allow CKAN to do this? If you click no you won't see this message again.

### Steps to reproduce

just try and launch ckan. It takes a very long time to even launch and when it does I get that message!  Then get a popup from Windows to allow ckan to run from an unknown publisher.  I never had this message in the past and it just started popping up on the last update to 1.34.4

**Comment by HebaruSan** [comment]
Hi, thanks for the report. We know about this issue, and it has been fixed in #3996, which will be included in the next release.
