### ISSUE TITLE
[Bug]: Number must be either non-negative and less than or equal to Int32.MaxValue 

### ISSUE THREAD

**Issue by IgnIVertiKalCaD** [KSP-CKAN/CKAN#4036]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Linux

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

KSP v1.12.5

### Describe the bug

When you select and start CKAN, it crashes. I tried to try the Linux version, but it doesn't see ksp.exe

### Steps to reproduce

Run CKAN

### Relevant log output

```
System.ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.
Parameter name: timeout
at System.Threading.WaitHandle.WaitOne (System.TimeSpan timeout, System.Boolean exitContext) [0x00026] in <006aeda5450e44e2a7c0b3f3e62d74fd>:0
at System.Transactions.Transaction.DoPreparePhase () [0x00055] in <321ca8c1b88347dcb99ed658286b1b33>:0
at System.Transactions.Transaction.DoCommit () [0x00076] in <321ca8c1b88347dcb99ed658286b1b33>:0
at System.Transactions.Transaction.CommitInternal () [0x00022] in <321ca8c1b88347dcb99ed658286b1b33>:0
```

**Comment by IgnIVertiKalCaD** [comment]
![image](https://github.com/KSP-CKAN/CKAN/assets/54883747/a28f6323-8592-487f-91e5-21b98488d80e)
I tried the GUI/TUI version of CKAN for Linux, but it still doesn't see the game folder. I don't understand why this is the case at all

**Comment by HebaruSan** [comment]
Hi @IgnIVertiKalCaD, first, please always try the latest client before submitting an issue in case it's already been fixed:

- <https://github.com/KSP-CKAN/CKAN/releases/tag/v1.34.4>

Second, what do you mean by "I tried to try the Linux version, but it doesn't see ksp.exe"?

Third, for your consoleui screenshot, try it without backslashes.

**Comment by IgnIVertiKalCaD** [comment]
> Hi @IgnIVertiKalCaD, first, please always try the latest client before submitting an issue in case it's already been fixed:
> 
>     * https://github.com/KSP-CKAN/CKAN/releases/tag/v1.34.4
> 
> 
> Second, what do you mean by "I tried to try the Linux version, but it doesn't see ksp.exe"?
> 
> Third, for your consoleui screenshot, try it without backslashes.

1) I'm using the latest version

2) 
![image](https://github.com/KSP-CKAN/CKAN/assets/54883747/03b42432-7bd2-4635-9922-72984bd71abd)


3) 
![image](https://github.com/KSP-CKAN/CKAN/assets/54883747/5d043868-1db5-4216-8be8-594b80ff7d3a)
![image](https://github.com/KSP-CKAN/CKAN/assets/54883747/2be0f38c-31a2-4a70-bfe3-464768c79699)

**Comment by HebaruSan** [comment]
OK, what is actually in that folder when you look at it outside of CKAN? We just had a user who was trying to use the Windows version of KSP1 on Linux, but CKAN looks for the _Linux_ executable file name. If you're doing the same, you should consider installing the Linux version of KSP1.

**Comment by HebaruSan** [comment]
> 1. I'm using the latest version

I was going by this, where you said you were using an older version:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/bbf43ad4-ea21-4656-a008-8872bf3b4466)

If that was wrong, please feel free to fix it.

**Comment by IgnIVertiKalCaD** [comment]
> > 1. I'm using the latest version
> 
> I was going by this, where you said you were using an older version:
> 
> ![image](https://private-user-images.githubusercontent.com/1559108/305586179-bbf43ad4-ea21-4656-a008-8872bf3b4466.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDgxMzEwNDQsIm5iZiI6MTcwODEzMDc0NCwicGF0aCI6Ii8xNTU5MTA4LzMwNTU4NjE3OS1iYmY0M2FkNC1lYTIxLTQ2NTYtYTAwOC04ODcyYmYzYjQ0NjYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDIxNyUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAyMTdUMDA0NTQ0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9ODRjODM2ZWUwODVhNDBiNzgzOTllMDJkMmY5NWRjYTNiMzIyNGQ2NDg5MTQyZmU3ZjJkZTZiZDllNDYyN2Q5MiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ._Shne9imKf-rtRWvJrHzFXNLHOQJb0kSzO8Ha54GFg4)
> 
> If that was wrong, please feel free to fix it.

I was wrong. In the terminal you can clearly see what version I used - 1.34.4
