### ISSUE TITLE
[Bug]: [LINUX]: " *directory* is not a valid game directory. " message when trying to create new game instance

### ISSUE THREAD

**Issue by Tryhard-Newbie** [KSP-CKAN/CKAN#4038]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Linux Mint

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190 (With Proton)

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No.

### Describe the bug

When I run CKAN, a window pops up for managing game instances. I press the "New Game Instance" button, followed by "Add instance to CKAN". This opens up a window, where I can manually go to the correct directory, the one that contains the game's contents. Unfortunately this window doesn't let me select (or see for that matter) any non folder files, which makes me unable to select the correct file. Attempting to go to the right directory and write the filename in the correct box results in the error message "*directory* is not a valid game directory.". I have attempted to use the CKAN Console UI to circumvent this but I get the "Path does not correspond to a game folder!" error message.
![Screenshot from 2024-02-18 15-31-41](https://github.com/KSP-CKAN/CKAN/assets/160403401/66978b0e-7772-4cc3-a88b-49111c3150e8)
![Screenshot from 2024-02-18 15-29-47](https://github.com/KSP-CKAN/CKAN/assets/160403401/544a35dd-ebc3-4636-8982-fcb78a72704d)

### Steps to reproduce

*Open CKAN
*Attempt to create a new instance
*Go to the game directory

**Comment by HebaruSan** [comment]
Hi @Tryhard-Newbie, thanks for the report. There's always been a Linux-native built of KSP1, and if you install that, it should work fine.

**Comment by tkalfaoglu** [comment]
I have the same issue for World of Warcraft..
$ ckan instance add Wow /home/turgut/Games/WoW/
Sorry, /home/turgut/Games/WoW/ does not appear to be a game instance

huh?

**Comment by HebaruSan** [comment]
@tkalfaoglu why would you try to use CKAN for WoW? It is for KSP1 and KSP2.

**Comment by Tryhard-Newbie** [comment]
Can confirm that the use of Proton was the issue, if anyone from the future sees this, use KSP native
