### ISSUE TITLE
[Bug]: Continue button is greyed out when trying to install modpack

### ISSUE THREAD

**Issue by LightningSheep** [KSP-CKAN/CKAN#4042]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Win 10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.3

### Describe the bug

When trying to install a modpack from a .ckan file I get the recommendations and stuff but the continue button is greyed out, this happens with the recommendations ticked and unticked.

### Steps to reproduce

1. Launch CKAN
2. Compatibility:
   ![image](https://github.com/KSP-CKAN/CKAN/assets/118577973/30e74770-97e9-472b-b250-1191bb9a6610)
4. Install this .ckan file:  [forallkerbalkind.zip](https://github.com/KSP-CKAN/CKAN/files/14382093/forallkerbalkind.zip)
5. ![image](https://github.com/KSP-CKAN/CKAN/assets/118577973/71185259-3b8d-4206-84bf-fd910726734e)

**Comment by HebaruSan** [comment]
Hi @LightningSheep, thanks for the report. We'll need three things to help you figure this out:

1. A copy of the .ckan file you're trying to install
2. A list of the mods you already have installed, if any
3. A screenshot of CKAN when you're having this problem

Cheers!

**Comment by LightningSheep** [comment]
https://www.mediafire.com/file/z3rqme76svbhdnj/FAK_Install.zip/file
I have no other mods installed
![image](https://github.com/KSP-CKAN/CKAN/assets/118577973/71185259-3b8d-4206-84bf-fd910726734e)

**Comment by HebaruSan** [comment]
Thanks! This error message across the bottom is the reason it's disabled:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/a7e6a6e9-1035-46cf-a827-f87ec02b85b7)




When I try that .ckan file, I get this warning:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/016d9ccd-fc04-41dd-a81f-d4593747bcc1)

Can you please also upload a screenshot of your compatibility settings from Settings → Compatible game versions?

For me, the Continue button is enabled:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/ff69d7d2-94ac-4bf4-9ec7-ee7e2d75896c)

**Comment by LightningSheep** [comment]
What do you mean by try that? Did you disable one of them?

**Comment by HebaruSan** [comment]
> What do you mean by try that? Did you disable one of them?

I mean I tried installing the .ckan file in the ZIP you linked.

Can you please upload a screenshot of your compatibility settings from Settings → Compatible game versions?

**Comment by LightningSheep** [comment]
![image](https://github.com/KSP-CKAN/CKAN/assets/118577973/30e74770-97e9-472b-b250-1191bb9a6610)

**Comment by HebaruSan** [comment]
Thanks. The Continue button is still enabled for me when I try it with those settings.

Can you please upload a screenshot of your main CKAN mod list so we can confirm that you don't already have anything installed?

**Comment by HebaruSan** [comment]
Also you can try the dev build to see if it makes a difference, if you like:

- <https://ksp-ckan.s3-us-west-2.amazonaws.com/ckan.exe>

**Comment by LightningSheep** [comment]
Well it turns out despite a new install of both the game and ckan it still carried all my mods over, sorry for wasting your time.
