### ISSUE TITLE
-- asroot

### ISSUE THREAD

**Issue by MIDJIE** [KSP-CKAN/CKAN#4045]
Vous essayer d'utiliser CKAN en tant que super-utilisateur.
C'est une mauvaise idée et il n'y a absolument aucune raison de le faire. Veuillez utiliser CKAN depuis un compte utilisateur (ou utilisez --asroot si vous aimez le risque).

Press any key to exit...

**Comment by HebaruSan** [comment]
Duplicate of #3956 or #4032.
