### ISSUE TITLE
Release date column didn't update when a new version of the mod became available

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4060]
Unfortunately I'm not sure what my repro steps here were.  I changed game instances, and then filtered by installed.  I did notice that before I switched the filter, the "update all" button was enabled.  A new version of QuickStart was just released, but the Release Date column has not been updated even though CKAN is aware of the new version.  Is it showing the release date of the installed version instead?  Maybe I'm just confused about what that column means.

![image](https://github.com/KSP-CKAN/CKAN/assets/9804078/d34a4e6e-331e-4427-920e-b7abacea7d73)

**Comment by HebaruSan** [comment]
When a mod is installed, all the info shown is for the installed version. Try upgrading.
