### ISSUE TITLE
Cannot find central directory for ProceduralParts v2.5.8.0

### ISSUE THREAD

**Issue by DominusCruz** [KSP-CKAN/CKAN#4061]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

win 11

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

Installing ProceduralParts v2.5.8.0...
Cannot find central directory
Error during installation!

### Steps to reproduce

try install Rp-1 end Reallism overhaul

### Relevant log output

Installing ProceduralParts v2.5.8.0...
Cannot find central directory
Error during installation!

![image](https://github.com/KSP-CKAN/CKAN/assets/163696469/c75b908a-3cba-47e3-95b9-a68b8071c611)

The ZIP file is corrupted:

![image](https://github.com/KSP-CKAN/CKAN/assets/163696469/e3ebe173-333d-48d9-87aa-0f19b959bbf2)

**Comment by HebaruSan** [comment]
This mod installed fine for me just now.

@DominusCruz, v1.13.4 is an extremely old version of CKAN. I assume you meant 1.**3**4.4? If not, try the latest version:

<https://github.com/KSP-CKAN/CKAN/releases/latest>

**Comment by DominusCruz** [comment]
Nothing changed, it still gives the same error in the same part of the installation.

**Comment by HebaruSan** [comment]
OK, thanks for double checking.
That message means the ZIP file in your cache is corrupted. Can you try purging it with the right click menu and then try again?

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/c7872417-c389-4f4d-ad90-80084ba039bb)

**Comment by DominusCruz** [comment]
This error occurs when I try to install realism overhaul, in the solo mod it does not occur

**Comment by HebaruSan** [comment]
Did you retry the RealismOverhaul install after purging from cache? Or are you assuming that it would havea problem now because you saw a problem before?

**Comment by DominusCruz** [comment]
i tryed again and same error

**Comment by DominusCruz** [comment]
it just doesn't seem to find the mod.

**Comment by HebaruSan** [comment]
OK, two points of follow-up, then.

First, please share a complete screenshot of the error, so we can confirm that the description isn't missing anything important. You can press Alt+PrintScreen on Windows to capture the CKAN window to the clipboard while CKAN has the focus, and then Ctrl+V to paste the image into the GitHub comment box.

Second, an you please try clicking the Open ZIP button for this mod and let us know whether it works? That would be another way to check whether the file might be corrupted.

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/1b6a09e2-737d-43f0-b62a-1fbe365901f0)

**Comment by DominusCruz** [comment]
![image](https://github.com/KSP-CKAN/CKAN/assets/163696469/c75b908a-3cba-47e3-95b9-a68b8071c611)

**Comment by DominusCruz** [comment]
It must be corrupt because this message appears. the archive is either in unknown format or damage

**Comment by DominusCruz** [comment]
![image](https://github.com/KSP-CKAN/CKAN/assets/163696469/e3ebe173-333d-48d9-87aa-0f19b959bbf2)

**Comment by HebaruSan** [comment]
Thanks!

Can you confirm that you tried purging the file? That should force it to be re-downloaded, which should fix the issue with the corruption:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/c7872417-c389-4f4d-ad90-80084ba039bb)

**Comment by DominusCruz** [comment]
OK it works now thanks

**Comment by HebaruSan** [comment]
Glad you got it working! 🎉 

BTW, CKAN checks that downloads are valid before it adds them to the cache, so this file probably became corrupted after it was added to the cache. You might want to check your storage device for other corruption and consider making backups and replacing it.
