### ISSUE TITLE
[Bug]: Error code 403 & Object reference not set to an instance of an object. Repository update failed!

### ISSUE THREAD

**Issue by yabegitu** [KSP-CKAN/CKAN#4070]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows

### CKAN Version

Niven / v1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No I did not if I recall. I followed the instruction on how to install it in Windows, and I also tried to re-install KSP and the CKAN.

### Describe the bug

![Screenshot (550)](https://github.com/KSP-CKAN/CKAN/assets/116003798/19efd676-5576-4adc-8f48-2364c461c21b)
![Screenshot (551)](https://github.com/KSP-CKAN/CKAN/assets/116003798/f3780935-aea0-4220-819a-b296edb04893)

### Steps to reproduce

Launch the ckan.exe

**Comment by HebaruSan** [comment]
Hi @yabegitu, are you able to access these URLs in your browser? This would help to diagnose what is going on with your network:

- <https://raw.githubusercontent.com/KSP-CKAN/CKAN-meta/master/builds.json>
- <https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz>

**Comment by yabegitu** [comment]
Yes, I can do access those URLs

**Comment by HebaruSan** [comment]
OK, then you'll want to check your system's firewall and antivirus software. The most likely cause is that something on your PC is blocking CKAN from accessing those URLs.
