### ISSUE TITLE
[Bug]: CKAN crashes on start after installing Windows 11's KB5036893 update

### ISSUE THREAD

**Issue by zhangyuesai** [KSP-CKAN/CKAN#4075]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Windows 11 23H2 (22631.3447)

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

After I installed Windows 11's KB5036893 update (version 22631.3447), CKAN crashed immediately on start.

I uninstalled that Windows update and CKAN started properly.

### Steps to reproduce

* Install Windows 11's KB5036893 update
* Launch CKAN
* CKAN crashes immediately on start

**Comment by HebaruSan** [comment]
Hi @zhangyuesai, we'll need some information about the crash to investigate this. Is there an error message? Can you describe what you see? Can you share a screenshot?

**Comment by zhangyuesai** [comment]
Hi @HebaruSan , it's really weird. I reinstalled the Windows update to take a screenshot but the issue was gone. However, after I reboot the computer the issue occurred again, and another rebooting could make it gone again. I'm pretty sure the issue occurs only when the Windows update is installed, but I can't 100% reproduce it.

Does CKAN has a log and where can I find it? I could provide the log if the issue occurs again.

Here's what I see when the issue occurs:

* Run CKAN.
* The console and the GUI show up.
* Process `ckan.exe` shows up in the Windows Task Manager, too.
* The console and the GUI disappear on "Loading registry...". Silently, no error message.
* And process `ckan.exe` disappears, too.

Attached is a video about the issue. I couldn't change my system language to English; the message showed on the GUI before CKAN crashed was "Loading registry..." or something like that. The Task Manager is on the right side of the screen.

https://github.com/KSP-CKAN/CKAN/assets/11785419/97674185-b5db-4e14-a686-04f55c8d9529

**Comment by HebaruSan** [comment]
@zhangyuesai, yes, if you open a terminal window and `cd` to the folder where `ckan.exe` is, you can run `ckan --debug --show-console` to see the logging. This should at least allow us to guess the last few things that happen before it closes, and if we're lucky, it may show an exception being thrown.

**Comment by zhangyuesai** [comment]
I'd like to share a further observation even though the issue is closed: 

**The crash may be caused by incompatibility between Windows Terminal and MacType.** More specifically, the Windows Terminal bundled with Windows 11. I tried uninstalling the bundled version of Terminal and reinstalling it through Microsoft Store, and have never experienced any crash after that.

So if anyone has MacType installed and experienced the same issue: **this may be a issue of Windows Terminal or MacType, not of CKAN.**
