### ISSUE TITLE
[Bug]: Unmet dependencies trying to install the .deb on Mint

### ISSUE THREAD

**Issue by The-Observer1984** [KSP-CKAN/CKAN#4080]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Latest linux mint

### CKAN Version

Latest ckan

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Its in a external drive

### Describe the bug

I ran into a error, tried to download it and it did not have a directory. if there is a fix for this i did not find it

### Steps to reproduce

- semi fresh install, not good at linux and have steam plus ksp installed
- open terminal
- type `sudo curl -sS -o /usr/share/keyrings/ksp-ckan-archive-keyring.gpg https://raw.githubusercontent.com/KSP-CKAN/CKAN/master/debian/ksp-ckan.gpg`
- type `echo 'deb [arch=amd64 signed-by=/usr/share/keyrings/ksp-ckan-archive-keyring.gpg] https://ksp-ckan.s3-us-west-2.amazonaws.com/deb stable main' | sudo tee /etc/apt/sources.list.d/ksp-ckan.list > /dev/null`
- type `sudo apt update`
- type `sudo apt install ckan`

### Relevant log output

Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgdiplus : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.

**Comment by HebaruSan** [comment]
Hi @The-Observer1984, it sounds like some of Mono'sa dependencies aren't available with how you have things set up currently. Try installing Mono as per the instructions first:

- <https://www.mono-project.com/download/stable/#download-lin>

**Comment by The-Observer1984** [comment]
thank you!

**Comment by The-Observer1984** [comment]
Ok i tried that and i got the same response
`Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 libgdiplus : Depends: libjpeg62-turbo (>= 1.3.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
`

**Comment by HebaruSan** [comment]
Maybe there's a conflict? Maybe try some other packager managers. I know `aptitude` shows the relationships in a lot more detail, kind of like CKAN.

**Comment by HebaruSan** [comment]
Actually, a clarifying question first. For the latest message, do you get that when you try to install **Mono**, or when you try to install **CKAN**? From the context of what you've said it could be either one.

**Comment by The-Observer1984** [comment]
Its the same message for both installing mono and ckan

**Comment by HebaruSan** [comment]
OK, that confirms that the problem is with installing Mono, not CKAN specifically. You'll have to figure that out somehow. Sorry I don't know the answer, but someone associated with the Mono project or with Linux Mint might be able to provide better assistance.

**Comment by The-Observer1984** [comment]
Alright thanks
