### ISSUE TITLE
[Feature] Ability to install from .ckan file for ConsoleUI

### ISSUE THREAD

**Issue by wright** [KSP-CKAN/CKAN#4084]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Macos

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No changes.

### Describe the bug

Macos can run only the text version of CKAN. The text version can export a mod list as a .ckan file, but cannot import it.

### Steps to reproduce

Start CKAN, press f10, no import menu item exists.

**Comment by HebaruSan** [comment]
Try `ckan install -f modpack.ckan` from the command line.

**Comment by wright** [comment]
I tried both `-c` and `-f`, and both just showed the usage options as if they were not recognized. This is how I am running it:


```
./CKAN.app/Contents/MacOS/CKAN instance default lifeboat
Successfully set "lifeboat" as the default game instance

./CKAN.app/Contents/MacOS/CKAN -c lifeboat-modpack.ckan
CKAN-CmdLine 1.31.2
Copyright © 2014–2022
Usage: ckan <command> [options] 
... [text deleted]
``` 

Setting the instance from the command like this way looks like it worked.

**Comment by HebaruSan** [comment]
@wright  You missed the `install` part of the command

**Comment by wright** [comment]
Thanks! There is some progress. It runs if I give it an absolute path to the .ckan file. But, it complains about unsatisfied dependencies and the two suggested workarounds don't seem to do anything:

```
./CKAN.app/Contents/MacOS/CKAN install --allow-incompatible -c /Applications/addons/games/KSP_osx_1.12.5_lifeboat/lifeboat-modpack.ckan
lifeboat-modpack dependency on AT-Utils version (any) not satisfied
If you're lucky, you can do a `ckan update` and try again.
Try `ckan install --no-recommends` to skip installation of recommended modules.
Or `ckan install --allow-incompatible` to ignore module compatibility.
```


CKAN update` says that everything is up to date.

**Comment by HebaruSan** [comment]
Try updating your compatibility to match what the modpack file says in the `ksp_version_min` and `ksp_version_max` properties.

**Comment by wright** [comment]
The mod pack says:
```
"ksp_version_min": "1.12.5",
"ksp_version_max": "1.12.5",
```

I updated the compatibility in CKAN to list 1.12.5.3190 (as suggested in the drop down box, although it displays after adding it as 1.12.5.319) and 1.12.5 (manually), and got the same result.

**Comment by HebaruSan** [comment]
That's very odd, since AT-Utils apparently only goes up to 1.10, so it wouldn't normally be installable in the original copy of the game with those settings. Maybe the mod was installed via the checkbox in the Versions tab to override the compatibility?

**Comment by wright** [comment]
I'm not sure, I did not generate the mod list. I would expect `--allow-incompatible` to work around that in any case.

**Comment by HebaruSan** [comment]
`--allow-incompatible` only affects the mods immediately listed on the command line, not dependencies.

**Comment by wright** [comment]
Is there a way to skip dependencies?

**Comment by HebaruSan** [comment]
No. Going by AT-Utils' compatibility, you could try this instead:

```
ckan compat add 1.10
ckan compat add 1.11
ckan compat add 1.12
```

**Comment by wright** [comment]
That worked to get passed the AT-Utils problem, but it failed on another dependency.

Thanks for the many suggestions, but I think that my bad example .ckan file is obscuring the actual issue: the ConsoleUI does not support importing a mod list from an exported .ckan file.

The command line process (even if it worked with a good .ckan file) is not the ideal user experience, and it is currently the only option available for MacOS KSP CKAN users. It might save a lot of exasperation  if the ConsoleUI could be expanded to:

- add an "Import mod list" menu item,
- that prompts for a .ckan file to read,
- then the file name is passed to the existing code that processes the list

Check Boxes could be added near the file name prompt for options such as `--allow-incompatible`. Error messages could be displayed in the same manner as other ConsoleUI errors.

**Comment by HebaruSan** [comment]
Don't worry, nothing's being obscured; this issue is still a marker for adding that featgure to ConsoleUI. I'm just trying to provide workarounds to get you going while the functionality does not exist.

**Comment by wright** [comment]
I appreciate your help. I am going to give up on this particular .ckan file.
