### ISSUE TITLE
[Feature]: Download cache change management

### ISSUE THREAD

**Issue by gsf600y** [KSP-CKAN/CKAN#4086]
### Problem

When updating the cache folder to a new location, existing contents of the cache are not moved to the new location, and the existing contents are not deleted.
This means that the existing contents effectively become orphaned files.
CKAN still appears to have them marked as being downloaded, and allows the "purge from cache" option to be selected, however when clicking on this option it does not delete the cached download from what is now the old location.

### Suggestion

When changing the download cache location, the existing cache data should be moved to the new cache location, potentially unless an option is ticked not to override one of these defaults.

### Alternatives

Alternatively, the old cache should be purged automatically when selecting a new location.

Another alternative would be to take no actions with the old cache, but prompt the user that the old location still contains data, e.g.
"Old cache location contains xxx MiB of data.  Do you wish to purge?"

**Comment by HebaruSan** [comment]
Previous related changes for reference:

- Creation of the setting with auto-move included: #2535
- Disabling of auto-move: #2538
- Deferring change of setting till form close: #3804
