### ISSUE TITLE
[Feature]: Symlinks for GameData

### ISSUE THREAD

**Issue by ProgrammerFailure** [KSP-CKAN/CKAN#4087]
### Problem

When using multiple KSP instances, the squad & squadexpansions folders, along with some others, are duplicated, wasting space.

### Suggestion

My idea is for that all mods in a specific instance, and any save files etc, would be saved outside KSP. Then, when you click "Launch Game", the data for that instance would be symlinked in.

For example, I have a KSP installation in C:/Games/Kerbal Space Program. I create a instance using this in CKAN, named "KSP test". When I install a mod, it goes to %appdata%/Local/CKAN/KSP test/GameData. Inside the CKAN/KSP test you would also have saves and ships. 

Now, I click launch game in CKAN. Symlinks are created from %appdata%/Local/CKAN/KSP test & its folders to the respective folders in C:/Games/Kerbal Space Program. When I play the game, KSP sees exactly what it usually would and runs accordingly.

The advantage of this is saving 3-4 GB of space per installation, which is quite significant. It also isolates the actual KSP folder, which   might be useful to prevent needing a reinstallation (unsure of this part).

I've been doing something similar with .bat files myself, and so far it works well!

### Additional context

 I believe most Skyrim mod installers do something similar to this, which could be useful for some help.

**Comment by JonnyOThan** [comment]
Hmm, I'd actually propose a slightly different solution:

The "create new instance" feature could be extended to set up a *lightweight* instance that just symlinks certain folders back to some other instance.  That way, there's no ongoing work to swap out stuff when you decide to launch the game, which would likely be a big maintenance burden and possible point of failure.

**Comment by HebaruSan** [comment]
Sounds like that would fit well as a checkbox here:

![image](https://github.com/user-attachments/assets/932de42c-7d5b-4384-9bef-ceb1431b0a91)

**Comment by HebaruSan** [comment]
... nope. There's a `File.CreateSymbolicLink`, but not for us:

![image](https://github.com/user-attachments/assets/45571a29-ebaa-4af9-8cd8-b899959f51cc)

**Comment by ProgrammerFailure** [comment]
> ... nope. There's a `File.CreateSymbolicLink`, but not for us:
> 
> ![image](https://github.com/user-attachments/assets/45571a29-ebaa-4af9-8cd8-b899959f51cc)
> 

You could have CKAN create, run, and delete a .bat file to make the symlinks? Or whatever the MacOS/Linux version is.

**Comment by ProgrammerFailure** [comment]
About the Skyrim mod manager stuff, they have a different, more complicated solution. They do some kind of virtualization to make the game think that the mods are present. That is to say, they probably aren't the best example for symlinks specifically.

**Comment by JonnyOThan** [comment]
> You could have CKAN create, run, and delete a .bat file to make the symlinks? Or whatever the MacOS/Linux version is.

Maybe..but probably also lots of issues related to OS permissions etc.

The original proposal is likely prohibitively complex.  But a lightweight instance where the unchanging large stock files are shared certainly seems feasible.  At least as long as we create the symlinks when creating the instance.

**Comment by ProgrammerFailure** [comment]
I figured out a solution that should work:
Note this for the explanation:
- When a game is added, that's called an instance 
- Each game can have multiple profiles 
- I'll use InstanceA and ProfileA as instance and profile names.
- CKAN/xxx refers to the global CKAN folder.

If the user selects "use symlinks" or similar, then:


1: Squad and SquadExpansion are moved out of GameData and into CKAN/instances/InstanceA/BaseGameFolder

3: - Delete the GameData folder in the KSP root folder.

2: Mods for profileA are installed into CKAN/instances/InstanceA/profiles/ProfileA/mods


3: At game run:
- symlink from "CKAN/instances/InstanceA/BaseGameFolder/Squad" to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called Squad.

- symlink from "CKAN/instances/InstanceA/BaseGameFolder/SquadExpansion" to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called SquadExpansion.

- symlink from KSP root to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called GameData.

4: Result
-  KSPx64.exe sees GameData, but it's actually "CKAN/instances/InstanceA/profiles/ProfileA/mods".
- KSPx64.exe sees GameData/Squad and SquadExpansion, but it's actually "CKAN/instances/InstanceA/BaseGameFolder/Squad" and "/SquadExpansion"

- Any mod generated folders/files go into "CKAN/instances/InstanceA/profiles/ProfileA/mods"

This strategy still saves disk space, (4gb per instance other than the first one), but since CKAN is a large part of managing the base game folder, it doesn't keep the less likely to need reinstall component.

It also needs a maximum of 3 symlinks.
InstanceA or ProfileA in the paths can be changed of course.

**Comment by ProgrammerFailure** [comment]
I figured out a solution that should work:
Note this for the explanation:
- When a game is added, that's called an instance 
- Each game can have multiple profiles 
- I'll use InstanceA and ProfileA as instance and profile names.
- CKAN/xxx refers to the global CKAN folder.

If the user selects "use symlinks" or similar, then:


1: Squad and SquadExpansion are moved out of GameData and into CKAN/instances/InstanceA/BaseGameFolder

3: - Delete the GameData folder in the KSP root folder.

2: Mods for profileA are installed into CKAN/instances/InstanceA/profiles/ProfileA/mods


3: At game run:
- symlink from "CKAN/instances/InstanceA/BaseGameFolder/Squad" to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called Squad.

- symlink from "CKAN/instances/InstanceA/BaseGameFolder/SquadExpansion" to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called SquadExpansion.

- symlink from KSP root to "CKAN/instances/InstanceA/profiles/ProfileA/mods". The symlink must be called GameData.

4: Result
-  KSPx64.exe sees GameData, but it's actually "CKAN/instances/InstanceA/profiles/ProfileA/mods".
- KSPx64.exe sees GameData/Squad and SquadExpansion, but it's actually "CKAN/instances/InstanceA/BaseGameFolder/Squad" and "/SquadExpansion"

- Any mod generated folders/files go into "CKAN/instances/InstanceA/profiles/ProfileA/mods"

This strategy still saves disk space, (4gb per instance other than the first one), but since CKAN is a large part of managing the base game folder, it doesn't keep the less likely to need reinstall component.

It also needs a maximum of 3 symlinks.
InstanceA or ProfileA in the paths can be changed of course.

**Comment by HebaruSan** [comment]
Hmm, that comment was a duplicate when I deleted it. I'll see if it'll let me undelete...

**Comment by ProgrammerFailure** [comment]
Wait, my comment got deleted by accident. The idea was that stock files are stored by CKAN, symlinked into the mods folder, then the whole mods folder is symlinked into KSP root named as GameData.

**Comment by JonnyOThan** [comment]
> Wait, my comment got deleted by accident. The idea was that stock files are stored by CKAN, symlinked into the mods folder, then the whole mods folder is symlinked into KSP root named as GameData.

What does this achieve that symlinking certain stock directories/files back to another instance doesn’t?  Because one of these is orders of magnitude more complex than the other.

**Comment by HebaruSan** [comment]
Realistically, the audience for this feature would probably be a fraction of the people who could homebrew it themselves in a couple of minutes. It's a fun thought experiment, though.

Also, imagine a typical user's thought process:

1. Cool, CKAN can run the game out of a much smaller folder! I can save so much disk space!
2. (Makes a symlinked game instance)
3. (Deletes the original instance where the symlinks point)
4. WTF, why doesn't the game run anymore????

**Comment by ProgrammerFailure** [comment]
> Realistically, the audience for this feature would probably be a fraction of the people who could homebrew it themselves in a couple of minutes. It's a fun thought experiment, though.
> 
> Also, imagine a typical user's thought process:
> 
> 1. Cool, CKAN can run the game out of a much smaller folder! I can save so much disk space!
> 2. (Makes a symlinked game instance)
> 3. (Deletes the original instance where the symlinks point)
> 4. WTF, why doesn't the game run anymore????
> 

Yeah, didn't think about the "customer" support aspect. Or would it be user support? 

You are correct that anyone who understands how it works could homebrew it, but the typical user wouldn't be able to. 

As for deleting instance and the game doesn't run anymore, could be addressed by a small popup?

**Comment by ProgrammerFailure** [comment]
> I have to say I am firmly, resolutely against messing with any stock files. That is a recipe for absolute disaster with the slightest unexpected bug, and "CKAN bricked my install" reports all up and down the bug tracker.
> 

I mostly agree. However, my proposed solution doesn't change stock files; to restore, the user just has to copy Squad and SquadExpansion back to GameData. That's within most users capabilities surely?

**Comment by HebaruSan** [comment]
> CKAN/BaseGameFiles/Squad to CKAN/Instances/InstanceA/mods
> 
> CKAN/BaseGameFiles/SquadExpansion to CKAN/Instances/InstanceA/mods
> 
> CKAN/instances/InstanceA/mods to KSP root, named as GameData.

I don't want to crush your dreams here, but: **No**. We're not moving stock files out of their canonical locations. To pick one reason at random among a vast number...

Steam users. Steam installs those files itself, and if you right click the game and select "verify integrity of game files", it will check them and re-download them to ensure they're valid. CKAN absolutely should not be in the business of disrupting that.

And for a game that has not had its dev team disbanded yet (remember that CKAN supports multiple games and will probably add more in the future), it would be _insane_ to remove such files from where Steam can update them when there are new game versions.

Please let that go lest this suggestion veer into total impracticality.

Another note, there are users who install mods via CKAN and then launch the game via Steam. They shouldn't be locked out of this feature by making it depend on "click launch game in CKAN".

Making the clone-instance feature support symbolic links for stock files would have none of the above problems, but it still faces the lack of cross-platform support for symbolic links in the version of .NET that CKAN uses.

**Comment by ProgrammerFailure** [comment]
Nah, fair enough. I can do it myself, this was a suggestion, and it had large issues making it impractical. Nothing wrong with that.

I will note that once symlinks are made the game can be launched any way you want; that's not an issue.

I'm gonna implement this for myself, if I figure out a solution that doesn't need modification of game files, I'll post it here.
 
Will close issue now.

**Comment by HebaruSan** [comment]
> I will note that once symlinks are made the game can be launched any way you want; that's not an issue.

That was specifically regarding this in the OP:

> Now, I click launch game in CKAN. Symlinks are created from %appdata%/Local/CKAN/KSP test & its folders to the respective folders in C:/Games/Kerbal Space Program. When I play the game, KSP sees exactly what it usually would and runs accordingly.

**Comment by ProgrammerFailure** [comment]
> That was specifically regarding this in the OP:
> 
> > Now, I click launch game in CKAN. Symlinks are created from %appdata%/Local/CKAN/KSP test & its folders to the respective folders in C:/Games/Kerbal Space Program. When I play the game, KSP sees exactly what it usually would and runs accordingly.

That's for first run/on switching instances. Afterwards, it'll work until symlinks are deleted (ideally on switching instances)

**Comment by JonnyOThan** [comment]
Hey if you find out any good info on programmatically creating symlinks let us know. I have a hunch that we could probably do it with a small amount of platform-specific code, but I haven’t looked into it at all.

**Comment by HebaruSan** [comment]
Yeah I think it's basically this.

```csharp
        [DllImport("libc")]
        private static extern int symlink(string src, string dest);

        [DllImport("kernel32.dll")]
        private static extern bool CreateSymbolicLink(string dest, string src,
                                                      SymbolicLink kind);

        private enum SymbolicLink
        {
            File      = 0,
            Directory = 1,
        }

        public static bool MakeSymLink(string src, string dest)
            => Platform.IsWindows ? File.Exists(src)      ? CreateSymbolicLink(dest, src, SymbolicLink.File)
                                  : Directory.Exists(src) && CreateSymbolicLink(dest, src, SymbolicLink.Directory)
             : Platform.IsUnix && symlink(src, dest) == 0;
```

**Comment by ProgrammerFailure** [comment]
> Yeah I think it's basically this. Haven't tested yet; the params may or may not work as strings, and not sure what to do about MacOS.
> 
> ```csharp
>         [DllImport("libc")]
>         private static extern int symlink(string src, string dest);
> 
>         [DllImport("kernel32.dll")]
>         private static extern bool CreateSymbolicLink(string dest, string src,
>                                                       SymbolicLink kind);
> 
>         private enum SymbolicLink
>         {
>             File      = 0,
>             Directory = 1,
>         }
> 
>         public static bool MakeSymLink(string src, string dest)
>             => Platform.IsWindows ? File.Exists(src)      ?  CreateSymbolicLink(dest, src, SymbolicLink.File)
>                                   : Directory.Exists(src) && CreateSymbolicLink(dest, src, SymbolicLink.Directory)
>              : Platform.IsUnix && symlink(src, dest) == 0;
> ```

Does this cover the name of the resulting symlink? I don't see a parameter for name in there.

**Comment by HebaruSan** [comment]
@ProgrammerFailure do you mean `dest`?

**Comment by ProgrammerFailure** [comment]
No, I mean the name of the symlink. For example, a symlink from A/B/C to 2/3/4 named "blue" would result in the following path: A/B/C/blue, where the contents of blue are the contents of 4. 

See this command: https://learn.microsoft.com/en-us/windows-server/administration/windows-commands/mklink . It's the windows symlink command. You'll notice a link field (the symlink is created in the current working directory, so no dest).

**Comment by HebaruSan** [comment]
Yeah, that's `dest`. Your example would be `MakeSymLink("2/3/4", "A/B/C/blue")`. There's no need for an extra parameter to specify the last piece of the path.

**Comment by ProgrammerFailure** [comment]
Ok, got confused by the naming I guess.

**Comment by JonnyOThan** [comment]
I'd suggest using the same names as in the win32 api to avoid confusion: symlinkFileName and targetFileName.

https://learn.microsoft.com/en-us/windows/win32/api/winbase/nf-winbase-createsymboliclinka

**Comment by HebaruSan** [comment]
What about naming the param to `CloneInstance` that determines whether to copy or symlink the stock files? RIght now I have `bool shallow = false`, but I don't like it very much.

**Comment by JonnyOThan** [comment]
shallowCopy is fine, or name it deepCopy or fullCopy and default to true.  Other possibilities: lightweight or shareStockFiles.

**Comment by HebaruSan** [comment]
Hoping to avert disasters with a tooltip warning (the accept/cancel buttons are still there underneath):

![image](https://github.com/user-attachments/assets/f16cc053-2bdd-4675-9e8e-1c387f92c14f)

**Comment by JonnyOThan** [comment]
Not bad.  I’d probably add a note in there about *why* someone would want to do this, and maybe an estimate of how much it saves per instance

**Comment by ProgrammerFailure** [comment]
Just to be clear, are you guys planning on adding this? Or is it more of a hypothetical?

**Comment by HebaruSan** [comment]
Heh, don't expect that kind of clarity until we have a merged pull request that closes this issue. I'm interested in the idea and have been looking at it but I can't yet guarantee that it will work well enough to be added.

**Comment by ProgrammerFailure** [comment]
Fair enough. If/when you close it GitHub sends me a ln email right? I'd be interested in using the feature myself. 

(My computer is VERY limited in disk space. That's the whole reason I suggested it.)

**Comment by HebaruSan** [comment]
Sure, in fact, I'll tag you in the pull request if/when it's ready so you can test a build with the changes before it goes out to everybody else.
