### ISSUE TITLE
[Bug]: CKAN just loading after trying to use a .ckan file.

### ISSUE THREAD

**Issue by NkoKirkto** [KSP-CKAN/CKAN#4099]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.13.53190

### Describe the bug

If i try to use the .ckan file my friend send me CKAN will not react lock the upper row of buttons(File,Settings,Help) and tunr my mouse into a loading circle until i force close it via the Task Manager

### Steps to reproduce

*Open CKAN
*Click  File Install from .ckan

**Comment by HebaruSan** [comment]
Hi @NkoKirkto, thanks for the report. To investigate this, we would need:

- A copy of the .ckan file you tried to use
- Your current game version compatibility settings
- A screenshot of CKAN when the problem occurs.

If you can share those things, please do and we can re-open this.

**Comment by NkoKirkto** [comment]
Where do i check the compatibility settings?

https://drive.google.com/file/d/1F5TcWx_IYeH5uP23emfWsy_ccUW7DAGl/view?usp=sharing
https://drive.google.com/file/d/1qq8Oc8f3XL5jjkPGXDlQW6J1Tnq6dBYH/view?usp=sharing

Here are both fo the files i tried it with but they contain the same mods.

![image](https://github.com/KSP-CKAN/CKAN/assets/153374559/57e820e6-a094-423e-9254-c610b60aefa1)
Here is a screenshot of CKAN when the problem occurs. You cant see my mouse but it is showing the Windows loading circle and i let it sit for 15 or so minutes and nothing changes.

**Comment by HebaruSan** [comment]
[Settings → Compatible game versions](https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions)

**Comment by HebaruSan** [comment]
Cross-referencing #4042 for a similar previous report, which was closed when the author found that a number of mods were already installed and causing conflicts.
