### ISSUE TITLE
[Bug]: Environmental Visual Enhancements from Blackrack's cloud mod (RaymarchedVolumetricsEarlyAccess27_03_24) not detected as a manually installed mod.

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN#4101]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Installed Blackrack's volumetric clouds mod (RaymarchedVolumetricsEarlyAccess27_03_24):  
  
1) deleted mods Environmental Visual Enhancements Redux, Scatterer and Scatterer Default Config via ckan  
2) then copied folders EnvironmentalVisualEnhancements, Scatterer, StockScattererConfigs, StockVolumetricClouds and file Blackrack_TUFX.cfg to the GameData folder.

### Describe the bug

I expected to see the letters "AD" in place of a checkbox in the 'installed' column for Environmental Visual Enhancements Redux  Instead, there is the usual checkbox.

The version of Environmental Visual Enhancements installed by ckan (Redux v 1.11.7.1) and from the volumetric mod's zip file have exactly the same named dll's in their Plugin directories.   
  

### Steps to reproduce

As described above.

**Comment by HebaruSan** [comment]
> The version of Environmental Visual Enhancements installed by ckan (Redux v 1.11.7.1) and from the volumetric mod's zip file have exactly the same named dll's in their Plugin directories.

If that's the case, then the described behavior would be expected. The "AD" feature only detects mods that have a DLL with a name that matches the mod identifier, and I don't see an `EnvironmentalVisualEnhancements.dll` file in the ZIP:

![image](https://github.com/KSP-CKAN/CKAN/assets/1559108/ddc7374d-e104-489a-8fca-c2424379722d)

**Comment by HebaruSan** [comment]
Also, in the specific case described, marking the normal EVE as "AD" when this custom Patreon-only variant of EVE is installed seems like it would be highly undesirable, since the user would be at risk of overwriting the special files they paid for with the normal ones from CKAN. (One user on Discord even said they did just that, and didn't have a backup!)

**Comment by tjanke42** [comment]
I can understand technical limitations.  I can see the work required to design and implement another way of detecting mods would not be trivial.  Frustrating, but understandable.

As for your second comment, fair point. I can see why that might be a problem.  The counter-argument is that, when troublshooting mods I'm now likely to delete the custom variant of EVE via ckan _without realizing it_, especially if it's been some months or more, and would likely unwittingly reinstall the regular version of it later, then wonder why those beautiful clouds are no longer working, leading to _two_ problems to troubleshoot, possibly simultaneously.  Also highly undesireable.

I would find it very desireable to know that a mod is present but was not installed by ckan.  Right now I have to track that manually, and I'd much prefer this wonderful tool to do that for me.  As is, I feel like, in a few cases, ckan is not giving me a consistent and accurate picture of my mod install base.
