### ISSUE TITLE
[Bug]: TweakScale/L displayed some error message about a DLL

### ISSUE THREAD

**Issue by badname64** [KSP-CKAN/CKAN#4106]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

v1.34.4

### Games

KSP 1

### Game Version

1.10.1

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

None

### Describe the bug

For CKAN to install everything needed for a mod to work like you know, the DLL files. and then TweakScale gave me an error popup saying the DLLs arent installed

### Steps to reproduce

Nothing and i was worried because it said that i should exit the game and install the DLLs orelse my files and savegames would get corrupted

### Relevant log output

i dont know how to get log

**Comment by HebaruSan** [comment]
Hi, exactly which DLL are you saying was not installed?

Try uninstalling `TweakScale` and installing `TweakScaleRescaled` instead. This newer fork has many fixes and improvements that are missing from the one you installed.

**Comment by badname64** [comment]
Ok @HebaruSan ill try that and notify you if it works

**Comment by badname64** [comment]
It doesnt work on my version of the game
(the checkbox is a "-")

**Comment by HebaruSan** [comment]
Why are you using 1.10?

**Comment by badname64** [comment]
Next Star Industries and certain BDARMORY mods

**Comment by HebaruSan** [comment]
Ahh. You can install those on 1.12.5 if you set 1.10 as compatible:

<https://github.com/KSP-CKAN/CKAN/wiki/User-guide#choosing-compatible-game-versions>

I'd either try that, or mark 1.12 as compatible in your 1.10 instance.

**Comment by badname64** [comment]
Thank you ill try that

**Comment by badname64** [comment]
Will TweakScale Rescaled work with 1.10.1?

**Comment by HebaruSan** [comment]
> Will TweakScale Rescaled work with 1.10.1?

I don't know for sure, but probably? I have asked the author in another chat and will update you when I hear back.

**Comment by badname64** [comment]
Thank you

**Comment by badname64** [comment]
Sadly the Next Star Industries tab does not show up on the tool bar Nor the TweakScale Slider for items and objects

**Comment by HebaruSan** [comment]
Huh? Can you clarify what problem you're having now?

**Comment by HebaruSan** [comment]
If you're still using KSP 1.10, try updating to 1.12.5.

**Comment by badname64** [comment]
Sorry for a late reply but Next Star Industries should have its own section below the cog icon on the left tool bar and there should be a slider when i right click a part for TweakScale to modify its size and that bar isnt showing up
![image_2024-06-07_214611609](https://github.com/KSP-CKAN/CKAN/assets/165085964/4cc40010-bc52-4d79-8822-641e96cec692)
![Screenshot 2024-06-07 214558](https://github.com/KSP-CKAN/CKAN/assets/165085964/9de93a7d-16e6-4b61-b1cb-83a09911f4a7)

**Comment by HebaruSan** [comment]
@JonnyOThan, any idea?

**Comment by badname64** [comment]
and now that i switched the version whenever i click the game freezes the crashse

**Comment by badname64** [comment]
crashes*

**Comment by badname64** [comment]
Solved the game version wasnt correct and i forgot to update all on ckan

**Comment by badname64** [comment]
Huge thanks to @HebaruSan  for helping me with my mods and for helping me in the ksp forums and thats TWICE! WOW I am ASTONISHED!

**Comment by HebaruSan** [comment]
It sounds like everything is working now! :tada: 
That's awesome, and enjoy your space gaming.

If not, please let us know.
