### ISSUE TITLE
I can't uninstall Textures Unlimited [Bug]: 

### ISSUE THREAD

**Issue by Miles964833** [KSP-CKAN/CKAN#4110]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

I installed textures unlimited but when I loaded into the game my other mods worked but textures unlimited did not so I tried deleting it, but it keeps saying it failed and won't delete.

### Steps to reproduce

I clicked on it to uninstall and it won't uninstall.

### Relevant log output

there is none

**Comment by PewPewCricket** [comment]
same issue here

**Comment by Miles964833** [comment]
I'm trying to install BD armory but it keeps trying to download Textures unlimited as well which is making it so it can't download BD armory

**Comment by PewPewCricket** [comment]
Also unable to uninstall  BDArmoryForRunwayProject 2:v1.6.12.0

**Comment by HebaruSan** [comment]
@Miles964833, to investigate this we would need to see the actual message from CKAN. If you can provide that, please do and we can re-open this.

**Comment by Miles964833** [comment]
![Screenshot 2024-06-22 131446](https://github.com/KSP-CKAN/CKAN/assets/173559085/d0a942eb-938c-4c2f-9f93-8fd1ac3e727a)

**Comment by HebaruSan** [comment]
Ahh, you have a GameData folder in your GameData folder, presumably manually installed. Try deleting that.

**Comment by Miles964833** [comment]
Thanks for the help
