### ISSUE TITLE
[Bug]: Access to path 'G:/steamitself/steamapps/common/kerbal space program/CKAN' is denied.

### ISSUE THREAD

**Issue by iceman4229** [KSP-CKAN/CKAN#4121]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

windows11

### CKAN Version

v1.34.2

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

no

### Describe the bug

So i have been following a vid on youtube to mod KSP 1 into a better experience and the first step was to download CKAN i did that and put it into my KSP folder and i do have the up-to date V of .NET.  When i go to run CKAN i get the message that its access to KSP is denied and i would perfer not to have to run it in admin mode.  

### Steps to reproduce

So i have been following a vid on youtube to mod KSP 1 into a better experience and the first step was to download CKAN i did that and put it into my KSP folder and i do have the up-to date V of .NET.  When i go to run CKAN i get the message that its access to KSP is denied and i would perfer not to have to run it in admin mode.

**Comment by HebaruSan** [comment]
Closing because not a problem of CKAN.
Check the permissions of that folder and do web searches for the error message. Your computer isn't letting CKAN access the path, and only you can figure out why.
