### ISSUE TITLE
[Feature]: alert the user when the repository is older than some threshold

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4130]
Some people aren’t getting mod updates because they don’t have “update repositories on launch” enabled and they never click refresh.

Can we pop up an alert when the repository has not been updated in >X days?  Maybe with a button to just turn on auto updates.

**Comment by HebaruSan** [comment]
A recurring popup could be very annoying for people who are doing that intentionally for whatever reason (feeling that a snapshot in time is adequate for their install, involuntary air gap, whatever). What about something in the status bar like ConsoleUI does?

![image](https://github.com/user-attachments/assets/ca6c4983-591b-49f4-9681-ee6c3116271d)

![image](https://github.com/user-attachments/assets/a24bc355-7e53-464c-b8da-2cd93ea7c49b)

**Comment by JonnyOThan** [comment]
I agree about the popup, which is why X should be a fairly long time (weekly? 2 weeks?).  But I just had someone tell me that they couldn't find tweakscale rescaled on ckan because they hadn't refreshed since it was released.

The status bar would never be noticed by anyone.  I'd be fine if the popup also has a button that says "don't update and stop asking"

**Comment by HebaruSan** [comment]
Anything we do will have pros and cons, but wow, that many complicated options in a popup... yeah, no.

Maybe we can borrow a page from social media and put a little alert icon on the Refresh button to draw the user's attention, then put an explanation in the tooltip:

![image](https://github.com/user-attachments/assets/0fe7b368-2eb0-485d-88b0-9ebde7200d99)

![image](https://github.com/user-attachments/assets/879bacd7-078e-4dd7-a9e4-fd4ba2835c75)

**Comment by JonnyOThan** [comment]
Looks good to me.

**Comment by HebaruSan** [comment]
I'm leaning against changing that since we already have user feedback against "internet requests without direct authorization" in #2108.

**Comment by JonnyOThan** [comment]
7 years ago from someone who didn't respond to questions?

I'd say the needs of the many outweigh the needs of the few here.  Just this week I've helped two people get updates because they had auto-refresh turned off.

I think a better fix for that guy's issue is to provide a way to cancel the update operation if it's taking too long?

**Comment by HebaruSan** [comment]
I said "leaning", not "dead-set against". Yes, it was just one person, but where one person speaks up there are always more with the same thoughts, and I think it's a reasonable point that CKAN should be transparent about how/when it accesses the network.

Did you get a sense of why those two people chose not to enable automatic updates? Did they not understand the popup (which would raise some questions about the usefulness of trying to fix this with another popup)?

**Comment by JonnyOThan** [comment]
> Did you get a sense of why those two people chose not to enable automatic updates? Did they not understand the popup 

I don’t know why.  But I’d also say that presenting a first-time user with a choice like that is a mistake. Someone who has never used ckan has no way to make an informed decision; they don’t know what it means.  Perhaps this could be improved by better wording, but I think it’s better to just let them decide later via settings.

**Comment by HebaruSan** [comment]
@JonnyOThan ConsoleUI currently treats 7+ days as stale and 30+ days as very stale.

https://github.com/KSP-CKAN/CKAN/blob/2561753b544ae16faf6f78f723e8d088c29d641d/ConsoleUI/ModListScreen.cs#L742-L743

In my feature branch so far I've been treating 1+ as stale and 7+ as very stale, but I'm thinking these should be consistent. What do you think are actually reasonable thresholds to use?
