### ISSUE TITLE
[Feature]: CKAN can have an automatic translator for the introduction of the mods

### ISSUE THREAD

**Issue by zhouyiqing0304** [KSP-CKAN/CKAN#4132]
### Problem

![image](https://github.com/user-attachments/assets/718f530d-7a16-4904-bf04-bfe0d9dea2c9)
Someone doesn't understand it ......

### Suggestion

take an automatic translator for ckan.

### Alternatives

ChatGPT or something else is good.
you can also use some module like mistral

**Comment by HebaruSan** [comment]
Thanks for the suggestion. I don't think we'll do that, due to licensing, performance, and poor quality of output.

**Comment by zhouyiqing0304** [comment]
ok
