### ISSUE TITLE
[Bug]: Marking the max version of a mod as conflicting is sorta buggy

### ISSUE THREAD

**Issue by Clayell** [KSP-CKAN/CKAN#4134]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

Niven

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

yes but not really relevant, reported by multiple people

### Describe the bug

Kerbal Engineer Redux 1.1.9.5 was recently marked as compatible with the RP-1 Express Install (https://github.com/KSP-RO/RP-1-ExpressInstall/pull/5), and this was done by marking all previous versions as conflicting. However, looking at the conflicts with the express install on ckan, it looks like there is some sort of bug with this, as 1.1.9.5 is displayed as being conflicted but hovering over it says 1.1.9.4 and lower.
![image](https://github.com/user-attachments/assets/9a36759d-dd0e-4543-8203-efa02d493079)

Additionally, some people (https://discord.com/channels/319857228905447436/512556137380315139/1267456547186020435) have had trouble installing KER with the express install, although I haven't tested this myself.
![image](https://github.com/user-attachments/assets/148f15da-71f4-4c35-a36a-c83b11e97e86)

Refreshing does not fix the problem, nor does closing and launching up ckan again. The update was several weeks ago, so I'd be surprised if it was just something that has failed to update.

### Steps to reproduce

Try to install express install and KER 1.1.9.5 at the same time

### Relevant log output

Please inform me on where to find this

**Comment by HebaruSan** [comment]
Hi @Clayell, this looks like an error in your metadata. The latest KER metadata says:

```json
    "version": "1.1.9.5",
```

Whereas your conflict is:

```json
        {
            "name": "KerbalEngineerRedux",
            "max_version": "v1.1.9.4"
        }
```

*That leading `v` is not insignificant! Quite the opposite, in fact!*

`v1.1.9.4`, _with the `v`_, is **greater** than `1.1.9.5`, _without the `v`._ So RP-1 Express still conflicts with all known versions of KER. Please try fixing that and let us know if these problems persist.

**Comment by Clayell** [comment]
> `v1.1.9.4`, _with the `v`_, is **greater** than `1.1.9.5`, _without the `v`._ So RP-1 Express still conflicts with all known versions of KER. Please try fixing that and let us know if these problems persist.

Gah, formatting! Thanks.
