### ISSUE TITLE
[Bug]:  Reposotory update failed!

### ISSUE THREAD

**Issue by gamerdo** [KSP-CKAN/CKAN#4140]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

v1.12.5.3190

### Games

KSP 1

### Game Version

1.12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Yes I deleted B9 Part swich manualy and then I use Ckan to delet the rest of the mods.

### Describe the bug

Reposotory update failed! I tried reinstalling it  Multlyple times but it dosent work.

### Steps to reproduce

Firts dowload Any mods that uses B9 swich or Berus and blue dog At minimun mods you should have 100 max 130.
Make sure you have far future and Near future istall.
Then go to ksp game data and unistall B9 part swich.
After a few minits or hour the CKan will get confused.
Then when you tried to open it will fail.

### Relevant log output

{
"registry_version": 3,
"sorted_repositories": {
"KSP-default": {
"name": "KSP-default",
"uri": "https://github.com/KSP-CKAN/CKAN-meta/archive/master.tar.gz",
"priority": 0
}
},
"installed_dlls": {
"BlendshapeModelLoader": "GameData/112x_TU_Stock Recolour_v0_3_12/GameData/000_TexturesUnlimited/Plugins/BlendshapeModelLoader.dll",
"TexturesUnlimited": "GameData/112x_TU_Stock Recolour_v0_3_12/GameData/000_TexturesUnlimited/Plugins/TexturesUnlimited.dll"
},
"installed_modules": {
"BreakingGround-DLC": {
"install_time": "2024-08-03T12:28:10.2756093-04:00",
"source_module": {
"spec_version": "v1.28",
"identifier": "BreakingGround-DLC",
"name": "BreakingGround-DLC",
"abstract": "An official expansion pack",
"author": "SQUAD",
"version": "1.7.1 (unmanaged)",
"license": "restricted",
"download": null,
"download_content_type": null,
"kind": "dlc"
},
"installed_files": {}
},
"MakingHistory-DLC": {
"install_time": "2024-08-03T12:28:10.2796069-04:00",
"source_module": {
"spec_version": "v1.28",
"identifier": "MakingHistory-DLC",
"name": "MakingHistory-DLC",
"abstract": "An official expansion pack",
"author": "SQUAD",
"version": "1.12.1 (unmanaged)",
"license": "restricted",
"download": null,
"download_content_type": null,
"kind": "dlc"
},
"installed_files": {}
}
},
"installed_files": {},
"available_modules": {},
"download_counts": {}
}

**Comment by HebaruSan** [comment]
Hi @gamerdo, thanks for the report. There are multiple different problems that might match up with what you're describing, so to investigate this, we will need a screenshot of the error message. If you can provide that, please do, and we can re-open this.
