### ISSUE TITLE
[Feature] Expose license metadata to search UI

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4146]
I saw someone request this on discord.  The higher goal would be to easily find mods that are no longer compatible and have licenses that permit adoption.  On the one hand, this would be a useful tool.  But it also could aid people who may not be able to sufficiently maintain such mods, harming the ecosystem.  In other words, a higher barrier to entry might actually be a good thing.

**Comment by HebaruSan** [comment]
Any thoughts on how the search should work at the level of string matching? Exact match only? Prefix? Any substring? No I am not making it use regexes.

**Comment by JonnyOThan** [comment]
prefix sounds fine.
