### ISSUE TITLE
[Feature] CmdLine: `compat` usability improvements

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4150]
* `ckan compat add` can only add one version at a time.  It would be nice to pass a set of versions, likely separated by spaces.

New command requests:

* `ckan compat set` - explicitly sets the list of compatible versions
* `ckan compat clear` - remove all compatible versions

Currently, there's not a good way to get your compatible versions into a consistent reproducible state.  You'd have to list them all, forget them one by one, and then add the ones you want.  These two commands would make that much simpler.

Alternatively, `ckan compat set` with no versions listed could effectively clear the list so `ckan compat clear` isn't strictly necessary.

**Comment by HebaruSan** [comment]
- Once we have this, we can simplify the validator a bit
  https://github.com/KSP-CKAN/xKAN-meta_testing/blob/f4845f71bd8185e4c4c3f9ac6d689c6eba65ad8b/ckan_meta_tester/dummy_game_instance.py#L38-L41
- The `Compat` class could use some mild refactoring while we're at it; currently everything is in `RunSubCommand` and should probably be split out into `List`, `Add`, `Forget`, `Set`, and `Clear` methods

**Comment by HebaruSan** [comment]
If we make `show` accept multiple values as well, then we can improve the output for special test cases as in KSP-CKAN/NetKAN#10156.

**Comment by HebaruSan** [comment]
@JonnyOThan, these new operations are pretty easy. Got anything more sporting?

What about a `[add|set] --by-game-engine` flag to automatically add 1.8-1.12 to the latest version, and so on?
