### ISSUE TITLE
The screen to select a mod to satisfy a virtual dependency does not filter out mods that are conflicting with other dependencies of the changeset

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4156]
I tried to set up a dependency on TweakscaleRescaled-Redist here, in order to remove an extra virtual dependency screen in the RP-1 install process: https://github.com/KSP-RO/RealismOverhaul/pull/2996

(Note that Tweakscale-Redist is a dependency of FAR)

However, it didn't have the intended effect - the user is still prompted to choose between Tweakscale-Redist and TweakscaleRescaled-Redist.  Worse, if they select Tweakscale-Redist then they're not alerted to the conflict until later:

![image](https://github.com/user-attachments/assets/2e9d9b62-062e-4140-9201-ed26cbca6a3d)

**Comment by HebaruSan** [comment]
Move your new dependency up above `AdvancedJetEngine`. Relationships are evaluated in order, and `AdvancedJetEngine` depends on `FAR` which is provided by `FerramAerospaceResearchContinued` which depends on `TweakScale-Redist`, which gets evaluated before your relationship is checked.
