### ISSUE TITLE
[Feature]: easier distribution for pre-release versions of mods

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4159]
## Motivation

I often put out a pre-release version of mods like RasterPropMonitor and FreeIva and have people alpha-test them for a bit to screen for any new bugs before pushing a wider distribution.  These currently always have to be manually installed since CKAN doesn't pick them up.  It would be nice to make that process a little more streamlined.

## Suggestions

I'd like to explore a way for mod developers to be able to publish pre-release versions of their mods and have users opt-in to receiving them.

I think in the past this has been done by adding metadata repos (for kopernicus?).  This works but feels pretty clunky - and requires a lot of extra work on behalf of the modder to set up.

There are two components that I'd like to see in some kind of system: 

- a way for modders to mark releases as "pre-release" vs "stable"
- a way for CKAN users to opt-in to getting pre-release versions of mods, either:
  - manually from the mod's versions tab
  - on an opt-in basis per mod (e.g. as a label)
  - globally (worst option, but I'd take it if the above aren't possible)

The modder's side of this sort of already exists, at least on github: releases can be marked as pre-release and ckan does not index these.  There is a release_status field in the .ckan metadata - is this actually used for anything currently?  As a weak proposal, what if we indexed github prereleases and set their release_status field?  And then the decision to update or not would be on the client side.

**Comment by HebaruSan** [comment]
Hey @JonnyOThan, could you please give some examples of when/why this would be desirable, to help with planning and prioritization?

**Comment by JonnyOThan** [comment]
Sure.  Specifically I often put out a pre-release version of mods like RasterPropMonitor and FreeIva and have people alpha-test them for a bit to screen for any new bugs before pushing a wider distribution.  These currently always have to be manually installed since CKAN doesn't pick them up.  It would be nice to make that process a little more streamlined.

**Comment by HebaruSan** [comment]
Searching CKAN-meta for existing mods with `release_status` set to anything other than `stable`:

```bash
find . -path ./.git -prune -o -name \*.ckan -print0 | xargs -0 jq -rM 'select(has("release_status") and .release_status != "stable")|{identifier,version,release_status}' > ../prereleases.txt
```

**Comment by HebaruSan** [comment]
lol, Scatterer's netkan has the least stable option:

https://github.com/KSP-CKAN/NetKAN/blob/76f36b8bb18ca7c04594cb29975f19196b694e08/NetKAN/Scatterer.netkan#L9

```yaml
release_status: development
```

We'll probably want to just purge that. If/when we introduce a new setting, the default would probably be `stable`/blank, and it would make absolutely no sense to have one of the top five most popular mods excluded from that. Likewise for a couple of other mods.

**Comment by HebaruSan** [comment]
Hey @JonnyOThan, is there a repo that currently has a prerelease? I have some scratch code going that I'd like to test against the real world.

**Comment by SofieBrink** [comment]
> Hey @JonnyOThan, is there a repo that currently has a prerelease? I have some scratch code going that I'd like to test against the real world.

There’s boring crew services [here](https://github.com/zorg2044/BoringCrewServices/releases), but it currently only has pre-releases and is not yet ckan indexed. It does have an internal .ckan if that helps.

**Comment by JonnyOThan** [comment]
@HebaruSan  Here ya go, hot off the github workflows: https://github.com/FirstPersonKSP/FreeIva/releases/tag/0.2.20.0

**Comment by HebaruSan** [comment]
I mocked up some prereleases in my local metadata, and it works, but I'm not sure about the UI (ignore the weird foreground colors, I'll look into those later):

![image](https://github.com/user-attachments/assets/14896a23-abdc-40a1-8d9c-75dadae499f6)

Any suggestions on how to indicate which versions are not shown as installable because they're prereleases (the top two rows, in this case)? I've thought of these options, which I don't love:

- A new column - Would take up a lot of space for something that's probably a rare corner case
- Some marker in an existing column - easy to confuse with actual versions, not a lot of space to fit something comprehensible
- Italics - Kind of non-obvious and would have to extend the legend section a bit, still probably my favorite option so far

Regardless of how that works out, we have plenty of space to explain it in the popup if they click one of those checkboxes:

![image](https://github.com/user-attachments/assets/dbd9a8b4-7c59-485b-a9e1-388e7a07e59d)

**Comment by HebaruSan** [comment]
Here's what it would look like with italics for prereleases:

![image](https://github.com/user-attachments/assets/02cec372-782b-476c-88b7-53280fbf8242)

**Comment by SofieBrink** [comment]
How about a new row colour & italics, that’d make it more obvious and force the user to check what the version they’re installing in the legend above, maybe purple/pinkish or something?

side note, how does one differentiate between testing and bleeding edge as a modder?

**Comment by HebaruSan** [comment]
> side note, how does one differentiate between testing and bleeding edge as a modder?

I don't know, I didn't create these categories, and the ones who did didn't document a definition that I've been able to find, and sometimes used them interchangeably: https://github.com/KSP-CKAN/CKAN/issues/403#issuecomment-63474063

I guess I would start by taking them literally:

- testing: A prerelease with some less stable changes for a mostly stable existing mod
- development: A brand new mod that isn't ready for wide distribution yet

**Comment by HebaruSan** [comment]
Apparently `testing` was added when `alpha` and `beta` were removed.

https://github.com/KSP-CKAN/CKAN/blob/3a311bb1c121131c4297f932e8b69807aa791dfb/Spec.md#release_status

![image](https://github.com/user-attachments/assets/6905382c-bf87-4ad9-8e2e-45c342d7bf1c)

**Comment by HebaruSan** [comment]
> How about a new row colour & italics, that’d make it more obvious and force the user to check what the version they’re installing in the legend above, maybe purple/pinkish or something?

I don't hate it (this is LightCoral, the bgcolor for conflicts in recommendations and the changeset):

![image](https://github.com/user-attachments/assets/4f12bb19-da91-493c-81aa-de041ba9ec76)

**Comment by HebaruSan** [comment]
Think I can get away with moving the legend to the bottom? It has always kind of annoyed me that it's right up top where your eye can't skip over it no matter how many times you've already seen it before:

![image](https://github.com/user-attachments/assets/840092c8-60d3-41df-9252-68913d59cb25)

**Comment by HebaruSan** [comment]
> * on an opt-in basis per mod (e.g. as a label)

I assume this would need to be not just mod-specific, but also instance-specific? I.e., e.g., this is the game instance where I use pre-releases of ... FARc, and in other instances I use the stable release?

**Comment by SofieBrink** [comment]
> > side note, how does one differentiate between testing and bleeding edge as a modder?
> …
> But ultimately they'll be defined functionally: pick "testing" if you want it to be installed for users who chose `testing` or `development` for the setting, and choose `development` if you only want it to be installed for those who chose `development`.

Right but how do i do this, because github doesn’t specify different types of pre-releases.
Does this then mean i need to edit my internal .ckan file for all releases to tell ckan what to do with this pre-release?
Or worse, if my mod doesn’t have an internal ckan, manually update the netkan?

I don’t personally see a point in having 2 “less-than-stable” options, especially if it’ll require the sorts of shenanigans mentioned above.
I feel like it’ll probably be a bit confusing for users too,
If i read “development - bleeding edge” to me doesn’t sound like a pre-release. It sounds like you’re downloading a commit, which is something ckan doesn’t and probably shouldn’t support.

**Comment by SofieBrink** [comment]
As for the colour and moving of the legend, i think those both look good.

**Comment by SofieBrink** [comment]
> Oh, I misunderstood what you were asking. Yes, in the code that I have in progress, pre-releases would be set to `testing` automatically, and if you wanted to mark a mod even more unstable than that, you'd do it in the netkan or internal ckan. You've called that "worse", but why?

I see, that’s great!
I was under the impression that for each pre-release I made i’d have to manually specify the stability to be “Testing” before then having to put it back to “Stable” for a full release. And under that assumption not having an internal ckan would make that much worse by having to submit a new pr to the netkan repo each time you make a new pre-release or release. 
All that can be ignored though as it’s not what is actually happening.

> Well, 2 options already exist. Our job is to figure out what to do with them. If you don't see any way to do that, then that's fine, you don't have to help with that part.

As for this part, sure i don’t have to help. I’m just pointing out (and perhaps questioning) what the use of the development is. To me now with this added context it sounds like it’ll never be assigned automatically and only be assigned by a modder.

For the other 3 parts about the text around the “Development” label already existing, and suggestions for it being welcome. I guess i’m just trying to understand why it exists in the first place. You say: 
> Well, 2 options *already exist*. Our job is to figure out what to do with them
Is this something that you’re unwilling to change? I feel like conforming to pre-existing types, even when they might not make sense is a little strange, but I’m open to having my mind changed on that if there’s a good argument for it!

**Comment by JonnyOThan** [comment]
I’d really suggest not using coral/red for prerelease versions. It looks too much like a conflict. Yellow or orange would probably be better.

**Comment by HebaruSan** [comment]
Good call. There are a couple of predefined yellow colors available; do any of these look OK?

`Color.Yellow`:

![image](https://github.com/user-attachments/assets/addc6c37-8a3a-440f-b178-9468519887fc)

`Color.LightYellow`:

![image](https://github.com/user-attachments/assets/ba0053e3-b53c-46b8-b267-8f02d570b0ea)

`Color.LightGoldenrodYellow`:

![image](https://github.com/user-attachments/assets/40b1f655-9f53-45be-9802-70cb36e443ff)

**Comment by SofieBrink** [comment]
These are barely noticeable to me, (though that’s probably related to my night shift settings) i’d still like to see what a magenta or something similar would look like. 
To me it feels like a pre-release should stand out, which yellow just doesn’t really do for me.

**Comment by JonnyOThan** [comment]
I like yellow and orange, magenta is also fine.

**Comment by HebaruSan** [comment]
I'll keep adding more colors; it takes a minute or two to compile, run, and screenshot...

**Comment by SofieBrink** [comment]
I'm personally of the opinion that pre-releases aren't supposed to be on spacedock at all.|
But i understand that CKAN probably wants to support it regardless. In which case i don't have any real objections to your proposed solution, assuming you do check that the characters surrounding that string are some kind of seperator type: ` `, `-` etc. to prevent accidentally matching mods such as `AlphaMensaes_Modular_Launch_Pads-2.7.0.zip` and possibly others.

**Comment by HebaruSan** [comment]
Testing it out on Windows, at first I thought Gold looked different, but maybe it's just that the background is different, since it's still partway between yellow and orange:

![image](https://github.com/user-attachments/assets/e1de0b33-9541-4eb9-a890-fc615eef66a7)
