### ISSUE TITLE
[Bug]: Module Manager saying it's already installed when it isn't

### ISSUE THREAD

**Issue by Tyler47412** [KSP-CKAN/CKAN#4165]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 11

### CKAN Version

v.1.34.4

### Games

KSP 1

### Game Version

1.12.5.3190

### Describe the bug

I was trying to install FreeIVA so that I could walk around my ships, it said I needed Module Manager in order for it to work correctly but I knew I already had it from other mods that I had installed. When I click "Install" it says "Module Manager already exists, but it is not in a place where CKAN would install it". The file that it says it is in does not exist. I then tried to install Module Manger itself without anything else and it brings up an error that certain mod dependencies are not satisfied.

### Steps to reproduce

1. Click install of Module Manager
2. Click past all of the suggested items.
3. Module Manager was not installed (Error message said in the "Describe the bug"
4. Try and install it by itself and not as something that gets installed with other mods.
5.  Get error message (Also in "Describe the bug"
6. Try and play without it installed and most of the mods don't work as it is a very big dependency.

**Comment by HebaruSan** [comment]
Hi @Tyler47412, to investigate this we'll need to see screenshots of the error in CKAN and your game folder. If you can add those, please do and we can re-open this.

**Comment by Tyler47412** [comment]
![Screenshot 2024-08-19 205536](https://github.com/user-attachments/assets/5fc7c3a3-39ce-4c26-9434-ed3dea5aba3b)
![image](https://github.com/user-attachments/assets/6c0dddfc-607c-4ab2-b22a-a0fca3646225)
![image](https://github.com/user-attachments/assets/8c57e162-242f-46b4-a8cc-c649ee827630)
![image](https://github.com/user-attachments/assets/0fddc4a9-98c6-4853-bb66-f425618f78fe)

I can't recreate the first error message as it keeps making the second error message pop up and cancelling the download. But the folder that it said that ModuleManager was in was a "GameData" folder that was in the GameData folder that game with the same.

**Comment by Tyler47412** [comment]
Do you need any other screenshots?

**Comment by HebaruSan** [comment]
> I can't recreate the first error message

OK, please let us know if you see it again, and we can take a look.

**Comment by Tyler47412** [comment]
Ok, I will keep trying.
