### ISSUE TITLE
[Bug]: CKAN not finding game instances

### ISSUE THREAD

**Issue by AGardenPeg** [KSP-CKAN/CKAN#4177]
### Is there an existing issue for this?

- [x] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.34.4

### Games

KSP 1

### Game Version

1.12.4

### Describe the bug

Upon starting the .exe it presents me with adding a '**New game instance**' which I click. Then I click '**add instance to CKAN**' and it opens up the file explorer. I go to my KSP folder and then look for '**buildID64.txt**' however the **CKAN.exe** cant detect the file. It only shows the folders in my KSP folder (e.g. **GameData, KSP_x63_Data, Plugins, PluginData, saves, Ships, UserLoadingScreens** ect.) and the **KSP_x64.exe** Application. All the other files and documents wont show up including the buildID64.txt file which is needed for the instance.

This is my first time using CKAN, I've had issues with using Forge and manual install because the mods wont show up. I stress that this is the first time using CKAN and that I have not changed anything about it other than open and run it as well as downloading the dotnet application.

I know I have these files because if I open up my file explorer and look in my KSP folder its all there, but when I do it through CKAN it doesn't detect them. Any help please?

### Steps to reproduce

* open CKAN
* click New Game
* Add instance to CKAN
* locate the 'Kerbal Space Program' folder in the file explorer
* go into the folder
* **no buildID64.txt to click on**

**Comment by HebaruSan** [comment]
Hi, it's not `buildID64.txt` anymore. Click the `KSP_x64.exe`.

https://github.com/KSP-CKAN/CKAN/wiki/User-guide#adding-game-folders
