### ISSUE TITLE
[Bug]: Display problem when multiple labels are used

### ISSUE THREAD

**Issue by kretze** [KSP-CKAN/CKAN#4202]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.35.0

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

If I have 2 or more labels selected and then you scroll up or down, the lines are no longer visible. If you then scroll back to the entries, the text is overlapped.
![image](https://github.com/user-attachments/assets/1c2dac2b-2ac0-42a1-95d0-2ff3d007ae86)

![image](https://github.com/user-attachments/assets/8549d68a-6eba-4016-8631-20f27b43cd1e)

### Steps to reproduce

select 2 or more labels
scroll up or down, the lines are no longer visible.
scroll back to the entries

**Comment by HebaruSan** [comment]
Hi @kretze, thanks for reporting this. I notice that one of those labels has a transparent background color. Does this happen if both labels use actual colors?

**Comment by kretze** [comment]
I redid all the labels. problem still occurs.

I also created 2 test labels. If I select both, the problem occurs.

The colors are chosen from the standard color palette.

label config
[labels.json](https://github.com/user-attachments/files/17170469/labels.json)


![image](https://github.com/user-attachments/assets/aab5e150-06f4-436e-a348-902cf621460f)
