### ISSUE TITLE
[Feature] Ability to suppress missing file checks for files auto-deleted by mods

### ISSUE THREAD

**Issue by kretze** [KSP-CKAN/CKAN#4204]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10

### CKAN Version

1.35.0

### Games

KSP 1

### Game Version

1.12.5

### Describe the bug

CKAN now constantly checks the installed contents of the mods in the gamedata folder.
FAR has a file that is deleted after it has been imported once. As a result, CKAN constantly reports that the FAR file is missing and wants to install an update.

![image](https://github.com/user-attachments/assets/0912dce0-1b17-40b5-bc17-c9c2f24c3b04)

![image](https://github.com/user-attachments/assets/57cd9e7d-c325-424d-b508-408f0cb69bf8)

### Steps to reproduce

install FAR
start KSP and exit
start CKAN again

**Comment by kretze** [comment]
same as #4205

**Comment by HebaruSan** [comment]
> same as #4205

Slightly different use case, though. In that one, the user has explicitly chosen to delete certain files, whereas with yours the mod itself is deleting one of its own files. At this point my expectation is that these would require different solutions.

**Comment by HebaruSan** [comment]
This suggestion from the other issue fits better here:

> A label option comes to mind for this. With a type "no compare" or "no file check".
> Just like it's currently done with "don't upgrade".
> 
> ![image](https://github.com/user-attachments/assets/23c78cbc-07cd-4bf3-8190-b3d32dd8264d)

**Comment by kretze** [comment]
Is this related to the filter extension in the content tab? That didn't happen before.
Commit: Apply filters to Contents tab, red highlight if missing

Therefore this was not reported in V1.34.4 and earlier, correct?

**Comment by HebaruSan** [comment]
Hi @kretze, right, the missing file behavior is new in v1.35.0, see #4067.

**Comment by Delta-86** [comment]
To add to this, this also causes issues with Zero MiniAVC, as any mods it prunes then state that they need to be updated.

**Comment by HebaruSan** [comment]
@Delta-86, yes, it's a good idea to uninstall ZeroMiniAVC anyway, see KSP-CKAN/NetKAN#10230.
