### ISSUE TITLE
[Feature] Ability to suppress missing file checks for user-deleted files

### ISSUE THREAD

**Issue by Sinomen** [KSP-CKAN/CKAN#4205]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Operating System

Windows 10 Pro

### CKAN Version

1.35.0.24270

### Games

KSP 1

### Game Version

1.12.3

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Yes! Changed some CFG-Files, removed some unnecessary files. On purpose.

I did on purpose change/delete some some files of those mods

### Steps to reproduce

Changed some CFG-files, removed unnecessary files I don't need. 
Example: Mod GregroxMultiColorSuitsPack. I only need the red, yellow, and blue suits. To save memory, I removed the other colored suits.
Example: Mod K2CommandPodCont. I only need the 1.25m version, hence deleted the 1.875m version, saving memory.
Example: Mod MissingHistory. I disabled the CFG file SpaceTuxIndustries.cfg, as I'll never have the KANDL engine from LLG.
Example: Mod ModularFuelTanks lacks configuration data for several fuel tanks, hence I added them to the respective CFG-files.

**Comment by kretze** [comment]
A label option comes to mind for this. With a type "no compare" or "no file check".
Just like it's currently done with "don't upgrade".

![image](https://github.com/user-attachments/assets/23c78cbc-07cd-4bf3-8190-b3d32dd8264d)

**Comment by Sinomen** [comment]
> A label option comes to mind for this. With a type "no compare" or "no file check". Just like it's currently done with "don't upgrade".

No, that's not a solution at all. If there is a newer version of a mod, I want to be able to update it via CKAN, even if the update might add/replace files I deleted/modified, as I can easily rectify that later.

But I don't want to have an update notification nagging for a mod that is perfectly working fine, with the same version as already installed, just because I have modified/deleted some files.

**Comment by Sinomen** [comment]
I was hoping for global setting option, not a per-mod setting.

**Comment by Sinomen** [comment]
@HebaruSan No offence, but I changed to the topic to 
Ability to suppress missing / changed file checks for user-deleted / modified files
Hope that's ok with you?

**Comment by HebaruSan** [comment]
Hi @Sinomen, no offense taken. But there is no changed or modified file check, so I'm going to go ahead and change it back. 👍

**Comment by Sinomen** [comment]
I see, ok, my bad, beg your pardon.

**Comment by Sinomen** [comment]
Question: does the file check also cover _additional_ files, or just deleted files?

**Comment by HebaruSan** [comment]
Hi @Sinomen, user-created files are mostly ignored as they always have been. They don't trigger any re-install behavior.

If you want to review them, you can use the File → Unmanaged files... option.

**Comment by Sinomen** [comment]
@HebaruSan  Thank you for your help, much appreciated!

**Comment by HebaruSan** [comment]
@Sinomen thanks. Taking a look at that mod, it does not seem to have any code to create files with a `.prune` extension. Are you sure that's the right mod? Could you maybe share a screenshot of the UI where you do this? I might be able to spot something that could lead to the right mod.

**Comment by HebaruSan** [comment]
A bit of GitHub search-fu later, Looks like it's probably Janitor's Closet.

- <https://forum.kerbalspaceprogram.com/topic/147463-112x-end-your-parts-list-nightmare-introducing-the-janitors-closet/>
- <https://github.com/linuxgurugamer/JanitorsCloset>

**Comment by Sinomen** [comment]
Ah ok, you're right, I mixed the two mods up. Sorry.

**Comment by HebaruSan** [comment]
No problem. 👍 

Investigating how Janitor's Closet works, it looks like another poor substitute for CKAN's installation filters (see #3458). If you ever upgrade or reinstall a mod containing a pruned file, the original file will be re-created by CKAN alongside the `.prune` file, and who knows how JC would react to that, on top of the parts being loaded again. Whereas if the filename is added to CKAN's installation filters, it would never be installed, whether initially or at subsequent upgrades or reinstalls.

This might be another opportunity to advertise CKAN's installation filters in the `abstract` of the mod as we did in KSP-CKAN/NetKAN#10230. Or maybe a "copy pruned file list to clipboard" option could be added to Janitor's Closet that could then be pasted into the CKAN setting, as a form of easier integration between the two. I'll keeep this in mind and maybe contact @linuxgurugamer about it.

**Comment by HebaruSan** [comment]
@Sinomen, does your KSP install have a file by this name?

- `GameData/JanitorsCloset/PluginData/RenamedFiles.dat`

If so, can you share it? It might contain some strings that could be modified and then pasted into the CKAN installation filters.

**Comment by Sinomen** [comment]
Here you go (had the change the extension to txt)
[RenamedFiles.txt](https://github.com/user-attachments/files/17193845/RenamedFiles.txt)

**Comment by HebaruSan** [comment]
OK, I have submitted linuxgurugamer/JanitorsCloset#41 to automatically sync up that mod's pruned files into CKAN's filter list. In my testing, this successfully caused the pruned mods to no longer be shown as missing files. I will contact @linuxgurugamer to see about getting those changes merged and a new version of Janitor's Closet released.

**Comment by Sinomen** [comment]
Sorry again for me mixing up JC and EER, my part mod base ist pretty stable for years, and it's been quite a while since I actively have used JC.

Regrading the pruned files, my idea how to deal with them:

CKAN finds that for a particular mod a specific file abc.xyz is missing.
Check if in the same directory there is a file with the name abc.xyz.prune
If yes, ignore the missing files warning, if no mark that mod as incomplete installed.

This way, no new dependency or even interaction between JC and CKAN arises, and JC could remain unchanged.

**Comment by HebaruSan** [comment]
@Sinomen, no need to worry about that, the new Janitor's Closet release is out now.

- <https://github.com/linuxgurugamer/JanitorsCloset/releases/tag/0.3.9>

**Comment by Sinomen** [comment]
Cool :)
If I read the description correctly, this change is not retroactive, i.e. already pruned files won't automatically create the respective CKAN filter?

**Comment by HebaruSan** [comment]
The filters will be created when the user clicks the Permanent Prune button.

![image](https://github.com/user-attachments/assets/f2219497-86e5-4aa7-81fd-ff3d07508bdc)

**Comment by Sinomen** [comment]
All right, thank you again for your help, and I'm glad that I could make a useful suggestion regarding the pruned files.
Good night.
