### ISSUE TITLE
[Mod]: Error installation 

### ISSUE THREAD

**Issue by Marc67000** [KSP-CKAN/CKAN#4208]
### Mod Name

Half Size Real Solar System Textures - 2048 x 1024

### Author(s)

pap1723

### License

CC-BY-NC-SA

### Homepage link

github

### Download link

https://github.com/KSP-RO/ScaledRSS-Textures

**Comment by Marc67000** [comment]
Via CKAN

**Comment by HebaruSan** [comment]
Hi @Marc67000, are you requesting this mod to be added to CKAN as in the issue description? Or are you reporting an error as in the title?
