### ISSUE TITLE
Pre-CKAN mods fail scenario

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#421]
This is an interesting problem to solve. Here's how to reproduce it:
- Vanilla KSP install with a manually-installed ModuleManager
- Run `ckan scan`, it marks modulemanager as existing
- Install a mod that depends on modulemanager e.g. `ckan install FerramAerospaceResearch`
- Exit ckan and manually delete modulemanager from GameData
- Re-run ckan 
- `scan` now throws because of inconsistencies (FerramAerospaceResearch needs ModuleManager but it's missing), registry doesn't get saved, ModuleManager.dll reference still in installed_dlls
- `install modulemanager` also fails because of the above
- User is stuck, only option is to manually edit registry.json to remove the ModuleManager reference from installed_dlls

**Comment by pjf** [comment]
re-opening and giving to @RichardLake as he grabbed it in the previous repo
