### ISSUE TITLE
[Bug]: Update All button not working, acts like 'sort by update' 

### ISSUE THREAD

**Issue by hngdog** [KSP-CKAN/CKAN#4218]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 10

### CKAN Version

1.35.0.24270

### Games

KSP 1

### Game Version

1.12.5.3190

### Describe the bug

Clicked on Update All. Should select all mods available to update. Instead, sorts the list by the Update field, same as if clicking on the Update field in the listing.

### Steps to reproduce

Click on Update All
No updates are checkboxed.

**Comment by hngdog** [comment]
Manually selecting checkboxes works, can still update.

**Comment by hngdog** [comment]
Not sure if that's the same thing. I don't think I had missing files.  Any way to back out the update of those mods to see?

**Comment by HebaruSan** [comment]
The issue didn't document all the use cases; mods with changed metadata were also affected. If you knew which mods were having this issue, we could check that.
