### ISSUE TITLE
[Feature]:  载具文件修补功能 (translation: Vehicle file patching function)

### ISSUE THREAD

**Issue by sgo123** [KSP-CKAN/CKAN#4219]
### Problem

无法知道载具缺少何种mod零件
(translation: There is no way to know what mod parts the vehicle is missing)

### Suggestion

读取载具文件信息，去补充‘载具’缺少的mod文件
(translation: Read the vehicle file information to supplement the missing mod files of the 'vehicle')

### Additional context

安装新的mod时会导致旧的载具无法使用
(translation: Installing a new mod will cause old vehicles to become unusable)

**Comment by HebaruSan** [comment]
Hi @sgo123, thanks for the suggestion. If Google's translation is accurate, you have a `.craft` file from somewhere and you wish to install the mods required for it to work. This is a function performed by the KerbalX web site:

- <https://kerbalx.com/>

For example:
<https://kerbalx.com/Cheezy/SST-3000-SuperNova>
![image](https://github.com/user-attachments/assets/995841be-d88d-4e2d-8ad3-f422d0da3e67)

I would recommend uploading your craft file there to find out which mods it requires.
