### ISSUE TITLE
Trying to upgrade a manually installed mod fails if it conflicts with another mod

### ISSUE THREAD

**Issue by JonnyOThan** [KSP-CKAN/CKAN#4225]
Repro:

1. Install Deferred using CKAN
2. Manually install RasterPropMonitor (any version)
3. Hit Refresh in CKAN so that it auto-detects RPM
4. Check the "upgrade" box for RPM and hit Apply

Result:

![image](https://github.com/user-attachments/assets/7354c4f3-7995-4c18-aef4-d386d6984982)

![image](https://github.com/user-attachments/assets/645798f9-be4e-4297-9005-63a94722dc00)

This may have something to do with the fact that RPM is incorrectly auto-detected; the DLL name is RasterPropMonitor but the module that contains the DLL is RasterPropMonitor-Core.

**Comment by HebaruSan** [comment]
Hey @JonnyOThan, what happens if you swap steps 1 and 2?

**Comment by JonnyOThan** [comment]
It won't let you install: 
![image](https://github.com/user-attachments/assets/c93382d7-f054-48f4-b8e1-84de7b005e80)
![image](https://github.com/user-attachments/assets/0db5b862-292c-462c-96da-91712bfbc797)

**Comment by HebaruSan** [comment]
Thanks, that's what I thought; at the end of step 2, your registry is already in an "inconsistent" state that it's not supposed to be able to get to, since a conflict is sastisfied among the installed mods and DLLs. So what happens after that is kind of beside the point.

**Comment by JonnyOThan** [comment]
The upgrade operation would have removed that conflict though.
