### ISSUE TITLE
[Bug]: Update not recommended

### ISSUE THREAD

**Issue by Sinomen** [KSP-CKAN/CKAN#4229]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

W10P

### CKAN Version

1.35.3.3173

### Games

KSP 1

### Game Version

1.12.3

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Nope

### Describe the bug

Been wondering, why does CKAN not trigger the update flag?

### Steps to reproduce

Star CKAN
Check for updates, while JC 0.3.8 is installed.
![image](https://github.com/user-attachments/assets/c0bc904f-e18a-44cc-b3cd-30019152ccbc)

**Comment by HebaruSan** [comment]
Hey @Sinomen, thanks for the report. This seems to be working fine for me:

![image](https://github.com/user-attachments/assets/450530e8-8641-4f20-bf6f-a2530554f663)

... so we'll need to know what's different about your computer to proceed.

I guess good places to start would be:

- What other mods do you have installed?
- Is there anything interesting in the bottom left corner of the window, on the status bar?

**Comment by Sinomen** [comment]
The mod list hasn't been changed for many months
Other mods show the upgrade checkbox when I remove the label ignore missing files (see issue #4205)
No Held label is active for any mod
Nothing interesting on the bottom left corner, only the usual "Repositories are up to date"
I could update JC by manually selecting the new version to install

Do you need any config or log files?

**Comment by HebaruSan** [comment]
> - What other mods do you have installed?

**Comment by Sinomen** [comment]
Have a look:
[installed-portable.ckan.txt](https://github.com/user-attachments/files/17335906/installed-portable.ckan.txt)

**Comment by HebaruSan** [comment]
OK, I finished installing your mod list, and it's still working fine:

![image](https://github.com/user-attachments/assets/64adfe01-3bb2-4f80-be2a-6f4bc7ef2536)

> I have installed both mods (Adjustable Mod Panel installed manually, JC via CKAN),
 
Hmm, that means the problem description was not accurate:

> **Did you make any manual changes to your game folder (i.e., not via CKAN)?**
> Nope

Can you please go back and update it so we have a complete and accurate description of what you're doing?

**Comment by Sinomen** [comment]
Got it, could just confirm my suspicion: when I remove Adjustable Mod Panel, JC shows the update checkbox, when I put it back in GamaData again, the checkbox is gone.
Another mystery solved. :)

**Comment by Sinomen** [comment]
> Hmm, that means the problem description was not accurate:
> 
> > **Did you make any manual changes to your game folder (i.e., not via CKAN)?**
> > Nope

Yes and no: iirc, this issue did not happen with earlier versions of CKAN, i.e. - if I actually do remember correctly, question mark - JC showed the update checkbox. I have both mods installed for years, so to be precise: I have not made manual changes to GamaData _recently_.

**Comment by HebaruSan** [comment]
OK, in that case, to further clarify, the question does not _say_ "recently" because that's not what it wants to know.
If you submit more issues in the future, please answer it as it is written and not with extra assumptions like "recently". Thanks!
