### ISSUE TITLE
CKAN no longer working on newest version of MACOS

### ISSUE THREAD

**Issue by calgaryaereo** [KSP-CKAN/CKAN#4237]
Nuff said. 

log:
<img width="1439" alt="Screenshot 2024-10-19 at 12 11 37 PM" src="https://github.com/user-attachments/assets/497c8d3b-3624-4563-bfb7-8f55eb6e45e1">

**Comment by HebaruSan** [comment]
Which version of CKAN are you using?

**Comment by calgaryaereo** [comment]
Penrose

**Comment by calgaryaereo** [comment]
which is where?

**Comment by HebaruSan** [comment]
Where did you get whatever you're using?

**Comment by calgaryaereo** [comment]
https://github.com/KSP-CKAN/CKAN/releases

**Comment by HebaruSan** [comment]
Yeah, download the latest release from there and try again.
