### ISSUE TITLE
The remote certificate is invalid according to the validation procedure during repo update

### ISSUE THREAD

**Issue by Ko4erishka** [KSP-CKAN/CKAN#4239]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 10 Pro

### CKAN Version

v1.35.2.24280

### Games

KSP 1

### Game Version

1.12.5.3190

### Describe the bug

![Снимок экрана (352)](https://github.com/user-attachments/assets/c394db56-883e-49db-9a4b-91e4a7c85574)

### Steps to reproduce

error appears when updating

**Comment by HebaruSan** [comment]
Hi @Ko4erishka, are you able to download that URL in a browser? When this has been reported previously (see #3802, #3814, and #3970), the problem was that the user's computer had been infected by malware that was redirecting certain GitHub URLs.

**Comment by Ko4erishka** [comment]
Hi @HebaruSan, when I tried to download this URL I got a privacy error
![Снимок экрана (353)](https://github.com/user-attachments/assets/ffd1eb72-3d87-4500-9964-7eacbaab471e)

**Comment by HebaruSan** [comment]
Yup, you're infected with something, then. Check your hosts file, the discussions in previous issues give more details.
