### ISSUE TITLE
Parallax Continued (manual install) causing conflict with Deferred

### ISSUE THREAD

**Issue by dewall3** [KSP-CKAN/CKAN#4241]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 11

### CKAN Version

1.35.2.24280

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I have a manual install of Linx's Parallax Continued.

### Describe the bug

The manually installed version of Parallax causes the following conflict: "Deferred 1.2.2.0 conflicts with Parallax 2.0.6 or earlier". This prevents anything from updating (even completely unrelated mods)

### Steps to reproduce

It happens anytime I try to add or update a mod.

### Relevant log output

Inconsistencies were found:
* Deferred 1.2.2.0 conflicts with Parallax 2.0.6 or earlier
Error during installation!
If the above message indicates a download error, please try again. Otherwise, please open an issue for us to investigate.
If you suspect a metadata problem: https://github.com/KSP-CKAN/NetKAN/issues/new/choose
If you suspect a bug in the client: https://github.com/KSP-CKAN/CKAN/issues/new/choose

**Comment by HebaruSan** [comment]
Yup, manual installs are treated as matching regardless of version, because we can't know the version of a manual install.
Any particular reason you're installing manually?

**Comment by dewall3** [comment]
Parallax Continued is not on CKAN. It is different than regular Parallax.

https://github.com/Gameslinx/Parallax-Continued

**Comment by HebaruSan** [comment]
Ah, I see, one of the paid mods. Yeah, those are pretty awkward to interface with CKAN. Sorry!

**Comment by dewall3** [comment]
You mentioned that manual mods are shown as matching by default, but I am
getting a compatibility error. The Parallax Continued app works fine. I
just can't update any of my other regular CKAN apps because of the
"conflict". Is there a way to just ignore any conflicts with manually
installed mods?

**Comment by HebaruSan** [comment]
> Is there a way to just ignore any conflicts with manually installed mods?

No. Sorry!

**Comment by xbdogger21** [comment]
> > Is there a way to just ignore any conflicts with manually installed mods?
> 
> No. Sorry!

But why? Installing mods should be as simple as copying files to the GameData folder. I guess you can get around this by temporarily removing the parallax continued files, using CKAN to install something, and then copying it back.

**Comment by dewall3** [comment]
> > > Is there a way to just ignore any conflicts with manually installed mods?
> > 
> > No. Sorry!
> 
> But why? Installing mods should be as simple as copying files to the GameData folder. I guess you can get around this by temporarily removing the parallax continued files, using CKAN to install something, and then copying it back.

Yeah this seems like something that should be implemented. That said, a simple workaround that works is just to uninstall Deferred from CKAN and install it manually. Deferred is the only conflict causing the issue, so that goes away if it's manually installed. Linx (Parallax author) is working on a better long-term solution, but this temporary fix works for now.

**Comment by HebaruSan** [comment]
The specific issue with Deferred was addressed 3 days ago in when Blackrack removed the conflict in KSP-CKAN/NetKAN#10269.

**Comment by dewall3** [comment]
I'm still getting the same error.

**Comment by HebaruSan** [comment]
Click Refresh.

**Comment by dewall3** [comment]
Already did. Still getting error.

**Comment by HebaruSan** [comment]
@dewall3 did you read my edit above about reinstalling?

**Comment by dewall3** [comment]
> @dewall3 did you read my edit above about reinstalling?

Deferred is completely uninstalled. I cannot install it because I am getting the exact same message. And yes, I clicked refresh.

**Comment by HebaruSan** [comment]
Ah! Sorry about that, the bot stopped running about 4 days ago (cause under investigation). I've re-deployed it and the update to Deferred just went through:

https://github.com/KSP-CKAN/CKAN-meta/commit/5f4cc04f9177edf341312257749c14db21f0517c

That means Refresh was still pulling the old metadata, but it will get the update now.

**Comment by dewall3** [comment]
> Ah! Sorry about that, the bot stopped running about 4 days ago (cause under investigation). I've re-deployed it and the update to Deferred just went through:
> 
> https://github.com/KSP-CKAN/CKAN-meta/commit/5f4cc04f9177edf341312257749c14db21f0517c
> 
> That means Refresh was still pulling the old metadata, but it will get the update now.
> 

Just tried it and it's all good now. Thanks!
