### ISSUE TITLE
[Bug]: When I boot up KSP through Ckan it blackscreens even without mods

### ISSUE THREAD

**Issue by Badman025111** [KSP-CKAN/CKAN#4243]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 10

### CKAN Version

Latest Ckan

### Games

KSP 1

### Game Version

1.12.3

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

When I Boot up KSP through Ckan or the files It bugs out and is a constant black screen

### Steps to reproduce

I Open Ckan Press The Start Button and then it loads ksp but its a constant black screen

### Relevant log output

[KSP.log](https://github.com/user-attachments/files/17532633/KSP.log)
[KSP_x64.gc.log](https://github.com/user-attachments/files/17532634/KSP_x64.gc.log)

**Comment by HebaruSan** [comment]
CKAN doesn't do anything special to launch the game. It just runs it normally.

**Comment by Badman025111** [comment]
Then what should i do @HebaruSan

**Comment by HebaruSan** [comment]
@Badman025111, the KSP forum is back up now, so you can seek volunteer in-game support here:

![image](https://github.com/user-attachments/assets/decdf16a-db62-4cf7-af39-c9161fb72770)
**&rArr;** <https://forum.kerbalspaceprogram.com/forum/70-ksp1-technical-support-pc-modded-installs/>
