### ISSUE TITLE
[Feature]: Configurable keys for menu/actions in ConsoleUI

### ISSUE THREAD

**Issue by DanStaal** [KSP-CKAN/CKAN#4248]
### Problem

macOS already overloads most of the function keys with system-level features.  Notably F10 defaults to 'show all windows', and won't be passed through to applications

### Suggestion

Have some way - either with a preferences file that can be edited without opening the app, or through the in-app menu to allow alternate/preferred choices for the function menu keys.

### Alternatives

Main alternative is for the user to go into System Preferences and disable the system-level features using those keys - which either means doing so every time CKAN is opened, or forces a change to workflow using the computer the rest of the time.

It would be acceptable for a one-off (to get into the menu the first time), but it's a large ask as a permanent solution.

**Comment by HebaruSan** [comment]
Hey @DanStaal, thanks for the suggestion.

Is <kbd>F10</kbd> the only one that has an issue? If not, which other keys are problematic? Picking a better set of defaults for a few hotkeys would be much less costly than creating a data structure, file format, UI, etc. for customization.

**Comment by DanStaal** [comment]
Looking through System Preferences, it looks like the main ones that are overloaded at that level are F10, F11, F14, F15.  The rest are either set in combination with modifier keys or can be switched to/from function key mode.

**Comment by HebaruSan** [comment]
OK, thanks. I know of at least one [CUA](https://en.wikipedia.org/wiki/IBM_Common_User_Access)-stule application ([`aptitude`](https://en.wikipedia.org/wiki/Aptitude_(software))) that uses <kbd>Ctrl+T</kbd> in addition to <kbd>F10</kbd> to open the menu. Maybe we could add that as an alternate hotkey, then make the on-screen tooltip change depending on the OS.

**Comment by DanStaal** [comment]
That would work well.

(I'll admit I'd prefer the ability to use no function-keys at all, but that's largely because I use a third-party ergo keyboard without them.)
