### ISSUE TITLE
ksp-ckan.org

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#425]
http://www.ksp-ckan.org now redirects to https://github.com/KSP-CKAN/CKAN until we have a proper homepage

The server is configured to rewrite URLs properly so stuff like:
http://ksp-ckan.org/releases and http://ksp-ckan.org/issues should work :)

**Comment by hakan42** [comment]
Another one for well-deserved retirement :smile:
