### ISSUE TITLE
Manually installing Parallax Continued still counts as a manually installed DLL even if you also install regular Parallax with CKAN

### ISSUE THREAD

**Issue by Kajto359** [KSP-CKAN/CKAN#4256]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 10

### CKAN Version

v1.35.2.24280

### Games

KSP 1

### Game Version

1.12.5.3190

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Deleted Parallax manually, replaced it with parallax continued

### Describe the bug

![Zrzut ekranu (911)](https://github.com/user-attachments/assets/7b14e445-f751-4a74-9f64-390933048380)
Error while trying to install any mod (Mod that im trying to install not releated to parallax), after replacing parallax with parallax continued (See Steps to reproduce on what I did exactly)

Game works fine

### Steps to reproduce

Have Parallax installed (Alongside stock and scatter textures)
Delete Parallax and stock + scatter textures manually (Through just.. deleting the folders)
Install Parallax Continued (And stock + scatter textures) manually
See error
![Zrzut ekranu (911)](https://github.com/user-attachments/assets/63cc249a-4258-4334-8414-a853bf0aca74)

Extra steps after that I did after the issue occured:
Backed up parallax continued
Deleted Parallax through CKAN
Restored any deleted Parallax files (just one, with the exact same name as in old parallax...)

Did not fix the issue.

**Comment by HebaruSan** [comment]
Hi @Kajto359, can you please show us what the manual installed files look like? I do not have access to this mod and so can't investigate issues with it directly.

**Comment by Kajto359** [comment]
I managed to solve the issue by deleting all of the associated parallax mods through CKAN, then re-installing the previously manually installed files again
