### ISSUE TITLE
[Bug]: CKAN won't run and no error messages are shown

### ISSUE THREAD

**Issue by dbtrnl** [KSP-CKAN/CKAN#4267]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Win10

### CKAN Version

1.35.2

### Games

KSP 1

### Game Version

1.12

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

I did not.

### Describe the bug

I run ckan.exe, the CMD prompt opens and immediately closes, without any error messages or prompts.
Previously CKAN ran without any problems, so i'm unsure on when this started, as i haven't played KSP in a few months.

### Steps to reproduce

Execute CKAN.exe

**Comment by HebaruSan** [comment]
Hi @dbtrnl, thanks for the report.

Can you please try this?

1. Open a command prompt window
2. `cd` to the folder where you saved ckan.exe
3. Type `ckan.exe` and press <kbd>Enter</kbd>

That should allow you to see whatever error is occurring without the window closing.

**Comment by dbtrnl** [comment]
Done that, @HebaruSan, but there's absolutely no output, just a blank line.

I checked the Windows Event Viewer and there was this error event related to some system DLL:

> Nome do aplicativo com falha: ckan.exe, versão: 1.35.2.24280, carimbo de data/hora: 0x11f9da3a
Nome do módulo com falha: KERNELBASE.dll, versão: 10.0.19041.5131, carimbo de data/hora: 0x011921da
Código de exceção: 0xc06d007e
Deslocamento da falha: 0x000000000003b699
ID do processo com falha: 0x3678
Hora de início do aplicativo com falha: 0x01db406ad183f2a5
Caminho do aplicativo com falha: C:\Users\user\Desktop\ckan.exe
Caminho do módulo com falha: C:\Windows\System32\KERNELBASE.dll
ID do Relatório: fd333b73-46f5-4bd6-9962-5d19be49a170
Nome completo do pacote com falha: 
ID do aplicativo relativo ao pacote com falha:

**Comment by HebaruSan** [comment]
OK, I would recommend taking that up with your OS vendor or possibly doing a web search for it. The CKAN team can't fix system DLLs.
