### ISSUE TITLE
[Bug]: Version info not displayed in Help | About dialog box

### ISSUE THREAD

**Issue by JustaSimpleUser** [KSP-CKAN/CKAN#4276]
### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Win 10 Home

### CKAN Version

1.35.3.24345

### Games

KSP 1

### Game Version

12.5

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

No

### Describe the bug

While there is a "Version" label immediately beneath the title in the About dialog, there is no associated information next to the label.  I appreciate that the version info is displayed in the CKAN window title bar but if there's no desire to display the version info in the About dialog, the label is unnecessary.

### Steps to reproduce

Display the Help | About dialog.

![image](https://github.com/user-attachments/assets/d04abdc3-9da0-4e3e-a328-9442256707df)

**Comment by HebaruSan** [comment]
It's still being set, but it wraps because the version string is longer than it was when the About dialog was created, and the label doesn't have `AutoSize` set.
