### ISSUE TITLE
[Bug]: Crash on startup with 1.35+, cannot deserialize a non-array value to type "System.Collections.Generic.List`1

### ISSUE THREAD

**Issue by MCOfficer** [KSP-CKAN/CKAN#4278]
# **IF YOU HAVE THE SAME ISSUE: TRY RESTARTING STEAM**

### Is there an existing issue for this?

- [X] I have checked the existing issues for an existing issue. I even actually looked at the ones that are pinned to the top!

### Operating System

Windows 10

### CKAN Version

1.35.0 / 1.35.2

### Games

KSP 1

### Game Version

/

### Did you make any manual changes to your game folder (i.e., not via CKAN)?

Removed it from the CKAN config to make sure the bug wasn't KSP-related, it happens before the KSP instance is known.

### Describe the bug

Download v1.35.0 or v1.35.2 and run it. A console window pops up with the error, and immediately closes.

1.34.4 works fine, so i'm tentatively pointing towards #4010. According to the `--debug`, it should be between these 2 logs:
https://github.com/KSP-CKAN/CKAN/blob/4a232bd7b86d8df7f666325a3493f05a695af090/Core/SteamLibrary.cs#L27-L46

I removed all non-steam games from my steam library to make sure that wasn't the problem, so i'm guessing there's something unexpected about my `libraryfolders.vdf`. I can provide that file in private if that helps.

### Steps to reproduce

- Download v1.35.0 / v1.35.2
- Run it, GUI or console or console arguments don't seem to matter
- See the error

### Relevant log output

```
$ ckan.exe --debug
27 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
40 [1] INFO CKAN.CmdLine.MainClass (null) - CKAN started.
166 [1] INFO CKAN.SteamLibrary (null) - Found Steam at c:/program files (x86)/steam

Unhandled Exception: System.InvalidOperationException: Cannot deserialize a non-array value to type "System.Collections.Generic.List`1".
   at ValveKeyValue.ObjectCopier.MakeObject[TObject](KVObject keyValueObject, IObjectReflector reflector)
   at CKAN.SteamLibrary..ctor(String libraryPath)
   at CKAN.GameInstanceManager..ctor(IUser user, IConfiguration configuration)
   at CKAN.CmdLine.MainClass.Execute(GameInstanceManager manager, CommonOptions opts, String[] args)
   at CKAN.CmdLine.MainClass.Main(String[] args)
```

**Comment by MCOfficer** [comment]
Oh, I can do you one better.

I just restarted steam, and now everything works. Which would be infuriating, except I still had the `libraryfolder.vdf` open in VSCode, and it caught the change.

I now have a `libraryfolders.vdf` that reliably works, and one that reliably fails, and they only differ in a few lines. lmk how I can get those to you.

**Comment by HebaruSan** [comment]
Glad you got it working!

(We don't maintain the `ValveKeyValue` parsing library or generate these corrupted files, so the details of the syntax aren't something we need to know. You could try reporting it to Valve, but considering how many other corrupted files we've seen from Steam, I'm guessing they probably don't care at all.)

**Comment by MCOfficer** [comment]
Hey,

thanks for the quick reply. I couldn't let it go, so I looked further into it, and I think I know what exactly happened.

Looking into my working .vdf, I can see that the "array" of library folders is arranged like this:
```go
"libraryfolders"
{
	"0"
	{
		// removed data for brevity
	}
	"1"
	{
		// removed data for brevity
	}
}
```
^this excerpt is in fact a valid `libraryfolders.vdf`, and CKAN / the library parses it just fine.

But, one key difference my corrupt file had was a that the "index" sequence skipped a number, like this:
```go
"libraryfolders"
{
	"0"
	{
		// removed data for brevity
	}
	"2"
	{
		// removed data for brevity
	}
}
```
Which is also a valid `libraryfolders.vdf` (as far as Steam is concerned), and elicits the exact error I was seeing.

That's when it clicked. I remember removing one of my steam library folders not too long ago - presumably it used to be index 1 -   which must've caused this jump in indexes. I do not believe steam has restarted since then, and once I did Steam rearranged the indexes to be contiguous again.

Looking into [Valve's documentation](https://developer.valvesoftware.com/wiki/KeyValues#Value_Types), it seems that "skipping an index" is in fact valid - this format is not supposed to be a list, it's something akin to a map/dictionary. But CKAN tries to parse it as a list here:
https://github.com/KSP-CKAN/CKAN/blob/4a232bd7b86d8df7f666325a3493f05a695af090/Core/SteamLibrary.cs#L29
...and once continuity of the indices is broken, that fails.

You could probably make CKAN more "steam-proof" by parsing the file as a Dictionary first, then transforming it into a list. And, failing that, I hope anyone else who has this issue will find this explanation and easy fix: **restart Steam** :)

**Comment by HebaruSan** [comment]
Thanks for that. I guess we can add that workaround.
