### ISSUE TITLE
Add `no-derivates` license to spec

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#431]
I have read [SCANsat's license](https://github.com/S-C-A-N/SCANsat/blob/release/SCANsat/LICENSE.txt) several times now and it appears that it's perfectly fine to redistribute the mod archive. The thing is that NetKAN sets the metadata field to 'restricted' which prevents MirrorKAN from mirroring the mod. 

Poking @DMagic1 and @technogeeky for elaboration :)

I checked the netkan file, it seems the license is hardcoded to 'restricted'

**Comment by Ippo343** [comment]
Closed in #581
