### ISSUE TITLE
`ckan help` is nearly useless

### ISSUE THREAD

**Issue by ToxicFrog** [KSP-CKAN/CKAN#445]
The offline documentation is extremely sparse, but that's ok, because ckan has a built in help command, right?

Well, not so much:
- `ckan help` doesn't list common options like --debug
- `ckan help <command>` produces the same output as `ckan help`
- Running a command without arguments produces help, but...
  - If it's a command that doesn't _take_ arguments, like `update`, it just runs the command
  - Even if it's a command that does, like `install`, it only lists some of the flags, not all of them

The upshot of this is that extremely useful options like `update --repo` or `install --ckanfile` can only be discovered by reading the source.

**Comment by pjf** [comment]
Re-opening with great joy!

**Comment by RichardLake** [comment]
Once again - can people check out 16cd88a17 (based of a old version) and tell me if they think the help is better?

**Comment by mgsdk** [comment]
From a user standpoint I like the help in the version @RichardLake linked over what we have now. I don't know if there is too much difference in the code behind the scenes, but it would be interesting to investigate further.

**Comment by politas** [comment]
Fixed by #2197
