### ISSUE TITLE
GUI: Hitting cancel doesn't cancel an install

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#454]
Steps to reproduce:

1. Select something to install with lots of dependencies (eg: B9) and which you already have cached (not sure if essential, but I have everything cached).
1. Accept the changes.
1. Hit 'cancel' while it's installing.

Note that the status bar at the bottom will continue to show installation progress.

This is almost certainly my fault, as I've removed the ability to signal to ModuleInstaller that we should cancel a process.

Luckily, we *may* have a good work-around. Because `InstallList` is transactionally aware, one can create a transaction and call `InstallList`. When it returns if the user has cancelled the transaction then we simply do a rollback, and if not we perform a commit.

I have no idea what happens if we exit the transaction *while* `InstallList` is running. However if we can terminate the thread running it and then abort the transaction then we might be fine. (The registry will restore its old state on transaction abort, and any file changes will be cleared up.)

**Comment by Postremus** [comment]
I am reopenning this. This Issue exists again since at least 1.5.0. Most likely cause is 327351d667e306ffa72168b5c3c11a107e8f3655.
