### ISSUE TITLE
CKAN-API

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#477]
### A preliminary version of the CKAN-API is now online.
The current starting endpoint is:
```
http://api.ksp-ckan.org/all
```
which is a dictionary mapping module identifiers to a list of tuples that represent the mod's version and the API url.
Also available are:
```
http://api.ksp-ckan.org/latest
```
which is a sorted list of mods updated in the last 24 hours

A list of active CKAN mirrors is available at:
```
http://api.ksp-ckan.org/mirrors
```

### Examples:

To grab the latest FerramAerospaceResearch metadata one needs to fetch:
```
http://api.ksp-ckan.org/FerramAerospaceResearch/latest
```

All the code to generate the API stuff resides in [MirrorKAN](https://github.com/KSP-CKAN/MirrorKAN).

**Comment by pjf** [comment]
Yay! We have an API.

Closing this because we have an API and no further work is needed. :)
