### ISSUE TITLE
GUI Poor UI feedback with conflicting mods.

### ISSUE THREAD

**Issue by RichardLake** [KSP-CKAN/CKAN#500]
On c1837bdb
Select both Neophyte's Elementary Aerodynamics Replacement and Advanced Jet Engines. 
The change-list tab will disappear. 
There are many use cases in which this could be confusing - for example the first time someone uses the program, selects a long list of mods, and can't work out how to install them. 

What would be the best way from a UI perspective to handle this?

**Comment by RichardLake** [comment]
Working on this again.

**Comment by Dazpoet** [comment]
If you get this working you will be my hero!
