### ISSUE TITLE
Let users see mod availability for other versions

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#53]
I'd love something that lets me know which mods support a future (or past) version of KSP, without needing that installed. This means if I'm thinking of upgrading to X, I can see which of my mods are already updated for X, and which ones I have to hope and see.

I have no idea what the interface for this would look like.

**Comment by glubo** [comment]
Related to https://github.com/KSP-CKAN/CKAN/issues/730

**Comment by plague006** [comment]
Closing in favor of #1202.
