### ISSUE TITLE
Show why a mod is automatically installed

### ISSUE THREAD

**Issue by xZise** [KSP-CKAN/CKAN#589]
When installing a mod, it might select other mods to be installed alongside and it would be helpful to know if a mod which was automatically installed because it was required, recommended or suggested (if those were enabled).

**Comment by pjf** [comment]
Re-opening every old ticket for great justice!

**Comment by pjf** [comment]
Closing in favour of #978.

**Comment by plague006** [comment]
Hitting the close button since @pjf seems to have missed. *shrug*
