### ISSUE TITLE
certificate error

### ISSUE THREAD

**Issue by basbebe** [KSP-CKAN/CKAN#596]
Hey!

I'm on a Mac with the latest Mono Hotfix (3.10.0.31).
I'm using CKAN 1.3.0.
My problem also is described [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-3-0-16-Dec-2014?p=1600250&viewfull=1#post1600250) and [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-3-0-16-Dec-2014?p=1603034&viewfull=1#post1603034)

Whenever I try to update, I get the certificate error.
I already ran `sudo mozroots --import --ask-remove`.

```
mono ckan.exe update -d
[…]
Downloading updates...
245 [1] DEBUG CKAN.KSP (null) - Found version 0.90.0
252 [1] INFO CKAN.Repo (null) - Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip
Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip
257 [1] DEBUG CKAN.Net (null) - Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip to /var/folders/m9/3pv9dj4s4r9dlsp0wkf6qzzw0000gn/T/CdFileMgr/d6a2ad03-8cf3-45.tmp
767 [1] DEBUG CKAN.Net (null) - Removing /var/folders/m9/3pv9dj4s4r9dlsp0wkf6qzzw0000gn/T/CdFileMgr/d6a2ad03-8cf3-45.tmp after web error failure

Oh no! Our download failed with a certificate error!

If you're on Linux, try running:
    mozroots --import --ask-remove
on the command-line to update your certificate store, and try again.

```

**Comment by bax-** [comment]
Still getting the same errors. Is anyone else getting them on OS X?
Is there a mono log file I could look into? Didn't find one…

**Comment by bax-** [comment]
I just installed the Git CA manually. No improvement. I guess it's not only about the certificate then!

**Comment by bax-** [comment]
The end of my log shows:

```
Downloading updates...
505 [1] INFO CKAN.Repo (null) - Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip
510 [1] DEBUG CKAN.Net (null) - Downloading https://github.com/KSP-CKAN/CKAN-meta/archive/master.zip to /var/folders/m9/3pv9dj4s4r9dlsp0wkf6qzzw0000gn/T/CdFileMgr/8d1fe339-ab92-47.tmp
1070 [1] DEBUG CKAN.Net (null) - Removing /var/folders/m9/3pv9dj4s4r9dlsp0wkf6qzzw0000gn/T/CdFileMgr/8d1fe339-ab92-47.tmp after web error failure

Oh no! Our download failed with a certificate error!

If you're on Linux, try running:
	mozroots --import --ask-remove
on the command-line to update your certificate store, and try again.
```

So maybe the download is successful but the problem lies somewhere else? Something I could try?
