### ISSUE TITLE
Automator apps for Mac users

### ISSUE THREAD

**Issue by bax-** [KSP-CKAN/CKAN#606]
For interested MAC users:

I created two automator apps to make running CKAN more comfortable.

One starts the CKAN GUI without having to open the terminal:
https://www.dropbox.com/sh/4yv46ogn3p5zv0y/AABiMEGNf-XH4PjP0W8MCtX0a?dl=0

I was having problems updating CKAN on my MAC. That's why I created another automator app. It retrieves a list of CKAN mirrors from the internet, lets you choose one and then updates your CKAN:
https://www.dropbox.com/sh/yiy17879eadaor8/AABDwu7HMlkP4Vt4SHAO5atna?dl=0

The apps have to lie in the same directory as your ckan.exe or otherwise they need to be adapted accordingly.

Everyone feel free to take it and do anything you like with it

**Comment by jbi1031** [comment]
So I can't get either of these apps to open... help?

**Comment by bax-** [comment]
They still do work for me…

Did you install the [Mono framework for OS X](http://www.mono-project.com/download/#download-mac)?

**Comment by jbi1031** [comment]
I do have Mono installed and i have updated the certificates. I unzip the file and launch it and immediately get an error saying "The application “CKAN_update” can’t be opened.” in a pop up. 

I have tried placing it in different folders etc.

Thanks in advance for any help

**Comment by bax-** [comment]
hm… that's strange, no idea what could be causing this. Have you tried editing / opening the app with "automator"?
Is the file in the same folder as the ckan.exe?

**Comment by jbi1031** [comment]
When I try to open it with automator it says this file can’t be opened. ? I’m at a loss

**Comment by SQMah** [comment]
Hi I have the same problem that jbi1031.

Thanks!

**Comment by bax-** [comment]
Strange – I don't know what could be the problem…
Anyhow, this is what the automator app does:

``` applescript
on run {input, parameters}
	
	set CKANpath to POSIX path of ((path to me as text) & "::")
	
	set command to "mono " & CKANpath & "ckan.exe"
	
	try 
	
		do shell script command
	
	on error errMsg
	
		display alert errMsg
		
	end try
	
end run
```

So you could just create a new automator app which simply executes this script.

**Comment by SQMah** [comment]
Thanks!

**Comment by pjf** [comment]
I'm on github closing out all our old issues. Since these are mentioned in the wiki, and I believe no more action is required on the CKAN side of things, I'm marking this as resolved! (Let me know if you think this should be re-opened.)

**Comment by cj81499** [comment]
@bax- Can you post the script for the update application?

**Comment by bax-** [comment]
@cj81499
Look four posts up, it's already there

**Comment by cj81499** [comment]
That's just the open ckan.exe one. I was looking for then update ckan.exe script
