### ISSUE TITLE
Support sha1/md5 fingerprints of downloaded files

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#62]
Right now we just blindly trust any file we download is what the user's after. It would be great if we supported a fingerprint (sha1/md5) field, allowing the ckan client to test that what it downloaded matches what we expect. This would catch incomplete downloads, incorrect versions, and upstream attackers using KSP mods to deliver code to a target machine.

These fields should be optional.

**Comment by dbent** [comment]
The more I think about this the more I realize having a checksum is fine so long as it's fairly strong (SHA256 at least). In this case users would have to trust the CKAN team as an intermediary and the mod author as the originator... but they already do, implicitly, if they're using CKAN. It would at least protect against a 3rd party compromising the upstream host and sending malicious content down.

**Comment by janbrohl** [comment]
Not sure if this belongs here but at least when generating hashes for #/ckan/http/:url you can only make sure netkan and you download the same file - not that it is the one created by the author

A solution woud be to add the possibility to store an author's public key (not even a full certificate) in the netkan files and verify the downloaded zip with it.
