### ISSUE TITLE
[Feature] Mod Roulette

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#626]
Suggested command-line interface:

```
ckan.exe random 10
```

Selects ten mods at random, and if they don't conflict, schedules them for install. If they
do conflict, pick another ten at random, until we have a non-conflicting set, or we've spent
too long trying to find a non-conflicting random set.

For the GUI, suggested interface would be in a menu (not a main button), with some sort of
option to specify how many mods the player wants.

This is kinda cool, because a player can `ckan.exe random 1` to get a random mod (neat
if they want to explore new things in little steps) or `ckan.exe random 50` if they
want to do some crazy stuff on twitch/youtube. :)

This may actually be an anti-feature.

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-support#18
