### ISSUE TITLE
Cant install new mods; "go to changes" always greyed out

### ISSUE THREAD

**Issue by VRPY** [KSP-CKAN/CKAN#646]
The first time launching CKAN, I can install new mods and update them. On subsequent launches, I cant select any new mods to install anymore; I can check them, but the "go to changes" button is greyed out and nothing happens. It does, however, allow for updates to already installed mods.

**Comment by RichardPGoulet** [comment]
I get the same issue here. Go To Changes button is greyed out. version 1.6.19 with ksp .90

**Comment by Dazpoet** [comment]
Assuming that clearing the cache means moving everything out of the downloads folder I'd recommend trying that if it worked for this issue before. You can find it in the CKAN folder in the KSP root directory.

**Comment by RichardPGoulet** [comment]
I tried clearing the cache and, double checked that the downloads folder was empty, still no joy.

**Comment by Dazpoet** [comment]
Does command line work? So we can determine if it's a core problem or a client problem.

**Comment by RichardPGoulet** [comment]
I have not tried command line. I'll find out how, and try it.

**Comment by Dazpoet** [comment]
'ckan install < identifier of mod >' will install a mod :) Do you have any mods installed which require configs installed separetly such as TAC-LS, Astronomers Pack, EVE, Distant Object Enhancement etc?

**Comment by plague006** [comment]
There have been a significant number of CKAN releases since this issue was last followed up on. Is this issue still present?

**Comment by RichardPGoulet** [comment]
Hi, sorry I have not had a chance to try out a new release. I have actually rolled back to an older version which is functional. I will update to the latest release and try again. Thanks.

**Comment by RichardPGoulet** [comment]
I have updated to the latest version and the issue is no longer present. Thanks
