### ISSUE TITLE
normalize version numbers for update comparisions

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN#701]
We have quite a few (at least ScienceAlert :blush:) ckans which fail to upgrade because the original author chose to follow "x.y.rcz" updated by x.y.(z+1), or "vx.y.z" followed by "(x+1).y.z". Basically, strict lexical ordering does not work for J. Q. Addondeveloper.

I suggest we write a version comparator that disregards well-known cases like "v" and "rc", leading to an easier life to J. Q. Addonconsumer.

Of course, teaching developers how to chose proper version numbers would be the much preferred way :stuck_out_tongue_winking_eye:

**Comment by pjf** [comment]
Imma moving this back because we're merging repos!

**Comment by pjf** [comment]
Hooray! I can close this for all the reasons that are in #963. :)
