### ISSUE TITLE
[IMPORTANT] Repo split and new continuous- integration bot

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#707]
Due to Travis not being flexible enough (and also very slow), me and hakan have setup a Jenkins server that tracks PRs and also builds CKAN/ NetKAN from master. It works pretty much the same as Travis except it's a lot faster, more reliable and configurable.

The following repositories are tracked for changes. All PRs will be built and you will see the build result the same way it was with Travis.
- [CKAN-core](http://github.com/KSP-CKAN/CKAN-core)
- [CKAN-cmdline](http://github.com/KSP-CKAN/CKAN-cmdline) 
- [CKAN-GUI](http://github.com/KSP-CKAN/CKAN-GUI) 
- [CKAN-netkan](http://github.com/KSP-CKAN/CKAN-netkan)
- [CKAN-meta](http://github.com/KSP-CKAN/CKAN-meta)
- [NetKAN](http://github.com/KSP-CKAN/NetKAN)

The server itself is at http://ci.ksp-ckan.org, you can login using your GitHub account.
The latest ckan.exe can be found [here](http://128.199.40.123:8080/job/CKAN/lastSuccessfulBuild/artifact/ckan.exe).
Latest netkan.exe is [here](http://128.199.40.123:8080/job/NetKAN/lastSuccessfulBuild/artifact/netkan.exe).
You can follow the Jenkins build logs in #ckan-jenkins at irc.esper.net.
All CKAN/ NetKAN merges get automatic releases in the [CKAN-nightly repo](https://github.com/KSP-CKAN/CKAN-nightly/releases).

The replacement for `.travis.yml` comes in the form of a simple bash script associated with each project called `build.sh`.

What works?
- Pretty much everything
- NUnit tests
- PRs are tracked and reported on
- PRs to the NetKAN PR will be inflated with the latest netkan.exe and installed with the latest ckan.exe (hooray!)
- PRs to the CKAN-meta PR will be installed with the latest ckan.exe

What's doesn't?
- All tests that use 'prove' are not implemented, need @pjf 's help on this one

**Final verdict  =>  from PR to build in 15 seconds instead of 5 minutes.**

**Comment by AlexanderDzhoganov** [comment]
***How to make releases using the new build system***

While not super-automated like the last system was, we do now have a relatively nice way to make new releases using the ckan-release-promoter.py tool. Here is a step-by-step guide on how to do that.

1) Pick [a release from CKAN-nighly](https://github.com/KSP-CKAN/CKAN-nightly/releases) that you want to promote to an official release and copy its Jenkins build URL. For example, if I choose [build 152](https://github.com/KSP-CKAN/CKAN-nightly/releases/tag/jenkins-CKAN-152) I will need "http://ci.ksp-ckan.org:8080/job/CKAN/152/"
2) Clone KSP-CKAN/CKAN, all of our build tools are there for now
3) Navigate to CKAN/bin
4) Run `python ckan-release-promoter.py <args>`, where the necessary arguments are described below:
`--user USER` - Your GitHub username
`--token TOKEN` - Your GitHub password (or app. token)
`--repository REPOSITORY` - The repository in which to create the release, you want this to be `KSP-CKAN/CKAN` for now
`--jenkins-build URL` - The build URL from step 1
`--release-version VERSION` - The CKAN version to stamp the .exe with, should be in the format vX.Y.Z e.g. v1.5.1
`--name NAME` - The name of the release e.g. "Galactic Center"
`--draft` - Optional, post the release as a draft, defaults to false
`--prerelease` - Optional, post the release as a pre-release, defaults to false

**Comment by hakan42** [comment]
Note to self : check if contents can be or already have been migrated to the wiki, then finalize this ticket.

**Comment by Dazpoet** [comment]
All information added to wiki, closing and removing from IRC topic.
