### ISSUE TITLE
Version comparison changes

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#715]
I have started working on a new version comparison algorithm for CKAN, specifically as it is implemented in ArchLInux's vercmp utility (as suggested by @dbent in [this issue](https://github.com/KSP-CKAN/CKAN-meta/issues/196)). The relevant source can be [found here](http://code.toofishes.net/pacman/doc/version_8c_source.html). This will be implemented in C# in a separate library, probably called CKAN-utils, so that it can be used by all of our tools.

**Comment by pjf** [comment]
Closing this out. We have [this policy](https://github.com/KSP-CKAN/CKAN/blob/master/policy/version-comparison.md) for mods with funny version names, and #834 for mods with more sensible ones. :)
