### ISSUE TITLE
Crashes on trying to install Real Solar System

### ISSUE THREAD

**Issue by TinyPirate** [KSP-CKAN/CKAN#716]
Haven't had any trouble with CKAN until today when I tried to install RSS. It crashed (more to come). I then tried installing RSS on a clean install of RSS. Crashed again. The screenshots I've listed here show the mods being installed. Next step - it gets to 0KB done and sits there, seemingly forever (I've left it for a few minutes). I press "cancel" and get taken to screenshot two, whereupon CKAN crashes.

http://i.imgur.com/j8atsue.png
http://i.imgur.com/EemYUli.png

I've tried running CKAN in administrator - no difference.

**Comment by AlexanderDzhoganov** [comment]
Hey, thanks for the report, looking at this now.

**Comment by TinyPirate** [comment]
To refine: I believe this is an issue with the KerbalStuff site - I reckon that the downloads on that site are being blocked to CKAN somehow. 

![ckanbug3](https://cloud.githubusercontent.com/assets/10363264/5592096/09deaa36-9219-11e4-983a-049e45b9f53f.png)

Here's an example where a single mod on KerbalStuff isn't getting got - removing it - things download and it's happy.

**Comment by TinyPirate** [comment]
I'm left wondering if having MULTIPLE files trying to be got from KerbalStuff causes the crash. I'm trying to test it now.

**Comment by AlexanderDzhoganov** [comment]
I am pretty sure that KerbalStuff is down at the moment.

**Comment by TinyPirate** [comment]
Ok so right now I'm trying to get CKAN to install BoxSat, Chatterer, Orbital Material Science and SmartStage and it hung at 95 % and then said the below when I hit cancel. No, I can't get the more details :( 

![ckanbug4](https://cloud.githubusercontent.com/assets/10363264/5592112/97f306b8-921a-11e4-9c02-491a9dbb252a.png)

**Comment by TinyPirate** [comment]
LOL, KerbalStuff is now, FINALLY showing as down for me. That could explain things. I guess?

**Comment by AlexanderDzhoganov** [comment]
Thanks for the info, if you have anything else just throw it here.

**Comment by TinyPirate** [comment]
I guess there's some work to be done on handling failures to get something as right now it's crashing the client?

**Comment by AlexanderDzhoganov** [comment]
The crash issue has been solved in [1.5.1](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.5.1).

**Comment by TinyPirate** [comment]
Arg! Thanks! I am not using it yet. Heck. ...adding an "update-me" alert - next job! ;)
