### ISSUE TITLE
KSP-CKAN Mod Loader

### ISSUE THREAD

**Issue by Almagnus1** [KSP-CKAN/CKAN#726]
Taking a note from Minecraft (Minecraft Forge specifically - http://www.minecraftforge.net/wiki/ ), and what they do in their modded scene, maybe it's time to consider doing more from RAM, and less from disk, with a KSP-CKAN Mod Loader mod.

The idea is to will largely sidestep the issues that #653 and #700 raise, as the install process becomes "install loader mode, then put files in directory".

The other upside to doing this is to enforce using optimal texture formats, and also enforce a standard mod structure, and enable runtime enforcement of stuff.  This makes it harder for users to hack stuff and do what what Spid did in http://forum.kerbalspaceprogram.com/threads/103196-?p=1627784&viewfull=1#post1627784 .

Using something like DotNetZip ( http://dotnetzip.codeplex.com/ ) would allow the ability to read from zip files, so data doesn't need to be persisted to disk.  There would probably need to be a config and data folder for the mods, should they need to persist information like user configs, and other such stuff to disk, but each config and data folder should be separated out by mod identifier so that the mods only fight with each other in RAM, and don't make a mess of the disk.

**Comment by plague006** [comment]
Over a year and no reply, I think it's safe to say there's no interest in implementing this at this time or in the near future. Will slap a "support" tag to give people a week to chime in if it isn't the case.
