### ISSUE TITLE
Universal Storage KAS Pack fails to install (overwrite file error)

### ISSUE THREAD

**Issue by adrianpavone** [KSP-CKAN/CKAN#728]
Universal Storage [KAS Pack] won''t install when selected through CKAN because it tries to overwrite a file (multiple iirc from manually installing it) from the base mod Universal Storage.

This error also occurs if you only select Universal Storage[KAS Pack] without selecting Universal Storage (and so it is added as an automatic dependency). Error also occurs both ways (if you install Universal Storage first error states Universal Storage as owning mod, if both install at same time (and KAS installs first) error states KAS as owning mod when Universal Storage tries to install).

Have attempted an update since first getting error and error persists. Additionally I only use CKAN GUI, unsure if issue occurs in command line (although it should).

Issue also reproduced after updating CKAN to 1.5.3 (same error, only CKAN Version changes).

Full output below:

About to remove:
Done!
About to install...
 * UniversalStorage-KAS 1.0.0 (cached)
 * UniversalStorage 1.0.90.1 (cached)

Module "Universal Storage [KAS PACK]" successfully installed

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at: https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:
File           : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage 1.0.90.1
Owning Mod     : UniversalStorage-KAS
CKAN Version   : v1.5.2-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by dbent** [comment]
This is probably because there are no longer separate mod packs for Universal Storage, only a single pack which enables features dynamically using ModuleManager. Just installing Universal Storage should get you what you need and the KAS pack should be considered obsolete.

Suggestion for devs: New metadata like a [replaces](https://wiki.archlinux.org/index.php/PKGBUILD#replaces) relationship could handle this more cleanly in the future.
