### ISSUE TITLE
Allow users to mark mods as favourites

### ISSUE THREAD

**Issue by rriegner** [KSP-CKAN/CKAN#730]
When KSP is updated, all mods lose official compatibility. A 'Favorite' attribute (and subsequent filter) would make checking any user's standard set of mods for compatibility quick and easy. 

An additional/alternate option would be to allow ticking of the install box for an incompatible mod with a per-mod option to:
1. Install anyway with incompatibility warning
2. Install when compatible version is released

**Comment by pjf** [comment]
We should definitely allow users to mark mods as favourites. Popping this in the enhancement queue.

**Comment by plague006** [comment]
Closing this for https://github.com/KSP-CKAN/CKAN/issues/1677
