### ISSUE TITLE
Can not install UniversalStorage CKAN Version

### ISSUE THREAD

**Issue by Maj-TomQ** [KSP-CKAN/CKAN#731]
CKAN will not install : GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.3-0-g0000000 (beta)

**Comment by mgsdk** [comment]
Are you trying to install both Universal Storage and the Universal Storage KAS pack? Recent changes to Universal Storage has rolled all the expansion packs into the main pack, and use module manager to enable them if the required mods are installed, so you only need the main pack.

**Comment by Maj-TomQ** [comment]
I was :(.
I looked at the folders and found the problem.
 Thank You for the quick reply

**Comment by Ajna** [comment]
i just had this problem too, leaving out  UniversalStorage-KAS 1.0.0 seems to work. i'm on CKAN v1.5.5-0-g0000000(beta)
