### ISSUE TITLE
Roll in support for pruning of parts/textures

### ISSUE THREAD

**Issue by mgsdk** [KSP-CKAN/CKAN#733]
With the issues 64 bit KSP has, it can be necessary to remove (prune) parts and textures is you are a heavy mod user (Even with texture compression) or want to add visual enhancements. Finding https://github.com/Felger/AutoPruner has made this easier, and I'm thinking of rolling support for this into CKAN. This would help with streamlining the update process of mods containing user-pruned files, and allow for configuration files removing all redundant parts for the users of procedural generated parts (Fairings, fuel tanks etc.).

Any thoughts on this before I commit too much time to this? It may be a bit outside the scope of CKAN.

**Comment by JamesFaraday** [comment]
A bit late, and I don't know if this is relevant to your project. However, are you aware of  http://forum.kerbalspaceprogram.com/threads/106363-CKAN-plugin-CKAN-PartManager-v1-0-Selectively-remove-parts-from-mods ? The plugin seems to have similar goals.

**Comment by mgsdk** [comment]
Yes, though it lack the support for removing parts of the core KSP (Squad and Nasamission folders). I also had an odd issue with Active Texture Management where it would load the textures from parts disabled with the mod.

For now I just manually rename the files to avoid loading them, and see where PartManager goes in the future.

**Comment by AlexanderDzhoganov** [comment]
This most likely won't be implemented in the base client.
