### ISSUE TITLE
Add step to Installing CKAN on Ubuntu 14.04

### ISSUE THREAD

**Issue by msholly** [KSP-CKAN/CKAN#735]
I'm a newbie with Ubuntu, installed it just for 64bit KSP. But I ran into an issue installing CKAN from your instructions here:

https://github.com/KSP-CKAN/CKAN-support/wiki/Installing-CKAN-on-Ubuntu-14.04

You should also add something like 

- Go to Ubuntu Software Center, search for mono-complete.
- Install mono-complete

These instructions should be after import certificates. CKAN wouldn't work unless I followed your entire guide AND installed mono-complete from the software center. 

BUT! hey I could be wrong!

Thank you for making CKAN, its a HUGE help.

**Comment by AlexanderDzhoganov** [comment]
Thanks, the wiki has been fixed.
