### ISSUE TITLE
Unhandled exceptions, both gui and cli, on Windows XP

### ISSUE THREAD

**Issue by tjanke42** [KSP-CKAN/CKAN#736]
Love the idea!  But CKAN won't work for me.  Much sadness.

CKAN                        v1.5.6-0-g0000000 (beta)
OS                          Windows XP 5.1.2600 Service Pack 3 Build 2600
System Manufacturer         ASUS
System Type                 X86-based PC
Processor                   x86 Family 15 Model 35 Stepping 2 AuthenticAMD ~2410 Mhz
BIOS Version/Date           American Megatrends Inc. 1009, 12/14/2005
SMBIOS Version              2.3
Hardware Abstraction Layer  Version = "5.1.2600.5512 (xpsp.080413-2111)"
Total Physical Memory       3,072.00 MB
Available Physical Memory   1.30 GB
Total Virtual Memory        2.00 GB
Available Virtual Memory    1.96 GB
Page File Space             5.04 GB

In the GUI, clicking Refresh switches to the Updating Repositories tab, the green cylon indicator begins sweeping back and forth, then a small dialog pops up saying "Error!  Failed to connect to repository.  Exception: The underlying connection was closed: An unexpected error occured on a send.", and the OK button in the dialog box is cut off.

![error dialog](https://cloud.githubusercontent.com/assets/1124476/5654123/1db04820-9675-11e4-8ec3-8fa942c234ea.png)

in the right panel, clicking the Relationships or Contents tab brings up an Unhandled Exception dialog box complaining about a null value:

![null value](https://cloud.githubusercontent.com/assets/1124476/5654257/1a0f82a2-9676-11e4-8cf9-4f76f0e4fae6.png)
 
Clicking the Details button in the dialog gives you the following:

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: node
   at System.Windows.Forms.TreeNodeCollection.AddInternal(TreeNode node, Int32 delta)
   at System.Windows.Forms.TreeNodeCollection.Add(TreeNode node)
   at CKAN.Main._UpdateModDependencyGraph()
   at CKAN.Util.Invoke[T](T obj, Action action)
   at CKAN.Main.UpdateModDependencyGraph(CkanModule module)
   at CKAN.Main.ModInfoIndexChanged(Object sender, EventArgs e)
   at System.Windows.Forms.TabControl.OnSelectedIndexChanged(EventArgs e)
   at System.Windows.Forms.TabControl.WmSelChange()
   at System.Windows.Forms.TabControl.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.NET/Framework/v4.0.30319/mscorlib.dll

----------------------------------------
ckan
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///G:/KSP tools/ckan.exe

----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll

----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll

----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll

----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll

----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll

----------------------------------------
15fqcljl
    Assembly Version: 0.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll

----------------------------------------
System.Transactions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Transactions/v4.0_4.0.0.0__b77a5c561934e089/System.Transactions.dll

----------------------------------------
System.Numerics
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll

----------------------------------------
System.ComponentModel.DataAnnotations
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.DataAnnotations/v4.0_4.0.0.0__31bf3856ad364e35/System.ComponentModel.DataAnnotations.dll

----------------------------------------
System.Runtime.Serialization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll

----------------------------------------
System.Xml.Linq
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 built by: RTMRel
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml.Linq/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.Linq.dll

----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll

----------------------------------------
System.EnterpriseServices
    Assembly Version: 4.0.0.0
    Win32 Version: 4.0.30319.1 (RTMRel.030319-0100)
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_32/System.EnterpriseServices/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.EnterpriseServices.dll

----------------------------------------
----------------------------------------

Similarly the CLI refuses to work.  The command "ckan update" triggers a visual studio JIT debugger dialog, complaining about "An unhandled win32 exception occured in ckan.exe (7608)":

![croppercapture 73](https://cloud.githubusercontent.com/assets/1124476/5654386/3a2fbf56-9677-11e4-8998-2566a3c5df84.png)

**Comment by AlexanderDzhoganov** [comment]
I'm sorry, Windows XP is not supported.

**Comment by tjanke42** [comment]
I thought CKAN runs on Mono, in which case it's targeting the Mono VM (not the underlying OS).  Please educate me if I'm wrong, but doesn't that make the underlying windoze version irrelevant?

**Comment by AlexanderDzhoganov** [comment]
CKAN doesn't use Mono on windows, it uses the default .NET stack. You may have luck running it using Mono (with [this guide](http://www.mono-project.com/docs/getting-started/install/windows/) or something), but we can't waste time chasing down problems with this approach.

**Comment by tjanke42** [comment]
Thanks for the clarification!  I certainly understand not supporting workarounds like that (I wouldn't either).
