### ISSUE TITLE
[REQUEST] Manual archive inclusion

### ISSUE THREAD

**Issue by Aquilux** [KSP-CKAN/CKAN#741]
I'm not sure if this is available already, but I can't seem to figure it out if it's there.

I'd like to be able to specify a folder (manual inclusion, local repository, ect.) to be able to have CKAN handle the installation of a manually downloaded file. Maybe CKAN could manage a database of these mods that people have installed to build incompatibility/dependency listings?

**Comment by Dazpoet** [comment]
I've read this a few times now but I'm not sure I understand fully what you're after. To install a manually constructed or downloaded .ckan file you'd just do `ckan install -c path/to/file.ckan` and it will install that file. It won't check for updates unless you also build netkan/mirrorkan and set up some local stuff, which I assume wouldn't be impossible.

There are more than a few people out there running their own hacked together .ckan files, myself being one of them when I feel like playing around with mods that aren't 100% compatible with my KSP version or I feel like filtering out some stuff from a certain mod. As long as you add your own identifiers the command line client will keep track of the mods and they won't collide with stuff in the official repositories.

**Comment by pjf** [comment]
> I'd like to be able to specify a folder (manual inclusion, local repository, ect.) to be able to have CKAN handle the installation of a manually downloaded file. Maybe CKAN could manage a database of these mods that people have installed to build incompatibility/dependency listings?

The CKAN depends upon metadata, and so if we don't have the metadata for a file, we can't install and manage it. It's certainly possible to do what Daz suggested with `ckan install -c`, and I'd *really* love us to give users a set of tools for being able to create their own metadata to essentially allow what you're asking for while still being able to maintain our model, but that's likely to be some distance in the future.

So, yes, we'd love to make it easier for folks to initiate their own machine-only metadata rebellion, but alas doing this is likely to be months away at the earliest.
