### ISSUE TITLE
Support syncing mods between different machines

### ISSUE THREAD

**Issue by henrybauer** [KSP-CKAN/CKAN#743]
With installed-default.ckan (http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-5-0-24-Dec-2014?p=1661157&viewfull=1#post1661157) we can install all the mods from computer 1 on to computer 2.

However this doesn't support the case where computer1 has mods A,B,C, but computer2 has mods B,C,D, and computer3 has mods A,C,D.  For example your win32 machine has ActiveTextureManagement and your lin64 machine does not, and your lin64 machine has a bunch of crazy high-memory beautification mods.

What I'd like to see is a common registry of mods, so that we can install/update/remove on one machine, then the other machines can apply the changes as well.  This way I don't install Karbonite on one machine and forget to install it on another.

Assume that Dropbox/Google Drive/whatever is already syncing a file/directory of our choice, and that CKAN is only run on one computer at a time.

In that synced file, we could have:

Mod1:
--- default: install
--- computer1: override-remove
Mod2:
--- default: install
Mod3:
--- default: remove
--- computer2: override-install

Then, when I'm on computer1, I can say "install Mod4", which will add to the common repository:

Mod4:
--- default: install

Then when I go onto computer2, it will say "Mod4 was installed on another computer, do you want to install on this one too?"  If I say yes, install it.  If I say no, add:

Mod4:
--- default: install
--- computer2: override-remove

Upgrades can be handled through the normal system; this is just whether a mod is installed or not.

**Comment by plague006** [comment]
This sounds interesting. But is it within the scope of what CKAN aims to be?

Pinging @pjf: the man with the vision, to answer that.

**Comment by plague006** [comment]
Making a call that this is beyond the scope of CKAN.
