### ISSUE TITLE
B9 forces RasterPropMonitor even if its installed

### ISSUE THREAD

**Issue by Grim187** [KSP-CKAN/CKAN#745]
RasterPropMonitor is force installed with B9, which conflicts if its already installed.
(I had to manually uninstall it to get b9 installed)
the conflict starts with "GameData\JSI\RasterPropMonitor\Library\Components\HUD\heading.png"

also it would make things alot easier if i could uncheck or delete things from the changelist, rather than have 1 in 20 have a problem and have to clear the list.

**Comment by Dazpoet** [comment]
Unable to reproduce, is this still a problem?

**Comment by Dazpoet** [comment]
Closing this as I am still unable to reproduce it.
