### ISSUE TITLE
[Request] Verbose mode for CLI update

### ISSUE THREAD

**Issue by bk2w** [KSP-CKAN/CKAN#748]
Add a switch to the CLI "update" command that lists what new mods have been added to (or removed from) the just-downloaded registry.

With nearly 300 mods in the registry, it can be quite difficult to identify newly supported mods just by reading the list of available mods. This was really evident in the days after 0.90 came out, when I was waiting for several mods to be updated, but had to manually scan the "available" list to see when they were available through CKAN.

**Comment by hakan42** [comment]
This issue was moved to KSP-CKAN/CKAN-cmdline#42
