### ISSUE TITLE
Overwrite Error: Packaging Bug

### ISSUE THREAD

**Issue by proconsul** [KSP-CKAN/CKAN#749]
I just received this error while trying to install a series of mods. Most notable Universal Storage and the KAS extension. 

Hope it helps

GameData/UniversalStorage/Parts/US_1R110_Wedge_KASContainer/KASContainer.tga
Installing Mod : UniversalStorage-KAS 1.0.0
Owning Mod     : UniversalStorage
CKAN Version   : v1.5.6-0-g0000000 (beta)

**Comment by hakan42** [comment]
Duplicate report, though thanking you for writing this up :smile:

The universal storage addon is one package with ModuleManager files now, you do not need the US-KAS addon anymore. Try deleting that first and running an update of the core afterwards.
