### ISSUE TITLE
vref handler for kerbalstuff

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN#752]
The Jenkins, Github (pre-release) and HTTP inflators can't use the rich metadata provided by Kerbalstuff.

I suggest adding a line like

```
"$vref" : "#/ckan/kerbalstuff/303",
```

in syntax very similiar (o.k., identical) to the $kref line, to enhance the metadata created by the aforementioned Inflators

**Comment by hakan42** [comment]
Note to self : the  TestFlight addon of @jwvanderbeck has releases on github and kerbalstuff, and an avc entry, so might be a good testcase for multiple vref support...

**Comment by plague006** [comment]
I suspect we can close this.
