### ISSUE TITLE
Astronomers Pack suggested CKAN installation order

### ISSUE THREAD

**Issue by msholly** [KSP-CKAN/CKAN#755]
I saw both Eve and Astronomer's Pack is available via CKAN now. Downloaded manually, Astronomer's pack requires the downloading of EVE as its core (step 1). 

Installing Astronomer's Pack after EVE in CKAN has this error message:

The following inconsistecies were found:
AstronomersPack-Clouds-High conflicts with EnvironmentalVisualEnhancements-HR.
Error!

What is the suggested installation technique to have both running?

Also in the posting of this issue, I also found that inconsistencies was misspelled in the error message.

Thanks as always!

**Comment by sparkybear** [comment]
Only install the base of EVE. The clouds and texture packs for EVE are overwritten by Astronomer's regardless, but to not get that error, just install the base EVE without the configurations.

**Comment by Dazpoet** [comment]
Choose the astronomers pack you want installed through CKAN and it will fix the dependencies for it without you having to order stuff in a specific way.

**Comment by pjf** [comment]
This looks like it's a resolved support issue, so I'm resolving it! :)
