### ISSUE TITLE
Ship Manifest versioning issue

### ISSUE THREAD

**Issue by PapaJoesSoup** [KSP-CKAN/CKAN#756]
I've been getting reports that my versioning is causing issues for users.

I (incorrectly) created a version (Shipmanifest-Shipmanifest.90.0.3.3.3  that is showing as the latest version.

I've subsequently uploaded a newer version with correct version naming (ShipManifest-0.90.0_3.3.4) which follows all previous versions with the exception of the one I first mentioned.

I'm tring to figure out how I can correct this so that CKAN correctly reports 0.90.0_3.3.4 as the latest version.  I noted a .ckan file for this version exists (created by your bot, but for some reason when I use the CKAN.exe, it reports Ship Manifest varsion 3.3.3...as the latest... :(

What steps do I need to take to resolve this?   I did a pull request to change the version, but not sure that will correct it.

thanks!

**Comment by hakan42** [comment]
Nope, the PR will not work the way you intended. 

We compare versions alphabetically, which means the version starting with "S" will always be more current than anything with "0" to "9"

The best bet would be to remove the broken version from CKAN-meta but that would leave people having installed that version in a state where they never see any updates anymore. 

If we remove the version, could you please make a post on your thread that people have to uninstall their addon and re-install to get the proper version?

**Comment by PapaJoesSoup** [comment]
I will be happy to.   I will also note the alphabetical nature of the parser for future reference.
Thanks!
