### ISSUE TITLE
Cannot find Valid Install

### ISSUE THREAD

**Issue by randysdoom** [KSP-CKAN/CKAN#757]
CKAN is saying it can't find a valid install but it is there. http://prntscr.com/5u9d24

**Comment by mgsdk** [comment]
CKAN currently depends on the readme file in the KSP directory to determine the KSP version, but from your screenshot it is not there. You could try to get Steam check your local files, which should recreate it.

I can't recall if Steam will delete saves/mods while doing this, so perhaps you should do a backup of those prior to checking your local files.

**Comment by randysdoom** [comment]
Yes, Validating Steam Install fixed it, Thank you.
