### ISSUE TITLE
Can't use plugins

### ISSUE THREAD

**Issue by MrGreenTea** [KSP-CKAN/CKAN#758]
When I try to use plugins I always get this error:
```
3304 [1] ERROR CKAN.URLHandlers (null) - Error: Parsing Error: Could not parse file ~/.local/share/applications/mimeapps.list
3336 [1] WARN CKAN.PluginController (null) - Failed to load assembly "\home\jonas\.local\share\Steam\steamapps\common\Kerbal Space     Program\CKAN\Plugins\MigrationToolPlugin.dll" - Could not load file or assembly '\home\jonas\.local\share\Steam\steamapps\common\Kerbal Space Program\CKAN\Plugins\MigrationToolPlugin.dll' or one of its dependencies. The system cannot find the file specified.
```
I am using linux, so I guess the problem are the backslashes. windows uses \ but linux uses / for file paths.

**Comment by mgsdk** [comment]
Removing line 37 in CKAN-GUI/PluginController.cs (Which renames "/" to "\") does fix it in linux for me. Seeing as that line came in as a fix in https://github.com/KSP-CKAN/CKAN-GUI/commit/5bf5866b064aef55be187edd93cf45bb3d290307 it is probably there for a reason.

Pinging @AlexanderDzhoganov for this one.

**Comment by MrGreenTea** [comment]
So I would have to build it myself for now? Is there any help on this, because I haven't done it often.
Also, would it be possible to only rename "/" to "\" if ckan is executed in a windows environment?

**Comment by mgsdk** [comment]
I do not know the reasoning for the change, or if removing it will cause any malfunctions.

I made a temporary release [here](https://github.com/mgsdk/CKAN-GUI/releases/tag/1.5.6%2B), but no guarantees.

**Comment by MrGreenTea** [comment]
Thanks, but I get this error when I try to start it:
`Cannot open assembly 'ckan.exe': File does not contain a valid CIL image.`

**Comment by mgsdk** [comment]
Might be that I have a different build setup than the official release server. I've tried to get the build server to do it for me. See if http://ci.ksp-ckan.org:8080/job/PR%20builder%20-%20CKAN-GUI/59/artifact/ckan.exe works for you.

**Comment by MrGreenTea** [comment]
Thanks a lot. The plugins seem to work now!

**Comment by AlexanderDzhoganov** [comment]
The [offending line](https://github.com/KSP-CKAN/CKAN-GUI/commit/5bf5866b064aef55be187edd93cf45bb3d290307) can be removed, it was used for testing something and I forgot it.

**Comment by bax-** [comment]
I also have a problem when trying to use Plugins on OS X yet I don't know if it has the same cause.
I'm using the GUI.
When I copy my plugins into CKANs plugins folder, they aren't automatically detected.
When I manually add them, nothing happens at all.
I can open another issue if this is not related.

**Comment by hakan42** [comment]
Fixed with https://github.com/KSP-CKAN/CKAN-GUI/pull/48
