### ISSUE TITLE
ckan doesn't find installed libgluezilla

### ISSUE THREAD

**Issue by MrGreenTea** [KSP-CKAN/CKAN#759]
I get this error when I try to use the KerbalStuffPlugin by nlight:
`libgluezilla not found. To have webbrowser support, you need libgluezilla installed`
I have libmono-webbrowser2.0-cil and libmono-webbrowser4.0-cil installed on my Ubuntu 14.10 system.

**Comment by mgsdk** [comment]
You probably need to create the ticket at https://github.com/AlexanderDzhoganov/CKAN-plugins/issues instead, as it is directly related to one of the plugins.

**Comment by MrGreenTea** [comment]
Okay, did that
