### ISSUE TITLE
quirky GUI on OSX

### ISSUE THREAD

**Issue by basbebe** [KSP-CKAN/CKAN#760]
Hey!

The GUI has some annoying bugs on OS X (for me). I can't say if this is CKAN or Monos behavior.
I understand that the regular Hotkeys work the windows way (CTRL-\* instead of CMD-*).
But whenever I try to enter something into the search field I have to type really really slow because otherwise letter are being dropped or doubled.
And the Interface doesn't update itself. e.g. "updating": The tabs switches to "Updating repositories" and then switches back to "Manage mods" when it is done. Although the tab "Manage mods" is then being active, the UI still shows the "Updating repositories" part where the list of the mods should be… I then have to switch tabs manually again to reset the view.

**Comment by alampros** [comment]
The GUI is definitely a bit finicky on OSX. I sometimes have to "kick" it by scrolling the mod list or attempting to select text in the log output to get it to repaint correctly. The issue can be seen when a mod update fails (in this case EVE) in this recording:
![txabnkmc5c](https://cloud.githubusercontent.com/assets/297461/5842571/e607d028-a173-11e4-9a3a-130c87ffb810.gif)

**Comment by calebmennen** [comment]
Not sure if this is feasible, but could you just signal mono to redraw the gui after every big change (change of tab, check box, etc)? That might help resolve the issue

**Comment by savagerose** [comment]
Looks like the tab issue is a long standing bug in Mono's Carbon-based WinForms driver: https://bugzilla.novell.com/show_bug.cgi?id=509245

I tried getting it to run in X11 instead to work around the issue but recent versions of the OSX Mono distribution don't have that compiled in.

I'm getting a development environment set up so I'll see if I can find a workaround like the one calebmennen mentioned.

**Comment by savagerose** [comment]
Manually setting visibility on the TabPage / controls in the TabPage works pretty well, but there's a case where the mod list doesn't reappear immediately after using the refresh button. It flashes on screen for a second but then disappears until it redraws again, not sure exactly what's going on there.


The search box behavior appears to be a combination of adding even a single row to a DataGridView being really slow and this key handling bug: http://mono.1490590.n4.nabble.com/Incorrect-missing-and-duplicate-keypress-events-td4658863.html

Unless there's a way to address one of those directly, the best work around I can think of would be to wait until the user finishes typing to update the table.

**Comment by savagerose** [comment]
Found another, more minor UI glitch: if you right click near where the column headers would be for the mod list, while on a different tab, the mod list gets shown on your current tab. Also having an issue with the Change Set ListView drawing / taking clicks even when it's set to invisible and on a different tab. Aside from that issue, setting control visibility just about works to solve the issue. Not sure how to make the ListView stop drawing though. 

WinForms is definitely a bit of a mess on OS X. :O

Also, Platform.isMac doesn't seem to work to identify when CKAN is running on a Mac; apparently Mono hasn't started differentiating Mac and Unix yet because they have too much legacy code?

**Comment by pjf** [comment]
@savagerose : Just here to say *thank you* for the fixes. They're super appreciated! (And now released)

**Comment by Heliosmaster** [comment]
For me the gui does not work at all :-/ 

`Mono JIT compiler version 3.12.1 ((detached/b7764aa Fri Mar  6 15:32:47 EST 2015)`
`v1.8.3-0-g1560902 (beta)`

Nothing shows up. Terminal version works somehow ok.

**Comment by Postremus** [comment]
Is the CKAN icon visible?

**Comment by Heliosmaster** [comment]
Not at all.

**Comment by HebaruSan** [comment]
Looks like this was fixed in KSP-CKAN/CKAN-GUI#118 and KSP-CKAN/CKAN-GUI#124.
(And most Macs will probably be defaulting to ConsoleUI now anyway thanks to the 32-bit situation.)
