### ISSUE TITLE
Saving/loading of mod lists

### ISSUE THREAD

**Issue by Xolroc** [KSP-CKAN/CKAN#761]
I'd like to see CKAN support saving/loading modlists; it'd be good for backup, transferring your list of favorite mods between computers, allowing people to easily use the same mods someone else does, or just allowing someone to revert changes without having to keep track of what mods they added (this happens more often than you'd think, if one just browses the list and checks everything that sounds cool; incompatibilities will probably happen).

I understand it already autosaves to a file in the KSP directory; I'd like to see a simple way in the GUI and/or command-line interface to save the mods somewhere else, which I suppose would be essentially copying the autosaved file.

**Comment by Zsub** [comment]
+1!

Exporting a list of mods would be very useful, also maybe for YouTubers who can make available the list of easily-installable mods so viewers can recreate their scenarios (Scott Manley's Interstellar Quest, for example).

**Comment by hakan42** [comment]
We already have the installed-default.ckan file. Maybe we should make it more visible, though... And a CSV / Text file to accompany it so it can be easily pasted into a forum or YouTube description...

**Comment by Xolroc** [comment]
I would suggest a button somewhere in the GUI that lets you pick a place to save a copy of installed-default.ckan, and another button to load one. Something to export to csv/text would be nice too!

**Comment by Moleculor** [comment]
I'd love this simply for the easy ability to switch back and forth between my Vanilla saved game and my heavily modded saved game. My 'vanilla' game still uses cosmetic enhancements.

**Comment by TeddyDD** [comment]
@Moleculor then you should use two independent installs of game. I suppose switching mods would be inefficient and complicated.

**Comment by hoylemd** [comment]
+1 from me! I've been thinking about this for some time now.

**Comment by Moleculor** [comment]
@TeddyDD Orrrr... I could not. 

Switching mods could be as simple as moving the temporarily uninstalled mods to a non GameData folder. This is, in my opinion, better than having the same game and some of the same mods installed in two separate locations, with two sets of mods to continue to update, two sets of saved games, etc.

**Comment by Ippo343** [comment]
Hey guys, as of v1.6 ckan supports this using metapackages.
You can create a metapackage and install it, effectively having a modlist. :)

**Comment by Shaggygoblin** [comment]
A user...
fracking awesome feature!  Just wish the wiki was more wiki and had a 'use guide' other than "install and hit refresh and add/remove mods with cheeck boxes."
CKAN, as it is is very unfriendly to users who know nothin' more than "click the .exe to run"

**Comment by Ippo343** [comment]
The whole point of a wiki is that you can help us expand it ;)
________________________________
Da: Shaggygoblin<mailto:notifications@github.com>
Inviato: ‎11/‎03/‎2015 03:31
A: KSP-CKAN/CKAN<mailto:CKAN@noreply.github.com>
Cc: Michele<mailto:m.ippolito@outlook.com>
Oggetto: Re: [CKAN] Saving/loading of mod lists (#761)

A user...
fracking awesome feature!  Just wish the wiki was more wiki and had a 'use guide' other than "install and hit refresh and add/remove mods with cheeck boxes."
CKAN, as it is is very unfriendly to users who know nothin' more than "click the .exe to run"

---
