### ISSUE TITLE
Add the ability to disable mods

### ISSUE THREAD

**Issue by Zer0t3ch** [KSP-CKAN/CKAN#764]
Obviously, unless implemented with lots of logic checking, this could add issues with something like firespitter. (IE, disabling Firespitter might remove the Firespitter folder, but if another mod requires Firespitter.dll, there could be issues)

The way I see it, this could be implemented in 2 ways, 1 easier, 1 better. The first way would simply delete the files in the disabled mod (hopefully checking for other mods' dependencies first) and that could be relatively easy. The other way would be to keep a centralized folder with all mods ever downloaded, and disabling only removes the mod from the GameData folder, not the global backup. (This would allow quick enabling/disabling without redownloading every time)

**Comment by AlexanderDzhoganov** [comment]
This proposal assumes that CKAN *does* redownload every time, which it totally doesn't (we cache all downloads).
