### ISSUE TITLE
CKAN issues

### ISSUE THREAD

**Issue by Dargon606** [KSP-CKAN/CKAN#765]
Ive run into two issues while using CKAN

1. When installing certain mods (i noticed with B9 shuttle wings) it does not install mods that are required to use that mod (firespitter for B9 shuttle wings) even though on the mod page it is specificed that it will need that mod

2. I refresh and press mark all updated every so often but every time i do it it says it cannot update kerbalstats because its not installed. And it isnt the box for it isnt checked or anything. I dont use kerbal stats and i dont want to so to update my mods i have to go in download kerbal stats update then remove kerbal stats just because it wont let me do it otherwise

I hope you can get the second one fixed because it annoys me extremely.

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-support#87
