### ISSUE TITLE
Can't install Realistic Progression Zero, go to changes greyed out.

### ISSUE THREAD

**Issue by jonassm** [KSP-CKAN/CKAN#766]
Newest release.

**Comment by mgsdk** [comment]
Realistic Progression Zero cannot be installed at the moment since the dependency on Community Tech Tree (CTT) is not met. CTT is ready for 0.90, but on of the mods it depends on (TechManager) is not marked as available for 0.90.

**Comment by Ippo343** [comment]
Well, I guess it's solved then :)
