### ISSUE TITLE
request the ability to see why a mod is incompatible

### ISSUE THREAD

**Issue by deathnutts** [KSP-CKAN/CKAN#768]
currently there is no why for the gui to display why a mod is incompatible it would be nice to know why a mod may be marked as incompatible.

**Comment by jonassm** [comment]
Yes. Please do this.

**Comment by Dazpoet** [comment]
GUI now displays conflicts through https://github.com/KSP-CKAN/CKAN-GUI/pull/59 but I assume this request is for something more obvious?

**Comment by Dazpoet** [comment]
Ok this is interesting, I just found https://github.com/KSP-CKAN/CKAN/issues/500 which acctually presented a solution in https://github.com/KSP-CKAN/CKAN/commit/c1f37d0dc88fb8c594d4ce7980863a86493a19b6 but the reposplitting prevented the PR from ever getting merged. Basically it seems @RichardLake made a working solution which was never implemented.

**Comment by RichardLake** [comment]
I've been meaning to get back into KSP and CKAN anyway so I'll take this. I've thought of some improvements on c1f37d0 and I should have new PRs ready for testing before Monday.
