### ISSUE TITLE
dynamic CKAN API, written in Java or C#?

### ISSUE THREAD

**Issue by hakan42** [KSP-CKAN/CKAN#770]
This is to trigger a small language policy discussion...

I want to implement a dynamic database backed API lookup service for our metadata. This would be an enhancement / replacement on the already existing content at http://api.ksp-ckan.org . I envision some server process, with nginx in front for caching yadda yadda yadda

The thing is, I am experienced in Java, but not so much in C#, where I started dabbling when I joined the CKAN team.

So, what would the team prefer? Having a separate thing, written in a new language (then again, MirrorKAN is written in python as well), or put effort into learning database access and web technologies in C# so the project can share code with CKAN-core?

**Comment by hakan42** [comment]
Obviously, my vote goes the Java way :smiling_imp:

**Comment by borogove** [comment]
If you know Java, you shouldn't have much trouble working in C#.

**Comment by hakan42** [comment]
I know, I actively develop the command line client and netkan :smile_imp:

The question is, are there things like spring-boot for c#?

**Comment by sparkybear** [comment]
My vote is for C#. Java is fine, but I like C# more, mainly due to the direction it's going in the next few years.

**Comment by GenPage** [comment]
I would like to pitch out from outside the box. Node.js is a great idea if you are looking to serve data over an API. Low overhead and great performance.

**Comment by pjf** [comment]
My vote would be for Perl, obviously, with a Dancer + Plack stack.  :)

But if I had to choose between Java and C# for new projects, I would lean towards C#, because that our existing codebase not only for the CKAN, but for KSP mods in general. :)

**Comment by pjf** [comment]
Imma closing out old issues! @hakan42 , feel free to re-open if you think we're still in need of discussion here. :)
