### ISSUE TITLE
Allow `ckan show [mod]` for non-installed mods

### ISSUE THREAD

**Issue by alampros** [KSP-CKAN/CKAN#771]
I'd like to find out more about a mod before I install it, such as the link to it's homepage, forum thread, or curse page.

Ideally, I'd like to see something like homebrew's `brew home [package]` which open's the package's homepage in your default browser.

**Comment by mgsdk** [comment]
This may be partially covered by https://github.com/KSP-CKAN/CKAN-cmdline/pull/45. The GUI should already give you a clickable link for each mod, and my terminal also yields easy access links with the code in the PR above.

I have no idea how the Windows/OS X (or other Linux alternatives) terminals behave in this matter, so it might not be a bad idea to implement the switch.

This should be part of the next public release after 1.5.6.

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-support#86
