### ISSUE TITLE
github latest release tag

### ISSUE THREAD

**Issue by Crzyrndm** [KSP-CKAN/CKAN#773]
As suggested [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-5-0-24-Dec-2014?p=1719686&viewfull=1#post1719686), making use of github's latest release tag could prevent typo's causing mods to become stalled

**Comment by plague006** [comment]
The old comment link has been broken by the forum change. Is this issue still valid? I think the main issue is that we don't throw up any flags/errors when we index a version of a mod that is out of sequence and I believe we have another issue relating to this.
