### ISSUE TITLE
When selecting Kerbal directory in GUI, allow text input

### ISSUE THREAD

**Issue by alexkindel** [KSP-CKAN/CKAN#777]
![](http://i.imgur.com/ST8KUlC.png)

It's very frustrating when you can't have text input. I can browse to my Kerbal directory from steam and then copy paste the address, but can't use it because you can't paste in this type of Browse Dialogue on Windows.

Unrelated: I'm not really sure if GUI issues should go here or in the CKAN-GUI issues tracker?

**Comment by alexkindel** [comment]
Is there a way to check where the Steam Libraries are? If so, you could auto-detect KSP installs easily.

**Comment by mgsdk** [comment]
GUI issues should go to the GUI tracker/sub-project. I think the main issue is the lack of a (at least to my knowledge) .NET widget with the feature you request.

You can circumvent the GUI dialog by using the CLI version to paste the path. Open a console (enter cmd into the "Run" prompt), go to the folder where CKAN is, and run

```ckan.exe ksp add DefaultKSP path```

and replace path with the one from Windows explorer. I don't know if this will be faster than doing it using the GUI though.

**Comment by alexkindel** [comment]
The vast majority of users aren't going to use the CLI, including myself. I poked around MSDN but didn't see anything. Unfortunately I don't have much experience with C# or .NET.

**Comment by mgsdk** [comment]
@alexkindel I agree, the CLI is handy for circumventing certain issues but in general the GUI is preferred. I tried to create a quick mock-up of a improved folder selection dialog but working with visual elements in C# is not my strong side either (my GUI experience is limited to Qt widgets).

I fear one would have to re-implement the entire dialog to add the functionality, but I hope someone smarter than me can find a way around doing that.

**Comment by Ippo343** [comment]
This issue was moved to KSP-CKAN/CKAN-GUI#55
