### ISSUE TITLE
KSP Won't Launch (Can't find Executable)

### ISSUE THREAD

**Issue by AlonmifexMaximus** [KSP-CKAN/CKAN#779]
KSP won't launch from CKAN, it gives me this dialog when I try to click Launch KSP:

 Couldn't start KSP. Cannot start process because a file name has not been provided

How do I solve this?

**Comment by mgsdk** [comment]
Can you go to "Settings" -> "KSP command-line" and tell us what is written in there (if anything)?

**Comment by AlonmifexMaximus** [comment]
I fixed the problem by writing in the (then empty) command line with ksp.exe

**Comment by Ippo343** [comment]
In the future, please address support issues at KSP-CKAN/CKAN-support
