### ISSUE TITLE
CKAN repository unaccessable

### ISSUE THREAD

**Issue by TitanLordIV** [KSP-CKAN/CKAN#780]
Every time I refresh the app (using GUI) it returns an error: "Failed to connect to repository. Exception: and exception occurred during a webClient request." I am using the default metadata reposiory, and I tried to change it to: https://github.com/KSP-CKAN/CKAN-meta , but it would not let me update it. Any help would be appreciated as no mods appear in the client.

**Comment by pjf** [comment]
Gosh, we should probably give CKAN a way to try multiple mirrors if the primary is acting up. You can try `http://amsterdam.ksp-ckan.org/master.zip` as another download location, and worst comes to worst you can run `ckan.exe update --repo=http://amsterdam.ksp-ckan.org/master.zip` on the command-line to force a refresh from that location¹.

¹ I'm assuming this still works, I'm not yet on the latest client, but can't imagine why the feature would have changed.

**Comment by AlexanderDzhoganov** [comment]
This issue has been open for more than a week without any comments from the original author which qualifies it to be closed. If this is a mistake, feel free to re-open the issue or create a new one.
