### ISSUE TITLE
Auto-updating CKAN, progress report

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#782]
I've been working extensively on the auto-update feature the last few days. Here is a checklist of necessary changes and additions in order to make this happen:

- Core
  - [x] Query GitHub for the latest CKAN version and download URL
  - [x] Query GitHub for the release notes
  - [x] Query GitHub for the download URL of the latest updater app build

- Command-line client:
  - [ ] A new command to display the latest CKAN version
  - [x] A new command to update to the latest CKAN version

- GUI client:
  - [x] [Form to host the new auto-update options](http://i.imgur.com/6qv5krL.png)
  - [x] Dialog that warns user of a new CKAN version
  - [x] Dialog that prompts user to automatically check for updates (first run only)
  - [x] Actual code to do the auto-update

- Other:
  - [x] [CKAN-autoupdate repo to host the updater application](https://github.com/KSP-CKAN/CKAN-autoupdate), [CI integration](http://ci.ksp-ckan.org:8080/job/CKAN-autoupdate/)

**Comment by hakan42** [comment]
Nice :+1:

**Comment by alampros** [comment]
Very nice indeed! :+1: 

Is it too soon to start thinking about fetching the release notes in these commands along with the version info? This would let you do something similar to the standard autoupdate frameworks out there ([Sparkle](http://sparkle-project.org/) or [NetSparkle](http://netsparkle.codeplex.com/)).

NetSparkle's UI:
![image](https://cloud.githubusercontent.com/assets/297461/6506618/7d27aeca-c31a-11e4-84d8-539bce936e91.png)

**Comment by birdspider** [comment]
Just a reminder that for instance on linux where ckan is installed via package mangaers, auto-update might fail due to permissions or/and might not be desired. 

So a option for _not_ using it would be nice. (compile flag, setting, cli option, ...)

**Comment by AlexanderDzhoganov** [comment]
@alampros Suggestion noted, thanks.

@birdspider Auto-update will be 100% optional and off by default.

**Comment by AlexanderDzhoganov** [comment]
After a series of PRs which I can't be bothered to list, the auto-update functionality is pretty much complete. [v1.6.3](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.6.3) contains all the auto-update stuff :tada:

**Comment by hakan42** [comment]
:+1:

**Comment by Ippo343** [comment]
@AlexanderDzhoganov , you ROCK!

**Comment by alampros** [comment]
Great work! Thanks @AlexanderDzhoganov ! :neckbeard:
