### ISSUE TITLE
[linux] Auto-updating fails if there are spaces in the path

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#787]
Tested with ckan v1.6.4.
Debian GNU/Linux 8 "jessie", x64

1. Started ckan v.1.6.4.
2. Selected "Install" from "A new version of CKAN is available" window. (Addtional bug, incorrect version displayed in changelist: "Changes since last 1.6.3")
3. CKAN GUI closed and browser window (Iceweasel in my case) was opened
4. Browser displays "File not found" error: "Iceweasel can't find the file at /opt/games/Kerbal."

Browser address bar shows "file:///opt/games/Kerbal", should be "file:///opt/games/Kerbal Space Program/ckan.exe"

**Comment by AlexanderDzhoganov** [comment]
Looking into this now, thanks.

**Comment by pjf** [comment]
Gosh dang, is this still an issue with the current clients?
