### ISSUE TITLE
[linux] Auto-updating fails to set executable bit

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#788]
Tested updating from v1.6.4 to v1.6.5
Debian GNU/Linux 8 "jessie" x64

Using the auto-update feature (which fails to restart, see #787), the new version of ckan.exe is downloaded, but the executable bit is not set:

`-rw-r--r--  1 micha users  2225664 Mar  5 23:46 ckan.exe`

**Comment by AlexanderDzhoganov** [comment]
Yes, this was an omission on my part that 1.6.5 should fix (i.e. next upgrade should go fine). Thanks for the info.

**Comment by vtdmhd** [comment]
Updated to 1.6.20 from previous version, still no executable bit.

**Comment by pjf** [comment]
Bah, our bot closed #798, but as this is the earlier ticket I'm opening this and pinning it as a bug.

I'm struggling to find the code that @AlexanderDzhoganov mentions for setting the execute bit. The AutoUpdater seems to contain a test to see if we're running Linux, but nothing that actually uses that test.

**Comment by Postremus** [comment]
@pjf The Code is located here: https://github.com/KSP-CKAN/CKAN/blob/master/Core/Net/AutoUpdate.cs#L64

I guess it should be in the AutoUpdater.

**Comment by pjf** [comment]
@Postremus : Aaah! So we're chmodding the autoupdater, but it's not chmodding `ckan.exe` in turn?

So it really should be in both. :)

**Comment by Postremus** [comment]
yup
