### ISSUE TITLE
GUI not displaying on desktop

### ISSUE THREAD

**Issue by KronicOffender** [KSP-CKAN/CKAN#789]
First the problem: When I launch CKAN 1.6.5 the black window that normally flashes does so as usual. However the main window does not display. If I hover over the program in the taskbar, it shows the small window you normally see when a program is minimized and the CKAN main window is visible in the preview. Oddly, any open window immediately disappears as if I've clicked on the Windows "Show Desktop" icon. The CKAN process shows in task manager as normal.
 Attempts to resolve: I've deleted CKAN, deleted the folder in the KSP folder and reinstalled/downloaded. This did not resolve the issue.

**Comment by KronicOffender** [comment]
Resolved by placing the CKAN.exe file inside of the KSP directory.

**Comment by ChristopherMeek** [comment]
Hey Kronic,  I'm having exactly the same issue.  The app worked fine for a day and then gives me exactly the same issues as you.  Moving the exe did not help in my case however.

**Comment by Dazpoet** [comment]
See https://github.com/KSP-CKAN/CKAN/issues/794

**Comment by ChristopherMeek** [comment]
Ahh, nice, I'll check that out.
