### ISSUE TITLE
[Linux] Updated filter shows no results

### ISSUE THREAD

**Issue by spookydonut** [KSP-CKAN/CKAN#791]
http://i.imgur.com/soKIugp.png

To replicate, open ckan, leave the default selected (currently 6s mod).  Select the updated filter.
You get what the image above shows.

If you go back to filter (all) and select the mod that the description shows in screenshot (in this case it was quick scroll), and then select the updated filter again the list displays normally.

**Comment by tanriol** [comment]
Filtering on name also does not work correctly in some cases.
For example, when `QuickScroll` is typed letter-by-letter into the filter, the all mods disappear after `Q` is entered, then the matching ones show up back when in comes to `Quic` and behave correctly to the end of this name.

**Comment by RichardLake** [comment]
Since this issue was made improvements have been made to both of these areas. If the issue still persists please reopen.
