### ISSUE TITLE
Whole program is broken!?

### ISSUE THREAD

**Issue by DELTA129** [KSP-CKAN/CKAN#792]
This program is horrible!
Some GUI elements aren't visible or they stretch outside of the window,
Crashes 80% of times when installing mods,
Wont EVER install most of the mods,
Often crashes without reason,
Sometimes won't even start up,
Half of the GUI sometimes doesn't work,
MANY other bugs,
Design issues:
 Already downloaded mods need to be reinstalled anyway?
 No failsafe check for wrong download link (i believe this is the reason why it won't download most of the mods)
 Many other failsafe/bad user input checks.

Idea for this program is great, it would be awesome to have a single program to manage your mods.
But it's terribly coded. 
As a programmer myself i can't believe that someone could publish such broken program.
Also i would recommend a better programming language than Python for such complex program, for example C# or Java.

**Comment by hakan42** [comment]
You are aware that the main program is written in C# ? And that supporting scripting like the mirroring and netkan expansion is written in Phyton, which in itself is a good choice for scripting?

On the other hand, why do I even take time to answer to this very obvious trolling attempt.... :imp:

**Comment by DELTA129** [comment]
I'm not trying to troll anyone, all i wrote happens to me. This program just doesn't work well.

**Comment by birdspider** [comment]
I too am a programmer, and while CKAN GUI does have its fair share of problems, it neither crashed nor prevented me from downloading stuff. 

That being said I suggest you try to identify/specifiy the problems you have and, if applicable, post recommendations/suggestions instead of issuing a general rant, devoid of any content to go from.

**Comment by DELTA129** [comment]
As i said it sometimes won't even start up, and if it does, most mods i'll try to install just throw some error during download and then it crashes.Many features just randomly tend to stop working for example i can't click Changes tab or how is it called. Sometimes the program jsut crashes witout any apparent reason.

**Comment by pjf** [comment]
Hooray! Programmers!

The whole program is open source, the project is run entirely by volunteers, and we happily accept pull-requests. Everything is at least MIT licensed or freer, so you're absolutely welcome to make your own better, stronger, CKAN.

If you're looking at getting started as a contributor, then [the wiki](https://github.com/KSP-CKAN/CKAN-support/wiki) is a good place to start.

Welcome aboard!

~ Paul

**Comment by DELTA129** [comment]
Actually i would like to fix those errors if I can, i don't know if it happens just to me but if no then it would be great if that fix could be published.

**Comment by dertroglodyt** [comment]
I'm a programmer too! (scnr)
Just wanted to let you know that I think you're doing a marvelous job here (for free!).
I know how fustrating it can be to work on something as complex as this and make it run on multiple platforms. If I had no health issuses I would gladly join in. So all I can do now is applaude you. Keep up the good work.

Oh and for the record: Runs without any problems on both Win 7 and Ubuntu 64bit here.

**Comment by TeddyDD** [comment]
You are a programmer and you posting issues like THAT?? Complaining without any details? What OS are you using, what version of Mono do you have installed etc? Some pics at least? Really? :angry:
