### ISSUE TITLE
CKAN shows open in taskbar and taskmanager but no accessible GUI Window (GUI Preview IS there in Taskbar).

### ISSUE THREAD

**Issue by Shaggygoblin** [KSP-CKAN/CKAN#794]
I had two KSP Installs, with ckan.exe in each.  One was KSPx32 and the other was KSPx64.
I removed all, formatted, then reinstalled KSPx64, downloaded a new CKAN.exe and placed it into KSPx64.  I run it and it opens a term(cmd) and shows some stuff, but I can't freeze it fast enough to read it.  It then appears running in Taskbar and Taskmanager as normal, but no GUI window appears.  Hovering over the Taskbar gives a preview of the window.  I use a shortcut on desktop to CKAN in each install labeled as "CKANx32" and "CKANx64" as appropriate.  the .exe inside each folder is still "ckan.exe," if this helps at all.  .

CKAN appears to be using the registry(?) to remember previous installs/locations, and is now trying to run based on old addressing info.  Running ckan repair inside KSPx64 directory gets me this clue:

D:\Kerbal Space Program x64>ckan repair
156 [1] WARN CKAN.KSPManager (null) - KSP x32 at D:/Kerbal Space Program x32 is not a vaild install
CKAN Client 0.0.0.0
MIT License - CKAN Team

Possible Fix: do not write this info to the registry.  write the KSP.exe location to the settings file.  If KSP.exe is not found, prompt for the new location.

"These are assumptions based on observations.  I'm not a programer."

**Comment by Shaggygoblin** [comment]
After making the assumption of ckan using the registry, I decided to snoop in mine.
Results:
[HKEY_CLASSES_ROOT\ckan\shell\open\command]
@="D:\\Kerbal Space Program x64\\ckan.exe gui %1"

[HKEY_CURRENT_USER\Software\CKAN]
"KSPAutoStartInstance"=""
"KSPInstanceCount"=dword:00000002
"KSPInstanceName_0"="KSP x32"
"KSPInstancePath_0"="D:/Kerbal Space Program x32"
"KSPInstanceName_1"="KSP x64"
"KSPInstancePath_1"="D:/Kerbal Space Program x64"

[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\ckan]
@="URL: ckan Protocol"
"URL Protocol"=""
[HKEY_LOCAL_MACHINE\SOFTWARE\Classes\ckan\shell\open\command]
@="D:\\Kerbal Space Program x64\\ckan.exe gui %1"

[HKEY_USERS\S-1-5-21-519370472-3212739218-805880181-1000\Software\CKAN]
"KSPAutoStartInstance"=""
"KSPInstanceCount"=dword:00000002
"KSPInstanceName_0"="KSP x32"
"KSPInstancePath_0"="D:/Kerbal Space Program x32"
"KSPInstanceName_1"="KSP x64"
"KSPInstancePath_1"="D:/Kerbal Space Program x64"

I have no idea which, if any, entry is the "Remember this as the default install" entry.

Again, writing this to a config file seems like an easier way to fix, but I am not a programer, so it may be harder.

**Comment by Shaggygoblin** [comment]
CKAN presents as normal when you rename/move the "...\Appdata\Local\CKAN" folder.

**Comment by Shaggygoblin** [comment]
[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Cygwin\Installations]
 Removing the old "...KSP x32" Install path from this reg entry causes the "Invalid" that was present in each invocation of ckan.exe via cmd.exe to go away.  No longer complains "KSP x32" ...Kerbal Space Program x32 is invalid.

**Comment by ThrillBird** [comment]
I had the exact same problem. Unfortunatelly I don't understand everything you wrote, but  Ican confirm you are not the only one with the issue. Just as you said, removing the CKAN folder under AppData\Local seemed to solve it. For the developers, I'm not sure when the issue started. I downloaded your (awesome) software this sunday and found the problems on monday. Hopefully Shaggygoblin's detailed info will help you, thanks for the great piece of software!

**Comment by damerell** [comment]
I have also had the issue where no GUI window appears. I don't know how to reliably reproduce this issue, but likewise I had a spurious window position in user.config as Shaggygoblin describes above.

I don't know about the multiple-installs issue, but I do suggest that CKAN should notice bogus window positions in this file and put the window somewhere the user can see it.

**Comment by Postremus** [comment]
I had the same problem using CKAN 1.6.6.
I downgraded to 1.5.6, and now the window apears

2015-03-23 19:12 GMT+01:00 damerell <notifications@github.com>:

**Comment by pjf** [comment]
@Postremus : Oooh! Can you confirm you downgraded from 1.6.6 to 1.5.6 (not 1.6.5)? Having both a 'known good' and 'known bad' points might help us in being able to bisect where this bug was introduced.

**Comment by Postremus** [comment]
jup, I can confirm it.

2015-03-26 19:48 GMT+01:00 Paul Fenwick <notifications@github.com>:

**Comment by Postremus** [comment]
I just tested it again, with a few different CKAN versions:
The Gui opens in 1.6.2, 1.6.3 and 1.6.5.
In 1.6.6, the gui does not open. I can see the "preview" of the window,
when I hover with the mouse over the taskbar icon.


2015-03-26 20:01 GMT+01:00 Postre mus <postremus1996@gmail.com>:

**Comment by Dazpoet** [comment]
Had this problem appear out of nowhere on one of my ckan installs aswell. When looking at the user.config I noticed that MainWindowPos had the values `-32000,-32000`. Setting these to more reasonable values I got my window back again.

**Comment by Postremus** [comment]
MainWindowPos is set in the config to 0, 0.

2015-03-26 20:13 GMT+01:00 Willhelm Rendahl <notifications@github.com>:

**Comment by cordery** [comment]
+1  Had the same issue in 1.6.6, setting CKAN/GUIConfig.xml MainWindowPos in to 0,0 from -32000,-32000 fixed the problem.

**Comment by LucianoFaretra** [comment]
Same problem here, tx Dazpoet, that as solved my problem

**Comment by Catmacey** [comment]
I can confirm the same issue with 1.6.11.  
In GUIConfig.xml:
<WindowLoc>
    <X>-32000</X>
    <Y>-32000</Y>
  </WindowLoc>
Changin them to something more reasonable works fine.

**Comment by Dazpoet** [comment]
If anyone has a reliable way of reproducing this issue it would be deeply appreciated by developers to get reproduction steps.

**Comment by damerell** [comment]
I've just reproduced it. I was on a Windows 7 system, on which I have two monitors, which I'll call L and R. When I shutdown the system, L was my primary display. I started the system; L does not normally autodetect at boot time, so R became the only active display.

I started CKAN, which appeared on R. I manually detected monitors. L turned on and became the primary display. The CKAN window vanished; but killing CKAN and restarting it produced a window (I forget on which display, alas).

I made R the primary display then invoked KSP on it. When I quit KSP, CKAN's window had again vanished. Restarting it did not change this state of affairs. Nuking user.config did.

I am pretty sure I was doing a similar display shuffle last time this happened.

**Comment by plague006** [comment]
There have been a significant number of releases since this issue was last commented in. Is this behaviour still reproducible?

**Comment by Smorfty** [comment]
I had this problem today (many years later) in version 1.26.0.
My solution was to set the <WindowLoc> <X> and <Y> values to 0 in the CKAN/GUIConfig.xml file.

**Comment by DasSkelett** [comment]
@Smorfty can you look at #2717 is this is the same issue you encountered, and if took the same steps that lead to the bug?
