### ISSUE TITLE
[Suggestion]Remove all mod before Install from ckan file

### ISSUE THREAD

**Issue by ryohpops** [KSP-CKAN/CKAN#796]
It would be nice that all mods are uninstalled previously when you try to install a .ckan file.

I'm sharing .ckan meta package with players on a multi-player mod server to sync mod installation.
Also I'm switching current mod-set via meta packages to play several universe with each mod environment.
In order to keep correct mod environment (no version conflict, no unnecessary mod), I remove all mods by hand firstly.

I suggest that it should be automated or configurable.
Leaving mod's config on a mod removal works fine in this situation as well.

**Comment by Dazpoet** [comment]
Moved to https://github.com/KSP-CKAN/CKAN-support/issues/108
