### ISSUE TITLE
[linux] Auto-updating client fails to set executable bit (re-opened)

### ISSUE THREAD

**Issue by mwerle** [KSP-CKAN/CKAN#798]
Originally raised as issue #788 (no option to re-open).

CKAN client v1.6.5  detected, downloaded, and installed v1.6.6.0, however, new binary did not have executable bit set and failed to start.

Workaround: Manually set executable bit on binary.

OS: Debian GNU/Linux 8 "jessie" (64-bit)

**Comment by amedee** [comment]
Issue also seen on Ubuntu Vivid Vervet (64 bit)

**Comment by pjf** [comment]
Gosh dang. Is this still an issue with current clients?

**Comment by amedee** [comment]
Yes it is.
