### ISSUE TITLE
build.sh: 5: build.sh: nunit-console: not found

### ISSUE THREAD

**Issue by krysopath** [KSP-CKAN/CKAN#799]
on Debian Jessie (Linux path 3.16.0-4-686-pae #1 SMP Debian 3.16.7-ckt7-1 (2015-03-01) i686 GNU/Linux) following the installation procedure given for ubuntu fails.

"+ nunit-console --exclude=FlakyNetwork Tests/bin/Debug/Tests.dll
build.sh: 5: build.sh: nunit-console: not found"

installing nunit-console via apt solves. perhaps you could update your wiki and bin/requirements.txt to reflect this.

**Comment by Dazpoet** [comment]
Looking at the wiki it seems that `nunit-console` is mentioned in the part about [Build Environment](https://github.com/KSP-CKAN/CKAN-support/wiki/Build-Environment). Should it also be somewhere else? I never use these functions myself so I'm not sure where it makes sense to add it I'm afraid.

**Comment by krysopath** [comment]
On Tue, 14 Apr 2015 15:07:18 -0700
Willhelm Rendahl <notifications@github.com> wrote:

> Looking at the wiki it seems that `nunit-console` is mentioned in the part about [Build Environment](https://github.com/KSP-CKAN/CKAN-support/wiki/Build-Environment). Should it also be somewhere else? I never use these functions myself so I'm not sure where it makes sense to add it I'm afraid.

Well after looking I found it mentioned in the given link. I just
completely failed to look at it :> Regarding your question, I would
always advise to keep a file like bin/requirements.txt up to date with
necessary dependencies. My workflow here was to dl your stuff and first
thing after was to check out requirements.txt. So I was just wondering,
if nunit-console could be added to requirements, as it is necessary to
use your software.

Kudos to you all for your work!

-- 
krysopath <krysopath@gmail.com>

**Comment by Dazpoet** [comment]
Just send a PR and we'll fix it :+1:

**Comment by pjf** [comment]
As far as I know these are all fixed now. Huzzah!
