### ISSUE TITLE
SpaceY fails to download

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#800]
I see this on Linux and OSX, not sure about Windows.

I select the SpaceY mod, and start the install.  

It hangs.

When I look at the download directory, I see that there is a tiny file:
-rw-r--r--  1 jbayer  1194979570  172 Mar 31 20:31 451C56ED-SpaceY-Lifters-0.11.zip

but it is not a valid zip file.  When I download the file by hand from kerbalstuff.com, and copy it over, and then restart the install, it sees that it is cached and successfully installs it.

Other mods have been successfully installed from kerbalstuff.com, it's only this one that I've seen the problem.

When I tested, this was the only one I was trying to install during the test

I just tested this in Windows, it works. This may be because the Windows executable is using a different method to download than Linux or OSX

**Comment by linuxgurugamer** [comment]
I just tested this in Windows, it works.  This may be because the Windows executable is using a different method to download than Linux or OSX

**Comment by Dazpoet** [comment]
This should have been solved with the newest test version available through [here](http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-6-26-Mar-2015?p=1836557&viewfull=1#post1836557). Please confirm if that is the case.

**Comment by linuxgurugamer** [comment]
On 4/14/2015 6:03 PM, Willhelm Rendahl wrote:
>
> This should have been solved with the newest test version available 
> through here 
> <http://forum.kerbalspaceprogram.com/threads/100067-The-Comprehensive-Kerbal-Archive-Network-%28CKAN%29-Package-Manager-v1-6-6-26-Mar-2015?p=1836557&viewfull=1#post1836557>. 
> Please confirm if that is the case.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KSP-CKAN/CKAN/issues/800#issuecomment-93083428>.
>
Tested this on OSX Yosemite.

Problem:  Asked me if I wanted to upgrade to 1.6.6 (I assume this will 
go away, just reporting all issues)
Problem:  Entering text in the filter field is very slow and iffy.  I 
need to type 1 char at a time, about 1/second.
Problem:  I typed "spacey" in the filter by name field.  all lines were 
deleted from listbox, BUT in the right side, it did say SpaceY Heavy 
Lifters Parts Pack

I then deleted the filter, scrolled to find SpaceY by hand, selected it 
and installed it.

Result:  Progress bar slowly advanced.  I monitored the network, it 
seemed to advance as data was received.  It was slow, I'm not sure why. 
  I have a 50 Mbit download speed here, and it is performing at that 
speed with other tests.

Problem:  It appeared that if I moved the mouse while the window had the 
focus, it would download at about 128 Kbit/second.  If I wasn't moving 
the mouse, or if the window didn't have focus, it wasn't downloading

Final result:  SpaceY was installed

**Comment by Dazpoet** [comment]
Does doing the same operation through commandline make a difference? I don't think GUI can affect dl speed but you never know.

**Comment by linuxgurugamer** [comment]
On 4/14/2015 7:38 PM, Willhelm Rendahl wrote:
>
> Does doing the same operation through commandline make a difference? I 
> don't think GUI can affect dl speed but you never know.
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/KSP-CKAN/CKAN/issues/800#issuecomment-93113564>.
>

Yes it did.  Doing it from the command line, it was done in about 5 
seconds, I didn't even get a chance to  move the mouse

Just a reminder, this is OSX


JBB

**Comment by linuxgurugamer** [comment]
I did do a mono ckan.exe clean before testing


JBB

**Comment by pjf** [comment]
This should be fixed with v1.6.7, which was just released, and is identical to the test build except with the 'release' flags set on.

Alas, the GUI slowness on OSX is well known, and seems to be specific to mono on Mac systems. Alas, I don' t have a Mac (which makes testing more difficult), but this is *definitely* something I want to address.

**Comment by linuxgurugamer** [comment]
I am aware of the GUI slowness on the Mac, was just reporting it to be complete.

But what about the download issue?

Also, autoupdate on mac, while it did do the update, failed on restart.  I think it just tried to run ckan.exe rather than doing the "mono ckan.exe".  I would suggest getting the command line which was used to start it and using that, rather than the windows "ckan.exe" command

**Comment by Dazpoet** [comment]
I can second that autoupdate fails to restart the gui. No idea why but it appears to also happen in linux https://github.com/KSP-CKAN/CKAN/issues/798

**Comment by Dazpoet** [comment]
Slow downloads should be atleast partially cleared by https://github.com/KSP-CKAN/CKAN-GUI/pull/128

It seems we're tracking the other problems in other issuereports and as such I'll close this. If that seems incorrect please comment so we can reopen.
