### ISSUE TITLE
Check for *.dds or ignore "folder is not empty"

### ISSUE THREAD

**Issue by doktorjet** [KSP-CKAN/CKAN#802]
Many players use ddsloader for speeding up game loading. CKAN however behaves strangely while trying to update ddsified mods - it simply refuses to delete "non-empty" folders when cleaning before install. It's almost OK in most cases, but when mod folder structure changes - it way lead to... consequences.
A simple "Do you want to continue with folder deletion?" popup will be good enough, but simple *.dds file detection with popup reminder to manually reDDSify after update will be even better.

**Comment by pjf** [comment]
We'll never delete or modify files that aren't registered with the CKAN at all. That's a firm promise, and essential for CKAN's model to work correctly.

However, we *can* have metadata that tells us that a mod will create files that should be removed on upgrade or uninstallation. This is needed for a whole bunch of things, and not just in-place conversion of files for DDS textures.

#949 is where the grand plan of this is going down, so I'm resolving this ticket in favour of that (although #949 will break into sub-tickets, including ones to allow us to tag assets for deletion or preservation).
