### ISSUE TITLE
Ikaros release change to Linux install tip

### ISSUE THREAD

**Issue by msholly** [KSP-CKAN/CKAN#811]
I'm a Linux newbie, but there's a ton more like me - so I thought a small clarification would be helpful. 

Would it be correct/acceptable to add the `sudo` command to the beginning of 

`apt-get install libcurl4-openssl-dev` or `yum install libcurl-devel`

**Comment by Dazpoet** [comment]
Ah yes adding a sudo before those is correct. See e.g. the [Ubuntu installation guide](https://github.com/KSP-CKAN/CKAN-support/wiki/Installing-CKAN-on-Ubuntu-14.04)

**Comment by msholly** [comment]
Great, I was able to figure that out for my installation - but I hope this info helps the wiki

**Comment by Ippo343** [comment]
Yes, it does! Thanks :)
