### ISSUE TITLE
Can't choose another KSP install

### ISSUE THREAD

**Issue by linuxgurugamer** [KSP-CKAN/CKAN#812]
I have a 2nd KSP install, but when I go into settings and then click "Choose another KSP install", both the settings window AND the main CKAN window close, and a few seconds later the CKAN window opens up.

This is Windows 7, CKAN 1.6.9-0

CKAN.exe is installed in one of the KSP install directories.  when I copied it out of that directory, it behaved better

**Comment by TeddyDD** [comment]
Sometimes It happens on Linux too. 

@linuxgurugamer as workaround you can swich KSP installs from command line
```ckan ksp default```

**Comment by linuxgurugamer** [comment]
I already figured out the problem and the work-around:

Here is my directory structure:

d:\kerbalinstalls\Beta\ksp_1
d:\kerbalinstalls\Beta\ksp_2

The first time I ran ckan.exe, I was IN the first directory, and the executable was also in that directory:

cd d:\kerbalinstalls\Beta\ksp_1
ckan.exe

I solved the problem by copying the executable into the Beta directory and running it from there:

cd d:\kerbalinstalls\Beta
copy ksp_1\ckan.exe
ckan.exe

Hope this makes sense

**Comment by Postremus** [comment]
closing this since it is an duplicate of the closed #740 anyway.
