### ISSUE TITLE
CKAN needs a download "throttle"

### ISSUE THREAD

**Issue by Tabris83** [KSP-CKAN/CKAN#814]
![ckan](https://cloud.githubusercontent.com/assets/8855255/7215594/748897b2-e623-11e4-96f2-81e7b87edda1.png)
this only shows-up during a full install(re-adding mods after clean install).
github(this one errors out the most)

**Comment by pjf** [comment]
No way! We don't need a throttle, we need MOAR BOOSTERS!!

#935 is our plan for fixing this. :)
