### ISSUE TITLE
A button to display the readme, if it exists

### ISSUE THREAD

**Issue by JustinKerbice** [KSP-CKAN/CKAN#815]
Another improvement I thought about:

when a mod A have a readme file, a button inside CKAN GUI to display it and allow users to get valuable informations on how to use the mods, issues, options, etc

Meta file could also include a new item: readme => location/name, ex:

{
  "spec_version": 1,
  "identifier": "modA",
"readme": "myreadme.txt",
...

default value could be readme.txt (non case sensitive, in archive root) and handle also github default (readme.md).

**Comment by plague006** [comment]
Closing this in favour of #837
