### ISSUE TITLE
Cannot find KSP directory

### ISSUE THREAD

**Issue by Zuthal** [KSP-CKAN/CKAN#818]
I am on a Mac, running OS X 10.9.5, and running ckan via the mono thingie. I have KSP installed via Steam, and when I point ckan at the location of the KSP files (path being ~/Library/Application Support/Steam/steamapps/common/Kerbal Space Program), it either (when I leave in the spaces) simply outputs the CKAN command list, or (when I replace them with underscores) says that there is no KSP directory found at that location.

**Comment by Dazpoet** [comment]
How are you trying to add the installation? Via command line? If so have you tried putting citations around the path like `mono ckan.exe ksp default "path/to/ksp/install"`

You could also try putting the ckan.exe file in the KSP main directory and starting it from there using `mono ckan.exe`

**Comment by Zuthal** [comment]
Hmmm... neither of those work. When I try to do it with putting citations around the path, it outputs `Couldn't find install with name "~/Library/Application Support/Steam/steamapps/common/Kerbal Space Program", aborting..` and when I try moving ckan.exe into the KSP main directory, it just output `Cannot open assembly '/Users/yannick/Library/Application_Support/Steam/steamapps/common/Kerbal_Space_Program/ckan.exe': No such file or directory.`

**Comment by Dazpoet** [comment]
Oh my I wrote out the first part wrong, I'm so sorry :( It should be `mono ckan.exe ksp add default "path/to/KSP/folder"` On a bright note it does seem to accept the path with citations around it so that's a start!

**Comment by Zuthal** [comment]
It worked! Thank you a lot. Though now, whenever I try to launch it with `mono ~/Downloads/ckan.exe gui`, it tells me that it cannot find the KSP version in readme.txt. Any idea on how to solve this?

**Comment by Dazpoet** [comment]
Hm do you have a readme.txt in the KSP root directory and if so does it include the line `Version 0.90.0 Beta` (I'm going to assume you're on 0.90).

**Comment by Zuthal** [comment]
Yes, the root KSP directory does contain a file named readme.txt and it does contain that line.

**Comment by Dazpoet** [comment]
Hm then I'm at something of a loss here. Does the ckan gui properly display your install as an 0.90 version? It says in the header, atleast on windows.

I'm not sure there is a way to set a certain version through either commandline or gui since it depends on the readme.txt file. Do you get mods listed after doing a refresh? At time of writing I'm seeing 535 modules available in the "All" category after clicking filter and that should be the same number as you're seeing if ckan picks up you're on version 0.90.

**Comment by Zuthal** [comment]
Yup, I am getting 535 mods available as well. I was just being a bit too impatient waiting for it to start, as for some reason the mono thing took about a minute to load up ckan, despite launching it from an SSD.

**Comment by Dazpoet** [comment]
Then it appears that CKAN does indeed pick you up as a 0.90 install and it shouldn't ask you for the readme.txt. On your next startup could you try `mono ckan.exe --debug gui` and see if it prints anything else than just asking for the file and then dump the log here?

As for the long startup time I'd hazard a guess on it getting stuck on some fontconfig stuff, I have the exact same issue on my macbook. For me it was resolved with `LC_CTYPE="en_US.UTF-8" && mono ckan.exe` which sets up the locale to something that CKAN likes.

**Comment by mlr84** [comment]
I haven't used CKAN in Mac OS X, but when using terminal command line spaces are typically delineated using \ vs / for directory switches. Hope this helps some one.
