### ISSUE TITLE
Latest version crashes on HyperEdit

### ISSUE THREAD

**Issue by MIC132** [KSP-CKAN/CKAN#821]
As in title, latest version crashes when trying to install HyperEdit (with the message that it's trying to install but it was not downloaded).

Also, why is database missing the USI mods? Most of them were already updated. They aren't even in "all", not only in compatible.

**Comment by mgsdk** [comment]
Does this still occur? HyperEdit seem to have been re-indexed shortly after your post, and I'm able to install HyperEdit 1.4 fine in KSP 1.0 using CKAN 1.6.11.

**Comment by MIC132** [comment]
Yeah, it works now.
