### ISSUE TITLE
Ability to selectively hide mods

### ISSUE THREAD

**Issue by McyD** [KSP-CKAN/CKAN#823]
I did not see a post for this, though I may have missed a previous one.

I am sure that like me, everyone has mods they will never use.  Also useful in cases where a mod has more than one version (lite, low, medium, high res, comes to mind here) or in cases of conflicting mods that Ckan does not recognize.  It would be nice to have the ability to hide a mod that would never be used.

Suggesting a tick box or similar, perhaps right; click hide.  Once marked the mod is hidden, and moved to a hidden list, which would have to be added to a menu somewhere (perhaps setting tab?) for those that accidentally hide a mod, or decide they are going to use it later.

**Comment by plague006** [comment]
I'm curious if #1021 would address what you want. Essentially categories would narrow the number of mods you see at once, and it would allow "config-only mods" to be hidden. So instead of the 10 or so rows Astronomer's pack currently occupies it would be only 1.

**Comment by plague006** [comment]
Closing as this has no proponents, and categories probably serves the desired function.
