### ISSUE TITLE
CKAN shows mods as compatible when they have incompatible dependencies, breaks "Go to changes"

### ISSUE THREAD

**Issue by dewiniaid** [KSP-CKAN/CKAN#824]
I'm looking at installing the various Astronomer's Pack addons on a 1.0 install, and I seem to have run into a bug:

"Astronomer's Pack: Auroras - 4k (recommended)" requires "Astronomer's Pack - PlanetShine configuration", which is not in the list of available mods (presumably, PlanetShine isn't compatible with 1.0 yet).

Selecting this mod grays out the "Go to changes" button due to the missing dependency.  This is particularly problematic if several mods are selected for installation and someone would have to go through and figure out why the button is grayed out.  Having the mod either omitted from the list or some visual indication of its "missing dependencies" status would help alleviate this issue.

**Comment by dewiniaid** [comment]
Just noticed "1628855 [1] ERROR CKAN.RelationshipResolver (null) - Dependency on PlanetShine found, but nothing provides it." in the log, so that's definitely what's going on -- but if I didn't have a log, there would have been no indication as to what was going on.

**Comment by Dazpoet** [comment]
We're working on it :) See https://github.com/KSP-CKAN/CKAN-GUI/pull/73

**Comment by plague006** [comment]
KSP-CKAN/CKAN-GUI#73 has merged, this issue seems fixed?

**Comment by Dazpoet** [comment]
Seeing as PlanetShine is out for 1.0 now on CKAN I think this should be considered resolved and I'll close it. If you think this is done prematurely please comment and I'll re-open.
