### ISSUE TITLE
Changeset tries reinstalling removed plugins if a download fails

### ISSUE THREAD

**Issue by thewebists** [KSP-CKAN/CKAN#828]
If I select several mods to remove at the same time as adding several others then CKAN first removes the existing mods and then goes on to download the new ones.

The problem I noticed is that in this situation, if one of the downloads fails then the change set will still have the mods that where set to be removed, but now it's set to (re)install them.

**Comment by Postremus** [comment]
Can you still reproduce this on 1.10.0?
