### ISSUE TITLE
ModuleManager 404 Error

### ISSUE THREAD

**Issue by Luvodicus** [KSP-CKAN/CKAN#829]
Downloading "https://ksp.sarbian.com/jenkins/job/ModuleManager/lastStableBuild/artifact/ModuleManager-2.6.1.zip"
Error!

The remote server returned an error (404) File not found

**Comment by Dazpoet** [comment]
2.6.2 is out and working now, sorry for the inconvenience.

**Comment by Luvodicus** [comment]
While I'll agree 2.6.2 is out and working now, my issue persists
![error](https://cloud.githubusercontent.com/assets/5627627/7419488/5a2a6818-ef43-11e4-9634-8e11d62c0048.PNG)
