### ISSUE TITLE
Module Manager 404 Error, original case closed, issue still persists.

### ISSUE THREAD

**Issue by Luvodicus** [KSP-CKAN/CKAN#835]
![error](https://cloud.githubusercontent.com/assets/5627627/7419505/7b30fc0c-ef43-11e4-94e3-fc80dca529a6.PNG)

**Comment by Dazpoet** [comment]
Have you refreshed to get the new master file with the change of download location?

I just dit `ckan install ModuleManager=2.6.1` locally and it fetched and installed 2.6.1 without problems.

**Comment by Luvodicus** [comment]
Hmm... I'm gonna delete my CKAN and directories, reinstall, and refresh. Stand by

**Comment by Luvodicus** [comment]
Wierd. I had to delete all local content, download and run the latest CKAN, and update. Fixed. Thanks, mate

**Comment by Dazpoet** [comment]
So you're saying that after a refresh the problem persisted?

**Comment by Luvodicus** [comment]
CKAN had updated itself to a new verison, and refreshing, the problem persisted. I deleted all local content, deleted KSP and reinstalled to a new directory, downloaded the latest CKAN release, made sure to manually refresh (even though it already does that when you run CKAN for the first time, just to be sure) and the issue was resolved. At this point, I'm firmly convinced it was a PICNIC error.. (PICNIC = Problem In Chair, Not In Computer)
