### ISSUE TITLE
[request] Add an option to "favor" mods.

### ISSUE THREAD

**Issue by BiZZKeryear** [KSP-CKAN/CKAN#836]
Ok, my original idea was to make it so that I can select even incompatible mods and CKAN will install them as soon as a compatible version will be found.

But... now my idea goes a little further ... please also add something that shows which mods are already cached (aka. installed and then uninstalled).

And a option to manual mark mods as incompatible. e.g. ATM 4-3 (for 0.90)does not work for me and CKAN hasn't updated its database to 5 (for 1.0)  yet... (well In background I have "overwritten" the 4-3 version with the 5 one) .

The manual marked ones then should be uninstalled but reinstalled on next update.

**Comment by pjf** [comment]
Favourite mods are covered in #730.

Save-breaking mods is #60.

While it's not obvious, cached mods will have their contents available via the 'Contents' tab on the right.

Marking mods as incompatible is something we should do in the metadata, and while I don't think we have a ticket for it yet, being able to suggest metadata changes from the client would be a really lovely thing to have. Opening a ticket for that now.

**Comment by pjf** [comment]
#947 covers suggestions to give users a better way to report changes to the metadata (mods not working, mods actually working on newer versions, etc etc).

Closing out this ticket as we've hopefully covered all the bases with the links above. If you think I've done this in error, let me know. :)
