### ISSUE TITLE
CLI "ckan upgrade --all" command raise an Exception

### ISSUE THREAD

**Issue by Kitefr** [KSP-CKAN/CKAN#841]
Hello.

Just tested this with the last version (1.6.12), the command "ckan upgrade --all" raise this error : 
```
Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at CKAN.CmdLine.Upgrade.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at CKAN.CmdLine.Upgrade.RunCommand (CKAN.KSP ksp, System.Object raw_options) [0x00000] in <filename unknown>:0
  at CKAN.CmdLine.MainClass.Main (System.String[] args) [0x00000] in <filename unknown>:0
```
In my clan list of mods, I have 2 upgradable mods, 1 incompatible and the others are up to date.

**Comment by Kitefr** [comment]
Sorry, i should put this in the CKAN-CLI Repo.

**Comment by mgsdk** [comment]
Could you tell us which OS you are running? If you are on Linux/OS X do you know which version of Mono you are running?

**Comment by Kitefr** [comment]
I am on OSX Mavericks (10.9.5) with Mono JIT compiler version 3.10.0

**Comment by Kitefr** [comment]
After some tests, I noted some things.
It only happened when you have an Incompatible plugin already installed in your list.
If not, the command works as expected.

This command should works even with incompatible and/or unknown plugins installed just by skipping them during the process.
