### ISSUE TITLE
File overwrite error when installing Firespitter

### ISSUE THREAD

**Issue by YellowApple** [KSP-CKAN/CKAN#843]
Per the instructions in the error message.  Pertinent information:

```
File           : GameData/Firespitter/Firespitter.version
Installing Mod : FirespitterCore 7.1
Owning Mod     : Firespitter
CKAN Version   : v1.6.12-0-g0000000 (beta)
```

Happens when attempting to install the "Firespitter" package; I'm guessing there's an excess Firespitter.version somewhere?

**Comment by Dazpoet** [comment]
Just fixed https://github.com/KSP-CKAN/NetKAN/pull/1147

**Comment by YellowApple** [comment]
That was quick; thanks!

It doesn't seem like Firespitter itself is appearing as an available mod, though, even after a refresh.  Is it out for further diagnosis at this point, or is it just slow to reappear?

**Comment by Dazpoet** [comment]
What version of KSP are you on? I might have inadvertantly removed 0.90 compatibility now that I look back on the fix...

**Comment by YellowApple** [comment]
I'm on 1.0.2.  FirespitterCore shows up fine, but Firespitter itself is no longer present (whereas it was when I filed this report).

**Comment by Dazpoet** [comment]
The thing is... I acctually set it up to have a correct behaviour now, which is to not show up on versions later than 0.24.2. However I see github had a new release so I'll have to do some tweaking to get things sorted

**Comment by YellowApple** [comment]
Ah, okay.  Yeah, 1.0.x compatibility was introduced yesterday; I figured (apparently mistakenly) that Firespitter's appearance there coincided with that.  I see that it's back up though regardless.  Thanks!
