### ISSUE TITLE
Updating someone else's mod.

### ISSUE THREAD

**Issue by SirDiazo** [KSP-CKAN/CKAN#845]
Are there any procedures in place for updating someone else's mod?

I have gone ahead and updated the Smart Parts mod for KSP 1.0, but I don't want to officially take it over at this point. Firov (the current Smart Parts) dev visited the forums just under 2 months ago and I've taken a hiatus longer then that myself from KSP so that is not long enough for me to consider the mod abandoned.

However, unless I update CKAN, a lot of players are going to miss the fact there is a KSP 1.0 compatible version of Smart Parts available.

Is it okay for me to grab the Smart Parts .netkan and point it to the release on my Github? (I'm talking from a policy perspective, I know it is technically possible.)

**Comment by Dazpoet** [comment]
I would say this is ok, currently firespittercore is solved in a similar way until I can get around to point it at the official repo now that it's out there.

You could always add a comment field to the .netkan file like 

`"comment" : "mod updated by Diazo in abscence of main author and therefore indexed from Diazos github until author returns"`

Or some similar short explanation so people updating it in the future will know why/how it came to be a certain way.

**Comment by pjf** [comment]
I see there's been a return of Firov to the forums. But for the record, the mod's under a CC BY-NC-SA 3.0 license, so Firov has already given you explicit and irrevocable permission to make derivative works under that license, which of course includes 1.0 recompiles. :)

So yes, I'd be saying this is absolutely 100% okay. :)

Also, closing with great joy.
