### ISSUE TITLE
Explain why mod is incompatible

### ISSUE THREAD

**Issue by MarkSRobinson** [KSP-CKAN/CKAN#846]
Many mods are marked as incompatible but it's not stated as why.  It would be really helpful if the tool could provide a reason why they're incompatible.  Even something like 'KSP {version} not supported by mod" or "Dependency {X} not compatible".

**Comment by pjf** [comment]
Aww yis! We do this now with our most recent releases, because @RichardLake is a total badass and added it. Marking this resolved with great joy. :)
