### ISSUE TITLE
Client: Validate all metadata files against the schema on repository update

### ISSUE THREAD

**Issue by AlexanderDzhoganov** [KSP-CKAN/CKAN#85]
This will help us avoid chasing non-existent bugs related to broken metadata files.

**Comment by HebaruSan** [comment]
Netkan itself (bot included) checks new modules against the schema as of #2788.

I think running this validation _in the client_ should not be done. First, it would be a lot more work during repo updates with a huge performance penalty. Second, if a non-conformant module was detected, the end user probably neither caused this problem nor knows how to do anything about it. Keeping the metadata repo clean accomplishes the same goal in a better way.
