### ISSUE TITLE
CKAN failing to recognize newer mod version if preceding 'v' in version number is dropped

### ISSUE THREAD

**Issue by ShicKla** [KSP-CKAN/CKAN#850]
To clarify if a mod's version number in its .ckan file normally contained a 'v' preceding the version number, but then a newer release of the mod and .ckan file drops that preceding 'v', CKAN still sees the older version as newer because it has the preceding 'v'.

*Example*
When CKAN reads the .ckan file it sees `"version": "v0.5",` as higher version number then this `"version": "0.6",`

So what is happening is even though a mod author has updated their mod and the subsequent entry in the CKAN repository, CKAN is failing to see that there is an update and the end user is of course not aware of said update. Subsequently the end user would have to manually install the updated version of the mod or modify that mod's .ckan file accordingly.

**Comment by BlackSoldierB** [comment]
Duplicate of https://github.com/KSP-CKAN/CKAN-support/issues/133?

**Comment by ShicKla** [comment]
After reading KSP-CKAN/CKAN-support#133 I can confirm it is the same issue. I failed to notice this issue already being posted before due to KSP-CKAN/CKAN-support#133 title did not reflect the underlying issue.

**Closing this issue since it is duplicate of KSP-CKAN/CKAN-support#133**

**Comment by BlackSoldierB** [comment]
I will use your title, because it's more accurate.
