### ISSUE TITLE
Exporting modlist via GUI

### ISSUE THREAD

**Issue by janbrohl** [KSP-CKAN/CKAN#855]
Sharing a modlist as described on https://github.com/KSP-CKAN/CKAN-support/wiki/Sharing-a-modlist-%28metapackages%29 is simple but it would be cool if there was a button in the GUI to directly export "installed-default.ckan" to a custom-named file.

**Comment by savagerose** [comment]
@cwc actually just implemented this over here: https://github.com/KSP-CKAN/CKAN-GUI/issues/121 :)

**Comment by mgsdk** [comment]
Should be implemented in [1.6.17](https://github.com/KSP-CKAN/CKAN/releases/tag/v1.6.17), just released.
