### ISSUE TITLE
Issues with AutoDetected mod dlls

### ISSUE THREAD

**Issue by MDBenson** [KSP-CKAN/CKAN#861]
If an 'autodetected dll' mod is removed from the Gamedata folder it is not 'unflagged' in the GUI (may be intentional) and if 'Refresh' is clicked then CKAN closes abruptly and does not update the repos or it's view of the Gamedata folder.

**Comment by Dazpoet** [comment]
Sounds like you might have removed something that something else depended on. Could you elaborate on what you removed and what other mods you have installed?

**Comment by plague006** [comment]
It's been almost 2 months. I unassigned @Dazpoet to let this close gracefully as an unresolved support issue.
