### ISSUE TITLE
Error on launch - There is an error in XML Document

### ISSUE THREAD

**Issue by sosayscory** [KSP-CKAN/CKAN#863]
This is a screenshot of the error I recieve every time I try to start CKAN.

http://i.imgur.com/bwLWFlw.png

**Comment by mgsdk** [comment]
There is a file in the CKAN folder under your KSP directory called **GUISettings.xml**. Could you try to move it out of the folder temporarily and start CKAN again?

**Comment by sosayscory** [comment]
Thank you mgsdk, that solved the problem!
