### ISSUE TITLE
Have ci.ksp-ckan.org do fewer things

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#868]
Right now ci.ksp-ckan.org does too many things. If I understand things correct, it's:

1. The same as amsterdam.ksp-ckan.org (providing a mirror)
1. Running the netkan indexing bot
1. Running jenkins

We'd really like to separate all of these. I'd like to:

- [ ] Transfer any mirrored mods on amsterdam.ksp-ckan.org over to master.ksp-ckan.org if not already present (hooray for rsync). This will let us free a lot of space.
- [ ] Have the bot run entirely on the new AWS infrastructure on a dedicated host (@techman83 is already working on this). This will let us free even more space.
- [ ] Update our DNS so amsterdam becomes a CNAME for master
- Just have jenkins running on ci.ksp-ckan.org until we can port it over to a dedicated AWS machine.

Summoning @AlexanderDzhoganov for two easy questions:

1. Do you anticipate any issues in flipping amsterdam to be the same as master in the DNS, provided we merge the mirrors first?
1. Any chance I can get DNS access so I can do the flip? (I know you've tried on multiple occasions to set me up with this, so my apologies in having not accepted in the past!)

Many, many thanks!

~ pjf

**Comment by techman83** [comment]
We should consider using Route53. It'll make managing our DNS easier, delegate-able and will give us extra flexibility down the track.

**Comment by plague006** [comment]
Spoke with @techman83 on IRC, and with ci.ksp-ckan.org down for the foreseeable future it seems this can be closed.

**Comment by techman83** [comment]
Thanks @plague006 - yep it is most certainly doing less things (and all critical things are being done elsewhere).
