### ISSUE TITLE
Generate (and install?) a reduced changeset after failing to download a mod

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#873]
when installing a mod and for somereason the download fails this kills the install.  Now on a single mod this is not a big deal you just restart it and carry on.  But whn you have a whole list of mods checked this stops them all and you must go back and redo all of them.

So the idea is if a mod fails to DL rather than fail the install just retry it or ignore that one and do the rest of the list and then just fail that single mod.

**Comment by pjf** [comment]
I generally agree with this. If we fail to download a mod, we should:

* Remove it from the changeset
* Re-run our relationship resolver, removing any mods which now have their dependencies broken
* Repeat until we have a consistent changeset, or bail out if we run out of consistent mods.

and then either:

1. Continue with the install, OR
2. Return the user to the list of mods, but with the consistent changeset already ticked (so they can just hit "go" to continue with the install).
