### ISSUE TITLE
Support multiple profiles

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#875]
Another idea I just had.

You already support multiple KSP installs so we can run older versions etc....

However what about multiple "Configs" for a single "install"?  As in keep the mod list for a particular config as a text file that we can select from a list of saved configs.  This will wipe the current config's mods as if we had uninstalled them.  and then go in and reinstall all the mods for the new config.

I know this could be done by just having 2 KSP installs of the same version, but it would save on drive space.

**Comment by Dazpoet** [comment]
This can kind of be done already. You can save multiple metapackages and when switching between them you'd do

`ckan remove --re .*?`
`ckan install -c /path/to/metapackage`

Maybe some kind of GUI shortcut like "Change modlist" which lets you choose from a folder of metapackages you've exported earlier using https://github.com/KSP-CKAN/CKAN-GUI/pull/123 which performs the above operation.

The danger here would be if you load a save which e.g. expects you to have KWRocketry installed but in your other modlist you instead use SpaceY Launchers so when you load your save your entire fleet of ships using KW parts disintegrates.

**Comment by Bit-Fiddler** [comment]
not quite what I was talking about...   I am talking about the "downloads" folder specifically.  I have several installs of KSP running but all of them have individual "download" folders each of these folders have 90% the same mods downloaded to them.  this makes me use 4 or 5 times the amount of drive space for my "download" folders.  I was just looking for a way to combine them to one central CKAN "download" folder.  purely to reduce HDD space used by CKAN.

**Comment by politas** [comment]
@Bit-Fiddler , #584 is the issue you want to be looking at for that. There's a description of how to share downloads between KSP installs in the discussion there. Also, I am currently working on adding a way to set the download location specifically.

**Comment by Olympic1** [comment]
I think this is resolved by #2535 as this is about a central download cache
