### ISSUE TITLE
Mirror FOSS mods to S3, allow clients to fallback to mirror

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#935]
We have a buttload of infrastructure available to us. We should:
- [ ] Mirror mods to S3 when the license permits. We already have MirrorKAN doing the equivalent of this, but S3 means less maintenance, and no need to expose a machine to the outside world.
- [ ] Have clients automatically fall back on this mirror if they have problems fetching the mod due to github throttling, websites being down, or other interruptions.
- [ ] Make sure the user can configure this, but have it default to enabled.

The client doesn't need to know the S3 URLs in advance, it can calculate them from the download URLs the same way we calculate cache hashes.

**Comment by politas** [comment]
Covered by #1682
