### ISSUE TITLE
Enhanced Navball and 1.0.2 compatibility

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#936]
Enhanced Navball has not been updated to show 1.0.2 on the webpage, but it has been confirmed to work on the forums....  does this mean it will not be added to CKAN for 1.0.2 until it is updated by the author?  or does the community confirmation suffice?

**Comment by Dazpoet** [comment]
It depends, can you link the appropriate parts f the forum thread discussing 1.0.2 compatibility? Are there any, no matter how small, issues with the mod in 1.0.2 we should consider?

Mods have been bumped before for varians reasons and even with minor errors in them so we need to evalute and then decide based on that :)
