### ISSUE TITLE
Active Texture Management Bugs

### ISSUE THREAD

**Issue by nmk456** [KSP-CKAN/CKAN#939]
I was trying to install ATM through CKAN and I'm getting some errors:

    The following inconsistencies were found: ActiveTextureManagement-x86-Aggressive conflicts with ActiveTextureManagement-x64-Aggressive. * ActiveTextureManagement-x64-Aggressive conflicts with ActiveTextureManagement-x86-Aggressive.

Is this a CKAN bug? Or am I missing an obvious problem with my client? Thanks in advance.

**Comment by Dazpoet** [comment]
It would appear that CKAN thinks you already have ATM installed and/or there's some faulty logic somewhere in the NetKAN files.

What version of ATM where you trying to install? What version of KSP are you using and what is the output of `ckan list --porcelain`?

**Comment by nmk456** [comment]
It shows this:

    X ActiveTextureMamagement-x64-Aggressive 4-3
    - <All my other installed mods>

**Comment by Dazpoet** [comment]
Are you running KSP 1.0.x ?

**Comment by nmk456** [comment]
1.0

**Comment by nmk456** [comment]
Now it crashes every time I click the checkbox next to ATM.

**Comment by nmk456** [comment]
And only ATM.

**Comment by Dazpoet** [comment]
Ah your installed version of ATM is not compatible with your installed version of ATM, probably due to some problems we had with ATM metadata early on. I recommend you do a `ckan remove ActiveTextureManagement-x64-Aggressive` and try again after doing either a `ckan update` or a Refresh in the GUI.

**Comment by nmk456** [comment]
It works now! Thanks!!

**Comment by Dazpoet** [comment]
Nice :) Then I'll close this issue.
