### ISSUE TITLE
Side panel does not respond to shrinking

### ISSUE THREAD

**Issue by ChucklesTheBeard** [KSP-CKAN/CKAN#940]
http://imgur.com/8Ms0yNY,dfHc6Ew

Description text runs off to the right side of the screen, it should wrap around. Note that it does respond as expected to expanding.

Linux 4.0.3-1-ARCH
xorg-server 1.17.1-5
Mono JIT compiler version 4.0.1
ckan-git v1.6.16.r7.g64c2f76 (that is, CKAN built based on the commit tagged 1.6.16 plus 7 commits - 64c2f76)

**Comment by politas** [comment]
I can confirm the same behaviour on Ubuntu 14.04, also running Mono JIT compiler version 4.0.1 and CKAN v1.6.16-0-g0000000 (beta)

**Comment by Postremus** [comment]
Closing as this is fixed in current master.

**Comment by plague006** [comment]
I think @Postremus misclicked and didn't hit "Close and comment". =)
