### ISSUE TITLE
CKAN no longer finds default Steam install under Linux

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#941]
As reported in #894 and elsewhere, the CKAN client is no longer discovering the default Steam install under Linux.

We sure *used* to do this, so at some point we've regressed somewhere.

**Comment by ChucklesTheBeard** [comment]
Confirmed:
( rm -rf ~/.mono/registry/CurrentUser/software/ckan to delete the registry entry)


Linux 4.0.4-2-ARCH #1 SMP PREEMPT x86_64 GNU/Linux
Mono JIT compiler version 4.0.1
CKAN 1.6.17 dev build (master commit e28764b, installed via AUR git package (runs `CKAN/bin/ckan-build.py`))

```
$ ckan gui --debug
119 [1] INFO CKAN.CmdLine.MainClass (null) - Debug logging enabled
136 [1] DEBUG CKAN.KSPManager (null) - Loading KSP instances from registry
141 [1] DEBUG CKAN.KSP (null) - Checking if KSP is in my exe dir: /usr/bin
141 [1] DEBUG CKAN.KSP (null) - Cannot find GameData in /usr/bin
I don't know where KSP is installed.
Use 'ckan ksp help' for assistance on setting this.
```
