### ISSUE TITLE
REQUEST: Move downloads as they complete

### ISSUE THREAD

**Issue by 7ranceaddic7** [KSP-CKAN/CKAN#957]
Okay, so I have only one major problem with CKAN.  When a number of mods are selected for downloading, CKAN will create and download to tmp########.tmp files.  Unfortunately, if something should go awry with the process all progress is lost and all downloads MUST be re-initiated.

It would be nice to have CKAN immediately transfer a completed download to .../CKAN/downloads.  This would benefit of:

1. securing progress for those with slow or unreliable connections (and off-chance interruptions).
2. reduce repeat load on servers servicing those downloads.
3. speed up the process of installing numerous mods.

Just a thought.

**Comment by Dazpoet** [comment]
Can you give reproduction steps? When my downloads fail midway through, CKAN keeps all the completed downloads in the cache.

**Comment by pjf** [comment]
Aye. We *should* already be doing this, so if we're not, that's a bug.

We don't keep *partial* downloads, the client isn't smart enough to restart them, but completed downloads should definitely be kept.

Reproduction steps would be grand. :)

**Comment by 7ranceaddic7** [comment]
Reproduction Steps:

1. clear temp directory (rm tmp*)
2. clear CKAN download directory of all "Contract Packs", "ScanSat", "Spacetux", "KerbinSide", "Kerbal Konstructs", "RemoteTech"
3. select all "Contract Packs" only; 'Go To Changes'; 'Apply'
4. prepare to interrupt internet connection.
4. select suggested mods and 'Continue'
5. interrupt download by disconnecting from internet. (to ensure verifiability wait for 50-75% download before disconnecting)

Temp files can be verified in the temp directory as being started.  If disconnection occurs before full download completes, only some tmp########.tmp files can be opened.  Others will error out.  Check CKAN download directory for file retention.

6. turn on internet connection before attempting to do any thing else.

**Comment by pjf** [comment]
@7ranceaddic7 : Thank you! Just to check, what's your OS and CKAN version? (The code we use to do downloads varies based upon these two factors, so I'm wondering if we've hit a regression somewhere...)

**Comment by 7ranceaddic7** [comment]
Linux 3.19.0-18-generic Ubuntu x86_64
CKAN v1.6.16-0-g0000000 (beta)

**Comment by 7ranceaddic7** [comment]
FYI, I've downloaded the master and built it through Monodevelop.

This functionality now works properly.

**Comment by pjf** [comment]
> This functionality now works properly.

Hooray! That means it should be working in our release as well, so I'm marking this closed with relief. :)
