### ISSUE TITLE
CKAN Won't Upgrade Mods

### ISSUE THREAD

**Issue by wpeng730** [KSP-CKAN/CKAN#958]
Whenever I try to update a mod, CKAN always pauses either right after the "Downloading" part if the mod isn't already downloaded or right after "Done!" (after "Removing:") when the mod already is. So, it won't upgrade anything. The mods in question are RasterPropMonitor Core and Scatterer. I'm using CKAN v1.6.16-0-g0000000 on Ubuntu 15.04.

**Comment by Dazpoet** [comment]
Is your KSP by any chance in a hidden folder or a folder with strict write priviliges?

What version of the mods do you have installed and which versions are you attempting to upgrade to? What version of KSP are you using?

**Comment by wpeng730** [comment]
I completely reinstalled CKAN, and that fixed the issue. But if you really want to know, KSP is not in a protected or hidden folder, I don't know which mod version was being upgraded, and I am on KSP 1.0.2
