### ISSUE TITLE
Core and clients should support multiple licenses.

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#966]
Split from #22.

> Multiple licence information should be presented to users in the CKAN client, and NetKAN should support multiple licences. — @politas

The spec agrees with this strongly since at least 3a311bb1, which pre-dates the existence of #22, and much of the CKAN codebase.
- https://github.com/KSP-CKAN/CKAN/blob/master/Spec.md#license
- ~~https://github.com/KSP-CKAN/CKAN/blob/master/CKAN.schema#L67-L69~~
  https://github.com/KSP-CKAN/CKAN/blob/c9a871e0e586984331fc1f5cf8e53e54c58e7c2f/CKAN.schema#L85-L88
  https://github.com/KSP-CKAN/CKAN/blob/c9a871e0e586984331fc1f5cf8e53e54c58e7c2f/CKAN.schema#L405-L415

These should only be used when the _whole mod_ is multi-licensed. (Eg: GPL or Artistic, which is common in the Perl community.)

**Comment by politas** [comment]
[QUOTE] If different assets in the mod have different licenses, the most restrictive license should be specified, which may be restricted.[/QUOTE] 
So if if a mod contains models under CC-BY-NC-SA and a dll under GPL, it's better to say "restricted" than to list both licences? What was the reasoning behind that?

**Comment by HebaruSan** [comment]
I think this was done in KSP-CKAN/CKAN#1132. `CkanModule.License` is a `List<License>` and includes a `JsonConverter` to handle a single value or an array.
