### ISSUE TITLE
Selecting new mod doesn't update settings GUI

### ISSUE THREAD

**Issue by Kemp-J** [KSP-CKAN/CKAN#967]
After choosing a new KSP install, the settings GUI continues to show the previous one as the currently selected one until it is closed and reopened. The main window titlebar updates immediately as expected.

**Comment by mgsdk** [comment]
In 1.6.17 the GUI client no longer restarts when changing instance, but it should still switch metadata, mods etc. Does the installed mods not change when you change KSP install?

**Comment by Kemp-J** [comment]
As far as I can tell, everything changes over as it should do except for the install directory named in the settings dialog. This isn't refreshed until the dialog is closed and reopened. This is potentially confusing for the user as it doesn't appear that the new install directory was actually selected.

**Comment by mgsdk** [comment]
This should fix part of the issue, though it would probably be a good idea to somehow convey to the user that all the settings are reloading as you suggest.

https://github.com/KSP-CKAN/CKAN-GUI/pull/135

**Comment by Kemp-J** [comment]
Beyond changing the KSP install shown in the dialog I'm not sure there needs to be further indication. Clicking Apply and having that label match what the users is expecting to see would be enough for me.

Disclaimer: entirely from my own point of view, and I'm not a UI expert of any kind :)

**Comment by mgsdk** [comment]
There is just a slight stutter while everything reloads. Before, you would not see any windows so you had an idea _something_ was going on. So it is more of a suggestion to add a dialog box or something along those lines, but it may be overkill.

**Comment by mgsdk** [comment]
The settings dialog should be fixed in the next release, the code has been merged in now.
