### ISSUE TITLE
Better health reporting on mod indexing.

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#969]
This is very much a "grand scheme" ticket, but it wold be really nice to have better reporting on mod indexing. Not just a log from our netkan-bot, but an actual nagios-style display of what's working, and what's not. If we fail to index a mod (eg, because it's missing) then a light goes red. If a mod is indexed but looks weird (eg: the latest version compares to be older than an existing version) we can flip things to a warning.

Such a display would not only allow users to check when a mod was last indexed, and the health of its metadata, but also could alert developers if something goes awry.

My sysadmin side thinks [nagios](https://www.nagios.org/) would be a pretty cool choice here, but I've not used it in anger for many years.

**Comment by techman83** [comment]
Nagios/Centreon can do things, but likely overkill and a lot of work to setup (though it is really easy to write custom checkers for it). I have some ideas over at KSP-CKAN/NetKAN-bot#7
