### ISSUE TITLE
Exported mods should not include "provided" relations

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#971]
Right now, exporting mods and `installed-default.ckan` lists "provided" mods, as well as real mods.

We shouldn't be listing "provided" mods, and I'm surprised it's not causing more trouble. Provided mods aren't real, and the purpose of the export function is to provide a genuine manifest.

**Comment by Dazpoet** [comment]
duplicate of #912?

**Comment by pjf** [comment]
@Dazpoet : You bet it is! I thought it felt familiar somehow. :)

(Closing with thanks!)
