### ISSUE TITLE
Mod Conflict

### ISSUE THREAD

**Issue by Bit-Fiddler** [KSP-CKAN/CKAN#974]
About to remove:

Done!

About to install...

 * OPTSpacePlaneParts V1.6.9.1 (cached)
 * OrbitalSurveyPlus 1.2 (cached)
 * PersistentRotation 0.5.3 (cached)
 * ProceduralParts v1.1.2 (cached)
 * QuantumStrutsContinued 1.3 (cached)
 * QuickBrake v1.00 (cached)
 * QuickSearch v1.12 (cached)
 * QuickStart v1.01 (cached)
 * QuizTechAeroPack v1.2.7 (cached)
 * Workshop 0.7.2 (cached)
 * ModuleRCSFX v4.1 (cached)

Oh no! We tried to overwrite a file owned by another mod!
Please try a `ckan update` and try again.

If this problem re-occurs, then it maybe a packaging bug.
Please report it at:

https://github.com/KSP-CKAN/CKAN-meta/issues/new

Please including the following information in your report:

File           : GameData/OPT/Parts/mk3_cockpit/mk3_cockpit.cfg
Installing Mod : OPTSpacePlaneParts V1.6.9.1
Owning Mod     : Mk3MiniExpansionPack
CKAN Version   : v1.6.17-0-g0000000 (beta)

Your GameData has been returned to its original state.

Error!

**Comment by Dazpoet** [comment]
Are you running KSP 0.90 by any chance? This problem should be confined to there.

**Comment by plague006** [comment]
It's been 3 months without a reply, I'm unassigning @Dazpoet and will let the bot close this in 1 week as an unresolved support ticket.

**Comment by plague006** [comment]
If this was under KSP 1.0.2 then KSP-CKAN/CKAN-meta#710 resolves this. If this was under 0.90.0 then KSP-CKAN/NetKAN#1087 solves this. Either way, closing this now, if anyone has more to add I'll happily reopen.
