### ISSUE TITLE
CKAN GUI no longer gives choices of dependencies (TACLS)

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#976]
Somewhere in the last few releases the GUI stopped giving the user a choice between mods to install.

### Steps to reproduce:

- Start with a fresh v0.90 install
- Download CKAN v1.6.18 or above.
- Tick the TACLS mod in the GUI.

### What should (and used to) happen:

- The GUI should ask if you want stock or reaismoverhaul configs, just like the cmdline does.

### What does happen:

- No changeset appears. The user can manually select a config, but they have to know that's required.

### Relevant tickets (feel free to add to):

- KSP-CKAN/CKAN-core#141

**Comment by RichardLake** [comment]
Can someone confirm that it used to ask the user as soon as tacls was selected? I thought it was during the install process.

**Comment by Dazpoet** [comment]
Just tried with CKAN 1.6.2 and I was prompted during the install process. The process was:

1) choose TAC-LS
2) Click apply in changeset tab
3) browse suggested mods since TAC-LS suggests KSP-AVC
4) click continue
5) get prompted about which Config I want to install

**Comment by RichardLake** [comment]
Solution needs testing at https://github.com/KSP-CKAN/CKAN-GUI/pull/137
