### ISSUE TITLE
NetKarmgeddon - Massive Purge of CKAN metadata and scripts

### ISSUE THREAD

**Issue by dbent** [KSP-CKAN/CKAN#979]
netkan-bot has decided to make a whole bunch of [commits](https://github.com/KSP-CKAN/CKAN-meta/commits/master?author=netkan-bot) deleting metadata and scripts for the CKAN-meta repository.

This is less than ideal.

**Comment by dbent** [comment]
FYI, the first commit of the purge is KSP-CKAN/CKAN-meta@bb5480d18d47dc34b041fbfc732413a5b3e466b1, basically going in alphabetical order of the file names.

**Comment by ttencate** [comment]
That explains why I'm only seeing mods from P onwards...

**Comment by dbent** [comment]
This should generate a patch to revert the changes:
```
git diff 95cbf5e867c021ed3ec1483eee447218bb089e6b 3bdad4cb7709663284b0d0269e4611b1e618e9c6 > netkarmgeddon-revert.patch
```
KSP-CKAN/CKAN@95cbf5e867c021ed3ec1483eee447218bb089e6b is the last bad commit made by netkan-bot and KSP-CKAN/CKAN@3bdad4cb7709663284b0d0269e4611b1e618e9c6 should be the commit just prior to the first bad commit made by netkan-bot. Running the command generates a 6,296KB patch file on my machine.

**Comment by Dazpoet** [comment]
Seems the bot is now recreating a bunch of the things it removed but only the latest versions so all older versions of mods are not indexed.

**Comment by CecilFF4** [comment]
Turned on CKAN this afternoon and found only 38 of my 64 mods are present in the list. Thought I'd post the mods that are gone at the moment, in case it helps anyone troubleshoot or repair the issue:

AGroupOnStage-2.0.7a.zip
AstronomersPack-Interstellar.V2.zip
DiverseKerbalHeads-1.0.zip
DockingPortAlignmentIndicator-6.2.zip
FerramAerospaceResearch-v0.15.2_Ferri.zip
FMRS-1.0.00.zip
Fusebox-1.31.zip
KAS-0.5.1.zip
KIS-1.1.4.zip
MechJeb2-2.5.1.zip
MechJebForAll-1.2.0.0.zip
MenuStabilizer-1.zip
ModularFlightIntegrator-1.0.zip
ModuleAnimateEmissive-v1.0.zip
ModuleManager-2.6.5.zip
OrbitalSurveyPlus-1.2.zip
PorkjetHabitats-0.4.zip
PreciseNode-1.1.3.zip
QuickHide-v3.01.zip
RasterPropMonitor-v0.19.4.zip
RCSLandAid-2.4.zip
RealChute-1.3.2.3.zip
Toolbar-1.7.9.zip
TweakScale-v2.1.zip
VesselView-0.71.zip
xScience-4.4.zip

**Comment by Dazpoet** [comment]
I'm holding off merging https://github.com/KSP-CKAN/CKAN-meta/pull/560 for now until someone who can at least check the new netkan-bot logs have taken a look so we don't end up with the same situation happening again.

**Comment by pjf** [comment]
Attentioning @techman83 on this.

It's 04:30 here, so I'll likely be doing the minimum required to stop the bot doing whatever it's doing (which is likely disabling it), and then reverting CKAN-meta back to where it was.

**Comment by pjf** [comment]
Steps taken:

1. Logged into ckan-bot on aws
2. Sudo'ed to netkan, commented out job in crontab file
3. killed all of netkan's processes which were running

I haven't revoked the bot's token, but I anticipate it staying dead.

**Comment by pjf** [comment]
I can see commits by both `Netkan inflator Robot` with GMT+0 timestamps, and `NetKAN bot` with GMT+2 timestamps, indicating that both the old an the new indexers may have been running at the same time.  See around bb5480d18d47dc34b041fbfc732413a5b3e466b1 for an example.

**Comment by pjf** [comment]
Apparently there have been 3061 commits since I went to bed last night. While it will cause some distress for anyone who's pulled CKAN-meta in the last few hours, I'm going to revert master. I'll leave the commits on a side-branch for forensics.

**Comment by pjf** [comment]
Current master is now on `netkangeddon_forensics`

**Comment by pjf** [comment]
Investigating reset to 3bdad4cb7709663284b0d0269e4611b1e618e9c6 , checking for commits after that time by innocent humans.

**Comment by pjf** [comment]
No innocent humans. Initiating reset.

**Comment by pjf** [comment]
### I've force-pushed to CKAN-meta

Doing a `git pull` may give you a message that is git's way of saying that *time went backwards*, and it doesn't expect that. If you don't get any errors or warnings when pulling, *then you do not need to follow the steps below*.

You can do the following to restore normality in your local timeline, **but first use `git status` to make sure you have no uncommited files**. If you do, then stash them, commit them to a branch, or back them up first.

```
git checkout master
git fetch upstream
get reset --hard upstream/master
```

**This assumes your remote pointing to KSP-CKAN/CKAN-meta is called `upstream`. If it's called `origin`, then place all instances of `upstream` with `origin`:**

```
git checkout master
git fetch origin
get reset --hard origin/master
```

These three steps:

1. Make sure you're on the right branch
2. Fetch the state of the remote repo, without changing your own
3. Resets your state to match the remote state.

**This will overwrite any uncommited files you have present**.

**Comment by pjf** [comment]
And I'm now going back to bed (5am here). I'll be taking a look at this in the morning to try and figure out what happened.

**Comment by techman83** [comment]
Gah, I didn't get the resilience work finished in time! I guess see what's happened though. If 2 were running at the same time the 2nd bot would have wiped the metadata as the first bot finished and committed what it thought was the change set. (Likely it also had some file locks which probably made the rmtree barf and why it only removed half of them).

I was thinking the other day I should add Sys::RunAlone! I think also Time::Limit could help here. When I get some breakfast and coffee in my head I'll make those changes.

Really sorry everyone!

**Comment by techman83** [comment]
Tracking in KSP-CKAN/NetKAN-bot#8

**Comment by techman83** [comment]
Ok, looking at the log file at around 7am May 29 UTC - the index started taking longer than 18 minutes to complete (it's pretty consistent) - we can use this ckan which is failing validation as a check point:

7am
```
[Fri May 29 07:27:22 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:30695 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
8am
```
[Fri May 29 08:35:55 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:2301 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
9am
```
[Fri May 29 09:41:12 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:6296 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
10am
```
[Fri May 29 10:47:33 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:10400 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
11am
```
[Fri May 29 11:52:03 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:14468 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
12pm
```
[Fri May 29 12:58:44 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:18546 (WARN) Failed to Parse Protractor/Protractor-v2.5.1.ckan
```
Start of the bad things
```
[Fri May 29 15:06:36 2015] /home/netkan/NetKAN-bot/bin/netkan-indexer:26579 (INFO) Commiting A6Intruder/A6Intruder-3.ckan
```

So at 3pm May 29 UTC is when it all went pair shaped. The 1pm indexer finally finished at 3pm (which at that point there were likely 3 running). As the indexer cleans out the meta data between runs we likely hit what I described earlier with a file lock preventing the rmtree from removing all the files, leaving the metadata half purged which the bot promptly committed and pushed all the changes.

I will add 'Sys::RunAlone' which will prevent the script running twice and likely 'Time::Limit' - because if the run is taking too long there is obviously something wrong and we should terminate and try again later.

I am in the process of making the bot smarter and more efficient (only about 10% done); this script was hacked together as a stop gap to alleviate the Jenkins host from constantly running out of space.

**Comment by techman83** [comment]
Gist of the relevant part of the log file here -> https://gist.github.com/techman83/943697cfbeeb156903ab

**Comment by pjf** [comment]
@techman83 : Awesome investigative work! So the fault we've seen is consistent with two bots running at once? That's excellent news, and your fixes look great.

As an extra layer, I've noticed the bot currently uses `git add -A`, which also allows for the deletion of files. As far as I know, the indexer should never be *deleting* anything. Do you think we can safely change this to `git add .`, which allows for the addition and modification of files, but *not* their deletion. (This should make it even harder for the bot to remove things if *something else* manages to damage its working area while it's running.)

**Comment by Dazpoet** [comment]
Ugh why is it failing on my protractor file?

**Comment by techman83** [comment]
It's too do with the version number from memory.

**Comment by pjf** [comment]
Since we've recovered from the bug, and have measures in place to prevent it happening in future, I'm joyously marking this as complete! :)
