### ISSUE TITLE
Jenkins vs Travis?

### ISSUE THREAD

**Issue by pjf** [KSP-CKAN/CKAN#990]
Up until the end of 2014, we used travis for continuous integration and testing. At the start of 2015 a jenkins server was commissioned to replace it.

I'd like to assess whether we want to move back to travis for our CI needs, and would _really_ love feedback here. I know that I'm very experienced in using travis, so that gives me a huge bias towards its use, as it's the easiest system for me to work with.

I can spot the following advantages for each system:
## Travis
- No need to maintain own servers (running out of disk space, applying security patches, etc etc)
- Configuration entirely controlled form git.
- Can test on [multiple versions of mono](http://docs.travis-ci.com/user/languages/csharp/)
- Makes deploying new releases is super-easy
## Jenkins
- All the flexibility we could ever need.
- In theory we could use a local cache of mods for metadata testing, but we don't.
## Both systems:
- Can easily store build artefacts, to test nightlies or PRs more easily.
- Have special support for handling nunit test output.

For code tests, it would be _very_ straightforward to replace jenkins with travis, and we'd get the bonus of being able to test code across multiple mono releases as part of the deal.

I'm looking for arguments for either system, both for and against. Input from @hakan42 and @AlexanderDzhoganov especially appreciated, as they set up the original jenkins instance.

I'm still investigating what the pre-release inflators on jenkins are doing, as I'm not personally familiar with them myself.

**Comment by hakan42** [comment]
The pre-release jobs do just what it says on the tin, fetch not yet released versions from either github or @sarbian jenkins and push then into the CKAN-meta-dev repository.

Should be also pretty easy to move over to travis if you would provide an example on how to run netkan over there and how to mask passwords for read-write repositories. I am much more experienced with Jenkins :smile:

**Comment by pjf** [comment]
@hakan42 : The joys of having a diverse range of developers on a project! :D

My plan for the moment is to enable travis for releases (see #1000), because being able to do that with a single button press is a pretty killer feature for me.

Where's the code for the pre-release jobs live? Are they just in jenkins, or do they have a github repo as well?

**Comment by Postremus** [comment]
Maybe usw booth. Travis for releases, because of one click. Jenkins for fev builds, because its is faster?

----- Ursprüngliche Nachricht -----
Von: "Paul Fenwick" <notifications@github.com>
Gesendet: ‎31.‎05.‎2015 10:20
An: "KSP-CKAN/CKAN" <CKAN@noreply.github.com>
Betreff: Re: [CKAN] Jenkins vs Travis? (#990)

@hakan42 : The joys of having a diverse range of developers on a project! :D
My plan for the moment is to enable travis for releases (see #1000), because being able to do that with a single button press is a pretty killer feature for me.
Where's the code for the pre-release jobs live? Are they just in jenkins, or do they have a github repo as well?

**Comment by hakan42** [comment]
@pjf the code for the pre-release jobs is in the Jenkins configuration. They are all identical (or should be) and read just the branch name from the "Parameter" of the job. Everything else is a stripped-down copy of the build.sh from the main netkan-bot script.

**Comment by HebaruSan** [comment]
The answer appears to have been Travis for building the app (until #2994), Jenkins for validating metadata. That combo has been working really well except for Travis's tendency to fail builds spuriously, but you can just log in and restart them.

If further choices are made about this, it probably won't be as a result of this conversation.
