### ISSUE TITLE
Ability to point the CKAN autoupdater to CKAN-nightlies rather than releases

### ISSUE THREAD

**Issue by Dazpoet** [KSP-CKAN/CKAN#997]
rabble rabble bleeding edge rabble rabble cooler than release rabble rabble hipster rabble rabble

On a much more serious note though sometimes we get errors reported that are hotfixed in the code (mono 4 incompatible gui comes to mind) and leads to a nightly release but the real release might be anywhere from a few hours to a few days away due to a number of reasons.

In times like these one could point users to a nigthly release and ask them to install that but upon running a nightly the user is always prompted by the autoupdater to update to the latest official version, presumably due to < logic >.

Being able to point a user to a guisetting/cli command which switched the autoupdater over to nightlies could be helpful in those situations. I'd hope that such a change would prompt the user that the change  they're doing switches them over to bleeding-edge with all the potential unstability which might come out of such a thing.

**Comment by HebaruSan** [comment]
As of #3197 APT (.deb) users can set up their OS to install "nightly" builds.
Nothing equivalent for other OSes yet.
